import type { FrontendDrillProblem } from '../types';

export const angularProblems: FrontendDrillProblem[] = [
  {
    id: 'fe-ng-component-decorator',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: 'Component Decorator',
    text: 'Write an Angular @Component decorator with selector "app-hello" and a template containing "<h1>Hello World</h1>".',
    setup: 'Write the full @Component({...}) decorator call.',
    setupCode: `const componentConfig = {};`,
    expected: '@Component decorator with selector and template',
    sample: `@Component({
  selector: 'app-hello',
  template: '<h1>Hello World</h1>'
})`,
    validPatterns: [
      /@Component\s*\(\s*\{[^}]*selector\s*:\s*['"]app-hello['"][^}]*template\s*:/,
      /@Component\s*\(\s*\{[^}]*template\s*:[^}]*selector\s*:\s*['"]app-hello['"]/,
    ],
    hints: ['Use @Component({...}) with selector and template properties'],
    tags: ['decorator', 'component'],
  },
  {
    id: 'fe-ng-event-binding',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'easy',
    title: 'Event Binding',
    text: 'Write an Angular template: a <button> with text "Click Me" that calls handleClick() on click using (click) event binding.',
    setup: 'Write the full HTML template string with Angular event binding syntax.',
    setupCode: `const template = '';`,
    expected: 'Template with (click) event binding',
    sample: `<button (click)="handleClick()">Click Me</button>`,
    validPatterns: [/<button[^>]*\(click\)\s*=\s*["']handleClick\(\)["'][^>]*>/],
    hints: ['Use Angular event binding syntax: (eventName)="handler()"'],
    editorLanguage: 'html',
    tags: ['events', 'template'],
  },
  {
    id: 'fe-ng-input-decorator',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'easy',
    title: '@Input Decorator',
    text: 'Declare a property "name" of type string with the @Input() decorator to accept data from a parent component.',
    setup: 'Write the decorated property declaration: @Input() name: string;',
    setupCode: `class MyComponent {}`,
    expected: '@Input decorated property',
    sample: `@Input() name: string;`,
    validPatterns: [/@Input\s*\(\s*\)\s+name\s*:\s*string/, /@Input\s*\(\s*\)\s+name\s*[;:]/],
    hints: ['Use @Input() decorator before the property'],
    tags: ['input', 'decorator', 'props'],
  },
  {
    id: 'fe-ng-output-eventemitter',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'medium',
    title: '@Output and EventEmitter',
    text: 'Create an @Output() property "notify" initialized as a new EventEmitter<string>().',
    setup: 'Write the full decorated property: @Output() notify = new EventEmitter<string>();',
    setupCode: `class MyComponent {}`,
    expected: '@Output with EventEmitter<string>',
    sample: `@Output() notify = new EventEmitter<string>();`,
    validPatterns: [
      /@Output\s*\(\s*\)\s+notify\s*=\s*new\s+EventEmitter\s*<\s*string\s*>\s*\(\s*\)/,
      /@Output\s*\(\s*\)\s+notify:\s*EventEmitter<string>\s*=\s*new\s+EventEmitter/,
    ],
    hints: ['Use @Output() with new EventEmitter<T>()'],
    tags: ['output', 'events', 'eventemitter'],
  },
  {
    id: 'fe-ng-ngfor-directive',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: '*ngFor Directive',
    text: 'Write an Angular template: a <li> element with *ngFor="let item of items" that displays each item using {{ item }} interpolation.',
    setup: 'Write the full <li> element with *ngFor directive and interpolation.',
    setupCode: `const items = ['apple', 'banana', 'cherry'];`,
    expected: 'Template with *ngFor loop',
    sample: `<li *ngFor="let item of items">{{ item }}</li>`,
    validPatterns: [/<li[^>]*\*ngFor\s*=\s*["']let\s+\w+\s+of\s+items["'][^>]*>/],
    hints: ['Use *ngFor="let item of items" syntax'],
    editorLanguage: 'html',
    tags: ['ngfor', 'loops', 'template'],
  },
  {
    id: 'fe-ng-ngif-directive',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: '*ngIf Directive',
    text: 'Write an Angular template: a <p> element with *ngIf="isVisible" that shows any text content (e.g. "I am visible!").',
    setup: 'Write the full <p> element with *ngIf directive.',
    setupCode: `const isVisible = true;`,
    expected: 'Template with *ngIf',
    sample: `<p *ngIf="isVisible">I am visible!</p>`,
    validPatterns: [/<p[^>]*\*ngIf\s*=\s*["']isVisible["'][^>]*>/],
    hints: ['Use *ngIf="condition" on the element'],
    editorLanguage: 'html',
    tags: ['ngif', 'conditional', 'template'],
  },
  {
    id: 'fe-ng-service-injectable',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: '@Injectable Decorator',
    text: 'Write an @Injectable({ providedIn: \'root\' }) decorator followed by the class declaration "class DataService {}".',
    setup: 'Write the full @Injectable decorator and class declaration.',
    setupCode: `class DataService {}`,
    expected: '@Injectable service with providedIn: root',
    sample: `@Injectable({
  providedIn: 'root'
})
class DataService {}`,
    validPatterns: [/@Injectable\s*\(\s*\{[^}]*providedIn\s*:\s*['"]root['"]/],
    hints: ["Use @Injectable({ providedIn: 'root' })"],
    tags: ['injectable', 'service', 'di'],
  },
  {
    id: 'fe-ng-ngoninit-lifecycle',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'easy',
    title: 'ngOnInit Lifecycle',
    text: "Write an ngOnInit() method body that calls console.log('Component initialized').",
    setup: 'Write the full ngOnInit() { ... } method implementation.',
    setupCode: `class MyComponent {}`,
    expected: 'ngOnInit method implementation',
    sample: `ngOnInit() {
  console.log('Component initialized');
}`,
    validPatterns: [
      /ngOnInit\s*\(\s*\)\s*\{[^}]*console\.log/,
      /ngOnInit\s*\(\s*\)\s*:\s*void\s*\{/,
    ],
    hints: ['Implement ngOnInit() { ... } method'],
    tags: ['lifecycle', 'hooks', 'ngoninit'],
  },
  {
    id: 'fe-ng-httpclient-get',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'medium',
    title: 'HttpClient GET Request',
    text: 'Call http.get(\'/api/users\') and chain .subscribe() with a callback that logs the data. The "http" object is already available.',
    setup: 'Write http.get(url).subscribe(callback).',
    setupCode: `const http = { get: (url: string) => ({ subscribe: (fn: any) => fn([]) }) };`,
    expected: 'http.get() with subscribe',
    sample: `http.get('/api/users').subscribe(data => {
  console.log(data);
});`,
    validPatterns: [/http\.get\s*\(\s*['"]\/api\/users['"]\s*\)\.subscribe/],
    hints: ['Use http.get(url).subscribe(...)'],
    tags: ['http', 'httpclient', 'api'],
  },
  {
    id: 'fe-ng-rxjs-pipe-map',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'RxJS pipe and map',
    text: 'Call source$.pipe(map(x => x * 2)) to double each emitted value. Both "source$" and "map" are already available.',
    setup: 'Write the source$.pipe(map(...)) expression.',
    setupCode: `const source$ = { pipe: (...args: any[]) => source$ };
const map = (fn: any) => fn;`,
    expected: 'pipe() with map() operator',
    sample: `source$.pipe(
  map(x => x * 2)
)`,
    validPatterns: [
      /source\$\.pipe\s*\(\s*map\s*\(/,
      /\.pipe\s*\([^)]*map\s*\([^)]*=>\s*[^)]*\*\s*2/,
    ],
    hints: ['Use source$.pipe(map(value => value * 2))'],
    tags: ['rxjs', 'observable', 'pipe', 'map'],
  },
  {
    id: 'fe-ng-two-way-binding',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'easy',
    title: 'Two-Way Binding',
    text: 'Write an Angular template: an <input> element with [(ngModel)]="username" for two-way data binding.',
    setup: 'Write the full <input> element with banana-in-a-box syntax.',
    setupCode: `const username = '';`,
    expected: 'Input with [(ngModel)]',
    sample: `<input [(ngModel)]="username" />`,
    validPatterns: [/<input[^>]*\[\(ngModel\)\]\s*=\s*["']username["'][^>]*>/],
    hints: ['Use [(ngModel)]="propertyName" for two-way binding'],
    editorLanguage: 'html',
    tags: ['ngmodel', 'forms', 'two-way'],
  },
  {
    id: 'fe-ng-formcontrol',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'medium',
    title: 'Reactive FormControl',
    text: 'Declare a const "emailControl" assigned to new FormControl(\'\') with an empty string as the initial value.',
    setup: "Write: const emailControl = new FormControl('');",
    setupCode: `const FormControl = class { constructor(value: any) {} };`,
    expected: 'new FormControl with initial value',
    sample: `const emailControl = new FormControl('');`,
    validPatterns: [
      /const\s+emailControl\s*=\s*new\s+FormControl\s*\(/,
      /emailControl\s*=\s*new\s+FormControl\s*\(\s*['"]{2}\s*\)/,
    ],
    hints: ['Use new FormControl(initialValue)'],
    tags: ['reactive-forms', 'formcontrol'],
  },
  {
    id: 'fe-ng-dependency-injection',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'Constructor Dependency Injection',
    text: 'Write a constructor that injects UserService as a private parameter: constructor(private userService: UserService) {}.',
    setup: 'Write the full constructor with TypeScript private shorthand.',
    setupCode: `class MyComponent {}
class UserService {}`,
    expected: 'Constructor with private injected service',
    sample: `constructor(private userService: UserService) {}`,
    validPatterns: [/constructor\s*\(\s*private\s+\w+\s*:\s*UserService\s*\)/],
    hints: ['Use constructor(private serviceName: ServiceType) {}'],
    tags: ['di', 'constructor', 'injection'],
  },
  {
    id: 'fe-ng-template-reference-variable',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'medium',
    title: 'Template Reference Variable',
    text: 'Write an Angular template with two elements: (1) an <input> with #nameInput reference variable and type="text", (2) a <button> with (click)="logValue(nameInput.value)" and text "Log".',
    setup: 'Write both elements using Angular template reference variable syntax.',
    setupCode: `const logValue = (val: string) => console.log(val);`,
    expected: 'Template with #ref and usage',
    sample: `<input #nameInput type="text">
<button (click)="logValue(nameInput.value)">Log</button>`,
    validPatterns: [/<input[^>]*#nameInput/, /nameInput\.value/],
    hints: ['Use #variableName to create a reference, then use it in event bindings'],
    editorLanguage: 'html',
    tags: ['template-ref', 'reference-variable'],
  },
];
