import type { FrontendDrillProblem } from '../types';

export const angularProblems: FrontendDrillProblem[] = [
  {
    id: 'fe-ng-component-decorator',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: 'Component Decorator',
    text: 'Write an Angular @Component decorator with selector "app-hello" and template showing "Hello World".',
    setup: 'Write the decorator syntax.',
    setupCode: `const componentConfig = {};`,
    expected: '@Component decorator with selector and template',
    sample: `@Component({
  selector: 'app-hello',
  template: '<h1>Hello World</h1>'
})`,
    validPatterns: [
      /@Component\s*\(\s*\{[^}]*selector\s*:\s*['"]app-hello['"][^}]*template\s*:/,
      /@Component\s*\(\s*\{[^}]*template\s*:[^}]*selector\s*:\s*['"]app-hello['"]/,
    ],
    hints: ['Use @Component({...}) with selector and template properties'],
    tags: ['decorator', 'component'],
  },
  {
    id: 'fe-ng-event-binding',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'easy',
    title: 'Event Binding',
    text: 'Write an Angular template with a button that calls handleClick() on click.',
    setup: 'Write the template string with event binding syntax.',
    setupCode: `const template = '';`,
    expected: 'Template with (click) event binding',
    sample: `<button (click)="handleClick()">Click Me</button>`,
    validPatterns: [/<button[^>]*\(click\)\s*=\s*["']handleClick\(\)["'][^>]*>/],
    hints: ['Use Angular event binding syntax: (eventName)="handler()"'],
    tags: ['events', 'template'],
  },
  {
    id: 'fe-ng-input-decorator',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'easy',
    title: '@Input Decorator',
    text: 'Declare a property "name" with @Input decorator to accept data from parent component.',
    setup: 'Write the property declaration with decorator.',
    setupCode: `class MyComponent {}`,
    expected: '@Input decorated property',
    sample: `@Input() name: string;`,
    validPatterns: [/@Input\s*\(\s*\)\s+name\s*:\s*string/, /@Input\s*\(\s*\)\s+name\s*[;:]/],
    hints: ['Use @Input() decorator before the property'],
    tags: ['input', 'decorator', 'props'],
  },
  {
    id: 'fe-ng-output-eventemitter',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'medium',
    title: '@Output and EventEmitter',
    text: 'Create an @Output property "notify" that emits string events using EventEmitter.',
    setup: 'Write the property declaration with @Output and EventEmitter.',
    setupCode: `class MyComponent {}`,
    expected: '@Output with EventEmitter<string>',
    sample: `@Output() notify = new EventEmitter<string>();`,
    validPatterns: [
      /@Output\s*\(\s*\)\s+notify\s*=\s*new\s+EventEmitter\s*<\s*string\s*>\s*\(\s*\)/,
      /@Output\s*\(\s*\)\s+notify:\s*EventEmitter<string>\s*=\s*new\s+EventEmitter/,
    ],
    hints: ['Use @Output() with new EventEmitter<T>()'],
    tags: ['output', 'events', 'eventemitter'],
  },
  {
    id: 'fe-ng-ngfor-directive',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: '*ngFor Directive',
    text: 'Write a template that loops over an array "items" using *ngFor and displays each item in a <li>.',
    setup: 'Write the template with *ngFor.',
    setupCode: `const items = ['apple', 'banana', 'cherry'];`,
    expected: 'Template with *ngFor loop',
    sample: `<li *ngFor="let item of items">{{ item }}</li>`,
    validPatterns: [/<li[^>]*\*ngFor\s*=\s*["']let\s+\w+\s+of\s+items["'][^>]*>/],
    hints: ['Use *ngFor="let item of items" syntax'],
    tags: ['ngfor', 'loops', 'template'],
  },
  {
    id: 'fe-ng-ngif-directive',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: '*ngIf Directive',
    text: 'Write a template that shows a <p> tag only when "isVisible" is true using *ngIf.',
    setup: 'Write the conditional template.',
    setupCode: `const isVisible = true;`,
    expected: 'Template with *ngIf',
    sample: `<p *ngIf="isVisible">I am visible!</p>`,
    validPatterns: [/<p[^>]*\*ngIf\s*=\s*["']isVisible["'][^>]*>/],
    hints: ['Use *ngIf="condition" on the element'],
    tags: ['ngif', 'conditional', 'template'],
  },
  {
    id: 'fe-ng-service-injectable',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: '@Injectable Decorator',
    text: 'Create a service class "DataService" with @Injectable decorator provided in root.',
    setup: 'Write the service class with decorator.',
    setupCode: `class DataService {}`,
    expected: '@Injectable service with providedIn: root',
    sample: `@Injectable({
  providedIn: 'root'
})
class DataService {}`,
    validPatterns: [/@Injectable\s*\(\s*\{[^}]*providedIn\s*:\s*['"]root['"]/],
    hints: ["Use @Injectable({ providedIn: 'root' })"],
    tags: ['injectable', 'service', 'di'],
  },
  {
    id: 'fe-ng-ngoninit-lifecycle',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'easy',
    title: 'ngOnInit Lifecycle',
    text: 'Implement the ngOnInit lifecycle hook that logs "Component initialized".',
    setup: 'Write the ngOnInit method.',
    setupCode: `class MyComponent {}`,
    expected: 'ngOnInit method implementation',
    sample: `ngOnInit() {
  console.log('Component initialized');
}`,
    validPatterns: [
      /ngOnInit\s*\(\s*\)\s*\{[^}]*console\.log/,
      /ngOnInit\s*\(\s*\)\s*:\s*void\s*\{/,
    ],
    hints: ['Implement ngOnInit() { ... } method'],
    tags: ['lifecycle', 'hooks', 'ngoninit'],
  },
  {
    id: 'fe-ng-httpclient-get',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'medium',
    title: 'HttpClient GET Request',
    text: 'Write code that uses HttpClient to GET data from "/api/users". Assume "http" is available.',
    setup: 'Write the HTTP GET call.',
    setupCode: `const http = { get: (url: string) => ({ subscribe: (fn: any) => fn([]) }) };`,
    expected: 'http.get() with subscribe',
    sample: `http.get('/api/users').subscribe(data => {
  console.log(data);
});`,
    validPatterns: [/http\.get\s*\(\s*['"]\/api\/users['"]\s*\)\.subscribe/],
    hints: ['Use http.get(url).subscribe(...)'],
    tags: ['http', 'httpclient', 'api'],
  },
  {
    id: 'fe-ng-rxjs-pipe-map',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'RxJS pipe and map',
    text: 'Use pipe() and map() on an Observable to transform each value by doubling it. Assume "source$" is available.',
    setup: 'Write the pipe and map operators.',
    setupCode: `const source$ = { pipe: (...args: any[]) => source$ };
const map = (fn: any) => fn;`,
    expected: 'pipe() with map() operator',
    sample: `source$.pipe(
  map(x => x * 2)
)`,
    validPatterns: [
      /source\$\.pipe\s*\(\s*map\s*\(/,
      /\.pipe\s*\([^)]*map\s*\([^)]*=>\s*[^)]*\*\s*2/,
    ],
    hints: ['Use source$.pipe(map(value => value * 2))'],
    tags: ['rxjs', 'observable', 'pipe', 'map'],
  },
  {
    id: 'fe-ng-two-way-binding',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'easy',
    title: 'Two-Way Binding',
    text: 'Write a template with an input using [(ngModel)] for two-way binding to "username".',
    setup: 'Write the input with ngModel binding.',
    setupCode: `const username = '';`,
    expected: 'Input with [(ngModel)]',
    sample: `<input [(ngModel)]="username" />`,
    validPatterns: [/<input[^>]*\[\(ngModel\)\]\s*=\s*["']username["'][^>]*>/],
    hints: ['Use [(ngModel)]="propertyName" for two-way binding'],
    tags: ['ngmodel', 'forms', 'two-way'],
  },
  {
    id: 'fe-ng-formcontrol',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'medium',
    title: 'Reactive FormControl',
    text: 'Create a FormControl named "emailControl" with an initial value of empty string.',
    setup: 'Write the FormControl instantiation.',
    setupCode: `const FormControl = class { constructor(value: any) {} };`,
    expected: 'new FormControl with initial value',
    sample: `const emailControl = new FormControl('');`,
    validPatterns: [
      /const\s+emailControl\s*=\s*new\s+FormControl\s*\(/,
      /emailControl\s*=\s*new\s+FormControl\s*\(\s*['"]{2}\s*\)/,
    ],
    hints: ['Use new FormControl(initialValue)'],
    tags: ['reactive-forms', 'formcontrol'],
  },
  {
    id: 'fe-ng-dependency-injection',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'Constructor Dependency Injection',
    text: 'Write a constructor that injects a service "UserService" using the private keyword.',
    setup: 'Write the constructor with DI.',
    setupCode: `class MyComponent {}
class UserService {}`,
    expected: 'Constructor with private injected service',
    sample: `constructor(private userService: UserService) {}`,
    validPatterns: [/constructor\s*\(\s*private\s+\w+\s*:\s*UserService\s*\)/],
    hints: ['Use constructor(private serviceName: ServiceType) {}'],
    tags: ['di', 'constructor', 'injection'],
  },
  {
    id: 'fe-ng-template-reference-variable',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'medium',
    title: 'Template Reference Variable',
    text: 'Create an input with template reference variable #nameInput and a button that calls logValue(nameInput.value).',
    setup: 'Write the template with reference variable.',
    setupCode: `const logValue = (val: string) => console.log(val);`,
    expected: 'Template with #ref and usage',
    sample: `<input #nameInput type="text">
<button (click)="logValue(nameInput.value)">Log</button>`,
    validPatterns: [/<input[^>]*#nameInput/, /nameInput\.value/],
    hints: ['Use #variableName to create a reference, then use it in event bindings'],
    tags: ['template-ref', 'reference-variable'],
  },
];
