import type { FrontendDrillProblem } from '../types';

export const angularProblems: FrontendDrillProblem[] = [
  {
    id: 'fe-ng-component-decorator',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: 'Component Decorator',
    text: 'Write an Angular @Component decorator with selector "app-hello" and a template containing "<h1>Hello World</h1>".',
    setup: 'Write the full @Component({...}) decorator call.',
    setupCode: `const componentConfig = {};`,
    expected: '@Component decorator with selector and template',
    sample: `@Component({
  selector: 'app-hello',
  template: '<h1>Hello World</h1>'
})`,
    validPatterns: [
      /@Component\s*\(\s*\{[^}]*selector\s*:\s*['"]app-hello['"][^}]*template\s*:/,
      /@Component\s*\(\s*\{[^}]*template\s*:[^}]*selector\s*:\s*['"]app-hello['"]/,
    ],
    hints: ['Use @Component({...}) with selector and template properties'],
    tags: ['decorator', 'component'],
  },
  {
    id: 'fe-ng-event-binding',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'easy',
    title: 'Event Binding',
    text: 'Write an Angular template: a <button> with text "Click Me" that calls handleClick() on click using (click) event binding.',
    setup: 'Write the full HTML template string with Angular event binding syntax.',
    setupCode: `const template = '';`,
    expected: 'Template with (click) event binding',
    sample: `<button (click)="handleClick()">Click Me</button>`,
    validPatterns: [/<button[^>]*\(click\)\s*=\s*["']handleClick\(\)["'][^>]*>/],
    hints: ['Use Angular event binding syntax: (eventName)="handler()"'],
    editorLanguage: 'html',
    tags: ['events', 'template'],
  },
  {
    id: 'fe-ng-input-decorator',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'easy',
    title: '@Input Decorator',
    text: 'Declare a property "name" of type string with the @Input() decorator to accept data from a parent component.',
    setup: 'Write the decorated property declaration: @Input() name: string;',
    setupCode: `class MyComponent {}`,
    expected: '@Input decorated property',
    sample: `@Input() name: string;`,
    validPatterns: [/@Input\s*\(\s*\)\s+name\s*:\s*string/, /@Input\s*\(\s*\)\s+name\s*[;:]/],
    hints: ['Use @Input() decorator before the property'],
    tags: ['input', 'decorator', 'props'],
  },
  {
    id: 'fe-ng-output-eventemitter',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'medium',
    title: '@Output and EventEmitter',
    text: 'Create an @Output() property "notify" initialized as a new EventEmitter<string>().',
    setup: 'Write the full decorated property: @Output() notify = new EventEmitter<string>();',
    setupCode: `class MyComponent {}`,
    expected: '@Output with EventEmitter<string>',
    sample: `@Output() notify = new EventEmitter<string>();`,
    validPatterns: [
      /@Output\s*\(\s*\)\s+notify\s*=\s*new\s+EventEmitter\s*<\s*string\s*>\s*\(\s*\)/,
      /@Output\s*\(\s*\)\s+notify:\s*EventEmitter<string>\s*=\s*new\s+EventEmitter/,
    ],
    hints: ['Use @Output() with new EventEmitter<T>()'],
    tags: ['output', 'events', 'eventemitter'],
  },
  {
    id: 'fe-ng-ngfor-directive',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: '*ngFor Directive',
    text: 'Write an Angular template: a <li> element with *ngFor="let item of items" that displays each item using {{ item }} interpolation.',
    setup: 'Write the full <li> element with *ngFor directive and interpolation.',
    setupCode: `const items = ['apple', 'banana', 'cherry'];`,
    expected: 'Template with *ngFor loop',
    sample: `<li *ngFor="let item of items">{{ item }}</li>`,
    validPatterns: [/<li[^>]*\*ngFor\s*=\s*["']let\s+\w+\s+of\s+items["'][^>]*>/],
    hints: ['Use *ngFor="let item of items" syntax'],
    editorLanguage: 'html',
    tags: ['ngfor', 'loops', 'template'],
  },
  {
    id: 'fe-ng-ngif-directive',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: '*ngIf Directive',
    text: 'Write an Angular template: a <p> element with *ngIf="isVisible" that shows any text content (e.g. "I am visible!").',
    setup: 'Write the full <p> element with *ngIf directive.',
    setupCode: `const isVisible = true;`,
    expected: 'Template with *ngIf',
    sample: `<p *ngIf="isVisible">I am visible!</p>`,
    validPatterns: [/<p[^>]*\*ngIf\s*=\s*["']isVisible["'][^>]*>/],
    hints: ['Use *ngIf="condition" on the element'],
    editorLanguage: 'html',
    tags: ['ngif', 'conditional', 'template'],
  },
  {
    id: 'fe-ng-service-injectable',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: '@Injectable Decorator',
    text: 'Write an @Injectable({ providedIn: \'root\' }) decorator followed by the class declaration "class DataService {}".',
    setup: 'Write the full @Injectable decorator and class declaration.',
    setupCode: `class DataService {}`,
    expected: '@Injectable service with providedIn: root',
    sample: `@Injectable({
  providedIn: 'root'
})
class DataService {}`,
    validPatterns: [/@Injectable\s*\(\s*\{[^}]*providedIn\s*:\s*['"]root['"]/],
    hints: ["Use @Injectable({ providedIn: 'root' })"],
    tags: ['injectable', 'service', 'di'],
  },
  {
    id: 'fe-ng-ngoninit-lifecycle',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'easy',
    title: 'ngOnInit Lifecycle',
    text: "Write an ngOnInit() method body that calls console.log('Component initialized').",
    setup: 'Write the full ngOnInit() { ... } method implementation.',
    setupCode: `class MyComponent {}`,
    expected: 'ngOnInit method implementation',
    sample: `ngOnInit() {
  console.log('Component initialized');
}`,
    validPatterns: [
      /ngOnInit\s*\(\s*\)\s*\{[^}]*console\.log/,
      /ngOnInit\s*\(\s*\)\s*:\s*void\s*\{/,
    ],
    hints: ['Implement ngOnInit() { ... } method'],
    tags: ['lifecycle', 'hooks', 'ngoninit'],
  },
  {
    id: 'fe-ng-httpclient-get',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'medium',
    title: 'HttpClient GET Request',
    text: 'Call http.get(\'/api/users\') and chain .subscribe() with a callback that logs the data. The "http" object is already available.',
    setup: 'Write http.get(url).subscribe(callback).',
    setupCode: `const http = { get: (url: string) => ({ subscribe: (fn: any) => fn([]) }) };`,
    expected: 'http.get() with subscribe',
    sample: `http.get('/api/users').subscribe(data => {
  console.log(data);
});`,
    validPatterns: [/http\.get\s*\(\s*['"]\/api\/users['"]\s*\)\.subscribe/],
    hints: ['Use http.get(url).subscribe(...)'],
    tags: ['http', 'httpclient', 'api'],
  },
  {
    id: 'fe-ng-rxjs-pipe-map',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'RxJS pipe and map',
    text: 'Call source$.pipe(map(x => x * 2)) to double each emitted value. Both "source$" and "map" are already available.',
    setup: 'Write the source$.pipe(map(...)) expression.',
    setupCode: `const source$ = { pipe: (...args: any[]) => source$ };
const map = (fn: any) => fn;`,
    expected: 'pipe() with map() operator',
    sample: `source$.pipe(
  map(x => x * 2)
)`,
    validPatterns: [
      /source\$\.pipe\s*\(\s*map\s*\(/,
      /\.pipe\s*\([^)]*map\s*\([^)]*=>\s*[^)]*\*\s*2/,
    ],
    hints: ['Use source$.pipe(map(value => value * 2))'],
    tags: ['rxjs', 'observable', 'pipe', 'map'],
  },
  {
    id: 'fe-ng-two-way-binding',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'easy',
    title: 'Two-Way Binding',
    text: 'Write an Angular template: an <input> element with [(ngModel)]="username" for two-way data binding.',
    setup: 'Write the full <input> element with banana-in-a-box syntax.',
    setupCode: `const username = '';`,
    expected: 'Input with [(ngModel)]',
    sample: `<input [(ngModel)]="username" />`,
    validPatterns: [/<input[^>]*\[\(ngModel\)\]\s*=\s*["']username["'][^>]*>/],
    hints: ['Use [(ngModel)]="propertyName" for two-way binding'],
    editorLanguage: 'html',
    tags: ['ngmodel', 'forms', 'two-way'],
  },
  {
    id: 'fe-ng-formcontrol',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'medium',
    title: 'Reactive FormControl',
    text: 'Declare a const "emailControl" assigned to new FormControl(\'\') with an empty string as the initial value.',
    setup: "Write: const emailControl = new FormControl('');",
    setupCode: `const FormControl = class { constructor(value: any) {} };`,
    expected: 'new FormControl with initial value',
    sample: `const emailControl = new FormControl('');`,
    validPatterns: [
      /const\s+emailControl\s*=\s*new\s+FormControl\s*\(/,
      /emailControl\s*=\s*new\s+FormControl\s*\(\s*['"]{2}\s*\)/,
    ],
    hints: ['Use new FormControl(initialValue)'],
    tags: ['reactive-forms', 'formcontrol'],
  },
  {
    id: 'fe-ng-dependency-injection',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'Constructor Dependency Injection',
    text: 'Write a constructor that injects UserService as a private parameter: constructor(private userService: UserService) {}.',
    setup: 'Write the full constructor with TypeScript private shorthand.',
    setupCode: `class MyComponent {}
class UserService {}`,
    expected: 'Constructor with private injected service',
    sample: `constructor(private userService: UserService) {}`,
    validPatterns: [/constructor\s*\(\s*private\s+\w+\s*:\s*UserService\s*\)/],
    hints: ['Use constructor(private serviceName: ServiceType) {}'],
    tags: ['di', 'constructor', 'injection'],
  },
  {
    id: 'fe-ng-template-reference-variable',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'medium',
    title: 'Template Reference Variable',
    text: 'Write an Angular template with two elements: (1) an <input> with #nameInput reference variable and type="text", (2) a <button> with (click)="logValue(nameInput.value)" and text "Log".',
    setup: 'Write both elements using Angular template reference variable syntax.',
    setupCode: `const logValue = (val: string) => console.log(val);`,
    expected: 'Template with #ref and usage',
    sample: `<input #nameInput type="text">
<button (click)="logValue(nameInput.value)">Log</button>`,
    validPatterns: [/<input[^>]*#nameInput/, /nameInput\.value/],
    hints: ['Use #variableName to create a reference, then use it in event bindings'],
    editorLanguage: 'html',
    tags: ['template-ref', 'reference-variable'],
  },

  // ═══════════════════════════════════════════════════════════════
  // DOM & Events (17 new problems)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'fe-ng-property-binding',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'easy',
    title: 'Property Binding',
    text: 'Write an Angular template: an <img> element with property binding [src]="imageUrl" and [alt]="imageAlt".',
    setup: 'Write the <img> element using Angular property binding syntax.',
    setupCode: `const template = '';`,
    expected: 'Template with [src] and [alt] property binding',
    sample: `<img [src]="imageUrl" [alt]="imageAlt" />`,
    validPatterns: [
      /<img[^>]*\[src\]\s*=\s*["']imageUrl["'][^>]*\[alt\]\s*=\s*["']imageAlt["']/,
      /<img[^>]*\[alt\]\s*=\s*["']imageAlt["'][^>]*\[src\]\s*=\s*["']imageUrl["']/,
    ],
    editorLanguage: 'html',
    hints: ['Use [property]="expression" syntax for property binding'],
    tags: ['property-binding', 'template'],
  },
  {
    id: 'fe-ng-interpolation',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'easy',
    title: 'String Interpolation',
    text: 'Write an Angular template: a <p> element displaying "Hello, {{ name }}!" using interpolation.',
    setup: 'Write the <p> element using Angular interpolation.',
    setupCode: `const template = '';`,
    expected: 'Template with {{ name }} interpolation',
    sample: `<p>Hello, {{ name }}!</p>`,
    validPatterns: [/<p>[^<]*\{\{\s*name\s*\}\}[^<]*<\/p>/],
    editorLanguage: 'html',
    hints: ['Use {{ expression }} for interpolation inside element content'],
    tags: ['interpolation', 'template'],
  },
  {
    id: 'fe-ng-keyup-event',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'easy',
    title: 'Key Event Binding',
    text: 'Write an Angular template: an <input> with (keyup.enter)="onSubmit()" to handle the Enter key.',
    setup: 'Write the <input> element with keyup.enter event binding.',
    setupCode: `const template = '';`,
    expected: 'Template with (keyup.enter) event binding',
    sample: `<input (keyup.enter)="onSubmit()" />`,
    validPatterns: [/<input[^>]*\(keyup\.enter\)\s*=\s*["']onSubmit\(\)["'][^>]*>/],
    editorLanguage: 'html',
    hints: ['Use (keyup.enter)="handler()" for Enter key events'],
    tags: ['events', 'keyup', 'template'],
  },
  {
    id: 'fe-ng-event-object',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'easy',
    title: 'Passing $event Object',
    text: 'Write an Angular template: an <input> with (input)="onInput($event)" to pass the event object to the handler.',
    setup: 'Write the <input> element passing $event.',
    setupCode: `const template = '';`,
    expected: 'Template passing $event to handler',
    sample: `<input (input)="onInput($event)" />`,
    validPatterns: [/<input[^>]*\(input\)\s*=\s*["']onInput\(\$event\)["'][^>]*>/],
    editorLanguage: 'html',
    hints: ['Use $event to pass the native DOM event to your handler'],
    tags: ['events', '$event', 'template'],
  },
  {
    id: 'fe-ng-host-listener',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'medium',
    title: '@HostListener Decorator',
    text: "Write a @HostListener('click', ['$event']) decorator followed by method onClick(event: Event) {}.",
    setup: 'Write the full decorator and method signature.',
    setupCode: `class MyDirective {}`,
    expected: '@HostListener with click event',
    sample: `@HostListener('click', ['$event'])
onClick(event: Event) {}`,
    validPatterns: [/@HostListener\s*\(\s*['"]click['"][^)]*\$event[^)]*\)/],
    hints: ['Use @HostListener(eventName, args) to listen to host element events'],
    tags: ['host-listener', 'directive', 'events'],
  },
  {
    id: 'fe-ng-host-binding',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'medium',
    title: '@HostBinding Decorator',
    text: "Write a @HostBinding('class.active') decorator followed by property isActive = false;.",
    setup: 'Write the full decorator and property declaration.',
    setupCode: `class MyDirective {}`,
    expected: '@HostBinding with class.active',
    sample: `@HostBinding('class.active') isActive = false;`,
    validPatterns: [/@HostBinding\s*\(\s*['"]class\.active['"]\s*\)\s+isActive/],
    hints: ['Use @HostBinding(hostProperty) to bind a property to the host element'],
    tags: ['host-binding', 'directive'],
  },
  {
    id: 'fe-ng-ngclass-directive',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'easy',
    title: '[ngClass] Directive',
    text: "Write an Angular template: a <div> with [ngClass]=\"{ 'active': isActive, 'disabled': isDisabled }\".",
    setup: 'Write the <div> element using [ngClass] with an object expression.',
    setupCode: `const template = '';`,
    expected: 'Template with [ngClass] object binding',
    sample: `<div [ngClass]="{ 'active': isActive, 'disabled': isDisabled }"></div>`,
    validPatterns: [/<div[^>]*\[ngClass\]\s*=\s*["']\{[^}]*active[^}]*isActive[^}]*\}["']/],
    editorLanguage: 'html',
    hints: ['Use [ngClass]="{ className: condition }" for conditional classes'],
    tags: ['ngclass', 'template', 'styling'],
  },
  {
    id: 'fe-ng-ngstyle-directive',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'easy',
    title: '[ngStyle] Directive',
    text: "Write an Angular template: a <div> with [ngStyle]=\"{ 'color': textColor, 'font-size': fontSize }\".",
    setup: 'Write the <div> element using [ngStyle] with an object expression.',
    setupCode: `const template = '';`,
    expected: 'Template with [ngStyle] object binding',
    sample: `<div [ngStyle]="{ 'color': textColor, 'font-size': fontSize }"></div>`,
    validPatterns: [/<div[^>]*\[ngStyle\]\s*=\s*["']\{[^}]*color[^}]*textColor[^}]*\}["']/],
    editorLanguage: 'html',
    hints: ['Use [ngStyle]="{ styleProp: expression }" for dynamic styles'],
    tags: ['ngstyle', 'template', 'styling'],
  },
  {
    id: 'fe-ng-class-binding',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'easy',
    title: 'Single Class Binding',
    text: 'Write an Angular template: a <div> with [class.highlight]="isHighlighted" for a single class toggle.',
    setup: 'Write the <div> element using single class binding.',
    setupCode: `const template = '';`,
    expected: 'Template with [class.highlight] binding',
    sample: `<div [class.highlight]="isHighlighted"></div>`,
    validPatterns: [/<div[^>]*\[class\.highlight\]\s*=\s*["']isHighlighted["'][^>]*>/],
    editorLanguage: 'html',
    hints: ['Use [class.className]="condition" to toggle a single class'],
    tags: ['class-binding', 'template'],
  },
  {
    id: 'fe-ng-style-binding',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'easy',
    title: 'Single Style Binding',
    text: 'Write an Angular template: a <div> with [style.background-color]="bgColor" for a single style property.',
    setup: 'Write the <div> element using single style binding.',
    setupCode: `const template = '';`,
    expected: 'Template with [style.background-color] binding',
    sample: `<div [style.background-color]="bgColor"></div>`,
    validPatterns: [/<div[^>]*\[style\.background-color\]\s*=\s*["']bgColor["'][^>]*>/],
    editorLanguage: 'html',
    hints: ['Use [style.property]="expression" to bind a single style'],
    tags: ['style-binding', 'template'],
  },
  {
    id: 'fe-ng-viewchild',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'medium',
    title: '@ViewChild Decorator',
    text: "Write a @ViewChild('myInput') decorator followed by property inputRef: ElementRef;.",
    setup: 'Write the full decorator and property declaration.',
    setupCode: `class MyComponent {}`,
    expected: '@ViewChild with template reference',
    sample: `@ViewChild('myInput') inputRef: ElementRef;`,
    validPatterns: [/@ViewChild\s*\(\s*['"]myInput['"]\s*\)\s+inputRef\s*:\s*ElementRef/],
    hints: ['Use @ViewChild(refName) to query a template reference variable'],
    tags: ['viewchild', 'dom-access'],
  },
  {
    id: 'fe-ng-viewchildren',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'medium',
    title: '@ViewChildren Decorator',
    text: 'Write a @ViewChildren(ItemComponent) decorator followed by property items: QueryList<ItemComponent>;.',
    setup: 'Write the full decorator and property declaration.',
    setupCode: `class MyComponent {}\nclass ItemComponent {}`,
    expected: '@ViewChildren with QueryList',
    sample: `@ViewChildren(ItemComponent) items: QueryList<ItemComponent>;`,
    validPatterns: [
      /@ViewChildren\s*\(\s*ItemComponent\s*\)\s+items\s*:\s*QueryList\s*<\s*ItemComponent\s*>/,
    ],
    hints: ['Use @ViewChildren(Component) to query all matching child components'],
    tags: ['viewchildren', 'querylist'],
  },
  {
    id: 'fe-ng-renderer2-setattr',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'hard',
    title: 'Renderer2 setAttribute',
    text: "Write a statement using Renderer2 to set an attribute: this.renderer.setAttribute(this.el.nativeElement, 'role', 'button');.",
    setup: 'Write the full this.renderer.setAttribute(...) call.',
    setupCode: `class MyDirective {}`,
    expected: 'Renderer2 setAttribute call',
    sample: `this.renderer.setAttribute(this.el.nativeElement, 'role', 'button');`,
    validPatterns: [
      /this\.renderer\.setAttribute\s*\(\s*this\.el\.nativeElement\s*,\s*['"]role['"]\s*,\s*['"]button['"]\s*\)/,
    ],
    hints: ['Use Renderer2 for safe DOM manipulation instead of direct nativeElement access'],
    tags: ['renderer2', 'dom', 'safe-access'],
  },
  {
    id: 'fe-ng-attribute-directive',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'hard',
    title: 'Custom Attribute Directive',
    text: "Write a @Directive decorator with selector '[appHighlight]' for a custom attribute directive.",
    setup: 'Write the full @Directive({...}) decorator.',
    setupCode: `class HighlightDirective {}`,
    expected: '@Directive with [appHighlight] selector',
    sample: `@Directive({
  selector: '[appHighlight]'
})`,
    validPatterns: [/@Directive\s*\(\s*\{[^}]*selector\s*:\s*['"]\[appHighlight\]['"]/],
    hints: ['Attribute directive selectors use [bracketSyntax]'],
    tags: ['directive', 'attribute-directive', 'decorator'],
  },
  {
    id: 'fe-ng-mouseover-event',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'easy',
    title: 'Mouse Event Binding',
    text: 'Write an Angular template: a <div> with (mouseenter)="onHover()" and (mouseleave)="onLeave()" event bindings.',
    setup: 'Write the <div> element with both mouse event bindings.',
    setupCode: `const template = '';`,
    expected: 'Template with mouseenter and mouseleave bindings',
    sample: `<div (mouseenter)="onHover()" (mouseleave)="onLeave()"></div>`,
    validPatterns: [
      /<div[^>]*\(mouseenter\)\s*=\s*["']onHover\(\)["'][^>]*\(mouseleave\)\s*=\s*["']onLeave\(\)["']/,
      /<div[^>]*\(mouseleave\)\s*=\s*["']onLeave\(\)["'][^>]*\(mouseenter\)\s*=\s*["']onHover\(\)["']/,
    ],
    editorLanguage: 'html',
    hints: ['Use (mouseenter) and (mouseleave) for hover events'],
    tags: ['events', 'mouse', 'template'],
  },
  {
    id: 'fe-ng-contentchild',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'medium',
    title: '@ContentChild Decorator',
    text: "Write a @ContentChild('header') decorator followed by property headerContent: TemplateRef<any>;.",
    setup: 'Write the full decorator and property declaration.',
    setupCode: `class MyComponent {}`,
    expected: '@ContentChild with TemplateRef',
    sample: `@ContentChild('header') headerContent: TemplateRef<any>;`,
    validPatterns: [/@ContentChild\s*\(\s*['"]header['"]\s*\)\s+headerContent\s*:\s*TemplateRef/],
    hints: ['Use @ContentChild to query projected content'],
    tags: ['contentchild', 'content-projection'],
  },
  {
    id: 'fe-ng-structural-directive',
    framework: 'angular',
    category: 'DOM & Events',
    difficulty: 'hard',
    title: 'Custom Structural Directive',
    text: "Write a @Directive decorator with selector '[appUnless]' and a constructor that injects TemplateRef<any> and ViewContainerRef.",
    setup: 'Write the decorator and constructor with injected dependencies.',
    setupCode: `class UnlessDirective {}`,
    expected: 'Structural directive with TemplateRef and ViewContainerRef',
    sample: `@Directive({ selector: '[appUnless]' })
class UnlessDirective {
  constructor(private templateRef: TemplateRef<any>, private vcRef: ViewContainerRef) {}
}`,
    validPatterns: [
      /@Directive\s*\(\s*\{[^}]*selector\s*:\s*['"]\[appUnless\]['"]/,
      /constructor\s*\([^)]*TemplateRef[^)]*ViewContainerRef[^)]*\)/,
    ],
    hints: ['Structural directives need TemplateRef and ViewContainerRef injected'],
    tags: ['structural-directive', 'directive', 'advanced'],
  },

  // ═══════════════════════════════════════════════════════════════
  // State & Lifecycle (17 new problems)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'fe-ng-ngonchanges',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'medium',
    title: 'ngOnChanges Lifecycle',
    text: 'Write an ngOnChanges(changes: SimpleChanges) method that logs changes.name.currentValue when changes.name exists.',
    setup: 'Write the full ngOnChanges method implementation.',
    setupCode: `class MyComponent {}`,
    expected: 'ngOnChanges with SimpleChanges parameter',
    sample: `ngOnChanges(changes: SimpleChanges) {
  if (changes.name) {
    console.log(changes.name.currentValue);
  }
}`,
    validPatterns: [
      /ngOnChanges\s*\(\s*changes\s*:\s*SimpleChanges\s*\)\s*\{/,
      /changes\.\w+\.currentValue/,
    ],
    hints: ['SimpleChanges provides currentValue and previousValue for each changed input'],
    tags: ['lifecycle', 'ngonchanges', 'simplechanges'],
  },
  {
    id: 'fe-ng-ngdocheck',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'medium',
    title: 'ngDoCheck Lifecycle',
    text: 'Write an ngDoCheck() method that uses a KeyValueDiffers check: log "Object changed" if this.differ.diff(this.data) is truthy.',
    setup: 'Write the full ngDoCheck method.',
    setupCode: `class MyComponent {}`,
    expected: 'ngDoCheck with differ check',
    sample: `ngDoCheck() {
  const changes = this.differ.diff(this.data);
  if (changes) {
    console.log('Object changed');
  }
}`,
    validPatterns: [/ngDoCheck\s*\(\s*\)\s*\{/, /differ\.diff\s*\(/],
    hints: ['ngDoCheck runs on every change detection cycle; use Differs for deep comparison'],
    tags: ['lifecycle', 'ngdocheck', 'change-detection'],
  },
  {
    id: 'fe-ng-afterviewinit',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'easy',
    title: 'ngAfterViewInit Lifecycle',
    text: 'Write an ngAfterViewInit() method that accesses this.inputRef.nativeElement.focus() to focus an input element.',
    setup: 'Write the full ngAfterViewInit method.',
    setupCode: `class MyComponent {}`,
    expected: 'ngAfterViewInit with nativeElement access',
    sample: `ngAfterViewInit() {
  this.inputRef.nativeElement.focus();
}`,
    validPatterns: [/ngAfterViewInit\s*\(\s*\)\s*\{/, /nativeElement\.focus\s*\(\s*\)/],
    hints: [
      'ngAfterViewInit fires after the view DOM is initialized — safe to access ViewChild refs',
    ],
    tags: ['lifecycle', 'afterviewinit', 'dom-access'],
  },
  {
    id: 'fe-ng-aftercontentinit',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'medium',
    title: 'ngAfterContentInit Lifecycle',
    text: 'Write an ngAfterContentInit() method that logs this.contentChild.length to check projected content.',
    setup: 'Write the full ngAfterContentInit method.',
    setupCode: `class MyComponent {}`,
    expected: 'ngAfterContentInit accessing projected content',
    sample: `ngAfterContentInit() {
  console.log(this.contentChild.length);
}`,
    validPatterns: [/ngAfterContentInit\s*\(\s*\)\s*\{/, /this\.contentChild/],
    hints: ['ngAfterContentInit fires after projected content (ng-content) is initialized'],
    tags: ['lifecycle', 'aftercontentinit', 'content-projection'],
  },
  {
    id: 'fe-ng-ondestroy',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'easy',
    title: 'ngOnDestroy Cleanup',
    text: 'Write an ngOnDestroy() method that calls this.subscription.unsubscribe() to prevent memory leaks.',
    setup: 'Write the full ngOnDestroy method.',
    setupCode: `class MyComponent {}`,
    expected: 'ngOnDestroy with unsubscribe cleanup',
    sample: `ngOnDestroy() {
  this.subscription.unsubscribe();
}`,
    validPatterns: [/ngOnDestroy\s*\(\s*\)\s*\{/, /\.unsubscribe\s*\(\s*\)/],
    hints: ['Always unsubscribe from Observables in ngOnDestroy to avoid memory leaks'],
    tags: ['lifecycle', 'ondestroy', 'cleanup'],
  },
  {
    id: 'fe-ng-afterviewchecked',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'medium',
    title: 'ngAfterViewChecked Lifecycle',
    text: 'Write an ngAfterViewChecked() method that compares this.prevHeight to this.container.nativeElement.scrollHeight and updates this.prevHeight.',
    setup: 'Write the full ngAfterViewChecked method.',
    setupCode: `class MyComponent {}`,
    expected: 'ngAfterViewChecked comparing DOM measurements',
    sample: `ngAfterViewChecked() {
  const newHeight = this.container.nativeElement.scrollHeight;
  if (newHeight !== this.prevHeight) {
    this.prevHeight = newHeight;
  }
}`,
    validPatterns: [/ngAfterViewChecked\s*\(\s*\)\s*\{/, /nativeElement\.scrollHeight/],
    hints: [
      'ngAfterViewChecked runs after every check of the view — avoid changing bound properties here',
    ],
    tags: ['lifecycle', 'afterviewchecked'],
  },
  {
    id: 'fe-ng-input-setter',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'medium',
    title: '@Input with Setter',
    text: 'Write an @Input() set name(value: string) setter that trims the value and stores it in _name.',
    setup: 'Write the full @Input() setter.',
    setupCode: `class MyComponent { private _name = ''; }`,
    expected: '@Input setter with transformation',
    sample: `@Input()
set name(value: string) {
  this._name = value.trim();
}`,
    validPatterns: [
      /@Input\s*\(\s*\)\s*\n?\s*set\s+name\s*\(\s*value\s*:\s*string\s*\)/,
      /this\._name\s*=\s*value\.trim\(\)/,
    ],
    hints: ['Use a setter on @Input to intercept and transform incoming values'],
    tags: ['input', 'setter', 'state'],
  },
  {
    id: 'fe-ng-signal-basic',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'easy',
    title: 'Signal Basics',
    text: 'Create a signal "count" initialized to 0 using signal(0), then write count.set(5) to update it.',
    setup: 'Write the signal creation and set call.',
    setupCode: `const signal = (val: any) => ({ set: (v: any) => v, update: (fn: any) => fn(val) });`,
    expected: 'Signal creation and set',
    sample: `const count = signal(0);
count.set(5);`,
    validPatterns: [/const\s+count\s*=\s*signal\s*\(\s*0\s*\)/, /count\.set\s*\(\s*5\s*\)/],
    hints: ['Signals are Angular 16+ reactive primitives: signal(initialValue)'],
    tags: ['signals', 'state', 'angular16'],
  },
  {
    id: 'fe-ng-computed-signal',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'medium',
    title: 'Computed Signal',
    text: 'Create a computed signal "doubleCount" using computed(() => count() * 2).',
    setup: 'Write the computed signal declaration.',
    setupCode: `const signal = (val: any) => { const s = () => val; s.set = (v: any) => { val = v; }; return s; };\nconst computed = (fn: any) => fn;\nconst count = signal(5);`,
    expected: 'Computed signal deriving from another signal',
    sample: `const doubleCount = computed(() => count() * 2);`,
    validPatterns: [
      /const\s+doubleCount\s*=\s*computed\s*\(\s*\(\s*\)\s*=>\s*count\s*\(\s*\)\s*\*\s*2\s*\)/,
    ],
    hints: ['computed() creates a derived signal that updates automatically'],
    tags: ['signals', 'computed', 'angular16'],
  },
  {
    id: 'fe-ng-effect-signal',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'medium',
    title: 'Signal Effect',
    text: 'Create an effect using effect(() => console.log("Count:", count())) to log whenever count changes.',
    setup: 'Write the effect declaration.',
    setupCode: `const signal = (val: any) => { const s = () => val; s.set = (v: any) => { val = v; }; return s; };\nconst effect = (fn: any) => fn;\nconst count = signal(0);`,
    expected: 'Effect reacting to signal changes',
    sample: `effect(() => console.log("Count:", count()));`,
    validPatterns: [/effect\s*\(\s*\(\s*\)\s*=>\s*console\.log\s*\([^)]*count\s*\(\s*\)/],
    hints: ['effect() runs side-effects whenever referenced signals change'],
    tags: ['signals', 'effect', 'angular16'],
  },
  {
    id: 'fe-ng-signal-update',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'easy',
    title: 'Signal Update',
    text: 'Use count.update(v => v + 1) to increment a signal value by 1.',
    setup: 'Write the signal update call.',
    setupCode: `const signal = (val: any) => { const s = () => val; s.set = (v: any) => { val = v; }; s.update = (fn: any) => { val = fn(val); }; return s; };\nconst count = signal(10);`,
    expected: 'Signal update with function',
    sample: `count.update(v => v + 1);`,
    validPatterns: [/count\.update\s*\(\s*v\s*=>\s*v\s*\+\s*1\s*\)/],
    hints: ['Use .update(fn) to derive new value from previous value'],
    tags: ['signals', 'update', 'angular16'],
  },
  {
    id: 'fe-ng-onpush-strategy',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'hard',
    title: 'OnPush Change Detection',
    text: 'Write a @Component decorator with changeDetection: ChangeDetectionStrategy.OnPush and selector "app-list".',
    setup: 'Write the full @Component decorator with OnPush strategy.',
    setupCode: `class ListComponent {}`,
    expected: '@Component with OnPush change detection',
    sample: `@Component({
  selector: 'app-list',
  template: '',
  changeDetection: ChangeDetectionStrategy.OnPush
})`,
    validPatterns: [
      /@Component\s*\(\s*\{[^}]*changeDetection\s*:\s*ChangeDetectionStrategy\.OnPush/,
    ],
    hints: ['OnPush only runs change detection when @Input references change or events fire'],
    tags: ['change-detection', 'onpush', 'performance'],
  },
  {
    id: 'fe-ng-markforcheck',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'hard',
    title: 'ChangeDetectorRef markForCheck',
    text: 'Write a method refresh() that calls this.cdr.markForCheck() to manually trigger change detection in an OnPush component.',
    setup: 'Write the full method.',
    setupCode: `class MyComponent {}`,
    expected: 'markForCheck for manual change detection',
    sample: `refresh() {
  this.cdr.markForCheck();
}`,
    validPatterns: [/this\.cdr\.markForCheck\s*\(\s*\)/],
    hints: [
      'Use ChangeDetectorRef.markForCheck() in OnPush components when you mutate state from non-Angular events',
    ],
    tags: ['change-detection', 'markforcheck', 'cdr'],
  },
  {
    id: 'fe-ng-detectchanges',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'hard',
    title: 'ChangeDetectorRef detectChanges',
    text: 'Write a method forceUpdate() that calls this.cdr.detectChanges() to immediately run change detection.',
    setup: 'Write the full method.',
    setupCode: `class MyComponent {}`,
    expected: 'detectChanges for immediate change detection',
    sample: `forceUpdate() {
  this.cdr.detectChanges();
}`,
    validPatterns: [/this\.cdr\.detectChanges\s*\(\s*\)/],
    hints: ['detectChanges() synchronously runs change detection on this component and children'],
    tags: ['change-detection', 'detectchanges', 'cdr'],
  },
  {
    id: 'fe-ng-takeuntil-destroy',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'hard',
    title: 'takeUntil Pattern for Unsubscribe',
    text: 'Declare a private destroy$ = new Subject<void>(); then in ngOnDestroy, call this.destroy$.next() and this.destroy$.complete().',
    setup: 'Write the property declaration and ngOnDestroy method.',
    setupCode: `class MyComponent {}`,
    expected: 'takeUntil destroy pattern',
    sample: `private destroy$ = new Subject<void>();

ngOnDestroy() {
  this.destroy$.next();
  this.destroy$.complete();
}`,
    validPatterns: [
      /destroy\$\s*=\s*new\s+Subject<void>\s*\(\s*\)/,
      /this\.destroy\$\.next\s*\(\s*\)/,
      /this\.destroy\$\.complete\s*\(\s*\)/,
    ],
    hints: ['The takeUntil(destroy$) pattern auto-unsubscribes all observables on destroy'],
    tags: ['rxjs', 'takeuntil', 'lifecycle', 'cleanup'],
  },
  {
    id: 'fe-ng-input-transform',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'medium',
    title: '@Input with Transform (v16+)',
    text: 'Write an @Input({ transform: booleanAttribute }) decorator for property disabled: boolean.',
    setup: 'Write the full @Input decorator with transform option.',
    setupCode: `class MyComponent {}`,
    expected: '@Input with booleanAttribute transform',
    sample: `@Input({ transform: booleanAttribute }) disabled: boolean = false;`,
    validPatterns: [/@Input\s*\(\s*\{[^}]*transform\s*:\s*booleanAttribute[^}]*\}\s*\)\s+disabled/],
    hints: ['Angular 16+ allows transform functions on @Input to coerce values'],
    tags: ['input', 'transform', 'angular16'],
  },
  {
    id: 'fe-ng-input-required',
    framework: 'angular',
    category: 'State & Lifecycle',
    difficulty: 'easy',
    title: 'Required @Input (v16+)',
    text: 'Write an @Input({ required: true }) decorator for property title: string.',
    setup: 'Write the full required @Input decorator.',
    setupCode: `class MyComponent {}`,
    expected: '@Input with required option',
    sample: `@Input({ required: true }) title!: string;`,
    validPatterns: [/@Input\s*\(\s*\{[^}]*required\s*:\s*true[^}]*\}\s*\)\s+title/],
    hints: ['Angular 16+ @Input({ required: true }) makes inputs mandatory'],
    tags: ['input', 'required', 'angular16'],
  },

  // ═══════════════════════════════════════════════════════════════
  // Common Patterns (17 new problems)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'fe-ng-use-factory',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'hard',
    title: 'useFactory Provider',
    text: 'Write a provider using useFactory: create an object { provide: API_URL, useFactory: () => environment.apiUrl }.',
    setup: 'Write the full provider object.',
    setupCode: `class MyModule {}`,
    expected: 'Provider with useFactory',
    sample: `{ provide: API_URL, useFactory: () => environment.apiUrl }`,
    validPatterns: [/provide\s*:\s*API_URL[^}]*useFactory\s*:\s*\(\s*\)\s*=>/],
    hints: ['useFactory lets you compute provider values at runtime'],
    tags: ['di', 'provider', 'usefactory'],
  },
  {
    id: 'fe-ng-use-value',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'easy',
    title: 'useValue Provider',
    text: "Write a provider: { provide: BASE_URL, useValue: 'https://api.example.com' }.",
    setup: 'Write the full provider object.',
    setupCode: `class MyModule {}`,
    expected: 'Provider with useValue',
    sample: `{ provide: BASE_URL, useValue: 'https://api.example.com' }`,
    validPatterns: [
      /provide\s*:\s*BASE_URL[^}]*useValue\s*:\s*['"]https:\/\/api\.example\.com['"]/,
    ],
    hints: ['useValue provides a static value for an injection token'],
    tags: ['di', 'provider', 'usevalue'],
  },
  {
    id: 'fe-ng-injection-token',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'InjectionToken',
    text: "Create an InjectionToken: const API_URL = new InjectionToken<string>('API_URL');.",
    setup: 'Write the full InjectionToken declaration.',
    setupCode: `const InjectionToken = class { constructor(desc: string) {} };`,
    expected: 'InjectionToken declaration',
    sample: `const API_URL = new InjectionToken<string>('API_URL');`,
    validPatterns: [
      /const\s+API_URL\s*=\s*new\s+InjectionToken\s*<\s*string\s*>\s*\(\s*['"]API_URL['"]\s*\)/,
    ],
    hints: ['InjectionToken creates a unique token for non-class dependencies'],
    tags: ['di', 'injection-token'],
  },
  {
    id: 'fe-ng-content-projection',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'easy',
    title: 'ng-content Projection',
    text: 'Write an Angular template with a <div class="card"> containing <ng-content></ng-content> for content projection.',
    setup: 'Write the template with ng-content.',
    setupCode: `const template = '';`,
    expected: 'Template with ng-content',
    sample: `<div class="card">
  <ng-content></ng-content>
</div>`,
    validPatterns: [/<ng-content\s*><\/ng-content>/, /<div[^>]*class\s*=\s*["']card["']/],
    editorLanguage: 'html',
    hints: ['ng-content acts like a slot where parent component can project content'],
    tags: ['content-projection', 'ng-content', 'template'],
  },
  {
    id: 'fe-ng-multi-slot-projection',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'Multi-Slot Content Projection',
    text: 'Write a template with two ng-content: <ng-content select="[header]"></ng-content> and <ng-content select="[body]"></ng-content>.',
    setup: 'Write the template with named content slots.',
    setupCode: `const template = '';`,
    expected: 'Template with named ng-content slots',
    sample: `<ng-content select="[header]"></ng-content>
<ng-content select="[body]"></ng-content>`,
    validPatterns: [
      /<ng-content[^>]*select\s*=\s*["']\[header\]/,
      /<ng-content[^>]*select\s*=\s*["']\[body\]/,
    ],
    editorLanguage: 'html',
    hints: ['Use select attribute on ng-content to create named slots'],
    tags: ['content-projection', 'multi-slot', 'template'],
  },
  {
    id: 'fe-ng-ng-container',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'easy',
    title: 'ng-container Grouping',
    text: 'Write an Angular template: <ng-container *ngIf="isLoggedIn"> wrapping a <p>Welcome</p> — no extra DOM element.',
    setup: 'Write the ng-container with *ngIf.',
    setupCode: `const template = '';`,
    expected: 'ng-container with *ngIf (no extra DOM)',
    sample: `<ng-container *ngIf="isLoggedIn">
  <p>Welcome</p>
</ng-container>`,
    validPatterns: [/<ng-container[^>]*\*ngIf\s*=\s*["']isLoggedIn["'][^>]*>/],
    editorLanguage: 'html',
    hints: ['ng-container is a grouping element that does not render to the DOM'],
    tags: ['ng-container', 'structural', 'template'],
  },
  {
    id: 'fe-ng-ng-template',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'ng-template with else',
    text: 'Write a template: <p *ngIf="hasData; else noData">Data loaded</p> followed by <ng-template #noData><p>No data</p></ng-template>.',
    setup: 'Write the *ngIf with else referencing ng-template.',
    setupCode: `const template = '';`,
    expected: '*ngIf with else ng-template',
    sample: `<p *ngIf="hasData; else noData">Data loaded</p>
<ng-template #noData><p>No data</p></ng-template>`,
    validPatterns: [/\*ngIf\s*=\s*["']hasData\s*;\s*else\s+noData["']/, /<ng-template\s+#noData>/],
    editorLanguage: 'html',
    hints: ['Use *ngIf="condition; else templateRef" with <ng-template #ref>'],
    tags: ['ngif', 'else', 'ng-template'],
  },
  {
    id: 'fe-ng-async-pipe',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'easy',
    title: 'Async Pipe',
    text: 'Write an Angular template: <p>{{ data$ | async }}</p> to unwrap an Observable in the template.',
    setup: 'Write the template using the async pipe.',
    setupCode: `const template = '';`,
    expected: 'Template with async pipe',
    sample: `<p>{{ data$ | async }}</p>`,
    validPatterns: [/\{\{\s*data\$\s*\|\s*async\s*\}\}/],
    editorLanguage: 'html',
    hints: ['The async pipe subscribes/unsubscribes automatically'],
    tags: ['async-pipe', 'rxjs', 'template'],
  },
  {
    id: 'fe-ng-custom-pipe',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'Custom Pipe',
    text: "Write a @Pipe({ name: 'truncate' }) decorator followed by class TruncatePipe implements PipeTransform.",
    setup: 'Write the decorator and class declaration.',
    setupCode: `class TruncatePipe {}`,
    expected: '@Pipe decorator with PipeTransform',
    sample: `@Pipe({ name: 'truncate' })
class TruncatePipe implements PipeTransform {
  transform(value: string, limit: number): string {
    return value.length > limit ? value.substring(0, limit) + '...' : value;
  }
}`,
    validPatterns: [
      /@Pipe\s*\(\s*\{[^}]*name\s*:\s*['"]truncate['"]/,
      /implements\s+PipeTransform/,
    ],
    hints: ['Custom pipes need @Pipe({ name }) and must implement PipeTransform.transform()'],
    tags: ['pipe', 'custom-pipe', 'transform'],
  },
  {
    id: 'fe-ng-pure-pipe',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'Impure Pipe',
    text: "Write a @Pipe({ name: 'filter', pure: false }) decorator for an impure pipe that re-runs on every change detection.",
    setup: 'Write the full @Pipe decorator with pure: false.',
    setupCode: `class FilterPipe {}`,
    expected: '@Pipe with pure: false',
    sample: `@Pipe({ name: 'filter', pure: false })`,
    validPatterns: [/@Pipe\s*\(\s*\{[^}]*name\s*:\s*['"]filter['"][^}]*pure\s*:\s*false/],
    hints: ['Impure pipes (pure: false) run on every change detection cycle'],
    tags: ['pipe', 'impure-pipe', 'performance'],
  },
  {
    id: 'fe-ng-ngswitch',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'ngSwitch Directive',
    text: 'Write an Angular template: a <div [ngSwitch]="status"> containing <p *ngSwitchCase="\'active\'">Active</p> and <p *ngSwitchDefault>Unknown</p>.',
    setup: 'Write the template with ngSwitch.',
    setupCode: `const template = '';`,
    expected: 'Template with [ngSwitch] and *ngSwitchCase',
    sample: `<div [ngSwitch]="status">
  <p *ngSwitchCase="'active'">Active</p>
  <p *ngSwitchDefault>Unknown</p>
</div>`,
    validPatterns: [
      /<div[^>]*\[ngSwitch\]\s*=\s*["']status["']/,
      /\*ngSwitchCase\s*=\s*["']'active'["']/,
      /\*ngSwitchDefault/,
    ],
    editorLanguage: 'html',
    hints: ['Use [ngSwitch], *ngSwitchCase, and *ngSwitchDefault together'],
    tags: ['ngswitch', 'conditional', 'template'],
  },
  {
    id: 'fe-ng-lazy-loading',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'hard',
    title: 'Lazy Loading Route',
    text: "Write a route object: { path: 'admin', loadChildren: () => import('./admin/admin.module').then(m => m.AdminModule) }.",
    setup: 'Write the full route configuration object.',
    setupCode: `const routes = [];`,
    expected: 'Route with lazy-loaded module',
    sample: `{ path: 'admin', loadChildren: () => import('./admin/admin.module').then(m => m.AdminModule) }`,
    validPatterns: [
      /path\s*:\s*['"]admin['"]/,
      /loadChildren\s*:\s*\(\s*\)\s*=>\s*import\s*\(/,
      /\.then\s*\(\s*m\s*=>\s*m\.AdminModule\s*\)/,
    ],
    hints: ['loadChildren with dynamic import() enables code splitting'],
    tags: ['routing', 'lazy-loading', 'module'],
  },
  {
    id: 'fe-ng-route-guard',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'hard',
    title: 'Functional Route Guard',
    text: 'Write a canActivate guard using inject(): const authGuard: CanActivateFn = () => inject(AuthService).isLoggedIn();.',
    setup: 'Write the full functional guard declaration.',
    setupCode: `class AuthService { isLoggedIn() { return true; } }`,
    expected: 'Functional canActivate guard',
    sample: `const authGuard: CanActivateFn = () => inject(AuthService).isLoggedIn();`,
    validPatterns: [/const\s+authGuard\s*:\s*CanActivateFn\s*=/, /inject\s*\(\s*AuthService\s*\)/],
    hints: ['Angular 14+ supports functional route guards with inject()'],
    tags: ['routing', 'guard', 'canactivate'],
  },
  {
    id: 'fe-ng-route-resolver',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'hard',
    title: 'Functional Route Resolver',
    text: "Write a resolver: const userResolver: ResolveFn<User> = (route) => inject(UserService).getUser(route.paramMap.get('id')!);.",
    setup: 'Write the full functional resolver declaration.',
    setupCode: `class UserService { getUser(id: string) { return {}; } }`,
    expected: 'Functional route resolver',
    sample: `const userResolver: ResolveFn<User> = (route) => inject(UserService).getUser(route.paramMap.get('id')!);`,
    validPatterns: [
      /const\s+userResolver\s*:\s*ResolveFn/,
      /inject\s*\(\s*UserService\s*\)\.getUser/,
    ],
    hints: ['Functional resolvers pre-fetch data before route activation'],
    tags: ['routing', 'resolver', 'data-fetching'],
  },
  {
    id: 'fe-ng-date-pipe',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'easy',
    title: 'Date Pipe',
    text: "Write an Angular template: <p>{{ birthday | date:'fullDate' }}</p> to format a date.",
    setup: 'Write the template using the date pipe with fullDate format.',
    setupCode: `const template = '';`,
    expected: 'Template with date pipe',
    sample: `<p>{{ birthday | date:'fullDate' }}</p>`,
    validPatterns: [/\{\{\s*birthday\s*\|\s*date\s*:\s*['"]fullDate['"]\s*\}\}/],
    editorLanguage: 'html',
    hints: ['The date pipe accepts format strings like shortDate, fullDate, etc.'],
    tags: ['pipe', 'date', 'template'],
  },
  {
    id: 'fe-ng-currency-pipe',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'easy',
    title: 'Currency Pipe',
    text: "Write an Angular template: <span>{{ price | currency:'USD' }}</span> to format a price.",
    setup: 'Write the template using the currency pipe.',
    setupCode: `const template = '';`,
    expected: 'Template with currency pipe',
    sample: `<span>{{ price | currency:'USD' }}</span>`,
    validPatterns: [/\{\{\s*price\s*\|\s*currency\s*:\s*['"]USD['"]\s*\}\}/],
    editorLanguage: 'html',
    hints: ['The currency pipe formats numbers as currency with symbol'],
    tags: ['pipe', 'currency', 'template'],
  },
  {
    id: 'fe-ng-use-class',
    framework: 'angular',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'useClass Provider',
    text: 'Write a provider: { provide: LoggerService, useClass: ConsoleLoggerService }.',
    setup: 'Write the full provider object.',
    setupCode: `class LoggerService {}\nclass ConsoleLoggerService {}`,
    expected: 'Provider with useClass',
    sample: `{ provide: LoggerService, useClass: ConsoleLoggerService }`,
    validPatterns: [/provide\s*:\s*LoggerService[^}]*useClass\s*:\s*ConsoleLoggerService/],
    hints: ['useClass swaps the implementation for a given provider token'],
    tags: ['di', 'provider', 'useclass'],
  },

  // ═══════════════════════════════════════════════════════════════
  // Rendering (17 new problems)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'fe-ng-ngfor-index',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: '*ngFor with Index',
    text: 'Write an Angular template: a <li> with *ngFor="let item of items; let i = index" that displays "{{ i }}: {{ item }}".',
    setup: 'Write the <li> element with *ngFor and index.',
    setupCode: `const items = ['a', 'b', 'c'];`,
    expected: '*ngFor with index variable',
    sample: `<li *ngFor="let item of items; let i = index">{{ i }}: {{ item }}</li>`,
    validPatterns: [/\*ngFor\s*=\s*["']let\s+\w+\s+of\s+items\s*;\s*let\s+\w+\s*=\s*index["']/],
    editorLanguage: 'html',
    hints: ['Use "let i = index" to access the current loop index'],
    tags: ['ngfor', 'index', 'template'],
  },
  {
    id: 'fe-ng-ngfor-trackby',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'medium',
    title: '*ngFor with trackBy',
    text: 'Write an Angular template: a <div *ngFor="let user of users; trackBy: trackById"> with {{ user.name }}.',
    setup: 'Write the template with trackBy function reference.',
    setupCode: `const template = '';`,
    expected: '*ngFor with trackBy for performance',
    sample: `<div *ngFor="let user of users; trackBy: trackById">{{ user.name }}</div>`,
    validPatterns: [/\*ngFor\s*=\s*["']let\s+\w+\s+of\s+users\s*;\s*trackBy\s*:\s*trackById["']/],
    editorLanguage: 'html',
    hints: ['trackBy helps Angular identify items and avoid unnecessary re-renders'],
    tags: ['ngfor', 'trackby', 'performance'],
  },
  {
    id: 'fe-ng-ngfor-first-last',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'medium',
    title: '*ngFor with first/last',
    text: 'Write an Angular template: a <div *ngFor="let item of items; let isFirst = first; let isLast = last" [class.first]="isFirst" [class.last]="isLast">.',
    setup: 'Write the template with first and last variables.',
    setupCode: `const template = '';`,
    expected: '*ngFor with first and last flags',
    sample: `<div *ngFor="let item of items; let isFirst = first; let isLast = last" [class.first]="isFirst" [class.last]="isLast">{{ item }}</div>`,
    validPatterns: [/let\s+\w+\s*=\s*first/, /let\s+\w+\s*=\s*last/],
    editorLanguage: 'html',
    hints: ['*ngFor exposes first, last, even, odd boolean variables'],
    tags: ['ngfor', 'first', 'last', 'template'],
  },
  {
    id: 'fe-ng-ngif-as',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'medium',
    title: '*ngIf with as',
    text: 'Write an Angular template: <div *ngIf="user$ | async as user">{{ user.name }}</div> to unwrap and alias an Observable.',
    setup: 'Write the template with *ngIf + async pipe + as alias.',
    setupCode: `const template = '';`,
    expected: '*ngIf with async pipe and alias',
    sample: `<div *ngIf="user$ | async as user">{{ user.name }}</div>`,
    validPatterns: [/\*ngIf\s*=\s*["']user\$\s*\|\s*async\s+as\s+user["']/],
    editorLanguage: 'html',
    hints: ['Combine *ngIf with async pipe and "as" to avoid multiple subscriptions'],
    tags: ['ngif', 'async', 'alias', 'template'],
  },
  {
    id: 'fe-ng-pipe-chain',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: 'Pipe Chaining',
    text: 'Write an Angular template: <p>{{ name | uppercase | slice:0:10 }}</p> to chain pipes.',
    setup: 'Write the template chaining uppercase and slice pipes.',
    setupCode: `const template = '';`,
    expected: 'Template with chained pipes',
    sample: `<p>{{ name | uppercase | slice:0:10 }}</p>`,
    validPatterns: [/\{\{\s*name\s*\|\s*uppercase\s*\|\s*slice\s*:\s*0\s*:\s*10\s*\}\}/],
    editorLanguage: 'html',
    hints: ['Pipes can be chained with | operator from left to right'],
    tags: ['pipe', 'chaining', 'template'],
  },
  {
    id: 'fe-ng-safe-navigation',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: 'Safe Navigation Operator',
    text: 'Write an Angular template: <p>{{ user?.address?.city }}</p> using safe navigation to avoid null errors.',
    setup: 'Write the template using the ?. operator.',
    setupCode: `const template = '';`,
    expected: 'Template with safe navigation operator',
    sample: `<p>{{ user?.address?.city }}</p>`,
    validPatterns: [/\{\{\s*user\?\.address\?\.city\s*\}\}/],
    editorLanguage: 'html',
    hints: ['Use ?. in templates to safely navigate potentially null properties'],
    tags: ['safe-navigation', 'template', 'null-safe'],
  },
  {
    id: 'fe-ng-non-null-assertion',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: 'Non-Null Assertion in Template',
    text: 'Write an Angular template: <p>{{ user!.name }}</p> using the non-null assertion operator.',
    setup: 'Write the template using the ! operator.',
    setupCode: `const template = '';`,
    expected: 'Template with non-null assertion',
    sample: `<p>{{ user!.name }}</p>`,
    validPatterns: [/\{\{\s*user!\.name\s*\}\}/],
    editorLanguage: 'html',
    hints: ['Use ! to assert a value is non-null when you are certain'],
    tags: ['non-null', 'assertion', 'template'],
  },
  {
    id: 'fe-ng-component-inline-styles',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: 'Component Inline Styles',
    text: 'Write a @Component decorator with selector "app-styled" and styles: [":host { display: block; }"].',
    setup: 'Write the @Component decorator with inline styles.',
    setupCode: `class StyledComponent {}`,
    expected: '@Component with inline styles array',
    sample: `@Component({
  selector: 'app-styled',
  template: '',
  styles: [':host { display: block; }']
})`,
    validPatterns: [
      /@Component\s*\(\s*\{[^}]*styles\s*:\s*\[/,
      /:host\s*\{[^}]*display\s*:\s*block/,
    ],
    hints: ['Component styles are encapsulated using ViewEncapsulation by default'],
    tags: ['component', 'styles', 'encapsulation'],
  },
  {
    id: 'fe-ng-view-encapsulation',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'hard',
    title: 'ViewEncapsulation.None',
    text: 'Write a @Component decorator with selector "app-global" and encapsulation: ViewEncapsulation.None to disable style scoping.',
    setup: 'Write the @Component decorator with encapsulation set.',
    setupCode: `class GlobalComponent {}`,
    expected: '@Component with ViewEncapsulation.None',
    sample: `@Component({
  selector: 'app-global',
  template: '',
  encapsulation: ViewEncapsulation.None
})`,
    validPatterns: [/@Component\s*\(\s*\{[^}]*encapsulation\s*:\s*ViewEncapsulation\.None/],
    hints: ['ViewEncapsulation.None applies styles globally without scoping'],
    tags: ['component', 'encapsulation', 'styles'],
  },
  {
    id: 'fe-ng-ngfor-even-odd',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'medium',
    title: '*ngFor with even/odd',
    text: 'Write a template: <tr *ngFor="let row of rows; let isEven = even" [class.even-row]="isEven">.',
    setup: 'Write the template using even variable from *ngFor.',
    setupCode: `const template = '';`,
    expected: '*ngFor with even variable',
    sample: `<tr *ngFor="let row of rows; let isEven = even" [class.even-row]="isEven"><td>{{ row }}</td></tr>`,
    validPatterns: [/let\s+\w+\s*=\s*even/, /\[class\.even-row\]/],
    editorLanguage: 'html',
    hints: ['*ngFor exposes even and odd boolean variables for alternating styles'],
    tags: ['ngfor', 'even', 'odd', 'template'],
  },
  {
    id: 'fe-ng-component-template-url',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: 'Component with templateUrl',
    text: 'Write a @Component decorator with selector "app-page" and templateUrl: "./page.component.html".',
    setup: 'Write the @Component decorator with external template.',
    setupCode: `class PageComponent {}`,
    expected: '@Component with templateUrl',
    sample: `@Component({
  selector: 'app-page',
  templateUrl: './page.component.html'
})`,
    validPatterns: [/@Component\s*\(\s*\{[^}]*templateUrl\s*:\s*['"]\.\/page\.component\.html['"]/],
    hints: ['Use templateUrl for external template files'],
    tags: ['component', 'templateurl'],
  },
  {
    id: 'fe-ng-ngtemplate-outlet',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'hard',
    title: 'ngTemplateOutlet',
    text: 'Write a template: <ng-container *ngTemplateOutlet="headerTemplate; context: { $implicit: title }"></ng-container>.',
    setup: 'Write the ng-container with ngTemplateOutlet and context.',
    setupCode: `const template = '';`,
    expected: 'ngTemplateOutlet with context',
    sample: `<ng-container *ngTemplateOutlet="headerTemplate; context: { $implicit: title }"></ng-container>`,
    validPatterns: [
      /\*ngTemplateOutlet\s*=\s*["']headerTemplate\s*;\s*context\s*:/,
      /\$implicit\s*:\s*title/,
    ],
    editorLanguage: 'html',
    hints: ['ngTemplateOutlet renders a template with optional context data'],
    tags: ['ng-template', 'outlet', 'advanced'],
  },
  {
    id: 'fe-ng-json-pipe',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'easy',
    title: 'JSON Pipe',
    text: 'Write an Angular template: <pre>{{ data | json }}</pre> to display an object as formatted JSON.',
    setup: 'Write the template using the json pipe.',
    setupCode: `const template = '';`,
    expected: 'Template with json pipe',
    sample: `<pre>{{ data | json }}</pre>`,
    validPatterns: [/\{\{\s*data\s*\|\s*json\s*\}\}/],
    editorLanguage: 'html',
    hints: ['The json pipe serializes an object to a JSON string'],
    tags: ['pipe', 'json', 'debug'],
  },
  {
    id: 'fe-ng-conditional-attribute',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'medium',
    title: 'Conditional Attribute Binding',
    text: 'Write a template: <button [attr.disabled]="isDisabled ? \'\' : null">Submit</button> to conditionally add the disabled attribute.',
    setup: 'Write the button with conditional attribute binding.',
    setupCode: `const template = '';`,
    expected: 'Template with [attr.disabled] conditional binding',
    sample: `<button [attr.disabled]="isDisabled ? '' : null">Submit</button>`,
    validPatterns: [
      /<button[^>]*\[attr\.disabled\]\s*=\s*["']isDisabled\s*\?\s*['"]{2}\s*:\s*null["']/,
    ],
    editorLanguage: 'html',
    hints: ['Setting an attribute binding to null removes the attribute'],
    tags: ['attribute-binding', 'conditional', 'template'],
  },
  {
    id: 'fe-ng-i18n-attribute',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'medium',
    title: 'i18n Attribute',
    text: 'Write a template: <h1 i18n="site header|Main heading">Welcome to My App</h1> for internationalization.',
    setup: 'Write the element with i18n attribute.',
    setupCode: `const template = '';`,
    expected: 'Template with i18n attribute',
    sample: `<h1 i18n="site header|Main heading">Welcome to My App</h1>`,
    validPatterns: [/<h1[^>]*i18n\s*=\s*["'][^"']*["'][^>]*>Welcome/],
    editorLanguage: 'html',
    hints: ['The i18n attribute marks text for Angular i18n extraction'],
    tags: ['i18n', 'internationalization', 'template'],
  },
  {
    id: 'fe-ng-dynamic-component',
    framework: 'angular',
    category: 'Rendering',
    difficulty: 'hard',
    title: 'Dynamic Component with ViewContainerRef',
    text: 'Write a method loadComponent() that calls this.vcRef.createComponent(MyComponent) to dynamically create a component.',
    setup: 'Write the full method.',
    setupCode: `class DynamicHost {}`,
    expected: 'ViewContainerRef.createComponent call',
    sample: `loadComponent() {
  this.vcRef.clear();
  this.vcRef.createComponent(MyComponent);
}`,
    validPatterns: [/this\.vcRef\.createComponent\s*\(\s*MyComponent\s*\)/],
    hints: ['ViewContainerRef.createComponent() dynamically instantiates components'],
    tags: ['dynamic-component', 'viewcontainerref', 'advanced'],
  },

  // ═══════════════════════════════════════════════════════════════
  // Data Fetching (17 new problems)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'fe-ng-http-post',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'medium',
    title: 'HttpClient POST Request',
    text: "Call http.post('/api/users', { name: 'Alice' }) and chain .subscribe() to log the response.",
    setup: 'Write the http.post() call with body and subscribe.',
    setupCode: `const http = { post: (url: string, body: any) => ({ subscribe: (fn: any) => fn({}) }) };`,
    expected: 'http.post() with body and subscribe',
    sample: `http.post('/api/users', { name: 'Alice' }).subscribe(data => {
  console.log(data);
});`,
    validPatterns: [/http\.post\s*\(\s*['"]\/api\/users['"]/, /\.subscribe\s*\(/],
    hints: ['http.post(url, body) sends data to the server'],
    tags: ['http', 'post', 'api'],
  },
  {
    id: 'fe-ng-http-headers',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'medium',
    title: 'HttpHeaders',
    text: "Create HttpHeaders with Authorization: const headers = new HttpHeaders().set('Authorization', 'Bearer token123');.",
    setup: 'Write the HttpHeaders creation.',
    setupCode: `const HttpHeaders = class { set(key: string, value: string) { return this; } };`,
    expected: 'HttpHeaders with Authorization',
    sample: `const headers = new HttpHeaders().set('Authorization', 'Bearer token123');`,
    validPatterns: [
      /new\s+HttpHeaders\s*\(\s*\)\.set\s*\(\s*['"]Authorization['"]/,
      /Bearer\s+token123/,
    ],
    hints: ['HttpHeaders is immutable — .set() returns a new instance'],
    tags: ['http', 'headers', 'auth'],
  },
  {
    id: 'fe-ng-http-params',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'medium',
    title: 'HttpParams',
    text: "Create HttpParams: const params = new HttpParams().set('page', '1').set('limit', '10');.",
    setup: 'Write the HttpParams creation with chained set calls.',
    setupCode: `const HttpParams = class { set(key: string, value: string) { return this; } };`,
    expected: 'HttpParams with query parameters',
    sample: `const params = new HttpParams().set('page', '1').set('limit', '10');`,
    validPatterns: [
      /new\s+HttpParams\s*\(\s*\)\.set\s*\(\s*['"]page['"]/,
      /\.set\s*\(\s*['"]limit['"]/,
    ],
    hints: ['HttpParams is immutable — chain .set() calls to build params'],
    tags: ['http', 'params', 'query'],
  },
  {
    id: 'fe-ng-http-interceptor',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'hard',
    title: 'HTTP Interceptor',
    text: 'Write an intercept method: intercept(req: HttpRequest<any>, next: HttpHandler) that clones the request with an auth header and calls next.handle(authReq).',
    setup: 'Write the full intercept method.',
    setupCode: `class AuthInterceptor {}`,
    expected: 'HTTP interceptor with cloned request',
    sample: `intercept(req: HttpRequest<any>, next: HttpHandler) {
  const authReq = req.clone({ setHeaders: { Authorization: 'Bearer token' } });
  return next.handle(authReq);
}`,
    validPatterns: [
      /intercept\s*\(\s*req\s*:\s*HttpRequest/,
      /req\.clone\s*\(/,
      /next\.handle\s*\(/,
    ],
    hints: ['Interceptors clone the request to add headers, then pass to next.handle()'],
    tags: ['interceptor', 'http', 'auth'],
  },
  {
    id: 'fe-ng-rxjs-switchmap',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'medium',
    title: 'RxJS switchMap',
    text: "Use pipe and switchMap to search: input$.pipe(switchMap(term => http.get('/api/search?q=' + term))).",
    setup: 'Write the pipe chain with switchMap.',
    setupCode: `const http = { get: (url: string) => ({ subscribe: (fn: any) => fn([]) }) };\nconst input$ = { pipe: (...args: any[]) => input$ };\nconst switchMap = (fn: any) => fn;`,
    expected: 'pipe() with switchMap() for search',
    sample: `input$.pipe(
  switchMap(term => http.get('/api/search?q=' + term))
)`,
    validPatterns: [/\.pipe\s*\([^)]*switchMap\s*\(/, /http\.get\s*\(/],
    hints: ['switchMap cancels the previous inner observable when a new value arrives'],
    tags: ['rxjs', 'switchmap', 'search'],
  },
  {
    id: 'fe-ng-rxjs-catcherror',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'medium',
    title: 'RxJS catchError',
    text: 'Use pipe with catchError to handle errors: source$.pipe(catchError(err => of([]))).',
    setup: 'Write the pipe chain with catchError.',
    setupCode: `const source$ = { pipe: (...args: any[]) => source$ };\nconst catchError = (fn: any) => fn;\nconst of = (val: any) => val;`,
    expected: 'pipe() with catchError()',
    sample: `source$.pipe(
  catchError(err => of([]))
)`,
    validPatterns: [/\.pipe\s*\([^)]*catchError\s*\(/, /of\s*\(\s*\[\s*\]\s*\)/],
    hints: ['catchError returns a fallback Observable when an error occurs'],
    tags: ['rxjs', 'catcherror', 'error-handling'],
  },
  {
    id: 'fe-ng-rxjs-retry',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'medium',
    title: 'RxJS retry',
    text: "Use pipe with retry to retry failed requests: http.get('/api/data').pipe(retry(3)).",
    setup: 'Write the http.get with retry operator.',
    setupCode: `const http = { get: (url: string) => ({ pipe: (...args: any[]) => ({}) }) };\nconst retry = (count: number) => count;`,
    expected: 'http.get() with retry operator',
    sample: `http.get('/api/data').pipe(retry(3))`,
    validPatterns: [/http\.get\s*\([^)]*\)\.pipe\s*\(\s*retry\s*\(\s*3\s*\)\s*\)/],
    hints: ['retry(n) resubscribes n times on error before giving up'],
    tags: ['rxjs', 'retry', 'error-handling'],
  },
  {
    id: 'fe-ng-rxjs-debouncetime',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'easy',
    title: 'RxJS debounceTime',
    text: 'Use pipe with debounceTime: search$.pipe(debounceTime(300)) to wait 300ms before emitting.',
    setup: 'Write the pipe chain with debounceTime.',
    setupCode: `const search$ = { pipe: (...args: any[]) => search$ };\nconst debounceTime = (ms: number) => ms;`,
    expected: 'pipe() with debounceTime()',
    sample: `search$.pipe(debounceTime(300))`,
    validPatterns: [/\.pipe\s*\(\s*debounceTime\s*\(\s*300\s*\)\s*\)/],
    hints: ['debounceTime waits for a pause in emissions before passing the latest value'],
    tags: ['rxjs', 'debouncetime', 'search'],
  },
  {
    id: 'fe-ng-rxjs-distinctuntilchanged',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'easy',
    title: 'RxJS distinctUntilChanged',
    text: 'Use pipe with distinctUntilChanged: input$.pipe(distinctUntilChanged()) to avoid duplicate consecutive values.',
    setup: 'Write the pipe chain with distinctUntilChanged.',
    setupCode: `const input$ = { pipe: (...args: any[]) => input$ };\nconst distinctUntilChanged = () => null;`,
    expected: 'pipe() with distinctUntilChanged()',
    sample: `input$.pipe(distinctUntilChanged())`,
    validPatterns: [/\.pipe\s*\(\s*distinctUntilChanged\s*\(\s*\)\s*\)/],
    hints: ['distinctUntilChanged filters out consecutive duplicate values'],
    tags: ['rxjs', 'distinctuntilchanged', 'optimization'],
  },
  {
    id: 'fe-ng-rxjs-combinelatest',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'hard',
    title: 'RxJS combineLatest',
    text: 'Use combineLatest([user$, settings$]).pipe(map(([user, settings]) => ({ user, settings }))) to combine two streams.',
    setup: 'Write the combineLatest with map.',
    setupCode: `const user$ = { pipe: (...args: any[]) => user$ };\nconst settings$ = {};\nconst combineLatest = (arr: any[]) => ({ pipe: (...args: any[]) => ({}) });\nconst map = (fn: any) => fn;`,
    expected: 'combineLatest with destructured map',
    sample: `combineLatest([user$, settings$]).pipe(
  map(([user, settings]) => ({ user, settings }))
)`,
    validPatterns: [
      /combineLatest\s*\(\s*\[\s*user\$\s*,\s*settings\$\s*\]\s*\)/,
      /map\s*\(\s*\(\s*\[\s*user\s*,\s*settings\s*\]\s*\)/,
    ],
    hints: ['combineLatest emits when any source emits, combining latest values from all'],
    tags: ['rxjs', 'combinelatest', 'composition'],
  },
  {
    id: 'fe-ng-rxjs-forkjoin',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'hard',
    title: 'RxJS forkJoin',
    text: "Use forkJoin({ users: http.get('/api/users'), posts: http.get('/api/posts') }).subscribe() for parallel requests.",
    setup: 'Write the forkJoin with an object of observables.',
    setupCode: `const http = { get: (url: string) => ({ subscribe: (fn: any) => fn({}) }) };\nconst forkJoin = (obj: any) => ({ subscribe: (fn: any) => fn({}) });`,
    expected: 'forkJoin for parallel HTTP requests',
    sample: `forkJoin({
  users: http.get('/api/users'),
  posts: http.get('/api/posts')
}).subscribe(results => {
  console.log(results);
});`,
    validPatterns: [
      /forkJoin\s*\(\s*\{/,
      /http\.get\s*\(\s*['"]\/api\/users['"]/,
      /http\.get\s*\(\s*['"]\/api\/posts['"]/,
    ],
    hints: ['forkJoin waits for all observables to complete, then emits all results'],
    tags: ['rxjs', 'forkjoin', 'parallel'],
  },
  {
    id: 'fe-ng-rxjs-subject',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'easy',
    title: 'RxJS Subject',
    text: "Create a Subject and emit values: const subject = new Subject<string>(); then subject.next('hello');.",
    setup: 'Write the Subject creation and next call.',
    setupCode: `const Subject = class { next(val: any) {} subscribe(fn: any) {} };`,
    expected: 'Subject creation and emission',
    sample: `const subject = new Subject<string>();
subject.next('hello');`,
    validPatterns: [
      /new\s+Subject\s*<\s*string\s*>\s*\(\s*\)/,
      /subject\.next\s*\(\s*['"]hello['"]\s*\)/,
    ],
    hints: ['Subject is both an Observable and Observer — call .next() to emit'],
    tags: ['rxjs', 'subject', 'multicast'],
  },
  {
    id: 'fe-ng-rxjs-behaviorsubject',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'medium',
    title: 'RxJS BehaviorSubject',
    text: 'Create a BehaviorSubject with initial value: const count$ = new BehaviorSubject<number>(0); then get current value with count$.getValue().',
    setup: 'Write the BehaviorSubject creation.',
    setupCode: `const BehaviorSubject = class { constructor(val: any) {} getValue() { return 0; } next(val: any) {} };`,
    expected: 'BehaviorSubject with initial value',
    sample: `const count$ = new BehaviorSubject<number>(0);
count$.getValue();`,
    validPatterns: [/new\s+BehaviorSubject\s*<\s*number\s*>\s*\(\s*0\s*\)/, /\.getValue\s*\(\s*\)/],
    hints: ['BehaviorSubject holds a current value and emits it to new subscribers'],
    tags: ['rxjs', 'behaviorsubject', 'state'],
  },
  {
    id: 'fe-ng-rxjs-mergemap',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'hard',
    title: 'RxJS mergeMap',
    text: "Use pipe with mergeMap: ids$.pipe(mergeMap(id => http.get('/api/item/' + id))) for concurrent requests.",
    setup: 'Write the pipe chain with mergeMap.',
    setupCode: `const http = { get: (url: string) => ({ pipe: (...args: any[]) => ({}) }) };\nconst ids$ = { pipe: (...args: any[]) => ids$ };\nconst mergeMap = (fn: any) => fn;`,
    expected: 'pipe() with mergeMap() for concurrent fetching',
    sample: `ids$.pipe(
  mergeMap(id => http.get('/api/item/' + id))
)`,
    validPatterns: [/\.pipe\s*\([^)]*mergeMap\s*\(/, /http\.get\s*\(\s*['"]\/api\/item\//],
    hints: ['mergeMap subscribes to all inner observables concurrently (unlike switchMap)'],
    tags: ['rxjs', 'mergemap', 'concurrent'],
  },
  {
    id: 'fe-ng-http-typed-response',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'easy',
    title: 'Typed HTTP Response',
    text: "Call http.get<User[]>('/api/users') with a type parameter for typed responses.",
    setup: 'Write the typed http.get call.',
    setupCode: `const http = { get: (url: string) => ({ subscribe: (fn: any) => fn([]) }) };`,
    expected: 'Typed http.get<T>()',
    sample: `http.get<User[]>('/api/users')`,
    validPatterns: [/http\.get\s*<\s*User\s*\[\s*\]\s*>\s*\(\s*['"]\/api\/users['"]\s*\)/],
    hints: ['Generic type parameter on http.get<T>() gives you typed responses'],
    tags: ['http', 'typescript', 'typed'],
  },
  {
    id: 'fe-ng-rxjs-tap',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'easy',
    title: 'RxJS tap Operator',
    text: "Use pipe with tap for side effects: data$.pipe(tap(val => console.log('Received:', val))).",
    setup: 'Write the pipe chain with tap.',
    setupCode: `const data$ = { pipe: (...args: any[]) => data$ };\nconst tap = (fn: any) => fn;`,
    expected: 'pipe() with tap() for side effects',
    sample: `data$.pipe(tap(val => console.log('Received:', val)))`,
    validPatterns: [/\.pipe\s*\(\s*tap\s*\(\s*\w+\s*=>\s*console\.log/],
    hints: ['tap() performs side effects without modifying the stream'],
    tags: ['rxjs', 'tap', 'debug'],
  },
  {
    id: 'fe-ng-rxjs-filter',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'medium',
    title: 'RxJS filter Operator',
    text: 'Use the filter and map operators to transform an array: keep only even numbers and double them.',
    setup: 'Mock pipe, filter, and map operators.',
    setupCode: `const pipe = (...fns) => (arr) => fns.reduce((a, fn) => fn(a), arr);\nconst filter = (pred) => (arr) => arr.filter(pred);\nconst map = (fn) => (arr) => arr.map(fn);\nconst numbers = [1, 2, 3, 4, 5, 6];`,
    expected: [4, 8, 12],
    sample: `pipe(filter(n => n % 2 === 0), map(n => n * 2))(numbers)`,
    hints: ['Pipe composes functions left to right', 'Filter evens, then double'],
    tags: ['rxjs', 'pipe', 'filter', 'map'],
  },
  {
    id: 'fe-ng-rxjs-takeuntil',
    framework: 'angular',
    category: 'Data Fetching',
    difficulty: 'medium',
    title: 'RxJS takeUntil Operator',
    text: 'Use pipe with takeUntil to auto-unsubscribe: data$.pipe(takeUntil(this.destroy$)).subscribe(val => console.log(val));.',
    setup: 'Write the pipe chain with takeUntil and subscribe.',
    setupCode: `const data$ = { pipe: (...args: any[]) => ({ subscribe: (fn: any) => fn(null) }) };\nconst takeUntil = (notifier: any) => notifier;`,
    expected: 'pipe() with takeUntil() for auto-unsubscribe',
    sample: `data$.pipe(takeUntil(this.destroy$)).subscribe(val => console.log(val));`,
    validPatterns: [/\.pipe\s*\(\s*takeUntil\s*\(\s*this\.destroy\$\s*\)\s*\)\.subscribe/],
    hints: ['takeUntil completes the observable when the notifier emits'],
    tags: ['rxjs', 'takeuntil', 'unsubscribe'],
  },

  // ═══════════════════════════════════════════════════════════════
  // Forms & Validation (17 new problems)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'fe-ng-formgroup',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'medium',
    title: 'Reactive FormGroup',
    text: "Create a FormGroup: const form = new FormGroup({ name: new FormControl(''), email: new FormControl('') });.",
    setup: 'Write the FormGroup creation.',
    setupCode: `const FormControl = class { constructor(val: any, validators?: any) {} };\nconst FormGroup = class { constructor(controls: any) {} };`,
    expected: 'FormGroup with multiple FormControls',
    sample: `const form = new FormGroup({
  name: new FormControl(''),
  email: new FormControl('')
});`,
    validPatterns: [
      /new\s+FormGroup\s*\(\s*\{/,
      /name\s*:\s*new\s+FormControl/,
      /email\s*:\s*new\s+FormControl/,
    ],
    hints: ['FormGroup groups multiple FormControls together'],
    tags: ['reactive-forms', 'formgroup'],
  },
  {
    id: 'fe-ng-formbuilder',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'medium',
    title: 'FormBuilder Group',
    text: "Use FormBuilder: this.form = this.fb.group({ name: [''], email: ['', Validators.required] });.",
    setup: 'Write the FormBuilder group creation.',
    setupCode: `class MyComponent {}`,
    expected: 'FormBuilder.group() with validators',
    sample: `this.form = this.fb.group({
  name: [''],
  email: ['', Validators.required]
});`,
    validPatterns: [
      /this\.fb\.group\s*\(\s*\{/,
      /name\s*:\s*\[/,
      /email\s*:\s*\[[\s\S]*Validators\.required/,
    ],
    hints: ['FormBuilder provides a shorthand for creating FormGroups'],
    tags: ['reactive-forms', 'formbuilder'],
  },
  {
    id: 'fe-ng-validators-required',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'easy',
    title: 'Required Validator',
    text: "Create a FormControl with required validator: const name = new FormControl('', Validators.required);.",
    setup: 'Write the FormControl with Validators.required.',
    setupCode: `const Validators = { required: (c: any) => null };\nconst FormControl = class { constructor(val: any, validator?: any) {} };`,
    expected: 'FormControl with required validator',
    sample: `const name = new FormControl('', Validators.required);`,
    validPatterns: [/new\s+FormControl\s*\(\s*['"]{2}\s*,\s*Validators\.required\s*\)/],
    hints: ['Pass Validators.required as the second argument to FormControl'],
    tags: ['reactive-forms', 'validators', 'required'],
  },
  {
    id: 'fe-ng-validators-compose',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'medium',
    title: 'Multiple Validators',
    text: "Create a FormControl with multiple validators: new FormControl('', [Validators.required, Validators.minLength(3)]).",
    setup: 'Write the FormControl with an array of validators.',
    setupCode: `const Validators = { required: (c: any) => null, minLength: (n: number) => (c: any) => null };\nconst FormControl = class { constructor(val: any, validators?: any) {} };`,
    expected: 'FormControl with multiple validators',
    sample: `new FormControl('', [Validators.required, Validators.minLength(3)])`,
    validPatterns: [
      /new\s+FormControl\s*\(\s*['"]{2}\s*,\s*\[\s*Validators\.required\s*,\s*Validators\.minLength\s*\(\s*3\s*\)\s*\]/,
    ],
    hints: ['Pass an array of validators for multiple validation rules'],
    tags: ['reactive-forms', 'validators', 'compose'],
  },
  {
    id: 'fe-ng-validators-pattern',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'medium',
    title: 'Pattern Validator',
    text: "Create a FormControl for phone with a regex pattern: new FormControl('', Validators.pattern('^[0-9]{10}$')).",
    setup: 'Write the FormControl with pattern validator.',
    setupCode: `const Validators = { pattern: (p: string) => (c: any) => null };\nconst FormControl = class { constructor(val: any, validators?: any) {} };`,
    expected: 'FormControl with pattern validator',
    sample: `new FormControl('', Validators.pattern('^[0-9]{10}$'))`,
    validPatterns: [/new\s+FormControl\s*\([^)]*Validators\.pattern\s*\(\s*['"]\^?\[0-9\]/],
    hints: ['Validators.pattern() accepts a regex string for validation'],
    tags: ['reactive-forms', 'validators', 'pattern'],
  },
  {
    id: 'fe-ng-formarray',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'hard',
    title: 'FormArray',
    text: "Create a FormArray: const items = new FormArray([new FormControl('Item 1'), new FormControl('Item 2')]); and push a new control.",
    setup: 'Write the FormArray creation and push.',
    setupCode: `const FormControl = class { constructor(val: any) {} };\nconst FormArray = class { controls: any[] = []; constructor(ctrls: any[]) { this.controls = ctrls; } push(ctrl: any) { this.controls.push(ctrl); } };`,
    expected: 'FormArray with push',
    sample: `const items = new FormArray([new FormControl('Item 1'), new FormControl('Item 2')]);
items.push(new FormControl('Item 3'));`,
    validPatterns: [/new\s+FormArray\s*\(\s*\[/, /items\.push\s*\(\s*new\s+FormControl/],
    hints: ['FormArray manages a dynamic list of controls; use .push() to add'],
    tags: ['reactive-forms', 'formarray', 'dynamic'],
  },
  {
    id: 'fe-ng-form-template-binding',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'medium',
    title: 'Reactive Form Template Binding',
    text: 'Write a template: <form [formGroup]="myForm"><input formControlName="email" /></form>.',
    setup: 'Write the form template with reactive form binding.',
    setupCode: `const template = '';`,
    expected: 'Template with [formGroup] and formControlName',
    sample: `<form [formGroup]="myForm">
  <input formControlName="email" />
</form>`,
    validPatterns: [
      /<form[^>]*\[formGroup\]\s*=\s*["']myForm["']/,
      /formControlName\s*=\s*["']email["']/,
    ],
    editorLanguage: 'html',
    hints: ['Bind the form with [formGroup] and controls with formControlName'],
    tags: ['reactive-forms', 'template', 'binding'],
  },
  {
    id: 'fe-ng-form-error-display',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'medium',
    title: 'Form Error Display',
    text: 'Write a template: show <div class="error" *ngIf="myForm.get(\'email\')?.errors?.required">Email is required</div>.',
    setup: 'Write the conditional error message template.',
    setupCode: `const template = '';`,
    expected: 'Template with form error display',
    sample: `<div class="error" *ngIf="myForm.get('email')?.errors?.required">Email is required</div>`,
    validPatterns: [
      /\*ngIf\s*=\s*["']myForm\.get\(\s*['"]email['"]\s*\)\?\.errors\?\.required["']/,
    ],
    editorLanguage: 'html',
    hints: ['Access errors via formGroup.get(controlName)?.errors?.validatorName'],
    tags: ['reactive-forms', 'validation', 'errors'],
  },
  {
    id: 'fe-ng-custom-validator',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'hard',
    title: 'Custom Validator Function',
    text: 'Write a custom validator function that checks if a value is not "admin": function forbiddenName(control: AbstractControl) returning { forbiddenName: true } or null.',
    setup: 'Write the custom validator function.',
    setupCode: `const AbstractControl = class { value: any; };`,
    expected: 'Custom validator returning error object or null',
    sample: `function forbiddenName(control: AbstractControl) {
  return control.value === 'admin' ? { forbiddenName: true } : null;
}`,
    validPatterns: [
      /function\s+forbiddenName\s*\(\s*control/,
      /forbiddenName\s*:\s*true/,
      /:\s*null/,
    ],
    hints: ['Custom validators return an error object { key: true } or null for valid'],
    tags: ['validators', 'custom', 'reactive-forms'],
  },
  {
    id: 'fe-ng-async-validator',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'hard',
    title: 'Async Validator',
    text: 'Write an async validator that returns an Observable: function uniqueEmail(control: AbstractControl) returning of(null) for valid or of({ emailTaken: true }) after a timer(1000).',
    setup: 'Write the async validator function.',
    setupCode: `class AbstractControl { value: any; }`,
    expected: 'Async validator returning Observable',
    sample: `function uniqueEmail(control: AbstractControl) {
  return timer(1000).pipe(
    map(() => control.value === 'taken@test.com' ? { emailTaken: true } : null)
  );
}`,
    validPatterns: [
      /function\s+uniqueEmail\s*\(\s*control/,
      /timer\s*\(\s*1000\s*\)/,
      /emailTaken\s*:\s*true/,
    ],
    hints: ['Async validators return an Observable<ValidationErrors | null>'],
    tags: ['validators', 'async', 'reactive-forms'],
  },
  {
    id: 'fe-ng-form-value-changes',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'medium',
    title: 'valueChanges Observable',
    text: "Subscribe to form value changes: this.form.get('email')?.valueChanges.subscribe(value => console.log(value));.",
    setup: 'Write the valueChanges subscription.',
    setupCode: `class MyComponent {}`,
    expected: 'valueChanges subscription on form control',
    sample: `this.form.get('email')?.valueChanges.subscribe(value => console.log(value));`,
    validPatterns: [/this\.form\.get\s*\(\s*['"]email['"]\s*\)\?\.valueChanges\.subscribe/],
    hints: ['Every FormControl exposes a valueChanges Observable'],
    tags: ['reactive-forms', 'valuechanges', 'rxjs'],
  },
  {
    id: 'fe-ng-form-patchvalue',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'easy',
    title: 'patchValue on FormGroup',
    text: "Use patchValue to update part of a form: this.form.patchValue({ name: 'Alice' });.",
    setup: 'Write the patchValue call.',
    setupCode: `class MyComponent {}`,
    expected: 'FormGroup patchValue call',
    sample: `this.form.patchValue({ name: 'Alice' });`,
    validPatterns: [/this\.form\.patchValue\s*\(\s*\{[^}]*name\s*:\s*['"]Alice['"]/],
    hints: ['patchValue updates only specified controls; setValue requires all'],
    tags: ['reactive-forms', 'patchvalue'],
  },
  {
    id: 'fe-ng-form-setvalue',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'easy',
    title: 'setValue on FormGroup',
    text: "Use setValue to set all form values: this.form.setValue({ name: 'Alice', email: 'alice@test.com' });.",
    setup: 'Write the setValue call.',
    setupCode: `class MyComponent {}`,
    expected: 'FormGroup setValue call',
    sample: `this.form.setValue({ name: 'Alice', email: 'alice@test.com' });`,
    validPatterns: [/this\.form\.setValue\s*\(\s*\{[^}]*name\s*:\s*['"]Alice['"][^}]*email\s*:/],
    hints: ['setValue requires values for ALL controls in the FormGroup'],
    tags: ['reactive-forms', 'setvalue'],
  },
  {
    id: 'fe-ng-form-reset',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'easy',
    title: 'Form Reset',
    text: 'Reset a form to initial state: this.form.reset();.',
    setup: 'Write the form reset call.',
    setupCode: `class MyComponent {}`,
    expected: 'FormGroup reset call',
    sample: `this.form.reset();`,
    validPatterns: [/this\.form\.reset\s*\(\s*\)/],
    hints: ['reset() clears all values and resets status to pristine/untouched'],
    tags: ['reactive-forms', 'reset'],
  },
  {
    id: 'fe-ng-form-status',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'easy',
    title: 'Form Status Check',
    text: 'Write a template: <button [disabled]="!myForm.valid">Submit</button> to disable submit when form is invalid.',
    setup: 'Write the button with disabled binding to form validity.',
    setupCode: `const template = '';`,
    expected: 'Template with form validity check',
    sample: `<button [disabled]="!myForm.valid">Submit</button>`,
    validPatterns: [/<button[^>]*\[disabled\]\s*=\s*["']!myForm\.valid["'][^>]*>/],
    editorLanguage: 'html',
    hints: ['FormGroup exposes .valid, .invalid, .dirty, .touched properties'],
    tags: ['reactive-forms', 'validation', 'template'],
  },
  {
    id: 'fe-ng-cross-field-validator',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'hard',
    title: 'Cross-Field Validator',
    text: 'Write a cross-field validator function passwordMatch(group: AbstractControl) that checks if "password" and "confirmPassword" controls match, returning { passwordMismatch: true } or null.',
    setup: 'Write the cross-field validator function.',
    setupCode: `const AbstractControl = class { value: any; get(name: string): any { return { value: '' }; } };`,
    expected: 'Cross-field validator comparing two controls',
    sample: `function passwordMatch(group: AbstractControl) {
  const password = group.get('password')?.value;
  const confirm = group.get('confirmPassword')?.value;
  return password === confirm ? null : { passwordMismatch: true };
}`,
    validPatterns: [
      /function\s+passwordMatch\s*\(\s*group/,
      /group\.get\s*\(\s*['"]password['"]/,
      /group\.get\s*\(\s*['"]confirmPassword['"]/,
      /passwordMismatch\s*:\s*true/,
    ],
    hints: ['Cross-field validators receive the FormGroup as the control parameter'],
    tags: ['validators', 'cross-field', 'reactive-forms'],
  },
  {
    id: 'fe-ng-template-driven-form',
    framework: 'angular',
    category: 'Forms & Validation',
    difficulty: 'medium',
    title: 'Template-Driven Form',
    text: 'Write a template-driven form: <form #myForm="ngForm" (ngSubmit)="onSubmit(myForm)"> with an <input name="email" ngModel required />.',
    setup: 'Write the template-driven form template.',
    setupCode: `const template = '';`,
    expected: 'Template-driven form with ngForm and ngModel',
    sample: `<form #myForm="ngForm" (ngSubmit)="onSubmit(myForm)">
  <input name="email" ngModel required />
</form>`,
    validPatterns: [
      /#myForm\s*=\s*["']ngForm["']/,
      /\(ngSubmit\)\s*=\s*["']onSubmit\(myForm\)["']/,
      /ngModel/,
    ],
    editorLanguage: 'html',
    hints: ['Template-driven forms use #ref="ngForm", ngModel, and (ngSubmit)'],
    tags: ['template-driven', 'ngform', 'ngmodel'],
  },
];
