import type { FrontendDrillProblem } from '../types';

export const reactProblems: FrontendDrillProblem[] = [
  {
    id: 'fe-react-usestate-basic',
    framework: 'react',
    category: 'State & Lifecycle',
    difficulty: 'easy',
    title: 'useState Basic Usage',
    text: 'Call useState with initial value 42 and return just the state value (first element of the array).',
    setup: 'A mock useState function that returns [initialValue, setterFn].',
    setupCode: `const useState = (initial) => [initial, (v) => v];`,
    expected: 42,
    sample: 'useState(42)[0]',
    hints: ['useState returns an array', 'The state value is the first element'],
    tags: ['hooks', 'useState', 'basics'],
  },
  {
    id: 'fe-react-usestate-updater',
    framework: 'react',
    category: 'State & Lifecycle',
    difficulty: 'easy',
    title: 'useState Functional Update',
    text: 'Given a mock setState function, call it with a functional updater that increments the previous value by 5. Return the result when prevState is 10.',
    setup: 'A mock setState that executes the updater function with prevState=10.',
    setupCode: `const setState = (updater) => typeof updater === 'function' ? updater(10) : updater;`,
    expected: 15,
    sample: 'setState((prev) => prev + 5)',
    hints: ['Functional updater receives previous state as argument', 'Return prev + 5'],
    tags: ['hooks', 'useState', 'functional-update'],
  },
  {
    id: 'fe-react-useeffect-deps',
    framework: 'react',
    category: 'State & Lifecycle',
    difficulty: 'medium',
    title: 'useEffect Dependency Array',
    text: 'Call useEffect with an effect function that returns the string "cleanup" and a dependency array containing [a, b]. Return the result object.',
    setup: 'A mock useEffect that returns an object with effect and deps.',
    setupCode: `const useEffect = (effect, deps) => ({ effect: effect(), deps });
const a = 1, b = 2;`,
    expected: { effect: 'cleanup', deps: [1, 2] },
    sample: 'useEffect(() => "cleanup", [a, b])',
    hints: [
      'useEffect takes a function and dependency array',
      'Return value from the effect function',
    ],
    tags: ['hooks', 'useEffect', 'cleanup', 'dependencies'],
  },
  {
    id: 'fe-react-useref-init',
    framework: 'react',
    category: 'State & Lifecycle',
    difficulty: 'easy',
    title: 'useRef Initial Value',
    text: 'Call useRef with initial value "hello" and return the entire ref object.',
    setup: 'A mock useRef that returns an object with a current property.',
    setupCode: `const useRef = (initial) => ({ current: initial });`,
    expected: { current: 'hello' },
    sample: 'useRef("hello")',
    hints: [
      'useRef returns an object with a current property',
      'Pass "hello" as the initial value',
    ],
    tags: ['hooks', 'useRef', 'refs'],
  },
  {
    id: 'fe-react-usememo-compute',
    framework: 'react',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'useMemo Computation',
    text: 'Call useMemo with a function that computes the sum of array [1, 2, 3, 4, 5] and a dependency array containing the array. Return the memoized value.',
    setup: 'A mock useMemo that executes the computation function.',
    setupCode: `const useMemo = (fn, deps) => fn();
const arr = [1, 2, 3, 4, 5];`,
    expected: 15,
    sample: 'useMemo(() => arr.reduce((a, b) => a + b, 0), [arr])',
    hints: ['useMemo runs the computation function', 'Use reduce to sum the array', 'Sum is 15'],
    tags: ['hooks', 'useMemo', 'memoization', 'performance'],
  },
  {
    id: 'fe-react-usecallback-fn',
    framework: 'react',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'useCallback Function Reference',
    text: 'Call useCallback with a function that multiplies its argument by multiplier (which is 3) and dependency array [multiplier]. Then call the returned function with 7.',
    setup: 'A mock useCallback that returns the callback function.',
    setupCode: `const useCallback = (fn, deps) => fn;
const multiplier = 3;`,
    expected: 21,
    sample: 'useCallback((x) => x * multiplier, [multiplier])(7)',
    hints: [
      'useCallback returns the function itself',
      'Call the returned function with 7',
      '7 * 3 = 21',
    ],
    tags: ['hooks', 'useCallback', 'memoization', 'performance'],
  },
  {
    id: 'fe-react-conditional-render',
    framework: 'react',
    category: 'Rendering',
    difficulty: 'easy',
    title: 'Conditional Rendering Logic',
    text: 'Return "Loading..." if isLoading is true, otherwise return "Content: " + data.',
    setup: 'Variables isLoading and data are defined.',
    setupCode: `const isLoading = false;
const data = "Hello World";`,
    expected: 'Content: Hello World',
    sample: 'isLoading ? "Loading..." : "Content: " + data',
    hints: ['Use ternary operator', 'isLoading is false so return the else branch'],
    tags: ['rendering', 'conditional', 'ternary'],
  },
  {
    id: 'fe-react-list-keys',
    framework: 'react',
    category: 'Rendering',
    difficulty: 'medium',
    title: 'List Rendering with Keys',
    text: 'Map over items array to create an array of objects with shape { key: id, value: name }.',
    setup: 'An items array with id and name properties.',
    setupCode: `const items = [
  { id: 1, name: 'Apple' },
  { id: 2, name: 'Banana' },
  { id: 3, name: 'Cherry' }
];`,
    expected: [
      { key: 1, value: 'Apple' },
      { key: 2, value: 'Banana' },
      { key: 3, value: 'Cherry' },
    ],
    sample: 'items.map(item => ({ key: item.id, value: item.name }))',
    hints: ['Use map to transform the array', 'Create objects with key and value properties'],
    tags: ['rendering', 'lists', 'keys', 'map'],
  },
  {
    id: 'fe-react-async-state',
    framework: 'react',
    category: 'Data Fetching',
    difficulty: 'medium',
    title: 'Async Data State Pattern',
    text: 'Create an object representing async data state with properties: loading (true), data (null), error (null).',
    setup: 'No setup needed.',
    setupCode: ``,
    expected: { loading: true, data: null, error: null },
    sample: '({ loading: true, data: null, error: null })',
    hints: [
      'Create an object with three properties',
      'Initial state: loading is true, data and error are null',
    ],
    tags: ['data-fetching', 'async', 'state-pattern'],
  },
  {
    id: 'fe-react-form-controlled',
    framework: 'react',
    category: 'Forms & Validation',
    difficulty: 'easy',
    title: 'Controlled Input Pattern',
    text: 'Create an object representing controlled input props with value set to inputValue and onChange set to handleChange.',
    setup: 'Variables inputValue and handleChange are defined.',
    setupCode: `const inputValue = "test@example.com";
const handleChange = (e) => e.target.value;`,
    expected: { value: 'test@example.com', onChange: 'function' },
    sample: '({ value: inputValue, onChange: handleChange })',
    hints: [
      'Create object with value and onChange properties',
      'value should be inputValue',
      'onChange should be handleChange function',
    ],
    tags: ['forms', 'controlled-component', 'input'],
    validPatterns: [/value:\s*inputValue/, /onChange:\s*handleChange/],
  },
  {
    id: 'fe-react-event-handler',
    framework: 'react',
    category: 'DOM & Events',
    difficulty: 'easy',
    title: 'Event Handler Binding',
    text: 'Call the mock event handler with an event object { target: { value: "hello" } } and return event.target.value.',
    setup: 'A mock handleInput function.',
    setupCode: `const handleInput = (event) => event.target.value;`,
    expected: 'hello',
    sample: 'handleInput({ target: { value: "hello" } })',
    hints: ['Call handleInput with the event object', 'Access event.target.value'],
    tags: ['events', 'event-handler', 'synthetic-events'],
  },
  {
    id: 'fe-react-custom-hook',
    framework: 'react',
    category: 'Common Patterns',
    difficulty: 'medium',
    title: 'Custom Hook Pattern',
    text: 'Call the custom hook useToggle with initial value false and return the resulting state object.',
    setup: 'A mock useToggle hook that returns [value, toggle function].',
    setupCode: `const useToggle = (initial) => [initial, () => !initial];`,
    expected: [false, 'function'],
    sample: 'useToggle(false)',
    hints: [
      'Custom hooks return values like built-in hooks',
      'useToggle returns [boolean, function]',
    ],
    tags: ['hooks', 'custom-hooks', 'patterns'],
    validPatterns: [/useToggle\(false\)/],
  },
  {
    id: 'fe-react-props-destructure',
    framework: 'react',
    category: 'Common Patterns',
    difficulty: 'easy',
    title: 'Props Destructuring',
    text: 'Destructure name and age from the props object and return them as a string: "name is age years old".',
    setup: 'A props object with name and age.',
    setupCode: `const props = { name: 'Alice', age: 30 };`,
    expected: 'Alice is 30 years old',
    sample: 'const { name, age } = props; `${name} is ${age} years old`',
    hints: ['Use destructuring assignment', 'Combine with template literal'],
    tags: ['props', 'destructuring', 'patterns'],
  },
  {
    id: 'fe-react-effect-cleanup',
    framework: 'react',
    category: 'State & Lifecycle',
    difficulty: 'medium',
    title: 'useEffect Cleanup Function',
    text: 'Create an effect function that sets up a timer ID of 123 and returns a cleanup function that returns the string "cleared: 123".',
    setup: 'Mock useEffect available.',
    setupCode: `const useEffect = (effect, deps) => effect;`,
    expected: 'cleared: 123',
    sample: 'useEffect(() => { const id = 123; return () => "cleared: " + id; }, [])())',
    hints: [
      'Effect returns cleanup function',
      'Cleanup function should return "cleared: 123"',
      'Call the returned cleanup to get the result',
    ],
    tags: ['hooks', 'useEffect', 'cleanup', 'lifecycle'],
  },
];
