import type { Method } from '../types';

export const cMethods: Method[] = [
  // String Functions (string.h)
  { name: 'strlen', category: 'String Functions', syntax: 'strlen(str)', description: 'Returns the length of a null-terminated string.', arguments: [{ name: 'str', type: 'const char*', description: 'String to measure' }], returns: { type: 'size_t', description: 'Length excluding null terminator' }, examples: [{ code: 'strlen("hello")', output: '5' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['sizeof', 'strnlen'], notes: ['Include <string.h>'] },
  { name: 'strcpy', category: 'String Functions', syntax: 'strcpy(dest, src)', description: 'Copies a string from source to destination.', arguments: [{ name: 'dest', type: 'char*', description: 'Destination buffer' }, { name: 'src', type: 'const char*', description: 'Source string' }], returns: { type: 'char*', description: 'Pointer to destination' }, examples: [{ code: 'char dest[10]; strcpy(dest, "hello");', output: 'dest = "hello"' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['strncpy', 'memcpy'], notes: ['Unsafe - use strncpy instead'] },
  { name: 'strncpy', category: 'String Functions', syntax: 'strncpy(dest, src, n)', description: 'Copies at most n characters from source to destination.', arguments: [{ name: 'dest', type: 'char*', description: 'Destination buffer' }, { name: 'src', type: 'const char*', description: 'Source string' }, { name: 'n', type: 'size_t', description: 'Max chars to copy' }], returns: { type: 'char*', description: 'Pointer to destination' }, examples: [{ code: 'char dest[6]; strncpy(dest, "hello", 5); dest[5] = \'\\0\';', output: 'dest = "hello"' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['strcpy', 'memcpy'], notes: ['May not null-terminate if src >= n'] },
  { name: 'strcat', category: 'String Functions', syntax: 'strcat(dest, src)', description: 'Appends source string to destination.', arguments: [{ name: 'dest', type: 'char*', description: 'Destination string' }, { name: 'src', type: 'const char*', description: 'String to append' }], returns: { type: 'char*', description: 'Pointer to destination' }, examples: [{ code: 'char dest[20] = "Hello "; strcat(dest, "World");', output: '"Hello World"' }], timeComplexity: 'O(n + m)', spaceComplexity: 'O(1)', relatedMethods: ['strncat', 'strcpy'], notes: ['dest must have enough space'] },
  { name: 'strcmp', category: 'String Functions', syntax: 'strcmp(s1, s2)', description: 'Compares two strings lexicographically.', arguments: [{ name: 's1', type: 'const char*', description: 'First string' }, { name: 's2', type: 'const char*', description: 'Second string' }], returns: { type: 'int', description: '<0 if s1<s2, 0 if equal, >0 if s1>s2' }, examples: [{ code: 'strcmp("abc", "abd")', output: '< 0' }], timeComplexity: 'O(min(n,m))', spaceComplexity: 'O(1)', relatedMethods: ['strncmp', 'strcasecmp'] },
  { name: 'strncmp', category: 'String Functions', syntax: 'strncmp(s1, s2, n)', description: 'Compares at most n characters of two strings.', arguments: [{ name: 's1', type: 'const char*', description: 'First string' }, { name: 's2', type: 'const char*', description: 'Second string' }, { name: 'n', type: 'size_t', description: 'Max chars to compare' }], returns: { type: 'int', description: 'Comparison result' }, examples: [{ code: 'strncmp("hello", "help", 3)', output: '0' }], timeComplexity: 'O(min(n,m))', spaceComplexity: 'O(1)', relatedMethods: ['strcmp'] },
  { name: 'strchr', category: 'String Functions', syntax: 'strchr(str, c)', description: 'Finds first occurrence of a character in a string.', arguments: [{ name: 'str', type: 'const char*', description: 'String to search' }, { name: 'c', type: 'int', description: 'Character to find' }], returns: { type: 'char*', description: 'Pointer to char or NULL' }, examples: [{ code: 'strchr("hello", \'l\')', output: 'Pointer to first "l"' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['strrchr', 'strstr'] },
  { name: 'strrchr', category: 'String Functions', syntax: 'strrchr(str, c)', description: 'Finds last occurrence of a character in a string.', arguments: [{ name: 'str', type: 'const char*', description: 'String to search' }, { name: 'c', type: 'int', description: 'Character to find' }], returns: { type: 'char*', description: 'Pointer to char or NULL' }, examples: [{ code: 'strrchr("hello", \'l\')', output: 'Pointer to second "l"' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['strchr', 'strstr'] },
  { name: 'strstr', category: 'String Functions', syntax: 'strstr(haystack, needle)', description: 'Finds first occurrence of substring.', arguments: [{ name: 'haystack', type: 'const char*', description: 'String to search' }, { name: 'needle', type: 'const char*', description: 'Substring to find' }], returns: { type: 'char*', description: 'Pointer to match or NULL' }, examples: [{ code: 'strstr("hello world", "world")', output: 'Pointer to "world"' }], timeComplexity: 'O(n * m)', spaceComplexity: 'O(1)', relatedMethods: ['strchr', 'strpbrk'] },
  { name: 'strtok', category: 'String Functions', syntax: 'strtok(str, delim)', description: 'Tokenizes a string using delimiter characters.', arguments: [{ name: 'str', type: 'char*', description: 'String to tokenize (NULL for subsequent calls)' }, { name: 'delim', type: 'const char*', description: 'Delimiter characters' }], returns: { type: 'char*', description: 'Next token or NULL' }, examples: [{ code: 'char s[] = "a,b,c";\nstrtok(s, ",");', output: '"a"' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['strtok_r'], notes: ['Modifies original string; not thread-safe'] },

  // Memory Functions (string.h)
  { name: 'memcpy', category: 'Memory Functions', syntax: 'memcpy(dest, src, n)', description: 'Copies n bytes from source to destination.', arguments: [{ name: 'dest', type: 'void*', description: 'Destination' }, { name: 'src', type: 'const void*', description: 'Source' }, { name: 'n', type: 'size_t', description: 'Bytes to copy' }], returns: { type: 'void*', description: 'Pointer to destination' }, examples: [{ code: 'int src[] = {1,2,3}; int dest[3];\nmemcpy(dest, src, sizeof(src));', output: 'dest = {1,2,3}' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['memmove', 'memset'], notes: ['Undefined if regions overlap'] },
  { name: 'memmove', category: 'Memory Functions', syntax: 'memmove(dest, src, n)', description: 'Copies n bytes, handles overlapping regions safely.', arguments: [{ name: 'dest', type: 'void*', description: 'Destination' }, { name: 'src', type: 'const void*', description: 'Source' }, { name: 'n', type: 'size_t', description: 'Bytes to copy' }], returns: { type: 'void*', description: 'Pointer to destination' }, examples: [{ code: 'char s[] = "hello";\nmemmove(s+1, s, 4);', output: 's = "hhell"' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['memcpy'] },
  { name: 'memset', category: 'Memory Functions', syntax: 'memset(ptr, value, n)', description: 'Fills n bytes of memory with a value.', arguments: [{ name: 'ptr', type: 'void*', description: 'Pointer to memory' }, { name: 'value', type: 'int', description: 'Value to set (as unsigned char)' }, { name: 'n', type: 'size_t', description: 'Number of bytes' }], returns: { type: 'void*', description: 'Pointer to memory' }, examples: [{ code: 'char buf[10];\nmemset(buf, 0, 10);', output: 'buf filled with zeros' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['memcpy', 'calloc'] },
  { name: 'memcmp', category: 'Memory Functions', syntax: 'memcmp(ptr1, ptr2, n)', description: 'Compares n bytes of two memory regions.', arguments: [{ name: 'ptr1', type: 'const void*', description: 'First region' }, { name: 'ptr2', type: 'const void*', description: 'Second region' }, { name: 'n', type: 'size_t', description: 'Bytes to compare' }], returns: { type: 'int', description: '<0, 0, or >0' }, examples: [{ code: 'int a[] = {1,2}; int b[] = {1,2};\nmemcmp(a, b, sizeof(a));', output: '0' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['strcmp'] },

  // Memory Allocation (stdlib.h)
  { name: 'malloc', category: 'Memory Allocation', syntax: 'malloc(size)', description: 'Allocates size bytes of uninitialized memory.', arguments: [{ name: 'size', type: 'size_t', description: 'Bytes to allocate' }], returns: { type: 'void*', description: 'Pointer to memory or NULL' }, examples: [{ code: 'int* arr = (int*)malloc(5 * sizeof(int));', output: 'Allocates space for 5 ints' }], timeComplexity: 'O(1) or O(n)', spaceComplexity: 'O(n)', relatedMethods: ['calloc', 'realloc', 'free'], notes: ['Include <stdlib.h>'] },
  { name: 'calloc', category: 'Memory Allocation', syntax: 'calloc(num, size)', description: 'Allocates memory for an array and initializes to zero.', arguments: [{ name: 'num', type: 'size_t', description: 'Number of elements' }, { name: 'size', type: 'size_t', description: 'Size of each element' }], returns: { type: 'void*', description: 'Pointer to zeroed memory or NULL' }, examples: [{ code: 'int* arr = (int*)calloc(5, sizeof(int));', output: 'Array of 5 zeros' }], timeComplexity: 'O(n)', spaceComplexity: 'O(n)', relatedMethods: ['malloc', 'realloc', 'free'] },
  { name: 'realloc', category: 'Memory Allocation', syntax: 'realloc(ptr, size)', description: 'Resizes a previously allocated memory block.', arguments: [{ name: 'ptr', type: 'void*', description: 'Pointer to resize' }, { name: 'size', type: 'size_t', description: 'New size' }], returns: { type: 'void*', description: 'Pointer to resized memory or NULL' }, examples: [{ code: 'arr = (int*)realloc(arr, 10 * sizeof(int));', output: 'Resizes to 10 ints' }], timeComplexity: 'O(n)', spaceComplexity: 'O(n)', relatedMethods: ['malloc', 'free'], notes: ['May move the memory block'] },
  { name: 'free', category: 'Memory Allocation', syntax: 'free(ptr)', description: 'Deallocates memory previously allocated.', arguments: [{ name: 'ptr', type: 'void*', description: 'Pointer to free' }], returns: { type: 'void', description: 'No return value' }, examples: [{ code: 'free(arr);\narr = NULL;', output: 'Memory freed' }], timeComplexity: 'O(1)', spaceComplexity: 'O(1)', relatedMethods: ['malloc', 'calloc'], notes: ['Set pointer to NULL after freeing'] },

  // Standard Library (stdlib.h)
  { name: 'atoi', category: 'Standard Library', syntax: 'atoi(str)', description: 'Converts string to integer.', arguments: [{ name: 'str', type: 'const char*', description: 'String to convert' }], returns: { type: 'int', description: 'Integer value' }, examples: [{ code: 'atoi("42")', output: '42' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['atol', 'strtol', 'itoa'], notes: ['No error checking; use strtol instead'] },
  { name: 'strtol', category: 'Standard Library', syntax: 'strtol(str, endptr, base)', description: 'Converts string to long with error detection.', arguments: [{ name: 'str', type: 'const char*', description: 'String to convert' }, { name: 'endptr', type: 'char**', description: 'End pointer' }, { name: 'base', type: 'int', description: 'Number base (0, 2-36)' }], returns: { type: 'long', description: 'Converted value' }, examples: [{ code: 'strtol("42", NULL, 10)', output: '42' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['atoi', 'strtod'] },
  { name: 'qsort', category: 'Standard Library', syntax: 'qsort(base, nmemb, size, compar)', description: 'Sorts an array using quicksort.', arguments: [{ name: 'base', type: 'void*', description: 'Array to sort' }, { name: 'nmemb', type: 'size_t', description: 'Number of elements' }, { name: 'size', type: 'size_t', description: 'Size of each element' }, { name: 'compar', type: 'function', description: 'Comparison function' }], returns: { type: 'void', description: 'No return value' }, examples: [{ code: 'int cmp(const void* a, const void* b) {\n  return *(int*)a - *(int*)b;\n}\nqsort(arr, n, sizeof(int), cmp);', output: 'Sorted array' }], timeComplexity: 'O(n log n)', spaceComplexity: 'O(log n)', relatedMethods: ['bsearch'] },
  { name: 'bsearch', category: 'Standard Library', syntax: 'bsearch(key, base, nmemb, size, compar)', description: 'Binary search in a sorted array.', arguments: [{ name: 'key', type: 'const void*', description: 'Value to find' }, { name: 'base', type: 'const void*', description: 'Sorted array' }, { name: 'nmemb', type: 'size_t', description: 'Number of elements' }, { name: 'size', type: 'size_t', description: 'Size of each element' }, { name: 'compar', type: 'function', description: 'Comparison function' }], returns: { type: 'void*', description: 'Pointer to match or NULL' }, examples: [{ code: 'int key = 5;\nint* result = bsearch(&key, arr, n, sizeof(int), cmp);', output: 'Pointer to 5 or NULL' }], timeComplexity: 'O(log n)', spaceComplexity: 'O(1)', relatedMethods: ['qsort'] },
  { name: 'abs', category: 'Standard Library', syntax: 'abs(n)', description: 'Returns absolute value of integer.', arguments: [{ name: 'n', type: 'int', description: 'Integer value' }], returns: { type: 'int', description: 'Absolute value' }, examples: [{ code: 'abs(-5)', output: '5' }], timeComplexity: 'O(1)', spaceComplexity: 'O(1)', relatedMethods: ['labs', 'fabs'] },
  { name: 'rand', category: 'Standard Library', syntax: 'rand()', description: 'Returns a pseudo-random integer.', arguments: [], returns: { type: 'int', description: 'Random number 0 to RAND_MAX' }, examples: [{ code: 'int r = rand() % 100;', output: 'Random 0-99' }], timeComplexity: 'O(1)', spaceComplexity: 'O(1)', relatedMethods: ['srand'], notes: ['Seed with srand() first'] },
  { name: 'srand', category: 'Standard Library', syntax: 'srand(seed)', description: 'Seeds the random number generator.', arguments: [{ name: 'seed', type: 'unsigned int', description: 'Seed value' }], returns: { type: 'void', description: 'No return value' }, examples: [{ code: 'srand(time(NULL));', output: 'Seeds with current time' }], timeComplexity: 'O(1)', spaceComplexity: 'O(1)', relatedMethods: ['rand'] },

  // Input/Output (stdio.h)
  { name: 'printf', category: 'Input/Output', syntax: 'printf(format, ...)', description: 'Prints formatted output to stdout.', arguments: [{ name: 'format', type: 'const char*', description: 'Format string' }, { name: '...', type: 'variadic', description: 'Values to print' }], returns: { type: 'int', description: 'Characters printed' }, examples: [{ code: 'printf("Hello %s, you are %d", "Alice", 30);', output: 'Hello Alice, you are 30' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['fprintf', 'sprintf', 'scanf'] },
  { name: 'sprintf', category: 'Input/Output', syntax: 'sprintf(buffer, format, ...)', description: 'Prints formatted output to a string buffer.', arguments: [{ name: 'buffer', type: 'char*', description: 'Destination buffer' }, { name: 'format', type: 'const char*', description: 'Format string' }], returns: { type: 'int', description: 'Characters written' }, examples: [{ code: 'char buf[50];\nsprintf(buf, "%d + %d = %d", 2, 3, 5);', output: '"2 + 3 = 5"' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['snprintf', 'printf'], notes: ['Use snprintf for safety'] },
  { name: 'scanf', category: 'Input/Output', syntax: 'scanf(format, ...)', description: 'Reads formatted input from stdin.', arguments: [{ name: 'format', type: 'const char*', description: 'Format string' }, { name: '...', type: 'variadic', description: 'Pointers to store values' }], returns: { type: 'int', description: 'Number of items read' }, examples: [{ code: 'int n; scanf("%d", &n);', output: 'Reads integer into n' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['fscanf', 'sscanf', 'printf'] },
  { name: 'fgets', category: 'Input/Output', syntax: 'fgets(str, n, stream)', description: 'Reads a line from a stream into a buffer.', arguments: [{ name: 'str', type: 'char*', description: 'Buffer' }, { name: 'n', type: 'int', description: 'Max chars' }, { name: 'stream', type: 'FILE*', description: 'Input stream' }], returns: { type: 'char*', description: 'Buffer or NULL' }, examples: [{ code: 'char line[100];\nfgets(line, 100, stdin);', output: 'Reads line with newline' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['fputs', 'gets'], notes: ['Safer than gets()'] },
];

export default cMethods;
