import type { Method } from '../types';

export const cppMethods: Method[] = [
  // ============================================================
  // Vector Methods
  // ============================================================
  {
    name: 'push_back',
    category: 'Vector Methods',
    syntax: 'vector.push_back(value)',
    description: 'Adds an element to the end of the vector. May cause reallocation if capacity is exceeded.',
    arguments: [
      { name: 'value', type: 'T', description: 'The value to add to the vector' },
    ],
    returns: { type: 'void', description: 'No return value' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3};\nv.push_back(4);', output: 'v = {1, 2, 3, 4}' },
      { code: 'vector<string> v;\nv.push_back("hello");', output: 'v = {"hello"}' },
    ],
    timeComplexity: 'O(1) amortized',
    spaceComplexity: 'O(1) amortized',
    relatedMethods: ['emplace_back', 'pop_back', 'insert'],
  },
  {
    name: 'pop_back',
    category: 'Vector Methods',
    syntax: 'vector.pop_back()',
    description: 'Removes the last element from the vector. Does not return the removed element.',
    arguments: [],
    returns: { type: 'void', description: 'No return value' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3};\nv.pop_back();', output: 'v = {1, 2}' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['push_back', 'back', 'erase'],
    notes: ['Calling on empty vector is undefined behavior'],
  },
  {
    name: 'emplace_back',
    category: 'Vector Methods',
    syntax: 'vector.emplace_back(args...)',
    description: 'Constructs an element in-place at the end of the vector. More efficient than push_back for complex types.',
    arguments: [
      { name: 'args', type: 'Args&&...', description: 'Arguments to forward to the element constructor' },
    ],
    returns: { type: 'reference', description: 'Reference to the inserted element (C++17)' },
    examples: [
      { code: 'vector<pair<int, string>> v;\nv.emplace_back(1, "one");', output: 'v = {{1, "one"}}' },
      { code: 'vector<pair<string, int>> data;\ndata.emplace_back("key", 42);', output: 'Constructs pair in-place' },
    ],
    timeComplexity: 'O(1) amortized',
    spaceComplexity: 'O(1) amortized',
    relatedMethods: ['push_back', 'emplace', 'insert'],
    sinceVersion: 'C++11',
  },
  {
    name: 'size',
    category: 'Vector Methods',
    syntax: 'vector.size()',
    description: 'Returns the number of elements in the vector.',
    arguments: [],
    returns: { type: 'size_type', description: 'Number of elements' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3};\nv.size();', output: '3' },
      { code: 'vector<int> v;\nv.size();', output: '0' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['empty', 'capacity', 'max_size'],
  },
  {
    name: 'empty',
    category: 'Vector Methods',
    syntax: 'vector.empty()',
    description: 'Checks if the vector has no elements.',
    arguments: [],
    returns: { type: 'bool', description: 'true if empty, false otherwise' },
    examples: [
      { code: 'vector<int> v;\nv.empty();', output: 'true' },
      { code: 'vector<int> v = {1};\nv.empty();', output: 'false' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['size', 'clear'],
  },
  {
    name: 'at',
    category: 'Vector Methods',
    syntax: 'vector.at(index)',
    description: 'Returns a reference to the element at specified position with bounds checking.',
    arguments: [
      { name: 'index', type: 'size_type', description: 'Position of the element' },
    ],
    returns: { type: 'reference', description: 'Reference to the element' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3};\nv.at(1);', output: '2' },
      { code: 'v.at(10);', output: 'throws std::out_of_range' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['operator[]', 'front', 'back'],
    notes: ['Throws out_of_range if index >= size(). Use operator[] for unchecked access.'],
  },
  {
    name: 'front',
    category: 'Vector Methods',
    syntax: 'vector.front()',
    description: 'Returns a reference to the first element in the vector.',
    arguments: [],
    returns: { type: 'reference', description: 'Reference to the first element' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3};\nv.front();', output: '1' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['back', 'at', 'begin'],
    notes: ['Calling on empty vector is undefined behavior'],
  },
  {
    name: 'back',
    category: 'Vector Methods',
    syntax: 'vector.back()',
    description: 'Returns a reference to the last element in the vector.',
    arguments: [],
    returns: { type: 'reference', description: 'Reference to the last element' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3};\nv.back();', output: '3' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['front', 'at', 'end'],
    notes: ['Calling on empty vector is undefined behavior'],
  },
  {
    name: 'clear',
    category: 'Vector Methods',
    syntax: 'vector.clear()',
    description: 'Removes all elements from the vector. Capacity remains unchanged.',
    arguments: [],
    returns: { type: 'void', description: 'No return value' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3};\nv.clear();\nv.size();', output: '0' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['erase', 'resize', 'shrink_to_fit'],
  },
  {
    name: 'insert',
    category: 'Vector Methods',
    syntax: 'vector.insert(position, value)',
    description: 'Inserts elements at the specified position in the vector.',
    arguments: [
      { name: 'position', type: 'iterator', description: 'Position where to insert' },
      { name: 'value', type: 'T', description: 'Value to insert' },
    ],
    returns: { type: 'iterator', description: 'Iterator pointing to the inserted element' },
    examples: [
      { code: 'vector<int> v = {1, 3};\nv.insert(v.begin() + 1, 2);', output: 'v = {1, 2, 3}' },
      { code: 'v.insert(v.end(), 4);', output: 'v = {1, 2, 3, 4}' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1) or O(n) with reallocation',
    relatedMethods: ['emplace', 'push_back', 'erase'],
  },
  {
    name: 'erase',
    category: 'Vector Methods',
    syntax: 'vector.erase(position) | vector.erase(first, last)',
    description: 'Removes elements from the vector at the specified position or range.',
    arguments: [
      { name: 'position', type: 'iterator', description: 'Position of element to remove' },
      { name: 'first, last', type: 'iterator', description: 'Range of elements to remove', optional: true },
    ],
    returns: { type: 'iterator', description: 'Iterator following the last removed element' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3, 4};\nv.erase(v.begin() + 1);', output: 'v = {1, 3, 4}' },
      { code: 'v.erase(v.begin(), v.begin() + 2);', output: 'v = {3, 4}' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['insert', 'clear', 'pop_back'],
  },
  {
    name: 'reserve',
    category: 'Vector Methods',
    syntax: 'vector.reserve(new_capacity)',
    description: 'Requests that the vector capacity be at least enough to contain n elements.',
    arguments: [
      { name: 'new_capacity', type: 'size_type', description: 'Minimum capacity to reserve' },
    ],
    returns: { type: 'void', description: 'No return value' },
    examples: [
      { code: 'vector<int> v;\nv.reserve(1000);\nv.capacity();', output: '>= 1000' },
    ],
    timeComplexity: 'O(n) if reallocation occurs',
    spaceComplexity: 'O(n)',
    relatedMethods: ['capacity', 'shrink_to_fit', 'resize'],
    notes: ['Use to avoid repeated reallocations when final size is known'],
  },
  {
    name: 'resize',
    category: 'Vector Methods',
    syntax: 'vector.resize(count, value)',
    description: 'Resizes the container to contain count elements.',
    arguments: [
      { name: 'count', type: 'size_type', description: 'New size of the container' },
      { name: 'value', type: 'T', description: 'Value to initialize new elements with', optional: true },
    ],
    returns: { type: 'void', description: 'No return value' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3};\nv.resize(5);', output: 'v = {1, 2, 3, 0, 0}' },
      { code: 'v.resize(2);', output: 'v = {1, 2}' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['reserve', 'size', 'clear'],
  },

  // ============================================================
  // String Methods
  // ============================================================
  {
    name: 'substr',
    category: 'String Methods',
    syntax: 'string.substr(pos, count)',
    description: 'Returns a substring starting at pos with length count.',
    arguments: [
      { name: 'pos', type: 'size_type', description: 'Starting position', defaultValue: '0' },
      { name: 'count', type: 'size_type', description: 'Length of substring', optional: true, defaultValue: 'npos' },
    ],
    returns: { type: 'string', description: 'The substring' },
    examples: [
      { code: 'string s = "Hello World";\ns.substr(0, 5);', output: '"Hello"' },
      { code: 's.substr(6);', output: '"World"' },
    ],
    timeComplexity: 'O(count)',
    spaceComplexity: 'O(count)',
    relatedMethods: ['find', 'compare', 'replace'],
  },
  {
    name: 'find',
    category: 'String Methods',
    syntax: 'string.find(str, pos)',
    description: 'Finds the first occurrence of the substring. Returns npos if not found.',
    arguments: [
      { name: 'str', type: 'string', description: 'Substring to search for' },
      { name: 'pos', type: 'size_type', description: 'Position to start searching', optional: true, defaultValue: '0' },
    ],
    returns: { type: 'size_type', description: 'Position of first match, or npos if not found' },
    examples: [
      { code: 'string s = "Hello World";\ns.find("World");', output: '6' },
      { code: 's.find("xyz");', output: 'string::npos' },
    ],
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['rfind', 'find_first_of', 'find_last_of'],
  },
  {
    name: 'append',
    category: 'String Methods',
    syntax: 'string.append(str)',
    description: 'Appends characters to the end of the string.',
    arguments: [
      { name: 'str', type: 'string', description: 'String to append' },
    ],
    returns: { type: 'string&', description: 'Reference to the modified string' },
    examples: [
      { code: 'string s = "Hello";\ns.append(" World");', output: '"Hello World"' },
      { code: 's.append(3, \'!\');', output: '"Hello World!!!"' },
    ],
    timeComplexity: 'O(m) where m is length of appended string',
    spaceComplexity: 'O(m)',
    relatedMethods: ['operator+=', 'push_back', 'insert'],
  },
  {
    name: 'replace',
    category: 'String Methods',
    syntax: 'string.replace(pos, count, str)',
    description: 'Replaces part of the string with another string.',
    arguments: [
      { name: 'pos', type: 'size_type', description: 'Start position' },
      { name: 'count', type: 'size_type', description: 'Number of characters to replace' },
      { name: 'str', type: 'string', description: 'Replacement string' },
    ],
    returns: { type: 'string&', description: 'Reference to the modified string' },
    examples: [
      { code: 'string s = "Hello World";\ns.replace(6, 5, "C++");', output: '"Hello C++"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['substr', 'erase', 'insert'],
  },
  {
    name: 'c_str',
    category: 'String Methods',
    syntax: 'string.c_str()',
    description: 'Returns a pointer to a null-terminated character array.',
    arguments: [],
    returns: { type: 'const char*', description: 'Pointer to null-terminated string' },
    examples: [
      { code: 'string s = "Hello";\nconst char* cstr = s.c_str();', output: '"Hello\\0"' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['data', 'size', 'length'],
    notes: ['Pointer may be invalidated by string modifications'],
  },
  {
    name: 'compare',
    category: 'String Methods',
    syntax: 'string.compare(str)',
    description: 'Compares two strings lexicographically.',
    arguments: [
      { name: 'str', type: 'string', description: 'String to compare with' },
    ],
    returns: { type: 'int', description: '0 if equal, <0 if less, >0 if greater' },
    examples: [
      { code: 'string s1 = "abc";\ns1.compare("abc");', output: '0' },
      { code: 'string s1 = "abc";\ns1.compare("abd");', output: '< 0' },
      { code: 'string s1 = "abd";\ns1.compare("abc");', output: '> 0' },
    ],
    timeComplexity: 'O(min(n, m))',
    spaceComplexity: 'O(1)',
    relatedMethods: ['operator==', 'operator<'],
  },

  // ============================================================
  // Algorithm Library
  // ============================================================
  {
    name: 'sort',
    category: 'Algorithm Library',
    syntax: 'std::sort(first, last, comp)',
    description: 'Sorts elements in the range [first, last) in ascending order or using a custom comparator.',
    arguments: [
      { name: 'first', type: 'RandomIt', description: 'Iterator to the beginning' },
      { name: 'last', type: 'RandomIt', description: 'Iterator to the end' },
      { name: 'comp', type: 'Compare', description: 'Comparison function', optional: true },
    ],
    returns: { type: 'void', description: 'No return value' },
    examples: [
      { code: 'vector<int> v = {3, 1, 4, 1, 5};\nsort(v.begin(), v.end());', output: 'v = {1, 1, 3, 4, 5}' },
      { code: 'sort(v.begin(), v.end(), greater<int>());', output: 'v = {5, 4, 3, 1, 1}' },
    ],
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(log n)',
    relatedMethods: ['stable_sort', 'partial_sort', 'nth_element'],
    notes: ['C++20: Use std::ranges::sort for cleaner syntax', 'Comparator must define strict weak ordering'],
  },
  {
    name: 'binary_search',
    category: 'Algorithm Library',
    syntax: 'std::binary_search(first, last, value)',
    description: 'Checks if an element exists in a sorted range.',
    arguments: [
      { name: 'first', type: 'ForwardIt', description: 'Iterator to the beginning' },
      { name: 'last', type: 'ForwardIt', description: 'Iterator to the end' },
      { name: 'value', type: 'T', description: 'Value to search for' },
    ],
    returns: { type: 'bool', description: 'true if found, false otherwise' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3, 4, 5};\nbinary_search(v.begin(), v.end(), 3);', output: 'true' },
      { code: 'binary_search(v.begin(), v.end(), 10);', output: 'false' },
    ],
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['lower_bound', 'upper_bound', 'equal_range'],
    notes: ['Range must be sorted'],
  },
  {
    name: 'lower_bound',
    category: 'Algorithm Library',
    syntax: 'std::lower_bound(first, last, value)',
    description: 'Returns iterator to first element not less than value in sorted range.',
    arguments: [
      { name: 'first', type: 'ForwardIt', description: 'Iterator to the beginning' },
      { name: 'last', type: 'ForwardIt', description: 'Iterator to the end' },
      { name: 'value', type: 'T', description: 'Value to compare elements to' },
    ],
    returns: { type: 'ForwardIt', description: 'Iterator to first element >= value' },
    examples: [
      { code: 'vector<int> v = {1, 2, 4, 5, 5, 6};\nauto it = lower_bound(v.begin(), v.end(), 5);', output: 'Iterator to first 5 (index 3)' },
      { code: 'lower_bound(v.begin(), v.end(), 3);', output: 'Iterator to 4 (index 2)' },
    ],
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['upper_bound', 'binary_search', 'equal_range'],
  },
  {
    name: 'upper_bound',
    category: 'Algorithm Library',
    syntax: 'std::upper_bound(first, last, value)',
    description: 'Returns iterator to first element greater than value in sorted range.',
    arguments: [
      { name: 'first', type: 'ForwardIt', description: 'Iterator to the beginning' },
      { name: 'last', type: 'ForwardIt', description: 'Iterator to the end' },
      { name: 'value', type: 'T', description: 'Value to compare elements to' },
    ],
    returns: { type: 'ForwardIt', description: 'Iterator to first element > value' },
    examples: [
      { code: 'vector<int> v = {1, 2, 4, 5, 5, 6};\nauto it = upper_bound(v.begin(), v.end(), 5);', output: 'Iterator to 6 (index 5)' },
    ],
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['lower_bound', 'binary_search', 'equal_range'],
  },
  {
    name: 'find',
    category: 'Algorithm Library',
    syntax: 'std::find(first, last, value)',
    description: 'Finds the first element equal to value in the range.',
    arguments: [
      { name: 'first', type: 'InputIt', description: 'Iterator to the beginning' },
      { name: 'last', type: 'InputIt', description: 'Iterator to the end' },
      { name: 'value', type: 'T', description: 'Value to search for' },
    ],
    returns: { type: 'InputIt', description: 'Iterator to the element, or last if not found' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3, 4};\nauto it = find(v.begin(), v.end(), 3);', output: 'Iterator to 3' },
      { code: 'find(v.begin(), v.end(), 10);', output: 'v.end()' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['find_if', 'find_if_not', 'count'],
  },
  {
    name: 'find_if',
    category: 'Algorithm Library',
    syntax: 'std::find_if(first, last, predicate)',
    description: 'Finds the first element satisfying the predicate.',
    arguments: [
      { name: 'first', type: 'InputIt', description: 'Iterator to the beginning' },
      { name: 'last', type: 'InputIt', description: 'Iterator to the end' },
      { name: 'predicate', type: 'UnaryPredicate', description: 'Function returning bool' },
    ],
    returns: { type: 'InputIt', description: 'Iterator to the element, or last if not found' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3, 4, 5};\nauto it = find_if(v.begin(), v.end(), [](int n) { return n > 3; });', output: 'Iterator to 4' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['find', 'find_if_not', 'any_of'],
  },
  {
    name: 'count',
    category: 'Algorithm Library',
    syntax: 'std::count(first, last, value)',
    description: 'Counts the number of elements equal to value.',
    arguments: [
      { name: 'first', type: 'InputIt', description: 'Iterator to the beginning' },
      { name: 'last', type: 'InputIt', description: 'Iterator to the end' },
      { name: 'value', type: 'T', description: 'Value to count' },
    ],
    returns: { type: 'difference_type', description: 'Number of elements equal to value' },
    examples: [
      { code: 'vector<int> v = {1, 2, 2, 3, 2};\ncount(v.begin(), v.end(), 2);', output: '3' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['count_if', 'find', 'any_of'],
  },
  {
    name: 'reverse',
    category: 'Algorithm Library',
    syntax: 'std::reverse(first, last)',
    description: 'Reverses the order of elements in the range.',
    arguments: [
      { name: 'first', type: 'BidirIt', description: 'Iterator to the beginning' },
      { name: 'last', type: 'BidirIt', description: 'Iterator to the end' },
    ],
    returns: { type: 'void', description: 'No return value' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3, 4};\nreverse(v.begin(), v.end());', output: 'v = {4, 3, 2, 1}' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['reverse_copy', 'rotate'],
  },
  {
    name: 'unique',
    category: 'Algorithm Library',
    syntax: 'std::unique(first, last)',
    description: 'Removes consecutive duplicate elements. Usually used with erase idiom.',
    arguments: [
      { name: 'first', type: 'ForwardIt', description: 'Iterator to the beginning' },
      { name: 'last', type: 'ForwardIt', description: 'Iterator to the end' },
    ],
    returns: { type: 'ForwardIt', description: 'Iterator to the new end of the range' },
    examples: [
      { code: 'vector<int> v = {1, 1, 2, 2, 3};\nauto last = unique(v.begin(), v.end());\nv.erase(last, v.end());', output: 'v = {1, 2, 3}' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['unique_copy', 'remove', 'remove_if'],
    notes: ['Sort first to remove all duplicates, not just consecutive ones'],
  },
  {
    name: 'max_element',
    category: 'Algorithm Library',
    syntax: 'std::max_element(first, last)',
    description: 'Finds the largest element in the range.',
    arguments: [
      { name: 'first', type: 'ForwardIt', description: 'Iterator to the beginning' },
      { name: 'last', type: 'ForwardIt', description: 'Iterator to the end' },
    ],
    returns: { type: 'ForwardIt', description: 'Iterator to the largest element' },
    examples: [
      { code: 'vector<int> v = {1, 5, 3, 4, 2};\nauto it = max_element(v.begin(), v.end());', output: '*it = 5' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['min_element', 'minmax_element', 'max'],
  },
  {
    name: 'min_element',
    category: 'Algorithm Library',
    syntax: 'std::min_element(first, last)',
    description: 'Finds the smallest element in the range.',
    arguments: [
      { name: 'first', type: 'ForwardIt', description: 'Iterator to the beginning' },
      { name: 'last', type: 'ForwardIt', description: 'Iterator to the end' },
    ],
    returns: { type: 'ForwardIt', description: 'Iterator to the smallest element' },
    examples: [
      { code: 'vector<int> v = {3, 1, 4, 1, 5};\nauto it = min_element(v.begin(), v.end());', output: '*it = 1' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['max_element', 'minmax_element', 'min'],
  },
  {
    name: 'accumulate',
    category: 'Algorithm Library',
    syntax: 'std::accumulate(first, last, init)',
    description: 'Computes the sum of init and all elements in the range.',
    arguments: [
      { name: 'first', type: 'InputIt', description: 'Iterator to the beginning' },
      { name: 'last', type: 'InputIt', description: 'Iterator to the end' },
      { name: 'init', type: 'T', description: 'Initial value' },
    ],
    returns: { type: 'T', description: 'The accumulated value' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3, 4};\naccumulate(v.begin(), v.end(), 0);', output: '10' },
      { code: 'accumulate(v.begin(), v.end(), 1, multiplies<int>());', output: '24' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['reduce', 'inner_product', 'partial_sum'],
    notes: ['Include <numeric> header'],
  },
  {
    name: 'transform',
    category: 'Algorithm Library',
    syntax: 'std::transform(first, last, d_first, op)',
    description: 'Applies a function to each element and stores the result.',
    arguments: [
      { name: 'first', type: 'InputIt', description: 'Iterator to input beginning' },
      { name: 'last', type: 'InputIt', description: 'Iterator to input end' },
      { name: 'd_first', type: 'OutputIt', description: 'Iterator to output beginning' },
      { name: 'op', type: 'UnaryOperation', description: 'Unary function to apply' },
    ],
    returns: { type: 'OutputIt', description: 'Iterator to the end of the output range' },
    examples: [
      { code: 'vector<int> v = {1, 2, 3};\nvector<int> result(3);\ntransform(v.begin(), v.end(), result.begin(), [](int n) { return n * 2; });', output: 'result = {2, 4, 6}' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['for_each', 'copy', 'copy_if'],
  },

  // ============================================================
  // Map Methods
  // ============================================================
  {
    name: 'insert',
    category: 'Map Methods',
    syntax: 'map.insert({key, value})',
    description: 'Inserts element(s) if key does not exist.',
    arguments: [
      { name: 'value', type: 'pair<Key, T>', description: 'Key-value pair to insert' },
    ],
    returns: { type: 'pair<iterator, bool>', description: 'Iterator and success status' },
    examples: [
      { code: 'map<string, int> m;\nm.insert({"apple", 1});', output: '{iterator, true}' },
      { code: 'm.insert({"apple", 2});', output: '{iterator, false} // key exists' },
    ],
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['emplace', 'operator[]', 'insert_or_assign'],
  },
  {
    name: 'find',
    category: 'Map Methods',
    syntax: 'map.find(key)',
    description: 'Finds an element with the specified key.',
    arguments: [
      { name: 'key', type: 'Key', description: 'Key to search for' },
    ],
    returns: { type: 'iterator', description: 'Iterator to element, or end() if not found' },
    examples: [
      { code: 'map<string, int> m = {{"a", 1}, {"b", 2}};\nauto it = m.find("a");', output: 'it->second = 1' },
      { code: 'm.find("c");', output: 'm.end()' },
    ],
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['count', 'contains', 'operator[]'],
    notes: ['C++20: Prefer map.contains(key) for existence check'],
  },
  {
    name: 'count',
    category: 'Map Methods',
    syntax: 'map.count(key)',
    description: 'Returns the number of elements with the specified key (0 or 1 for map, 0+ for multimap).',
    arguments: [
      { name: 'key', type: 'Key', description: 'Key to count' },
    ],
    returns: { type: 'size_type', description: 'Number of elements with the key' },
    examples: [
      { code: 'map<string, int> m = {{"a", 1}};\nm.count("a");', output: '1' },
      { code: 'm.count("b");', output: '0' },
    ],
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['find', 'contains'],
    notes: ['C++20: Prefer map.contains(key) which returns bool directly'],
  },
  {
    name: 'erase',
    category: 'Map Methods',
    syntax: 'map.erase(key) | map.erase(position)',
    description: 'Removes elements from the map.',
    arguments: [
      { name: 'key', type: 'Key', description: 'Key to remove' },
      { name: 'position', type: 'iterator', description: 'Position to remove', optional: true },
    ],
    returns: { type: 'size_type | iterator', description: 'Number removed (by key) or iterator (by position)' },
    examples: [
      { code: 'map<string, int> m = {{"a", 1}, {"b", 2}};\nm.erase("a");', output: '1, m = {{"b", 2}}' },
    ],
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['clear', 'insert', 'find'],
  },

  // ============================================================
  // Set Methods
  // ============================================================
  {
    name: 'insert',
    category: 'Set Methods',
    syntax: 'set.insert(value)',
    description: 'Inserts an element if it does not already exist.',
    arguments: [
      { name: 'value', type: 'T', description: 'Value to insert' },
    ],
    returns: { type: 'pair<iterator, bool>', description: 'Iterator and success status' },
    examples: [
      { code: 'set<int> s;\ns.insert(1);\ns.insert(2);\ns.insert(1);', output: 's = {1, 2}' },
    ],
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['emplace', 'erase', 'find'],
  },
  {
    name: 'find',
    category: 'Set Methods',
    syntax: 'set.find(value)',
    description: 'Finds an element with the specified value.',
    arguments: [
      { name: 'value', type: 'T', description: 'Value to search for' },
    ],
    returns: { type: 'iterator', description: 'Iterator to element, or end() if not found' },
    examples: [
      { code: 'set<int> s = {1, 2, 3};\ns.find(2);', output: 'Iterator to 2' },
      { code: 's.find(5);', output: 's.end()' },
    ],
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['count', 'contains', 'lower_bound'],
    notes: ['C++20: Prefer set.contains(value) for existence check'],
  },
  {
    name: 'count',
    category: 'Set Methods',
    syntax: 'set.count(value)',
    description: 'Returns 1 if the value exists, 0 otherwise.',
    arguments: [
      { name: 'value', type: 'T', description: 'Value to count' },
    ],
    returns: { type: 'size_type', description: '1 if found, 0 otherwise' },
    examples: [
      { code: 'set<int> s = {1, 2, 3};\ns.count(2);', output: '1' },
      { code: 's.count(5);', output: '0' },
    ],
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['find', 'contains'],
    notes: ['C++20: Prefer set.contains(value) which returns bool directly'],
  },

  // ============================================================
  // Stack/Queue
  // ============================================================
  {
    name: 'push',
    category: 'Stack/Queue',
    syntax: 'container.push(value)',
    description: 'Adds an element to the stack (top) or queue (back).',
    arguments: [
      { name: 'value', type: 'T', description: 'Value to add' },
    ],
    returns: { type: 'void', description: 'No return value' },
    examples: [
      { code: 'stack<int> s;\ns.push(1);\ns.push(2);', output: 'Stack: bottom [1, 2] top' },
      { code: 'queue<int> q;\nq.push(1);\nq.push(2);', output: 'Queue: front [1, 2] back' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['pop', 'top', 'front', 'back'],
  },
  {
    name: 'pop',
    category: 'Stack/Queue',
    syntax: 'container.pop()',
    description: 'Removes the top element (stack) or front element (queue). Does not return the element.',
    arguments: [],
    returns: { type: 'void', description: 'No return value' },
    examples: [
      { code: 'stack<int> s;\ns.push(1); s.push(2); s.push(3);\ns.pop();', output: 'Removes 3 (top), s now has {1, 2}' },
      { code: 'queue<int> q;\nq.push(1); q.push(2); q.push(3);\nq.pop();', output: 'Removes 1 (front), q now has {2, 3}' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['push', 'top', 'front'],
    notes: ['Access top()/front() before pop() to get the value'],
  },
  {
    name: 'top',
    category: 'Stack/Queue',
    syntax: 'stack.top()',
    description: 'Returns a reference to the top element of the stack.',
    arguments: [],
    returns: { type: 'reference', description: 'Reference to the top element' },
    examples: [
      { code: 'stack<int> s;\ns.push(1);\ns.push(2);\ns.top();', output: '2' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['push', 'pop', 'empty'],
  },
  {
    name: 'front',
    category: 'Stack/Queue',
    syntax: 'queue.front()',
    description: 'Returns a reference to the front element of the queue.',
    arguments: [],
    returns: { type: 'reference', description: 'Reference to the front element' },
    examples: [
      { code: 'queue<int> q;\nq.push(1);\nq.push(2);\nq.front();', output: '1' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['back', 'push', 'pop'],
  },
];
