import type { Method } from '../types';

export const csharpMethods: Method[] = [
  // List Methods
  { name: 'Add', category: 'List Methods', syntax: 'list.Add(item)', description: 'Adds an element to the end of the List.', arguments: [{ name: 'item', type: 'T', description: 'Element to add' }], returns: { type: 'void', description: 'No return value' }, examples: [{ code: 'var list = new List<int> { 1, 2 }; list.Add(3);', output: '[1, 2, 3]' }], timeComplexity: 'O(1) amortized', spaceComplexity: 'O(1)', relatedMethods: ['AddRange', 'Insert'] },
  { name: 'Remove', category: 'List Methods', syntax: 'list.Remove(item)', description: 'Removes the first occurrence of an element.', arguments: [{ name: 'item', type: 'T', description: 'Element to remove' }], returns: { type: 'bool', description: 'true if removed' }, examples: [{ code: 'var list = new List<int> { 1, 2, 3 }; list.Remove(2);', output: '[1, 3]' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['RemoveAt', 'RemoveAll'] },
  { name: 'Find', category: 'List Methods', syntax: 'list.Find(predicate)', description: 'Searches for an element matching the predicate.', arguments: [{ name: 'predicate', type: 'Predicate<T>', description: 'Match function' }], returns: { type: 'T', description: 'First match or default' }, examples: [{ code: 'new List<int> { 1, 2, 3 }.Find(x => x > 2);', output: '3' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['FindAll', 'FindIndex'] },
  { name: 'Sort', category: 'List Methods', syntax: 'list.Sort()', description: 'Sorts the elements in the entire List.', arguments: [], returns: { type: 'void', description: 'Modifies list in place' }, examples: [{ code: 'var list = new List<int> { 3, 1, 2 }; list.Sort();', output: '[1, 2, 3]' }], timeComplexity: 'O(n log n)', spaceComplexity: 'O(log n)', relatedMethods: ['OrderBy', 'Reverse'] },
  { name: 'Contains', category: 'List Methods', syntax: 'list.Contains(item)', description: 'Determines whether an element is in the List.', arguments: [{ name: 'item', type: 'T', description: 'Element to find' }], returns: { type: 'bool', description: 'true if found' }, examples: [{ code: 'new List<int> { 1, 2, 3 }.Contains(2);', output: 'true' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['IndexOf', 'Find'] },

  // LINQ Methods
  { name: 'Where', category: 'LINQ Methods', syntax: 'source.Where(predicate)', description: 'Filters a sequence based on a predicate.', arguments: [{ name: 'predicate', type: 'Func<T, bool>', description: 'Filter function' }], returns: { type: 'IEnumerable<T>', description: 'Filtered sequence' }, examples: [{ code: 'new[] { 1, 2, 3, 4 }.Where(x => x > 2);', output: '[3, 4]' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['Select', 'First'], sinceVersion: '.NET 3.5' },
  { name: 'Select', category: 'LINQ Methods', syntax: 'source.Select(selector)', description: 'Projects each element into a new form.', arguments: [{ name: 'selector', type: 'Func<T, TResult>', description: 'Transform function' }], returns: { type: 'IEnumerable<TResult>', description: 'Transformed sequence' }, examples: [{ code: 'new[] { 1, 2, 3 }.Select(x => x * 2);', output: '[2, 4, 6]' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['SelectMany', 'Where'], sinceVersion: '.NET 3.5' },
  { name: 'First', category: 'LINQ Methods', syntax: 'source.First()', description: 'Returns the first element of a sequence.', arguments: [], returns: { type: 'T', description: 'First element' }, examples: [{ code: 'new[] { 1, 2, 3 }.First();', output: '1' }], timeComplexity: 'O(1)', spaceComplexity: 'O(1)', relatedMethods: ['FirstOrDefault', 'Last'], sinceVersion: '.NET 3.5', notes: ['Throws if empty'] },
  { name: 'FirstOrDefault', category: 'LINQ Methods', syntax: 'source.FirstOrDefault()', description: 'Returns the first element, or default if empty.', arguments: [], returns: { type: 'T', description: 'First element or default' }, examples: [{ code: 'new int[] { }.FirstOrDefault();', output: '0' }], timeComplexity: 'O(1)', spaceComplexity: 'O(1)', relatedMethods: ['First', 'SingleOrDefault'], sinceVersion: '.NET 3.5' },
  { name: 'Any', category: 'LINQ Methods', syntax: 'source.Any(predicate)', description: 'Determines if any elements satisfy a condition.', arguments: [{ name: 'predicate', type: 'Func<T, bool>', description: 'Test function', optional: true }], returns: { type: 'bool', description: 'true if any match' }, examples: [{ code: 'new[] { 1, 2, 3 }.Any(x => x > 2);', output: 'true' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['All', 'Count'], sinceVersion: '.NET 3.5' },
  { name: 'All', category: 'LINQ Methods', syntax: 'source.All(predicate)', description: 'Determines if all elements satisfy a condition.', arguments: [{ name: 'predicate', type: 'Func<T, bool>', description: 'Test function' }], returns: { type: 'bool', description: 'true if all match' }, examples: [{ code: 'new[] { 2, 4, 6 }.All(x => x % 2 == 0);', output: 'true' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['Any'], sinceVersion: '.NET 3.5' },
  { name: 'Count', category: 'LINQ Methods', syntax: 'source.Count()', description: 'Returns the number of elements.', arguments: [], returns: { type: 'int', description: 'Element count' }, examples: [{ code: 'new[] { 1, 2, 3 }.Count();', output: '3' }], timeComplexity: 'O(n) or O(1)', spaceComplexity: 'O(1)', relatedMethods: ['Any', 'Sum'], sinceVersion: '.NET 3.5' },
  { name: 'Sum', category: 'LINQ Methods', syntax: 'source.Sum()', description: 'Computes the sum of a sequence.', arguments: [], returns: { type: 'number', description: 'Sum of elements' }, examples: [{ code: 'new[] { 1, 2, 3 }.Sum();', output: '6' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['Average', 'Count'], sinceVersion: '.NET 3.5' },
  { name: 'OrderBy', category: 'LINQ Methods', syntax: 'source.OrderBy(keySelector)', description: 'Sorts elements in ascending order.', arguments: [{ name: 'keySelector', type: 'Func<T, TKey>', description: 'Key extractor' }], returns: { type: 'IOrderedEnumerable<T>', description: 'Sorted sequence' }, examples: [{ code: 'new[] { 3, 1, 2 }.OrderBy(x => x);', output: '[1, 2, 3]' }], timeComplexity: 'O(n log n)', spaceComplexity: 'O(n)', relatedMethods: ['OrderByDescending', 'ThenBy'], sinceVersion: '.NET 3.5' },
  { name: 'OrderByDescending', category: 'LINQ Methods', syntax: 'source.OrderByDescending(keySelector)', description: 'Sorts elements in descending order.', arguments: [{ name: 'keySelector', type: 'Func<T, TKey>', description: 'Key extractor' }], returns: { type: 'IOrderedEnumerable<T>', description: 'Sorted sequence' }, examples: [{ code: 'new[] { 1, 3, 2 }.OrderByDescending(x => x);', output: '[3, 2, 1]' }], timeComplexity: 'O(n log n)', spaceComplexity: 'O(n)', relatedMethods: ['OrderBy'], sinceVersion: '.NET 3.5' },
  { name: 'GroupBy', category: 'LINQ Methods', syntax: 'source.GroupBy(keySelector)', description: 'Groups elements by a key.', arguments: [{ name: 'keySelector', type: 'Func<T, TKey>', description: 'Key extractor' }], returns: { type: 'IEnumerable<IGrouping<TKey, T>>', description: 'Grouped sequence' }, examples: [{ code: 'new[] { 1, 2, 3, 4 }.GroupBy(x => x % 2);', output: '[{0: [2,4]}, {1: [1,3]}]' }], timeComplexity: 'O(n)', spaceComplexity: 'O(n)', relatedMethods: ['ToDictionary', 'ToLookup'], sinceVersion: '.NET 3.5' },
  { name: 'Distinct', category: 'LINQ Methods', syntax: 'source.Distinct()', description: 'Returns distinct elements.', arguments: [], returns: { type: 'IEnumerable<T>', description: 'Unique elements' }, examples: [{ code: 'new[] { 1, 2, 2, 3 }.Distinct();', output: '[1, 2, 3]' }], timeComplexity: 'O(n)', spaceComplexity: 'O(n)', relatedMethods: ['GroupBy'], sinceVersion: '.NET 3.5' },
  { name: 'Take', category: 'LINQ Methods', syntax: 'source.Take(count)', description: 'Returns a specified number of elements from the start.', arguments: [{ name: 'count', type: 'int', description: 'Number to take' }], returns: { type: 'IEnumerable<T>', description: 'First count elements' }, examples: [{ code: 'new[] { 1, 2, 3, 4, 5 }.Take(3);', output: '[1, 2, 3]' }], timeComplexity: 'O(count)', spaceComplexity: 'O(1)', relatedMethods: ['Skip', 'First'], sinceVersion: '.NET 3.5' },
  { name: 'Skip', category: 'LINQ Methods', syntax: 'source.Skip(count)', description: 'Bypasses a specified number of elements.', arguments: [{ name: 'count', type: 'int', description: 'Number to skip' }], returns: { type: 'IEnumerable<T>', description: 'Remaining elements' }, examples: [{ code: 'new[] { 1, 2, 3, 4, 5 }.Skip(2);', output: '[3, 4, 5]' }], timeComplexity: 'O(count)', spaceComplexity: 'O(1)', relatedMethods: ['Take', 'SkipWhile'], sinceVersion: '.NET 3.5' },
  { name: 'ToList', category: 'LINQ Methods', syntax: 'source.ToList()', description: 'Creates a List from a sequence.', arguments: [], returns: { type: 'List<T>', description: 'New List' }, examples: [{ code: 'new[] { 1, 2 }.Where(x => x > 0).ToList();', output: 'List<int> { 1, 2 }' }], timeComplexity: 'O(n)', spaceComplexity: 'O(n)', relatedMethods: ['ToArray', 'ToDictionary'], sinceVersion: '.NET 3.5' },
  { name: 'ToDictionary', category: 'LINQ Methods', syntax: 'source.ToDictionary(keySelector)', description: 'Creates a Dictionary from a sequence.', arguments: [{ name: 'keySelector', type: 'Func<T, TKey>', description: 'Key extractor' }], returns: { type: 'Dictionary<TKey, T>', description: 'New Dictionary' }, examples: [{ code: 'new[] { "a", "bb" }.ToDictionary(x => x.Length);', output: '{ 1: "a", 2: "bb" }' }], timeComplexity: 'O(n)', spaceComplexity: 'O(n)', relatedMethods: ['ToList', 'GroupBy'], sinceVersion: '.NET 3.5' },
  { name: 'Aggregate', category: 'LINQ Methods', syntax: 'source.Aggregate(func)', description: 'Applies an accumulator function over a sequence.', arguments: [{ name: 'func', type: 'Func<T, T, T>', description: 'Accumulator function' }], returns: { type: 'T', description: 'Accumulated value' }, examples: [{ code: 'new[] { 1, 2, 3, 4 }.Aggregate((a, b) => a + b);', output: '10' }], timeComplexity: 'O(n)', spaceComplexity: 'O(1)', relatedMethods: ['Sum', 'Max'], sinceVersion: '.NET 3.5' },

  // String Methods
  { name: 'Split', category: 'String Methods', syntax: 'string.Split(separator)', description: 'Splits a string into substrings.', arguments: [{ name: 'separator', type: 'char', description: 'Delimiter' }], returns: { type: 'string[]', description: 'Array of substrings' }, examples: [{ code: '"a,b,c".Split(\',\');', output: '["a", "b", "c"]' }], timeComplexity: 'O(n)', spaceComplexity: 'O(n)', relatedMethods: ['Join', 'Substring'] },
  { name: 'Join', category: 'String Methods', syntax: 'string.Join(separator, values)', description: 'Concatenates elements using a separator.', arguments: [{ name: 'separator', type: 'string', description: 'Separator' }, { name: 'values', type: 'IEnumerable<string>', description: 'Values to join' }], returns: { type: 'string', description: 'Joined string' }, examples: [{ code: 'string.Join(", ", new[] { "a", "b", "c" });', output: '"a, b, c"' }], timeComplexity: 'O(n)', spaceComplexity: 'O(n)', relatedMethods: ['Split', 'Concat'] },
  { name: 'Trim', category: 'String Methods', syntax: 'string.Trim()', description: 'Removes leading and trailing whitespace.', arguments: [], returns: { type: 'string', description: 'Trimmed string' }, examples: [{ code: '"  hello  ".Trim();', output: '"hello"' }], timeComplexity: 'O(n)', spaceComplexity: 'O(n)', relatedMethods: ['TrimStart', 'TrimEnd'] },
  { name: 'Replace', category: 'String Methods', syntax: 'string.Replace(old, new)', description: 'Replaces all occurrences of a substring.', arguments: [{ name: 'old', type: 'string', description: 'Value to replace' }, { name: 'new', type: 'string', description: 'Replacement' }], returns: { type: 'string', description: 'Modified string' }, examples: [{ code: '"hello world".Replace("world", "there");', output: '"hello there"' }], timeComplexity: 'O(n)', spaceComplexity: 'O(n)', relatedMethods: ['Remove', 'Insert'] },
  { name: 'ToUpper', category: 'String Methods', syntax: 'string.ToUpper()', description: 'Converts to uppercase.', arguments: [], returns: { type: 'string', description: 'Uppercase string' }, examples: [{ code: '"hello".ToUpper();', output: '"HELLO"' }], timeComplexity: 'O(n)', spaceComplexity: 'O(n)', relatedMethods: ['ToLower'] },
  { name: 'ToLower', category: 'String Methods', syntax: 'string.ToLower()', description: 'Converts to lowercase.', arguments: [], returns: { type: 'string', description: 'Lowercase string' }, examples: [{ code: '"HELLO".ToLower();', output: '"hello"' }], timeComplexity: 'O(n)', spaceComplexity: 'O(n)', relatedMethods: ['ToUpper'] },
  { name: 'StartsWith', category: 'String Methods', syntax: 'string.StartsWith(value)', description: 'Determines if string starts with value.', arguments: [{ name: 'value', type: 'string', description: 'Prefix to check' }], returns: { type: 'bool', description: 'true if starts with value' }, examples: [{ code: '"hello world".StartsWith("hello");', output: 'true' }], timeComplexity: 'O(m)', spaceComplexity: 'O(1)', relatedMethods: ['EndsWith', 'Contains'] },
  { name: 'EndsWith', category: 'String Methods', syntax: 'string.EndsWith(value)', description: 'Determines if string ends with value.', arguments: [{ name: 'value', type: 'string', description: 'Suffix to check' }], returns: { type: 'bool', description: 'true if ends with value' }, examples: [{ code: '"hello world".EndsWith("world");', output: 'true' }], timeComplexity: 'O(m)', spaceComplexity: 'O(1)', relatedMethods: ['StartsWith', 'Contains'] },

  // Dictionary Methods
  { name: 'Add', category: 'Dictionary Methods', syntax: 'dict.Add(key, value)', description: 'Adds a key-value pair.', arguments: [{ name: 'key', type: 'TKey', description: 'Key' }, { name: 'value', type: 'TValue', description: 'Value' }], returns: { type: 'void', description: 'No return value' }, examples: [{ code: 'var dict = new Dictionary<string, int>(); dict.Add("a", 1);', output: '{ "a": 1 }' }], timeComplexity: 'O(1)', spaceComplexity: 'O(1)', relatedMethods: ['TryAdd', 'Remove'], notes: ['Throws if key exists'] },
  { name: 'TryGetValue', category: 'Dictionary Methods', syntax: 'dict.TryGetValue(key, out value)', description: 'Gets value if key exists.', arguments: [{ name: 'key', type: 'TKey', description: 'Key to find' }, { name: 'value', type: 'TValue', description: 'Output value' }], returns: { type: 'bool', description: 'true if found' }, examples: [{ code: 'dict.TryGetValue("a", out int val);', output: 'true if key exists' }], timeComplexity: 'O(1)', spaceComplexity: 'O(1)', relatedMethods: ['ContainsKey', 'GetValueOrDefault'] },
  { name: 'ContainsKey', category: 'Dictionary Methods', syntax: 'dict.ContainsKey(key)', description: 'Determines if key exists.', arguments: [{ name: 'key', type: 'TKey', description: 'Key to check' }], returns: { type: 'bool', description: 'true if key exists' }, examples: [{ code: 'new Dictionary<string, int> { {"a", 1} }.ContainsKey("a");', output: 'true' }], timeComplexity: 'O(1)', spaceComplexity: 'O(1)', relatedMethods: ['TryGetValue', 'ContainsValue'] },
];

export default csharpMethods;
