import type { Method } from '../types';

export const javascriptMethods: Method[] = [
  // ============================================================
  // Array Methods
  // ============================================================
  {
    name: 'filter',
    category: 'Array Methods',
    syntax: 'array.filter(callback(element, index, array), thisArg)',
    description: 'Creates a new array with all elements that pass the test implemented by the provided function.',
    arguments: [
      { name: 'callback', type: 'Function', description: 'Function to test each element. Return true to keep, false to discard.' },
      { name: 'element', type: 'any', description: 'The current element being processed' },
      { name: 'index', type: 'number', description: 'The index of the current element', optional: true },
      { name: 'array', type: 'Array', description: 'The array filter was called on', optional: true },
      { name: 'thisArg', type: 'any', description: 'Value to use as this in callback', optional: true },
    ],
    returns: { type: 'Array', description: 'A new array with elements that pass the test' },
    examples: [
      { code: '[1, 2, 3, 4, 5].filter(n => n > 2)', output: '[3, 4, 5]' },
      { code: '["apple", "banana", "cherry"].filter(f => f.length > 5)', output: '["banana", "cherry"]' },
      { code: '[1, 2, 3, 4].filter((n, i) => i % 2 === 0)', output: '[1, 3]', explanation: 'Filter by index position' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['find', 'findIndex', 'every', 'some'],
    sinceVersion: 'ES5',
  },
  {
    name: 'map',
    category: 'Array Methods',
    syntax: 'array.map(callback(element, index, array), thisArg)',
    description: 'Creates a new array populated with the results of calling a provided function on every element in the calling array.',
    arguments: [
      { name: 'callback', type: 'Function', description: 'Function that produces an element of the new array' },
      { name: 'element', type: 'any', description: 'The current element being processed' },
      { name: 'index', type: 'number', description: 'The index of the current element', optional: true },
      { name: 'array', type: 'Array', description: 'The array map was called on', optional: true },
      { name: 'thisArg', type: 'any', description: 'Value to use as this in callback', optional: true },
    ],
    returns: { type: 'Array', description: 'A new array with each element being the result of the callback function' },
    examples: [
      { code: '[1, 2, 3].map(x => x * 2)', output: '[2, 4, 6]' },
      { code: '["a", "b", "c"].map(s => s.toUpperCase())', output: '["A", "B", "C"]' },
      { code: '[1, 2, 3].map((n, i) => n + i)', output: '[1, 3, 5]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['flatMap', 'forEach', 'filter'],
    sinceVersion: 'ES5',
  },
  {
    name: 'reduce',
    category: 'Array Methods',
    syntax: 'array.reduce(callback(accumulator, currentValue, index, array), initialValue)',
    description: 'Executes a user-supplied reducer callback function on each element of the array, passing in the return value from the calculation on the preceding element.',
    arguments: [
      { name: 'callback', type: 'Function', description: 'Reducer function to execute on each element' },
      { name: 'accumulator', type: 'any', description: 'The accumulated value previously returned' },
      { name: 'currentValue', type: 'any', description: 'The current element being processed' },
      { name: 'index', type: 'number', description: 'The index of the current element', optional: true },
      { name: 'array', type: 'Array', description: 'The array reduce was called on', optional: true },
      { name: 'initialValue', type: 'any', description: 'Value to use as the first argument to the first call of callback', optional: true },
    ],
    returns: { type: 'any', description: 'The single value that results from the reduction' },
    examples: [
      { code: '[1, 2, 3, 4].reduce((acc, n) => acc + n, 0)', output: '10' },
      { code: '[[1, 2], [3, 4]].reduce((acc, arr) => acc.concat(arr), [])', output: '[1, 2, 3, 4]' },
      { code: '[1, 2, 3].reduce((acc, n) => ({ ...acc, [n]: n * 2 }), {})', output: '{ 1: 2, 2: 4, 3: 6 }' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['reduceRight', 'map', 'filter'],
    sinceVersion: 'ES5',
    notes: ['Always provide an initialValue to avoid errors with empty arrays'],
  },
  {
    name: 'find',
    category: 'Array Methods',
    syntax: 'array.find(callback(element, index, array), thisArg)',
    description: 'Returns the first element in the provided array that satisfies the provided testing function. If no values satisfy the testing function, undefined is returned.',
    arguments: [
      { name: 'callback', type: 'Function', description: 'Function to execute on each value in the array' },
      { name: 'element', type: 'any', description: 'The current element being processed' },
      { name: 'index', type: 'number', description: 'The index of the current element', optional: true },
      { name: 'array', type: 'Array', description: 'The array find was called on', optional: true },
      { name: 'thisArg', type: 'any', description: 'Value to use as this in callback', optional: true },
    ],
    returns: { type: 'any | undefined', description: 'The first element that satisfies the testing function, or undefined' },
    examples: [
      { code: '[1, 2, 3, 4, 5].find(n => n > 3)', output: '4' },
      { code: '[{id: 1}, {id: 2}].find(obj => obj.id === 2)', output: '{id: 2}' },
      { code: '[1, 2, 3].find(n => n > 10)', output: 'undefined' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['findIndex', 'findLast', 'filter', 'some'],
    sinceVersion: 'ES6',
  },
  {
    name: 'findIndex',
    category: 'Array Methods',
    syntax: 'array.findIndex(callback(element, index, array), thisArg)',
    description: 'Returns the index of the first element in the array that satisfies the provided testing function. Otherwise, it returns -1.',
    arguments: [
      { name: 'callback', type: 'Function', description: 'Function to execute on each value in the array' },
      { name: 'element', type: 'any', description: 'The current element being processed' },
      { name: 'index', type: 'number', description: 'The index of the current element', optional: true },
      { name: 'array', type: 'Array', description: 'The array findIndex was called on', optional: true },
      { name: 'thisArg', type: 'any', description: 'Value to use as this in callback', optional: true },
    ],
    returns: { type: 'number', description: 'The index of the first element that passes the test, or -1' },
    examples: [
      { code: '[1, 2, 3, 4, 5].findIndex(n => n > 3)', output: '3' },
      { code: '["a", "b", "c"].findIndex(s => s === "b")', output: '1' },
      { code: '[1, 2, 3].findIndex(n => n > 10)', output: '-1' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['find', 'indexOf', 'lastIndexOf'],
    sinceVersion: 'ES6',
  },
  {
    name: 'forEach',
    category: 'Array Methods',
    syntax: 'array.forEach(callback(element, index, array), thisArg)',
    description: 'Executes a provided function once for each array element. Returns undefined and cannot be chained.',
    arguments: [
      { name: 'callback', type: 'Function', description: 'Function to execute on each element' },
      { name: 'element', type: 'any', description: 'The current element being processed' },
      { name: 'index', type: 'number', description: 'The index of the current element', optional: true },
      { name: 'array', type: 'Array', description: 'The array forEach was called on', optional: true },
      { name: 'thisArg', type: 'any', description: 'Value to use as this in callback', optional: true },
    ],
    returns: { type: 'undefined', description: 'Always returns undefined' },
    examples: [
      { code: '[1, 2, 3].forEach(n => console.log(n))', output: '// logs: 1, 2, 3' },
      { code: 'let sum = 0; [1, 2, 3].forEach(n => sum += n); sum', output: '6' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['map', 'for...of'],
    sinceVersion: 'ES5',
    notes: ['Cannot break out of forEach loop - use for...of or some() instead'],
  },
  {
    name: 'some',
    category: 'Array Methods',
    syntax: 'array.some(callback(element, index, array), thisArg)',
    description: 'Tests whether at least one element in the array passes the test implemented by the provided function. Returns true if it finds an element for which the callback returns truthy.',
    arguments: [
      { name: 'callback', type: 'Function', description: 'Function to test each element' },
      { name: 'element', type: 'any', description: 'The current element being processed' },
      { name: 'index', type: 'number', description: 'The index of the current element', optional: true },
      { name: 'array', type: 'Array', description: 'The array some was called on', optional: true },
      { name: 'thisArg', type: 'any', description: 'Value to use as this in callback', optional: true },
    ],
    returns: { type: 'boolean', description: 'true if at least one element passes the test, false otherwise' },
    examples: [
      { code: '[1, 2, 3, 4, 5].some(n => n > 4)', output: 'true' },
      { code: '[1, 2, 3].some(n => n > 10)', output: 'false' },
      { code: '[].some(n => n > 0)', output: 'false', explanation: 'Empty array always returns false' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['every', 'find', 'includes'],
    sinceVersion: 'ES5',
  },
  {
    name: 'every',
    category: 'Array Methods',
    syntax: 'array.every(callback(element, index, array), thisArg)',
    description: 'Tests whether all elements in the array pass the test implemented by the provided function. Returns true only if every element passes.',
    arguments: [
      { name: 'callback', type: 'Function', description: 'Function to test each element' },
      { name: 'element', type: 'any', description: 'The current element being processed' },
      { name: 'index', type: 'number', description: 'The index of the current element', optional: true },
      { name: 'array', type: 'Array', description: 'The array every was called on', optional: true },
      { name: 'thisArg', type: 'any', description: 'Value to use as this in callback', optional: true },
    ],
    returns: { type: 'boolean', description: 'true if all elements pass the test, false otherwise' },
    examples: [
      { code: '[2, 4, 6, 8].every(n => n % 2 === 0)', output: 'true' },
      { code: '[1, 2, 3].every(n => n > 0)', output: 'true' },
      { code: '[1, 2, 3].every(n => n > 2)', output: 'false' },
      { code: '[].every(n => n > 0)', output: 'true', explanation: 'Empty array always returns true (vacuous truth)' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['some', 'filter'],
    sinceVersion: 'ES5',
  },
  {
    name: 'includes',
    category: 'Array Methods',
    syntax: 'array.includes(searchElement, fromIndex)',
    description: 'Determines whether an array includes a certain value among its entries, returning true or false as appropriate.',
    arguments: [
      { name: 'searchElement', type: 'any', description: 'The value to search for' },
      { name: 'fromIndex', type: 'number', description: 'Position to start searching from', optional: true, defaultValue: '0' },
    ],
    returns: { type: 'boolean', description: 'true if the value is found, false otherwise' },
    examples: [
      { code: '[1, 2, 3].includes(2)', output: 'true' },
      { code: '["a", "b", "c"].includes("d")', output: 'false' },
      { code: '[1, 2, 3].includes(2, 2)', output: 'false', explanation: 'Starts searching from index 2' },
      { code: '[NaN].includes(NaN)', output: 'true', explanation: 'Unlike indexOf, handles NaN correctly' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['indexOf', 'find', 'some'],
    sinceVersion: 'ES7',
  },
  {
    name: 'slice',
    category: 'Array Methods',
    syntax: 'array.slice(start, end)',
    description: 'Returns a shallow copy of a portion of an array into a new array object selected from start to end (end not included).',
    arguments: [
      { name: 'start', type: 'number', description: 'Zero-based index at which to start extraction', optional: true, defaultValue: '0' },
      { name: 'end', type: 'number', description: 'Zero-based index before which to end extraction', optional: true, defaultValue: 'array.length' },
    ],
    returns: { type: 'Array', description: 'A new array containing the extracted elements' },
    examples: [
      { code: '[1, 2, 3, 4, 5].slice(1, 4)', output: '[2, 3, 4]' },
      { code: '[1, 2, 3, 4, 5].slice(2)', output: '[3, 4, 5]' },
      { code: '[1, 2, 3, 4, 5].slice(-2)', output: '[4, 5]', explanation: 'Negative index counts from end' },
      { code: '[1, 2, 3].slice()', output: '[1, 2, 3]', explanation: 'Creates a shallow copy' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['splice', 'concat', 'toSpliced'],
    sinceVersion: 'ES3',
    notes: ['Does not modify the original array'],
  },
  {
    name: 'splice',
    category: 'Array Methods',
    syntax: 'array.splice(start, deleteCount, item1, item2, ...)',
    description: 'Changes the contents of an array by removing or replacing existing elements and/or adding new elements in place.',
    arguments: [
      { name: 'start', type: 'number', description: 'Index at which to start changing the array' },
      { name: 'deleteCount', type: 'number', description: 'Number of elements to remove', optional: true },
      { name: 'items', type: 'any', description: 'Elements to add to the array', optional: true },
    ],
    returns: { type: 'Array', description: 'An array containing the deleted elements' },
    examples: [
      { code: 'let arr = [1, 2, 3, 4]; arr.splice(1, 2); arr', output: '[1, 4]' },
      { code: 'let arr = [1, 2, 3]; arr.splice(1, 0, "a", "b"); arr', output: '[1, "a", "b", 2, 3]' },
      { code: 'let arr = [1, 2, 3]; arr.splice(1, 1, "x"); arr', output: '[1, "x", 3]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['slice', 'toSpliced', 'push', 'pop'],
    sinceVersion: 'ES3',
    notes: ['Modifies the original array'],
  },
  {
    name: 'concat',
    category: 'Array Methods',
    syntax: 'array.concat(value1, value2, ...)',
    description: 'Merges two or more arrays. This method does not change the existing arrays, but instead returns a new array.',
    arguments: [
      { name: 'values', type: 'any | Array', description: 'Arrays and/or values to concatenate into a new array' },
    ],
    returns: { type: 'Array', description: 'A new Array instance containing all elements' },
    examples: [
      { code: '[1, 2].concat([3, 4])', output: '[1, 2, 3, 4]' },
      { code: '[1, 2].concat([3, 4], [5, 6])', output: '[1, 2, 3, 4, 5, 6]' },
      { code: '[1, 2].concat(3, 4)', output: '[1, 2, 3, 4]' },
    ],
    timeComplexity: 'O(n + m)',
    spaceComplexity: 'O(n + m)',
    relatedMethods: ['push', 'spread operator', 'flat'],
    sinceVersion: 'ES3',
  },
  {
    name: 'sort',
    category: 'Array Methods',
    syntax: 'array.sort(compareFunction)',
    description: 'Sorts the elements of an array in place and returns the reference to the same array, now sorted.',
    arguments: [
      { name: 'compareFunction', type: 'Function', description: 'Function that defines the sort order', optional: true },
    ],
    returns: { type: 'Array', description: 'The sorted array (same reference)' },
    examples: [
      { code: '[3, 1, 4, 1, 5].sort((a, b) => a - b)', output: '[1, 1, 3, 4, 5]' },
      { code: '["banana", "apple", "cherry"].sort()', output: '["apple", "banana", "cherry"]' },
      { code: '[10, 2, 1].sort()', output: '[1, 10, 2]', explanation: 'Default sort is lexicographic!' },
      { code: '[{n: 3}, {n: 1}].sort((a, b) => a.n - b.n)', output: '[{n: 1}, {n: 3}]' },
    ],
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(log n)',
    relatedMethods: ['toSorted', 'reverse', 'toReversed'],
    sinceVersion: 'ES1',
    notes: ['Modifies the original array', 'Use toSorted() for immutable sorting (ES2023)'],
  },
  {
    name: 'reverse',
    category: 'Array Methods',
    syntax: 'array.reverse()',
    description: 'Reverses an array in place and returns the reference to the same array.',
    arguments: [],
    returns: { type: 'Array', description: 'The reversed array (same reference)' },
    examples: [
      { code: '[1, 2, 3].reverse()', output: '[3, 2, 1]' },
      { code: '["a", "b", "c"].reverse()', output: '["c", "b", "a"]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['toReversed', 'sort'],
    sinceVersion: 'ES1',
    notes: ['Modifies the original array', 'Use toReversed() for immutable reversal (ES2023)'],
  },
  {
    name: 'flat',
    category: 'Array Methods',
    syntax: 'array.flat(depth)',
    description: 'Creates a new array with all sub-array elements concatenated into it recursively up to the specified depth.',
    arguments: [
      { name: 'depth', type: 'number', description: 'The depth level specifying how deep a nested array structure should be flattened', optional: true, defaultValue: '1' },
    ],
    returns: { type: 'Array', description: 'A new array with the sub-array elements concatenated into it' },
    examples: [
      { code: '[1, [2, 3], [4, [5]]].flat()', output: '[1, 2, 3, 4, [5]]' },
      { code: '[1, [2, [3, [4]]]].flat(2)', output: '[1, 2, 3, [4]]' },
      { code: '[1, [2, [3, [4]]]].flat(Infinity)', output: '[1, 2, 3, 4]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['flatMap', 'concat'],
    sinceVersion: 'ES2019',
  },
  {
    name: 'flatMap',
    category: 'Array Methods',
    syntax: 'array.flatMap(callback(element, index, array), thisArg)',
    description: 'Returns a new array formed by applying a given callback function to each element of the array, and then flattening the result by one level.',
    arguments: [
      { name: 'callback', type: 'Function', description: 'Function that produces an element of the new array' },
      { name: 'element', type: 'any', description: 'The current element being processed' },
      { name: 'index', type: 'number', description: 'The index of the current element', optional: true },
      { name: 'array', type: 'Array', description: 'The array flatMap was called on', optional: true },
      { name: 'thisArg', type: 'any', description: 'Value to use as this in callback', optional: true },
    ],
    returns: { type: 'Array', description: 'A new array with each element being the result of the callback function and flattened to a depth of 1' },
    examples: [
      { code: '[1, 2, 3].flatMap(x => [x, x * 2])', output: '[1, 2, 2, 4, 3, 6]' },
      { code: '["hello world", "foo bar"].flatMap(s => s.split(" "))', output: '["hello", "world", "foo", "bar"]' },
      { code: '[1, 2, 3].flatMap(x => x % 2 === 0 ? [x] : [])', output: '[2]', explanation: 'Filter and map in one operation' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['flat', 'map', 'filter'],
    sinceVersion: 'ES2019',
  },
  {
    name: 'join',
    category: 'Array Methods',
    syntax: 'array.join(separator)',
    description: 'Creates and returns a new string by concatenating all of the elements in an array, separated by commas or a specified separator string.',
    arguments: [
      { name: 'separator', type: 'string', description: 'String to separate each pair of adjacent elements', optional: true, defaultValue: '"," ' },
    ],
    returns: { type: 'string', description: 'A string with all array elements joined' },
    examples: [
      { code: '["a", "b", "c"].join()', output: '"a,b,c"' },
      { code: '["a", "b", "c"].join("-")', output: '"a-b-c"' },
      { code: '[1, 2, 3].join("")', output: '"123"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['toString', 'split'],
    sinceVersion: 'ES1',
  },
  {
    name: 'push',
    category: 'Array Methods',
    syntax: 'array.push(element1, element2, ...)',
    description: 'Adds one or more elements to the end of an array and returns the new length of the array.',
    arguments: [
      { name: 'elements', type: 'any', description: 'The elements to add to the end of the array' },
    ],
    returns: { type: 'number', description: 'The new length of the array' },
    examples: [
      { code: 'let arr = [1, 2]; arr.push(3); arr', output: '[1, 2, 3]' },
      { code: 'let arr = [1]; arr.push(2, 3, 4); arr', output: '[1, 2, 3, 4]' },
      { code: '[1, 2].push(3)', output: '3', explanation: 'Returns new length' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['pop', 'unshift', 'concat'],
    sinceVersion: 'ES3',
    notes: ['Modifies the original array'],
  },
  {
    name: 'pop',
    category: 'Array Methods',
    syntax: 'array.pop()',
    description: 'Removes the last element from an array and returns that element.',
    arguments: [],
    returns: { type: 'any', description: 'The removed element, or undefined if the array is empty' },
    examples: [
      { code: 'let arr = [1, 2, 3]; arr.pop()', output: '3' },
      { code: 'let arr = [1, 2, 3]; arr.pop(); arr', output: '[1, 2]' },
      { code: '[].pop()', output: 'undefined' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['push', 'shift', 'slice'],
    sinceVersion: 'ES3',
    notes: ['Modifies the original array'],
  },
  {
    name: 'shift',
    category: 'Array Methods',
    syntax: 'array.shift()',
    description: 'Removes the first element from an array and returns that removed element.',
    arguments: [],
    returns: { type: 'any', description: 'The removed element, or undefined if the array is empty' },
    examples: [
      { code: 'let arr = [1, 2, 3]; arr.shift()', output: '1' },
      { code: 'let arr = [1, 2, 3]; arr.shift(); arr', output: '[2, 3]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['unshift', 'pop', 'slice'],
    sinceVersion: 'ES3',
    notes: ['Modifies the original array', 'O(n) because all elements must be re-indexed'],
  },
  {
    name: 'unshift',
    category: 'Array Methods',
    syntax: 'array.unshift(element1, element2, ...)',
    description: 'Adds one or more elements to the beginning of an array and returns the new length of the array.',
    arguments: [
      { name: 'elements', type: 'any', description: 'The elements to add to the front of the array' },
    ],
    returns: { type: 'number', description: 'The new length of the array' },
    examples: [
      { code: 'let arr = [1, 2]; arr.unshift(0); arr', output: '[0, 1, 2]' },
      { code: 'let arr = [3]; arr.unshift(1, 2); arr', output: '[1, 2, 3]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['shift', 'push', 'concat'],
    sinceVersion: 'ES3',
    notes: ['Modifies the original array'],
  },
  {
    name: 'indexOf',
    category: 'Array Methods',
    syntax: 'array.indexOf(searchElement, fromIndex)',
    description: 'Returns the first index at which a given element can be found in the array, or -1 if it is not present.',
    arguments: [
      { name: 'searchElement', type: 'any', description: 'Element to locate in the array' },
      { name: 'fromIndex', type: 'number', description: 'The index to start the search at', optional: true, defaultValue: '0' },
    ],
    returns: { type: 'number', description: 'The first index of the element in the array, or -1 if not found' },
    examples: [
      { code: '[1, 2, 3, 2].indexOf(2)', output: '1' },
      { code: '[1, 2, 3].indexOf(4)', output: '-1' },
      { code: '[1, 2, 3, 2].indexOf(2, 2)', output: '3' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['lastIndexOf', 'includes', 'findIndex'],
    sinceVersion: 'ES5',
    notes: ['Uses strict equality (===) for comparison', 'Does not handle NaN correctly - use includes() instead'],
  },
  {
    name: 'fill',
    category: 'Array Methods',
    syntax: 'array.fill(value, start, end)',
    description: 'Fills all the elements of an array from a start index to an end index with a static value.',
    arguments: [
      { name: 'value', type: 'any', description: 'Value to fill the array with' },
      { name: 'start', type: 'number', description: 'Start index', optional: true, defaultValue: '0' },
      { name: 'end', type: 'number', description: 'End index', optional: true, defaultValue: 'array.length' },
    ],
    returns: { type: 'Array', description: 'The modified array' },
    examples: [
      { code: '[1, 2, 3].fill(0)', output: '[0, 0, 0]' },
      { code: '[1, 2, 3, 4].fill(0, 1, 3)', output: '[1, 0, 0, 4]' },
      { code: 'new Array(3).fill(1)', output: '[1, 1, 1]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['map', 'Array.from'],
    sinceVersion: 'ES6',
    notes: ['Modifies the original array'],
  },
  {
    name: 'at',
    category: 'Array Methods',
    syntax: 'array.at(index)',
    description: 'Returns the element at the given index, allowing for positive and negative integers. Negative integers count back from the last element.',
    arguments: [
      { name: 'index', type: 'number', description: 'Zero-based index of the array element to be returned' },
    ],
    returns: { type: 'any', description: 'The element at the given index, or undefined' },
    examples: [
      { code: '[1, 2, 3, 4, 5].at(2)', output: '3' },
      { code: '[1, 2, 3, 4, 5].at(-1)', output: '5' },
      { code: '[1, 2, 3, 4, 5].at(-2)', output: '4' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['slice', 'indexOf'],
    sinceVersion: 'ES2022',
  },

  // ============================================================
  // String Methods
  // ============================================================
  {
    name: 'split',
    category: 'String Methods',
    syntax: 'string.split(separator, limit)',
    description: 'Divides a String into an ordered list of substrings, puts these substrings into an array, and returns the array.',
    arguments: [
      { name: 'separator', type: 'string | RegExp', description: 'The pattern describing where each split should occur' },
      { name: 'limit', type: 'number', description: 'Limits the number of pieces the string is split into', optional: true },
    ],
    returns: { type: 'string[]', description: 'An array of strings split at each point where the separator occurs' },
    examples: [
      { code: '"a,b,c".split(",")', output: '["a", "b", "c"]' },
      { code: '"hello world".split(" ")', output: '["hello", "world"]' },
      { code: '"hello".split("")', output: '["h", "e", "l", "l", "o"]' },
      { code: '"a,b,c,d".split(",", 2)', output: '["a", "b"]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['join', 'slice', 'substring'],
    sinceVersion: 'ES3',
  },
  {
    name: 'substring',
    category: 'String Methods',
    syntax: 'string.substring(indexStart, indexEnd)',
    description: 'Returns the part of the string between the start and end indexes, or to the end of the string.',
    arguments: [
      { name: 'indexStart', type: 'number', description: 'The index of the first character to include' },
      { name: 'indexEnd', type: 'number', description: 'The index of the first character to exclude', optional: true },
    ],
    returns: { type: 'string', description: 'A new string containing the specified part of the given string' },
    examples: [
      { code: '"Mozilla".substring(1, 3)', output: '"oz"' },
      { code: '"Mozilla".substring(2)', output: '"zilla"' },
      { code: '"Mozilla".substring(0, 1)', output: '"M"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['slice', 'substr', 'split'],
    sinceVersion: 'ES1',
  },
  {
    name: 'toLowerCase',
    category: 'String Methods',
    syntax: 'string.toLowerCase()',
    description: 'Returns the calling string value converted to lower case.',
    arguments: [],
    returns: { type: 'string', description: 'A new string representing the calling string converted to lower case' },
    examples: [
      { code: '"HELLO".toLowerCase()', output: '"hello"' },
      { code: '"Hello World".toLowerCase()', output: '"hello world"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['toUpperCase', 'toLocaleLowerCase'],
    sinceVersion: 'ES1',
  },
  {
    name: 'toUpperCase',
    category: 'String Methods',
    syntax: 'string.toUpperCase()',
    description: 'Returns the calling string value converted to upper case.',
    arguments: [],
    returns: { type: 'string', description: 'A new string representing the calling string converted to upper case' },
    examples: [
      { code: '"hello".toUpperCase()', output: '"HELLO"' },
      { code: '"Hello World".toUpperCase()', output: '"HELLO WORLD"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['toLowerCase', 'toLocaleUpperCase'],
    sinceVersion: 'ES1',
  },
  {
    name: 'trim',
    category: 'String Methods',
    syntax: 'string.trim()',
    description: 'Removes whitespace from both ends of a string and returns a new string.',
    arguments: [],
    returns: { type: 'string', description: 'A new string with whitespace removed from both ends' },
    examples: [
      { code: '"  hello  ".trim()', output: '"hello"' },
      { code: '"\\n\\t hello \\n".trim()', output: '"hello"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['trimStart', 'trimEnd'],
    sinceVersion: 'ES5',
  },
  {
    name: 'replace',
    category: 'String Methods',
    syntax: 'string.replace(searchValue, replaceValue)',
    description: 'Returns a new string with one, some, or all matches of a pattern replaced by a replacement.',
    arguments: [
      { name: 'searchValue', type: 'string | RegExp', description: 'The value to search for' },
      { name: 'replaceValue', type: 'string | Function', description: 'The value to replace with' },
    ],
    returns: { type: 'string', description: 'A new string with the replacement(s) made' },
    examples: [
      { code: '"hello world".replace("world", "there")', output: '"hello there"' },
      { code: '"aabbcc".replace(/b/g, "x")', output: '"aaxxcc"' },
      { code: '"hello".replace(/./g, c => c.toUpperCase())', output: '"HELLO"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['replaceAll', 'match', 'split'],
    sinceVersion: 'ES3',
    notes: ['Without regex /g flag, only first occurrence is replaced'],
  },
  {
    name: 'replaceAll',
    category: 'String Methods',
    syntax: 'string.replaceAll(searchValue, replaceValue)',
    description: 'Returns a new string with all matches of a pattern replaced by a replacement.',
    arguments: [
      { name: 'searchValue', type: 'string | RegExp', description: 'The value to search for' },
      { name: 'replaceValue', type: 'string | Function', description: 'The value to replace with' },
    ],
    returns: { type: 'string', description: 'A new string with all replacements made' },
    examples: [
      { code: '"aabbaa".replaceAll("a", "x")', output: '"xxbbxx"' },
      { code: '"hello world world".replaceAll("world", "there")', output: '"hello there there"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['replace', 'split', 'join'],
    sinceVersion: 'ES2021',
  },
  {
    name: 'startsWith',
    category: 'String Methods',
    syntax: 'string.startsWith(searchString, position)',
    description: 'Determines whether a string begins with the characters of a specified string.',
    arguments: [
      { name: 'searchString', type: 'string', description: 'The characters to be searched for' },
      { name: 'position', type: 'number', description: 'The position to begin searching', optional: true, defaultValue: '0' },
    ],
    returns: { type: 'boolean', description: 'true if the string begins with the search string, false otherwise' },
    examples: [
      { code: '"hello world".startsWith("hello")', output: 'true' },
      { code: '"hello world".startsWith("world")', output: 'false' },
      { code: '"hello world".startsWith("world", 6)', output: 'true' },
    ],
    timeComplexity: 'O(m)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['endsWith', 'includes', 'indexOf'],
    sinceVersion: 'ES6',
  },
  {
    name: 'endsWith',
    category: 'String Methods',
    syntax: 'string.endsWith(searchString, length)',
    description: 'Determines whether a string ends with the characters of a specified string.',
    arguments: [
      { name: 'searchString', type: 'string', description: 'The characters to be searched for' },
      { name: 'length', type: 'number', description: 'The length of string to search', optional: true },
    ],
    returns: { type: 'boolean', description: 'true if the string ends with the search string, false otherwise' },
    examples: [
      { code: '"hello world".endsWith("world")', output: 'true' },
      { code: '"hello world".endsWith("hello")', output: 'false' },
      { code: '"hello world".endsWith("hello", 5)', output: 'true' },
    ],
    timeComplexity: 'O(m)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['startsWith', 'includes', 'indexOf'],
    sinceVersion: 'ES6',
  },
  {
    name: 'padStart',
    category: 'String Methods',
    syntax: 'string.padStart(targetLength, padString)',
    description: 'Pads the current string with another string until the resulting string reaches the given length. Padding is applied from the start.',
    arguments: [
      { name: 'targetLength', type: 'number', description: 'The length of the resulting string' },
      { name: 'padString', type: 'string', description: 'The string to pad with', optional: true, defaultValue: '" "' },
    ],
    returns: { type: 'string', description: 'A new string padded to the given length' },
    examples: [
      { code: '"5".padStart(3, "0")', output: '"005"' },
      { code: '"hello".padStart(10)', output: '"     hello"' },
      { code: '"abc".padStart(6, "123")', output: '"123abc"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['padEnd', 'repeat'],
    sinceVersion: 'ES2017',
  },
  {
    name: 'repeat',
    category: 'String Methods',
    syntax: 'string.repeat(count)',
    description: 'Constructs and returns a new string which contains the specified number of copies of the string.',
    arguments: [
      { name: 'count', type: 'number', description: 'An integer indicating the number of times to repeat the string' },
    ],
    returns: { type: 'string', description: 'A new string containing the specified number of copies' },
    examples: [
      { code: '"abc".repeat(3)', output: '"abcabcabc"' },
      { code: '"x".repeat(5)', output: '"xxxxx"' },
      { code: '"".repeat(10)', output: '""' },
    ],
    timeComplexity: 'O(n * count)',
    spaceComplexity: 'O(n * count)',
    relatedMethods: ['padStart', 'padEnd', 'concat'],
    sinceVersion: 'ES6',
  },
  {
    name: 'charAt',
    category: 'String Methods',
    syntax: 'string.charAt(index)',
    description: 'Returns a new string consisting of the single UTF-16 code unit located at the specified offset into the string.',
    arguments: [
      { name: 'index', type: 'number', description: 'An integer between 0 and string.length - 1' },
    ],
    returns: { type: 'string', description: 'A string representing the character at the specified index' },
    examples: [
      { code: '"hello".charAt(1)', output: '"e"' },
      { code: '"hello".charAt(0)', output: '"h"' },
      { code: '"hello".charAt(10)', output: '""' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['charCodeAt', 'at', 'indexOf'],
    sinceVersion: 'ES1',
  },

  // ============================================================
  // Object Methods
  // ============================================================
  {
    name: 'Object.keys',
    category: 'Object Methods',
    syntax: 'Object.keys(obj)',
    description: 'Returns an array of a given object\'s own enumerable property names, iterated in the same order as a normal loop.',
    arguments: [
      { name: 'obj', type: 'Object', description: 'The object whose enumerable own properties are to be returned' },
    ],
    returns: { type: 'string[]', description: 'An array of strings representing all enumerable properties' },
    examples: [
      { code: 'Object.keys({ a: 1, b: 2, c: 3 })', output: '["a", "b", "c"]' },
      { code: 'Object.keys([1, 2, 3])', output: '["0", "1", "2"]' },
      { code: 'Object.keys({})', output: '[]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['Object.values', 'Object.entries', 'Object.getOwnPropertyNames'],
    sinceVersion: 'ES5',
  },
  {
    name: 'Object.values',
    category: 'Object Methods',
    syntax: 'Object.values(obj)',
    description: 'Returns an array of a given object\'s own enumerable property values.',
    arguments: [
      { name: 'obj', type: 'Object', description: 'The object whose enumerable own property values are to be returned' },
    ],
    returns: { type: 'any[]', description: 'An array containing the object\'s property values' },
    examples: [
      { code: 'Object.values({ a: 1, b: 2, c: 3 })', output: '[1, 2, 3]' },
      { code: 'Object.values({ name: "John", age: 30 })', output: '["John", 30]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['Object.keys', 'Object.entries'],
    sinceVersion: 'ES2017',
  },
  {
    name: 'Object.entries',
    category: 'Object Methods',
    syntax: 'Object.entries(obj)',
    description: 'Returns an array of a given object\'s own enumerable string-keyed property [key, value] pairs.',
    arguments: [
      { name: 'obj', type: 'Object', description: 'The object whose enumerable own property pairs are to be returned' },
    ],
    returns: { type: '[string, any][]', description: 'An array of [key, value] pairs' },
    examples: [
      { code: 'Object.entries({ a: 1, b: 2 })', output: '[["a", 1], ["b", 2]]' },
      { code: 'Object.entries({ name: "John" })', output: '[["name", "John"]]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['Object.keys', 'Object.values', 'Object.fromEntries'],
    sinceVersion: 'ES2017',
  },
  {
    name: 'Object.fromEntries',
    category: 'Object Methods',
    syntax: 'Object.fromEntries(iterable)',
    description: 'Transforms a list of key-value pairs into an object.',
    arguments: [
      { name: 'iterable', type: 'Iterable', description: 'An iterable such as Array or Map containing key-value pairs' },
    ],
    returns: { type: 'Object', description: 'A new object whose properties are given by the entries of the iterable' },
    examples: [
      { code: 'Object.fromEntries([["a", 1], ["b", 2]])', output: '{ a: 1, b: 2 }' },
      { code: 'Object.fromEntries(new Map([["name", "John"]]))', output: '{ name: "John" }' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['Object.entries', 'Map'],
    sinceVersion: 'ES2019',
  },
  {
    name: 'Object.assign',
    category: 'Object Methods',
    syntax: 'Object.assign(target, ...sources)',
    description: 'Copies all enumerable own properties from one or more source objects to a target object. It returns the modified target object.',
    arguments: [
      { name: 'target', type: 'Object', description: 'The target object to copy to' },
      { name: 'sources', type: 'Object', description: 'The source object(s) to copy from' },
    ],
    returns: { type: 'Object', description: 'The target object' },
    examples: [
      { code: 'Object.assign({}, { a: 1 }, { b: 2 })', output: '{ a: 1, b: 2 }' },
      { code: 'Object.assign({ a: 1 }, { a: 2, b: 3 })', output: '{ a: 2, b: 3 }' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['spread operator', 'Object.create'],
    sinceVersion: 'ES6',
    notes: ['Performs shallow copy only', 'Modifies and returns the target object'],
  },
  {
    name: 'Object.freeze',
    category: 'Object Methods',
    syntax: 'Object.freeze(obj)',
    description: 'Freezes an object. A frozen object can no longer be changed; freezing prevents adding new properties, removing existing properties, and changing values.',
    arguments: [
      { name: 'obj', type: 'Object', description: 'The object to freeze' },
    ],
    returns: { type: 'Object', description: 'The same object that was passed to the function' },
    examples: [
      { code: 'const obj = Object.freeze({ a: 1 }); obj.a = 2; obj.a', output: '1' },
      { code: 'Object.isFrozen(Object.freeze({}))', output: 'true' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Object.seal', 'Object.isFrozen', 'Object.preventExtensions'],
    sinceVersion: 'ES5',
    notes: ['Only freezes top level - nested objects are not frozen'],
  },
  {
    name: 'hasOwnProperty',
    category: 'Object Methods',
    syntax: 'object.hasOwnProperty(prop)',
    description: 'Returns a boolean indicating whether the object has the specified property as its own property.',
    arguments: [
      { name: 'prop', type: 'string | Symbol', description: 'The name of the property to test' },
    ],
    returns: { type: 'boolean', description: 'true if the object has the specified property as own property; false otherwise' },
    examples: [
      { code: '({ a: 1 }).hasOwnProperty("a")', output: 'true' },
      { code: '({ a: 1 }).hasOwnProperty("b")', output: 'false' },
      { code: '({ a: 1 }).hasOwnProperty("toString")', output: 'false', explanation: 'Inherited properties return false' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['in operator', 'Object.hasOwn', 'Object.keys'],
    sinceVersion: 'ES3',
    notes: ['Use Object.hasOwn() in modern code as a safer alternative'],
  },

  // ============================================================
  // Math Operations
  // ============================================================
  {
    name: 'Math.max',
    category: 'Math Operations',
    syntax: 'Math.max(value1, value2, ...)',
    description: 'Returns the largest of zero or more numbers.',
    arguments: [
      { name: 'values', type: 'number', description: 'Zero or more numbers to compare' },
    ],
    returns: { type: 'number', description: 'The largest of the given numbers, or -Infinity if no arguments' },
    examples: [
      { code: 'Math.max(1, 3, 2)', output: '3' },
      { code: 'Math.max(...[1, 2, 3])', output: '3' },
      { code: 'Math.max()', output: '-Infinity' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Math.min', 'Array.reduce'],
    sinceVersion: 'ES1',
  },
  {
    name: 'Math.min',
    category: 'Math Operations',
    syntax: 'Math.min(value1, value2, ...)',
    description: 'Returns the smallest of zero or more numbers.',
    arguments: [
      { name: 'values', type: 'number', description: 'Zero or more numbers to compare' },
    ],
    returns: { type: 'number', description: 'The smallest of the given numbers, or Infinity if no arguments' },
    examples: [
      { code: 'Math.min(1, 3, 2)', output: '1' },
      { code: 'Math.min(...[1, 2, 3])', output: '1' },
      { code: 'Math.min()', output: 'Infinity' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Math.max', 'Array.reduce'],
    sinceVersion: 'ES1',
  },
  {
    name: 'Math.floor',
    category: 'Math Operations',
    syntax: 'Math.floor(x)',
    description: 'Returns the largest integer less than or equal to a given number.',
    arguments: [
      { name: 'x', type: 'number', description: 'A number' },
    ],
    returns: { type: 'number', description: 'The largest integer less than or equal to x' },
    examples: [
      { code: 'Math.floor(5.9)', output: '5' },
      { code: 'Math.floor(-5.1)', output: '-6' },
      { code: 'Math.floor(5)', output: '5' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Math.ceil', 'Math.round', 'Math.trunc'],
    sinceVersion: 'ES1',
  },
  {
    name: 'Math.ceil',
    category: 'Math Operations',
    syntax: 'Math.ceil(x)',
    description: 'Returns the smallest integer greater than or equal to a given number.',
    arguments: [
      { name: 'x', type: 'number', description: 'A number' },
    ],
    returns: { type: 'number', description: 'The smallest integer greater than or equal to x' },
    examples: [
      { code: 'Math.ceil(5.1)', output: '6' },
      { code: 'Math.ceil(-5.9)', output: '-5' },
      { code: 'Math.ceil(5)', output: '5' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Math.floor', 'Math.round', 'Math.trunc'],
    sinceVersion: 'ES1',
  },
  {
    name: 'Math.round',
    category: 'Math Operations',
    syntax: 'Math.round(x)',
    description: 'Returns the value of a number rounded to the nearest integer.',
    arguments: [
      { name: 'x', type: 'number', description: 'A number' },
    ],
    returns: { type: 'number', description: 'The value of x rounded to the nearest integer' },
    examples: [
      { code: 'Math.round(5.5)', output: '6' },
      { code: 'Math.round(5.4)', output: '5' },
      { code: 'Math.round(-5.5)', output: '-5' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Math.floor', 'Math.ceil', 'Math.trunc'],
    sinceVersion: 'ES1',
  },
  {
    name: 'Math.abs',
    category: 'Math Operations',
    syntax: 'Math.abs(x)',
    description: 'Returns the absolute value of a number.',
    arguments: [
      { name: 'x', type: 'number', description: 'A number' },
    ],
    returns: { type: 'number', description: 'The absolute value of x' },
    examples: [
      { code: 'Math.abs(-5)', output: '5' },
      { code: 'Math.abs(5)', output: '5' },
      { code: 'Math.abs(-0)', output: '0' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Math.sign'],
    sinceVersion: 'ES1',
  },
  {
    name: 'Math.random',
    category: 'Math Operations',
    syntax: 'Math.random()',
    description: 'Returns a floating-point, pseudo-random number in the range 0 to less than 1.',
    arguments: [],
    returns: { type: 'number', description: 'A floating-point number from 0 (inclusive) to 1 (exclusive)' },
    examples: [
      { code: 'Math.random()', output: '0.123456789... (example)' },
      { code: 'Math.floor(Math.random() * 10)', output: '0-9 (random integer)' },
      { code: 'Math.floor(Math.random() * (max - min + 1)) + min', output: 'Random integer between min and max' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Math.floor', 'crypto.getRandomValues'],
    sinceVersion: 'ES1',
    notes: ['Not cryptographically secure - use crypto.getRandomValues() for security'],
  },
  {
    name: 'Math.pow',
    category: 'Math Operations',
    syntax: 'Math.pow(base, exponent)',
    description: 'Returns the base to the exponent power.',
    arguments: [
      { name: 'base', type: 'number', description: 'The base number' },
      { name: 'exponent', type: 'number', description: 'The exponent to raise the base by' },
    ],
    returns: { type: 'number', description: 'base raised to the power of exponent' },
    examples: [
      { code: 'Math.pow(2, 3)', output: '8' },
      { code: 'Math.pow(4, 0.5)', output: '2' },
      { code: '2 ** 3', output: '8', explanation: 'ES6 exponentiation operator alternative' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Math.sqrt', 'Math.cbrt', '** operator'],
    sinceVersion: 'ES1',
  },
  {
    name: 'Math.sqrt',
    category: 'Math Operations',
    syntax: 'Math.sqrt(x)',
    description: 'Returns the square root of a number.',
    arguments: [
      { name: 'x', type: 'number', description: 'A number greater than or equal to 0' },
    ],
    returns: { type: 'number', description: 'The square root of x, or NaN if x is negative' },
    examples: [
      { code: 'Math.sqrt(9)', output: '3' },
      { code: 'Math.sqrt(2)', output: '1.4142135623730951' },
      { code: 'Math.sqrt(-1)', output: 'NaN' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Math.pow', 'Math.cbrt'],
    sinceVersion: 'ES1',
  },

  // ============================================================
  // JSON Methods
  // ============================================================
  {
    name: 'JSON.parse',
    category: 'JSON Methods',
    syntax: 'JSON.parse(text, reviver)',
    description: 'Parses a JSON string, constructing the JavaScript value or object described by the string.',
    arguments: [
      { name: 'text', type: 'string', description: 'The string to parse as JSON' },
      { name: 'reviver', type: 'Function', description: 'Function to transform the results', optional: true },
    ],
    returns: { type: 'any', description: 'The JavaScript value corresponding to the given JSON text' },
    examples: [
      { code: 'JSON.parse(\'{"a": 1, "b": 2}\')', output: '{ a: 1, b: 2 }' },
      { code: 'JSON.parse(\'[1, 2, 3]\')', output: '[1, 2, 3]' },
      { code: 'JSON.parse(\'"hello"\')', output: '"hello"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['JSON.stringify'],
    sinceVersion: 'ES5',
    notes: ['Throws SyntaxError if the string is not valid JSON'],
  },
  {
    name: 'JSON.stringify',
    category: 'JSON Methods',
    syntax: 'JSON.stringify(value, replacer, space)',
    description: 'Converts a JavaScript value to a JSON string, optionally replacing values if a replacer function is specified.',
    arguments: [
      { name: 'value', type: 'any', description: 'The value to convert to a JSON string' },
      { name: 'replacer', type: 'Function | Array', description: 'Function or array to filter properties', optional: true },
      { name: 'space', type: 'string | number', description: 'Indentation space for formatting', optional: true },
    ],
    returns: { type: 'string', description: 'A JSON string representing the given value' },
    examples: [
      { code: 'JSON.stringify({ a: 1, b: 2 })', output: '\'{"a":1,"b":2}\'' },
      { code: 'JSON.stringify({ a: 1 }, null, 2)', output: '\'{\\n  "a": 1\\n}\'' },
      { code: 'JSON.stringify([1, 2, 3])', output: '\'[1,2,3]\'' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['JSON.parse'],
    sinceVersion: 'ES5',
    notes: ['Ignores functions, undefined, and Symbol values'],
  },

  // ============================================================
  // Promise Methods
  // ============================================================
  {
    name: 'Promise.all',
    category: 'Promise Methods',
    syntax: 'Promise.all(iterable)',
    description: 'Takes an iterable of promises and returns a single Promise that resolves when all of the promises resolve, or rejects when any promise rejects.',
    arguments: [
      { name: 'iterable', type: 'Iterable<Promise>', description: 'An iterable of promises' },
    ],
    returns: { type: 'Promise<Array>', description: 'A promise that resolves to an array of all resolved values' },
    examples: [
      { code: 'Promise.all([Promise.resolve(1), Promise.resolve(2)])', output: 'Promise<[1, 2]>' },
      { code: 'await Promise.all([fetch(url1), fetch(url2)])', output: '[response1, response2]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['Promise.allSettled', 'Promise.race', 'Promise.any'],
    sinceVersion: 'ES6',
    notes: ['Fails fast - rejects immediately if any promise rejects'],
  },
  {
    name: 'Promise.allSettled',
    category: 'Promise Methods',
    syntax: 'Promise.allSettled(iterable)',
    description: 'Returns a promise that resolves after all of the given promises have either fulfilled or rejected, with an array of objects describing the outcome of each promise.',
    arguments: [
      { name: 'iterable', type: 'Iterable<Promise>', description: 'An iterable of promises' },
    ],
    returns: { type: 'Promise<Array>', description: 'A promise resolving to an array of outcome objects' },
    examples: [
      { code: 'Promise.allSettled([Promise.resolve(1), Promise.reject("error")])', output: '[{status: "fulfilled", value: 1}, {status: "rejected", reason: "error"}]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['Promise.all', 'Promise.race', 'Promise.any'],
    sinceVersion: 'ES2020',
    notes: ['Never rejects - always waits for all promises to settle'],
  },
  {
    name: 'Promise.race',
    category: 'Promise Methods',
    syntax: 'Promise.race(iterable)',
    description: 'Returns a promise that fulfills or rejects as soon as one of the promises in an iterable fulfills or rejects.',
    arguments: [
      { name: 'iterable', type: 'Iterable<Promise>', description: 'An iterable of promises' },
    ],
    returns: { type: 'Promise', description: 'A promise that settles with the state of the first promise to settle' },
    examples: [
      { code: 'Promise.race([slowPromise, fastPromise])', output: 'Result of whichever resolves/rejects first' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Promise.all', 'Promise.any', 'Promise.allSettled'],
    sinceVersion: 'ES6',
  },

  // ============================================================
  // Set Methods
  // ============================================================
  {
    name: 'Set.add',
    category: 'Set Methods',
    syntax: 'set.add(value)',
    description: 'Appends a new element with a specified value to the end of a Set object.',
    arguments: [
      { name: 'value', type: 'any', description: 'The value to add to the Set' },
    ],
    returns: { type: 'Set', description: 'The Set object with the added value' },
    examples: [
      { code: 'new Set().add(1).add(2).add(1)', output: 'Set { 1, 2 }' },
      { code: 'const s = new Set([1, 2]); s.add(3); [...s]', output: '[1, 2, 3]' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Set.has', 'Set.delete', 'Set.clear'],
    sinceVersion: 'ES6',
  },
  {
    name: 'Set.has',
    category: 'Set Methods',
    syntax: 'set.has(value)',
    description: 'Returns a boolean indicating whether an element with the specified value exists in a Set object.',
    arguments: [
      { name: 'value', type: 'any', description: 'The value to test for presence in the Set' },
    ],
    returns: { type: 'boolean', description: 'true if the value exists in the Set, false otherwise' },
    examples: [
      { code: 'new Set([1, 2, 3]).has(2)', output: 'true' },
      { code: 'new Set([1, 2, 3]).has(4)', output: 'false' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Set.add', 'Set.delete'],
    sinceVersion: 'ES6',
  },
  {
    name: 'Set.delete',
    category: 'Set Methods',
    syntax: 'set.delete(value)',
    description: 'Removes a specified value from a Set object, if it is in the set.',
    arguments: [
      { name: 'value', type: 'any', description: 'The value to remove from the Set' },
    ],
    returns: { type: 'boolean', description: 'true if the element was removed, false if it was not in the Set' },
    examples: [
      { code: 'const s = new Set([1, 2, 3]); s.delete(2); [...s]', output: '[1, 3]' },
      { code: 'new Set([1, 2]).delete(3)', output: 'false' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Set.add', 'Set.has', 'Set.clear'],
    sinceVersion: 'ES6',
  },

  // ============================================================
  // Map Methods
  // ============================================================
  {
    name: 'Map.set',
    category: 'Map Methods',
    syntax: 'map.set(key, value)',
    description: 'Adds or updates an entry in the Map object with a specified key and value.',
    arguments: [
      { name: 'key', type: 'any', description: 'The key of the element to add to the Map' },
      { name: 'value', type: 'any', description: 'The value of the element to add to the Map' },
    ],
    returns: { type: 'Map', description: 'The Map object' },
    examples: [
      { code: 'new Map().set("a", 1).set("b", 2)', output: 'Map { "a" => 1, "b" => 2 }' },
      { code: 'const m = new Map(); m.set("key", "value"); m.get("key")', output: '"value"' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Map.get', 'Map.has', 'Map.delete'],
    sinceVersion: 'ES6',
  },
  {
    name: 'Map.get',
    category: 'Map Methods',
    syntax: 'map.get(key)',
    description: 'Returns a specified element from a Map object.',
    arguments: [
      { name: 'key', type: 'any', description: 'The key of the element to return' },
    ],
    returns: { type: 'any', description: 'The element associated with the key, or undefined if not found' },
    examples: [
      { code: 'new Map([["a", 1], ["b", 2]]).get("a")', output: '1' },
      { code: 'new Map([["a", 1]]).get("b")', output: 'undefined' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Map.set', 'Map.has'],
    sinceVersion: 'ES6',
  },
  {
    name: 'Map.has',
    category: 'Map Methods',
    syntax: 'map.has(key)',
    description: 'Returns a boolean indicating whether an element with the specified key exists in a Map object.',
    arguments: [
      { name: 'key', type: 'any', description: 'The key to test for presence in the Map' },
    ],
    returns: { type: 'boolean', description: 'true if the key exists in the Map, false otherwise' },
    examples: [
      { code: 'new Map([["a", 1]]).has("a")', output: 'true' },
      { code: 'new Map([["a", 1]]).has("b")', output: 'false' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Map.get', 'Map.set', 'Map.delete'],
    sinceVersion: 'ES6',
  },
];
