import type { Method } from '../types';

export const javaMethods: Method[] = [
  // ============================================================
  // ArrayList Methods
  // ============================================================
  {
    name: 'add',
    category: 'ArrayList Methods',
    syntax: 'list.add(element) | list.add(index, element)',
    description:
      'Appends the specified element to the end of the list, or inserts it at the specified position.',
    arguments: [
      {
        name: 'index',
        type: 'int',
        description: 'Index at which to insert (optional)',
        optional: true,
      },
      { name: 'element', type: 'E', description: 'Element to be inserted' },
    ],
    returns: {
      type: 'boolean | void',
      description: 'true if list changed (for single arg), void for indexed insert',
    },
    examples: [
      {
        code: 'List<Integer> list = new ArrayList<>(); list.add(1); list.add(2);',
        output: '[1, 2]',
      },
      { code: 'list.add(0, 10);', output: '[10, 1, 2]' },
    ],
    timeComplexity: 'O(1) amortized for append, O(n) for indexed insert',
    spaceComplexity: 'O(1)',
    relatedMethods: ['addAll', 'set', 'remove'],
  },
  {
    name: 'get',
    category: 'ArrayList Methods',
    syntax: 'list.get(index)',
    description: 'Returns the element at the specified position in this list.',
    arguments: [{ name: 'index', type: 'int', description: 'Index of the element to return' }],
    returns: { type: 'E', description: 'The element at the specified position' },
    examples: [
      { code: 'List<String> list = Arrays.asList("a", "b", "c"); list.get(1)', output: '"b"' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['set', 'indexOf', 'contains'],
    notes: ['Throws IndexOutOfBoundsException if index is out of range'],
  },
  {
    name: 'set',
    category: 'ArrayList Methods',
    syntax: 'list.set(index, element)',
    description: 'Replaces the element at the specified position with the specified element.',
    arguments: [
      { name: 'index', type: 'int', description: 'Index of element to replace' },
      { name: 'element', type: 'E', description: 'Element to be stored' },
    ],
    returns: { type: 'E', description: 'The element previously at the specified position' },
    examples: [
      {
        code: 'List<String> list = new ArrayList<>(Arrays.asList("a", "b")); list.set(0, "x");',
        output: 'Returns "a", list is ["x", "b"]',
      },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['get', 'add', 'remove'],
  },
  {
    name: 'remove',
    category: 'ArrayList Methods',
    syntax: 'list.remove(index) | list.remove(object)',
    description:
      'Removes the element at the specified position or the first occurrence of the specified element.',
    arguments: [
      { name: 'index', type: 'int', description: 'Index of element to remove' },
      { name: 'object', type: 'Object', description: 'Element to be removed if present' },
    ],
    returns: {
      type: 'E | boolean',
      description: 'Removed element (by index) or true if element was found (by object)',
    },
    examples: [
      {
        code: 'List<Integer> list = new ArrayList<>(Arrays.asList(1, 2, 3)); list.remove(1);',
        output: 'Returns 2, list is [1, 3]',
      },
      { code: 'list.remove(Integer.valueOf(1));', output: 'Returns true, list is [3]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['add', 'clear', 'removeAll'],
    notes: ['For Integer lists, use Integer.valueOf() to remove by object'],
  },
  {
    name: 'size',
    category: 'ArrayList Methods',
    syntax: 'list.size()',
    description: 'Returns the number of elements in this list.',
    arguments: [],
    returns: { type: 'int', description: 'The number of elements in this list' },
    examples: [
      { code: 'Arrays.asList(1, 2, 3).size()', output: '3' },
      { code: 'new ArrayList<>().size()', output: '0' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['isEmpty', 'clear'],
  },
  {
    name: 'isEmpty',
    category: 'ArrayList Methods',
    syntax: 'list.isEmpty()',
    description: 'Returns true if this list contains no elements.',
    arguments: [],
    returns: { type: 'boolean', description: 'true if this list contains no elements' },
    examples: [
      { code: 'new ArrayList<>().isEmpty()', output: 'true' },
      { code: 'Arrays.asList(1).isEmpty()', output: 'false' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['size', 'clear'],
  },
  {
    name: 'contains',
    category: 'ArrayList Methods',
    syntax: 'list.contains(object)',
    description: 'Returns true if this list contains the specified element.',
    arguments: [{ name: 'object', type: 'Object', description: 'Element to search for' }],
    returns: { type: 'boolean', description: 'true if list contains the element' },
    examples: [
      { code: 'Arrays.asList(1, 2, 3).contains(2)', output: 'true' },
      { code: 'Arrays.asList("a", "b").contains("c")', output: 'false' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['indexOf', 'containsAll'],
  },
  {
    name: 'indexOf',
    category: 'ArrayList Methods',
    syntax: 'list.indexOf(object)',
    description:
      'Returns the index of the first occurrence of the specified element, or -1 if not found.',
    arguments: [{ name: 'object', type: 'Object', description: 'Element to search for' }],
    returns: { type: 'int', description: 'Index of first occurrence, or -1' },
    examples: [
      { code: 'Arrays.asList("a", "b", "c", "b").indexOf("b")', output: '1' },
      { code: 'Arrays.asList(1, 2, 3).indexOf(5)', output: '-1' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['lastIndexOf', 'contains', 'get'],
  },
  {
    name: 'subList',
    category: 'ArrayList Methods',
    syntax: 'list.subList(fromIndex, toIndex)',
    description: 'Returns a view of the portion of this list between the specified indices.',
    arguments: [
      { name: 'fromIndex', type: 'int', description: 'Low endpoint (inclusive)' },
      { name: 'toIndex', type: 'int', description: 'High endpoint (exclusive)' },
    ],
    returns: { type: 'List<E>', description: 'A view of the specified range within this list' },
    examples: [{ code: 'Arrays.asList(1, 2, 3, 4, 5).subList(1, 4)', output: '[2, 3, 4]' }],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['get', 'toArray'],
    notes: ['Changes to the subList are reflected in the original list'],
  },
  {
    name: 'toArray',
    category: 'ArrayList Methods',
    syntax: 'list.toArray() | list.toArray(T[] array)',
    description: 'Returns an array containing all elements in this list in proper sequence.',
    arguments: [
      {
        name: 'array',
        type: 'T[]',
        description: 'Array to store elements (optional)',
        optional: true,
      },
    ],
    returns: { type: 'Object[] | T[]', description: 'An array containing all elements' },
    examples: [
      { code: 'Arrays.asList(1, 2, 3).toArray()', output: 'Object[]{1, 2, 3}' },
      { code: 'list.toArray(new String[0])', output: 'String[] array' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['Arrays.asList', 'stream'],
  },

  // ============================================================
  // String Methods
  // ============================================================
  {
    name: 'charAt',
    category: 'String Methods',
    syntax: 'string.charAt(index)',
    description: 'Returns the char value at the specified index.',
    arguments: [{ name: 'index', type: 'int', description: 'Index of the char value' }],
    returns: { type: 'char', description: 'The char value at the specified index' },
    examples: [
      { code: '"hello".charAt(1)', output: "'e'" },
      { code: '"Java".charAt(0)', output: "'J'" },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['substring', 'toCharArray', 'codePointAt'],
  },
  {
    name: 'substring',
    category: 'String Methods',
    syntax: 'string.substring(beginIndex) | string.substring(beginIndex, endIndex)',
    description: 'Returns a string that is a substring of this string.',
    arguments: [
      { name: 'beginIndex', type: 'int', description: 'Beginning index (inclusive)' },
      { name: 'endIndex', type: 'int', description: 'Ending index (exclusive)', optional: true },
    ],
    returns: { type: 'String', description: 'The specified substring' },
    examples: [
      { code: '"hamburger".substring(4, 8)', output: '"urge"' },
      { code: '"hello".substring(2)', output: '"llo"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['charAt', 'split', 'subSequence'],
  },
  {
    name: 'split',
    category: 'String Methods',
    syntax: 'string.split(regex) | string.split(regex, limit)',
    description: 'Splits this string around matches of the given regular expression.',
    arguments: [
      { name: 'regex', type: 'String', description: 'The delimiting regular expression' },
      { name: 'limit', type: 'int', description: 'Result threshold', optional: true },
    ],
    returns: { type: 'String[]', description: 'Array of strings split around the regex' },
    examples: [
      { code: '"a,b,c".split(",")', output: '["a", "b", "c"]' },
      { code: '"hello world".split(" ")', output: '["hello", "world"]' },
      {
        code: '"a.b.c".split("\\\\.")',
        output: '["a", "b", "c"]',
        explanation: 'Escape regex special characters',
      },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['join', 'substring', 'Pattern.split'],
  },
  {
    name: 'toLowerCase',
    category: 'String Methods',
    syntax: 'string.toLowerCase()',
    description: 'Converts all characters in this string to lowercase.',
    arguments: [],
    returns: { type: 'String', description: 'String converted to lowercase' },
    examples: [
      { code: '"HELLO".toLowerCase()', output: '"hello"' },
      { code: '"HeLLo WoRLd".toLowerCase()', output: '"hello world"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['toUpperCase', 'equalsIgnoreCase'],
  },
  {
    name: 'toUpperCase',
    category: 'String Methods',
    syntax: 'string.toUpperCase()',
    description: 'Converts all characters in this string to uppercase.',
    arguments: [],
    returns: { type: 'String', description: 'String converted to uppercase' },
    examples: [{ code: '"hello".toUpperCase()', output: '"HELLO"' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['toLowerCase', 'equalsIgnoreCase'],
  },
  {
    name: 'trim',
    category: 'String Methods',
    syntax: 'string.trim()',
    description: 'Returns a string with leading and trailing whitespace removed.',
    arguments: [],
    returns: { type: 'String', description: 'String with whitespace removed' },
    examples: [
      { code: '"  hello  ".trim()', output: '"hello"' },
      { code: '"\\t hello \\n".trim()', output: '"hello"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['strip', 'stripLeading', 'stripTrailing'],
    notes: ['strip() (Java 11+) handles Unicode whitespace better'],
  },
  {
    name: 'replace',
    category: 'String Methods',
    syntax: 'string.replace(oldChar, newChar) | string.replace(target, replacement)',
    description: 'Returns a string with all occurrences of a character or sequence replaced.',
    arguments: [
      {
        name: 'target',
        type: 'char | CharSequence',
        description: 'Character or sequence to be replaced',
      },
      {
        name: 'replacement',
        type: 'char | CharSequence',
        description: 'Replacement character or sequence',
      },
    ],
    returns: { type: 'String', description: 'String with replacements made' },
    examples: [
      { code: "\"hello\".replace('l', 'w')", output: '"hewwo"' },
      { code: '"hello world".replace("world", "Java")', output: '"hello Java"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['replaceAll', 'replaceFirst'],
  },
  {
    name: 'replaceAll',
    category: 'String Methods',
    syntax: 'string.replaceAll(regex, replacement)',
    description: 'Replaces each substring that matches the regex with the given replacement.',
    arguments: [
      { name: 'regex', type: 'String', description: 'Regular expression to match' },
      { name: 'replacement', type: 'String', description: 'Replacement string' },
    ],
    returns: { type: 'String', description: 'String with all matches replaced' },
    examples: [
      { code: '"a1b2c3".replaceAll("\\\\d", "X")', output: '"aXbXcX"' },
      { code: '"hello   world".replaceAll("\\\\s+", " ")', output: '"hello world"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['replace', 'replaceFirst'],
  },
  {
    name: 'startsWith',
    category: 'String Methods',
    syntax: 'string.startsWith(prefix)',
    description: 'Tests if this string starts with the specified prefix.',
    arguments: [{ name: 'prefix', type: 'String', description: 'The prefix to check' }],
    returns: { type: 'boolean', description: 'true if string starts with prefix' },
    examples: [
      { code: '"hello world".startsWith("hello")', output: 'true' },
      { code: '"hello world".startsWith("world")', output: 'false' },
    ],
    timeComplexity: 'O(m)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['endsWith', 'indexOf', 'contains'],
  },
  {
    name: 'endsWith',
    category: 'String Methods',
    syntax: 'string.endsWith(suffix)',
    description: 'Tests if this string ends with the specified suffix.',
    arguments: [{ name: 'suffix', type: 'String', description: 'The suffix to check' }],
    returns: { type: 'boolean', description: 'true if string ends with suffix' },
    examples: [
      { code: '"hello world".endsWith("world")', output: 'true' },
      { code: '"hello.txt".endsWith(".txt")', output: 'true' },
    ],
    timeComplexity: 'O(m)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['startsWith', 'contains'],
  },
  {
    name: 'contains',
    category: 'String Methods',
    syntax: 'string.contains(sequence)',
    description: 'Returns true if this string contains the specified sequence of char values.',
    arguments: [
      { name: 'sequence', type: 'CharSequence', description: 'The sequence to search for' },
    ],
    returns: { type: 'boolean', description: 'true if string contains sequence' },
    examples: [
      { code: '"hello world".contains("world")', output: 'true' },
      { code: '"hello".contains("xyz")', output: 'false' },
    ],
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['indexOf', 'startsWith', 'endsWith'],
  },
  {
    name: 'equals',
    category: 'String Methods',
    syntax: 'string.equals(anObject)',
    description: 'Compares this string to the specified object for equality.',
    arguments: [{ name: 'anObject', type: 'Object', description: 'Object to compare' }],
    returns: { type: 'boolean', description: 'true if strings are equal' },
    examples: [
      { code: '"hello".equals("hello")', output: 'true' },
      { code: '"Hello".equals("hello")', output: 'false' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['equalsIgnoreCase', 'compareTo', '=='],
    notes: ['Always use equals() instead of == for String comparison'],
  },
  {
    name: 'equalsIgnoreCase',
    category: 'String Methods',
    syntax: 'string.equalsIgnoreCase(anotherString)',
    description: 'Compares this string to another string, ignoring case considerations.',
    arguments: [{ name: 'anotherString', type: 'String', description: 'String to compare' }],
    returns: { type: 'boolean', description: 'true if strings are equal ignoring case' },
    examples: [
      { code: '"Hello".equalsIgnoreCase("hello")', output: 'true' },
      { code: '"JAVA".equalsIgnoreCase("java")', output: 'true' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['equals', 'compareToIgnoreCase'],
  },

  // ============================================================
  // Stream API
  // ============================================================
  {
    name: 'filter',
    category: 'Stream API',
    syntax: 'stream.filter(predicate)',
    description: 'Returns a stream consisting of elements that match the given predicate.',
    arguments: [
      {
        name: 'predicate',
        type: 'Predicate<T>',
        description: 'Predicate to apply to each element',
      },
    ],
    returns: { type: 'Stream<T>', description: 'A stream of matching elements' },
    examples: [
      { code: 'List.of(1, 2, 3, 4).stream().filter(n -> n > 2).toList()', output: '[3, 4]' },
      {
        code: 'names.stream().filter(s -> s.startsWith("A")).toList()',
        output: 'Names starting with A',
      },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1) lazy',
    relatedMethods: ['map', 'flatMap', 'takeWhile'],
    sinceVersion: 'Java 8',
  },
  {
    name: 'map',
    category: 'Stream API',
    syntax: 'stream.map(function)',
    description:
      'Returns a stream consisting of the results of applying the given function to the elements.',
    arguments: [
      {
        name: 'function',
        type: 'Function<T, R>',
        description: 'Function to apply to each element',
      },
    ],
    returns: { type: 'Stream<R>', description: 'A stream of transformed elements' },
    examples: [
      { code: 'List.of(1, 2, 3).stream().map(n -> n * 2).toList()', output: '[2, 4, 6]' },
      { code: 'words.stream().map(String::toUpperCase).toList()', output: 'Uppercase words' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1) lazy',
    relatedMethods: ['filter', 'flatMap', 'mapToInt'],
    sinceVersion: 'Java 8',
  },
  {
    name: 'flatMap',
    category: 'Stream API',
    syntax: 'stream.flatMap(function)',
    description:
      'Returns a stream consisting of the results of replacing each element with the contents of a mapped stream.',
    arguments: [
      {
        name: 'function',
        type: 'Function<T, Stream<R>>',
        description: 'Function producing a stream for each element',
      },
    ],
    returns: { type: 'Stream<R>', description: 'A flattened stream' },
    examples: [
      {
        code: 'List.of(List.of(1, 2), List.of(3, 4)).stream().flatMap(Collection::stream).toList()',
        output: '[1, 2, 3, 4]',
      },
      {
        code: 'words.stream().flatMap(s -> Arrays.stream(s.split(""))).toList()',
        output: 'Individual characters',
      },
    ],
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(1) lazy',
    relatedMethods: ['map', 'filter', 'concat'],
    sinceVersion: 'Java 8',
  },
  {
    name: 'reduce',
    category: 'Stream API',
    syntax: 'stream.reduce(identity, accumulator)',
    description: 'Performs a reduction on the elements using an associative accumulation function.',
    arguments: [
      { name: 'identity', type: 'T', description: 'Identity value for the accumulator' },
      {
        name: 'accumulator',
        type: 'BinaryOperator<T>',
        description: 'Associative accumulation function',
      },
    ],
    returns: { type: 'T | Optional<T>', description: 'Result of the reduction' },
    examples: [
      { code: 'List.of(1, 2, 3, 4).stream().reduce(0, Integer::sum)', output: '10' },
      { code: 'words.stream().reduce("", (a, b) -> a + b)', output: 'Concatenated string' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['collect', 'sum', 'count'],
    sinceVersion: 'Java 8',
  },
  {
    name: 'collect',
    category: 'Stream API',
    syntax: 'stream.collect(collector)',
    description: 'Performs a mutable reduction operation on the elements using a Collector.',
    arguments: [
      {
        name: 'collector',
        type: 'Collector<T, A, R>',
        description: 'Collector describing the reduction',
      },
    ],
    returns: { type: 'R', description: 'Result of the reduction' },
    examples: [
      { code: 'stream.collect(Collectors.toList())', output: 'List of elements' },
      { code: 'stream.collect(Collectors.joining(", "))', output: 'Joined string' },
      {
        code: 'stream.collect(Collectors.groupingBy(Person::getCity))',
        output: 'Map grouped by city',
      },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['reduce', 'toList', 'toArray'],
    sinceVersion: 'Java 8',
  },
  {
    name: 'sorted',
    category: 'Stream API',
    syntax: 'stream.sorted() | stream.sorted(comparator)',
    description:
      'Returns a stream with elements sorted according to natural order or the provided comparator.',
    arguments: [
      {
        name: 'comparator',
        type: 'Comparator<T>',
        description: 'Comparator for ordering',
        optional: true,
      },
    ],
    returns: { type: 'Stream<T>', description: 'A sorted stream' },
    examples: [
      { code: 'List.of(3, 1, 2).stream().sorted().toList()', output: '[1, 2, 3]' },
      {
        code: 'names.stream().sorted(Comparator.reverseOrder()).toList()',
        output: 'Reverse sorted names',
      },
    ],
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['distinct', 'limit', 'skip'],
    sinceVersion: 'Java 8',
  },
  {
    name: 'distinct',
    category: 'Stream API',
    syntax: 'stream.distinct()',
    description: 'Returns a stream consisting of the distinct elements according to equals().',
    arguments: [],
    returns: { type: 'Stream<T>', description: 'A stream with unique elements' },
    examples: [
      { code: 'List.of(1, 2, 2, 3, 3, 3).stream().distinct().toList()', output: '[1, 2, 3]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['sorted', 'filter'],
    sinceVersion: 'Java 8',
  },
  {
    name: 'findFirst',
    category: 'Stream API',
    syntax: 'stream.findFirst()',
    description:
      'Returns an Optional describing the first element of this stream, or empty if stream is empty.',
    arguments: [],
    returns: { type: 'Optional<T>', description: 'Optional containing first element or empty' },
    examples: [
      { code: 'List.of(1, 2, 3).stream().findFirst()', output: 'Optional[1]' },
      { code: 'Stream.empty().findFirst()', output: 'Optional.empty' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['findAny', 'filter', 'limit'],
    sinceVersion: 'Java 8',
  },
  {
    name: 'anyMatch',
    category: 'Stream API',
    syntax: 'stream.anyMatch(predicate)',
    description: 'Returns whether any elements of this stream match the provided predicate.',
    arguments: [{ name: 'predicate', type: 'Predicate<T>', description: 'Predicate to apply' }],
    returns: { type: 'boolean', description: 'true if any element matches' },
    examples: [
      { code: 'List.of(1, 2, 3).stream().anyMatch(n -> n > 2)', output: 'true' },
      { code: 'List.of(1, 2, 3).stream().anyMatch(n -> n > 5)', output: 'false' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['allMatch', 'noneMatch', 'filter'],
    sinceVersion: 'Java 8',
  },
  {
    name: 'allMatch',
    category: 'Stream API',
    syntax: 'stream.allMatch(predicate)',
    description: 'Returns whether all elements of this stream match the provided predicate.',
    arguments: [{ name: 'predicate', type: 'Predicate<T>', description: 'Predicate to apply' }],
    returns: { type: 'boolean', description: 'true if all elements match' },
    examples: [
      { code: 'List.of(2, 4, 6).stream().allMatch(n -> n % 2 == 0)', output: 'true' },
      { code: 'List.of(1, 2, 3).stream().allMatch(n -> n > 1)', output: 'false' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['anyMatch', 'noneMatch', 'filter'],
    sinceVersion: 'Java 8',
  },

  // ============================================================
  // HashMap Methods
  // ============================================================
  {
    name: 'put',
    category: 'HashMap Methods',
    syntax: 'map.put(key, value)',
    description: 'Associates the specified value with the specified key in this map.',
    arguments: [
      { name: 'key', type: 'K', description: 'Key with which the value is to be associated' },
      { name: 'value', type: 'V', description: 'Value to be associated with the key' },
    ],
    returns: { type: 'V', description: 'Previous value associated with key, or null' },
    examples: [
      {
        code: 'Map<String, Integer> map = new HashMap<>(); map.put("a", 1);',
        output: 'null (no previous value)',
      },
      { code: 'map.put("a", 2);', output: '1 (previous value)' },
    ],
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    relatedMethods: ['get', 'putIfAbsent', 'remove'],
  },
  {
    name: 'get',
    category: 'HashMap Methods',
    syntax: 'map.get(key)',
    description: 'Returns the value to which the specified key is mapped, or null if not present.',
    arguments: [{ name: 'key', type: 'Object', description: 'Key whose value is to be returned' }],
    returns: { type: 'V', description: 'Value mapped to key, or null' },
    examples: [
      { code: 'Map.of("a", 1, "b", 2).get("a")', output: '1' },
      { code: 'Map.of("a", 1).get("c")', output: 'null' },
    ],
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    relatedMethods: ['put', 'getOrDefault', 'containsKey'],
  },
  {
    name: 'getOrDefault',
    category: 'HashMap Methods',
    syntax: 'map.getOrDefault(key, defaultValue)',
    description: 'Returns the value mapped to key, or defaultValue if key is not present.',
    arguments: [
      { name: 'key', type: 'Object', description: 'Key whose value is to be returned' },
      { name: 'defaultValue', type: 'V', description: 'Default value to return' },
    ],
    returns: { type: 'V', description: 'Value mapped to key, or defaultValue' },
    examples: [
      { code: 'Map.of("a", 1).getOrDefault("a", 0)', output: '1' },
      { code: 'Map.of("a", 1).getOrDefault("b", 0)', output: '0' },
    ],
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    relatedMethods: ['get', 'putIfAbsent', 'computeIfAbsent'],
    sinceVersion: 'Java 8',
  },
  {
    name: 'containsKey',
    category: 'HashMap Methods',
    syntax: 'map.containsKey(key)',
    description: 'Returns true if this map contains a mapping for the specified key.',
    arguments: [{ name: 'key', type: 'Object', description: 'Key to check' }],
    returns: { type: 'boolean', description: 'true if key is present' },
    examples: [
      { code: 'Map.of("a", 1).containsKey("a")', output: 'true' },
      { code: 'Map.of("a", 1).containsKey("b")', output: 'false' },
    ],
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    relatedMethods: ['containsValue', 'get', 'keySet'],
  },
  {
    name: 'keySet',
    category: 'HashMap Methods',
    syntax: 'map.keySet()',
    description: 'Returns a Set view of the keys contained in this map.',
    arguments: [],
    returns: { type: 'Set<K>', description: 'A set view of the keys' },
    examples: [{ code: 'Map.of("a", 1, "b", 2).keySet()', output: 'Set of ["a", "b"]' }],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['values', 'entrySet'],
  },
  {
    name: 'values',
    category: 'HashMap Methods',
    syntax: 'map.values()',
    description: 'Returns a Collection view of the values contained in this map.',
    arguments: [],
    returns: { type: 'Collection<V>', description: 'A collection view of the values' },
    examples: [{ code: 'Map.of("a", 1, "b", 2).values()', output: 'Collection of [1, 2]' }],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['keySet', 'entrySet'],
  },
  {
    name: 'entrySet',
    category: 'HashMap Methods',
    syntax: 'map.entrySet()',
    description: 'Returns a Set view of the mappings contained in this map.',
    arguments: [],
    returns: { type: 'Set<Map.Entry<K, V>>', description: 'A set view of the mappings' },
    examples: [
      {
        code: 'for (Map.Entry<String, Integer> e : map.entrySet()) { ... }',
        output: 'Iterate over entries',
      },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['keySet', 'values', 'forEach'],
  },
  {
    name: 'putIfAbsent',
    category: 'HashMap Methods',
    syntax: 'map.putIfAbsent(key, value)',
    description:
      'If the key is not already associated with a value, associates it with the given value.',
    arguments: [
      { name: 'key', type: 'K', description: 'Key to check' },
      { name: 'value', type: 'V', description: 'Value to associate' },
    ],
    returns: { type: 'V', description: 'Previous value, or null if newly inserted' },
    examples: [
      { code: 'map.putIfAbsent("a", 1)', output: 'null (inserted)' },
      { code: 'map.putIfAbsent("a", 2)', output: '1 (not inserted)' },
    ],
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    relatedMethods: ['put', 'getOrDefault', 'computeIfAbsent'],
    sinceVersion: 'Java 8',
  },

  // ============================================================
  // Arrays Utility
  // ============================================================
  {
    name: 'Arrays.sort',
    category: 'Arrays Utility',
    syntax: 'Arrays.sort(array) | Arrays.sort(array, comparator)',
    description: 'Sorts the specified array into ascending order.',
    arguments: [
      { name: 'array', type: 'T[]', description: 'Array to be sorted' },
      {
        name: 'comparator',
        type: 'Comparator<T>',
        description: 'Comparator to determine order',
        optional: true,
      },
    ],
    returns: { type: 'void', description: 'Sorts in place' },
    examples: [
      { code: 'int[] arr = {3, 1, 2}; Arrays.sort(arr);', output: '[1, 2, 3]' },
      { code: 'Arrays.sort(arr, Comparator.reverseOrder());', output: 'Descending order' },
    ],
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['Arrays.parallelSort', 'Collections.sort'],
  },
  {
    name: 'Arrays.binarySearch',
    category: 'Arrays Utility',
    syntax: 'Arrays.binarySearch(array, key)',
    description: 'Searches the specified sorted array for the specified value using binary search.',
    arguments: [
      { name: 'array', type: 'T[]', description: 'Sorted array to search' },
      { name: 'key', type: 'T', description: 'Value to search for' },
    ],
    returns: {
      type: 'int',
      description: 'Index of key if found, otherwise (-(insertion point) - 1)',
    },
    examples: [
      { code: 'Arrays.binarySearch(new int[]{1, 2, 3, 4}, 3)', output: '2' },
      {
        code: 'Arrays.binarySearch(new int[]{1, 2, 4}, 3)',
        output: '-3 (insertion point would be 2)',
      },
    ],
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Arrays.sort', 'Collections.binarySearch'],
    notes: ['Array must be sorted before calling binarySearch'],
  },
  {
    name: 'Arrays.asList',
    category: 'Arrays Utility',
    syntax: 'Arrays.asList(elements)',
    description: 'Returns a fixed-size list backed by the specified array.',
    arguments: [{ name: 'elements', type: 'T...', description: 'Elements to create list from' }],
    returns: { type: 'List<T>', description: 'A fixed-size list' },
    examples: [
      { code: 'Arrays.asList(1, 2, 3)', output: '[1, 2, 3]' },
      { code: 'Arrays.asList("a", "b", "c")', output: '["a", "b", "c"]' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['List.of', 'new ArrayList<>()'],
    notes: ['Returned list has fixed size - cannot add/remove elements'],
  },
  {
    name: 'Arrays.fill',
    category: 'Arrays Utility',
    syntax: 'Arrays.fill(array, value)',
    description: 'Assigns the specified value to each element of the specified array.',
    arguments: [
      { name: 'array', type: 'T[]', description: 'Array to be filled' },
      { name: 'value', type: 'T', description: 'Value to fill with' },
    ],
    returns: { type: 'void', description: 'Modifies array in place' },
    examples: [{ code: 'int[] arr = new int[3]; Arrays.fill(arr, 5);', output: '[5, 5, 5]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Arrays.setAll', 'Collections.fill'],
  },
  {
    name: 'Arrays.copyOf',
    category: 'Arrays Utility',
    syntax: 'Arrays.copyOf(original, newLength)',
    description: 'Copies the specified array, truncating or padding with zeros/nulls if necessary.',
    arguments: [
      { name: 'original', type: 'T[]', description: 'Array to be copied' },
      { name: 'newLength', type: 'int', description: 'Length of the copy' },
    ],
    returns: { type: 'T[]', description: 'A copy of the original array' },
    examples: [
      { code: 'Arrays.copyOf(new int[]{1, 2, 3}, 5)', output: '[1, 2, 3, 0, 0]' },
      { code: 'Arrays.copyOf(new int[]{1, 2, 3}, 2)', output: '[1, 2]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['Arrays.copyOfRange', 'System.arraycopy', 'clone'],
  },

  // ============================================================
  // Optional Methods
  // ============================================================
  {
    name: 'Optional.of',
    category: 'Optional Methods',
    syntax: 'Optional.of(value)',
    description: 'Returns an Optional with the specified non-null value.',
    arguments: [{ name: 'value', type: 'T', description: 'Non-null value to wrap' }],
    returns: { type: 'Optional<T>', description: 'An Optional with the value' },
    examples: [
      { code: 'Optional.of("hello")', output: 'Optional[hello]' },
      { code: 'Optional.of(null)', output: 'Throws NullPointerException' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Optional.ofNullable', 'Optional.empty'],
    sinceVersion: 'Java 8',
  },
  {
    name: 'Optional.ofNullable',
    category: 'Optional Methods',
    syntax: 'Optional.ofNullable(value)',
    description:
      'Returns an Optional describing the value if non-null, otherwise returns empty Optional.',
    arguments: [{ name: 'value', type: 'T', description: 'Value to wrap (can be null)' }],
    returns: { type: 'Optional<T>', description: 'An Optional with value or empty' },
    examples: [
      { code: 'Optional.ofNullable("hello")', output: 'Optional[hello]' },
      { code: 'Optional.ofNullable(null)', output: 'Optional.empty' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['Optional.of', 'Optional.empty'],
    sinceVersion: 'Java 8',
  },
  {
    name: 'orElse',
    category: 'Optional Methods',
    syntax: 'optional.orElse(other)',
    description: 'Returns the value if present, otherwise returns the specified default value.',
    arguments: [{ name: 'other', type: 'T', description: 'Default value to return' }],
    returns: { type: 'T', description: 'The value if present, otherwise default' },
    examples: [
      { code: 'Optional.of("hello").orElse("default")', output: '"hello"' },
      { code: 'Optional.empty().orElse("default")', output: '"default"' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['orElseGet', 'orElseThrow', 'ifPresent'],
    sinceVersion: 'Java 8',
  },
  {
    name: 'orElseGet',
    category: 'Optional Methods',
    syntax: 'optional.orElseGet(supplier)',
    description:
      'Returns the value if present, otherwise invokes the supplier and returns its result.',
    arguments: [
      {
        name: 'supplier',
        type: 'Supplier<T>',
        description: 'Supplier to invoke if value not present',
      },
    ],
    returns: { type: 'T', description: 'The value if present, otherwise supplier result' },
    examples: [
      {
        code: 'Optional.empty().orElseGet(() -> computeDefault())',
        output: 'Result of computeDefault()',
      },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['orElse', 'orElseThrow'],
    sinceVersion: 'Java 8',
    notes: ['Supplier is only called if value is not present (lazy evaluation)'],
  },
  {
    name: 'ifPresent',
    category: 'Optional Methods',
    syntax: 'optional.ifPresent(consumer)',
    description: 'If a value is present, performs the given action with the value.',
    arguments: [
      { name: 'consumer', type: 'Consumer<T>', description: 'Action to perform if value present' },
    ],
    returns: { type: 'void', description: 'No return value' },
    examples: [
      { code: 'Optional.of("hello").ifPresent(System.out::println)', output: 'Prints "hello"' },
      { code: 'Optional.empty().ifPresent(System.out::println)', output: 'Does nothing' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['ifPresentOrElse', 'isPresent', 'map'],
    sinceVersion: 'Java 8',
  },
];
