import type { Method } from '../types';

export const pythonMethods: Method[] = [
  // ============================================================
  // List Methods
  // ============================================================
  {
    name: 'append',
    category: 'List Methods',
    syntax: 'list.append(element)',
    description: 'Adds an element to the end of the list. Modifies the list in place.',
    arguments: [
      { name: 'element', type: 'any', description: 'The element to add to the list' },
    ],
    returns: { type: 'None', description: 'Returns None, modifies list in place' },
    examples: [
      { code: 'lst = [1, 2, 3]; lst.append(4); lst', output: '[1, 2, 3, 4]' },
      { code: 'lst = []; lst.append("hello"); lst', output: '["hello"]' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['extend', 'insert', '+= operator'],
  },
  {
    name: 'extend',
    category: 'List Methods',
    syntax: 'list.extend(iterable)',
    description: 'Extends the list by appending all elements from the iterable.',
    arguments: [
      { name: 'iterable', type: 'iterable', description: 'An iterable whose elements will be added' },
    ],
    returns: { type: 'None', description: 'Returns None, modifies list in place' },
    examples: [
      { code: 'lst = [1, 2]; lst.extend([3, 4]); lst', output: '[1, 2, 3, 4]' },
      { code: 'lst = [1]; lst.extend("abc"); lst', output: '[1, "a", "b", "c"]' },
    ],
    timeComplexity: 'O(k)',
    spaceComplexity: 'O(k)',
    relatedMethods: ['append', '+= operator', 'list concatenation'],
    notes: ['More efficient than += for adding multiple elements'],
  },
  {
    name: 'insert',
    category: 'List Methods',
    syntax: 'list.insert(index, element)',
    description: 'Inserts an element at a given position. All elements after it are shifted right.',
    arguments: [
      { name: 'index', type: 'int', description: 'Index where the element should be inserted' },
      { name: 'element', type: 'any', description: 'The element to insert' },
    ],
    returns: { type: 'None', description: 'Returns None, modifies list in place' },
    examples: [
      { code: 'lst = [1, 2, 3]; lst.insert(1, "x"); lst', output: '[1, "x", 2, 3]' },
      { code: 'lst = [1, 2]; lst.insert(0, 0); lst', output: '[0, 1, 2]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['append', 'extend'],
  },
  {
    name: 'remove',
    category: 'List Methods',
    syntax: 'list.remove(element)',
    description: 'Removes the first occurrence of a value. Raises ValueError if not present.',
    arguments: [
      { name: 'element', type: 'any', description: 'The element to remove' },
    ],
    returns: { type: 'None', description: 'Returns None, modifies list in place' },
    examples: [
      { code: 'lst = [1, 2, 3, 2]; lst.remove(2); lst', output: '[1, 3, 2]' },
      { code: 'lst = ["a", "b", "c"]; lst.remove("b"); lst', output: '["a", "c"]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['pop', 'del', 'clear'],
    notes: ['Raises ValueError if element not found'],
  },
  {
    name: 'pop',
    category: 'List Methods',
    syntax: 'list.pop(index=-1)',
    description: 'Removes and returns the element at the given position. Defaults to the last element.',
    arguments: [
      { name: 'index', type: 'int', description: 'Index of element to remove', optional: true, defaultValue: '-1' },
    ],
    returns: { type: 'any', description: 'The removed element' },
    examples: [
      { code: 'lst = [1, 2, 3]; lst.pop()', output: '3' },
      { code: 'lst = [1, 2, 3]; lst.pop(0)', output: '1' },
      { code: 'lst = [1, 2, 3]; lst.pop(1); lst', output: '[1, 3]' },
    ],
    timeComplexity: 'O(1) for last, O(n) for arbitrary',
    spaceComplexity: 'O(1)',
    relatedMethods: ['remove', 'del', 'clear'],
    notes: ['Raises IndexError if list is empty or index out of range'],
  },
  {
    name: 'index',
    category: 'List Methods',
    syntax: 'list.index(element, start=0, end=len(list))',
    description: 'Returns the index of the first occurrence of the specified element.',
    arguments: [
      { name: 'element', type: 'any', description: 'The element to search for' },
      { name: 'start', type: 'int', description: 'Start index for search', optional: true, defaultValue: '0' },
      { name: 'end', type: 'int', description: 'End index for search', optional: true, defaultValue: 'len(list)' },
    ],
    returns: { type: 'int', description: 'Index of the first occurrence' },
    examples: [
      { code: '[1, 2, 3, 2].index(2)', output: '1' },
      { code: '[1, 2, 3, 2].index(2, 2)', output: '3' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['find (strings)', 'count', 'in operator'],
    notes: ['Raises ValueError if element not found'],
  },
  {
    name: 'count',
    category: 'List Methods',
    syntax: 'list.count(element)',
    description: 'Returns the number of times the specified element appears in the list.',
    arguments: [
      { name: 'element', type: 'any', description: 'The element to count' },
    ],
    returns: { type: 'int', description: 'Number of occurrences' },
    examples: [
      { code: '[1, 2, 2, 3, 2].count(2)', output: '3' },
      { code: '["a", "b", "a"].count("a")', output: '2' },
      { code: '[1, 2, 3].count(4)', output: '0' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['index', 'len'],
  },
  {
    name: 'sort',
    category: 'List Methods',
    syntax: 'list.sort(key=None, reverse=False)',
    description: 'Sorts the list in place. Can use a custom key function and reverse order.',
    arguments: [
      { name: 'key', type: 'function', description: 'Function to extract comparison key', optional: true },
      { name: 'reverse', type: 'bool', description: 'If True, sort in descending order', optional: true, defaultValue: 'False' },
    ],
    returns: { type: 'None', description: 'Returns None, modifies list in place' },
    examples: [
      { code: 'lst = [3, 1, 2]; lst.sort(); lst', output: '[1, 2, 3]' },
      { code: 'lst = [3, 1, 2]; lst.sort(reverse=True); lst', output: '[3, 2, 1]' },
      { code: 'lst = ["banana", "apple", "cherry"]; lst.sort(key=len); lst', output: '["apple", "banana", "cherry"]' },
    ],
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['sorted', 'reverse'],
    notes: ['Use sorted() for a new sorted list without modifying original'],
  },
  {
    name: 'reverse',
    category: 'List Methods',
    syntax: 'list.reverse()',
    description: 'Reverses the elements of the list in place.',
    arguments: [],
    returns: { type: 'None', description: 'Returns None, modifies list in place' },
    examples: [
      { code: 'lst = [1, 2, 3]; lst.reverse(); lst', output: '[3, 2, 1]' },
      { code: 'lst = ["a", "b", "c"]; lst.reverse(); lst', output: '["c", "b", "a"]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['reversed', 'sort', 'slice [::-1]'],
    notes: ['Use reversed() or [::-1] for a new reversed list'],
  },
  {
    name: 'copy',
    category: 'List Methods',
    syntax: 'list.copy()',
    description: 'Returns a shallow copy of the list.',
    arguments: [],
    returns: { type: 'list', description: 'A shallow copy of the list' },
    examples: [
      { code: 'lst = [1, 2, 3]; lst2 = lst.copy(); lst2', output: '[1, 2, 3]' },
      { code: 'lst = [1, 2]; lst2 = lst.copy(); lst2.append(3); lst', output: '[1, 2]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['deepcopy', 'list()', 'slice [:]'],
    notes: ['Only creates shallow copy - nested objects are still referenced'],
  },
  {
    name: 'clear',
    category: 'List Methods',
    syntax: 'list.clear()',
    description: 'Removes all elements from the list.',
    arguments: [],
    returns: { type: 'None', description: 'Returns None, modifies list in place' },
    examples: [
      { code: 'lst = [1, 2, 3]; lst.clear(); lst', output: '[]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['del', 'pop', 'remove'],
  },

  // ============================================================
  // String Methods
  // ============================================================
  {
    name: 'split',
    category: 'String Methods',
    syntax: 'string.split(sep=None, maxsplit=-1)',
    description: 'Splits the string at the specified separator and returns a list of substrings.',
    arguments: [
      { name: 'sep', type: 'str', description: 'The separator to split on', optional: true, defaultValue: 'whitespace' },
      { name: 'maxsplit', type: 'int', description: 'Maximum number of splits', optional: true, defaultValue: '-1 (no limit)' },
    ],
    returns: { type: 'list[str]', description: 'A list of substrings' },
    examples: [
      { code: '"hello world".split()', output: '["hello", "world"]' },
      { code: '"a,b,c".split(",")', output: '["a", "b", "c"]' },
      { code: '"a,b,c,d".split(",", 2)', output: '["a", "b", "c,d"]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['join', 'rsplit', 'splitlines', 'partition'],
  },
  {
    name: 'join',
    category: 'String Methods',
    syntax: 'separator.join(iterable)',
    description: 'Joins elements of an iterable with the string as separator.',
    arguments: [
      { name: 'iterable', type: 'iterable', description: 'Iterable of strings to join' },
    ],
    returns: { type: 'str', description: 'A single string with elements joined' },
    examples: [
      { code: '",".join(["a", "b", "c"])', output: '"a,b,c"' },
      { code: '" ".join(["hello", "world"])', output: '"hello world"' },
      { code: '"".join(["a", "b", "c"])', output: '"abc"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['split', '+ operator'],
  },
  {
    name: 'strip',
    category: 'String Methods',
    syntax: 'string.strip(chars=None)',
    description: 'Returns a copy of the string with leading and trailing characters removed.',
    arguments: [
      { name: 'chars', type: 'str', description: 'Characters to remove', optional: true, defaultValue: 'whitespace' },
    ],
    returns: { type: 'str', description: 'String with specified characters removed from both ends' },
    examples: [
      { code: '"  hello  ".strip()', output: '"hello"' },
      { code: '"xxxhelloxxx".strip("x")', output: '"hello"' },
      { code: '"\\n\\thello\\n".strip()', output: '"hello"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['lstrip', 'rstrip', 'replace'],
  },
  {
    name: 'replace',
    category: 'String Methods',
    syntax: 'string.replace(old, new, count=-1)',
    description: 'Returns a copy with all occurrences of substring old replaced by new.',
    arguments: [
      { name: 'old', type: 'str', description: 'Substring to be replaced' },
      { name: 'new', type: 'str', description: 'Replacement substring' },
      { name: 'count', type: 'int', description: 'Maximum replacements', optional: true, defaultValue: '-1 (all)' },
    ],
    returns: { type: 'str', description: 'String with replacements made' },
    examples: [
      { code: '"hello world".replace("world", "there")', output: '"hello there"' },
      { code: '"aabbaa".replace("a", "x")', output: '"xxbbxx"' },
      { code: '"aabbaa".replace("a", "x", 2)', output: '"xxbbaa"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['translate', 're.sub', 'strip'],
  },
  {
    name: 'find',
    category: 'String Methods',
    syntax: 'string.find(sub, start=0, end=len(string))',
    description: 'Returns the lowest index where substring is found, or -1 if not found.',
    arguments: [
      { name: 'sub', type: 'str', description: 'Substring to search for' },
      { name: 'start', type: 'int', description: 'Start index', optional: true, defaultValue: '0' },
      { name: 'end', type: 'int', description: 'End index', optional: true, defaultValue: 'len(string)' },
    ],
    returns: { type: 'int', description: 'Index of substring, or -1 if not found' },
    examples: [
      { code: '"hello world".find("world")', output: '6' },
      { code: '"hello world".find("x")', output: '-1' },
      { code: '"hello hello".find("hello", 1)', output: '6' },
    ],
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['index', 'rfind', 'in operator'],
    notes: ['Use index() if you want ValueError instead of -1'],
  },
  {
    name: 'startswith',
    category: 'String Methods',
    syntax: 'string.startswith(prefix, start=0, end=len(string))',
    description: 'Returns True if the string starts with the specified prefix.',
    arguments: [
      { name: 'prefix', type: 'str | tuple', description: 'Prefix(es) to check' },
      { name: 'start', type: 'int', description: 'Start index', optional: true, defaultValue: '0' },
      { name: 'end', type: 'int', description: 'End index', optional: true, defaultValue: 'len(string)' },
    ],
    returns: { type: 'bool', description: 'True if string starts with prefix' },
    examples: [
      { code: '"hello world".startswith("hello")', output: 'True' },
      { code: '"hello world".startswith(("hi", "hello"))', output: 'True' },
      { code: '"hello world".startswith("world", 6)', output: 'True' },
    ],
    timeComplexity: 'O(k)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['endswith', 'find'],
  },
  {
    name: 'endswith',
    category: 'String Methods',
    syntax: 'string.endswith(suffix, start=0, end=len(string))',
    description: 'Returns True if the string ends with the specified suffix.',
    arguments: [
      { name: 'suffix', type: 'str | tuple', description: 'Suffix(es) to check' },
      { name: 'start', type: 'int', description: 'Start index', optional: true, defaultValue: '0' },
      { name: 'end', type: 'int', description: 'End index', optional: true, defaultValue: 'len(string)' },
    ],
    returns: { type: 'bool', description: 'True if string ends with suffix' },
    examples: [
      { code: '"hello world".endswith("world")', output: 'True' },
      { code: '"hello.txt".endswith((".txt", ".py"))', output: 'True' },
    ],
    timeComplexity: 'O(k)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['startswith', 'find'],
  },
  {
    name: 'upper',
    category: 'String Methods',
    syntax: 'string.upper()',
    description: 'Returns a copy of the string with all characters converted to uppercase.',
    arguments: [],
    returns: { type: 'str', description: 'Uppercase version of string' },
    examples: [
      { code: '"hello".upper()', output: '"HELLO"' },
      { code: '"Hello World".upper()', output: '"HELLO WORLD"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['lower', 'capitalize', 'title', 'swapcase'],
  },
  {
    name: 'lower',
    category: 'String Methods',
    syntax: 'string.lower()',
    description: 'Returns a copy of the string with all characters converted to lowercase.',
    arguments: [],
    returns: { type: 'str', description: 'Lowercase version of string' },
    examples: [
      { code: '"HELLO".lower()', output: '"hello"' },
      { code: '"Hello World".lower()', output: '"hello world"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['upper', 'capitalize', 'title', 'casefold'],
  },
  {
    name: 'isdigit',
    category: 'String Methods',
    syntax: 'string.isdigit()',
    description: 'Returns True if all characters in the string are digits.',
    arguments: [],
    returns: { type: 'bool', description: 'True if all characters are digits' },
    examples: [
      { code: '"12345".isdigit()', output: 'True' },
      { code: '"12.34".isdigit()', output: 'False' },
      { code: '"".isdigit()', output: 'False' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['isnumeric', 'isdecimal', 'isalpha', 'isalnum'],
  },
  {
    name: 'isalpha',
    category: 'String Methods',
    syntax: 'string.isalpha()',
    description: 'Returns True if all characters in the string are alphabetic.',
    arguments: [],
    returns: { type: 'bool', description: 'True if all characters are alphabetic' },
    examples: [
      { code: '"hello".isalpha()', output: 'True' },
      { code: '"hello123".isalpha()', output: 'False' },
      { code: '"".isalpha()', output: 'False' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['isdigit', 'isalnum', 'isspace'],
  },
  {
    name: 'format',
    category: 'String Methods',
    syntax: 'string.format(*args, **kwargs)',
    description: 'Performs string formatting with positional and keyword arguments.',
    arguments: [
      { name: 'args', type: 'any', description: 'Positional arguments for formatting' },
      { name: 'kwargs', type: 'any', description: 'Keyword arguments for formatting' },
    ],
    returns: { type: 'str', description: 'Formatted string' },
    examples: [
      { code: '"{} {}".format("hello", "world")', output: '"hello world"' },
      { code: '"{0} {1} {0}".format("a", "b")', output: '"a b a"' },
      { code: '"{name} is {age}".format(name="Alice", age=30)', output: '"Alice is 30"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['f-strings', '% operator'],
    notes: ['f-strings (f"...") are preferred in Python 3.6+'],
  },
  {
    name: 'zfill',
    category: 'String Methods',
    syntax: 'string.zfill(width)',
    description: 'Pads the string with zeros on the left to fill the specified width.',
    arguments: [
      { name: 'width', type: 'int', description: 'Total width of resulting string' },
    ],
    returns: { type: 'str', description: 'Zero-padded string' },
    examples: [
      { code: '"42".zfill(5)', output: '"00042"' },
      { code: '"-42".zfill(5)', output: '"-0042"' },
      { code: '"hello".zfill(3)', output: '"hello"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['ljust', 'rjust', 'center'],
  },

  // ============================================================
  // Dict Methods
  // ============================================================
  {
    name: 'get',
    category: 'Dict Methods',
    syntax: 'dict.get(key, default=None)',
    description: 'Returns the value for key if key is in the dictionary, else default.',
    arguments: [
      { name: 'key', type: 'any', description: 'Key to look up' },
      { name: 'default', type: 'any', description: 'Value to return if key not found', optional: true, defaultValue: 'None' },
    ],
    returns: { type: 'any', description: 'Value associated with key, or default' },
    examples: [
      { code: '{"a": 1, "b": 2}.get("a")', output: '1' },
      { code: '{"a": 1}.get("b", 0)', output: '0' },
      { code: '{"a": 1}.get("b")', output: 'None' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['setdefault', '__getitem__', 'pop'],
    notes: ['Safer than dict[key] as it does not raise KeyError'],
  },
  {
    name: 'keys',
    category: 'Dict Methods',
    syntax: 'dict.keys()',
    description: 'Returns a view object displaying all keys in the dictionary.',
    arguments: [],
    returns: { type: 'dict_keys', description: 'A view object of all keys' },
    examples: [
      { code: '{"a": 1, "b": 2}.keys()', output: 'dict_keys(["a", "b"])' },
      { code: 'list({"a": 1, "b": 2}.keys())', output: '["a", "b"]' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['values', 'items'],
  },
  {
    name: 'values',
    category: 'Dict Methods',
    syntax: 'dict.values()',
    description: 'Returns a view object displaying all values in the dictionary.',
    arguments: [],
    returns: { type: 'dict_values', description: 'A view object of all values' },
    examples: [
      { code: '{"a": 1, "b": 2}.values()', output: 'dict_values([1, 2])' },
      { code: 'list({"a": 1, "b": 2}.values())', output: '[1, 2]' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['keys', 'items'],
  },
  {
    name: 'items',
    category: 'Dict Methods',
    syntax: 'dict.items()',
    description: 'Returns a view object displaying all key-value pairs as tuples.',
    arguments: [],
    returns: { type: 'dict_items', description: 'A view object of (key, value) tuples' },
    examples: [
      { code: '{"a": 1, "b": 2}.items()', output: 'dict_items([("a", 1), ("b", 2)])' },
      { code: 'for k, v in {"a": 1}.items(): print(k, v)', output: 'a 1' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['keys', 'values'],
  },
  {
    name: 'update',
    category: 'Dict Methods',
    syntax: 'dict.update(other)',
    description: 'Updates the dictionary with key-value pairs from another dictionary or iterable.',
    arguments: [
      { name: 'other', type: 'dict | iterable', description: 'Dictionary or iterable of key-value pairs' },
    ],
    returns: { type: 'None', description: 'Returns None, modifies dict in place' },
    examples: [
      { code: 'd = {"a": 1}; d.update({"b": 2}); d', output: '{"a": 1, "b": 2}' },
      { code: 'd = {"a": 1}; d.update(a=10, c=3); d', output: '{"a": 10, "c": 3}' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['setdefault', '|= operator'],
    sinceVersion: 'Python 2.0',
  },
  {
    name: 'pop',
    category: 'Dict Methods',
    syntax: 'dict.pop(key, default)',
    description: 'Removes and returns the value for key. If key is not found, returns default or raises KeyError.',
    arguments: [
      { name: 'key', type: 'any', description: 'Key to remove' },
      { name: 'default', type: 'any', description: 'Value to return if key not found', optional: true },
    ],
    returns: { type: 'any', description: 'The removed value' },
    examples: [
      { code: 'd = {"a": 1, "b": 2}; d.pop("a")', output: '1' },
      { code: 'd = {"a": 1}; d.pop("b", 0)', output: '0' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['get', 'del', 'popitem'],
    notes: ['Raises KeyError if key not found and no default provided'],
  },
  {
    name: 'setdefault',
    category: 'Dict Methods',
    syntax: 'dict.setdefault(key, default=None)',
    description: 'Returns value for key if it exists, otherwise inserts key with default value and returns default.',
    arguments: [
      { name: 'key', type: 'any', description: 'Key to look up or insert' },
      { name: 'default', type: 'any', description: 'Value to insert if key not found', optional: true, defaultValue: 'None' },
    ],
    returns: { type: 'any', description: 'Value associated with key' },
    examples: [
      { code: 'd = {"a": 1}; d.setdefault("a", 10)', output: '1' },
      { code: 'd = {"a": 1}; d.setdefault("b", 2); d', output: '{"a": 1, "b": 2}' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['get', 'update', 'defaultdict'],
    notes: ['Useful for building dictionaries with default values'],
  },

  // ============================================================
  // Built-in Functions
  // ============================================================
  {
    name: 'len',
    category: 'Built-in Functions',
    syntax: 'len(object)',
    description: 'Returns the number of items in an object (sequence or collection).',
    arguments: [
      { name: 'object', type: 'sequence | collection', description: 'Object to measure' },
    ],
    returns: { type: 'int', description: 'Number of items' },
    examples: [
      { code: 'len([1, 2, 3])', output: '3' },
      { code: 'len("hello")', output: '5' },
      { code: 'len({"a": 1, "b": 2})', output: '2' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['count', 'sizeof'],
  },
  {
    name: 'range',
    category: 'Built-in Functions',
    syntax: 'range(start, stop, step)',
    description: 'Returns an immutable sequence of numbers from start to stop with step increment.',
    arguments: [
      { name: 'start', type: 'int', description: 'Start value (inclusive)', optional: true, defaultValue: '0' },
      { name: 'stop', type: 'int', description: 'Stop value (exclusive)' },
      { name: 'step', type: 'int', description: 'Step increment', optional: true, defaultValue: '1' },
    ],
    returns: { type: 'range', description: 'A range object' },
    examples: [
      { code: 'list(range(5))', output: '[0, 1, 2, 3, 4]' },
      { code: 'list(range(2, 5))', output: '[2, 3, 4]' },
      { code: 'list(range(0, 10, 2))', output: '[0, 2, 4, 6, 8]' },
      { code: 'list(range(5, 0, -1))', output: '[5, 4, 3, 2, 1]' },
    ],
    timeComplexity: 'O(1) to create, O(n) to iterate',
    spaceComplexity: 'O(1)',
    relatedMethods: ['enumerate', 'zip'],
  },
  {
    name: 'enumerate',
    category: 'Built-in Functions',
    syntax: 'enumerate(iterable, start=0)',
    description: 'Returns an enumerate object yielding pairs of (index, value).',
    arguments: [
      { name: 'iterable', type: 'iterable', description: 'An iterable object' },
      { name: 'start', type: 'int', description: 'Starting index', optional: true, defaultValue: '0' },
    ],
    returns: { type: 'enumerate', description: 'An enumerate object' },
    examples: [
      { code: 'list(enumerate(["a", "b", "c"]))', output: '[(0, "a"), (1, "b"), (2, "c")]' },
      { code: 'list(enumerate(["a", "b"], start=1))', output: '[(1, "a"), (2, "b")]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['zip', 'range', 'iter'],
  },
  {
    name: 'zip',
    category: 'Built-in Functions',
    syntax: 'zip(*iterables)',
    description: 'Returns an iterator of tuples, where the i-th tuple contains the i-th element from each input iterable.',
    arguments: [
      { name: 'iterables', type: 'iterable', description: 'Two or more iterables' },
    ],
    returns: { type: 'zip', description: 'A zip iterator' },
    examples: [
      { code: 'list(zip([1, 2], ["a", "b"]))', output: '[(1, "a"), (2, "b")]' },
      { code: 'list(zip([1, 2, 3], ["a", "b"]))', output: '[(1, "a"), (2, "b")]', explanation: 'Stops at shortest iterable' },
      { code: 'dict(zip(["a", "b"], [1, 2]))', output: '{"a": 1, "b": 2}' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['enumerate', 'itertools.zip_longest'],
    notes: ['Use itertools.zip_longest to pad shorter iterables'],
  },
  {
    name: 'map',
    category: 'Built-in Functions',
    syntax: 'map(function, iterable, ...)',
    description: 'Returns an iterator that applies function to every item of iterable.',
    arguments: [
      { name: 'function', type: 'callable', description: 'Function to apply' },
      { name: 'iterable', type: 'iterable', description: 'One or more iterables' },
    ],
    returns: { type: 'map', description: 'A map iterator' },
    examples: [
      { code: 'list(map(str.upper, ["a", "b", "c"]))', output: '["A", "B", "C"]' },
      { code: 'list(map(lambda x: x * 2, [1, 2, 3]))', output: '[2, 4, 6]' },
      { code: 'list(map(lambda x, y: x + y, [1, 2], [10, 20]))', output: '[11, 22]' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['filter', 'reduce', 'list comprehension'],
    notes: ['List comprehensions are often more Pythonic'],
  },
  {
    name: 'filter',
    category: 'Built-in Functions',
    syntax: 'filter(function, iterable)',
    description: 'Returns an iterator yielding items for which function returns True.',
    arguments: [
      { name: 'function', type: 'callable | None', description: 'Function to test each element' },
      { name: 'iterable', type: 'iterable', description: 'An iterable to filter' },
    ],
    returns: { type: 'filter', description: 'A filter iterator' },
    examples: [
      { code: 'list(filter(lambda x: x > 2, [1, 2, 3, 4]))', output: '[3, 4]' },
      { code: 'list(filter(str.isalpha, ["a", "1", "b"]))', output: '["a", "b"]' },
      { code: 'list(filter(None, [0, 1, "", "a"]))', output: '[1, "a"]', explanation: 'None removes falsy values' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['map', 'reduce', 'list comprehension'],
  },
  {
    name: 'sorted',
    category: 'Built-in Functions',
    syntax: 'sorted(iterable, key=None, reverse=False)',
    description: 'Returns a new sorted list from the items in iterable.',
    arguments: [
      { name: 'iterable', type: 'iterable', description: 'An iterable to sort' },
      { name: 'key', type: 'callable', description: 'Function to extract comparison key', optional: true },
      { name: 'reverse', type: 'bool', description: 'Sort in descending order', optional: true, defaultValue: 'False' },
    ],
    returns: { type: 'list', description: 'A new sorted list' },
    examples: [
      { code: 'sorted([3, 1, 2])', output: '[1, 2, 3]' },
      { code: 'sorted([3, 1, 2], reverse=True)', output: '[3, 2, 1]' },
      { code: 'sorted(["banana", "apple"], key=len)', output: '["apple", "banana"]' },
    ],
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['list.sort', 'reversed', 'min', 'max'],
    notes: ['Unlike list.sort(), returns a new list'],
  },
  {
    name: 'reversed',
    category: 'Built-in Functions',
    syntax: 'reversed(sequence)',
    description: 'Returns a reverse iterator over the values of the given sequence.',
    arguments: [
      { name: 'sequence', type: 'sequence', description: 'A sequence to reverse' },
    ],
    returns: { type: 'reversed', description: 'A reverse iterator' },
    examples: [
      { code: 'list(reversed([1, 2, 3]))', output: '[3, 2, 1]' },
      { code: 'list(reversed("hello"))', output: '["o", "l", "l", "e", "h"]' },
    ],
    timeComplexity: 'O(1) to create, O(n) to iterate',
    spaceComplexity: 'O(1)',
    relatedMethods: ['list.reverse', 'sorted', 'slice [::-1]'],
  },
  {
    name: 'sum',
    category: 'Built-in Functions',
    syntax: 'sum(iterable, start=0)',
    description: 'Returns the sum of all items in the iterable plus the start value.',
    arguments: [
      { name: 'iterable', type: 'iterable', description: 'An iterable of numbers' },
      { name: 'start', type: 'number', description: 'Value to add to sum', optional: true, defaultValue: '0' },
    ],
    returns: { type: 'number', description: 'Sum of all items' },
    examples: [
      { code: 'sum([1, 2, 3])', output: '6' },
      { code: 'sum([1, 2, 3], 10)', output: '16' },
      { code: 'sum([[1, 2], [3, 4]], [])', output: '[1, 2, 3, 4]', explanation: 'Flatten lists (but use itertools.chain instead)' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['math.fsum', 'reduce'],
    notes: ['For string concatenation, use "".join() instead'],
  },
  {
    name: 'min',
    category: 'Built-in Functions',
    syntax: 'min(iterable, key=None, default=None) | min(arg1, arg2, ...)',
    description: 'Returns the smallest item in an iterable or the smallest of two or more arguments.',
    arguments: [
      { name: 'iterable', type: 'iterable', description: 'An iterable of items' },
      { name: 'key', type: 'callable', description: 'Function to extract comparison key', optional: true },
      { name: 'default', type: 'any', description: 'Value to return if iterable is empty', optional: true },
    ],
    returns: { type: 'any', description: 'The smallest item' },
    examples: [
      { code: 'min([3, 1, 2])', output: '1' },
      { code: 'min("hello")', output: '"e"' },
      { code: 'min(["apple", "banana"], key=len)', output: '"apple"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['max', 'sorted'],
  },
  {
    name: 'max',
    category: 'Built-in Functions',
    syntax: 'max(iterable, key=None, default=None) | max(arg1, arg2, ...)',
    description: 'Returns the largest item in an iterable or the largest of two or more arguments.',
    arguments: [
      { name: 'iterable', type: 'iterable', description: 'An iterable of items' },
      { name: 'key', type: 'callable', description: 'Function to extract comparison key', optional: true },
      { name: 'default', type: 'any', description: 'Value to return if iterable is empty', optional: true },
    ],
    returns: { type: 'any', description: 'The largest item' },
    examples: [
      { code: 'max([3, 1, 2])', output: '3' },
      { code: 'max("hello")', output: '"o"' },
      { code: 'max(["apple", "banana"], key=len)', output: '"banana"' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['min', 'sorted'],
  },
  {
    name: 'abs',
    category: 'Built-in Functions',
    syntax: 'abs(x)',
    description: 'Returns the absolute value of a number.',
    arguments: [
      { name: 'x', type: 'int | float | complex', description: 'A number' },
    ],
    returns: { type: 'int | float', description: 'The absolute value' },
    examples: [
      { code: 'abs(-5)', output: '5' },
      { code: 'abs(3.14)', output: '3.14' },
      { code: 'abs(-3 + 4j)', output: '5.0', explanation: 'Magnitude of complex number' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['math.fabs'],
  },
  {
    name: 'any',
    category: 'Built-in Functions',
    syntax: 'any(iterable)',
    description: 'Returns True if any element of the iterable is truthy. Returns False if the iterable is empty.',
    arguments: [
      { name: 'iterable', type: 'iterable', description: 'An iterable to check' },
    ],
    returns: { type: 'bool', description: 'True if any element is truthy' },
    examples: [
      { code: 'any([False, True, False])', output: 'True' },
      { code: 'any([0, "", None])', output: 'False' },
      { code: 'any(x > 3 for x in [1, 2, 5])', output: 'True' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['all', 'filter'],
    notes: ['Short-circuits on first truthy value'],
  },
  {
    name: 'all',
    category: 'Built-in Functions',
    syntax: 'all(iterable)',
    description: 'Returns True if all elements of the iterable are truthy. Returns True if the iterable is empty.',
    arguments: [
      { name: 'iterable', type: 'iterable', description: 'An iterable to check' },
    ],
    returns: { type: 'bool', description: 'True if all elements are truthy' },
    examples: [
      { code: 'all([True, True, True])', output: 'True' },
      { code: 'all([True, False, True])', output: 'False' },
      { code: 'all(x > 0 for x in [1, 2, 3])', output: 'True' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['any', 'filter'],
    notes: ['Short-circuits on first falsy value'],
  },

  // ============================================================
  // Set Methods
  // ============================================================
  {
    name: 'add',
    category: 'Set Methods',
    syntax: 'set.add(element)',
    description: 'Adds an element to the set.',
    arguments: [
      { name: 'element', type: 'hashable', description: 'Element to add' },
    ],
    returns: { type: 'None', description: 'Returns None, modifies set in place' },
    examples: [
      { code: 's = {1, 2}; s.add(3); s', output: '{1, 2, 3}' },
      { code: 's = {1, 2}; s.add(2); s', output: '{1, 2}', explanation: 'Duplicates ignored' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['update', 'discard', 'remove'],
  },
  {
    name: 'discard',
    category: 'Set Methods',
    syntax: 'set.discard(element)',
    description: 'Removes an element from the set if present. Does nothing if not present.',
    arguments: [
      { name: 'element', type: 'hashable', description: 'Element to remove' },
    ],
    returns: { type: 'None', description: 'Returns None, modifies set in place' },
    examples: [
      { code: 's = {1, 2, 3}; s.discard(2); s', output: '{1, 3}' },
      { code: 's = {1, 2}; s.discard(3); s', output: '{1, 2}', explanation: 'No error if not present' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['remove', 'pop', 'clear'],
    notes: ['Unlike remove(), does not raise KeyError'],
  },
  {
    name: 'union',
    category: 'Set Methods',
    syntax: 'set.union(*others)',
    description: 'Returns a new set with elements from the set and all others.',
    arguments: [
      { name: 'others', type: 'iterable', description: 'Other sets or iterables' },
    ],
    returns: { type: 'set', description: 'A new set with all unique elements' },
    examples: [
      { code: '{1, 2}.union({2, 3})', output: '{1, 2, 3}' },
      { code: '{1, 2} | {3, 4}', output: '{1, 2, 3, 4}' },
    ],
    timeComplexity: 'O(n + m)',
    spaceComplexity: 'O(n + m)',
    relatedMethods: ['intersection', 'difference', '| operator'],
  },
  {
    name: 'intersection',
    category: 'Set Methods',
    syntax: 'set.intersection(*others)',
    description: 'Returns a new set with elements common to the set and all others.',
    arguments: [
      { name: 'others', type: 'iterable', description: 'Other sets or iterables' },
    ],
    returns: { type: 'set', description: 'A new set with common elements' },
    examples: [
      { code: '{1, 2, 3}.intersection({2, 3, 4})', output: '{2, 3}' },
      { code: '{1, 2, 3} & {2, 3, 4}', output: '{2, 3}' },
    ],
    timeComplexity: 'O(min(n, m))',
    spaceComplexity: 'O(min(n, m))',
    relatedMethods: ['union', 'difference', '& operator'],
  },
  {
    name: 'difference',
    category: 'Set Methods',
    syntax: 'set.difference(*others)',
    description: 'Returns a new set with elements in the set that are not in the others.',
    arguments: [
      { name: 'others', type: 'iterable', description: 'Other sets or iterables' },
    ],
    returns: { type: 'set', description: 'A new set with elements only in the original' },
    examples: [
      { code: '{1, 2, 3}.difference({2, 3, 4})', output: '{1}' },
      { code: '{1, 2, 3} - {2, 3}', output: '{1}' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['union', 'intersection', 'symmetric_difference', '- operator'],
  },
];
