import type { Method } from '../types';

export const rubyMethods: Method[] = [
  // Array Methods
  {
    name: 'push',
    category: 'Array Methods',
    syntax: 'array.push(obj)',
    description: 'Appends one or more elements to the end of the array.',
    arguments: [{ name: 'obj', type: 'Object', description: 'Element(s) to add' }],
    returns: { type: 'Array', description: 'The modified array' },
    examples: [{ code: '[1, 2].push(3)', output: '[1, 2, 3]' }],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['<<', 'pop', 'unshift'],
  },
  {
    name: 'pop',
    category: 'Array Methods',
    syntax: 'array.pop',
    description: 'Removes and returns the last element.',
    arguments: [],
    returns: { type: 'Object', description: 'Removed element' },
    examples: [{ code: '[1, 2, 3].pop', output: '3' }],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['push', 'shift'],
  },
  {
    name: 'shift',
    category: 'Array Methods',
    syntax: 'array.shift',
    description: 'Removes and returns the first element.',
    arguments: [],
    returns: { type: 'Object', description: 'Removed element' },
    examples: [{ code: '[1, 2, 3].shift', output: '1' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['unshift', 'pop'],
  },
  {
    name: 'unshift',
    category: 'Array Methods',
    syntax: 'array.unshift(obj)',
    description: 'Prepends one or more elements to the beginning.',
    arguments: [{ name: 'obj', type: 'Object', description: 'Element(s) to add' }],
    returns: { type: 'Array', description: 'The modified array' },
    examples: [{ code: '[2, 3].unshift(1)', output: '[1, 2, 3]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['shift', 'push'],
  },
  {
    name: 'map',
    category: 'Array Methods',
    syntax: 'array.map { |item| block }',
    description: 'Returns a new array with results of running block for every element.',
    arguments: [{ name: 'block', type: 'Block', description: 'Transformation block' }],
    returns: { type: 'Array', description: 'Transformed array' },
    examples: [{ code: '[1, 2, 3].map { |x| x * 2 }', output: '[2, 4, 6]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['collect', 'map!', 'each'],
  },
  {
    name: 'select',
    category: 'Array Methods',
    syntax: 'array.select { |item| block }',
    description: 'Returns array of elements for which block returns true.',
    arguments: [{ name: 'block', type: 'Block', description: 'Filter block' }],
    returns: { type: 'Array', description: 'Filtered array' },
    examples: [{ code: '[1, 2, 3, 4].select { |x| x.even? }', output: '[2, 4]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['reject', 'find_all', 'filter'],
  },
  {
    name: 'reject',
    category: 'Array Methods',
    syntax: 'array.reject { |item| block }',
    description: 'Returns array excluding elements for which block returns true.',
    arguments: [{ name: 'block', type: 'Block', description: 'Rejection block' }],
    returns: { type: 'Array', description: 'Filtered array' },
    examples: [{ code: '[1, 2, 3, 4].reject { |x| x.even? }', output: '[1, 3]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['select', 'reject!'],
  },
  {
    name: 'reduce',
    category: 'Array Methods',
    syntax: 'array.reduce(initial) { |acc, item| block }',
    description: 'Combines all elements by applying a binary operation.',
    arguments: [
      { name: 'initial', type: 'Object', description: 'Initial value', optional: true },
      { name: 'block', type: 'Block', description: 'Accumulator block' },
    ],
    returns: { type: 'Object', description: 'Accumulated result' },
    examples: [{ code: '[1, 2, 3].reduce(0) { |sum, x| sum + x }', output: '6' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['inject', 'sum'],
  },
  {
    name: 'find',
    category: 'Array Methods',
    syntax: 'array.find { |item| block }',
    description: 'Returns first element for which block is truthy.',
    arguments: [{ name: 'block', type: 'Block', description: 'Search block' }],
    returns: { type: 'Object', description: 'Found element or nil' },
    examples: [{ code: '[1, 2, 3, 4].find { |x| x > 2 }', output: '3' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['detect', 'find_all', 'select'],
  },
  {
    name: 'each',
    category: 'Array Methods',
    syntax: 'array.each { |item| block }',
    description: 'Calls block once for each element.',
    arguments: [{ name: 'block', type: 'Block', description: 'Iterator block' }],
    returns: { type: 'Array', description: 'Original array' },
    examples: [{ code: '[1, 2, 3].each { |x| puts x }', output: 'prints 1, 2, 3' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['each_with_index', 'map', 'for'],
  },
  {
    name: 'each_with_index',
    category: 'Array Methods',
    syntax: 'array.each_with_index { |item, index| block }',
    description: 'Calls block with each element and its index.',
    arguments: [{ name: 'block', type: 'Block', description: 'Iterator block with index' }],
    returns: { type: 'Array', description: 'Original array' },
    examples: [
      { code: '["a", "b"].each_with_index { |x, i| puts "#{i}: #{x}" }', output: '0: a, 1: b' },
    ],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['each', 'with_index'],
  },
  {
    name: 'include?',
    category: 'Array Methods',
    syntax: 'array.include?(obj)',
    description: 'Returns true if array contains the element.',
    arguments: [{ name: 'obj', type: 'Object', description: 'Element to find' }],
    returns: { type: 'Boolean', description: 'true if found' },
    examples: [{ code: '[1, 2, 3].include?(2)', output: 'true' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['any?', 'member?'],
  },
  {
    name: 'sort',
    category: 'Array Methods',
    syntax: 'array.sort | array.sort { |a, b| block }',
    description: 'Returns a new sorted array.',
    arguments: [{ name: 'block', type: 'Block', description: 'Comparison block', optional: true }],
    returns: { type: 'Array', description: 'Sorted array' },
    examples: [{ code: '[3, 1, 2].sort', output: '[1, 2, 3]' }],
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['sort!', 'sort_by', 'reverse'],
  },
  {
    name: 'sort_by',
    category: 'Array Methods',
    syntax: 'array.sort_by { |item| block }',
    description: 'Sorts using the value returned by the block.',
    arguments: [{ name: 'block', type: 'Block', description: 'Key block' }],
    returns: { type: 'Array', description: 'Sorted array' },
    examples: [
      { code: '["bb", "a", "ccc"].sort_by { |s| s.length }', output: '["a", "bb", "ccc"]' },
    ],
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['sort', 'min_by', 'max_by'],
  },
  {
    name: 'reverse',
    category: 'Array Methods',
    syntax: 'array.reverse',
    description: 'Returns a new array with elements in reverse order.',
    arguments: [],
    returns: { type: 'Array', description: 'Reversed array' },
    examples: [{ code: '[1, 2, 3].reverse', output: '[3, 2, 1]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['reverse!', 'sort'],
  },
  {
    name: 'flatten',
    category: 'Array Methods',
    syntax: 'array.flatten(level)',
    description: 'Returns a new flattened array.',
    arguments: [
      { name: 'level', type: 'Integer', description: 'Depth to flatten', optional: true },
    ],
    returns: { type: 'Array', description: 'Flattened array' },
    examples: [{ code: '[[1, 2], [3, [4, 5]]].flatten', output: '[1, 2, 3, 4, 5]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['flatten!', 'compact'],
  },
  {
    name: 'uniq',
    category: 'Array Methods',
    syntax: 'array.uniq',
    description: 'Returns a new array with duplicate values removed.',
    arguments: [],
    returns: { type: 'Array', description: 'Array with unique elements' },
    examples: [{ code: '[1, 2, 2, 3, 3].uniq', output: '[1, 2, 3]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['uniq!', 'distinct'],
  },
  {
    name: 'compact',
    category: 'Array Methods',
    syntax: 'array.compact',
    description: 'Returns a new array with nil values removed.',
    arguments: [],
    returns: { type: 'Array', description: 'Array without nils' },
    examples: [{ code: '[1, nil, 2, nil, 3].compact', output: '[1, 2, 3]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['compact!', 'reject'],
  },
  {
    name: 'first',
    category: 'Array Methods',
    syntax: 'array.first(n)',
    description: 'Returns the first element(s).',
    arguments: [{ name: 'n', type: 'Integer', description: 'Number of elements', optional: true }],
    returns: { type: 'Object or Array', description: 'First element(s)' },
    examples: [
      { code: '[1, 2, 3].first', output: '1' },
      { code: '[1, 2, 3].first(2)', output: '[1, 2]' },
    ],
    timeComplexity: 'O(1) or O(n)',
    spaceComplexity: 'O(1) or O(n)',
    relatedMethods: ['last', 'take'],
  },
  {
    name: 'last',
    category: 'Array Methods',
    syntax: 'array.last(n)',
    description: 'Returns the last element(s).',
    arguments: [{ name: 'n', type: 'Integer', description: 'Number of elements', optional: true }],
    returns: { type: 'Object or Array', description: 'Last element(s)' },
    examples: [{ code: '[1, 2, 3].last', output: '3' }],
    timeComplexity: 'O(1) or O(n)',
    spaceComplexity: 'O(1) or O(n)',
    relatedMethods: ['first', 'drop'],
  },
  {
    name: 'take',
    category: 'Array Methods',
    syntax: 'array.take(n)',
    description: 'Returns first n elements.',
    arguments: [{ name: 'n', type: 'Integer', description: 'Number of elements' }],
    returns: { type: 'Array', description: 'First n elements' },
    examples: [{ code: '[1, 2, 3, 4, 5].take(3)', output: '[1, 2, 3]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['drop', 'first'],
  },
  {
    name: 'drop',
    category: 'Array Methods',
    syntax: 'array.drop(n)',
    description: 'Returns all elements after first n.',
    arguments: [{ name: 'n', type: 'Integer', description: 'Number to skip' }],
    returns: { type: 'Array', description: 'Remaining elements' },
    examples: [{ code: '[1, 2, 3, 4, 5].drop(2)', output: '[3, 4, 5]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['take', 'last'],
  },
  {
    name: 'any?',
    category: 'Array Methods',
    syntax: 'array.any? { |item| block }',
    description: 'Returns true if any element satisfies the block.',
    arguments: [{ name: 'block', type: 'Block', description: 'Test block', optional: true }],
    returns: { type: 'Boolean', description: 'true if any match' },
    examples: [{ code: '[1, 2, 3].any? { |x| x > 2 }', output: 'true' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['all?', 'none?', 'one?'],
  },
  {
    name: 'all?',
    category: 'Array Methods',
    syntax: 'array.all? { |item| block }',
    description: 'Returns true if all elements satisfy the block.',
    arguments: [{ name: 'block', type: 'Block', description: 'Test block', optional: true }],
    returns: { type: 'Boolean', description: 'true if all match' },
    examples: [{ code: '[2, 4, 6].all? { |x| x.even? }', output: 'true' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['any?', 'none?'],
  },
  {
    name: 'count',
    category: 'Array Methods',
    syntax: 'array.count(item) | array.count { |x| block }',
    description: 'Returns the count of elements.',
    arguments: [{ name: 'item', type: 'Object', description: 'Item to count', optional: true }],
    returns: { type: 'Integer', description: 'Count' },
    examples: [{ code: '[1, 2, 2, 3].count(2)', output: '2' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['size', 'length'],
  },
  {
    name: 'sum',
    category: 'Array Methods',
    syntax: 'array.sum',
    description: 'Returns the sum of all elements.',
    arguments: [],
    returns: { type: 'Numeric', description: 'Sum' },
    examples: [{ code: '[1, 2, 3].sum', output: '6' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['reduce', 'inject'],
    sinceVersion: 'Ruby 2.4',
  },
  {
    name: 'min',
    category: 'Array Methods',
    syntax: 'array.min',
    description: 'Returns the minimum element.',
    arguments: [],
    returns: { type: 'Object', description: 'Minimum element' },
    examples: [{ code: '[3, 1, 2].min', output: '1' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['max', 'minmax'],
  },
  {
    name: 'max',
    category: 'Array Methods',
    syntax: 'array.max',
    description: 'Returns the maximum element.',
    arguments: [],
    returns: { type: 'Object', description: 'Maximum element' },
    examples: [{ code: '[1, 3, 2].max', output: '3' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['min', 'minmax'],
  },
  {
    name: 'join',
    category: 'Array Methods',
    syntax: 'array.join(separator)',
    description: 'Returns a string of all elements joined.',
    arguments: [{ name: 'separator', type: 'String', description: 'Separator', optional: true }],
    returns: { type: 'String', description: 'Joined string' },
    examples: [{ code: '["a", "b", "c"].join("-")', output: '"a-b-c"' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['split', 'to_s'],
  },

  // String Methods
  {
    name: 'split',
    category: 'String Methods',
    syntax: 'string.split(pattern)',
    description: 'Divides string into substrings based on delimiter.',
    arguments: [{ name: 'pattern', type: 'String or Regexp', description: 'Delimiter' }],
    returns: { type: 'Array', description: 'Array of substrings' },
    examples: [{ code: '"a,b,c".split(",")', output: '["a", "b", "c"]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['join', 'scan'],
  },
  {
    name: 'upcase',
    category: 'String Methods',
    syntax: 'string.upcase',
    description: 'Returns uppercase version of string.',
    arguments: [],
    returns: { type: 'String', description: 'Uppercase string' },
    examples: [{ code: '"hello".upcase', output: '"HELLO"' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['downcase', 'capitalize'],
  },
  {
    name: 'downcase',
    category: 'String Methods',
    syntax: 'string.downcase',
    description: 'Returns lowercase version of string.',
    arguments: [],
    returns: { type: 'String', description: 'Lowercase string' },
    examples: [{ code: '"HELLO".downcase', output: '"hello"' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['upcase', 'capitalize'],
  },
  {
    name: 'strip',
    category: 'String Methods',
    syntax: 'string.strip',
    description: 'Returns string with leading/trailing whitespace removed.',
    arguments: [],
    returns: { type: 'String', description: 'Stripped string' },
    examples: [{ code: '"  hello  ".strip', output: '"hello"' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['lstrip', 'rstrip', 'chomp'],
  },
  {
    name: 'gsub',
    category: 'String Methods',
    syntax: 'string.gsub(pattern, replacement)',
    description: 'Returns string with all occurrences of pattern replaced.',
    arguments: [
      { name: 'pattern', type: 'String or Regexp', description: 'Pattern to replace' },
      { name: 'replacement', type: 'String', description: 'Replacement' },
    ],
    returns: { type: 'String', description: 'Modified string' },
    examples: [{ code: '"hello world".gsub("world", "ruby")', output: '"hello ruby"' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['sub', 'tr'],
  },
  {
    name: 'start_with?',
    category: 'String Methods',
    syntax: 'string.start_with?(prefix)',
    description: 'Returns true if string starts with the given prefix.',
    arguments: [{ name: 'prefix', type: 'String', description: 'Prefix to check' }],
    returns: { type: 'Boolean', description: 'true if starts with prefix' },
    examples: [{ code: '"hello".start_with?("he")', output: 'true' }],
    timeComplexity: 'O(m)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['end_with?', 'include?'],
  },
  {
    name: 'end_with?',
    category: 'String Methods',
    syntax: 'string.end_with?(suffix)',
    description: 'Returns true if string ends with the given suffix.',
    arguments: [{ name: 'suffix', type: 'String', description: 'Suffix to check' }],
    returns: { type: 'Boolean', description: 'true if ends with suffix' },
    examples: [{ code: '"hello".end_with?("lo")', output: 'true' }],
    timeComplexity: 'O(m)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['start_with?', 'include?'],
  },
  {
    name: 'chars',
    category: 'String Methods',
    syntax: 'string.chars',
    description: 'Returns an array of characters.',
    arguments: [],
    returns: { type: 'Array', description: 'Array of single-char strings' },
    examples: [{ code: '"hello".chars', output: '["h", "e", "l", "l", "o"]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['bytes', 'each_char'],
  },

  // Hash Methods
  {
    name: 'keys',
    category: 'Hash Methods',
    syntax: 'hash.keys',
    description: 'Returns an array of all keys.',
    arguments: [],
    returns: { type: 'Array', description: 'Array of keys' },
    examples: [{ code: '{ a: 1, b: 2 }.keys', output: '[:a, :b]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['values', 'each_key'],
  },
  {
    name: 'values',
    category: 'Hash Methods',
    syntax: 'hash.values',
    description: 'Returns an array of all values.',
    arguments: [],
    returns: { type: 'Array', description: 'Array of values' },
    examples: [{ code: '{ a: 1, b: 2 }.values', output: '[1, 2]' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['keys', 'each_value'],
  },
  {
    name: 'fetch',
    category: 'Hash Methods',
    syntax: 'hash.fetch(key, default)',
    description: 'Returns the value for key, or default if not found.',
    arguments: [
      { name: 'key', type: 'Object', description: 'Key to find' },
      { name: 'default', type: 'Object', description: 'Default value', optional: true },
    ],
    returns: { type: 'Object', description: 'Value or default' },
    examples: [
      { code: '{ a: 1 }.fetch(:a)', output: '1' },
      { code: '{ a: 1 }.fetch(:b, 0)', output: '0' },
    ],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['[]', 'dig'],
  },
  {
    name: 'merge',
    category: 'Hash Methods',
    syntax: 'hash.merge(other_hash)',
    description: 'Returns a new hash with combined contents.',
    arguments: [{ name: 'other_hash', type: 'Hash', description: 'Hash to merge' }],
    returns: { type: 'Hash', description: 'Merged hash' },
    examples: [{ code: '{ a: 1 }.merge({ b: 2 })', output: '{ a: 1, b: 2 }' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['merge!', 'update'],
  },
  {
    name: 'key?',
    category: 'Hash Methods',
    syntax: 'hash.key?(key)',
    description: 'Returns true if key exists.',
    arguments: [{ name: 'key', type: 'Object', description: 'Key to check' }],
    returns: { type: 'Boolean', description: 'true if key exists' },
    examples: [{ code: '{ a: 1 }.key?(:a)', output: 'true' }],
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    relatedMethods: ['has_key?', 'include?', 'value?'],
  },
  {
    name: 'transform_values',
    category: 'Hash Methods',
    syntax: 'hash.transform_values { |v| block }',
    description: 'Returns new hash with values transformed by block.',
    arguments: [{ name: 'block', type: 'Block', description: 'Transform block' }],
    returns: { type: 'Hash', description: 'Transformed hash' },
    examples: [{ code: '{ a: 1, b: 2 }.transform_values { |v| v * 2 }', output: '{ a: 2, b: 4 }' }],
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    relatedMethods: ['transform_keys', 'map'],
    sinceVersion: 'Ruby 2.4',
  },
];

export default rubyMethods;
