import type { Language, LanguageId } from './types';

export const languages: Record<LanguageId, Language> = {
  javascript: {
    id: 'javascript',
    name: 'JavaScript',
    icon: 'JS',
    color: '#F7DF1E',
    secondaryColor: '#323330',
    fileExtension: '.js',
    monacoLanguage: 'javascript',
    categories: [
      'Array Methods',
      'String Methods',
      'Object Methods',
      'Set Methods',
      'Map Methods',
      'Math Operations',
      'Date Methods',
      'JSON Methods',
      'RegExp Methods',
      'Promise Methods',
    ],
  },
  typescript: {
    id: 'typescript',
    name: 'TypeScript',
    icon: 'TS',
    color: '#3178C6',
    secondaryColor: '#235A97',
    fileExtension: '.ts',
    monacoLanguage: 'typescript',
    categories: [
      'Array Methods',
      'String Methods',
      'Object Methods',
      'Set Methods',
      'Map Methods',
      'Type Utilities',
      'Generic Patterns',
      'Utility Types',
    ],
  },
  python: {
    id: 'python',
    name: 'Python',
    icon: 'PY',
    color: '#3776AB',
    secondaryColor: '#FFD43B',
    fileExtension: '.py',
    monacoLanguage: 'python',
    categories: [
      'List Methods',
      'String Methods',
      'Dict Methods',
      'Set Methods',
      'Tuple Methods',
      'List Comprehensions',
      'Built-in Functions',
      'Itertools',
    ],
  },
  java: {
    id: 'java',
    name: 'Java',
    icon: 'JA',
    color: '#ED8B00',
    secondaryColor: '#5382A1',
    fileExtension: '.java',
    monacoLanguage: 'java',
    categories: [
      'ArrayList Methods',
      'String Methods',
      'Stream API',
      'HashMap Methods',
      'HashSet Methods',
      'Arrays Utility',
      'Collections Utility',
      'Optional Methods',
    ],
  },
  cpp: {
    id: 'cpp',
    name: 'C++',
    icon: 'C++',
    color: '#00599C',
    secondaryColor: '#004482',
    fileExtension: '.cpp',
    monacoLanguage: 'cpp',
    categories: [
      'Vector Methods',
      'String Methods',
      'Algorithm Library',
      'Map Methods',
      'Set Methods',
      'Deque Methods',
      'Stack/Queue',
      'Numeric Operations',
    ],
  },
  csharp: {
    id: 'csharp',
    name: 'C#',
    icon: 'C#',
    color: '#512BD4',
    secondaryColor: '#68217A',
    fileExtension: '.cs',
    monacoLanguage: 'csharp',
    categories: [
      'List Methods',
      'String Methods',
      'LINQ Methods',
      'Dictionary Methods',
      'HashSet Methods',
      'Array Methods',
      'Enumerable Methods',
    ],
  },
  go: {
    id: 'go',
    name: 'Go',
    icon: 'GO',
    color: '#00ADD8',
    secondaryColor: '#5DC9E2',
    fileExtension: '.go',
    monacoLanguage: 'go',
    categories: [
      'Slice Operations',
      'String Operations',
      'Map Operations',
      'Sort Package',
      'Strings Package',
      'Strconv Package',
      'Math Package',
    ],
  },
  ruby: {
    id: 'ruby',
    name: 'Ruby',
    icon: 'RB',
    color: '#CC342D',
    secondaryColor: '#A91401',
    fileExtension: '.rb',
    monacoLanguage: 'ruby',
    categories: [
      'Array Methods',
      'String Methods',
      'Hash Methods',
      'Enumerable Methods',
      'Set Methods',
      'Range Methods',
      'Numeric Methods',
    ],
  },
  c: {
    id: 'c',
    name: 'C',
    icon: 'C',
    color: '#A8B9CC',
    secondaryColor: '#283593',
    fileExtension: '.c',
    monacoLanguage: 'c',
    categories: [
      'String Functions',
      'Memory Functions',
      'Math Functions',
      'Stdlib Functions',
      'Stdio Functions',
      'Ctype Functions',
      'Array Operations',
    ],
  },
};

export const getLanguage = (id: LanguageId): Language => languages[id];

export const getAllLanguages = (): Language[] => Object.values(languages);

export const getLanguagesByCategory = (category: string): Language[] =>
  Object.values(languages).filter((lang) => lang.categories.includes(category));

export const languageIds: LanguageId[] = Object.keys(languages) as LanguageId[];
