import type { Language, LanguageId } from './types';

export const languages: Record<LanguageId, Language> = {
  javascript: {
    id: 'javascript',
    name: 'JavaScript',
    icon: 'JS',
    color: '#F7DF1E',
    secondaryColor: '#323330',
    fileExtension: '.js',
    monacoLanguage: 'javascript',
    categories: [
      'Array Methods',
      'String Methods',
      'Object Methods',
      'Set Methods',
      'Map Methods',
      'Math Operations',
      'Date Methods',
      'JSON Methods',
      'RegExp Methods',
      'Promise Methods',
    ],
  },
  typescript: {
    id: 'typescript',
    name: 'TypeScript',
    icon: 'TS',
    color: '#3178C6',
    secondaryColor: '#235A97',
    fileExtension: '.ts',
    monacoLanguage: 'typescript',
    categories: [
      'Array Methods',
      'String Methods',
      'Object Methods',
      'Set Methods',
      'Map Methods',
      'Type Utilities',
      'Generic Patterns',
      'Utility Types',
    ],
  },
  python: {
    id: 'python',
    name: 'Python',
    icon: 'PY',
    color: '#3776AB',
    secondaryColor: '#FFD43B',
    fileExtension: '.py',
    monacoLanguage: 'python',
    categories: [
      'List Methods',
      'String Methods',
      'Dict Methods',
      'Set Methods',
      'Tuple Methods',
      'List Comprehensions',
      'Built-in Functions',
      'Itertools',
    ],
  },
  java: {
    id: 'java',
    name: 'Java',
    icon: 'JA',
    color: '#ED8B00',
    secondaryColor: '#5382A1',
    fileExtension: '.java',
    monacoLanguage: 'java',
    categories: [
      'ArrayList Methods',
      'String Methods',
      'Stream API',
      'HashMap Methods',
      'HashSet Methods',
      'Arrays Utility',
      'Collections Utility',
      'Optional Methods',
    ],
  },
  cpp: {
    id: 'cpp',
    name: 'C++',
    icon: 'C++',
    color: '#00599C',
    secondaryColor: '#004482',
    fileExtension: '.cpp',
    monacoLanguage: 'cpp',
    categories: [
      'Vector Methods',
      'String Methods',
      'Algorithm Library',
      'Map Methods',
      'Set Methods',
      'Deque Methods',
      'Stack/Queue',
      'Numeric Operations',
    ],
  },
  csharp: {
    id: 'csharp',
    name: 'C#',
    icon: 'C#',
    color: '#512BD4',
    secondaryColor: '#68217A',
    fileExtension: '.cs',
    monacoLanguage: 'csharp',
    categories: [
      'List Methods',
      'String Methods',
      'LINQ Methods',
      'Dictionary Methods',
      'HashSet Methods',
      'Array Methods',
      'Enumerable Methods',
    ],
  },
  go: {
    id: 'go',
    name: 'Go',
    icon: 'GO',
    color: '#00ADD8',
    secondaryColor: '#5DC9E2',
    fileExtension: '.go',
    monacoLanguage: 'go',
    categories: [
      'Slice Operations',
      'String Operations',
      'Map Operations',
      'Sort Package',
      'Strings Package',
      'Strconv Package',
      'Math Package',
    ],
  },
  ruby: {
    id: 'ruby',
    name: 'Ruby',
    icon: 'RB',
    color: '#CC342D',
    secondaryColor: '#A91401',
    fileExtension: '.rb',
    monacoLanguage: 'ruby',
    categories: [
      'Array Methods',
      'String Methods',
      'Hash Methods',
      'Enumerable Methods',
      'Set Methods',
      'Range Methods',
      'Numeric Methods',
    ],
  },
  c: {
    id: 'c',
    name: 'C',
    icon: 'C',
    color: '#A8B9CC',
    secondaryColor: '#283593',
    fileExtension: '.c',
    monacoLanguage: 'c',
    categories: [
      'String Functions',
      'Memory Functions',
      'Math Functions',
      'Stdlib Functions',
      'Stdio Functions',
      'Ctype Functions',
      'Array Operations',
    ],
  },
  php: {
    id: 'php',
    name: 'PHP',
    icon: 'PHP',
    color: '#777BB4',
    secondaryColor: '#4F5B93',
    fileExtension: '.php',
    monacoLanguage: 'php',
    categories: [
      'Array Functions',
      'String Functions',
      'Collection Methods',
      'Eloquent ORM',
      'Laravel Helpers',
      'Date & Time',
      'File Functions',
      'JSON Functions',
      'Math Functions',
      'Type Functions',
    ],
  },
  kotlin: {
    id: 'kotlin',
    name: 'Kotlin',
    icon: 'Kt',
    color: '#7F52FF',
    secondaryColor: '#A97BFF',
    fileExtension: '.kt',
    monacoLanguage: 'kotlin',
    categories: [
      'List Operations',
      'Collection Functions',
      'String Operations',
      'Map Operations',
      'Null Safety',
      'Scope Functions',
      'Sequences',
      'Kotlin Idioms',
    ],
  },
  // New languages
  rust: {
    id: 'rust',
    name: 'Rust',
    icon: 'RS',
    color: '#DEA584',
    secondaryColor: '#B7410E',
    fileExtension: '.rs',
    monacoLanguage: 'rust',
    categories: [
      'Iterators',
      'Vectors',
      'Strings',
      'Option/Result',
      'Slices',
      'HashMap',
      'Ownership',
      'Pattern Matching',
    ],
  },
  swift: {
    id: 'swift',
    name: 'Swift',
    icon: 'SW',
    color: '#F05138',
    secondaryColor: '#FFAC45',
    fileExtension: '.swift',
    monacoLanguage: 'swift',
    categories: [
      'Arrays',
      'Strings',
      'Dictionaries',
      'Sets',
      'Optionals',
      'Higher-Order Functions',
      'Protocols',
      'Error Handling',
    ],
  },
  scala: {
    id: 'scala',
    name: 'Scala',
    icon: 'SC',
    color: '#DC322F',
    secondaryColor: '#C21325',
    fileExtension: '.scala',
    monacoLanguage: 'scala',
    categories: [
      'Lists',
      'Strings',
      'Options',
      'Maps',
      'Pattern Matching',
      'Case Classes',
      'Collections',
      'Functional',
    ],
  },
  r: {
    id: 'r',
    name: 'R',
    icon: 'R',
    color: '#276DC3',
    secondaryColor: '#165CAA',
    fileExtension: '.r',
    monacoLanguage: 'r',
    categories: [
      'Vectors',
      'Strings',
      'Lists',
      'Data Frames',
      'Math',
      'Statistical',
      'Matrix Operations',
      'Apply Functions',
    ],
  },
  perl: {
    id: 'perl',
    name: 'Perl',
    icon: 'PL',
    color: '#39457E',
    secondaryColor: '#0298C3',
    fileExtension: '.pl',
    monacoLanguage: 'perl',
    categories: [
      'Arrays',
      'Strings',
      'Hashes',
      'Regex',
      'Files',
      'References',
      'Built-ins',
    ],
  },
  lua: {
    id: 'lua',
    name: 'Lua',
    icon: 'LUA',
    color: '#000080',
    secondaryColor: '#00007F',
    fileExtension: '.lua',
    monacoLanguage: 'lua',
    categories: [
      'Tables',
      'Strings',
      'Math',
      'Iterators',
      'Patterns',
      'Coroutines',
      'Metatables',
    ],
  },
  haskell: {
    id: 'haskell',
    name: 'Haskell',
    icon: 'HS',
    color: '#5D4F85',
    secondaryColor: '#453A62',
    fileExtension: '.hs',
    monacoLanguage: 'haskell',
    categories: [
      'Lists',
      'Strings',
      'Higher-Order',
      'Maybe/Either',
      'Folds',
      'Type Classes',
      'Monads',
      'Pattern Matching',
    ],
  },
  elixir: {
    id: 'elixir',
    name: 'Elixir',
    icon: 'EX',
    color: '#4B275F',
    secondaryColor: '#6E4A7E',
    fileExtension: '.ex',
    monacoLanguage: 'elixir',
    categories: [
      'Enum',
      'Strings',
      'Lists',
      'Maps',
      'Pipes',
      'Pattern Matching',
      'Streams',
      'Agents',
    ],
  },
  dart: {
    id: 'dart',
    name: 'Dart',
    icon: 'DT',
    color: '#0175C2',
    secondaryColor: '#02569B',
    fileExtension: '.dart',
    monacoLanguage: 'dart',
    categories: [
      'Lists',
      'Strings',
      'Maps',
      'Sets',
      'Null Safety',
      'Futures',
      'Streams',
      'Collections',
    ],
  },
  clojure: {
    id: 'clojure',
    name: 'Clojure',
    icon: 'CLJ',
    color: '#5881D8',
    secondaryColor: '#63B132',
    fileExtension: '.clj',
    monacoLanguage: 'clojure',
    categories: [
      'Sequences',
      'Collections',
      'Strings',
      'Threading',
      'Transducers',
      'Multimethods',
      'Atoms',
      'Destructuring',
    ],
  },
};

export const getLanguage = (id: LanguageId): Language => languages[id];

export const getAllLanguages = (): Language[] => Object.values(languages);

export const getLanguagesByCategory = (category: string): Language[] =>
  Object.values(languages).filter((lang) => lang.categories.includes(category));

export const languageIds: LanguageId[] = Object.keys(languages) as LanguageId[];
