/**
 * C++ STL Cheatsheet
 *
 * Essential C++ STL methods for coding interviews.
 * Covers vector, string, map, unordered_map, set, unordered_set,
 * algorithm functions, stack, queue, and priority_queue.
 */

import type { CheatsheetEntry } from './types';

export const cppCheatsheet: CheatsheetEntry[] = [
  // ============== VECTOR (arrays) ==============
  {
    name: 'push_back',
    category: 'arrays',
    syntax: 'vec.push_back(value)',
    description: 'Adds element to the end of vector',
    example: {
      code: 'vector<int> v = {1, 2};\nv.push_back(3);\n// v = {1, 2, 3}',
      output: '{1, 2, 3}',
    },
    timeComplexity: 'O(1) amortized',
    spaceComplexity: 'O(1)',
    gotchas: ['May cause reallocation if capacity exceeded'],
    interviewTip: 'Use emplace_back for in-place construction of complex objects',
    priority: 'essential',
  },
  {
    name: 'pop_back',
    category: 'arrays',
    syntax: 'vec.pop_back()',
    description: 'Removes the last element from vector',
    example: {
      code: 'vector<int> v = {1, 2, 3};\nv.pop_back();\n// v = {1, 2}',
      output: '{1, 2}',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Undefined behavior on empty vector - check size first'],
    priority: 'essential',
  },
  {
    name: 'size',
    category: 'arrays',
    syntax: 'vec.size()',
    description: 'Returns number of elements in container',
    example: {
      code: 'vector<int> v = {1, 2, 3};\nsize_t n = v.size();\n// n = 3',
      output: '3',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns size_t (unsigned) - be careful with subtraction'],
    interviewTip: 'Cast to int when doing arithmetic to avoid underflow bugs',
    priority: 'essential',
  },
  {
    name: 'empty',
    category: 'arrays',
    syntax: 'vec.empty()',
    description: 'Returns true if container has no elements',
    example: {
      code: 'vector<int> v;\nbool e = v.empty();\n// e = true',
      output: 'true',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Prefer empty() over size() == 0 for clarity',
    priority: 'essential',
  },
  {
    name: 'front/back',
    category: 'arrays',
    syntax: 'vec.front() / vec.back()',
    description: 'Access first/last element of vector',
    example: {
      code: 'vector<int> v = {1, 2, 3};\nint f = v.front(); // 1\nint b = v.back();  // 3',
      output: '1, 3',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Undefined behavior on empty vector'],
    priority: 'essential',
  },
  {
    name: 'erase',
    category: 'arrays',
    syntax: 'vec.erase(iterator) / vec.erase(first, last)',
    description: 'Removes element(s) at position or range',
    example: {
      code: 'vector<int> v = {1, 2, 3, 4};\nv.erase(v.begin() + 1);\n// v = {1, 3, 4}',
      output: '{1, 3, 4}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Invalidates iterators at and after erased position'],
    interviewTip: 'Use erase-remove idiom for removing multiple elements',
    priority: 'essential',
  },
  {
    name: 'insert',
    category: 'arrays',
    syntax: 'vec.insert(iterator, value)',
    description: 'Inserts element at specified position',
    example: {
      code: 'vector<int> v = {1, 3};\nv.insert(v.begin() + 1, 2);\n// v = {1, 2, 3}',
      output: '{1, 2, 3}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Invalidates all iterators if reallocation occurs'],
    priority: 'common',
  },
  {
    name: 'reserve',
    category: 'arrays',
    syntax: 'vec.reserve(n)',
    description: 'Pre-allocates memory for n elements',
    example: {
      code: 'vector<int> v;\nv.reserve(1000);\n// Capacity >= 1000, size = 0',
      output: 'capacity >= 1000',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Use when you know the final size to avoid reallocations',
    priority: 'common',
  },
  {
    name: 'resize',
    category: 'arrays',
    syntax: 'vec.resize(n) / vec.resize(n, value)',
    description: 'Changes container size, adding/removing elements as needed',
    example: {
      code: 'vector<int> v = {1, 2};\nv.resize(4, 0);\n// v = {1, 2, 0, 0}',
      output: '{1, 2, 0, 0}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['New elements are value-initialized if no value provided'],
    priority: 'common',
  },
  {
    name: 'clear',
    category: 'arrays',
    syntax: 'vec.clear()',
    description: 'Removes all elements from container',
    example: {
      code: 'vector<int> v = {1, 2, 3};\nv.clear();\n// v.size() = 0',
      output: 'size = 0',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Does not reduce capacity - use shrink_to_fit if needed'],
    priority: 'common',
  },

  // ============== STRING ==============
  {
    name: 'substr',
    category: 'strings',
    syntax: 'str.substr(pos, len)',
    description: 'Returns substring starting at pos with length len',
    example: {
      code: 'string s = "hello";\nstring sub = s.substr(1, 3);\n// sub = "ell"',
      output: '"ell"',
    },
    timeComplexity: 'O(len)',
    spaceComplexity: 'O(len)',
    gotchas: ['Throws out_of_range if pos > size()'],
    interviewTip: 'Second parameter is length, not end position',
    priority: 'essential',
  },
  {
    name: 'find',
    category: 'strings',
    syntax: 'str.find(substr, pos)',
    description: 'Finds first occurrence of substring starting from pos',
    example: {
      code: 'string s = "hello";\nsize_t pos = s.find("ll");\n// pos = 2',
      output: '2',
    },
    timeComplexity: 'O(n*m)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns string::npos if not found - always check!'],
    interviewTip: 'Compare with string::npos, not -1',
    priority: 'essential',
  },
  {
    name: 'append/+=',
    category: 'strings',
    syntax: 'str.append(s) / str += s',
    description: 'Appends string or character to end',
    example: {
      code: 'string s = "hello";\ns += " world";\n// s = "hello world"',
      output: '"hello world"',
    },
    timeComplexity: 'O(m) where m is appended length',
    spaceComplexity: 'O(m)',
    interviewTip: 'Building strings in loop? Consider reserve() first',
    priority: 'essential',
  },
  {
    name: 'c_str',
    category: 'strings',
    syntax: 'str.c_str()',
    description: 'Returns null-terminated C-style string pointer',
    example: {
      code: 'string s = "hello";\nconst char* cs = s.c_str();',
      output: '"hello\\0"',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Pointer invalidated if string is modified'],
    priority: 'common',
  },
  {
    name: 'stoi/stol/stod',
    category: 'strings',
    syntax: 'stoi(str) / stol(str) / stod(str)',
    description: 'Converts string to int/long/double',
    example: {
      code: 'string s = "123";\nint n = stoi(s);\n// n = 123',
      output: '123',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Throws invalid_argument if conversion fails'],
    interviewTip: 'Use try-catch or validate input for robustness',
    priority: 'essential',
  },
  {
    name: 'to_string',
    category: 'strings',
    syntax: 'to_string(num)',
    description: 'Converts numeric value to string',
    example: {
      code: 'int n = 42;\nstring s = to_string(n);\n// s = "42"',
      output: '"42"',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(log n)',
    priority: 'essential',
  },
  {
    name: 'compare',
    category: 'strings',
    syntax: 'str1.compare(str2)',
    description: 'Compares strings lexicographically, returns <0, 0, or >0',
    example: {
      code: 'string a = "abc", b = "abd";\nint cmp = a.compare(b);\n// cmp < 0',
      output: '-1 (negative)',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use == for equality, compare() for ordering',
    priority: 'common',
  },

  // ============== MAP (ordered) ==============
  {
    name: 'map insert/[]',
    category: 'maps',
    syntax: 'map[key] = value / map.insert({key, value})',
    description: 'Inserts or updates key-value pair in ordered map',
    example: {
      code: 'map<string, int> m;\nm["a"] = 1;\nm.insert({"b", 2});',
      output: '{{"a", 1}, {"b", 2}}',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['operator[] creates default entry if key not found'],
    interviewTip: "Use insert() if you don't want to create new entries",
    priority: 'essential',
  },
  {
    name: 'map find',
    category: 'maps',
    syntax: 'map.find(key)',
    description: 'Returns iterator to element or end() if not found',
    example: {
      code: 'map<string, int> m = {{"a", 1}};\nauto it = m.find("a");\n// it->second = 1',
      output: 'iterator to {"a", 1}',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Always check it != map.end() before dereferencing',
    priority: 'essential',
  },
  {
    name: 'map count',
    category: 'maps',
    syntax: 'map.count(key)',
    description: 'Returns 1 if key exists, 0 otherwise',
    example: {
      code: 'map<string, int> m = {{"a", 1}};\nint c = m.count("a");\n// c = 1',
      output: '1',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    interviewTip: "Use for existence check when you don't need the value",
    priority: 'essential',
  },
  {
    name: 'map erase',
    category: 'maps',
    syntax: 'map.erase(key) / map.erase(iterator)',
    description: 'Removes element by key or iterator',
    example: {
      code: 'map<string, int> m = {{"a", 1}, {"b", 2}};\nm.erase("a");\n// m = {{"b", 2}}',
      output: '{{"b", 2}}',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },

  // ============== UNORDERED_MAP ==============
  {
    name: 'unordered_map insert/[]',
    category: 'maps',
    syntax: 'umap[key] = value',
    description: 'Inserts or updates key-value pair in hash map',
    example: {
      code: 'unordered_map<string, int> m;\nm["a"] = 1;',
      output: '{{"a", 1}}',
    },
    timeComplexity: 'O(1) average, O(n) worst',
    spaceComplexity: 'O(1)',
    gotchas: ['operator[] creates default entry if key not found'],
    interviewTip: "Prefer unordered_map over map for O(1) lookups when order doesn't matter",
    priority: 'essential',
  },
  {
    name: 'unordered_map find',
    category: 'maps',
    syntax: 'umap.find(key)',
    description: 'Returns iterator to element or end() if not found',
    example: {
      code: 'unordered_map<int, int> m = {{1, 10}};\nauto it = m.find(1);',
      output: 'iterator to {1, 10}',
    },
    timeComplexity: 'O(1) average, O(n) worst',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },

  // ============== SET ==============
  {
    name: 'set insert',
    category: 'sets',
    syntax: 'set.insert(value)',
    description: 'Inserts element into ordered set',
    example: {
      code: 'set<int> s;\ns.insert(3);\ns.insert(1);\n// s = {1, 3}',
      output: '{1, 3}',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns pair<iterator, bool> - second is false if already exists'],
    priority: 'essential',
  },
  {
    name: 'set find',
    category: 'sets',
    syntax: 'set.find(value)',
    description: 'Returns iterator to element or end() if not found',
    example: {
      code: 'set<int> s = {1, 2, 3};\nauto it = s.find(2);\n// *it = 2',
      output: 'iterator to 2',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'set count',
    category: 'sets',
    syntax: 'set.count(value)',
    description: 'Returns 1 if element exists, 0 otherwise',
    example: {
      code: 'set<int> s = {1, 2, 3};\nint c = s.count(2);\n// c = 1',
      output: '1',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'set erase',
    category: 'sets',
    syntax: 'set.erase(value)',
    description: 'Removes element from set',
    example: {
      code: 'set<int> s = {1, 2, 3};\ns.erase(2);\n// s = {1, 3}',
      output: '{1, 3}',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },

  // ============== UNORDERED_SET ==============
  {
    name: 'unordered_set insert',
    category: 'sets',
    syntax: 'uset.insert(value)',
    description: 'Inserts element into hash set',
    example: {
      code: 'unordered_set<int> s;\ns.insert(1);\ns.insert(2);',
      output: '{1, 2}',
    },
    timeComplexity: 'O(1) average, O(n) worst',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use for O(1) lookups when you only need existence checks',
    priority: 'essential',
  },
  {
    name: 'unordered_set count',
    category: 'sets',
    syntax: 'uset.count(value)',
    description: 'Returns 1 if element exists, 0 otherwise',
    example: {
      code: 'unordered_set<int> s = {1, 2};\nbool exists = s.count(1);',
      output: '1 (true)',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },

  // ============== SORTING ==============
  {
    name: 'sort',
    category: 'sorting',
    syntax: 'sort(begin, end) / sort(begin, end, comparator)',
    description: 'Sorts elements in ascending order (or by custom comparator)',
    example: {
      code: 'vector<int> v = {3, 1, 2};\nsort(v.begin(), v.end());\n// v = {1, 2, 3}',
      output: '{1, 2, 3}',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(log n)',
    gotchas: ['Comparator must define strict weak ordering'],
    interviewTip:
      'Use lambda for custom sorting: sort(v.begin(), v.end(), [](int a, int b) { return a > b; })',
    priority: 'essential',
  },
  {
    name: 'stable_sort',
    category: 'sorting',
    syntax: 'stable_sort(begin, end)',
    description: 'Sorts preserving relative order of equal elements',
    example: {
      code: 'vector<pair<int,int>> v = {{1,1}, {2,1}, {1,2}};\nstable_sort(v.begin(), v.end());',
      output: '{{1,1}, {1,2}, {2,1}}',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Use when order of equal elements matters',
    priority: 'common',
  },
  {
    name: 'partial_sort',
    category: 'sorting',
    syntax: 'partial_sort(begin, middle, end)',
    description: 'Sorts first (middle-begin) elements',
    example: {
      code: 'vector<int> v = {5, 3, 1, 4, 2};\npartial_sort(v.begin(), v.begin()+3, v.end());\n// First 3 are sorted',
      output: '{1, 2, 3, ...}',
    },
    timeComplexity: 'O(n log k)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Efficient for finding top-k elements',
    priority: 'useful',
  },
  {
    name: 'nth_element',
    category: 'sorting',
    syntax: 'nth_element(begin, nth, end)',
    description: 'Partitions so nth element is in sorted position',
    example: {
      code: 'vector<int> v = {5, 3, 1, 4, 2};\nnth_element(v.begin(), v.begin()+2, v.end());\n// v[2] is the median',
      output: 'v[2] = 3 (median)',
    },
    timeComplexity: 'O(n) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Perfect for finding kth smallest/largest in O(n)',
    priority: 'common',
  },

  // ============== SEARCHING ==============
  {
    name: 'binary_search',
    category: 'searching',
    syntax: 'binary_search(begin, end, value)',
    description: 'Returns true if value exists in sorted range',
    example: {
      code: 'vector<int> v = {1, 2, 3, 4, 5};\nbool found = binary_search(v.begin(), v.end(), 3);',
      output: 'true',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Container must be sorted!'],
    interviewTip: 'Only tells you existence - use lower_bound for position',
    priority: 'essential',
  },
  {
    name: 'lower_bound',
    category: 'searching',
    syntax: 'lower_bound(begin, end, value)',
    description: 'Returns iterator to first element >= value',
    example: {
      code: 'vector<int> v = {1, 2, 4, 5};\nauto it = lower_bound(v.begin(), v.end(), 3);\n// *it = 4',
      output: 'iterator to 4',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns end() if all elements are less than value'],
    interviewTip: 'Essential for binary search problems - memorize this!',
    priority: 'essential',
  },
  {
    name: 'upper_bound',
    category: 'searching',
    syntax: 'upper_bound(begin, end, value)',
    description: 'Returns iterator to first element > value',
    example: {
      code: 'vector<int> v = {1, 2, 2, 3};\nauto it = upper_bound(v.begin(), v.end(), 2);\n// *it = 3',
      output: 'iterator to 3',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'upper_bound - lower_bound gives count of element',
    priority: 'essential',
  },
  {
    name: 'find (algorithm)',
    category: 'searching',
    syntax: 'find(begin, end, value)',
    description: 'Linear search for value, returns iterator',
    example: {
      code: 'vector<int> v = {1, 2, 3};\nauto it = find(v.begin(), v.end(), 2);',
      output: 'iterator to 2',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use binary_search on sorted data instead',
    priority: 'common',
  },

  // ============== STACK ==============
  {
    name: 'stack push/pop/top',
    category: 'collections',
    syntax: 'stk.push(val) / stk.pop() / stk.top()',
    description: 'LIFO operations: add, remove, and access top element',
    example: {
      code: 'stack<int> s;\ns.push(1);\ns.push(2);\nint t = s.top(); // 2\ns.pop();',
      output: 'top = 2',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['top() and pop() on empty stack is undefined behavior'],
    interviewTip: 'Essential for parentheses matching, monotonic stack problems',
    priority: 'essential',
  },

  // ============== QUEUE ==============
  {
    name: 'queue push/pop/front',
    category: 'collections',
    syntax: 'q.push(val) / q.pop() / q.front()',
    description: 'FIFO operations: add to back, remove from front',
    example: {
      code: 'queue<int> q;\nq.push(1);\nq.push(2);\nint f = q.front(); // 1\nq.pop();',
      output: 'front = 1',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['pop() removes but does not return element'],
    interviewTip: 'Essential for BFS traversal',
    priority: 'essential',
  },

  // ============== PRIORITY_QUEUE ==============
  {
    name: 'priority_queue (max-heap)',
    category: 'collections',
    syntax: 'priority_queue<int> pq;',
    description: 'Max-heap: largest element always on top',
    example: {
      code: 'priority_queue<int> pq;\npq.push(1);\npq.push(3);\npq.push(2);\nint t = pq.top(); // 3',
      output: 'top = 3',
    },
    timeComplexity: 'O(log n) push/pop, O(1) top',
    spaceComplexity: 'O(n)',
    interviewTip: 'Default is max-heap - use greater<int> for min-heap',
    priority: 'essential',
  },
  {
    name: 'priority_queue (min-heap)',
    category: 'collections',
    syntax: 'priority_queue<int, vector<int>, greater<int>> pq;',
    description: 'Min-heap: smallest element always on top',
    example: {
      code: 'priority_queue<int, vector<int>, greater<int>> pq;\npq.push(3);\npq.push(1);\nint t = pq.top(); // 1',
      output: 'top = 1',
    },
    timeComplexity: 'O(log n) push/pop, O(1) top',
    spaceComplexity: 'O(n)',
    gotchas: ['Syntax is verbose - consider using negative values with max-heap'],
    interviewTip: 'Memorize this syntax for interviews',
    priority: 'essential',
  },

  // ============== ITERATION ==============
  {
    name: 'for-each loop',
    category: 'iteration',
    syntax: 'for (auto& x : container)',
    description: 'Range-based for loop over container elements',
    example: {
      code: 'vector<int> v = {1, 2, 3};\nfor (int x : v) cout << x;',
      output: '123',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Use auto& to modify elements, auto for read-only'],
    interviewTip: 'Cleaner than iterator-based loops for simple traversal',
    priority: 'essential',
  },
  {
    name: 'reverse',
    category: 'iteration',
    syntax: 'reverse(begin, end)',
    description: 'Reverses elements in range',
    example: {
      code: 'vector<int> v = {1, 2, 3};\nreverse(v.begin(), v.end());\n// v = {3, 2, 1}',
      output: '{3, 2, 1}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'max_element/min_element',
    category: 'iteration',
    syntax: 'max_element(begin, end) / min_element(begin, end)',
    description: 'Returns iterator to max/min element',
    example: {
      code: 'vector<int> v = {3, 1, 2};\nauto it = max_element(v.begin(), v.end());\n// *it = 3',
      output: '3',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns iterator, not value - dereference with *'],
    priority: 'common',
  },
  {
    name: 'accumulate',
    category: 'iteration',
    syntax: 'accumulate(begin, end, init)',
    description: 'Computes sum (or fold) of range',
    example: {
      code: '#include <numeric>\nvector<int> v = {1, 2, 3};\nint sum = accumulate(v.begin(), v.end(), 0);',
      output: '6',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Include <numeric> header, not <algorithm>'],
    interviewTip: 'Initial value type determines result type',
    priority: 'common',
  },

  // ============== MEMORY ==============
  {
    name: 'swap',
    category: 'memory',
    syntax: 'swap(a, b)',
    description: 'Swaps values of two variables',
    example: {
      code: 'int a = 1, b = 2;\nswap(a, b);\n// a = 2, b = 1',
      output: 'a = 2, b = 1',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Works with any type including containers',
    priority: 'essential',
  },
  {
    name: 'make_pair',
    category: 'memory',
    syntax: 'make_pair(first, second)',
    description: 'Creates a pair object',
    example: {
      code: 'auto p = make_pair(1, "hello");\n// p.first = 1, p.second = "hello"',
      output: '{1, "hello"}',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use {a, b} brace syntax in C++11+ instead',
    priority: 'common',
  },
  {
    name: 'fill',
    category: 'memory',
    syntax: 'fill(begin, end, value)',
    description: 'Fills range with specified value',
    example: {
      code: 'vector<int> v(5);\nfill(v.begin(), v.end(), -1);\n// v = {-1, -1, -1, -1, -1}',
      output: '{-1, -1, -1, -1, -1}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use for initializing arrays with specific values',
    priority: 'common',
  },
];
