import type { CheatsheetEntry } from './types';

export const csharpCheatsheet: CheatsheetEntry[] = [
  // ============================================================
  // List<T> Methods
  // ============================================================
  {
    name: 'List.Add',
    category: 'collections',
    syntax: 'list.Add(item)',
    description: 'Adds an element to the end of the List<T>',
    example: {
      code: 'var list = new List<int> { 1, 2 };\nlist.Add(3);\n// list: [1, 2, 3]',
      output: '[1, 2, 3]',
    },
    timeComplexity: 'O(1) amortized',
    spaceComplexity: 'O(1)',
    gotchas: ['May trigger array resize when capacity exceeded'],
    interviewTip: 'Use List<T> as your default dynamic array in C#',
    priority: 'essential',
  },
  {
    name: 'List.Remove',
    category: 'collections',
    syntax: 'list.Remove(item)',
    description: 'Removes the first occurrence of a specific object from the List<T>',
    example: {
      code: 'var list = new List<int> { 1, 2, 3, 2 };\nlist.Remove(2);\n// list: [1, 3, 2]',
      output: '[1, 3, 2]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Only removes first occurrence', 'Returns false if item not found'],
    priority: 'essential',
  },
  {
    name: 'List.RemoveAt',
    category: 'collections',
    syntax: 'list.RemoveAt(index)',
    description: 'Removes the element at the specified index',
    example: {
      code: 'var list = new List<int> { 1, 2, 3 };\nlist.RemoveAt(1);\n// list: [1, 3]',
      output: '[1, 3]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Throws ArgumentOutOfRangeException if index is invalid'],
    priority: 'essential',
  },
  {
    name: 'List.Insert',
    category: 'collections',
    syntax: 'list.Insert(index, item)',
    description: 'Inserts an element into the List<T> at the specified index',
    example: {
      code: 'var list = new List<int> { 1, 3 };\nlist.Insert(1, 2);\n// list: [1, 2, 3]',
      output: '[1, 2, 3]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Prefer Add() when inserting at the end for O(1) performance',
    priority: 'common',
  },
  {
    name: 'List.Contains',
    category: 'collections',
    syntax: 'list.Contains(item)',
    description: 'Determines whether an element is in the List<T>',
    example: {
      code: 'var list = new List<int> { 1, 2, 3 };\nbool has2 = list.Contains(2); // true',
      output: 'true',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use HashSet<T> for O(1) lookups if you need frequent Contains checks',
    priority: 'essential',
  },
  {
    name: 'List.IndexOf',
    category: 'collections',
    syntax: 'list.IndexOf(item)',
    description: 'Returns the zero-based index of the first occurrence of a value',
    example: {
      code: 'var list = new List<int> { 1, 2, 3, 2 };\nint idx = list.IndexOf(2); // 1',
      output: '1',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns -1 if not found'],
    priority: 'essential',
  },
  {
    name: 'List.Sort',
    category: 'sorting',
    syntax: 'list.Sort() or list.Sort(comparison)',
    description:
      'Sorts the elements in the entire List<T> using the default comparer or a custom comparison',
    example: {
      code: 'var list = new List<int> { 3, 1, 2 };\nlist.Sort();\n// list: [1, 2, 3]',
      output: '[1, 2, 3]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(log n)',
    interviewTip: 'Use custom comparison: list.Sort((a, b) => b - a) for descending',
    priority: 'essential',
  },
  {
    name: 'List.BinarySearch',
    category: 'searching',
    syntax: 'list.BinarySearch(item)',
    description: 'Searches a sorted List<T> for an element using binary search',
    example: {
      code: 'var list = new List<int> { 1, 2, 3, 4, 5 };\nint idx = list.BinarySearch(3); // 2',
      output: '2',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    gotchas: [
      'List must be sorted first',
      'Returns bitwise complement of next larger element index if not found',
    ],
    interviewTip: 'If result < 0, ~result gives insertion point',
    priority: 'common',
  },

  // ============================================================
  // Dictionary<K,V> Methods
  // ============================================================
  {
    name: 'Dictionary.Add',
    category: 'maps',
    syntax: 'dict.Add(key, value) or dict[key] = value',
    description: 'Adds the specified key and value to the dictionary',
    example: {
      code: 'var dict = new Dictionary<string, int>();\ndict.Add("a", 1);\n// or dict["a"] = 1;',
      output: '{"a": 1}',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    gotchas: ['Add() throws if key exists', 'Use indexer dict[key] = value to add or update'],
    priority: 'essential',
  },
  {
    name: 'Dictionary.TryGetValue',
    category: 'maps',
    syntax: 'dict.TryGetValue(key, out value)',
    description:
      'Gets the value associated with the specified key without throwing if key not found',
    example: {
      code: 'var dict = new Dictionary<string, int> { ["a"] = 1 };\nif (dict.TryGetValue("a", out int val)) {\n  // val is 1\n}',
      output: 'val = 1',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Always prefer TryGetValue over ContainsKey + indexer for single lookup',
    priority: 'essential',
  },
  {
    name: 'Dictionary.ContainsKey',
    category: 'maps',
    syntax: 'dict.ContainsKey(key)',
    description: 'Determines whether the dictionary contains the specified key',
    example: {
      code: 'var dict = new Dictionary<string, int> { ["a"] = 1 };\nbool has = dict.ContainsKey("a"); // true',
      output: 'true',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'Dictionary.Remove',
    category: 'maps',
    syntax: 'dict.Remove(key)',
    description: 'Removes the value with the specified key from the dictionary',
    example: {
      code: 'var dict = new Dictionary<string, int> { ["a"] = 1 };\ndict.Remove("a");',
      output: '{}',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns false if key not found'],
    priority: 'essential',
  },
  {
    name: 'Dictionary.Keys/Values',
    category: 'maps',
    syntax: 'dict.Keys or dict.Values',
    description: 'Gets a collection containing the keys or values in the dictionary',
    example: {
      code: 'var dict = new Dictionary<string, int> { ["a"] = 1, ["b"] = 2 };\nvar keys = dict.Keys; // ["a", "b"]',
      output: '["a", "b"]',
    },
    timeComplexity: 'O(1) to get collection, O(n) to iterate',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },

  // ============================================================
  // HashSet<T> Methods
  // ============================================================
  {
    name: 'HashSet.Add',
    category: 'sets',
    syntax: 'set.Add(item)',
    description: 'Adds the specified element to a HashSet<T>',
    example: {
      code: 'var set = new HashSet<int>();\nset.Add(1);\nbool added = set.Add(1); // false (duplicate)',
      output: 'false',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns false if element already exists'],
    interviewTip: 'Use HashSet for O(1) membership testing and duplicate removal',
    priority: 'essential',
  },
  {
    name: 'HashSet.Contains',
    category: 'sets',
    syntax: 'set.Contains(item)',
    description: 'Determines whether a HashSet<T> contains the specified element',
    example: {
      code: 'var set = new HashSet<int> { 1, 2, 3 };\nbool has = set.Contains(2); // true',
      output: 'true',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Perfect for checking visited nodes or detecting duplicates',
    priority: 'essential',
  },
  {
    name: 'HashSet.Remove',
    category: 'sets',
    syntax: 'set.Remove(item)',
    description: 'Removes the specified element from a HashSet<T>',
    example: {
      code: 'var set = new HashSet<int> { 1, 2, 3 };\nset.Remove(2);\n// set: {1, 3}',
      output: '{1, 3}',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'HashSet.UnionWith',
    category: 'sets',
    syntax: 'set.UnionWith(other)',
    description:
      'Modifies the current set to contain all elements present in itself and the specified collection',
    example: {
      code: 'var set = new HashSet<int> { 1, 2 };\nset.UnionWith(new[] { 2, 3 });\n// set: {1, 2, 3}',
      output: '{1, 2, 3}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },
  {
    name: 'HashSet.IntersectWith',
    category: 'sets',
    syntax: 'set.IntersectWith(other)',
    description:
      'Modifies the current set to contain only elements present in both itself and the specified collection',
    example: {
      code: 'var set = new HashSet<int> { 1, 2, 3 };\nset.IntersectWith(new[] { 2, 3, 4 });\n// set: {2, 3}',
      output: '{2, 3}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },

  // ============================================================
  // String Methods
  // ============================================================
  {
    name: 'String.Substring',
    category: 'strings',
    syntax: 'str.Substring(startIndex, length)',
    description: 'Retrieves a substring from this instance',
    example: {
      code: 'string s = "hello";\nstring sub = s.Substring(1, 3); // "ell"',
      output: '"ell"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: [
      'Throws if startIndex or length is out of range',
      'Use Range syntax s[1..4] in C# 8+',
    ],
    priority: 'essential',
  },
  {
    name: 'String.Split',
    category: 'strings',
    syntax: 'str.Split(separator)',
    description: 'Splits a string into substrings based on specified delimiter',
    example: {
      code: 'string s = "a,b,c";\nstring[] parts = s.Split(\',\'); // ["a", "b", "c"]',
      output: '["a", "b", "c"]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Use StringSplitOptions.RemoveEmptyEntries to filter empty strings',
    priority: 'essential',
  },
  {
    name: 'String.Join',
    category: 'strings',
    syntax: 'string.Join(separator, values)',
    description: 'Concatenates elements of a collection using the specified separator',
    example: {
      code: 'string[] arr = { "a", "b", "c" };\nstring s = string.Join(",", arr); // "a,b,c"',
      output: '"a,b,c"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'essential',
  },
  {
    name: 'String.ToCharArray',
    category: 'strings',
    syntax: 'str.ToCharArray()',
    description: 'Copies characters in this string to a character array',
    example: {
      code: "string s = \"abc\";\nchar[] chars = s.ToCharArray(); // ['a', 'b', 'c']",
      output: "['a', 'b', 'c']",
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip:
      'Useful since strings are immutable - convert to char[] for in-place modifications',
    priority: 'essential',
  },
  {
    name: 'String.Contains',
    category: 'strings',
    syntax: 'str.Contains(value)',
    description: 'Returns whether the specified substring occurs within this string',
    example: {
      code: 'string s = "hello world";\nbool has = s.Contains("world"); // true',
      output: 'true',
    },
    timeComplexity: 'O(n*m)',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'String.IndexOf',
    category: 'strings',
    syntax: 'str.IndexOf(value)',
    description: 'Returns the zero-based index of the first occurrence of specified value',
    example: {
      code: 'string s = "hello";\nint idx = s.IndexOf(\'l\'); // 2',
      output: '2',
    },
    timeComplexity: 'O(n*m)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns -1 if not found'],
    priority: 'essential',
  },
  {
    name: 'String.Replace',
    category: 'strings',
    syntax: 'str.Replace(oldValue, newValue)',
    description: 'Returns a new string with all occurrences of a specified value replaced',
    example: {
      code: 'string s = "hello";\nstring r = s.Replace(\'l\', \'x\'); // "hexxo"',
      output: '"hexxo"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Strings are immutable - returns new string'],
    priority: 'essential',
  },
  {
    name: 'String.ToLower/ToUpper',
    category: 'strings',
    syntax: 'str.ToLower() or str.ToUpper()',
    description: 'Returns a copy of this string converted to lowercase or uppercase',
    example: {
      code: 'string s = "Hello";\nstring lower = s.ToLower(); // "hello"',
      output: '"hello"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Use for case-insensitive comparisons in interview problems',
    priority: 'common',
  },
  {
    name: 'StringBuilder',
    category: 'strings',
    syntax: 'new StringBuilder().Append(str)',
    description: 'Mutable string builder for efficient string concatenation',
    example: {
      code: 'var sb = new StringBuilder();\nsb.Append("hello");\nsb.Append(" world");\nstring s = sb.ToString(); // "hello world"',
      output: '"hello world"',
    },
    timeComplexity: 'O(1) amortized per Append',
    spaceComplexity: 'O(n)',
    interviewTip: 'Always use StringBuilder when concatenating strings in a loop',
    priority: 'essential',
  },

  // ============================================================
  // Array Methods
  // ============================================================
  {
    name: 'Array.Sort',
    category: 'sorting',
    syntax: 'Array.Sort(array)',
    description: 'Sorts the elements in an entire array using the default comparer',
    example: {
      code: 'int[] arr = { 3, 1, 2 };\nArray.Sort(arr);\n// arr: [1, 2, 3]',
      output: '[1, 2, 3]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(log n)',
    interviewTip: 'Use Array.Sort(arr, (a, b) => b - a) for descending order',
    priority: 'essential',
  },
  {
    name: 'Array.Reverse',
    category: 'arrays',
    syntax: 'Array.Reverse(array)',
    description: 'Reverses the sequence of elements in the entire array',
    example: {
      code: 'int[] arr = { 1, 2, 3 };\nArray.Reverse(arr);\n// arr: [3, 2, 1]',
      output: '[3, 2, 1]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },
  {
    name: 'Array.BinarySearch',
    category: 'searching',
    syntax: 'Array.BinarySearch(array, value)',
    description: 'Searches a sorted array for a value using binary search',
    example: {
      code: 'int[] arr = { 1, 2, 3, 4, 5 };\nint idx = Array.BinarySearch(arr, 3); // 2',
      output: '2',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Array must be sorted', 'Returns bitwise complement if not found'],
    priority: 'common',
  },
  {
    name: 'Array.Fill',
    category: 'arrays',
    syntax: 'Array.Fill(array, value)',
    description: 'Fills an array with the specified value',
    example: {
      code: 'int[] arr = new int[3];\nArray.Fill(arr, 5);\n// arr: [5, 5, 5]',
      output: '[5, 5, 5]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },

  // ============================================================
  // LINQ Methods
  // ============================================================
  {
    name: 'Where',
    category: 'functional',
    syntax: 'collection.Where(predicate)',
    description: 'Filters a sequence of values based on a predicate',
    example: {
      code: 'int[] arr = { 1, 2, 3, 4 };\nvar evens = arr.Where(x => x % 2 == 0).ToList(); // [2, 4]',
      output: '[2, 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1) deferred, O(n) when materialized',
    interviewTip: 'LINQ uses deferred execution - call ToList() or ToArray() to materialize',
    priority: 'essential',
  },
  {
    name: 'Select',
    category: 'functional',
    syntax: 'collection.Select(selector)',
    description: 'Projects each element of a sequence into a new form',
    example: {
      code: 'int[] arr = { 1, 2, 3 };\nvar doubled = arr.Select(x => x * 2).ToList(); // [2, 4, 6]',
      output: '[2, 4, 6]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1) deferred, O(n) when materialized',
    interviewTip: 'Equivalent to map() in other languages',
    priority: 'essential',
  },
  {
    name: 'Aggregate',
    category: 'functional',
    syntax: 'collection.Aggregate(seed, func)',
    description: 'Applies an accumulator function over a sequence',
    example: {
      code: 'int[] arr = { 1, 2, 3, 4 };\nint sum = arr.Aggregate(0, (acc, x) => acc + x); // 10',
      output: '10',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Equivalent to reduce() in other languages',
    priority: 'essential',
  },
  {
    name: 'OrderBy/OrderByDescending',
    category: 'sorting',
    syntax: 'collection.OrderBy(keySelector)',
    description: 'Sorts the elements of a sequence in ascending or descending order',
    example: {
      code: 'int[] arr = { 3, 1, 2 };\nvar sorted = arr.OrderBy(x => x).ToList(); // [1, 2, 3]',
      output: '[1, 2, 3]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Chain with ThenBy() for secondary sorting',
    priority: 'essential',
  },
  {
    name: 'GroupBy',
    category: 'functional',
    syntax: 'collection.GroupBy(keySelector)',
    description: 'Groups the elements of a sequence according to a specified key selector',
    example: {
      code: 'string[] words = { "apple", "ant", "bee" };\nvar groups = words.GroupBy(w => w[0]);\n// Groups: a -> [apple, ant], b -> [bee]',
      output: "{'a': ['apple', 'ant'], 'b': ['bee']}",
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Great for frequency counting and categorization problems',
    priority: 'essential',
  },
  {
    name: 'First/FirstOrDefault',
    category: 'functional',
    syntax: 'collection.First() or collection.FirstOrDefault()',
    description:
      'Returns the first element of a sequence, or a default value if no element is found',
    example: {
      code: 'int[] arr = { 1, 2, 3 };\nint first = arr.First(); // 1\nint[] empty = { };\nint def = empty.FirstOrDefault(); // 0',
      output: '1',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['First() throws if sequence is empty', 'Use FirstOrDefault() to avoid exception'],
    priority: 'essential',
  },
  {
    name: 'Any/All',
    category: 'functional',
    syntax: 'collection.Any(predicate) or collection.All(predicate)',
    description: 'Determines whether any or all elements satisfy a condition',
    example: {
      code: 'int[] arr = { 1, 2, 3 };\nbool hasEven = arr.Any(x => x % 2 == 0); // true\nbool allPositive = arr.All(x => x > 0); // true',
      output: 'true, true',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Any() without predicate checks if collection is non-empty',
    priority: 'essential',
  },
  {
    name: 'Count',
    category: 'functional',
    syntax: 'collection.Count() or collection.Count(predicate)',
    description: 'Returns the number of elements in a sequence, optionally filtered by predicate',
    example: {
      code: 'int[] arr = { 1, 2, 3, 4 };\nint total = arr.Count(); // 4\nint evens = arr.Count(x => x % 2 == 0); // 2',
      output: '4, 2',
    },
    timeComplexity: 'O(1) for ICollection, O(n) otherwise',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'Sum/Max/Min/Average',
    category: 'functional',
    syntax: 'collection.Sum() or collection.Max() or collection.Min()',
    description: 'Computes the sum, maximum, minimum, or average of a sequence of numeric values',
    example: {
      code: 'int[] arr = { 1, 2, 3, 4 };\nint sum = arr.Sum(); // 10\nint max = arr.Max(); // 4',
      output: '10, 4',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Throws InvalidOperationException on empty sequence (use nullable overloads)'],
    priority: 'essential',
  },
  {
    name: 'Distinct',
    category: 'functional',
    syntax: 'collection.Distinct()',
    description: 'Returns distinct elements from a sequence',
    example: {
      code: 'int[] arr = { 1, 2, 2, 3, 3, 3 };\nvar unique = arr.Distinct().ToList(); // [1, 2, 3]',
      output: '[1, 2, 3]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Quick way to remove duplicates from a sequence',
    priority: 'common',
  },
  {
    name: 'Take/Skip',
    category: 'functional',
    syntax: 'collection.Take(count) or collection.Skip(count)',
    description: 'Returns a specified number of elements from the start or skips them',
    example: {
      code: 'int[] arr = { 1, 2, 3, 4, 5 };\nvar first3 = arr.Take(3).ToList(); // [1, 2, 3]\nvar skip2 = arr.Skip(2).ToList(); // [3, 4, 5]',
      output: '[1, 2, 3], [3, 4, 5]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1) deferred',
    interviewTip: 'Useful for pagination and sliding window problems',
    priority: 'common',
  },
  {
    name: 'SelectMany',
    category: 'functional',
    syntax: 'collection.SelectMany(selector)',
    description:
      'Projects each element to a sequence and flattens the resulting sequences into one',
    example: {
      code: 'var lists = new List<List<int>> { new() { 1, 2 }, new() { 3, 4 } };\nvar flat = lists.SelectMany(x => x).ToList(); // [1, 2, 3, 4]',
      output: '[1, 2, 3, 4]',
    },
    timeComplexity: 'O(n*m)',
    spaceComplexity: 'O(1) deferred',
    interviewTip: 'Equivalent to flatMap in other languages',
    priority: 'common',
  },
  {
    name: 'ToDictionary',
    category: 'functional',
    syntax: 'collection.ToDictionary(keySelector, valueSelector)',
    description:
      'Creates a Dictionary from a sequence according to specified key and value selectors',
    example: {
      code: 'string[] arr = { "apple", "bee" };\nvar dict = arr.ToDictionary(s => s[0], s => s);\n// {\'a\': "apple", \'b\': "bee"}',
      output: "{a: 'apple', b: 'bee'}",
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Throws on duplicate keys'],
    priority: 'common',
  },
  {
    name: 'ToHashSet',
    category: 'functional',
    syntax: 'collection.ToHashSet()',
    description: 'Creates a HashSet from a sequence',
    example: {
      code: 'int[] arr = { 1, 2, 2, 3 };\nvar set = arr.ToHashSet(); // {1, 2, 3}',
      output: '{1, 2, 3}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Quick way to convert array to set for O(1) lookups',
    priority: 'common',
  },

  // ============================================================
  // Other Useful Methods
  // ============================================================
  {
    name: 'Math.Max/Min',
    category: 'math',
    syntax: 'Math.Max(a, b) or Math.Min(a, b)',
    description: 'Returns the larger or smaller of two numbers',
    example: {
      code: 'int max = Math.Max(3, 7); // 7\nint min = Math.Min(3, 7); // 3',
      output: '7, 3',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Only compares two values at a time - use LINQ Max/Min for collections'],
    priority: 'essential',
  },
  {
    name: 'Math.Abs',
    category: 'math',
    syntax: 'Math.Abs(value)',
    description: 'Returns the absolute value of a number',
    example: {
      code: 'int abs = Math.Abs(-5); // 5',
      output: '5',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },
  {
    name: 'int.Parse/TryParse',
    category: 'type-conversion',
    syntax: 'int.Parse(str) or int.TryParse(str, out result)',
    description: 'Converts string representation of a number to an integer',
    example: {
      code: 'int n = int.Parse("123"); // 123\nif (int.TryParse("456", out int val)) {\n  // val is 456\n}',
      output: '123, 456',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Parse throws on invalid input', 'TryParse returns false on invalid input'],
    interviewTip: 'Use TryParse to avoid exceptions with user input',
    priority: 'common',
  },
  {
    name: 'char.IsLetter/IsDigit',
    category: 'strings',
    syntax: 'char.IsLetter(c) or char.IsDigit(c)',
    description: 'Indicates whether a character is a letter or digit',
    example: {
      code: "bool isLetter = char.IsLetter('a'); // true\nbool isDigit = char.IsDigit('5'); // true",
      output: 'true, true',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Essential for parsing and validation problems',
    priority: 'common',
  },
];
