/**
 * Dart Cheatsheet
 *
 * Essential Dart methods and operations for coding interviews.
 * Covers List, String, Map, Set, and common functional patterns.
 */

import type { CheatsheetEntry } from './types';

export const dartCheatsheet: CheatsheetEntry[] = [
  // ============ LIST (ARRAYS) METHODS ============
  {
    name: 'add',
    category: 'arrays',
    syntax: 'list.add(element)',
    description: 'Adds an element to the end of the list',
    example: {
      code: 'var nums = [1, 2, 3];\nnums.add(4);\nprint(nums);',
      output: '[1, 2, 3, 4]',
    },
    timeComplexity: 'O(1) amortized',
    spaceComplexity: 'O(1)',
    gotchas: ['Modifies the original list', 'Throws if list is fixed-length'],
    priority: 'essential',
  },
  {
    name: 'addAll',
    category: 'arrays',
    syntax: 'list.addAll(iterable)',
    description: 'Adds all elements from an iterable to the end of the list',
    example: {
      code: 'var nums = [1, 2];\nnums.addAll([3, 4, 5]);\nprint(nums);',
      output: '[1, 2, 3, 4, 5]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'insert',
    category: 'arrays',
    syntax: 'list.insert(index, element)',
    description: 'Inserts an element at the specified index',
    example: {
      code: 'var nums = [1, 3, 4];\nnums.insert(1, 2);\nprint(nums);',
      output: '[1, 2, 3, 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Shifts all elements after index'],
    priority: 'common',
  },
  {
    name: 'remove',
    category: 'arrays',
    syntax: 'list.remove(element)',
    description: 'Removes the first occurrence of an element',
    example: {
      code: 'var nums = [1, 2, 3, 2];\nnums.remove(2);\nprint(nums);',
      output: '[1, 3, 2]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns bool indicating if element was found', 'Only removes first occurrence'],
    priority: 'essential',
  },
  {
    name: 'removeAt',
    category: 'arrays',
    syntax: 'list.removeAt(index)',
    description: 'Removes and returns the element at the specified index',
    example: {
      code: "var nums = [1, 2, 3];\nvar removed = nums.removeAt(1);\nprint('$removed, $nums');",
      output: '2, [1, 3]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'removeLast',
    category: 'arrays',
    syntax: 'list.removeLast()',
    description: 'Removes and returns the last element',
    example: {
      code: "var nums = [1, 2, 3];\nvar last = nums.removeLast();\nprint('$last, $nums');",
      output: '3, [1, 2]',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Throws StateError on empty list'],
    interviewTip: 'Useful for stack-like operations',
    priority: 'essential',
  },
  {
    name: 'removeWhere',
    category: 'arrays',
    syntax: 'list.removeWhere((e) => condition)',
    description: 'Removes all elements matching a condition',
    example: {
      code: 'var nums = [1, 2, 3, 4, 5];\nnums.removeWhere((n) => n % 2 == 0);\nprint(nums);',
      output: '[1, 3, 5]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },
  {
    name: 'indexOf',
    category: 'arrays',
    syntax: 'list.indexOf(element, [start])',
    description: 'Returns the first index of element, or -1 if not found',
    example: {
      code: 'var nums = [1, 2, 3, 2];\nprint(nums.indexOf(2));',
      output: '1',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use for linear search in unsorted lists',
    priority: 'essential',
  },
  {
    name: 'contains',
    category: 'arrays',
    syntax: 'list.contains(element)',
    description: 'Returns true if the list contains the element',
    example: {
      code: 'var nums = [1, 2, 3];\nprint(nums.contains(2));',
      output: 'true',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'For frequent lookups, consider using a Set instead',
    priority: 'essential',
  },
  {
    name: 'sublist',
    category: 'arrays',
    syntax: 'list.sublist(start, [end])',
    description: 'Returns a new list from start to end (exclusive)',
    example: {
      code: 'var nums = [1, 2, 3, 4, 5];\nprint(nums.sublist(1, 4));',
      output: '[2, 3, 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns a new list, does not modify original'],
    priority: 'essential',
  },
  {
    name: 'reversed',
    category: 'arrays',
    syntax: 'list.reversed',
    description: 'Returns an iterable of elements in reverse order',
    example: {
      code: 'var nums = [1, 2, 3];\nprint(nums.reversed.toList());',
      output: '[3, 2, 1]',
    },
    timeComplexity: 'O(1) for iterable, O(n) for toList()',
    spaceComplexity: 'O(1) lazy, O(n) for toList()',
    gotchas: ['Returns Iterable, not List - call toList() if needed'],
    priority: 'essential',
  },
  {
    name: 'sort',
    category: 'sorting',
    syntax: 'list.sort([compare])',
    description: 'Sorts the list in-place using optional comparator',
    example: {
      code: 'var nums = [3, 1, 4, 1, 5];\nnums.sort();\nprint(nums);\nnums.sort((a, b) => b - a);\nprint(nums);',
      output: '[1, 1, 3, 4, 5]\n[5, 4, 3, 1, 1]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(log n)',
    gotchas: ['Modifies original list', 'Default sort is ascending'],
    interviewTip: 'Custom comparators are essential for complex sorting',
    priority: 'essential',
  },
  {
    name: 'shuffle',
    category: 'arrays',
    syntax: 'list.shuffle([random])',
    description: 'Randomly shuffles the elements in-place',
    example: {
      code: 'var nums = [1, 2, 3, 4, 5];\nnums.shuffle();\nprint(nums);',
      output: '[3, 1, 5, 2, 4] // random order',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Implements Fisher-Yates shuffle',
    priority: 'useful',
  },
  {
    name: 'first / last',
    category: 'arrays',
    syntax: 'list.first / list.last',
    description: 'Gets the first or last element of the list',
    example: {
      code: 'var nums = [1, 2, 3];\nprint(nums.first); // 1\nprint(nums.last);  // 3',
      output: '1, 3',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Throws StateError on empty list', 'Use firstOrNull/lastOrNull for safe access'],
    priority: 'essential',
  },
  {
    name: 'isEmpty / isNotEmpty',
    category: 'arrays',
    syntax: 'list.isEmpty / list.isNotEmpty',
    description: 'Checks if the list has no elements or has elements',
    example: {
      code: 'var nums = <int>[];\nprint(nums.isEmpty);    // true\nprint(nums.isNotEmpty); // false',
      output: 'true, false',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Prefer isEmpty over length == 0',
    priority: 'essential',
  },
  {
    name: 'length',
    category: 'arrays',
    syntax: 'list.length',
    description: 'Returns the number of elements in the list',
    example: {
      code: 'var nums = [1, 2, 3, 4, 5];\nprint(nums.length);',
      output: '5',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'List.filled',
    category: 'arrays',
    syntax: 'List.filled(length, fill, {growable: true})',
    description: 'Creates a list of given length filled with a value',
    example: {
      code: 'var zeros = List.filled(5, 0);\nprint(zeros);',
      output: '[0, 0, 0, 0, 0]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['For objects, all elements reference the same instance'],
    interviewTip: 'Use List.generate for unique objects per element',
    priority: 'essential',
  },
  {
    name: 'List.generate',
    category: 'arrays',
    syntax: 'List.generate(length, (index) => value)',
    description: 'Creates a list by calling generator for each index',
    example: {
      code: 'var squares = List.generate(5, (i) => i * i);\nprint(squares);',
      output: '[0, 1, 4, 9, 16]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Perfect for creating 2D arrays: List.generate(n, (_) => List.filled(m, 0))',
    priority: 'essential',
  },

  // ============ FUNCTIONAL METHODS ============
  {
    name: 'map',
    category: 'functional',
    syntax: 'iterable.map((e) => transform)',
    description: 'Transforms each element and returns a lazy iterable',
    example: {
      code: 'var nums = [1, 2, 3];\nvar doubled = nums.map((n) => n * 2).toList();\nprint(doubled);',
      output: '[2, 4, 6]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1) lazy, O(n) for toList()',
    gotchas: ['Returns Iterable, not List', 'Lazy - not computed until iterated'],
    interviewTip: 'Chain with toList() when you need a List result',
    priority: 'essential',
  },
  {
    name: 'where',
    category: 'functional',
    syntax: 'iterable.where((e) => condition)',
    description: 'Filters elements matching a condition (like filter)',
    example: {
      code: 'var nums = [1, 2, 3, 4, 5];\nvar evens = nums.where((n) => n % 2 == 0).toList();\nprint(evens);',
      output: '[2, 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1) lazy, O(n) for toList()',
    gotchas: ['Lazy evaluation', 'Returns Iterable'],
    interviewTip: "Dart's equivalent of filter() in other languages",
    priority: 'essential',
  },
  {
    name: 'fold',
    category: 'functional',
    syntax: 'iterable.fold(initial, (acc, e) => combine)',
    description: 'Reduces elements to a single value with initial value',
    example: {
      code: 'var nums = [1, 2, 3, 4];\nvar sum = nums.fold(0, (acc, n) => acc + n);\nprint(sum);',
      output: '10',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'More flexible than reduce() - specify initial value and return type',
    priority: 'essential',
  },
  {
    name: 'reduce',
    category: 'functional',
    syntax: 'iterable.reduce((acc, e) => combine)',
    description: 'Reduces elements using first element as initial value',
    example: {
      code: 'var nums = [1, 2, 3, 4];\nvar product = nums.reduce((acc, n) => acc * n);\nprint(product);',
      output: '24',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Throws StateError on empty iterable', 'Return type must match element type'],
    priority: 'essential',
  },
  {
    name: 'expand',
    category: 'functional',
    syntax: 'iterable.expand((e) => iterable)',
    description: 'Flattens nested iterables (flatMap equivalent)',
    example: {
      code: 'var nested = [[1, 2], [3, 4]];\nvar flat = nested.expand((list) => list).toList();\nprint(flat);',
      output: '[1, 2, 3, 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1) lazy',
    interviewTip: 'Use for flattening nested structures or one-to-many transformations',
    priority: 'common',
  },
  {
    name: 'every',
    category: 'functional',
    syntax: 'iterable.every((e) => condition)',
    description: 'Returns true if all elements satisfy the condition',
    example: {
      code: 'var nums = [2, 4, 6];\nprint(nums.every((n) => n % 2 == 0));',
      output: 'true',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Short-circuits on first false'],
    priority: 'common',
  },
  {
    name: 'any',
    category: 'functional',
    syntax: 'iterable.any((e) => condition)',
    description: 'Returns true if any element satisfies the condition',
    example: {
      code: 'var nums = [1, 2, 3];\nprint(nums.any((n) => n > 2));',
      output: 'true',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Short-circuits on first true'],
    priority: 'common',
  },
  {
    name: 'firstWhere',
    category: 'functional',
    syntax: 'iterable.firstWhere((e) => condition, {orElse: () => default})',
    description: 'Returns first element matching condition',
    example: {
      code: 'var nums = [1, 2, 3, 4];\nvar first = nums.firstWhere((n) => n > 2);\nprint(first);',
      output: '3',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Throws StateError if not found and no orElse provided'],
    interviewTip: 'Always provide orElse for safe lookups',
    priority: 'essential',
  },
  {
    name: 'take / skip',
    category: 'functional',
    syntax: 'iterable.take(n) / iterable.skip(n)',
    description: 'Takes first n elements or skips first n elements',
    example: {
      code: 'var nums = [1, 2, 3, 4, 5];\nprint(nums.take(3).toList());\nprint(nums.skip(2).toList());',
      output: '[1, 2, 3]\n[3, 4, 5]',
    },
    timeComplexity: 'O(1) lazy',
    spaceComplexity: 'O(1)',
    interviewTip: 'Useful for pagination or limiting results',
    priority: 'common',
  },
  {
    name: 'takeWhile / skipWhile',
    category: 'functional',
    syntax: 'iterable.takeWhile((e) => cond) / skipWhile((e) => cond)',
    description: 'Takes/skips elements while condition is true',
    example: {
      code: 'var nums = [1, 2, 3, 4, 1];\nprint(nums.takeWhile((n) => n < 4).toList());',
      output: '[1, 2, 3]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1) lazy',
    priority: 'useful',
  },

  // ============ STRING METHODS ============
  {
    name: 'split',
    category: 'strings',
    syntax: 'str.split(pattern)',
    description: 'Splits string by pattern into a list of substrings',
    example: {
      code: "var s = 'a,b,c';\nprint(s.split(','));",
      output: '[a, b, c]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: "split('') gives individual characters",
    priority: 'essential',
  },
  {
    name: 'substring',
    category: 'strings',
    syntax: 'str.substring(start, [end])',
    description: 'Returns substring from start to end (exclusive)',
    example: {
      code: "var s = 'hello world';\nprint(s.substring(0, 5));",
      output: 'hello',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Throws RangeError if indices are out of bounds'],
    priority: 'essential',
  },
  {
    name: 'contains',
    category: 'strings',
    syntax: 'str.contains(pattern)',
    description: 'Returns true if string contains the pattern',
    example: {
      code: "var s = 'hello world';\nprint(s.contains('world'));",
      output: 'true',
    },
    timeComplexity: 'O(n*m)',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'startsWith / endsWith',
    category: 'strings',
    syntax: 'str.startsWith(prefix) / str.endsWith(suffix)',
    description: 'Checks if string starts or ends with given pattern',
    example: {
      code: "var s = 'hello world';\nprint(s.startsWith('hello')); // true\nprint(s.endsWith('world'));   // true",
      output: 'true, true',
    },
    timeComplexity: 'O(m) where m is pattern length',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'indexOf / lastIndexOf',
    category: 'strings',
    syntax: 'str.indexOf(pattern) / str.lastIndexOf(pattern)',
    description: 'Returns index of first/last occurrence, or -1',
    example: {
      code: "var s = 'abcabc';\nprint(s.indexOf('b'));     // 1\nprint(s.lastIndexOf('b')); // 4",
      output: '1, 4',
    },
    timeComplexity: 'O(n*m)',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'replaceAll / replaceFirst',
    category: 'strings',
    syntax: 'str.replaceAll(from, to)',
    description: 'Replaces all or first occurrence of pattern',
    example: {
      code: "var s = 'aaa';\nprint(s.replaceAll('a', 'b'));\nprint(s.replaceFirst('a', 'b'));",
      output: 'bbb\nbaa',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns new string, original is unchanged'],
    priority: 'essential',
  },
  {
    name: 'trim / trimLeft / trimRight',
    category: 'strings',
    syntax: 'str.trim()',
    description: 'Removes leading and/or trailing whitespace',
    example: {
      code: "var s = '  hello  ';\nprint(s.trim()); // 'hello'",
      output: '[hello]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'essential',
  },
  {
    name: 'toUpperCase / toLowerCase',
    category: 'strings',
    syntax: 'str.toUpperCase() / str.toLowerCase()',
    description: 'Converts string to upper or lower case',
    example: {
      code: "var s = 'Hello World';\nprint(s.toLowerCase());",
      output: 'hello world',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'essential',
  },
  {
    name: 'padLeft / padRight',
    category: 'strings',
    syntax: 'str.padLeft(width, [padding])',
    description: 'Pads string to specified width',
    example: {
      code: "var s = '42';\nprint(s.padLeft(5, '0'));",
      output: '00042',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Useful for formatting numbers or alignment',
    priority: 'common',
  },
  {
    name: 'codeUnits / codeUnitAt',
    category: 'strings',
    syntax: 'str.codeUnits / str.codeUnitAt(index)',
    description: 'Gets UTF-16 code units of string or at index',
    example: {
      code: "var s = 'abc';\nprint(s.codeUnitAt(0));\nprint(s.codeUnits);",
      output: '97\n[97, 98, 99]',
    },
    timeComplexity: 'O(1) for codeUnitAt, O(n) for codeUnits',
    spaceComplexity: 'O(1) / O(n)',
    interviewTip: 'Use for character arithmetic: codeUnitAt(i) - 97 for a-z to 0-25',
    priority: 'common',
  },
  {
    name: 'String.fromCharCode',
    category: 'strings',
    syntax: 'String.fromCharCode(code)',
    description: 'Creates a string from a character code',
    example: {
      code: 'print(String.fromCharCode(97));',
      output: 'a',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Pair with codeUnitAt for character manipulation',
    priority: 'common',
  },

  // ============ MAP METHODS ============
  {
    name: 'Map literal / Map()',
    category: 'maps',
    syntax: "var map = {'key': value} / Map<K, V>()",
    description: 'Creates a new map (hash map by default)',
    example: {
      code: "var map = {'a': 1, 'b': 2};\nprint(map);",
      output: '{a: 1, b: 2}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'essential',
  },
  {
    name: 'putIfAbsent',
    category: 'maps',
    syntax: 'map.putIfAbsent(key, () => value)',
    description: 'Adds key-value only if key is not present',
    example: {
      code: "var map = {'a': 1};\nmap.putIfAbsent('b', () => 2);\nmap.putIfAbsent('a', () => 99);\nprint(map);",
      output: '{a: 1, b: 2}',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Essential for frequency counting: map.putIfAbsent(k, () => 0); map[k]!++;',
    priority: 'essential',
  },
  {
    name: 'update',
    category: 'maps',
    syntax: 'map.update(key, (v) => newV, {ifAbsent: () => default})',
    description: 'Updates value for key using update function',
    example: {
      code: "var map = {'a': 1};\nmap.update('a', (v) => v + 1);\nmap.update('b', (v) => v + 1, ifAbsent: () => 0);\nprint(map);",
      output: '{a: 2, b: 0}',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Clean way to increment counters',
    priority: 'essential',
  },
  {
    name: 'containsKey / containsValue',
    category: 'maps',
    syntax: 'map.containsKey(key) / map.containsValue(value)',
    description: 'Checks if map contains key or value',
    example: {
      code: "var map = {'a': 1, 'b': 2};\nprint(map.containsKey('a'));",
      output: 'true',
    },
    timeComplexity: 'O(1) for key, O(n) for value',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'keys / values / entries',
    category: 'maps',
    syntax: 'map.keys / map.values / map.entries',
    description: 'Gets iterables of keys, values, or key-value pairs',
    example: {
      code: "var map = {'a': 1, 'b': 2};\nprint(map.keys.toList()); // [a, b]\nprint(map.entries.toList()); // [MapEntry(a: 1), MapEntry(b: 2)]",
      output: '[a, b]\n[a:1, b:2]',
    },
    timeComplexity: 'O(1) for property, O(n) for iteration',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'forEach (Map)',
    category: 'maps',
    syntax: 'map.forEach((key, value) => action)',
    description: 'Executes function for each key-value pair',
    example: {
      code: "var map = {'a': 1, 'b': 2};\nmap.forEach((k, v) => print('$k: $v'));",
      output: 'a: 1\nb: 2',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },
  {
    name: 'remove (Map)',
    category: 'maps',
    syntax: 'map.remove(key)',
    description: 'Removes key and returns its value, or null',
    example: {
      code: "var map = {'a': 1, 'b': 2};\nvar val = map.remove('a');\nprint('$val, $map');",
      output: '1, {b: 2}',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },

  // ============ SET METHODS ============
  {
    name: 'Set literal / Set()',
    category: 'sets',
    syntax: 'var set = {1, 2, 3} / Set<T>()',
    description: 'Creates a new set (hash set by default)',
    example: {
      code: 'var set = {1, 2, 3, 2};\nprint(set);',
      output: '{1, 2, 3}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Empty {} creates Map, use <int>{} for empty Set'],
    priority: 'essential',
  },
  {
    name: 'add / remove (Set)',
    category: 'sets',
    syntax: 'set.add(element) / set.remove(element)',
    description: 'Adds or removes an element from set',
    example: {
      code: 'var set = {1, 2};\nset.add(3);\nset.remove(1);\nprint(set);',
      output: '{2, 3}',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    gotchas: ['add returns bool indicating if element was new'],
    priority: 'essential',
  },
  {
    name: 'union / intersection / difference',
    category: 'sets',
    syntax: 'set1.union(set2) / set1.intersection(set2) / set1.difference(set2)',
    description: 'Set operations returning new sets',
    example: {
      code: 'var a = {1, 2, 3};\nvar b = {2, 3, 4};\nprint(a.intersection(b));\nprint(a.difference(b));',
      output: '{2, 3}\n{1}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Perfect for finding common elements or unique elements',
    priority: 'essential',
  },
  {
    name: 'toSet',
    category: 'sets',
    syntax: 'iterable.toSet()',
    description: 'Converts any iterable to a Set, removing duplicates',
    example: {
      code: 'var list = [1, 2, 2, 3, 3, 3];\nprint(list.toSet());',
      output: '{1, 2, 3}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Quick way to find unique elements',
    priority: 'essential',
  },

  // ============ ITERATION ============
  {
    name: 'for-in loop',
    category: 'iteration',
    syntax: 'for (var item in iterable) { ... }',
    description: 'Iterates over elements of any iterable',
    example: {
      code: 'for (var n in [1, 2, 3]) {\n  print(n);\n}',
      output: '1\n2\n3',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'forEach',
    category: 'iteration',
    syntax: 'iterable.forEach((e) => action)',
    description: 'Executes function for each element',
    example: {
      code: '[1, 2, 3].forEach((n) => print(n * 2));',
      output: '2\n4\n6',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Cannot use break/continue', 'Cannot be async'],
    priority: 'common',
  },
  {
    name: 'asMap',
    category: 'iteration',
    syntax: 'list.asMap()',
    description: 'Returns map with indices as keys',
    example: {
      code: "var list = ['a', 'b', 'c'];\nlist.asMap().forEach((i, v) => print('$i: $v'));",
      output: '0: a\n1: b\n2: c',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use to iterate with index when you need both index and value',
    priority: 'common',
  },
  {
    name: 'indexed (Dart 3)',
    category: 'iteration',
    syntax: 'for (var (i, v) in list.indexed) { ... }',
    description: 'Iterates with index-value pairs (Dart 3+)',
    example: {
      code: "for (var (i, v) in ['a', 'b', 'c'].indexed) {\n  print('$i: $v');\n}",
      output: '0: a\n1: b\n2: c',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Modern way to iterate with index in Dart 3',
    priority: 'common',
  },

  // ============ TYPE CONVERSION ============
  {
    name: 'int.parse / double.parse',
    category: 'type-conversion',
    syntax: 'int.parse(str) / double.parse(str)',
    description: 'Parses string to int or double',
    example: {
      code: "print(int.parse('42'));\nprint(double.parse('3.14'));",
      output: '42\n3.14',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Throws FormatException on invalid input', 'Use tryParse for safe parsing'],
    priority: 'essential',
  },
  {
    name: 'toString',
    category: 'type-conversion',
    syntax: 'value.toString()',
    description: 'Converts any value to its string representation',
    example: {
      code: 'print(42.toString());\nprint([1, 2, 3].toString());',
      output: '42\n[1, 2, 3]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'essential',
  },
  {
    name: 'toList / toSet',
    category: 'type-conversion',
    syntax: 'iterable.toList() / iterable.toSet()',
    description: 'Converts iterable to List or Set',
    example: {
      code: 'var set = {1, 2, 3};\nprint(set.toList());\nvar list = [1, 1, 2];\nprint(list.toSet());',
      output: '[1, 2, 3]\n{1, 2}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Essential when chaining functional methods that return Iterable',
    priority: 'essential',
  },
  {
    name: 'join',
    category: 'type-conversion',
    syntax: 'iterable.join([separator])',
    description: 'Joins elements into a string with separator',
    example: {
      code: "var list = ['a', 'b', 'c'];\nprint(list.join('-'));",
      output: 'a-b-c',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'essential',
  },

  // ============ MATH ============
  {
    name: 'abs / ceil / floor / round',
    category: 'math',
    syntax: 'num.abs() / num.ceil() / num.floor() / num.round()',
    description: 'Absolute value, ceiling, floor, or rounded value',
    example: {
      code: 'print((-5).abs());\nprint(3.7.ceil());\nprint(3.7.floor());',
      output: '5\n4\n3',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'min / max (dart:math)',
    category: 'math',
    syntax: 'min(a, b) / max(a, b)',
    description: 'Returns minimum or maximum of two numbers',
    example: {
      code: "import 'dart:math';\nprint(min(3, 7));\nprint(max(3, 7));",
      output: '3\n7',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Requires import dart:math'],
    interviewTip: 'For list min/max, use list.reduce(min) or fold',
    priority: 'essential',
  },
];
