/**
 * JavaScript Cheatsheet
 *
 * Essential JavaScript methods and patterns for coding interviews.
 * Covers arrays, strings, objects, sets, maps, and common utilities.
 */

import type { CheatsheetEntry } from './types';

export const javascriptCheatsheet: CheatsheetEntry[] = [
  // ============================================
  // ARRAYS - Core Methods
  // ============================================
  {
    name: 'push',
    category: 'arrays',
    syntax: 'array.push(element1, ...elementN)',
    description: 'Adds elements to end of array, returns new length',
    example: { code: 'const arr = [1, 2]; arr.push(3, 4);', output: '4 // arr is [1, 2, 3, 4]' },
    timeComplexity: 'O(1) amortized',
    spaceComplexity: 'O(1)',
    gotchas: ['Mutates original array', 'Returns length, not array'],
    priority: 'essential',
  },
  {
    name: 'pop',
    category: 'arrays',
    syntax: 'array.pop()',
    description: 'Removes and returns last element',
    example: { code: 'const arr = [1, 2, 3]; arr.pop();', output: '3 // arr is [1, 2]' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Mutates original array', 'Returns undefined if empty'],
    interviewTip: 'Use with push() to implement a stack',
    priority: 'essential',
  },
  {
    name: 'shift',
    category: 'arrays',
    syntax: 'array.shift()',
    description: 'Removes and returns first element',
    example: { code: 'const arr = [1, 2, 3]; arr.shift();', output: '1 // arr is [2, 3]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Mutates array', 'O(n) because all indices shift'],
    interviewTip:
      'Use with push() to implement a queue (but consider using index pointers for O(1))',
    priority: 'essential',
  },
  {
    name: 'unshift',
    category: 'arrays',
    syntax: 'array.unshift(element1, ...elementN)',
    description: 'Adds elements to beginning of array, returns new length',
    example: { code: 'const arr = [2, 3]; arr.unshift(0, 1);', output: '4 // arr is [0, 1, 2, 3]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['O(n) because all indices shift', 'Mutates original array'],
    priority: 'common',
  },
  {
    name: 'slice',
    category: 'arrays',
    syntax: 'array.slice(start?, end?)',
    description: 'Returns shallow copy of portion of array (end not included)',
    example: { code: 'const arr = [1, 2, 3, 4, 5]; arr.slice(1, 4);', output: '[2, 3, 4]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: [
      'Does NOT mutate original',
      'End index is exclusive',
      'Negative indices count from end',
    ],
    interviewTip: 'Use slice() to clone an array: arr.slice() or [...arr]',
    priority: 'essential',
  },
  {
    name: 'splice',
    category: 'arrays',
    syntax: 'array.splice(start, deleteCount?, ...items)',
    description: 'Removes/replaces elements in place, returns removed elements',
    example: {
      code: 'const arr = [1, 2, 3, 4]; arr.splice(1, 2, "a", "b");',
      output: '[2, 3] // arr is [1, "a", "b", 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['MUTATES original array', 'Easily confused with slice()'],
    interviewTip: 'splice(i, 1) removes element at index i; splice(i, 0, x) inserts x at index i',
    priority: 'essential',
  },
  {
    name: 'concat',
    category: 'arrays',
    syntax: 'array.concat(array2, ...arrayN)',
    description: 'Merges arrays and returns new array',
    example: { code: '[1, 2].concat([3, 4], [5]);', output: '[1, 2, 3, 4, 5]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Does NOT mutate original', 'Flattens one level only'],
    interviewTip: 'Modern alternative: [...arr1, ...arr2]',
    priority: 'common',
  },
  {
    name: 'indexOf',
    category: 'arrays',
    syntax: 'array.indexOf(element, fromIndex?)',
    description: 'Returns first index of element, or -1 if not found',
    example: { code: '[1, 2, 3, 2].indexOf(2);', output: '1' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Uses strict equality (===)', 'Cannot find NaN'],
    interviewTip: 'Use includes() for boolean check, indexOf() when you need the position',
    priority: 'essential',
  },
  {
    name: 'includes',
    category: 'arrays',
    syntax: 'array.includes(element, fromIndex?)',
    description: 'Returns true if array contains element',
    example: { code: '[1, 2, 3].includes(2);', output: 'true' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Can find NaN (unlike indexOf)', 'Uses SameValueZero comparison'],
    interviewTip: 'For O(1) lookup, convert to Set first',
    priority: 'essential',
  },
  {
    name: 'reverse',
    category: 'arrays',
    syntax: 'array.reverse()',
    description: 'Reverses array in place and returns it',
    example: { code: '[1, 2, 3].reverse();', output: '[3, 2, 1]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['MUTATES original array', 'Returns same array reference'],
    interviewTip: 'To reverse without mutating: [...arr].reverse() or arr.slice().reverse()',
    priority: 'essential',
  },
  {
    name: 'join',
    category: 'arrays',
    syntax: 'array.join(separator?)',
    description: 'Joins all elements into a string',
    example: { code: "['a', 'b', 'c'].join('-');", output: '"a-b-c"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Default separator is comma', 'null/undefined become empty strings'],
    interviewTip: 'Useful for building strings from character arrays',
    priority: 'essential',
  },
  {
    name: 'fill',
    category: 'arrays',
    syntax: 'array.fill(value, start?, end?)',
    description: 'Fills array with static value',
    example: { code: 'new Array(5).fill(0);', output: '[0, 0, 0, 0, 0]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['MUTATES original', 'Fill with objects shares same reference!'],
    interviewTip: 'For 2D arrays, use Array.from({length: n}, () => new Array(m).fill(0))',
    priority: 'essential',
  },
  {
    name: 'Array.from',
    category: 'arrays',
    syntax: 'Array.from(iterable, mapFn?)',
    description: 'Creates array from iterable or array-like object',
    example: { code: "Array.from('abc');", output: "['a', 'b', 'c']" },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: [
      'Works with Set, Map, strings, NodeList',
      'Optional map function runs on each element',
    ],
    interviewTip: 'Array.from({length: n}, (_, i) => i) creates [0, 1, 2, ..., n-1]',
    priority: 'essential',
  },

  // ============================================
  // ARRAYS - Functional Methods
  // ============================================
  {
    name: 'map',
    category: 'functional',
    syntax: 'array.map((element, index, array) => newValue)',
    description: 'Creates new array with results of calling function on every element',
    example: { code: '[1, 2, 3].map(x => x * 2);', output: '[2, 4, 6]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Does NOT mutate original', 'Returns array of same length', 'Skips empty slots'],
    interviewTip: 'Chain with filter() for transform + filter operations',
    priority: 'essential',
  },
  {
    name: 'filter',
    category: 'functional',
    syntax: 'array.filter((element, index, array) => boolean)',
    description: 'Creates new array with elements that pass the test',
    example: { code: '[1, 2, 3, 4, 5].filter(x => x % 2 === 0);', output: '[2, 4]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Does NOT mutate original', 'Returns empty array if nothing passes'],
    interviewTip: 'Combine with map: arr.filter(...).map(...)',
    priority: 'essential',
  },
  {
    name: 'reduce',
    category: 'functional',
    syntax: 'array.reduce((acc, curr, index, array) => newAcc, initialValue)',
    description: 'Reduces array to single value by applying function',
    example: { code: '[1, 2, 3, 4].reduce((sum, n) => sum + n, 0);', output: '4' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Always provide initialValue to avoid errors on empty arrays', 'Can return any type'],
    interviewTip: 'Extremely versatile: sum, max, grouping, flattening, counting',
    priority: 'essential',
  },
  {
    name: 'find',
    category: 'functional',
    syntax: 'array.find((element, index, array) => boolean)',
    description: 'Returns first element that satisfies the test, or undefined',
    example: { code: '[1, 2, 3, 4].find(x => x > 2);', output: '3' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns undefined if not found (not -1)', 'Stops at first match'],
    interviewTip: 'Use findIndex() if you need the position instead of the value',
    priority: 'essential',
  },
  {
    name: 'findIndex',
    category: 'functional',
    syntax: 'array.findIndex((element, index, array) => boolean)',
    description: 'Returns index of first element that satisfies test, or -1',
    example: { code: '[1, 2, 3, 4].findIndex(x => x > 2);', output: '2' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns -1 if not found', 'Unlike indexOf(), takes a predicate function'],
    priority: 'essential',
  },
  {
    name: 'some',
    category: 'functional',
    syntax: 'array.some((element, index, array) => boolean)',
    description: 'Returns true if at least one element passes the test',
    example: { code: '[1, 2, 3].some(x => x > 2);', output: 'true' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Short-circuits on first true', 'Returns false for empty array'],
    interviewTip: 'Useful for validation checks',
    priority: 'common',
  },
  {
    name: 'every',
    category: 'functional',
    syntax: 'array.every((element, index, array) => boolean)',
    description: 'Returns true if all elements pass the test',
    example: { code: '[2, 4, 6].every(x => x % 2 === 0);', output: 'true' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Short-circuits on first false', 'Returns true for empty array'],
    priority: 'common',
  },
  {
    name: 'forEach',
    category: 'iteration',
    syntax: 'array.forEach((element, index, array) => void)',
    description: 'Executes function once for each element',
    example: { code: '[1, 2, 3].forEach(x => console.log(x));', output: '// logs 1, 2, 3' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: [
      'Cannot break early (use for...of instead)',
      'Returns undefined',
      'Skips empty slots',
    ],
    interviewTip: 'Prefer for...of when you need break/continue/return',
    priority: 'common',
  },

  // ============================================
  // SORTING & SEARCHING
  // ============================================
  {
    name: 'sort',
    category: 'sorting',
    syntax: 'array.sort((a, b) => number)',
    description: 'Sorts array in place and returns it',
    example: { code: '[3, 1, 4, 1, 5].sort((a, b) => a - b);', output: '[1, 1, 3, 4, 5]' },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(log n)',
    gotchas: [
      'MUTATES original',
      'Default sort is lexicographic (strings)!',
      'Return negative, zero, or positive',
    ],
    interviewTip:
      'a - b for ascending, b - a for descending. Always provide comparator for numbers!',
    priority: 'essential',
  },
  {
    name: 'Binary Search Pattern',
    category: 'searching',
    syntax: 'while (left <= right) { mid = Math.floor((left + right) / 2); ... }',
    description: 'Efficient search in sorted array',
    example: {
      code: 'let left = 0, right = arr.length - 1;\nwhile (left <= right) {\n  const mid = Math.floor((left + right) / 2);\n  if (arr[mid] === target) return mid;\n  if (arr[mid] < target) left = mid + 1;\n  else right = mid - 1;\n}\nreturn -1;',
      output: '// index of target or -1',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Array must be sorted', 'Watch for integer overflow in (left + right)'],
    interviewTip:
      'Extremely common pattern. Practice variations: first/last occurrence, insertion point',
    priority: 'essential',
  },

  // ============================================
  // STRINGS
  // ============================================
  {
    name: 'split',
    category: 'strings',
    syntax: 'string.split(separator, limit?)',
    description: 'Splits string into array by separator',
    example: { code: '"a-b-c".split("-");', output: '["a", "b", "c"]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Empty string separator splits each character', 'Regex separators are powerful'],
    interviewTip: 'str.split("") converts string to char array',
    priority: 'essential',
  },
  {
    name: 'substring',
    category: 'strings',
    syntax: 'string.substring(start, end?)',
    description: 'Returns part of string between start and end (end exclusive)',
    example: { code: '"Hello".substring(1, 4);', output: '"ell"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Swaps args if start > end', 'Negative values treated as 0'],
    interviewTip: 'slice() is more predictable with negative indices',
    priority: 'essential',
  },
  {
    name: 'slice (string)',
    category: 'strings',
    syntax: 'string.slice(start, end?)',
    description: 'Extracts section of string (end exclusive)',
    example: { code: '"Hello".slice(-3);', output: '"llo"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Negative indices count from end', 'Returns empty string if start >= end'],
    interviewTip: 'Prefer slice() over substring() for consistency with array.slice()',
    priority: 'essential',
  },
  {
    name: 'charAt / charCodeAt',
    category: 'strings',
    syntax: 'string.charAt(index) / string.charCodeAt(index)',
    description: 'Returns character or Unicode value at index',
    example: { code: '"ABC".charCodeAt(0);', output: '65' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: [
      'charAt returns empty string for out of bounds',
      'charCodeAt returns NaN for out of bounds',
    ],
    interviewTip:
      'charCodeAt useful for alphabet problems: char.charCodeAt(0) - 97 gives 0-25 for a-z',
    priority: 'essential',
  },
  {
    name: 'String.fromCharCode',
    category: 'strings',
    syntax: 'String.fromCharCode(num1, ...numN)',
    description: 'Creates string from Unicode values',
    example: { code: 'String.fromCharCode(65, 66, 67);', output: '"ABC"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['For Unicode code points > 65535, use fromCodePoint()'],
    interviewTip: 'Inverse of charCodeAt. String.fromCharCode(97 + i) gives a-z',
    priority: 'essential',
  },
  {
    name: 'includes (string)',
    category: 'strings',
    syntax: 'string.includes(searchString, position?)',
    description: 'Returns true if string contains substring',
    example: { code: '"Hello World".includes("World");', output: 'true' },
    timeComplexity: 'O(n*m)',
    spaceComplexity: 'O(1)',
    gotchas: ['Case-sensitive', 'Optional position to start searching'],
    priority: 'essential',
  },
  {
    name: 'indexOf (string)',
    category: 'strings',
    syntax: 'string.indexOf(searchValue, fromIndex?)',
    description: 'Returns first index of substring, or -1',
    example: { code: '"hello".indexOf("l");', output: '2' },
    timeComplexity: 'O(n*m)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns -1 if not found', 'Case-sensitive'],
    priority: 'essential',
  },
  {
    name: 'replace / replaceAll',
    category: 'strings',
    syntax: 'string.replace(pattern, replacement)',
    description: 'Replaces first (or all) occurrences of pattern',
    example: { code: '"aabbcc".replaceAll("b", "x");', output: '"aaxxcc"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: [
      'replace() only replaces first occurrence unless using regex with /g',
      'Strings are immutable',
    ],
    interviewTip: 'Use replaceAll() or replace(/pattern/g, ...) for all occurrences',
    priority: 'common',
  },
  {
    name: 'trim / trimStart / trimEnd',
    category: 'strings',
    syntax: 'string.trim()',
    description: 'Removes whitespace from both ends',
    example: { code: '"  hello  ".trim();', output: '"hello"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: [
      'Returns new string, does not mutate',
      'Removes all whitespace including tabs, newlines',
    ],
    priority: 'common',
  },
  {
    name: 'toLowerCase / toUpperCase',
    category: 'strings',
    syntax: 'string.toLowerCase() / string.toUpperCase()',
    description: 'Converts string to lower/upper case',
    example: { code: '"Hello".toLowerCase();', output: '"hello"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns new string', 'Locale-sensitive for some characters'],
    interviewTip: 'Useful for case-insensitive comparisons',
    priority: 'essential',
  },

  // ============================================
  // OBJECTS
  // ============================================
  {
    name: 'Object.keys',
    category: 'objects',
    syntax: 'Object.keys(obj)',
    description: "Returns array of object's own enumerable property names",
    example: { code: 'Object.keys({a: 1, b: 2});', output: '["a", "b"]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: [
      'Only own properties, not inherited',
      'Order: integers first (sorted), then strings (insertion order)',
    ],
    interviewTip: 'Object.keys(obj).length gives number of properties',
    priority: 'essential',
  },
  {
    name: 'Object.values',
    category: 'objects',
    syntax: 'Object.values(obj)',
    description: "Returns array of object's own enumerable property values",
    example: { code: 'Object.values({a: 1, b: 2});', output: '[1, 2]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Same order as Object.keys'],
    priority: 'essential',
  },
  {
    name: 'Object.entries',
    category: 'objects',
    syntax: 'Object.entries(obj)',
    description: 'Returns array of [key, value] pairs',
    example: { code: 'Object.entries({a: 1, b: 2});', output: '[["a", 1], ["b", 2]]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Useful for iteration with for...of'],
    interviewTip: 'for (const [key, value] of Object.entries(obj)) { ... }',
    priority: 'essential',
  },
  {
    name: 'Object.assign',
    category: 'objects',
    syntax: 'Object.assign(target, ...sources)',
    description: 'Copies properties from sources to target',
    example: { code: 'Object.assign({a: 1}, {b: 2});', output: '{a: 1, b: 2}' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Mutates target object', 'Shallow copy only', 'Later sources overwrite earlier'],
    interviewTip: 'Modern alternative: {...obj1, ...obj2} spread syntax',
    priority: 'common',
  },
  {
    name: 'hasOwnProperty / in',
    category: 'objects',
    syntax: 'obj.hasOwnProperty(key) / key in obj',
    description: 'Checks if property exists on object',
    example: { code: '({a: 1}).hasOwnProperty("a");', output: 'true' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['"in" checks prototype chain too', 'hasOwnProperty only checks own properties'],
    interviewTip:
      'Safer: Object.hasOwn(obj, key) or Object.prototype.hasOwnProperty.call(obj, key)',
    priority: 'essential',
  },

  // ============================================
  // SETS
  // ============================================
  {
    name: 'Set',
    category: 'sets',
    syntax: 'new Set(iterable?)',
    description: 'Collection of unique values',
    example: { code: 'new Set([1, 2, 2, 3]);', output: 'Set {1, 2, 3}' },
    timeComplexity: 'O(n) to construct',
    spaceComplexity: 'O(n)',
    gotchas: ['Objects are compared by reference', 'NaN equals NaN in Set'],
    interviewTip: 'Great for removing duplicates: [...new Set(arr)]',
    priority: 'essential',
  },
  {
    name: 'Set.add / delete / has',
    category: 'sets',
    syntax: 'set.add(value) / set.delete(value) / set.has(value)',
    description: 'Add, remove, or check for value in Set',
    example: { code: 'const s = new Set(); s.add(1); s.has(1);', output: 'true' },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    gotchas: ['add() returns the Set (chainable)', 'delete() returns boolean'],
    interviewTip: 'O(1) lookup makes Set ideal for membership testing',
    priority: 'essential',
  },

  // ============================================
  // MAPS
  // ============================================
  {
    name: 'Map',
    category: 'maps',
    syntax: 'new Map(iterable?)',
    description: 'Collection of key-value pairs with any key type',
    example: { code: 'new Map([["a", 1], ["b", 2]]);', output: 'Map {"a" => 1, "b" => 2}' },
    timeComplexity: 'O(n) to construct',
    spaceComplexity: 'O(n)',
    gotchas: ['Keys can be any type (unlike objects)', 'Maintains insertion order'],
    interviewTip: 'Better than object for dynamic keys or when key order matters',
    priority: 'essential',
  },
  {
    name: 'Map.set / get / has / delete',
    category: 'maps',
    syntax: 'map.set(key, value) / map.get(key) / map.has(key) / map.delete(key)',
    description: 'Core Map operations',
    example: { code: 'const m = new Map(); m.set("a", 1); m.get("a");', output: '1' },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    gotchas: ['get() returns undefined for missing keys', 'set() returns Map (chainable)'],
    interviewTip: 'Frequency counter: map.set(key, (map.get(key) || 0) + 1)',
    priority: 'essential',
  },

  // ============================================
  // MATH
  // ============================================
  {
    name: 'Math.max / Math.min',
    category: 'math',
    syntax: 'Math.max(...values) / Math.min(...values)',
    description: 'Returns largest/smallest of given numbers',
    example: { code: 'Math.max(1, 5, 3);', output: '5' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: [
      'Returns -Infinity/Infinity for no arguments',
      'Use spread for arrays: Math.max(...arr)',
    ],
    interviewTip: 'For large arrays, use reduce to avoid stack overflow',
    priority: 'essential',
  },
  {
    name: 'Math.floor / ceil / round / trunc',
    category: 'math',
    syntax: 'Math.floor(x) / Math.ceil(x) / Math.round(x) / Math.trunc(x)',
    description: 'Rounds number down/up/nearest/toward zero',
    example: { code: 'Math.floor(4.7);', output: '4' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['floor(-4.7) = -5, trunc(-4.7) = -4', 'round(0.5) = 1'],
    interviewTip: 'Integer division: Math.floor(a / b) or Math.trunc(a / b)',
    priority: 'essential',
  },
  {
    name: 'Math.abs',
    category: 'math',
    syntax: 'Math.abs(x)',
    description: 'Returns absolute value',
    example: { code: 'Math.abs(-5);', output: '5' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },

  // ============================================
  // TYPE CONVERSION
  // ============================================
  {
    name: 'parseInt / parseFloat',
    category: 'type-conversion',
    syntax: 'parseInt(string, radix?) / parseFloat(string)',
    description: 'Parses string to integer or float',
    example: { code: 'parseInt("42px");', output: '42' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: [
      'Always specify radix for parseInt',
      'Returns NaN if cannot parse',
      'Stops at first invalid char',
    ],
    interviewTip: 'parseInt("08") may be octal in old JS; use parseInt("08", 10)',
    priority: 'essential',
  },
  {
    name: 'Number / String / Boolean',
    category: 'type-conversion',
    syntax: 'Number(value) / String(value) / Boolean(value)',
    description: 'Converts value to number, string, or boolean',
    example: { code: 'Number("42");', output: '42' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Number("") = 0, Number("abc") = NaN', 'Boolean("") = false, Boolean("0") = true'],
    interviewTip: '+str is shorthand for Number(str)',
    priority: 'essential',
  },
  {
    name: 'JSON.stringify / parse',
    category: 'type-conversion',
    syntax: 'JSON.stringify(obj) / JSON.parse(string)',
    description: 'Converts object to JSON string and back',
    example: { code: 'JSON.stringify({a: 1});', output: '\'{"a":1}\'' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: [
      'Loses functions, undefined, symbols',
      'Deep clone trick: JSON.parse(JSON.stringify(obj))',
    ],
    interviewTip: 'Quick deep clone (but loses functions and handles only JSON-safe values)',
    priority: 'common',
  },
];
