/**
 * Java Cheatsheet
 *
 * Essential Java methods and patterns for coding interviews.
 * Covers ArrayList, HashMap, HashSet, String, Arrays, Collections, and Stream API.
 */

import type { CheatsheetEntry } from './types';

export const javaCheatsheet: CheatsheetEntry[] = [
  // ============ ARRAYS ============
  {
    name: 'Arrays.sort',
    category: 'sorting',
    syntax: 'Arrays.sort(array) | Arrays.sort(array, comparator)',
    description:
      'Sorts array in-place using dual-pivot Quicksort (primitives) or TimSort (objects)',
    example: {
      code: 'int[] arr = {3, 1, 4};\nArrays.sort(arr);\n// arr = [1, 3, 4]',
      output: '[1, 3, 4]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(log n)',
    gotchas: ['Modifies original array', 'Use Integer[] for custom comparator, not int[]'],
    interviewTip: 'For descending order: Arrays.sort(arr, Collections.reverseOrder())',
    priority: 'essential',
  },
  {
    name: 'Arrays.binarySearch',
    category: 'searching',
    syntax: 'Arrays.binarySearch(array, key)',
    description: 'Searches sorted array for key, returns index or (-(insertion point) - 1)',
    example: {
      code: 'int[] arr = {1, 3, 5, 7};\nint idx = Arrays.binarySearch(arr, 5);\n// idx = 2',
      output: '2',
    },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Array must be sorted first', 'Negative result means not found'],
    interviewTip: 'To get insertion point from negative result: -(result + 1)',
    priority: 'essential',
  },
  {
    name: 'Arrays.fill',
    category: 'arrays',
    syntax: 'Arrays.fill(array, value) | Arrays.fill(array, from, to, value)',
    description: 'Fills array or range with specified value',
    example: {
      code: 'int[] arr = new int[5];\nArrays.fill(arr, -1);\n// arr = [-1, -1, -1, -1, -1]',
      output: '[-1, -1, -1, -1, -1]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['For 2D arrays, fills with same reference if using Object[]'],
    interviewTip: 'Great for initializing DP arrays with default values',
    priority: 'common',
  },
  {
    name: 'Arrays.copyOf',
    category: 'arrays',
    syntax: 'Arrays.copyOf(array, newLength)',
    description: 'Creates new array with specified length, copying elements',
    example: {
      code: 'int[] arr = {1, 2, 3};\nint[] copy = Arrays.copyOf(arr, 5);\n// copy = [1, 2, 3, 0, 0]',
      output: '[1, 2, 3, 0, 0]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Pads with default values if new length is larger'],
    priority: 'common',
  },
  {
    name: 'Arrays.asList',
    category: 'arrays',
    syntax: 'Arrays.asList(array)',
    description: 'Returns fixed-size list backed by array',
    example: {
      code: 'String[] arr = {"a", "b", "c"};\nList<String> list = Arrays.asList(arr);',
      output: '[a, b, c]',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: [
      'Cannot add/remove elements (fixed size)',
      'Does not work with primitive arrays - use int[] requires boxed Integer[]',
    ],
    interviewTip: 'Use new ArrayList<>(Arrays.asList(...)) for mutable list',
    priority: 'essential',
  },

  // ============ ARRAYLIST ============
  {
    name: 'ArrayList.add',
    category: 'collections',
    syntax: 'list.add(element) | list.add(index, element)',
    description: 'Appends element or inserts at index',
    example: {
      code: 'List<Integer> list = new ArrayList<>();\nlist.add(1);\nlist.add(0, 0);\n// list = [0, 1]',
      output: '[0, 1]',
    },
    timeComplexity: 'O(1) amortized, O(n) at index',
    spaceComplexity: 'O(1)',
    gotchas: ['Inserting at index shifts subsequent elements'],
    priority: 'essential',
  },
  {
    name: 'ArrayList.get',
    category: 'collections',
    syntax: 'list.get(index)',
    description: 'Returns element at specified index',
    example: {
      code: 'List<String> list = Arrays.asList("a", "b", "c");\nString s = list.get(1);\n// s = "b"',
      output: '"b"',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Throws IndexOutOfBoundsException if index invalid'],
    priority: 'essential',
  },
  {
    name: 'ArrayList.set',
    category: 'collections',
    syntax: 'list.set(index, element)',
    description: 'Replaces element at index, returns old element',
    example: {
      code: 'List<Integer> list = new ArrayList<>(Arrays.asList(1, 2, 3));\nint old = list.set(1, 5);\n// old = 2, list = [1, 5, 3]',
      output: 'old = 2, list = [1, 5, 3]',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },
  {
    name: 'ArrayList.remove',
    category: 'collections',
    syntax: 'list.remove(index) | list.remove(object)',
    description: 'Removes element by index or first occurrence of object',
    example: {
      code: 'List<Integer> list = new ArrayList<>(Arrays.asList(1, 2, 3));\nlist.remove(1);\n// list = [1, 3]',
      output: '[1, 3]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: [
      'For Integer list, remove(1) removes at index 1; use remove(Integer.valueOf(1)) to remove value',
    ],
    interviewTip: 'Be careful with Integer lists - ambiguous between index and value',
    priority: 'essential',
  },
  {
    name: 'ArrayList.contains',
    category: 'collections',
    syntax: 'list.contains(object)',
    description: 'Returns true if list contains specified element',
    example: {
      code: 'List<String> list = Arrays.asList("a", "b", "c");\nboolean has = list.contains("b");\n// has = true',
      output: 'true',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Uses equals() for comparison'],
    interviewTip: 'Use HashSet for O(1) lookups if checking frequently',
    priority: 'essential',
  },
  {
    name: 'ArrayList.subList',
    category: 'collections',
    syntax: 'list.subList(fromIndex, toIndex)',
    description: 'Returns view of portion of list (fromIndex inclusive, toIndex exclusive)',
    example: {
      code: 'List<Integer> list = Arrays.asList(0, 1, 2, 3, 4);\nList<Integer> sub = list.subList(1, 4);\n// sub = [1, 2, 3]',
      output: '[1, 2, 3]',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns a view - changes affect original list'],
    interviewTip: 'Use new ArrayList<>(list.subList(...)) for independent copy',
    priority: 'common',
  },
  {
    name: 'Collections.reverse',
    category: 'collections',
    syntax: 'Collections.reverse(list)',
    description: 'Reverses list in-place',
    example: {
      code: 'List<Integer> list = new ArrayList<>(Arrays.asList(1, 2, 3));\nCollections.reverse(list);\n// list = [3, 2, 1]',
      output: '[3, 2, 1]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Modifies original list'],
    priority: 'essential',
  },
  {
    name: 'Collections.sort',
    category: 'sorting',
    syntax: 'Collections.sort(list) | Collections.sort(list, comparator)',
    description: 'Sorts list in-place using TimSort',
    example: {
      code: 'List<Integer> list = new ArrayList<>(Arrays.asList(3, 1, 2));\nCollections.sort(list);\n// list = [1, 2, 3]',
      output: '[1, 2, 3]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    gotchas: ['List must implement List interface'],
    interviewTip: 'Use list.sort(comparator) in Java 8+ as shorthand',
    priority: 'essential',
  },
  {
    name: 'Collections.max/min',
    category: 'collections',
    syntax: 'Collections.max(collection) | Collections.min(collection)',
    description: 'Returns maximum or minimum element',
    example: {
      code: 'List<Integer> list = Arrays.asList(3, 1, 4, 1, 5);\nint max = Collections.max(list);\n// max = 5',
      output: '5',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Throws NoSuchElementException if collection is empty'],
    priority: 'common',
  },

  // ============ HASHMAP ============
  {
    name: 'HashMap.put',
    category: 'maps',
    syntax: 'map.put(key, value)',
    description: 'Associates key with value, returns previous value or null',
    example: {
      code: 'Map<String, Integer> map = new HashMap<>();\nmap.put("a", 1);\nmap.put("a", 2);\n// map = {a=2}',
      output: '{a=2}',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    gotchas: ['Overwrites existing value for same key'],
    priority: 'essential',
  },
  {
    name: 'HashMap.get',
    category: 'maps',
    syntax: 'map.get(key)',
    description: 'Returns value for key, or null if not present',
    example: {
      code: 'Map<String, Integer> map = new HashMap<>();\nmap.put("a", 1);\nInteger val = map.get("a");\n// val = 1',
      output: '1',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns null for missing key - check with containsKey if value could be null'],
    priority: 'essential',
  },
  {
    name: 'HashMap.getOrDefault',
    category: 'maps',
    syntax: 'map.getOrDefault(key, defaultValue)',
    description: 'Returns value for key, or default if not present',
    example: {
      code: 'Map<String, Integer> map = new HashMap<>();\nint val = map.getOrDefault("a", 0);\n// val = 0',
      output: '0',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Essential for counting patterns - avoids null checks',
    priority: 'essential',
  },
  {
    name: 'HashMap.containsKey',
    category: 'maps',
    syntax: 'map.containsKey(key)',
    description: 'Returns true if map contains the key',
    example: {
      code: 'Map<String, Integer> map = new HashMap<>();\nmap.put("a", 1);\nboolean has = map.containsKey("a");\n// has = true',
      output: 'true',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'HashMap.computeIfAbsent',
    category: 'maps',
    syntax: 'map.computeIfAbsent(key, mappingFunction)',
    description: 'Computes value using function if key is absent, returns value',
    example: {
      code: 'Map<String, List<Integer>> map = new HashMap<>();\nmap.computeIfAbsent("a", k -> new ArrayList<>()).add(1);\n// map = {a=[1]}',
      output: '{a=[1]}',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Perfect for grouping problems - initializes and returns in one call',
    priority: 'essential',
  },
  {
    name: 'HashMap.merge',
    category: 'maps',
    syntax: 'map.merge(key, value, remappingFunction)',
    description: 'Merges value with existing using function, or puts if absent',
    example: {
      code: 'Map<String, Integer> map = new HashMap<>();\nmap.merge("a", 1, Integer::sum);\nmap.merge("a", 1, Integer::sum);\n// map.get("a") = 2',
      output: '2',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Elegant one-liner for frequency counting',
    priority: 'common',
  },
  {
    name: 'HashMap.keySet',
    category: 'maps',
    syntax: 'map.keySet()',
    description: 'Returns Set view of all keys',
    example: {
      code: 'Map<String, Integer> map = new HashMap<>();\nmap.put("a", 1); map.put("b", 2);\nSet<String> keys = map.keySet();\n// keys = [a, b]',
      output: '[a, b]',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns a view - changes affect original map'],
    priority: 'essential',
  },
  {
    name: 'HashMap.entrySet',
    category: 'maps',
    syntax: 'map.entrySet()',
    description: 'Returns Set of key-value entry pairs for iteration',
    example: {
      code: 'for (Map.Entry<String, Integer> e : map.entrySet()) {\n  System.out.println(e.getKey() + ": " + e.getValue());\n}',
      output: 'a: 1\nb: 2',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Most efficient way to iterate over both keys and values',
    priority: 'essential',
  },

  // ============ HASHSET ============
  {
    name: 'HashSet.add',
    category: 'sets',
    syntax: 'set.add(element)',
    description: 'Adds element to set, returns true if not already present',
    example: {
      code: 'Set<Integer> set = new HashSet<>();\nboolean added = set.add(1);\nboolean dup = set.add(1);\n// added = true, dup = false',
      output: 'added = true, dup = false',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Return value is useful for detecting duplicates in one operation',
    priority: 'essential',
  },
  {
    name: 'HashSet.contains',
    category: 'sets',
    syntax: 'set.contains(element)',
    description: 'Returns true if set contains element',
    example: {
      code: 'Set<Integer> set = new HashSet<>(Arrays.asList(1, 2, 3));\nboolean has = set.contains(2);\n// has = true',
      output: 'true',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use for O(1) lookups instead of list.contains() which is O(n)',
    priority: 'essential',
  },
  {
    name: 'HashSet.remove',
    category: 'sets',
    syntax: 'set.remove(element)',
    description: 'Removes element from set, returns true if present',
    example: {
      code: 'Set<Integer> set = new HashSet<>(Arrays.asList(1, 2, 3));\nboolean removed = set.remove(2);\n// removed = true, set = [1, 3]',
      output: 'removed = true',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'HashSet.retainAll',
    category: 'sets',
    syntax: 'set.retainAll(collection)',
    description: 'Retains only elements in both (intersection)',
    example: {
      code: 'Set<Integer> a = new HashSet<>(Arrays.asList(1, 2, 3));\nSet<Integer> b = new HashSet<>(Arrays.asList(2, 3, 4));\na.retainAll(b);\n// a = [2, 3]',
      output: '[2, 3]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use for set intersection problems',
    priority: 'common',
  },
  {
    name: 'HashSet.addAll',
    category: 'sets',
    syntax: 'set.addAll(collection)',
    description: 'Adds all elements from collection (union)',
    example: {
      code: 'Set<Integer> a = new HashSet<>(Arrays.asList(1, 2));\na.addAll(Arrays.asList(2, 3));\n// a = [1, 2, 3]',
      output: '[1, 2, 3]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'common',
  },

  // ============ STRINGS ============
  {
    name: 'String.charAt',
    category: 'strings',
    syntax: 'str.charAt(index)',
    description: 'Returns character at specified index',
    example: { code: 'String s = "hello";\nchar c = s.charAt(1);\n// c = \'e\'', output: "'e'" },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Throws StringIndexOutOfBoundsException for invalid index'],
    priority: 'essential',
  },
  {
    name: 'String.substring',
    category: 'strings',
    syntax: 'str.substring(beginIndex) | str.substring(beginIndex, endIndex)',
    description: 'Returns substring (endIndex is exclusive)',
    example: {
      code: 'String s = "hello";\nString sub = s.substring(1, 4);\n// sub = "ell"',
      output: '"ell"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Creates new String object', 'endIndex is exclusive'],
    priority: 'essential',
  },
  {
    name: 'String.toCharArray',
    category: 'strings',
    syntax: 'str.toCharArray()',
    description: 'Converts string to character array',
    example: {
      code: "String s = \"abc\";\nchar[] arr = s.toCharArray();\n// arr = ['a', 'b', 'c']",
      output: "['a', 'b', 'c']",
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Essential for in-place string manipulation since strings are immutable',
    priority: 'essential',
  },
  {
    name: 'String.split',
    category: 'strings',
    syntax: 'str.split(regex) | str.split(regex, limit)',
    description: 'Splits string by regex pattern into array',
    example: {
      code: 'String s = "a,b,c";\nString[] parts = s.split(",");\n// parts = ["a", "b", "c"]',
      output: '["a", "b", "c"]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Argument is regex - escape special chars like "\\\\." for dot'],
    priority: 'essential',
  },
  {
    name: 'String.indexOf',
    category: 'strings',
    syntax: 'str.indexOf(char) | str.indexOf(substring)',
    description: 'Returns first index of char/substring, or -1 if not found',
    example: {
      code: 'String s = "hello";\nint idx = s.indexOf("ll");\n// idx = 2',
      output: '2',
    },
    timeComplexity: 'O(n*m) for substring',
    spaceComplexity: 'O(1)',
    gotchas: ['lastIndexOf() finds last occurrence'],
    priority: 'essential',
  },
  {
    name: 'String.equals',
    category: 'strings',
    syntax: 'str1.equals(str2)',
    description: 'Compares string content for equality',
    example: {
      code: 'String a = "hello";\nString b = new String("hello");\nboolean eq = a.equals(b);\n// eq = true',
      output: 'true',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Never use == for string comparison (compares references)'],
    interviewTip: 'Always use .equals() for string comparison in Java',
    priority: 'essential',
  },
  {
    name: 'String.compareTo',
    category: 'strings',
    syntax: 'str1.compareTo(str2)',
    description: 'Compares strings lexicographically, returns negative/zero/positive',
    example: {
      code: 'int cmp = "apple".compareTo("banana");\n// cmp < 0 (negative)',
      output: 'negative value',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Useful for custom sorting of strings',
    priority: 'common',
  },
  {
    name: 'String.startsWith/endsWith',
    category: 'strings',
    syntax: 'str.startsWith(prefix) | str.endsWith(suffix)',
    description: 'Checks if string starts/ends with specified substring',
    example: {
      code: 'String s = "hello";\nboolean starts = s.startsWith("he");\n// starts = true',
      output: 'true',
    },
    timeComplexity: 'O(m) where m is prefix/suffix length',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },
  {
    name: 'String.toLowerCase/toUpperCase',
    category: 'strings',
    syntax: 'str.toLowerCase() | str.toUpperCase()',
    description: 'Returns new string with all characters converted to lower/upper case',
    example: {
      code: 'String s = "Hello";\nString lower = s.toLowerCase();\n// lower = "hello"',
      output: '"hello"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns new string, original unchanged'],
    priority: 'common',
  },
  {
    name: 'String.trim',
    category: 'strings',
    syntax: 'str.trim()',
    description: 'Returns string with leading and trailing whitespace removed',
    example: {
      code: 'String s = "  hello  ";\nString trimmed = s.trim();\n// trimmed = "hello"',
      output: '"hello"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Only removes leading/trailing, not internal whitespace'],
    priority: 'common',
  },
  {
    name: 'String.replace',
    category: 'strings',
    syntax: 'str.replace(oldChar, newChar) | str.replace(target, replacement)',
    description: 'Returns new string with all occurrences replaced',
    example: {
      code: 'String s = "hello";\nString r = s.replace("l", "L");\n// r = "heLLo"',
      output: '"heLLo"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['replaceAll() uses regex, replace() uses literal strings'],
    priority: 'common',
  },
  {
    name: 'StringBuilder',
    category: 'strings',
    syntax: 'new StringBuilder() | sb.append(x) | sb.toString()',
    description: 'Mutable string builder for efficient concatenation',
    example: {
      code: 'StringBuilder sb = new StringBuilder();\nsb.append("a").append("b");\nString s = sb.toString();\n// s = "ab"',
      output: '"ab"',
    },
    timeComplexity: 'O(1) amortized for append',
    spaceComplexity: 'O(n)',
    interviewTip: 'Always use StringBuilder in loops instead of string concatenation',
    priority: 'essential',
  },
  {
    name: 'StringBuilder.reverse',
    category: 'strings',
    syntax: 'sb.reverse()',
    description: 'Reverses the string builder in-place',
    example: {
      code: 'StringBuilder sb = new StringBuilder("hello");\nsb.reverse();\n// sb = "olleh"',
      output: '"olleh"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Quick way to reverse a string',
    priority: 'essential',
  },
  {
    name: 'Character.isDigit/isLetter/isLetterOrDigit',
    category: 'strings',
    syntax: 'Character.isDigit(c) | Character.isLetter(c)',
    description: 'Checks if character is digit, letter, or alphanumeric',
    example: {
      code: "boolean d = Character.isDigit('5');\nboolean l = Character.isLetter('a');\n// d = true, l = true",
      output: 'd = true, l = true',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Essential for parsing and validation problems',
    priority: 'essential',
  },
  {
    name: 'Integer.parseInt',
    category: 'type-conversion',
    syntax: 'Integer.parseInt(str) | Integer.valueOf(str)',
    description: 'Parses string to int primitive or Integer object',
    example: {
      code: 'int n = Integer.parseInt("123");\n// n = 123',
      output: '123',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Throws NumberFormatException for invalid input'],
    priority: 'essential',
  },
  {
    name: 'String.valueOf',
    category: 'type-conversion',
    syntax: 'String.valueOf(value)',
    description: 'Converts any primitive or object to string',
    example: {
      code: 'String s = String.valueOf(123);\n// s = "123"',
      output: '"123"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'common',
  },

  // ============ MATH ============
  {
    name: 'Math.max/min',
    category: 'math',
    syntax: 'Math.max(a, b) | Math.min(a, b)',
    description: 'Returns larger or smaller of two values',
    example: {
      code: 'int max = Math.max(3, 7);\nint min = Math.min(3, 7);\n// max = 7, min = 3',
      output: 'max = 7, min = 3',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use for updating running max/min in loops',
    priority: 'essential',
  },
  {
    name: 'Math.abs',
    category: 'math',
    syntax: 'Math.abs(value)',
    description: 'Returns absolute value',
    example: {
      code: 'int a = Math.abs(-5);\n// a = 5',
      output: '5',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Math.abs(Integer.MIN_VALUE) returns negative due to overflow'],
    priority: 'essential',
  },
  {
    name: 'Math.pow',
    category: 'math',
    syntax: 'Math.pow(base, exponent)',
    description: 'Returns base raised to exponent power (returns double)',
    example: {
      code: 'double p = Math.pow(2, 10);\n// p = 1024.0',
      output: '1024.0',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns double, cast to int if needed'],
    priority: 'common',
  },
  {
    name: 'Math.sqrt',
    category: 'math',
    syntax: 'Math.sqrt(value)',
    description: 'Returns square root',
    example: {
      code: 'double s = Math.sqrt(16);\n// s = 4.0',
      output: '4.0',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },
  {
    name: 'Math.floor/ceil/round',
    category: 'math',
    syntax: 'Math.floor(x) | Math.ceil(x) | Math.round(x)',
    description: 'Rounds down, up, or to nearest integer',
    example: {
      code: 'double f = Math.floor(3.7);\ndouble c = Math.ceil(3.2);\n// f = 3.0, c = 4.0',
      output: 'f = 3.0, c = 4.0',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },

  // ============ STREAM API ============
  {
    name: 'Stream.filter',
    category: 'functional',
    syntax: 'stream.filter(predicate)',
    description: 'Returns stream with elements matching predicate',
    example: {
      code: 'List<Integer> evens = Arrays.asList(1, 2, 3, 4).stream()\n  .filter(n -> n % 2 == 0)\n  .collect(Collectors.toList());\n// evens = [2, 4]',
      output: '[2, 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Intermediate operation - must be followed by terminal operation',
    priority: 'essential',
  },
  {
    name: 'Stream.map',
    category: 'functional',
    syntax: 'stream.map(function)',
    description: 'Transforms each element using function',
    example: {
      code: 'List<Integer> doubled = Arrays.asList(1, 2, 3).stream()\n  .map(n -> n * 2)\n  .collect(Collectors.toList());\n// doubled = [2, 4, 6]',
      output: '[2, 4, 6]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Use mapToInt/mapToLong for primitives to avoid boxing',
    priority: 'essential',
  },
  {
    name: 'Stream.reduce',
    category: 'functional',
    syntax: 'stream.reduce(identity, accumulator)',
    description: 'Reduces stream to single value using accumulator function',
    example: {
      code: 'int sum = Arrays.asList(1, 2, 3, 4).stream()\n  .reduce(0, Integer::sum);\n// sum = 10',
      output: '10',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Identity is the starting value and returned for empty streams',
    priority: 'essential',
  },
  {
    name: 'Stream.collect',
    category: 'functional',
    syntax: 'stream.collect(Collectors.toList())',
    description: 'Collects stream elements into a collection',
    example: {
      code: 'List<String> list = stream.collect(Collectors.toList());\nSet<String> set = stream.collect(Collectors.toSet());',
      output: 'List or Set',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Terminal operation - stream cannot be reused after'],
    priority: 'essential',
  },
  {
    name: 'Collectors.groupingBy',
    category: 'functional',
    syntax: 'stream.collect(Collectors.groupingBy(classifier))',
    description: 'Groups elements by classifier function into Map',
    example: {
      code: 'Map<Integer, List<String>> byLength = words.stream()\n  .collect(Collectors.groupingBy(String::length));\n// {3=[cat, dog], 5=[hello]}',
      output: '{3=[cat, dog], 5=[hello]}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Powerful for grouping/categorization problems',
    priority: 'common',
  },
  {
    name: 'Stream.sorted',
    category: 'functional',
    syntax: 'stream.sorted() | stream.sorted(comparator)',
    description: 'Returns stream with elements sorted',
    example: {
      code: 'List<Integer> sorted = Arrays.asList(3, 1, 2).stream()\n  .sorted()\n  .collect(Collectors.toList());\n// sorted = [1, 2, 3]',
      output: '[1, 2, 3]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Use Comparator.reverseOrder() for descending',
    priority: 'common',
  },
  {
    name: 'Stream.distinct',
    category: 'functional',
    syntax: 'stream.distinct()',
    description: 'Returns stream with duplicate elements removed',
    example: {
      code: 'List<Integer> unique = Arrays.asList(1, 2, 2, 3).stream()\n  .distinct()\n  .collect(Collectors.toList());\n// unique = [1, 2, 3]',
      output: '[1, 2, 3]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'common',
  },
  {
    name: 'Stream.anyMatch/allMatch/noneMatch',
    category: 'functional',
    syntax: 'stream.anyMatch(predicate)',
    description: 'Tests if any/all/none elements match predicate',
    example: {
      code: 'boolean hasEven = Arrays.asList(1, 2, 3).stream()\n  .anyMatch(n -> n % 2 == 0);\n// hasEven = true',
      output: 'true',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Short-circuits - stops at first match/mismatch',
    priority: 'common',
  },
  {
    name: 'Stream.findFirst/findAny',
    category: 'functional',
    syntax: 'stream.findFirst()',
    description: 'Returns Optional of first element (or any for parallel)',
    example: {
      code: 'Optional<Integer> first = Arrays.asList(1, 2, 3).stream()\n  .filter(n -> n > 1)\n  .findFirst();\n// first = Optional[2]',
      output: 'Optional[2]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns Optional - use .orElse() or .get()'],
    priority: 'common',
  },
  {
    name: 'IntStream.range',
    category: 'iteration',
    syntax: 'IntStream.range(start, end) | IntStream.rangeClosed(start, end)',
    description: 'Creates stream of integers from start to end (exclusive/inclusive)',
    example: {
      code: 'int[] arr = IntStream.range(0, 5).toArray();\n// arr = [0, 1, 2, 3, 4]',
      output: '[0, 1, 2, 3, 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Useful for generating index ranges or number sequences',
    priority: 'common',
  },
];
