/**
 * Kotlin Cheatsheet
 *
 * Essential Kotlin methods and idioms for coding interviews.
 * Covers collections, strings, maps, sets, scope functions, and functional operations.
 */

import type { CheatsheetEntry } from './types';

export const kotlinCheatsheet: CheatsheetEntry[] = [
  // ============ ARRAYS / LISTS ============
  {
    name: 'listOf / mutableListOf',
    category: 'arrays',
    syntax: 'listOf(elements) / mutableListOf(elements)',
    description: 'Creates immutable or mutable list from elements',
    example: { code: 'val nums = mutableListOf(1, 2)\nnums.add(3)', output: '[1, 2, 3]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['listOf returns immutable List; use mutableListOf for add/remove'],
    interviewTip: 'mutableListOf is primary choice for dynamic lists in interviews',
    priority: 'essential',
  },
  {
    name: 'add / removeAt',
    category: 'arrays',
    syntax: 'list.add(element) / list.removeAt(index)',
    description: 'Adds element to end or removes element at index',
    example: {
      code: 'val list = mutableListOf(1, 3)\nlist.add(1, 2)\nlist.removeAt(0)',
      output: '[2, 3]',
    },
    timeComplexity: 'O(1) add / O(n) removeAt',
    spaceComplexity: 'O(1)',
    gotchas: ['removeAt shifts elements; add(index, elem) is O(n)'],
    priority: 'essential',
  },
  {
    name: 'get / []',
    category: 'arrays',
    syntax: 'list[index] / list.getOrNull(index)',
    description: 'Access element at index; getOrNull returns null if out of bounds',
    example: { code: 'listOf(1, 2).getOrNull(5)', output: 'null' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['[] throws IndexOutOfBoundsException for invalid index'],
    interviewTip: 'Use getOrNull() for safe boundary access',
    priority: 'essential',
  },
  {
    name: 'size / isEmpty',
    category: 'arrays',
    syntax: 'list.size / list.isEmpty() / list.isNotEmpty()',
    description: 'Returns count of elements or checks if empty',
    example: { code: 'listOf<Int>().isEmpty()', output: 'true' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use isNotEmpty() instead of size > 0 for readability',
    priority: 'essential',
  },
  {
    name: 'first / last',
    category: 'arrays',
    syntax: 'list.first() / list.last() / list.firstOrNull()',
    description: 'Returns first/last element; throws if empty without OrNull variant',
    example: { code: 'listOf(1, 2, 3).first()', output: '1' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['first()/last() throw NoSuchElementException on empty list'],
    interviewTip: 'Use firstOrNull()/lastOrNull() for safe access',
    priority: 'essential',
  },
  {
    name: 'indices / withIndex',
    category: 'arrays',
    syntax: 'list.indices / list.withIndex()',
    description: 'Returns index range or iterable of (index, value) pairs',
    example: {
      code: 'for ((i, v) in listOf("a","b").withIndex())\n  println("$i: $v")',
      output: '0: a\\n1: b',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Kotlin idiom for enumerate-style iteration',
    priority: 'common',
  },
  {
    name: 'reversed',
    category: 'arrays',
    syntax: 'list.reversed()',
    description: 'Returns new list with elements in reversed order',
    example: { code: 'listOf(1, 2, 3).reversed()', output: '[3, 2, 1]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Creates a new list, does not modify original'],
    priority: 'common',
  },
  {
    name: 'slice / subList',
    category: 'arrays',
    syntax: 'list.slice(range) / list.subList(from, to)',
    description: 'Returns list portion; subList is a view, slice creates new list',
    example: { code: 'listOf(0,1,2,3,4).slice(1..3)', output: '[1, 2, 3]' },
    timeComplexity: 'O(k) slice / O(1) subList',
    spaceComplexity: 'O(k) / O(1)',
    gotchas: ['subList changes reflect in original mutable list'],
    priority: 'common',
  },

  // ============ STRINGS ============
  {
    name: 'length / isEmpty',
    category: 'strings',
    syntax: 'str.length / str.isEmpty() / str.isBlank()',
    description: 'Returns character count or checks if empty/blank',
    example: { code: '"  ".isBlank()', output: 'true' },
    timeComplexity: 'O(1) / O(n) for isBlank',
    spaceComplexity: 'O(1)',
    interviewTip: 'isBlank checks for whitespace-only strings',
    priority: 'essential',
  },
  {
    name: 'substring',
    category: 'strings',
    syntax: 'str.substring(startIndex, endIndex)',
    description: 'Extracts substring from start to end (exclusive)',
    example: { code: '"hello".substring(1, 4)', output: '"ell"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['End index is exclusive'],
    priority: 'essential',
  },
  {
    name: 'split / joinToString',
    category: 'strings',
    syntax: 'str.split(delimiter) / list.joinToString(separator)',
    description: 'Splits string into list or joins list elements into string',
    example: { code: '"a,b,c".split(",").joinToString("-")', output: '"a-b-c"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'joinToString supports prefix, postfix, and transform lambda',
    priority: 'essential',
  },
  {
    name: 'toCharArray',
    category: 'strings',
    syntax: 'str.toCharArray()',
    description: 'Converts string to CharArray for mutation',
    example: { code: '"abc".toCharArray()', output: "['a', 'b', 'c']" },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Essential for in-place string manipulation problems',
    priority: 'essential',
  },
  {
    name: 'toInt / toIntOrNull',
    category: 'strings',
    syntax: 'str.toInt() / str.toIntOrNull()',
    description: 'Parses string to integer; toIntOrNull returns null on failure',
    example: { code: '"abc".toIntOrNull()', output: 'null' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['toInt() throws NumberFormatException on invalid input'],
    interviewTip: 'Use toIntOrNull() for safe parsing',
    priority: 'essential',
  },
  {
    name: 'contains / startsWith / endsWith',
    category: 'strings',
    syntax: 'str.contains(s) / str.startsWith(prefix)',
    description: 'Checks for substring, prefix, or suffix presence',
    example: { code: '"hello".contains("ell")', output: 'true' },
    timeComplexity: 'O(n*m) contains / O(k) prefix',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'trim / replace',
    category: 'strings',
    syntax: 'str.trim() / str.replace(old, new)',
    description: 'Removes whitespace or replaces all occurrences',
    example: { code: '"  hello  ".trim().replace("l", "L")', output: '"heLLo"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'common',
  },

  // ============ MAPS ============
  {
    name: 'mapOf / mutableMapOf',
    category: 'maps',
    syntax: 'mapOf(k1 to v1) / mutableMapOf<K, V>()',
    description: 'Creates immutable or mutable HashMap',
    example: { code: 'val m = mutableMapOf<String, Int>()\nm["a"] = 1', output: '{a=1}' },
    timeComplexity: 'O(1) average operations',
    spaceComplexity: 'O(n)',
    interviewTip: 'Go-to for frequency counting and lookups',
    priority: 'essential',
  },
  {
    name: 'get / getOrDefault',
    category: 'maps',
    syntax: 'map[key] / map.getOrDefault(key, default)',
    description: 'Returns value for key, or null/default if not present',
    example: { code: 'mapOf("a" to 1).getOrDefault("b", 0)', output: '0' },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Perfect for frequency counting: map.getOrDefault(k, 0) + 1',
    priority: 'essential',
  },
  {
    name: 'getOrPut',
    category: 'maps',
    syntax: 'map.getOrPut(key) { defaultValue }',
    description: 'Returns existing value or computes, stores, and returns default',
    example: {
      code: 'val m = mutableMapOf<String, MutableList<Int>>()\nm.getOrPut("a") { mutableListOf() }.add(1)',
      output: '{a=[1]}',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Essential for grouping problems (adjacency lists, anagrams)',
    priority: 'essential',
  },
  {
    name: 'containsKey / in',
    category: 'maps',
    syntax: 'key in map / map.containsKey(key)',
    description: 'Checks if map contains the specified key',
    example: { code: '"a" in mapOf("a" to 1)', output: 'true' },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Prefer "in" operator for readability',
    priority: 'essential',
  },
  {
    name: 'keys / values / entries',
    category: 'maps',
    syntax: 'map.keys / map.values / map.entries',
    description: 'Returns set of keys, collection of values, or set of entries',
    example: { code: 'for ((k, v) in map.entries) println("$k=$v")', output: 'a=1' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use destructuring in for loop: for ((k, v) in map)',
    priority: 'essential',
  },
  {
    name: 'remove (Map)',
    category: 'maps',
    syntax: 'map.remove(key)',
    description: 'Removes entry for key, returns previous value or null',
    example: { code: 'val m = mutableMapOf("a" to 1)\nm.remove("a")', output: '1' },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },

  // ============ SETS ============
  {
    name: 'setOf / mutableSetOf',
    category: 'sets',
    syntax: 'setOf(elements) / mutableSetOf(elements)',
    description: 'Creates immutable or mutable HashSet',
    example: { code: 'val s = mutableSetOf(1, 2, 2, 3)', output: '[1, 2, 3]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Duplicates are automatically removed'],
    interviewTip: 'Use for O(1) lookup and deduplication',
    priority: 'essential',
  },
  {
    name: 'add / contains (Set)',
    category: 'sets',
    syntax: 'set.add(element) / element in set',
    description: 'Adds element (returns true if new) or checks membership',
    example: { code: 'val s = mutableSetOf(1)\nval added = s.add(1)', output: 'false' },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'add() return value useful for detecting duplicates',
    priority: 'essential',
  },
  {
    name: 'toSet',
    category: 'sets',
    syntax: 'collection.toSet()',
    description: 'Converts collection to Set, removing duplicates',
    example: { code: 'listOf(1, 1, 2, 2).toSet()', output: '[1, 2]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Quick way to get unique elements',
    priority: 'common',
  },

  // ============ FUNCTIONAL ============
  {
    name: 'map',
    category: 'functional',
    syntax: 'collection.map { transform }',
    description: 'Transforms each element, returns new list',
    example: { code: 'listOf(1, 2, 3).map { it * 2 }', output: '[2, 4, 6]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: '"it" is implicit single parameter name',
    priority: 'essential',
  },
  {
    name: 'filter / filterNot',
    category: 'functional',
    syntax: 'collection.filter { predicate }',
    description: 'Returns list of elements matching (or not matching) predicate',
    example: { code: 'listOf(1, 2, 3, 4).filter { it % 2 == 0 }', output: '[2, 4]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'essential',
  },
  {
    name: 'reduce / fold',
    category: 'functional',
    syntax: 'list.reduce { acc, e -> } / list.fold(init) { acc, e -> }',
    description: 'Accumulates values; fold takes initial value, reduce uses first element',
    example: { code: 'listOf(1, 2, 3).fold(10) { acc, n -> acc + n }', output: '16' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['reduce throws on empty collection; use fold or reduceOrNull'],
    interviewTip: 'fold is safer - works on empty collections',
    priority: 'essential',
  },
  {
    name: 'flatMap',
    category: 'functional',
    syntax: 'collection.flatMap { transform }',
    description: 'Maps each element to iterable and flattens results',
    example: { code: 'listOf(1, 2).flatMap { listOf(it, it * 10) }', output: '[1, 10, 2, 20]' },
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(n * m)',
    interviewTip: 'Useful for generating combinations or expanding elements',
    priority: 'common',
  },
  {
    name: 'groupBy',
    category: 'functional',
    syntax: 'collection.groupBy { keySelector }',
    description: 'Groups elements by key into Map<K, List<V>>',
    example: { code: 'listOf("a", "ab", "b").groupBy { it.length }', output: '{1=[a, b], 2=[ab]}' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Perfect for anagram grouping, categorization problems',
    priority: 'essential',
  },
  {
    name: 'sortedBy / sortedByDescending',
    category: 'sorting',
    syntax: 'collection.sortedBy { selector }',
    description: 'Returns list sorted by comparable key selector',
    example: {
      code: 'listOf("bb", "a", "ccc").sortedBy { it.length }',
      output: '["a", "bb", "ccc"]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    priority: 'essential',
  },
  {
    name: 'any / all / none',
    category: 'functional',
    syntax: 'collection.any { } / .all { } / .none { }',
    description: 'Checks if any/all/none elements match predicate',
    example: { code: 'listOf(1, 2, 3).any { it > 2 }', output: 'true' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Short-circuits on first match/mismatch'],
    priority: 'common',
  },
  {
    name: 'count / sumOf',
    category: 'functional',
    syntax: 'list.count { predicate } / list.sumOf { selector }',
    description: 'Counts matching elements or sums selected values',
    example: { code: 'listOf("a", "bb").sumOf { it.length }', output: '3' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },
  {
    name: 'take / drop',
    category: 'functional',
    syntax: 'list.take(n) / list.drop(n)',
    description: 'Returns first n elements / returns list without first n',
    example: { code: 'listOf(1,2,3,4).take(2)', output: '[1, 2]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'common',
  },
  {
    name: 'distinct',
    category: 'functional',
    syntax: 'collection.distinct() / collection.distinctBy { }',
    description: 'Returns list with only distinct elements',
    example: { code: 'listOf(1, 1, 2, 2, 3).distinct()', output: '[1, 2, 3]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'common',
  },

  // ============ SORTING ============
  {
    name: 'sorted / sortedDescending',
    category: 'sorting',
    syntax: 'collection.sorted() / collection.sortedDescending()',
    description: 'Returns new list sorted in natural or reverse order',
    example: { code: 'listOf(3, 1, 2).sorted()', output: '[1, 2, 3]' },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns new list, does not modify original'],
    priority: 'essential',
  },
  {
    name: 'sortedWith / compareBy',
    category: 'sorting',
    syntax: 'list.sortedWith(compareBy { it.x })',
    description: 'Sorts with custom comparator; compareBy for multi-level sorting',
    example: {
      code: 'listOf("aa", "b").sortedWith(compareBy { it.length })',
      output: '["b", "aa"]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Multi-level: compareBy({ it.x }, { it.y })',
    priority: 'essential',
  },
  {
    name: 'binarySearch',
    category: 'sorting',
    syntax: 'list.binarySearch(element)',
    description: 'Searches sorted list; returns index or negative insertion point',
    example: { code: 'listOf(1, 3, 5).binarySearch(3)', output: '1' },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['List must be sorted; not found returns -(insertionPoint + 1)'],
    interviewTip: 'Insertion point = -(result + 1) when not found',
    priority: 'essential',
  },

  // ============ SCOPE FUNCTIONS ============
  {
    name: 'let',
    category: 'functional',
    syntax: 'obj?.let { it -> ... }',
    description: 'Executes block with object as "it", returns block result',
    example: { code: 'val len = "hello"?.let { it.length }', output: '5' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Perfect for null-safe operations with ?. operator',
    priority: 'essential',
  },
  {
    name: 'apply',
    category: 'functional',
    syntax: 'obj.apply { this -> ... }',
    description: 'Executes block with "this" context, returns the object itself',
    example: {
      code: 'val sb = StringBuilder().apply {\n  append("a")\n  append("b")\n}',
      output: 'StringBuilder("ab")',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Builder pattern - configure object and return it',
    priority: 'essential',
  },
  {
    name: 'also',
    category: 'functional',
    syntax: 'obj.also { it -> ... }',
    description: 'Executes block with object as "it", returns the object',
    example: {
      code: 'val nums = mutableListOf(1).also { println(it) }',
      output: '[1] (printed), nums=[1]',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use for side effects like logging while chaining',
    priority: 'common',
  },
  {
    name: 'run / with',
    category: 'functional',
    syntax: 'obj.run { } / with(obj) { }',
    description: 'Executes block with "this" context, returns block result',
    example: { code: 'val len = "hello".run { length }', output: '5' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'run is extension function; with takes object as argument',
    priority: 'common',
  },

  // ============ COLLECTIONS UTILITIES ============
  {
    name: 'maxOrNull / minOrNull',
    category: 'collections',
    syntax: 'collection.maxOrNull() / collection.maxByOrNull { }',
    description: 'Returns max/min element or null if empty',
    example: { code: 'listOf(1, 3, 2).maxOrNull()', output: '3' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns null on empty collection'],
    interviewTip: 'Use maxByOrNull { } for custom comparison',
    priority: 'essential',
  },
  {
    name: 'sum',
    category: 'collections',
    syntax: 'collection.sum()',
    description: 'Returns sum of all numeric elements',
    example: { code: 'listOf(1, 2, 3).sum()', output: '6' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use sumOf { } for custom numeric extraction',
    priority: 'essential',
  },
  {
    name: 'zip',
    category: 'collections',
    syntax: 'list1.zip(list2)',
    description: 'Returns list of pairs combining elements at same indices',
    example: { code: 'listOf(1, 2).zip(listOf("a", "b"))', output: '[(1, a), (2, b)]' },
    timeComplexity: 'O(min(n, m))',
    spaceComplexity: 'O(min(n, m))',
    gotchas: ['Result length is minimum of both lists'],
    priority: 'common',
  },
  {
    name: 'windowed',
    category: 'collections',
    syntax: 'collection.windowed(size, step)',
    description: 'Returns sliding windows of specified size',
    example: { code: 'listOf(1,2,3,4).windowed(2)', output: '[[1, 2], [2, 3], [3, 4]]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Perfect for sliding window problems',
    priority: 'useful',
  },
];
