/**
 * Lua Cheatsheet
 *
 * Essential Lua functions and patterns for coding interviews.
 * Covers table library, string library, math library, and common iteration patterns.
 */

import type { CheatsheetEntry } from './types';

export const luaCheatsheet: CheatsheetEntry[] = [
  // ============================================
  // TABLE LIBRARY (Arrays/Tables)
  // ============================================
  {
    name: 'table.insert',
    category: 'arrays',
    syntax: 'table.insert(t, [pos,] value)',
    description: 'Inserts value at position pos (default: end of table).',
    example: {
      code: 'local t = {1, 2, 3}\ntable.insert(t, 4)\ntable.insert(t, 2, 10)',
      output: '{1, 10, 2, 3, 4}',
    },
    timeComplexity: 'O(n) when inserting at position, O(1) at end',
    spaceComplexity: 'O(1)',
    gotchas: ['Modifies table in place', 'Position is optional - defaults to end'],
    interviewTip: 'Use for stack operations (push) or inserting at specific positions.',
    priority: 'essential',
  },
  {
    name: 'table.remove',
    category: 'arrays',
    syntax: 'table.remove(t [, pos])',
    description: 'Removes and returns element at position pos (default: last element).',
    example: {
      code: 'local t = {1, 2, 3, 4}\nlocal val = table.remove(t)  -- removes 4\nlocal val2 = table.remove(t, 1)  -- removes 1',
      output: 'val=4, val2=1, t={2, 3}',
    },
    timeComplexity: 'O(n) when removing from middle, O(1) from end',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns the removed value', 'Shifts remaining elements down'],
    interviewTip: 'Use for stack (pop) or queue operations.',
    priority: 'essential',
  },
  {
    name: 'table.concat',
    category: 'arrays',
    syntax: 'table.concat(t [, sep [, i [, j]]])',
    description: 'Concatenates table elements into a string with optional separator.',
    example: {
      code: 'local t = {"a", "b", "c"}\nprint(table.concat(t, "-"))',
      output: '"a-b-c"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Only works with string/number values', 'nil values cause error'],
    interviewTip: 'Efficient way to build strings from array of parts.',
    priority: 'essential',
  },
  {
    name: 'table.sort',
    category: 'sorting',
    syntax: 'table.sort(t [, comp])',
    description:
      'Sorts table in place. Optional comparison function returns true if first arg should come first.',
    example: {
      code: 'local t = {3, 1, 4, 1, 5}\ntable.sort(t)\n-- Custom: descending\ntable.sort(t, function(a, b) return a > b end)',
      output: '{1, 1, 3, 4, 5} or {5, 4, 3, 1, 1}',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(log n)',
    gotchas: [
      'Sorts in place, no return value',
      'Comparison must be consistent (no a < b and b < a)',
    ],
    interviewTip: 'Custom comparator is essential for sorting complex objects.',
    priority: 'essential',
  },
  {
    name: '#table (length)',
    category: 'arrays',
    syntax: '#t',
    description:
      'Returns the length of a sequence (table with consecutive integer keys starting at 1).',
    example: {
      code: 'local t = {10, 20, 30}\nprint(#t)',
      output: '3',
    },
    timeComplexity: 'O(1) for arrays, O(log n) for sparse tables',
    spaceComplexity: 'O(1)',
    gotchas: ['Only counts consecutive integer keys from 1', 'Undefined for tables with holes'],
    interviewTip: 'Use for array-like tables only. For hash tables, iterate to count.',
    priority: 'essential',
  },
  {
    name: 'table.unpack',
    category: 'arrays',
    syntax: 'table.unpack(t [, i [, j]])',
    description: 'Returns elements from table as multiple values.',
    example: {
      code: 'local t = {1, 2, 3}\nlocal a, b, c = table.unpack(t)\nprint(a, b, c)',
      output: '1  2  3',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['In Lua 5.1, use unpack() instead of table.unpack()'],
    interviewTip: 'Useful for passing table elements as function arguments.',
    priority: 'common',
  },
  {
    name: 'table.move',
    category: 'arrays',
    syntax: 'table.move(a1, f, e, t [, a2])',
    description: 'Moves elements from a1[f..e] to a2[t..], returns destination table.',
    example: {
      code: 'local t1 = {1, 2, 3}\nlocal t2 = {}\ntable.move(t1, 1, 3, 1, t2)',
      output: 't2 = {1, 2, 3}',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Lua 5.3+ only', 'Destination defaults to source table'],
    interviewTip: 'Efficient for copying array segments.',
    priority: 'useful',
  },

  // ============================================
  // ITERATION
  // ============================================
  {
    name: 'ipairs',
    category: 'iteration',
    syntax: 'for i, v in ipairs(t) do ... end',
    description: 'Iterates over array part of table (consecutive integer keys from 1).',
    example: {
      code: 'local t = {"a", "b", "c"}\nfor i, v in ipairs(t) do\n  print(i, v)\nend',
      output: '1 a\n2 b\n3 c',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Stops at first nil value', 'Only iterates numeric keys starting at 1'],
    interviewTip: 'Use for arrays when order matters and you need the index.',
    priority: 'essential',
  },
  {
    name: 'pairs',
    category: 'iteration',
    syntax: 'for k, v in pairs(t) do ... end',
    description: 'Iterates over all key-value pairs in a table.',
    example: {
      code: 'local t = {a = 1, b = 2, c = 3}\nfor k, v in pairs(t) do\n  print(k, v)\nend',
      output: 'a 1\nb 2\nc 3 (order not guaranteed)',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Order is not guaranteed', 'Includes both array and hash parts'],
    interviewTip: 'Use for hash tables or when you need all keys.',
    priority: 'essential',
  },
  {
    name: 'next',
    category: 'iteration',
    syntax: 'next(t [, index])',
    description: 'Returns next key-value pair after index, or first pair if index is nil.',
    example: {
      code: 'local t = {a = 1, b = 2}\nlocal k, v = next(t)\nprint(k, v)',
      output: 'a 1 (or b 2, order not defined)',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns nil when no more elements', 'Order is undefined'],
    interviewTip: 'Use next(t) == nil to check if table is empty.',
    priority: 'common',
  },

  // ============================================
  // STRING LIBRARY
  // ============================================
  {
    name: 'string.sub',
    category: 'strings',
    syntax: 'string.sub(s, i [, j])',
    description:
      'Returns substring from index i to j (default: end). Negative indices count from end.',
    example: {
      code: 'local s = "hello"\nprint(string.sub(s, 2, 4))\nprint(string.sub(s, -2))',
      output: '"ell"\n"lo"',
    },
    timeComplexity: 'O(j - i)',
    spaceComplexity: 'O(j - i)',
    gotchas: ['Indices are 1-based', 'Negative indices count from end (-1 is last char)'],
    interviewTip: 'Essential for string manipulation. Remember Lua is 1-indexed!',
    priority: 'essential',
  },
  {
    name: 'string.len / #string',
    category: 'strings',
    syntax: 'string.len(s) or #s',
    description: 'Returns the length of a string in bytes.',
    example: {
      code: 'local s = "hello"\nprint(#s)\nprint(string.len(s))',
      output: '5\n5',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns byte count, not character count for UTF-8'],
    interviewTip: '# operator is more idiomatic in modern Lua.',
    priority: 'essential',
  },
  {
    name: 'string.find',
    category: 'strings',
    syntax: 'string.find(s, pattern [, init [, plain]])',
    description: 'Finds first match of pattern. Returns start and end indices, plus captures.',
    example: {
      code: 'local s = "hello world"\nlocal i, j = string.find(s, "world")\nprint(i, j)',
      output: '7  11',
    },
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns nil if not found', 'Set plain=true to disable pattern matching'],
    interviewTip: 'Returns nil for no match - always check result.',
    priority: 'essential',
  },
  {
    name: 'string.match',
    category: 'strings',
    syntax: 'string.match(s, pattern [, init])',
    description: 'Returns captures from pattern match, or whole match if no captures.',
    example: {
      code: 'local s = "hello 123 world"\nlocal num = string.match(s, "%d+")\nprint(num)',
      output: '"123"',
    },
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(k) captures',
    gotchas: ['Returns nil if no match', 'Returns multiple values for multiple captures'],
    interviewTip: 'Use for extracting specific patterns from strings.',
    priority: 'essential',
  },
  {
    name: 'string.gmatch',
    category: 'strings',
    syntax: 'string.gmatch(s, pattern)',
    description: 'Returns iterator over all pattern matches in string.',
    example: {
      code: 'local s = "a1b2c3"\nfor digit in string.gmatch(s, "%d") do\n  print(digit)\nend',
      output: '1\n2\n3',
    },
    timeComplexity: 'O(n * m) total',
    spaceComplexity: 'O(1) per iteration',
    gotchas: ['Returns iterator, not table', 'Each call advances to next match'],
    interviewTip: 'Use for tokenizing strings or finding all matches.',
    priority: 'essential',
  },
  {
    name: 'string.gsub',
    category: 'strings',
    syntax: 'string.gsub(s, pattern, repl [, n])',
    description:
      'Returns string with pattern matches replaced. repl can be string, table, or function.',
    example: {
      code: 'local s = "hello world"\nlocal result = string.gsub(s, "world", "Lua")\nprint(result)',
      output: '"hello Lua"',
    },
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns modified string AND count of replacements', 'Original string unchanged'],
    interviewTip: 'Powerful for string transformations. Capture groups with %1, %2, etc.',
    priority: 'essential',
  },
  {
    name: 'string.format',
    category: 'strings',
    syntax: 'string.format(formatstring, ...)',
    description: 'Returns formatted string (similar to C printf).',
    example: {
      code: 'local s = string.format("Name: %s, Age: %d", "Bob", 25)\nprint(s)',
      output: '"Name: Bob, Age: 25"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['%s for strings, %d for integers, %f for floats', '%q quotes strings with escapes'],
    interviewTip: 'Use for building formatted output strings.',
    priority: 'common',
  },
  {
    name: 'string.byte',
    category: 'strings',
    syntax: 'string.byte(s [, i [, j]])',
    description: 'Returns numeric byte values of characters s[i] through s[j].',
    example: {
      code: 'local s = "ABC"\nprint(string.byte(s, 1))\nprint(string.byte(s, 1, 3))',
      output: '65\n65 66 67',
    },
    timeComplexity: 'O(j - i)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns ASCII/byte value, not character', 'Multiple values for range'],
    interviewTip: 'Useful for character manipulation and ASCII comparisons.',
    priority: 'common',
  },
  {
    name: 'string.char',
    category: 'strings',
    syntax: 'string.char(...)',
    description: 'Returns string from numeric byte values.',
    example: {
      code: 'print(string.char(65, 66, 67))',
      output: '"ABC"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Arguments must be valid byte values (0-255)'],
    interviewTip: 'Inverse of string.byte. Use for building strings from ASCII codes.',
    priority: 'common',
  },
  {
    name: 'string.rep',
    category: 'strings',
    syntax: 'string.rep(s, n [, sep])',
    description: 'Returns string s repeated n times, with optional separator.',
    example: {
      code: 'print(string.rep("ab", 3))\nprint(string.rep("x", 3, "-"))',
      output: '"ababab"\n"x-x-x"',
    },
    timeComplexity: 'O(n * len(s))',
    spaceComplexity: 'O(n * len(s))',
    gotchas: ['sep parameter is Lua 5.2+'],
    interviewTip: 'Useful for creating repeated patterns or padding.',
    priority: 'common',
  },
  {
    name: 'string.reverse',
    category: 'strings',
    syntax: 'string.reverse(s)',
    description: 'Returns reversed string.',
    example: {
      code: 'print(string.reverse("hello"))',
      output: '"olleh"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Creates new string, does not modify original'],
    interviewTip: 'Useful for palindrome checks and string algorithms.',
    priority: 'common',
  },
  {
    name: 'string.upper / string.lower',
    category: 'strings',
    syntax: 'string.upper(s) / string.lower(s)',
    description: 'Returns uppercase/lowercase version of string.',
    example: {
      code: 'print(string.upper("Hello"))\nprint(string.lower("Hello"))',
      output: '"HELLO"\n"hello"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Only affects ASCII letters by default'],
    interviewTip: 'Use for case-insensitive comparisons.',
    priority: 'common',
  },

  // ============================================
  // MATH LIBRARY
  // ============================================
  {
    name: 'math.max / math.min',
    category: 'math',
    syntax: 'math.max(...) / math.min(...)',
    description: 'Returns maximum/minimum of arguments.',
    example: {
      code: 'print(math.max(1, 5, 3))\nprint(math.min(1, 5, 3))',
      output: '5\n1',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Takes multiple arguments, not a table', 'Use table.unpack for tables'],
    interviewTip: 'For tables: math.max(table.unpack(t))',
    priority: 'essential',
  },
  {
    name: 'math.floor / math.ceil',
    category: 'math',
    syntax: 'math.floor(x) / math.ceil(x)',
    description: 'Rounds down/up to nearest integer.',
    example: {
      code: 'print(math.floor(3.7))\nprint(math.ceil(3.2))',
      output: '3\n4',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns integer type in Lua 5.3+'],
    interviewTip: 'Use floor for integer division: math.floor(a / b)',
    priority: 'essential',
  },
  {
    name: 'math.abs',
    category: 'math',
    syntax: 'math.abs(x)',
    description: 'Returns absolute value of x.',
    example: {
      code: 'print(math.abs(-5))\nprint(math.abs(5))',
      output: '5\n5',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Essential for distance calculations and comparisons.',
    priority: 'essential',
  },
  {
    name: 'math.sqrt',
    category: 'math',
    syntax: 'math.sqrt(x)',
    description: 'Returns square root of x.',
    example: {
      code: 'print(math.sqrt(16))\nprint(math.sqrt(2))',
      output: '4\n1.4142135623731',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns float', 'Domain error for negative numbers'],
    interviewTip: 'Use for distance formulas and prime checking optimizations.',
    priority: 'common',
  },
  {
    name: 'math.random',
    category: 'math',
    syntax: 'math.random([m [, n]])',
    description: 'Returns random number. No args: [0,1). One arg: [1,m]. Two args: [m,n].',
    example: {
      code: 'print(math.random())      -- 0 to 1\nprint(math.random(10))    -- 1 to 10\nprint(math.random(5, 10)) -- 5 to 10',
      output: '0.84018...\n7\n8',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Call math.randomseed() first for non-deterministic results'],
    interviewTip: 'Use for shuffling arrays or random sampling.',
    priority: 'common',
  },
  {
    name: 'math.randomseed',
    category: 'math',
    syntax: 'math.randomseed(x)',
    description: 'Sets seed for random number generator.',
    example: {
      code: 'math.randomseed(os.time())\nprint(math.random(100))',
      output: '(random number 1-100)',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Call once at program start', 'Same seed produces same sequence'],
    interviewTip: 'Use os.time() for pseudo-random behavior.',
    priority: 'common',
  },
  {
    name: 'math.huge',
    category: 'math',
    syntax: 'math.huge',
    description: 'Represents positive infinity.',
    example: {
      code: 'local minVal = math.huge\nfor _, v in ipairs({3, 1, 4}) do\n  minVal = math.min(minVal, v)\nend',
      output: 'minVal = 1',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['-math.huge for negative infinity'],
    interviewTip: 'Initialize min/max searches with math.huge/-math.huge.',
    priority: 'essential',
  },
  {
    name: 'math.fmod',
    category: 'math',
    syntax: 'math.fmod(x, y)',
    description: 'Returns remainder of x/y (same sign as x).',
    example: {
      code: 'print(math.fmod(7, 3))\nprint(math.fmod(-7, 3))',
      output: '1\n-1',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Different from % operator for negative numbers'],
    interviewTip: 'Use % operator for most cases, fmod for float precision.',
    priority: 'useful',
  },
  {
    name: 'math.modf',
    category: 'math',
    syntax: 'math.modf(x)',
    description: 'Returns integral and fractional parts of x.',
    example: {
      code: 'local int, frac = math.modf(3.14)\nprint(int, frac)',
      output: '3  0.14',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Useful for separating integer and decimal parts.',
    priority: 'useful',
  },
  {
    name: 'math.pow / ^ operator',
    category: 'math',
    syntax: 'math.pow(x, y) or x ^ y',
    description: 'Returns x raised to power y.',
    example: {
      code: 'print(2 ^ 10)\nprint(math.pow(2, 10))',
      output: '1024\n1024',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['^ operator is more idiomatic'],
    interviewTip: 'Use for exponential calculations and bit manipulation tricks.',
    priority: 'common',
  },
  {
    name: 'math.log',
    category: 'math',
    syntax: 'math.log(x [, base])',
    description: 'Returns logarithm of x. Default base is e (natural log).',
    example: {
      code: 'print(math.log(10))      -- natural log\nprint(math.log(8, 2))    -- log base 2',
      output: '2.302585...\n3',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Base parameter is Lua 5.2+', 'Use math.log(x)/math.log(base) for 5.1'],
    interviewTip: 'Useful for binary search analysis and logarithmic algorithms.',
    priority: 'useful',
  },

  // ============================================
  // TYPE CONVERSION & CHECKING
  // ============================================
  {
    name: 'tonumber',
    category: 'type-conversion',
    syntax: 'tonumber(e [, base])',
    description: 'Converts value to number. Returns nil if conversion fails.',
    example: {
      code: 'print(tonumber("42"))\nprint(tonumber("FF", 16))\nprint(tonumber("hello"))',
      output: '42\n255\nnil',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns nil for invalid input, not error', 'Base can be 2-36'],
    interviewTip: 'Always check for nil when converting user input.',
    priority: 'essential',
  },
  {
    name: 'tostring',
    category: 'type-conversion',
    syntax: 'tostring(v)',
    description: 'Converts value to string representation.',
    example: {
      code: 'print(tostring(42))\nprint(tostring(true))\nprint(tostring(nil))',
      output: '"42"\n"true"\n"nil"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Tables show address unless __tostring metamethod defined'],
    interviewTip: 'Use for concatenation with .. operator.',
    priority: 'essential',
  },
  {
    name: 'type',
    category: 'type-conversion',
    syntax: 'type(v)',
    description: 'Returns type of value as string.',
    example: {
      code: 'print(type(42))\nprint(type("hello"))\nprint(type({}))\nprint(type(nil))',
      output: '"number"\n"string"\n"table"\n"nil"',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns string, not type object'],
    interviewTip: 'Use for input validation and polymorphic functions.',
    priority: 'essential',
  },

  // ============================================
  // COMMON PATTERNS
  // ============================================
  {
    name: 'rawget / rawset',
    category: 'arrays',
    syntax: 'rawget(t, k) / rawset(t, k, v)',
    description: 'Gets/sets table value bypassing metamethods.',
    example: {
      code: 'local t = {}\nrawset(t, "key", "value")\nprint(rawget(t, "key"))',
      output: '"value"',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Bypasses __index and __newindex metamethods'],
    interviewTip: 'Use when implementing custom table behaviors.',
    priority: 'useful',
  },
  {
    name: 'setmetatable / getmetatable',
    category: 'objects',
    syntax: 'setmetatable(t, mt) / getmetatable(t)',
    description: 'Sets/gets metatable for table. Metatables control table behavior.',
    example: {
      code: 'local t = {}\nlocal mt = {__index = function(t, k) return "default" end}\nsetmetatable(t, mt)\nprint(t.anything)',
      output: '"default"',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Can only set one metatable per table', '__metatable protects from getmetatable'],
    interviewTip: 'Foundation for OOP in Lua. Understand __index and __newindex.',
    priority: 'common',
  },
  {
    name: 'select',
    category: 'functional',
    syntax: 'select(index, ...) or select("#", ...)',
    description: 'Returns arguments after index, or count of arguments with "#".',
    example: {
      code: 'print(select(2, "a", "b", "c"))\nprint(select("#", "a", "b", "c"))',
      output: 'b  c\n3',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Negative index counts from end', 'Preserves nil values in varargs'],
    interviewTip: 'Use select("#", ...) to count varargs including nils.',
    priority: 'common',
  },
  {
    name: 'pcall',
    category: 'error-handling',
    syntax: 'pcall(f, arg1, ...)',
    description: 'Calls function in protected mode. Returns success boolean and results/error.',
    example: {
      code: 'local ok, result = pcall(function() return 1/0 end)\nprint(ok, result)\nlocal ok2, err = pcall(function() error("oops") end)\nprint(ok2, err)',
      output: 'true  inf\nfalse  oops',
    },
    timeComplexity: 'O(1) + function time',
    spaceComplexity: 'O(1)',
    gotchas: ['First return is always boolean', 'Error message in second return on failure'],
    interviewTip: 'Use for graceful error handling without crashing.',
    priority: 'common',
  },
  {
    name: 'assert',
    category: 'error-handling',
    syntax: 'assert(v [, message])',
    description: 'Raises error if v is false or nil, otherwise returns v.',
    example: {
      code: 'local x = assert(tonumber("42"), "Invalid number")\nprint(x)',
      output: '42',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns all values passed to it if assertion passes'],
    interviewTip: 'Use for precondition checking and input validation.',
    priority: 'common',
  },
  {
    name: 'error',
    category: 'error-handling',
    syntax: 'error(message [, level])',
    description: 'Raises an error with given message. Level affects error position in traceback.',
    example: {
      code: 'function validate(x)\n  if x < 0 then error("Negative not allowed", 2) end\nend',
      output: '(throws error)',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Level 1 is current function, 2 is caller'],
    interviewTip: 'Use level 2 to report error at caller location.',
    priority: 'common',
  },

  // ============================================
  // ADDITIONAL USEFUL FUNCTIONS
  // ============================================
  {
    name: 'collectgarbage',
    category: 'memory',
    syntax: 'collectgarbage([opt [, arg]])',
    description: 'Controls garbage collector. "collect" runs full GC cycle.',
    example: {
      code: 'collectgarbage("collect")\nprint(collectgarbage("count"))',
      output: '(memory in KB)',
    },
    timeComplexity: 'O(n) heap size',
    spaceComplexity: 'O(1)',
    gotchas: ['Usually not needed in interviews', '"count" returns memory in KB'],
    interviewTip: 'Rarely needed, but know it exists for memory-constrained problems.',
    priority: 'useful',
  },
  {
    name: 'load / loadstring',
    category: 'functional',
    syntax: 'load(chunk [, chunkname [, mode [, env]]])',
    description: 'Compiles string/function as Lua chunk, returns function or nil+error.',
    example: {
      code: 'local f = load("return 1 + 2")\nprint(f())',
      output: '3',
    },
    timeComplexity: 'O(n) chunk size',
    spaceComplexity: 'O(n)',
    gotchas: ['loadstring deprecated in Lua 5.2+, use load', 'Security risk with untrusted input'],
    interviewTip: 'Powerful but rarely needed. Know it exists for dynamic code.',
    priority: 'useful',
  },
  {
    name: 'os.time / os.date',
    category: 'date-time',
    syntax: 'os.time([table]) / os.date([format [, time]])',
    description: 'os.time returns Unix timestamp. os.date formats time.',
    example: {
      code: 'print(os.time())\nprint(os.date("%Y-%m-%d", os.time()))',
      output: '1706000000\n"2024-01-23"',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['os.date("*t", time) returns table with year, month, day, etc.'],
    interviewTip: 'Use for timestamp calculations and date formatting.',
    priority: 'useful',
  },
  {
    name: 'os.clock',
    category: 'date-time',
    syntax: 'os.clock()',
    description: 'Returns CPU time used by program in seconds.',
    example: {
      code: 'local start = os.clock()\n-- do work\nprint(os.clock() - start)',
      output: '0.001234',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Measures CPU time, not wall time'],
    interviewTip: 'Use for benchmarking algorithm performance.',
    priority: 'useful',
  },
  {
    name: 'print',
    category: 'io',
    syntax: 'print(...)',
    description: 'Prints values to stdout separated by tabs, with newline.',
    example: {
      code: 'print("Hello", 42, true)',
      output: 'Hello\t42\ttrue',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Uses tostring on each argument', 'Not suitable for formatted output'],
    interviewTip: 'Use for quick debugging. Use io.write for no newline.',
    priority: 'essential',
  },
  {
    name: 'io.read',
    category: 'io',
    syntax: 'io.read([format1, ...])',
    description: 'Reads from stdin. "*l" for line, "*n" for number, "*a" for all.',
    example: {
      code: 'local line = io.read("*l")\nlocal num = io.read("*n")',
      output: '(reads from stdin)',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['*l is default and strips newline', '*L includes newline'],
    interviewTip: 'Know formats for reading different input types.',
    priority: 'common',
  },
  {
    name: 'Pattern: Deep Copy',
    category: 'arrays',
    syntax: 'function deepcopy(t) ... end',
    description: 'Recursively copies table and all nested tables.',
    example: {
      code: 'local function deepcopy(t)\n  if type(t) ~= "table" then return t end\n  local copy = {}\n  for k, v in pairs(t) do\n    copy[deepcopy(k)] = deepcopy(v)\n  end\n  return copy\nend',
      output: '(new independent table copy)',
    },
    timeComplexity: 'O(n) total elements',
    spaceComplexity: 'O(n)',
    gotchas: ['Simple version does not handle cycles or metatables'],
    interviewTip: 'Know how to implement - Lua has no built-in deep copy.',
    priority: 'essential',
  },
  {
    name: 'Pattern: Table Contains',
    category: 'searching',
    syntax: 'function contains(t, value) ... end',
    description: 'Checks if array-like table contains a value.',
    example: {
      code: 'local function contains(t, val)\n  for _, v in ipairs(t) do\n    if v == val then return true end\n  end\n  return false\nend',
      output: 'true or false',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['No built-in function - must implement'],
    interviewTip: 'For frequent lookups, convert array to hash table for O(1).',
    priority: 'essential',
  },
  {
    name: 'Pattern: Table Keys',
    category: 'arrays',
    syntax: 'function keys(t) ... end',
    description: 'Returns array of all keys in a table.',
    example: {
      code: 'local function keys(t)\n  local result = {}\n  for k in pairs(t) do\n    result[#result + 1] = k\n  end\n  return result\nend',
      output: 'array of keys',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Order not guaranteed for hash tables'],
    interviewTip: 'Useful pattern for iterating keys separately from values.',
    priority: 'common',
  },
  {
    name: 'Pattern: Table Values',
    category: 'arrays',
    syntax: 'function values(t) ... end',
    description: 'Returns array of all values in a table.',
    example: {
      code: 'local function values(t)\n  local result = {}\n  for _, v in pairs(t) do\n    result[#result + 1] = v\n  end\n  return result\nend',
      output: 'array of values',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Order not guaranteed for hash tables'],
    interviewTip: 'Use when you need values without keys.',
    priority: 'common',
  },
  {
    name: 'Pattern: String Split',
    category: 'strings',
    syntax: 'function split(s, sep) ... end',
    description: 'Splits string by separator into array of substrings.',
    example: {
      code: 'local function split(s, sep)\n  local result = {}\n  for part in string.gmatch(s, "[^" .. sep .. "]+") do\n    result[#result + 1] = part\n  end\n  return result\nend',
      output: 'array of substrings',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['No built-in split function in Lua', 'Pattern escaping needed for special chars'],
    interviewTip: 'Essential pattern - Lua lacks built-in string split.',
    priority: 'essential',
  },
];
