/**
 * Perl Cheatsheet
 *
 * Essential Perl functions and operations for coding interviews.
 * Covers arrays, hashes, strings, regex, sorting, and functional operations.
 */

import type { CheatsheetEntry } from './types';

export const perlCheatsheet: CheatsheetEntry[] = [
  // ==================== ARRAYS ====================
  {
    name: 'push',
    category: 'arrays',
    syntax: 'push(@array, $value)',
    description: 'Append one or more elements to the end of an array',
    example: { code: 'my @arr = (1, 2);\npush(@arr, 3, 4);\nprint "@arr";', output: '1 2 3 4' },
    timeComplexity: 'O(1) amortized',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns the new length of the array, not the array itself'],
    interviewTip: 'Use push for stack operations (LIFO with pop)',
    priority: 'essential',
  },
  {
    name: 'pop',
    category: 'arrays',
    syntax: 'pop(@array)',
    description: 'Remove and return the last element of an array',
    example: {
      code: 'my @arr = (1, 2, 3);\nmy $last = pop(@arr);\nprint "$last, @arr";',
      output: '3, 1 2',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns undef if array is empty'],
    interviewTip: 'Combine with push for stack implementation',
    priority: 'essential',
  },
  {
    name: 'shift',
    category: 'arrays',
    syntax: 'shift(@array)',
    description: 'Remove and return the first element of an array',
    example: {
      code: 'my @arr = (1, 2, 3);\nmy $first = shift(@arr);\nprint "$first, @arr";',
      output: '1, 2 3',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['O(n) because all elements must be shifted down'],
    interviewTip: 'Use for queue operations (FIFO with push)',
    priority: 'essential',
  },
  {
    name: 'unshift',
    category: 'arrays',
    syntax: 'unshift(@array, $value)',
    description: 'Prepend one or more elements to the beginning of an array',
    example: { code: 'my @arr = (2, 3);\nunshift(@arr, 0, 1);\nprint "@arr";', output: '0 1 2 3' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns the new length, O(n) due to shifting all elements'],
    interviewTip: 'Avoid in performance-critical loops',
    priority: 'essential',
  },
  {
    name: 'splice',
    category: 'arrays',
    syntax: 'splice(@array, $offset, $length, @list)',
    description: 'Remove and/or add elements at any position in an array',
    example: {
      code: 'my @arr = (1, 2, 3, 4);\nmy @removed = splice(@arr, 1, 2, "a", "b");\nprint "@arr | @removed";',
      output: '1 a b 4 | 2 3',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(k) where k is removed elements',
    gotchas: ['Negative offset counts from end', 'Modifies the original array'],
    interviewTip: 'Swiss army knife for array manipulation - insert, delete, or replace',
    priority: 'essential',
  },
  {
    name: 'reverse',
    category: 'arrays',
    syntax: 'reverse(@array)',
    description: 'Return elements in reverse order (does not modify original)',
    example: {
      code: 'my @arr = (1, 2, 3);\nmy @rev = reverse(@arr);\nprint "@rev";',
      output: '3 2 1',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns a new list, does not modify in place', 'Also works on strings'],
    interviewTip: 'Use @arr = reverse(@arr) to reverse in place',
    priority: 'common',
  },
  {
    name: 'scalar',
    category: 'arrays',
    syntax: 'scalar(@array)',
    description: 'Return the number of elements in an array',
    example: { code: 'my @arr = (1, 2, 3, 4, 5);\nprint scalar(@arr);', output: '5' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Also triggered by scalar context: my $len = @arr;'],
    interviewTip: '$#array gives last index (length - 1)',
    priority: 'essential',
  },
  {
    name: 'join',
    category: 'arrays',
    syntax: 'join($separator, @array)',
    description: 'Concatenate array elements into a string with separator',
    example: { code: 'my @arr = ("a", "b", "c");\nprint join("-", @arr);', output: 'a-b-c' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Separator comes first, unlike many other languages'],
    interviewTip: 'Opposite of split - use together for string transformations',
    priority: 'essential',
  },
  {
    name: 'split',
    category: 'strings',
    syntax: 'split(/pattern/, $string, $limit)',
    description: 'Split a string into an array based on a pattern',
    example: {
      code: 'my $str = "a,b,c";\nmy @arr = split(/,/, $str);\nprint "@arr";',
      output: 'a b c',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: [
      'Use // for empty pattern to split into characters',
      'Trailing empty strings are removed by default',
    ],
    interviewTip: 'split(//, $str) splits into individual characters',
    priority: 'essential',
  },
  {
    name: 'sort',
    category: 'sorting',
    syntax: 'sort { $a <=> $b } @array',
    description: 'Return sorted list (default: lexicographic order)',
    example: {
      code: 'my @arr = (3, 1, 4, 1, 5);\nmy @sorted = sort { $a <=> $b } @arr;\nprint "@sorted";',
      output: '1 1 3 4 5',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Default sort is string comparison!', 'Use <=> for numeric, cmp for string'],
    interviewTip: 'Remember: $a <=> $b for ascending, $b <=> $a for descending',
    priority: 'essential',
  },
  {
    name: 'grep',
    category: 'functional',
    syntax: 'grep { condition } @array',
    description: 'Filter array elements based on a condition (like filter)',
    example: {
      code: 'my @arr = (1, 2, 3, 4, 5);\nmy @evens = grep { $_ % 2 == 0 } @arr;\nprint "@evens";',
      output: '2 4',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(k) where k is matching elements',
    gotchas: [
      '$_ is the current element in the block',
      'Returns list in list context, count in scalar context',
    ],
    interviewTip: 'grep { /pattern/ } for regex filtering',
    priority: 'essential',
  },
  {
    name: 'map',
    category: 'functional',
    syntax: 'map { expression } @array',
    description: 'Transform each element of an array',
    example: {
      code: 'my @arr = (1, 2, 3);\nmy @squared = map { $_ ** 2 } @arr;\nprint "@squared";',
      output: '1 4 9',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['$_ is the current element', 'Can return multiple values per iteration'],
    interviewTip: 'map can flatten: map { ($_, $_*2) } (1,2) returns (1,2,2,4)',
    priority: 'essential',
  },
  {
    name: 'reduce',
    category: 'functional',
    syntax: 'use List::Util qw(reduce);\nreduce { $a + $b } @array',
    description: 'Reduce array to single value by applying function cumulatively',
    example: {
      code: 'use List::Util qw(reduce);\nmy @arr = (1, 2, 3, 4);\nmy $sum = reduce { $a + $b } @arr;\nprint $sum;',
      output: '10',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Requires List::Util module', '$a is accumulator, $b is current element'],
    interviewTip: 'Use for sum, product, min, max operations',
    priority: 'common',
  },
  {
    name: 'first',
    category: 'functional',
    syntax: 'use List::Util qw(first);\nfirst { condition } @array',
    description: 'Return the first element matching a condition',
    example: {
      code: 'use List::Util qw(first);\nmy @arr = (1, 4, 9, 16);\nmy $found = first { $_ > 5 } @arr;\nprint $found;',
      output: '9',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns undef if no match found', 'Short-circuits on first match'],
    interviewTip: 'More efficient than (grep { cond } @arr)[0] since it stops early',
    priority: 'common',
  },
  {
    name: 'any',
    category: 'functional',
    syntax: 'use List::Util qw(any);\nany { condition } @array',
    description: 'Return true if any element matches the condition',
    example: {
      code: 'use List::Util qw(any);\nmy @arr = (1, 2, 3, 4);\nprint any { $_ > 3 } @arr;',
      output: '1',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Short-circuits on first true', 'Returns 1 or empty string'],
    interviewTip: 'Use for existence checks without needing the actual element',
    priority: 'common',
  },
  {
    name: 'all',
    category: 'functional',
    syntax: 'use List::Util qw(all);\nall { condition } @array',
    description: 'Return true if all elements match the condition',
    example: {
      code: 'use List::Util qw(all);\nmy @arr = (2, 4, 6);\nprint all { $_ % 2 == 0 } @arr;',
      output: '1',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Short-circuits on first false', 'Returns true for empty array'],
    interviewTip: 'Use for validation checks on entire arrays',
    priority: 'common',
  },
  // ==================== HASHES (OBJECTS) ====================
  {
    name: 'keys',
    category: 'objects',
    syntax: 'keys(%hash)',
    description: 'Return a list of all keys in a hash',
    example: { code: 'my %h = (a => 1, b => 2);\nmy @k = keys(%h);\nprint "@k";', output: 'a b' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Order is not guaranteed (hash order)', 'scalar(keys %h) returns count'],
    interviewTip: 'Use for iterating over hash keys',
    priority: 'essential',
  },
  {
    name: 'values',
    category: 'objects',
    syntax: 'values(%hash)',
    description: 'Return a list of all values in a hash',
    example: { code: 'my %h = (a => 1, b => 2);\nmy @v = values(%h);\nprint "@v";', output: '1 2' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Order corresponds to keys order'],
    interviewTip: 'Useful when you only need values, not keys',
    priority: 'essential',
  },
  {
    name: 'each',
    category: 'objects',
    syntax: 'each(%hash)',
    description: 'Return next key-value pair as a list',
    example: {
      code: 'my %h = (a => 1, b => 2);\nwhile (my ($k, $v) = each %h) {\n  print "$k:$v ";\n}',
      output: 'a:1 b:2 ',
    },
    timeComplexity: 'O(1) per call',
    spaceComplexity: 'O(1)',
    gotchas: [
      'Internal iterator - mixing with keys/values can cause issues',
      'Reset with keys(%hash) in void context',
    ],
    interviewTip: 'for my $k (keys %h) is often safer than each',
    priority: 'common',
  },
  {
    name: 'exists',
    category: 'objects',
    syntax: 'exists($hash{$key})',
    description: 'Check if a key exists in a hash',
    example: {
      code: 'my %h = (a => 1, b => undef);\nprint exists($h{a}), exists($h{b}), exists($h{c});',
      output: '110',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns true even if value is undef', 'Different from defined($h{$key})'],
    interviewTip: 'exists checks key presence, defined checks if value is not undef',
    priority: 'essential',
  },
  {
    name: 'delete',
    category: 'objects',
    syntax: 'delete($hash{$key})',
    description: 'Remove a key-value pair from a hash',
    example: {
      code: 'my %h = (a => 1, b => 2);\nmy $val = delete($h{a});\nprint "$val, ", exists($h{a});',
      output: '1, ',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns the deleted value', 'Can delete from arrays too (leaves undef)'],
    interviewTip: 'Use for removing entries while potentially using the removed value',
    priority: 'essential',
  },
  {
    name: '%hash = ()',
    category: 'objects',
    syntax: '%hash = ()',
    description: 'Clear all entries from a hash',
    example: { code: 'my %h = (a => 1, b => 2);\n%h = ();\nprint scalar(keys %h);', output: '0' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Also works with undef %hash but that is deprecated'],
    interviewTip: 'Fastest way to empty a hash',
    priority: 'common',
  },
  // ==================== STRINGS ====================
  {
    name: 'length',
    category: 'strings',
    syntax: 'length($string)',
    description: 'Return the number of characters in a string',
    example: { code: 'my $str = "hello";\nprint length($str);', output: '5' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns bytes in older Perl without use utf8', 'Use on arrays to get element count'],
    interviewTip: 'Use length for strings, scalar for arrays',
    priority: 'essential',
  },
  {
    name: 'substr',
    category: 'strings',
    syntax: 'substr($string, $offset, $length, $replacement)',
    description: 'Extract or replace a substring',
    example: { code: 'my $str = "Hello World";\nprint substr($str, 0, 5);', output: 'Hello' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n) for extraction',
    gotchas: ['Negative offset counts from end', 'Can be used as lvalue: substr($s, 0, 1) = "X"'],
    interviewTip: 'substr($s, -3) gets last 3 characters',
    priority: 'essential',
  },
  {
    name: 'index',
    category: 'strings',
    syntax: 'index($string, $substring, $position)',
    description: 'Find position of substring (returns -1 if not found)',
    example: { code: 'my $str = "hello world";\nprint index($str, "o");', output: '4' },
    timeComplexity: 'O(n*m)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns -1 (not undef) if not found', 'Case sensitive'],
    interviewTip: 'Use optional third arg for finding multiple occurrences',
    priority: 'essential',
  },
  {
    name: 'rindex',
    category: 'strings',
    syntax: 'rindex($string, $substring, $position)',
    description: 'Find last position of substring',
    example: { code: 'my $str = "hello world";\nprint rindex($str, "o");', output: '7' },
    timeComplexity: 'O(n*m)',
    spaceComplexity: 'O(1)',
    gotchas: ['Searches from right to left', 'Returns -1 if not found'],
    interviewTip: 'Use for finding last occurrence in a string',
    priority: 'common',
  },
  {
    name: 'uc',
    category: 'strings',
    syntax: 'uc($string)',
    description: 'Convert string to uppercase',
    example: { code: 'print uc("hello");', output: 'HELLO' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns a new string', 'Also: ucfirst for first char only'],
    interviewTip: 'Use for case-insensitive comparisons',
    priority: 'common',
  },
  {
    name: 'lc',
    category: 'strings',
    syntax: 'lc($string)',
    description: 'Convert string to lowercase',
    example: { code: 'print lc("HELLO");', output: 'hello' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns a new string', 'Also: lcfirst for first char only'],
    interviewTip: 'Normalize strings before comparison: lc($a) eq lc($b)',
    priority: 'common',
  },
  {
    name: 'chomp',
    category: 'strings',
    syntax: 'chomp($string)',
    description: 'Remove trailing newline from string (modifies in place)',
    example: { code: 'my $str = "hello\\n";\nchomp($str);\nprint "$str|";', output: 'hello|' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Modifies the variable in place', 'Returns number of characters removed'],
    interviewTip: 'Essential when reading lines from files',
    priority: 'essential',
  },
  {
    name: 'chop',
    category: 'strings',
    syntax: 'chop($string)',
    description: 'Remove and return last character (modifies in place)',
    example: {
      code: 'my $str = "hello";\nmy $ch = chop($str);\nprint "$str, $ch";',
      output: 'hell, o',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Removes ANY last character, not just newline', 'Use chomp for newlines'],
    interviewTip: 'chop is indiscriminate - prefer chomp for newlines',
    priority: 'useful',
  },
  {
    name: 'sprintf',
    category: 'strings',
    syntax: 'sprintf($format, @values)',
    description: 'Return formatted string (C-style formatting)',
    example: {
      code: 'my $s = sprintf("%05d %.2f", 42, 3.14159);\nprint $s;',
      output: '00042 3.14',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['%s for strings, %d for integers, %f for floats', '%% for literal percent'],
    interviewTip: 'Use for precise number formatting and padding',
    priority: 'common',
  },
  // ==================== REGEX ====================
  {
    name: 'm// (match)',
    category: 'regex',
    syntax: '$string =~ m/pattern/flags',
    description: 'Test if pattern matches string',
    example: {
      code: 'my $str = "hello world";\nprint $str =~ /world/ ? "yes" : "no";',
      output: 'yes',
    },
    timeComplexity: 'O(n) to O(n*m)',
    spaceComplexity: 'O(1)',
    gotchas: ['m is optional if using /', 'Returns list of captures in list context'],
    interviewTip: 'Use //i for case-insensitive, //g for global',
    priority: 'essential',
  },
  {
    name: 's/// (substitute)',
    category: 'regex',
    syntax: '$string =~ s/pattern/replacement/flags',
    description: 'Search and replace pattern in string',
    example: {
      code: 'my $str = "hello world";\n$str =~ s/world/perl/;\nprint $str;',
      output: 'hello perl',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Modifies string in place', 'Use /g for global replace, /r to return new string'],
    interviewTip: 's///r returns modified copy without changing original (Perl 5.14+)',
    priority: 'essential',
  },
  {
    name: 'tr/// (transliterate)',
    category: 'regex',
    syntax: '$string =~ tr/search/replace/',
    description: 'Character-by-character translation',
    example: { code: 'my $str = "hello";\n$str =~ tr/a-z/A-Z/;\nprint $str;', output: 'HELLO' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Not regex - character mapping only', 'Returns count of translations'],
    interviewTip: 'tr/a-zA-Z//d removes all letters, tr/a-z//s squashes runs',
    priority: 'common',
  },
  {
    name: 'qw//',
    category: 'arrays',
    syntax: 'qw/word1 word2 word3/',
    description: 'Quote words - create list from whitespace-separated words',
    example: {
      code: 'my @arr = qw/apple banana cherry/;\nprint "@arr";',
      output: 'apple banana cherry',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['No commas or quotes needed', 'Can use any delimiter: qw(), qw{}, qw[]'],
    interviewTip: 'Cleaner than ("apple", "banana", "cherry")',
    priority: 'common',
  },
  {
    name: 'captures ($1, $2)',
    category: 'regex',
    syntax: 'if ($str =~ /(w+)/) { print $1; }',
    description: 'Access captured groups from regex match',
    example: {
      code: 'my $str = "name: John";\nif ($str =~ /name: (\\w+)/) {\n  print $1;\n}',
      output: 'John',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(k) for k captures',
    gotchas: [
      '$1, $2, etc. are global and persist until next successful match',
      'Use (?:...) for non-capturing groups',
    ],
    interviewTip: 'Always check match succeeded before using $1, $2',
    priority: 'essential',
  },
  // ==================== MATH ====================
  {
    name: 'int',
    category: 'math',
    syntax: 'int($number)',
    description: 'Truncate to integer (toward zero)',
    example: { code: 'print int(4.7), " ", int(-4.7);', output: '4 -4' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Truncates toward zero, not floor', 'int(-4.7) is -4, not -5'],
    interviewTip: 'Use POSIX::floor for true floor function',
    priority: 'essential',
  },
  {
    name: 'abs',
    category: 'math',
    syntax: 'abs($number)',
    description: 'Return absolute value',
    example: { code: 'print abs(-5), " ", abs(5);', output: '5 5' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Works on integers and floats'],
    interviewTip: 'Use for distance calculations',
    priority: 'common',
  },
  {
    name: 'sqrt',
    category: 'math',
    syntax: 'sqrt($number)',
    description: 'Return square root',
    example: { code: 'print sqrt(16);', output: '4' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns NaN for negative numbers', 'Use ** 0.5 as alternative'],
    interviewTip: 'Useful for distance formulas',
    priority: 'useful',
  },
  {
    name: 'rand',
    category: 'math',
    syntax: 'rand($max)',
    description: 'Return random float between 0 and max (default 1)',
    example: { code: 'srand(42);\nprint int(rand(10));', output: '1' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Use srand to seed', 'int(rand(n)) for random integer 0 to n-1'],
    interviewTip: 'int(rand($#arr + 1)) for random array index',
    priority: 'useful',
  },
  {
    name: 'max/min',
    category: 'math',
    syntax: 'use List::Util qw(max min);\nmax(@array)',
    description: 'Return maximum or minimum value from a list',
    example: {
      code: 'use List::Util qw(max min);\nmy @arr = (3, 1, 4, 1, 5);\nprint max(@arr), " ", min(@arr);',
      output: '5 1',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Requires List::Util', 'Also: minstr/maxstr for string comparison'],
    interviewTip: 'Essential for many array problems',
    priority: 'essential',
  },
  {
    name: 'sum',
    category: 'math',
    syntax: 'use List::Util qw(sum);\nsum(@array)',
    description: 'Return sum of all elements',
    example: {
      code: 'use List::Util qw(sum);\nmy @arr = (1, 2, 3, 4, 5);\nprint sum(@arr);',
      output: '15',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns undef for empty list', 'sum0 returns 0 for empty list'],
    interviewTip: 'Use sum0 to avoid undef on empty arrays',
    priority: 'essential',
  },
  // ==================== SORTING ====================
  {
    name: 'sort (custom)',
    category: 'sorting',
    syntax: 'sort { $a->{key} <=> $b->{key} } @array',
    description: 'Sort array of hashes or complex structures',
    example: {
      code: 'my @arr = ({n=>3}, {n=>1}, {n=>2});\n@arr = sort { $a->{n} <=> $b->{n} } @arr;\nprint $arr[0]{n};',
      output: '1',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Block must return -1, 0, or 1', '$a and $b are package variables'],
    interviewTip: 'Chain comparisons: sort { $a->{x} <=> $b->{x} || $a->{y} <=> $b->{y} }',
    priority: 'essential',
  },
  {
    name: 'sort (descending)',
    category: 'sorting',
    syntax: 'sort { $b <=> $a } @array',
    description: 'Sort array in descending order',
    example: {
      code: 'my @arr = (3, 1, 4, 1, 5);\nmy @desc = sort { $b <=> $a } @arr;\nprint "@desc";',
      output: '5 4 3 1 1',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Swap $a and $b for descending', 'Or use reverse sort { $a <=> $b }'],
    interviewTip: 'Swapping $a/$b is more efficient than reversing',
    priority: 'essential',
  },
  // ==================== REFERENCES ====================
  {
    name: '\\ (reference)',
    category: 'memory',
    syntax: 'my $ref = \\$scalar; my $aref = \\@array',
    description: 'Create a reference to a variable',
    example: { code: 'my @arr = (1, 2, 3);\nmy $aref = \\@arr;\nprint $aref->[1];', output: '2' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['References allow pass-by-reference', 'Essential for complex data structures'],
    interviewTip: 'Use references to avoid copying large arrays',
    priority: 'essential',
  },
  {
    name: '-> (dereference)',
    category: 'memory',
    syntax: '$aref->[0], $href->{key}',
    description: 'Access elements through a reference',
    example: {
      code: 'my $aref = [1, 2, 3];\nmy $href = {a => 1};\nprint $aref->[0], $href->{a};',
      output: '11',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['-> is optional between adjacent brackets: $a->[0][1] == $a->[0]->[1]'],
    interviewTip: 'Most interview problems use references for complex structures',
    priority: 'essential',
  },
  {
    name: 'ref',
    category: 'memory',
    syntax: 'ref($variable)',
    description: 'Return the type of reference (ARRAY, HASH, SCALAR, etc.)',
    example: {
      code: 'my $aref = [1,2,3];\nmy $href = {a=>1};\nprint ref($aref), " ", ref($href);',
      output: 'ARRAY HASH',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns empty string for non-references', 'Returns blessed class name for objects'],
    interviewTip: 'Use for type checking in polymorphic code',
    priority: 'common',
  },
  // ==================== DEFINED/BOOLEAN ====================
  {
    name: 'defined',
    category: 'type-conversion',
    syntax: 'defined($variable)',
    description: 'Check if a variable has a defined value (not undef)',
    example: { code: 'my $x = 0;\nmy $y;\nprint defined($x), defined($y);', output: '1' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['0 and "" are defined but false', 'Different from exists for hashes'],
    interviewTip: 'Use // (defined-or) operator: $x // "default"',
    priority: 'essential',
  },
  // ==================== UNIQUE OPERATIONS ====================
  {
    name: 'uniq',
    category: 'arrays',
    syntax: 'use List::Util qw(uniq);\nuniq(@array)',
    description: 'Remove duplicate elements preserving order',
    example: {
      code: 'use List::Util qw(uniq);\nmy @arr = (1, 2, 2, 3, 1);\nprint join(",", uniq(@arr));',
      output: '1,2,3',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Requires List::Util 1.45+', 'Alternative: keys %{{ map { $_ => 1 } @arr }}'],
    interviewTip: 'Use %seen hash for older Perl: grep { !$seen{$_}++ } @arr',
    priority: 'common',
  },
  {
    name: 'shuffle',
    category: 'arrays',
    syntax: 'use List::Util qw(shuffle);\nshuffle(@array)',
    description: 'Randomly reorder array elements',
    example: {
      code: 'use List::Util qw(shuffle);\nsrand(42);\nmy @arr = shuffle(1..5);\nprint "@arr";',
      output: '4 1 5 3 2',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Fisher-Yates algorithm', 'Returns new list, does not modify original'],
    interviewTip: 'Use for randomizing test cases or card shuffling problems',
    priority: 'useful',
  },
];
