/**
 * PHP Cheatsheet
 *
 * Essential PHP functions for coding interviews.
 */

import type { CheatsheetEntry } from './types';

export const phpCheatsheet: CheatsheetEntry[] = [
  // ============ ARRAYS ============
  {
    name: 'array_map',
    category: 'arrays',
    syntax: 'array_map(callable $callback, array $array, array ...$arrays): array',
    description: 'Apply a callback to each element of an array',
    example: {
      code: '$nums = [1, 2, 3];\n$doubled = array_map(fn($n) => $n * 2, $nums);',
      output: '[2, 4, 6]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns new array, does not modify original', 'Callback receives value, not key'],
    interviewTip: 'Use for transforming array elements without mutation',
    priority: 'essential',
  },
  {
    name: 'array_filter',
    category: 'arrays',
    syntax: 'array_filter(array $array, ?callable $callback = null, int $mode = 0): array',
    description: 'Filter elements using a callback function',
    example: {
      code: '$nums = [1, 2, 3, 4, 5];\n$evens = array_filter($nums, fn($n) => $n % 2 === 0);',
      output: '[2 => 2, 4 => 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: [
      'Preserves original keys',
      'Use array_values() to reindex',
      'Without callback, removes falsy values',
    ],
    interviewTip: 'Remember keys are preserved - use array_values() if you need 0-indexed result',
    priority: 'essential',
  },
  {
    name: 'array_reduce',
    category: 'arrays',
    syntax: 'array_reduce(array $array, callable $callback, mixed $initial = null): mixed',
    description: 'Reduce array to a single value using callback',
    example: {
      code: '$nums = [1, 2, 3, 4];\n$sum = array_reduce($nums, fn($acc, $n) => $acc + $n, 0);',
      output: '10',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: [
      'Initial value is important for empty arrays',
      'Callback receives (accumulator, current)',
    ],
    interviewTip: 'Perfect for sum, product, or building complex structures from arrays',
    priority: 'essential',
  },
  {
    name: 'array_merge',
    category: 'arrays',
    syntax: 'array_merge(array ...$arrays): array',
    description: 'Merge one or more arrays',
    example: {
      code: '$a = [1, 2];\n$b = [3, 4];\n$merged = array_merge($a, $b);',
      output: '[1, 2, 3, 4]',
    },
    timeComplexity: 'O(n + m)',
    spaceComplexity: 'O(n + m)',
    gotchas: [
      'Numeric keys are renumbered',
      'String keys are overwritten by later arrays',
      'Use + operator to preserve numeric keys',
    ],
    interviewTip: 'Use spread operator [...$a, ...$b] in PHP 7.4+ as alternative',
    priority: 'essential',
  },
  {
    name: 'in_array',
    category: 'searching',
    syntax: 'in_array(mixed $needle, array $haystack, bool $strict = false): bool',
    description: 'Check if a value exists in an array',
    example: {
      code: '$fruits = ["apple", "banana", "cherry"];\n$exists = in_array("banana", $fruits);',
      output: 'true',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Use strict=true for type-safe comparison', 'Without strict, "0" == 0 is true'],
    interviewTip: 'For frequent lookups, consider using array_flip() + isset() for O(1)',
    priority: 'essential',
  },
  {
    name: 'array_search',
    category: 'searching',
    syntax: 'array_search(mixed $needle, array $haystack, bool $strict = false): int|string|false',
    description: 'Search for a value and return its key',
    example: {
      code: '$fruits = ["a" => "apple", "b" => "banana"];\n$key = array_search("banana", $fruits);',
      output: '"b"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: [
      'Returns false if not found',
      'Use === to distinguish false from key 0',
      'Only returns first match',
    ],
    interviewTip: 'Always use strict comparison when checking result: $key !== false',
    priority: 'essential',
  },
  {
    name: 'array_keys',
    category: 'arrays',
    syntax: 'array_keys(array $array, mixed $filter_value = null, bool $strict = false): array',
    description: 'Return all keys or keys for a specific value',
    example: {
      code: '$arr = ["a" => 1, "b" => 2, "c" => 1];\n$keys = array_keys($arr);',
      output: '["a", "b", "c"]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Optional filter_value finds keys with that value'],
    interviewTip: 'Useful for iterating over keys or finding all occurrences of a value',
    priority: 'essential',
  },
  {
    name: 'array_values',
    category: 'arrays',
    syntax: 'array_values(array $array): array',
    description: 'Return all values with numeric keys',
    example: {
      code: '$arr = ["a" => 1, "b" => 2];\n$values = array_values($arr);',
      output: '[1, 2]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Reindexes array starting from 0'],
    interviewTip: 'Use after array_filter() to get 0-indexed array',
    priority: 'essential',
  },
  {
    name: 'array_push',
    category: 'arrays',
    syntax: 'array_push(array &$array, mixed ...$values): int',
    description: 'Push one or more elements onto end of array',
    example: {
      code: '$stack = [1, 2];\narray_push($stack, 3, 4);',
      output: '$stack = [1, 2, 3, 4]',
    },
    timeComplexity: 'O(1) amortized',
    spaceComplexity: 'O(1)',
    gotchas: [
      'Modifies array in place',
      'Returns new array length',
      '$arr[] = $val is faster for single element',
    ],
    interviewTip: 'Use $arr[] = $val for single additions - its faster',
    priority: 'essential',
  },
  {
    name: 'array_pop',
    category: 'arrays',
    syntax: 'array_pop(array &$array): mixed',
    description: 'Pop element from end of array',
    example: {
      code: '$stack = [1, 2, 3];\n$last = array_pop($stack);',
      output: '$last = 3, $stack = [1, 2]',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns null if array is empty', 'Modifies array in place'],
    interviewTip: 'Use with array_push for stack operations',
    priority: 'essential',
  },
  {
    name: 'array_shift',
    category: 'arrays',
    syntax: 'array_shift(array &$array): mixed',
    description: 'Shift element from beginning of array',
    example: {
      code: '$queue = [1, 2, 3];\n$first = array_shift($queue);',
      output: '$first = 1, $queue = [2, 3]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Reindexes numeric keys', 'O(n) because all elements shift'],
    interviewTip: 'Use with array_push for queue operations, but consider SplQueue for performance',
    priority: 'essential',
  },
  {
    name: 'array_unshift',
    category: 'arrays',
    syntax: 'array_unshift(array &$array, mixed ...$values): int',
    description: 'Prepend elements to beginning of array',
    example: {
      code: '$arr = [3, 4];\narray_unshift($arr, 1, 2);',
      output: '$arr = [1, 2, 3, 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Reindexes numeric keys', 'Returns new array length'],
    interviewTip: 'O(n) operation - avoid in loops if possible',
    priority: 'common',
  },
  {
    name: 'array_slice',
    category: 'arrays',
    syntax:
      'array_slice(array $array, int $offset, ?int $length = null, bool $preserve_keys = false): array',
    description: 'Extract a portion of an array',
    example: {
      code: '$arr = [1, 2, 3, 4, 5];\n$slice = array_slice($arr, 1, 3);',
      output: '[2, 3, 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Negative offset counts from end', 'Does not modify original'],
    interviewTip: 'Similar to substring but for arrays',
    priority: 'essential',
  },
  {
    name: 'array_splice',
    category: 'arrays',
    syntax:
      'array_splice(array &$array, int $offset, ?int $length = null, mixed $replacement = []): array',
    description: 'Remove and/or replace portion of array',
    example: {
      code: '$arr = [1, 2, 3, 4];\n$removed = array_splice($arr, 1, 2, [5, 6]);',
      output: '$removed = [2, 3], $arr = [1, 5, 6, 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Modifies array in place', 'Returns removed elements', 'Reindexes numeric keys'],
    interviewTip: 'Use for inserting/removing at specific positions',
    priority: 'common',
  },
  {
    name: 'array_reverse',
    category: 'arrays',
    syntax: 'array_reverse(array $array, bool $preserve_keys = false): array',
    description: 'Return array in reverse order',
    example: {
      code: '$arr = [1, 2, 3];\n$reversed = array_reverse($arr);',
      output: '[3, 2, 1]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns new array', 'preserve_keys=true keeps original keys'],
    interviewTip: 'Useful for reversing traversal order',
    priority: 'common',
  },
  {
    name: 'array_unique',
    category: 'arrays',
    syntax: 'array_unique(array $array, int $flags = SORT_STRING): array',
    description: 'Remove duplicate values from array',
    example: {
      code: '$arr = [1, 2, 2, 3, 3, 3];\n$unique = array_unique($arr);',
      output: '[0 => 1, 1 => 2, 3 => 3]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    gotchas: [
      'Preserves first occurrence keys',
      'Use array_values() to reindex',
      'SORT_REGULAR for strict comparison',
    ],
    interviewTip: 'Remember to reindex with array_values() if needed',
    priority: 'essential',
  },
  {
    name: 'array_flip',
    category: 'arrays',
    syntax: 'array_flip(array $array): array',
    description: 'Exchange keys and values',
    example: {
      code: '$arr = ["a" => 1, "b" => 2];\n$flipped = array_flip($arr);',
      output: '[1 => "a", 2 => "b"]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Values must be valid keys (int/string)', 'Duplicate values keep last key'],
    interviewTip: 'Use for O(1) lookups: isset(array_flip($arr)[$val])',
    priority: 'common',
  },
  {
    name: 'array_count_values',
    category: 'arrays',
    syntax: 'array_count_values(array $array): array',
    description: 'Count occurrences of each value',
    example: {
      code: '$arr = ["a", "b", "a", "c", "a"];\n$counts = array_count_values($arr);',
      output: '["a" => 3, "b" => 1, "c" => 1]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Only works with int/string values'],
    interviewTip: 'Perfect for frequency counting problems',
    priority: 'essential',
  },
  {
    name: 'array_diff',
    category: 'arrays',
    syntax: 'array_diff(array $array, array ...$arrays): array',
    description: 'Compute difference of arrays',
    example: {
      code: '$a = [1, 2, 3, 4];\n$b = [2, 4];\n$diff = array_diff($a, $b);',
      output: '[0 => 1, 2 => 3]',
    },
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns values from first array not in others', 'Preserves keys'],
    interviewTip: 'Useful for finding missing elements',
    priority: 'common',
  },
  {
    name: 'array_intersect',
    category: 'arrays',
    syntax: 'array_intersect(array $array, array ...$arrays): array',
    description: 'Compute intersection of arrays',
    example: {
      code: '$a = [1, 2, 3, 4];\n$b = [2, 4, 6];\n$common = array_intersect($a, $b);',
      output: '[1 => 2, 3 => 4]',
    },
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(n)',
    gotchas: ['Values from first array preserved', 'Preserves keys from first array'],
    interviewTip: 'Find common elements between arrays',
    priority: 'common',
  },
  {
    name: 'array_key_exists',
    category: 'searching',
    syntax: 'array_key_exists(string|int $key, array $array): bool',
    description: 'Check if key exists in array',
    example: {
      code: '$arr = ["a" => 1, "b" => null];\n$exists = array_key_exists("b", $arr);',
      output: 'true',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns true even if value is null', 'isset() returns false for null values'],
    interviewTip: 'Use when null is a valid value; use isset() otherwise',
    priority: 'essential',
  },
  {
    name: 'count',
    category: 'arrays',
    syntax: 'count(Countable|array $value, int $mode = COUNT_NORMAL): int',
    description: 'Count elements in array or object',
    example: {
      code: '$arr = [1, 2, 3, 4, 5];\n$len = count($arr);',
      output: '5',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['COUNT_RECURSIVE counts nested arrays', 'sizeof() is alias'],
    interviewTip: 'O(1) for arrays - PHP caches array length',
    priority: 'essential',
  },

  // ============ SORTING ============
  {
    name: 'sort',
    category: 'sorting',
    syntax: 'sort(array &$array, int $flags = SORT_REGULAR): bool',
    description: 'Sort array in ascending order',
    example: {
      code: '$arr = [3, 1, 4, 1, 5];\nsort($arr);',
      output: '$arr = [1, 1, 3, 4, 5]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Modifies array in place', 'Reindexes keys', 'SORT_NUMERIC for numeric comparison'],
    interviewTip: 'Use asort() to preserve keys',
    priority: 'essential',
  },
  {
    name: 'rsort',
    category: 'sorting',
    syntax: 'rsort(array &$array, int $flags = SORT_REGULAR): bool',
    description: 'Sort array in descending order',
    example: {
      code: '$arr = [3, 1, 4, 1, 5];\nrsort($arr);',
      output: '$arr = [5, 4, 3, 1, 1]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Modifies array in place', 'Reindexes keys'],
    interviewTip: 'Use arsort() to preserve keys',
    priority: 'common',
  },
  {
    name: 'usort',
    category: 'sorting',
    syntax: 'usort(array &$array, callable $callback): bool',
    description: 'Sort array using user-defined comparison function',
    example: {
      code: '$arr = [[1, 2], [1, 1], [2, 1]];\nusort($arr, fn($a, $b) => $a[0] <=> $b[0] ?: $a[1] <=> $b[1]);',
      output: '$arr = [[1, 1], [1, 2], [2, 1]]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Callback returns negative/zero/positive', 'Use spaceship operator <=>'],
    interviewTip: 'Essential for custom sorting - master the <=> operator',
    priority: 'essential',
  },
  {
    name: 'ksort',
    category: 'sorting',
    syntax: 'ksort(array &$array, int $flags = SORT_REGULAR): bool',
    description: 'Sort array by keys in ascending order',
    example: {
      code: '$arr = ["c" => 3, "a" => 1, "b" => 2];\nksort($arr);',
      output: '$arr = ["a" => 1, "b" => 2, "c" => 3]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Modifies array in place', 'Maintains key-value associations'],
    interviewTip: 'Use for sorted associative arrays',
    priority: 'common',
  },

  // ============ STRINGS ============
  {
    name: 'explode',
    category: 'strings',
    syntax: 'explode(string $separator, string $string, int $limit = PHP_INT_MAX): array',
    description: 'Split string by delimiter into array',
    example: {
      code: '$str = "a,b,c,d";\n$parts = explode(",", $str);',
      output: '["a", "b", "c", "d"]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Empty separator throws error', 'Negative limit removes last n elements'],
    interviewTip: 'Use for parsing CSV-like strings',
    priority: 'essential',
  },
  {
    name: 'implode',
    category: 'strings',
    syntax: 'implode(string $separator, array $array): string',
    description: 'Join array elements with separator',
    example: {
      code: '$arr = ["a", "b", "c"];\n$str = implode("-", $arr);',
      output: '"a-b-c"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['join() is alias', 'Works with any separator including empty string'],
    interviewTip: 'Use for building output strings from arrays',
    priority: 'essential',
  },
  {
    name: 'substr',
    category: 'strings',
    syntax: 'substr(string $string, int $offset, ?int $length = null): string',
    description: 'Return part of a string',
    example: {
      code: '$str = "Hello World";\n$sub = substr($str, 0, 5);',
      output: '"Hello"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Negative offset counts from end', 'Negative length omits from end'],
    interviewTip: 'Essential for string manipulation in interviews',
    priority: 'essential',
  },
  {
    name: 'str_replace',
    category: 'strings',
    syntax:
      'str_replace(array|string $search, array|string $replace, string|array $subject, int &$count = null): string|array',
    description: 'Replace occurrences of search with replace',
    example: {
      code: '$str = "Hello World";\n$new = str_replace("World", "PHP", $str);',
      output: '"Hello PHP"',
    },
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(n)',
    gotchas: [
      'Case-sensitive',
      'Use str_ireplace for case-insensitive',
      'Can use arrays for multiple replacements',
    ],
    interviewTip: 'Use arrays to do multiple replacements in one call',
    priority: 'essential',
  },
  {
    name: 'strlen',
    category: 'strings',
    syntax: 'strlen(string $string): int',
    description: 'Get string length in bytes',
    example: {
      code: '$str = "Hello";\n$len = strlen($str);',
      output: '5',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns bytes, not characters', 'Use mb_strlen for multibyte strings'],
    interviewTip: 'Use mb_strlen() for Unicode/UTF-8 strings',
    priority: 'essential',
  },
  {
    name: 'strpos',
    category: 'searching',
    syntax: 'strpos(string $haystack, string $needle, int $offset = 0): int|false',
    description: 'Find position of first occurrence of substring',
    example: {
      code: '$str = "Hello World";\n$pos = strpos($str, "World");',
      output: '6',
    },
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(1)',
    gotchas: [
      'Returns false if not found',
      'Use === to distinguish from position 0',
      'Case-sensitive',
    ],
    interviewTip: 'Always use strict comparison: $pos !== false',
    priority: 'essential',
  },
  {
    name: 'strtolower',
    category: 'strings',
    syntax: 'strtolower(string $string): string',
    description: 'Convert string to lowercase',
    example: {
      code: '$str = "Hello World";\n$lower = strtolower($str);',
      output: '"hello world"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Only ASCII characters', 'Use mb_strtolower for Unicode'],
    interviewTip: 'Use for case-insensitive comparisons',
    priority: 'essential',
  },
  {
    name: 'strtoupper',
    category: 'strings',
    syntax: 'strtoupper(string $string): string',
    description: 'Convert string to uppercase',
    example: {
      code: '$str = "Hello World";\n$upper = strtoupper($str);',
      output: '"HELLO WORLD"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Only ASCII characters', 'Use mb_strtoupper for Unicode'],
    priority: 'common',
  },
  {
    name: 'trim',
    category: 'strings',
    syntax: 'trim(string $string, string $characters = " \\n\\r\\t\\v\\x00"): string',
    description: 'Strip whitespace from beginning and end',
    example: {
      code: '$str = "  Hello World  ";\n$trimmed = trim($str);',
      output: '"Hello World"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Can specify custom characters to trim', 'ltrim/rtrim for one side only'],
    interviewTip: 'Always trim user input before processing',
    priority: 'essential',
  },
  {
    name: 'str_split',
    category: 'strings',
    syntax: 'str_split(string $string, int $length = 1): array',
    description: 'Convert string to array of characters',
    example: {
      code: '$str = "Hello";\n$chars = str_split($str);',
      output: '["H", "e", "l", "l", "o"]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Length parameter splits into chunks', 'Use mb_str_split for Unicode'],
    interviewTip: 'Essential for character-by-character processing',
    priority: 'essential',
  },
  {
    name: 'sprintf',
    category: 'strings',
    syntax: 'sprintf(string $format, mixed ...$values): string',
    description: 'Return formatted string',
    example: {
      code: '$name = "John";\n$age = 25;\n$str = sprintf("%s is %d years old", $name, $age);',
      output: '"John is 25 years old"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['%s for string, %d for int, %f for float', '%02d for zero-padded'],
    interviewTip: 'Use for formatted output and number padding',
    priority: 'common',
  },
  {
    name: 'preg_match',
    category: 'regex',
    syntax:
      'preg_match(string $pattern, string $subject, array &$matches = null, int $flags = 0, int $offset = 0): int|false',
    description: 'Perform regular expression match',
    example: {
      code: '$str = "The year is 2024";\npreg_match(\'/\\d+/\', $str, $matches);',
      output: '$matches = ["2024"]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns 1 if matched, 0 if not, false on error', 'Pattern needs delimiters'],
    interviewTip: 'Use preg_match_all for all matches',
    priority: 'essential',
  },
  {
    name: 'preg_replace',
    category: 'regex',
    syntax:
      'preg_replace(string|array $pattern, string|array $replacement, string|array $subject, int $limit = -1, int &$count = null): string|array|null',
    description: 'Perform regular expression search and replace',
    example: {
      code: "$str = \"The  quick   brown\";\n$clean = preg_replace('/\\s+/', ' ', $str);",
      output: '"The quick brown"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns null on error', 'Use $1, $2 for backreferences'],
    interviewTip: 'Powerful for complex string transformations',
    priority: 'common',
  },

  // ============ MATH ============
  {
    name: 'max',
    category: 'math',
    syntax: 'max(mixed $value, mixed ...$values): mixed',
    description: 'Find highest value',
    example: {
      code: '$arr = [1, 5, 3, 9, 2];\n$highest = max($arr);',
      output: '9',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Works with arrays or multiple args', 'Returns first value for equal max'],
    interviewTip: 'Combine with array_column for max of specific key',
    priority: 'essential',
  },
  {
    name: 'min',
    category: 'math',
    syntax: 'min(mixed $value, mixed ...$values): mixed',
    description: 'Find lowest value',
    example: {
      code: '$arr = [1, 5, 3, 9, 2];\n$lowest = min($arr);',
      output: '1',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Works with arrays or multiple args', 'Returns first value for equal min'],
    priority: 'essential',
  },
  {
    name: 'abs',
    category: 'math',
    syntax: 'abs(int|float $num): int|float',
    description: 'Get absolute value',
    example: {
      code: '$val = abs(-5);',
      output: '5',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use for distance calculations',
    priority: 'essential',
  },
  {
    name: 'floor',
    category: 'math',
    syntax: 'floor(int|float $num): float',
    description: 'Round down to nearest integer',
    example: {
      code: '$val = floor(4.7);',
      output: '4.0',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns float, cast to int if needed', 'Rounds toward negative infinity'],
    priority: 'common',
  },
  {
    name: 'ceil',
    category: 'math',
    syntax: 'ceil(int|float $num): float',
    description: 'Round up to nearest integer',
    example: {
      code: '$val = ceil(4.1);',
      output: '5.0',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns float, cast to int if needed'],
    priority: 'common',
  },
  {
    name: 'round',
    category: 'math',
    syntax: 'round(int|float $num, int $precision = 0, int $mode = PHP_ROUND_HALF_UP): float',
    description: 'Round a number',
    example: {
      code: '$val = round(4.567, 2);',
      output: '4.57',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Precision can be negative for rounding to tens, hundreds, etc.'],
    priority: 'common',
  },

  // ============ TYPE CONVERSION ============
  {
    name: 'intval',
    category: 'type-conversion',
    syntax: 'intval(mixed $value, int $base = 10): int',
    description: 'Get integer value of variable',
    example: {
      code: '$str = "42abc";\n$num = intval($str);',
      output: '42',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Stops at first non-numeric character', 'Returns 0 for non-numeric strings'],
    interviewTip: '(int) cast is usually faster',
    priority: 'common',
  },
  {
    name: 'strval',
    category: 'type-conversion',
    syntax: 'strval(mixed $value): string',
    description: 'Get string value of variable',
    example: {
      code: '$num = 42;\n$str = strval($num);',
      output: '"42"',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Arrays and objects may not convert as expected'],
    priority: 'common',
  },
  {
    name: 'is_array',
    category: 'type-conversion',
    syntax: 'is_array(mixed $value): bool',
    description: 'Check if variable is an array',
    example: {
      code: '$arr = [1, 2, 3];\n$check = is_array($arr);',
      output: 'true',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use for type validation before array operations',
    priority: 'common',
  },
  {
    name: 'is_numeric',
    category: 'type-conversion',
    syntax: 'is_numeric(mixed $value): bool',
    description: 'Check if variable is numeric',
    example: {
      code: '$val = "42.5";\n$check = is_numeric($val);',
      output: 'true',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns true for numeric strings', 'Hexadecimal notation returns false in PHP 7+'],
    priority: 'common',
  },

  // ============ FUNCTIONAL ============
  {
    name: 'array_walk',
    category: 'functional',
    syntax: 'array_walk(array|object &$array, callable $callback, mixed $arg = null): bool',
    description: 'Apply callback to each element in place',
    example: {
      code: '$arr = [1, 2, 3];\narray_walk($arr, fn(&$val) => $val *= 2);',
      output: '$arr = [2, 4, 6]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Modifies array in place', 'Callback receives value by reference to modify'],
    interviewTip: 'Use for in-place modification, array_map for new array',
    priority: 'common',
  },
  {
    name: 'array_column',
    category: 'arrays',
    syntax:
      'array_column(array $array, int|string|null $column_key, int|string|null $index_key = null): array',
    description: 'Return values from single column',
    example: {
      code: '$users = [["id" => 1, "name" => "Alice"], ["id" => 2, "name" => "Bob"]];\n$names = array_column($users, "name");',
      output: '["Alice", "Bob"]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['index_key creates associative array', 'null column_key returns entire rows'],
    interviewTip: 'Extremely useful for extracting data from arrays of objects/arrays',
    priority: 'essential',
  },
  {
    name: 'array_combine',
    category: 'arrays',
    syntax: 'array_combine(array $keys, array $values): array',
    description: 'Create array using keys and values arrays',
    example: {
      code: '$keys = ["a", "b", "c"];\n$vals = [1, 2, 3];\n$arr = array_combine($keys, $vals);',
      output: '["a" => 1, "b" => 2, "c" => 3]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Arrays must have same length', 'Throws error if lengths differ'],
    interviewTip: 'Useful for creating lookup tables',
    priority: 'common',
  },
  {
    name: 'array_fill',
    category: 'arrays',
    syntax: 'array_fill(int $start_index, int $count, mixed $value): array',
    description: 'Fill array with values',
    example: {
      code: '$arr = array_fill(0, 5, 0);',
      output: '[0, 0, 0, 0, 0]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Use for initializing arrays with default values',
    priority: 'common',
  },
  {
    name: 'range',
    category: 'arrays',
    syntax: 'range(string|int|float $start, string|int|float $end, int|float $step = 1): array',
    description: 'Create array of sequential values',
    example: {
      code: '$nums = range(1, 5);\n$letters = range("a", "e");',
      output: '[1, 2, 3, 4, 5] and ["a", "b", "c", "d", "e"]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Works with numbers and characters', 'Step can be negative for descending'],
    interviewTip: 'Great for generating test data or iteration sequences',
    priority: 'common',
  },
  {
    name: 'array_sum',
    category: 'math',
    syntax: 'array_sum(array $array): int|float',
    description: 'Calculate sum of array values',
    example: {
      code: '$nums = [1, 2, 3, 4, 5];\n$sum = array_sum($nums);',
      output: '15',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Non-numeric values are treated as 0'],
    interviewTip: 'Faster than array_reduce for simple sums',
    priority: 'essential',
  },
];
