/**
 * Python Cheatsheet
 *
 * Essential Python methods and functions for coding interviews.
 * Covers lists, strings, dicts, sets, and built-in functions.
 */

import type { CheatsheetEntry } from './types';

export const pythonCheatsheet: CheatsheetEntry[] = [
  // ============================================
  // LIST METHODS (arrays category)
  // ============================================
  {
    name: 'list.append',
    category: 'arrays',
    syntax: 'list.append(item)',
    description: 'Add an item to the end of the list',
    example: { code: 'nums = [1, 2]; nums.append(3)', output: '[1, 2, 3]' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Modifies list in place, returns None'],
    interviewTip: 'Use for building results incrementally',
    priority: 'essential',
  },
  {
    name: 'list.extend',
    category: 'arrays',
    syntax: 'list.extend(iterable)',
    description: 'Extend list by appending all items from an iterable',
    example: { code: 'a = [1, 2]; a.extend([3, 4])', output: '[1, 2, 3, 4]' },
    timeComplexity: 'O(k)',
    spaceComplexity: 'O(1)',
    gotchas: ['Different from append - extend flattens the iterable'],
    interviewTip: 'Use += as shorthand: a += [3, 4]',
    priority: 'common',
  },
  {
    name: 'list.pop',
    category: 'arrays',
    syntax: 'list.pop([index])',
    description: 'Remove and return item at index (default last)',
    example: { code: 'nums = [1, 2, 3]; nums.pop()', output: '3' },
    timeComplexity: 'O(1) end, O(n) middle',
    spaceComplexity: 'O(1)',
    gotchas: ['pop(0) is O(n) - use collections.deque for O(1)'],
    interviewTip: 'Use for stack operations (LIFO)',
    priority: 'essential',
  },
  {
    name: 'list.sort',
    category: 'sorting',
    syntax: 'list.sort(key=None, reverse=False)',
    description: 'Sort list in place',
    example: { code: 'nums = [3, 1, 2]; nums.sort()', output: '[1, 2, 3]' },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Modifies in place, returns None', 'Use sorted() for new list'],
    interviewTip: 'Use key=lambda for custom sorting',
    priority: 'essential',
  },
  {
    name: 'list.reverse',
    category: 'arrays',
    syntax: 'list.reverse()',
    description: 'Reverse list in place',
    example: { code: 'nums = [1, 2, 3]; nums.reverse()', output: '[3, 2, 1]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns None', 'Use [::-1] for a reversed copy'],
    priority: 'essential',
  },
  {
    name: 'list slicing',
    category: 'arrays',
    syntax: 'list[start:end:step]',
    description: 'Extract a portion of the list',
    example: { code: 'nums = [0,1,2,3,4]; nums[1:4]', output: '[1, 2, 3]' },
    timeComplexity: 'O(k)',
    spaceComplexity: 'O(k)',
    gotchas: ['End index is exclusive', 'Negative indices count from end'],
    interviewTip: 'nums[::-1] reverses, nums[::2] gets every 2nd element',
    priority: 'essential',
  },

  // ============================================
  // STRING METHODS
  // ============================================
  {
    name: 'str.split',
    category: 'strings',
    syntax: 'str.split(sep=None, maxsplit=-1)',
    description: 'Split string into list by separator',
    example: { code: '"a,b,c".split(",")', output: "['a', 'b', 'c']" },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Default splits on whitespace and removes empty strings'],
    interviewTip: 'Essential for parsing input strings',
    priority: 'essential',
  },
  {
    name: 'str.join',
    category: 'strings',
    syntax: 'separator.join(iterable)',
    description: 'Join iterable elements with separator',
    example: { code: '",".join(["a", "b", "c"])', output: '"a,b,c"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['All elements must be strings'],
    interviewTip: 'More efficient than string concatenation in loops',
    priority: 'essential',
  },
  {
    name: 'str.strip',
    category: 'strings',
    syntax: 'str.strip([chars])',
    description: 'Remove leading/trailing whitespace or specified chars',
    example: { code: '"  hello  ".strip()', output: '"hello"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['lstrip() and rstrip() for one-sided trimming'],
    priority: 'essential',
  },
  {
    name: 'str.find',
    category: 'searching',
    syntax: 'str.find(sub, start=0, end=len)',
    description: 'Return lowest index of substring, or -1 if not found',
    example: { code: '"hello".find("ll")', output: '2' },
    timeComplexity: 'O(n*m)',
    spaceComplexity: 'O(1)',
    gotchas: ['Use "in" operator for existence check', 'index() raises ValueError instead'],
    priority: 'common',
  },
  {
    name: 'str.replace',
    category: 'strings',
    syntax: 'str.replace(old, new, count=-1)',
    description: 'Return copy with all occurrences replaced',
    example: { code: '"aaa".replace("a", "b", 2)', output: '"bba"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Strings are immutable - returns new string'],
    priority: 'essential',
  },
  {
    name: 'str.isalnum',
    category: 'strings',
    syntax: 'str.isalnum()',
    description: 'Check if all characters are alphanumeric',
    example: { code: '"abc123".isalnum()', output: 'True' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns False for empty string', 'Also: isalpha(), isdigit(), isspace()'],
    interviewTip: 'Useful for string validation problems',
    priority: 'common',
  },
  {
    name: 'str.lower / str.upper',
    category: 'strings',
    syntax: 'str.lower() / str.upper()',
    description: 'Convert string to lowercase/uppercase',
    example: { code: '"Hello".lower()', output: '"hello"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns new string (immutable)'],
    interviewTip: 'Normalize case for case-insensitive comparison',
    priority: 'essential',
  },
  {
    name: 'ord / chr',
    category: 'strings',
    syntax: 'ord(char) / chr(code)',
    description: 'Convert between character and ASCII/Unicode code point',
    example: { code: "ord('a'), chr(97)", output: '(97, "a")' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['ord() takes single character only'],
    interviewTip: "ord('a') = 97, useful for alphabet indexing",
    priority: 'essential',
  },

  // ============================================
  // DICTIONARY METHODS (objects category)
  // ============================================
  {
    name: 'dict.get',
    category: 'objects',
    syntax: 'dict.get(key, default=None)',
    description: 'Get value for key, or default if not found',
    example: { code: '{"a": 1}.get("b", 0)', output: '0' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns None by default, not KeyError'],
    interviewTip: 'Cleaner than try/except for missing keys',
    priority: 'essential',
  },
  {
    name: 'dict.keys',
    category: 'objects',
    syntax: 'dict.keys()',
    description: 'Return view of dictionary keys',
    example: { code: '{"a": 1, "b": 2}.keys()', output: "dict_keys(['a', 'b'])" },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns view object, not list - wrap in list() if needed'],
    priority: 'essential',
  },
  {
    name: 'dict.values',
    category: 'objects',
    syntax: 'dict.values()',
    description: 'Return view of dictionary values',
    example: { code: '{"a": 1, "b": 2}.values()', output: 'dict_values([1, 2])' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Values are not unique'],
    priority: 'essential',
  },
  {
    name: 'dict.items',
    category: 'objects',
    syntax: 'dict.items()',
    description: 'Return view of (key, value) pairs',
    example: { code: '{"a": 1}.items()', output: "dict_items([('a', 1)])" },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Iteration order is insertion order (Python 3.7+)'],
    interviewTip: 'Use for iterating key-value pairs together',
    priority: 'essential',
  },
  {
    name: 'dict.update',
    category: 'objects',
    syntax: 'dict.update(other)',
    description: 'Update dict with key/value pairs from another dict',
    example: { code: 'd = {"a": 1}; d.update({"b": 2})', output: '{"a": 1, "b": 2}' },
    timeComplexity: 'O(k)',
    spaceComplexity: 'O(1)',
    gotchas: ['Overwrites existing keys', 'Use |= in Python 3.9+'],
    priority: 'common',
  },
  {
    name: 'defaultdict',
    category: 'objects',
    syntax: 'defaultdict(default_factory)',
    description: 'Dict subclass with default value for missing keys',
    example: {
      code: 'from collections import defaultdict; d = defaultdict(list); d["a"].append(1)',
      output: "defaultdict(<class 'list'>, {'a': [1]})",
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Import from collections', 'default_factory is called, not a value'],
    interviewTip: 'Perfect for frequency counts: defaultdict(int)',
    priority: 'essential',
  },
  {
    name: 'Counter',
    category: 'objects',
    syntax: 'Counter(iterable)',
    description: 'Dict subclass for counting hashable objects',
    example: {
      code: 'from collections import Counter; Counter("aab")',
      output: "Counter({'a': 2, 'b': 1})",
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(k)',
    gotchas: ['Returns 0 for missing keys', 'most_common(n) returns top n'],
    interviewTip: 'Essential for frequency counting problems',
    priority: 'essential',
  },

  // ============================================
  // SET OPERATIONS
  // ============================================
  {
    name: 'set.add',
    category: 'sets',
    syntax: 'set.add(elem)',
    description: 'Add element to set',
    example: { code: 's = {1, 2}; s.add(3)', output: '{1, 2, 3}' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['No effect if element already present'],
    priority: 'essential',
  },
  {
    name: 'set.remove / discard',
    category: 'sets',
    syntax: 'set.remove(elem) / set.discard(elem)',
    description: 'Remove element from set',
    example: { code: 's = {1, 2}; s.discard(1)', output: '{2}' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['remove() raises KeyError if missing, discard() does not'],
    priority: 'common',
  },
  {
    name: 'set union',
    category: 'sets',
    syntax: 'set1 | set2 or set1.union(set2)',
    description: 'Return set with elements from both sets',
    example: { code: '{1, 2} | {2, 3}', output: '{1, 2, 3}' },
    timeComplexity: 'O(n + m)',
    spaceComplexity: 'O(n + m)',
    interviewTip: 'Use for combining unique elements',
    priority: 'essential',
  },
  {
    name: 'set intersection',
    category: 'sets',
    syntax: 'set1 & set2 or set1.intersection(set2)',
    description: 'Return set with elements common to both',
    example: { code: '{1, 2, 3} & {2, 3, 4}', output: '{2, 3}' },
    timeComplexity: 'O(min(n, m))',
    spaceComplexity: 'O(min(n, m))',
    interviewTip: 'Efficient for finding common elements',
    priority: 'essential',
  },
  {
    name: 'set difference',
    category: 'sets',
    syntax: 'set1 - set2 or set1.difference(set2)',
    description: 'Return set with elements in set1 but not set2',
    example: { code: '{1, 2, 3} - {2, 3}', output: '{1}' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Order matters: a - b != b - a'],
    priority: 'common',
  },

  // ============================================
  // BUILT-IN FUNCTIONS
  // ============================================
  {
    name: 'len',
    category: 'arrays',
    syntax: 'len(obj)',
    description: 'Return the length of an object',
    example: { code: 'len([1, 2, 3])', output: '3' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Works on strings, lists, dicts, sets, etc.'],
    priority: 'essential',
  },
  {
    name: 'range',
    category: 'iteration',
    syntax: 'range(start, stop, step)',
    description: 'Generate sequence of numbers',
    example: { code: 'list(range(0, 5, 2))', output: '[0, 2, 4]' },
    timeComplexity: 'O(1) creation',
    spaceComplexity: 'O(1)',
    gotchas: ['Stop is exclusive', 'Returns iterator, not list'],
    interviewTip: 'range(len(arr)-1, -1, -1) for reverse iteration',
    priority: 'essential',
  },
  {
    name: 'enumerate',
    category: 'iteration',
    syntax: 'enumerate(iterable, start=0)',
    description: 'Return iterator of (index, value) pairs',
    example: { code: 'list(enumerate(["a", "b"]))', output: '[(0, "a"), (1, "b")]' },
    timeComplexity: 'O(1) creation',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns iterator, not list'],
    interviewTip: 'Always prefer over range(len(arr)) + indexing',
    priority: 'essential',
  },
  {
    name: 'zip',
    category: 'iteration',
    syntax: 'zip(*iterables)',
    description: 'Iterate over multiple iterables in parallel',
    example: { code: 'list(zip([1, 2], ["a", "b"]))', output: '[(1, "a"), (2, "b")]' },
    timeComplexity: 'O(1) creation',
    spaceComplexity: 'O(1)',
    gotchas: ['Stops at shortest iterable', 'Use zip_longest for padding'],
    interviewTip: 'Useful for matrix transpose: list(zip(*matrix))',
    priority: 'essential',
  },
  {
    name: 'sorted',
    category: 'sorting',
    syntax: 'sorted(iterable, key=None, reverse=False)',
    description: 'Return new sorted list from iterable',
    example: { code: 'sorted([3, 1, 2])', output: '[1, 2, 3]' },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns new list, does not modify original'],
    interviewTip: 'sorted(d.items(), key=lambda x: x[1]) for sorting by value',
    priority: 'essential',
  },
  {
    name: 'map',
    category: 'functional',
    syntax: 'map(function, iterable)',
    description: 'Apply function to every item of iterable',
    example: { code: 'list(map(str, [1, 2, 3]))', output: "['1', '2', '3']" },
    timeComplexity: 'O(1) creation',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns iterator', 'Often cleaner as list comprehension'],
    interviewTip: 'map(int, input().split()) for parsing integers',
    priority: 'common',
  },
  {
    name: 'filter',
    category: 'functional',
    syntax: 'filter(function, iterable)',
    description: 'Filter items where function returns True',
    example: { code: 'list(filter(lambda x: x > 0, [-1, 0, 1]))', output: '[1]' },
    timeComplexity: 'O(1) creation',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns iterator', 'Often cleaner as list comprehension'],
    priority: 'common',
  },
  {
    name: 'list comprehension',
    category: 'functional',
    syntax: '[expr for item in iterable if condition]',
    description: 'Create list using concise syntax',
    example: { code: '[x**2 for x in range(4) if x % 2 == 0]', output: '[0, 4]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Can be nested for 2D operations'],
    interviewTip: 'Preferred over map/filter in Python',
    priority: 'essential',
  },
  {
    name: 'min / max',
    category: 'math',
    syntax: 'min(iterable, key=None) / max(iterable, key=None)',
    description: 'Return smallest/largest item',
    example: { code: 'max([1, 3, 2], key=lambda x: -x)', output: '1' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Can take multiple args: max(1, 2, 3)'],
    interviewTip: 'Use key for custom comparison logic',
    priority: 'essential',
  },
  {
    name: 'sum',
    category: 'math',
    syntax: 'sum(iterable, start=0)',
    description: 'Sum all items in iterable',
    example: { code: 'sum([1, 2, 3], 10)', output: '16' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Only works with numbers', 'Use join() for strings'],
    priority: 'essential',
  },
  {
    name: 'abs',
    category: 'math',
    syntax: 'abs(x)',
    description: 'Return absolute value of number',
    example: { code: 'abs(-5)', output: '5' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Essential for distance calculations',
    priority: 'essential',
  },
  {
    name: 'any / all',
    category: 'functional',
    syntax: 'any(iterable) / all(iterable)',
    description: 'Check if any/all elements are truthy',
    example: { code: 'any([0, 1, 0]), all([1, 1, 1])', output: '(True, True)' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Short-circuits on first True/False'],
    interviewTip: 'Great with generator expressions',
    priority: 'common',
  },
  {
    name: 'reversed',
    category: 'iteration',
    syntax: 'reversed(seq)',
    description: 'Return reverse iterator',
    example: { code: 'list(reversed([1, 2, 3]))', output: '[3, 2, 1]' },
    timeComplexity: 'O(1) creation',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns iterator, not list', 'Works on sequences only'],
    interviewTip: 'More memory efficient than [::-1]',
    priority: 'common',
  },

  // ============================================
  // COLLECTIONS & HEAPS
  // ============================================
  {
    name: 'heapq.heappush',
    category: 'arrays',
    syntax: 'heapq.heappush(heap, item)',
    description: 'Push item onto heap maintaining heap property',
    example: { code: 'import heapq; h = []; heapq.heappush(h, 3)', output: '[3]' },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Min-heap by default', 'For max-heap, negate values'],
    interviewTip: 'Essential for top-k and priority queue problems',
    priority: 'essential',
  },
  {
    name: 'heapq.heappop',
    category: 'arrays',
    syntax: 'heapq.heappop(heap)',
    description: 'Pop smallest item from heap',
    example: { code: 'import heapq; h = [1, 3, 2]; heapq.heappop(h)', output: '1' },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['IndexError if heap is empty'],
    priority: 'essential',
  },
  {
    name: 'heapq.heapify',
    category: 'arrays',
    syntax: 'heapq.heapify(list)',
    description: 'Transform list into heap in-place',
    example: { code: 'import heapq; h = [3, 1, 2]; heapq.heapify(h)', output: '[1, 3, 2]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Modifies list in place'],
    interviewTip: 'Faster than n heappush operations',
    priority: 'essential',
  },
  {
    name: 'deque',
    category: 'arrays',
    syntax: 'deque(iterable, maxlen=None)',
    description: 'Double-ended queue with O(1) operations at both ends',
    example: {
      code: 'from collections import deque; d = deque([1, 2]); d.appendleft(0)',
      output: 'deque([0, 1, 2])',
    },
    timeComplexity: 'O(1) append/pop both ends',
    spaceComplexity: 'O(n)',
    gotchas: ['popleft() and appendleft() for left operations'],
    interviewTip: 'Use for BFS queue or sliding window',
    priority: 'essential',
  },
  {
    name: 'bisect.bisect_left',
    category: 'searching',
    syntax: 'bisect.bisect_left(arr, x)',
    description: 'Find insertion point for x in sorted array',
    example: { code: 'import bisect; bisect.bisect_left([1, 3, 5], 3)', output: '1' },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['bisect_left vs bisect_right for duplicates'],
    interviewTip: 'Binary search without writing it yourself',
    priority: 'essential',
  },
];
