/**
 * R Cheatsheet
 *
 * Essential R functions for coding interviews and data manipulation.
 * Covers vectors, apply family, strings, math, and data operations.
 */

import type { CheatsheetEntry } from './types';

export const rCheatsheet: CheatsheetEntry[] = [
  // ============ VECTOR OPERATIONS (arrays) ============
  {
    name: 'c',
    category: 'arrays',
    syntax: 'c(...)',
    description: 'Combine values into a vector',
    example: { code: 'c(1, 2, 3, 4, 5)', output: '[1] 1 2 3 4 5' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Coerces all elements to same type', 'NULL values are dropped'],
    interviewTip: 'Most fundamental function for creating vectors',
    priority: 'essential',
  },
  {
    name: 'length',
    category: 'arrays',
    syntax: 'length(x)',
    description: 'Get the length of a vector or list',
    example: { code: 'length(c(1, 2, 3))', output: '[1] 3' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use for loop bounds and size checks',
    priority: 'essential',
  },
  {
    name: 'seq',
    category: 'arrays',
    syntax: 'seq(from, to, by) or seq_len(n)',
    description: 'Generate a sequence of numbers',
    example: { code: 'seq(1, 10, by = 2)', output: '[1] 1 3 5 7 9' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['seq_along is safer than 1:length(x) for empty vectors'],
    interviewTip: 'Use seq_len(n) instead of 1:n to handle n=0 case',
    priority: 'essential',
  },
  {
    name: 'rep',
    category: 'arrays',
    syntax: 'rep(x, times) or rep(x, each = n)',
    description: 'Replicate elements of a vector',
    example: { code: 'rep(1:3, times = 2)', output: '[1] 1 2 3 1 2 3' },
    timeComplexity: 'O(n * times)',
    spaceComplexity: 'O(n * times)',
    gotchas: ['times replicates whole vector, each replicates each element'],
    priority: 'common',
  },
  {
    name: 'append',
    category: 'arrays',
    syntax: 'append(x, values, after = length(x))',
    description: 'Add elements to a vector at a specified position',
    example: { code: 'append(1:3, 99, after = 1)', output: '[1] 1 99 2 3' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Creates a new vector, does not modify in place'],
    priority: 'common',
  },
  {
    name: 'head',
    category: 'arrays',
    syntax: 'head(x, n = 6)',
    description: 'Return the first n elements',
    example: { code: 'head(1:10, 3)', output: '[1] 1 2 3' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Useful for quick data inspection',
    priority: 'common',
  },
  {
    name: 'tail',
    category: 'arrays',
    syntax: 'tail(x, n = 6)',
    description: 'Return the last n elements',
    example: { code: 'tail(1:10, 3)', output: '[1] 8 9 10' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'common',
  },
  {
    name: 'rev',
    category: 'arrays',
    syntax: 'rev(x)',
    description: 'Reverse a vector',
    example: { code: 'rev(1:5)', output: '[1] 5 4 3 2 1' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Common in palindrome and reversal problems',
    priority: 'essential',
  },
  {
    name: 'unique',
    category: 'arrays',
    syntax: 'unique(x)',
    description: 'Remove duplicate values from a vector',
    example: { code: 'unique(c(1, 2, 2, 3, 3, 3))', output: '[1] 1 2 3' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Essential for finding distinct elements',
    priority: 'essential',
  },
  {
    name: 'which',
    category: 'searching',
    syntax: 'which(x)',
    description: 'Return indices where condition is TRUE',
    example: { code: 'which(c(1, 5, 3, 8) > 4)', output: '[1] 2 4' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns integer(0) if no matches'],
    interviewTip: 'Key function for finding positions of elements',
    priority: 'essential',
  },
  {
    name: 'which.min',
    category: 'searching',
    syntax: 'which.min(x) / which.max(x)',
    description: 'Return index of first minimum/maximum value',
    example: { code: 'which.max(c(1, 5, 3, 8, 2))', output: '[1] 4' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns first occurrence if multiple min/max exist'],
    priority: 'common',
  },
  {
    name: '%in%',
    category: 'searching',
    syntax: 'x %in% table',
    description: 'Check if elements of x are in table',
    example: { code: 'c(1, 2, 5) %in% c(1, 2, 3)', output: '[1] TRUE TRUE FALSE' },
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Vectorized membership testing',
    priority: 'essential',
  },
  {
    name: 'match',
    category: 'searching',
    syntax: 'match(x, table)',
    description: 'Return positions of first matches of x in table',
    example: { code: 'match(c("b", "d"), c("a", "b", "c"))', output: '[1] 2 NA' },
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns NA for no match'],
    priority: 'common',
  },

  // ============ SORTING ============
  {
    name: 'sort',
    category: 'sorting',
    syntax: 'sort(x, decreasing = FALSE)',
    description: 'Sort a vector in ascending or descending order',
    example: { code: 'sort(c(3, 1, 4, 1, 5))', output: '[1] 1 1 3 4 5' },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    gotchas: ['NA values are removed by default'],
    interviewTip: 'Use decreasing = TRUE for descending order',
    priority: 'essential',
  },
  {
    name: 'order',
    category: 'sorting',
    syntax: 'order(..., decreasing = FALSE)',
    description: 'Return indices that would sort the vector',
    example: { code: 'order(c(3, 1, 4))', output: '[1] 2 1 3' },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Use x[order(x)] to sort, allows custom sorting with multiple keys',
    priority: 'essential',
  },
  // ============ APPLY FAMILY (functional) ============
  {
    name: 'lapply',
    category: 'functional',
    syntax: 'lapply(X, FUN, ...)',
    description: 'Apply function to each element, return list',
    example: { code: 'lapply(1:3, function(x) x^2)', output: '[[1]] 1\n[[2]] 4\n[[3]] 9' },
    timeComplexity: 'O(n * f(x))',
    spaceComplexity: 'O(n)',
    interviewTip: 'Returns list - use sapply for vector output',
    priority: 'essential',
  },
  {
    name: 'sapply',
    category: 'functional',
    syntax: 'sapply(X, FUN, ...)',
    description: 'Apply function to each element, simplify to vector/matrix',
    example: { code: 'sapply(1:3, function(x) x^2)', output: '[1] 1 4 9' },
    timeComplexity: 'O(n * f(x))',
    spaceComplexity: 'O(n)',
    gotchas: ['Return type depends on function output - can be unpredictable'],
    interviewTip: 'Like lapply but simplifies output automatically',
    priority: 'essential',
  },
  {
    name: 'vapply',
    category: 'functional',
    syntax: 'vapply(X, FUN, FUN.VALUE)',
    description: 'Apply function with specified return type',
    example: { code: 'vapply(1:3, function(x) x^2, numeric(1))', output: '[1] 1 4 9' },
    timeComplexity: 'O(n * f(x))',
    spaceComplexity: 'O(n)',
    interviewTip: 'Safer than sapply - return type is guaranteed',
    priority: 'common',
  },
  {
    name: 'mapply',
    category: 'functional',
    syntax: 'mapply(FUN, ...)',
    description: 'Apply function to multiple vectors in parallel',
    example: { code: 'mapply(function(x, y) x + y, 1:3, 10:12)', output: '[1] 11 13 15' },
    timeComplexity: 'O(n * f(x))',
    spaceComplexity: 'O(n)',
    interviewTip: 'Multivariate version of sapply',
    priority: 'common',
  },
  {
    name: 'apply',
    category: 'functional',
    syntax: 'apply(X, MARGIN, FUN)',
    description: 'Apply function over array margins (rows=1, cols=2)',
    example: { code: 'apply(matrix(1:6, 2, 3), 1, sum)', output: '[1] 9 12' },
    timeComplexity: 'O(n * f(x))',
    spaceComplexity: 'O(n)',
    gotchas: ['MARGIN=1 for rows, MARGIN=2 for columns'],
    interviewTip: 'Essential for matrix operations in interviews',
    priority: 'essential',
  },
  {
    name: 'tapply',
    category: 'functional',
    syntax: 'tapply(X, INDEX, FUN)',
    description: 'Apply function to groups defined by INDEX',
    example: { code: 'tapply(1:6, c(1,1,2,2,3,3), sum)', output: '1  2  3\n3  7 11' },
    timeComplexity: 'O(n * f(x))',
    spaceComplexity: 'O(n)',
    interviewTip: 'Group-by operations without external packages',
    priority: 'common',
  },
  {
    name: 'Reduce',
    category: 'functional',
    syntax: 'Reduce(f, x, init)',
    description: 'Successively apply binary function to reduce vector',
    example: { code: 'Reduce(`+`, 1:5)', output: '[1] 15' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'R equivalent of fold/reduce from functional programming',
    priority: 'common',
  },
  {
    name: 'Filter',
    category: 'functional',
    syntax: 'Filter(f, x)',
    description: 'Extract elements where function returns TRUE',
    example: { code: 'Filter(function(x) x > 2, 1:5)', output: '[1] 3 4 5' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Functional alternative to logical subsetting',
    priority: 'common',
  },
  // ============ STRING FUNCTIONS ============
  {
    name: 'paste',
    category: 'strings',
    syntax: 'paste(..., sep = " ") or paste0(...)',
    description: 'Concatenate strings with separator',
    example: { code: 'paste("Hello", "World", sep = "-")', output: '[1] "Hello-World"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['paste0 is same as paste with sep=""'],
    interviewTip: 'Use collapse to join vector elements into single string',
    priority: 'essential',
  },
  {
    name: 'nchar',
    category: 'strings',
    syntax: 'nchar(x)',
    description: 'Count number of characters in string',
    example: { code: 'nchar("Hello")', output: '[1] 5' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns NA for NA input, not 2'],
    priority: 'essential',
  },
  {
    name: 'substr',
    category: 'strings',
    syntax: 'substr(x, start, stop)',
    description: 'Extract substring by position (1-indexed)',
    example: { code: 'substr("Hello", 2, 4)', output: '[1] "ell"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Indices are 1-based, not 0-based'],
    interviewTip: 'Use for substring extraction problems',
    priority: 'essential',
  },
  {
    name: 'strsplit',
    category: 'strings',
    syntax: 'strsplit(x, split)',
    description: 'Split string by delimiter into list of character vectors',
    example: { code: 'strsplit("a,b,c", ",")', output: '[[1]] "a" "b" "c"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns a list, use [[1]] to get vector'],
    interviewTip: 'Common for parsing input strings',
    priority: 'essential',
  },
  {
    name: 'grep',
    category: 'strings',
    syntax: 'grep(pattern, x) or grepl(pattern, x)',
    description: 'Find pattern matches (grep: indices, grepl: logical)',
    example: { code: 'grep("a", c("apple", "banana", "cherry"))', output: '[1] 1 2' },
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(n)',
    gotchas: ['Uses regex by default, use fixed=TRUE for literal matching'],
    interviewTip: 'grepl returns logical vector for filtering',
    priority: 'essential',
  },
  {
    name: 'gsub',
    category: 'strings',
    syntax: 'gsub(pattern, replacement, x)',
    description: 'Replace all occurrences of pattern',
    example: { code: 'gsub("a", "X", "banana")', output: '[1] "bXnXnX"' },
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(n)',
    gotchas: ['sub replaces only first occurrence, gsub replaces all'],
    priority: 'essential',
  },
  {
    name: 'toupper',
    category: 'strings',
    syntax: 'toupper(x) / tolower(x)',
    description: 'Convert string to upper/lower case',
    example: { code: 'toupper("Hello")', output: '[1] "HELLO"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'common',
  },
  {
    name: 'sprintf',
    category: 'strings',
    syntax: 'sprintf(fmt, ...)',
    description: 'Format strings with placeholders',
    example: {
      code: 'sprintf("Value: %d, Name: %s", 42, "test")',
      output: '[1] "Value: 42, Name: test"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['%d for integer, %f for float, %s for string'],
    priority: 'common',
  },

  // ============ MATH FUNCTIONS ============
  {
    name: 'sum',
    category: 'math',
    syntax: 'sum(..., na.rm = FALSE)',
    description: 'Sum of vector elements',
    example: { code: 'sum(1:10)', output: '[1] 55' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns NA if any NA present unless na.rm=TRUE'],
    interviewTip: 'Use na.rm=TRUE to handle missing values',
    priority: 'essential',
  },
  {
    name: 'mean',
    category: 'math',
    syntax: 'mean(x, na.rm = FALSE)',
    description: 'Arithmetic mean of vector',
    example: { code: 'mean(c(1, 2, 3, 4, 5))', output: '[1] 3' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns NA if any NA present unless na.rm=TRUE'],
    priority: 'essential',
  },
  {
    name: 'max',
    category: 'math',
    syntax: 'max(..., na.rm = FALSE)',
    description: 'Maximum value in vector',
    example: { code: 'max(c(3, 1, 4, 1, 5))', output: '[1] 5' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns -Inf for empty vector'],
    priority: 'essential',
  },
  {
    name: 'min',
    category: 'math',
    syntax: 'min(..., na.rm = FALSE)',
    description: 'Minimum value in vector',
    example: { code: 'min(c(3, 1, 4, 1, 5))', output: '[1] 1' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns Inf for empty vector'],
    priority: 'essential',
  },
  {
    name: 'abs',
    category: 'math',
    syntax: 'abs(x)',
    description: 'Absolute value',
    example: { code: 'abs(c(-3, -1, 2))', output: '[1] 3 1 2' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'essential',
  },
  {
    name: 'sqrt',
    category: 'math',
    syntax: 'sqrt(x)',
    description: 'Square root',
    example: { code: 'sqrt(c(4, 9, 16))', output: '[1] 2 3 4' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns NaN for negative numbers'],
    priority: 'common',
  },
  {
    name: 'floor',
    category: 'math',
    syntax: 'floor(x) / ceiling(x) / round(x, digits)',
    description: 'Round down/up/to specified digits',
    example: { code: 'floor(3.7)', output: '[1] 3' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'floor rounds toward -Inf, trunc rounds toward 0',
    priority: 'common',
  },
  {
    name: 'cumsum',
    category: 'math',
    syntax: 'cumsum(x) / cumprod(x) / cummax(x) / cummin(x)',
    description: 'Cumulative sum/product/max/min',
    example: { code: 'cumsum(1:5)', output: '[1] 1 3 6 10 15' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Essential for running totals and prefix sum problems',
    priority: 'essential',
  },
  {
    name: 'diff',
    category: 'math',
    syntax: 'diff(x, lag = 1)',
    description: 'Lagged differences between consecutive elements',
    example: { code: 'diff(c(1, 3, 6, 10))', output: '[1] 2 3 4' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns vector of length n-1'],
    interviewTip: 'Useful for finding consecutive differences',
    priority: 'common',
  },
  // ============ DATA MANIPULATION ============
  {
    name: 'table',
    category: 'collections',
    syntax: 'table(...)',
    description: 'Build frequency table / count occurrences',
    example: { code: 'table(c("a", "b", "a", "c", "a"))', output: 'a b c\n3 1 1' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(k)',
    interviewTip: 'Essential for counting frequencies - like Counter in Python',
    priority: 'essential',
  },
  {
    name: 'list',
    category: 'collections',
    syntax: 'list(...)',
    description: 'Create a list (heterogeneous collection)',
    example: {
      code: 'list(a = 1, b = "text", c = TRUE)',
      output: '$a [1] 1\n$b [1] "text"\n$c [1] TRUE',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Access with $ or [[]], not []'],
    interviewTip: 'Use for heterogeneous data structures',
    priority: 'essential',
  },
  {
    name: 'names',
    category: 'collections',
    syntax: 'names(x) or names(x) <- value',
    description: 'Get or set names of vector/list elements',
    example: { code: 'names(c(a = 1, b = 2))', output: '[1] "a" "b"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'common',
  },
  {
    name: 'unlist',
    category: 'collections',
    syntax: 'unlist(x, recursive = TRUE)',
    description: 'Flatten a list to a vector',
    example: { code: 'unlist(list(a = 1:2, b = 3:4))', output: 'a1 a2 b1 b2\n 1  2  3  4' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Use to convert list results to vectors',
    priority: 'common',
  },
  {
    name: 'is.na',
    category: 'type-conversion',
    syntax: 'is.na(x) / is.null(x) / is.numeric(x)',
    description: 'Test for NA, NULL, or type',
    example: { code: 'is.na(c(1, NA, 3))', output: '[1] FALSE TRUE FALSE' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Always check for NA in data processing',
    priority: 'essential',
  },
  {
    name: 'as.numeric',
    category: 'type-conversion',
    syntax: 'as.numeric(x) / as.character(x) / as.integer(x)',
    description: 'Type conversion functions',
    example: { code: 'as.numeric(c("1", "2", "3"))', output: '[1] 1 2 3' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Invalid conversions produce NA with warning'],
    priority: 'essential',
  },
  {
    name: 'any',
    category: 'functional',
    syntax: 'any(..., na.rm = FALSE)',
    description: 'Check if any element is TRUE',
    example: { code: 'any(c(FALSE, TRUE, FALSE))', output: '[1] TRUE' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Short-circuits on first TRUE',
    priority: 'essential',
  },
  {
    name: 'all',
    category: 'functional',
    syntax: 'all(..., na.rm = FALSE)',
    description: 'Check if all elements are TRUE',
    example: { code: 'all(c(TRUE, TRUE, FALSE))', output: '[1] FALSE' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Short-circuits on first FALSE',
    priority: 'essential',
  },
  {
    name: 'setdiff',
    category: 'sets',
    syntax: 'setdiff(x, y) / union(x, y) / intersect(x, y)',
    description: 'Set operations: difference, union, intersection',
    example: { code: 'setdiff(1:5, 3:7)', output: '[1] 1 2' },
    timeComplexity: 'O(n + m)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Essential for set-based interview problems',
    priority: 'essential',
  },
  {
    name: 'duplicated',
    category: 'arrays',
    syntax: 'duplicated(x)',
    description: 'Identify duplicate values (TRUE for duplicates)',
    example: {
      code: 'duplicated(c(1, 2, 2, 3, 3, 3))',
      output: '[1] FALSE FALSE TRUE FALSE TRUE TRUE',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Use !duplicated(x) to keep first occurrence of each value',
    priority: 'common',
  },
];
