/**
 * Swift Cheatsheet
 *
 * Essential Swift methods and operations for coding interviews.
 * Covers arrays, strings, dictionaries, sets, optionals, and functional programming.
 */

import type { CheatsheetEntry } from './types';

export const swiftCheatsheet: CheatsheetEntry[] = [
  // ============ ARRAYS ============
  {
    name: 'append',
    category: 'arrays',
    syntax: 'array.append(element)',
    description: 'Add an element to the end of an array',
    example: {
      code: 'var nums = [1, 2, 3]\nnums.append(4)\nprint(nums)',
      output: '[1, 2, 3, 4]',
    },
    timeComplexity: 'O(1) amortized',
    spaceComplexity: 'O(1)',
    gotchas: ['Array must be declared with var, not let'],
    interviewTip: 'Use append for building results incrementally',
    priority: 'essential',
  },
  {
    name: 'insert',
    category: 'arrays',
    syntax: 'array.insert(element, at: index)',
    description: 'Insert an element at a specific index',
    example: {
      code: 'var nums = [1, 2, 4]\nnums.insert(3, at: 2)\nprint(nums)',
      output: '[1, 2, 3, 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Index must be valid (0...count)', 'Elements after index are shifted'],
    priority: 'common',
  },
  {
    name: 'remove',
    category: 'arrays',
    syntax: 'array.remove(at: index)',
    description: 'Remove and return element at index',
    example: {
      code: 'var nums = [1, 2, 3, 4]\nlet removed = nums.remove(at: 1)\nprint(removed, nums)',
      output: '2 [1, 3, 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Index must be valid', 'Returns the removed element'],
    priority: 'essential',
  },
  {
    name: 'removeLast / popLast',
    category: 'arrays',
    syntax: 'array.removeLast() / array.popLast()',
    description: 'Remove and return last element (popLast returns optional)',
    example: {
      code: 'var nums = [1, 2, 3]\nlet last = nums.removeLast()\nprint(last, nums)',
      output: '3 [1, 2]',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['removeLast crashes on empty array', 'popLast returns nil safely'],
    interviewTip: 'Use popLast for safe stack operations',
    priority: 'essential',
  },
  {
    name: 'first / last',
    category: 'arrays',
    syntax: 'array.first / array.last',
    description: 'Access first or last element as optional',
    example: {
      code: 'let nums = [1, 2, 3]\nprint(nums.first!, nums.last!)',
      output: '1 3',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns nil for empty array', 'Force unwrap (!) crashes on nil'],
    interviewTip: 'Use optional binding for safe access',
    priority: 'essential',
  },
  {
    name: 'count / isEmpty',
    category: 'arrays',
    syntax: 'array.count / array.isEmpty',
    description: 'Get element count or check if empty',
    example: {
      code: 'let nums = [1, 2, 3]\nprint(nums.count, nums.isEmpty)',
      output: '3 false',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Prefer isEmpty over count == 0',
    priority: 'essential',
  },
  {
    name: 'contains',
    category: 'arrays',
    syntax: 'array.contains(element)',
    description: 'Check if array contains an element',
    example: {
      code: 'let nums = [1, 2, 3, 4, 5]\nprint(nums.contains(3))',
      output: 'true',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Linear search - use Set for O(1) lookups'],
    interviewTip: 'Convert to Set if doing many lookups',
    priority: 'essential',
  },
  {
    name: 'firstIndex',
    category: 'arrays',
    syntax: 'array.firstIndex(of: element)',
    description: 'Find index of first occurrence',
    example: {
      code: 'let nums = [1, 2, 3, 2, 1]\nprint(nums.firstIndex(of: 2)!)',
      output: '1',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns nil if not found', 'Element must be Equatable'],
    priority: 'common',
  },
  {
    name: 'reversed',
    category: 'arrays',
    syntax: 'array.reversed() / array.reverse()',
    description: 'Return reversed view or reverse in place',
    example: {
      code: 'let nums = [1, 2, 3]\nprint(Array(nums.reversed()))',
      output: '[3, 2, 1]',
    },
    timeComplexity: 'O(1) for view, O(n) to materialize',
    spaceComplexity: 'O(1) for view',
    gotchas: ['reversed() returns ReversedCollection', 'reverse() mutates in place'],
    priority: 'common',
  },
  {
    name: 'swapAt',
    category: 'arrays',
    syntax: 'array.swapAt(i, j)',
    description: 'Swap elements at two indices',
    example: {
      code: 'var nums = [1, 2, 3]\nnums.swapAt(0, 2)\nprint(nums)',
      output: '[3, 2, 1]',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Essential for in-place sorting algorithms',
    priority: 'common',
  },
  {
    name: 'subscript range',
    category: 'arrays',
    syntax: 'array[start..<end]',
    description: 'Get a slice of the array',
    example: {
      code: 'let nums = [0, 1, 2, 3, 4]\nprint(Array(nums[1..<4]))',
      output: '[1, 2, 3]',
    },
    timeComplexity: 'O(1) for slice',
    spaceComplexity: 'O(1) for slice',
    gotchas: ['Returns ArraySlice, wrap in Array() if needed'],
    interviewTip: 'Use ... for inclusive range, ..< for exclusive',
    priority: 'essential',
  },

  // ============ STRINGS ============
  {
    name: 'String to Array',
    category: 'strings',
    syntax: 'Array(string)',
    description: 'Convert string to array of characters',
    example: {
      code: 'let s = "hello"\nlet chars = Array(s)\nprint(chars)',
      output: '["h", "e", "l", "l", "o"]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Essential for string manipulation problems',
    priority: 'essential',
  },
  {
    name: 'String from Array',
    category: 'strings',
    syntax: 'String(charArray)',
    description: 'Convert character array back to string',
    example: {
      code: 'let chars: [Character] = ["h", "i"]\nprint(String(chars))',
      output: 'hi',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'essential',
  },
  {
    name: 'count (String)',
    category: 'strings',
    syntax: 'string.count',
    description: 'Get the number of characters',
    example: {
      code: 'let s = "hello"\nprint(s.count)',
      output: '5',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['O(n) because Swift strings are Unicode-aware'],
    interviewTip: 'Cache count if used repeatedly in loops',
    priority: 'essential',
  },
  {
    name: 'hasPrefix / hasSuffix',
    category: 'strings',
    syntax: 'string.hasPrefix(prefix) / string.hasSuffix(suffix)',
    description: 'Check if string starts/ends with substring',
    example: {
      code: 'let s = "hello world"\nprint(s.hasPrefix("hello"), s.hasSuffix("world"))',
      output: 'true true',
    },
    timeComplexity: 'O(k) where k is prefix/suffix length',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },
  {
    name: 'lowercased / uppercased',
    category: 'strings',
    syntax: 'string.lowercased() / string.uppercased()',
    description: 'Convert to lowercase or uppercase',
    example: {
      code: 'let s = "Hello"\nprint(s.lowercased(), s.uppercased())',
      output: 'hello HELLO',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Useful for case-insensitive comparisons',
    priority: 'essential',
  },
  {
    name: 'split',
    category: 'strings',
    syntax: 'string.split(separator: Character)',
    description: 'Split string into array of substrings',
    example: {
      code: 'let s = "a,b,c"\nlet parts = s.split(separator: ",")\nprint(parts.map { String($0) })',
      output: '["a", "b", "c"]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns [Substring], may need String() conversion'],
    interviewTip: 'Use components(separatedBy:) for string separator',
    priority: 'essential',
  },
  {
    name: 'joined',
    category: 'strings',
    syntax: 'array.joined(separator: String)',
    description: 'Join array elements into a string',
    example: {
      code: 'let parts = ["a", "b", "c"]\nprint(parts.joined(separator: "-"))',
      output: 'a-b-c',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'common',
  },
  {
    name: 'Character properties',
    category: 'strings',
    syntax: 'char.isLetter / char.isNumber / char.isWhitespace',
    description: 'Check character type properties',
    example: {
      code: 'let c: Character = "A"\nprint(c.isLetter, c.isUppercase)',
      output: 'true true',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Essential for parsing and validation problems',
    priority: 'essential',
  },
  {
    name: 'Character.asciiValue',
    category: 'strings',
    syntax: 'char.asciiValue',
    description: 'Get ASCII value of a character',
    example: {
      code: 'let c: Character = "A"\nprint(c.asciiValue!)',
      output: '65',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns nil for non-ASCII characters'],
    interviewTip: 'Use for character arithmetic in alphabet problems',
    priority: 'common',
  },

  // ============ DICTIONARIES (Maps) ============
  {
    name: 'Dictionary literal',
    category: 'maps',
    syntax: 'var dict: [Key: Value] = [:]',
    description: 'Create an empty dictionary',
    example: {
      code: 'var freq: [Character: Int] = [:]\nfreq["a"] = 1\nprint(freq)',
      output: '["a": 1]',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Use for frequency counting problems',
    priority: 'essential',
  },
  {
    name: 'Dictionary subscript',
    category: 'maps',
    syntax: 'dict[key]',
    description: 'Get or set value for key (returns optional)',
    example: {
      code: 'var dict = ["a": 1]\nprint(dict["a"] ?? 0, dict["b"] ?? 0)',
      output: '1 0',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns nil if key not found', 'Use ?? for default value'],
    priority: 'essential',
  },
  {
    name: 'Dictionary default value',
    category: 'maps',
    syntax: 'dict[key, default: value]',
    description: 'Get value with default, enables in-place mutation',
    example: {
      code: 'var freq: [String: Int] = [:]\nfreq["a", default: 0] += 1\nprint(freq)',
      output: '["a": 1]',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Perfect for counting - cleaner than ?? nil coalescing',
    priority: 'essential',
  },
  {
    name: 'keys / values',
    category: 'maps',
    syntax: 'dict.keys / dict.values',
    description: 'Get collection of keys or values',
    example: {
      code: 'let dict = ["a": 1, "b": 2]\nprint(Array(dict.keys).sorted())',
      output: '["a", "b"]',
    },
    timeComplexity: 'O(1) for view',
    spaceComplexity: 'O(1) for view',
    gotchas: ['Order is not guaranteed', 'Wrap in Array() if needed'],
    priority: 'essential',
  },
  {
    name: 'removeValue',
    category: 'maps',
    syntax: 'dict.removeValue(forKey: key)',
    description: 'Remove and return value for key',
    example: {
      code: 'var dict = ["a": 1, "b": 2]\nlet removed = dict.removeValue(forKey: "a")\nprint(removed ?? -1)',
      output: '1',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns nil if key not found'],
    priority: 'common',
  },

  // ============ SETS ============
  {
    name: 'Set literal',
    category: 'sets',
    syntax: 'var set: Set<Type> = []',
    description: 'Create an empty set',
    example: {
      code: 'var seen: Set<Int> = []\nseen.insert(1)\nprint(seen)',
      output: '[1]',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Use for O(1) membership testing',
    priority: 'essential',
  },
  {
    name: 'Set from Array',
    category: 'sets',
    syntax: 'Set(array)',
    description: 'Create set from array (removes duplicates)',
    example: {
      code: 'let nums = [1, 2, 2, 3, 3, 3]\nlet unique = Set(nums)\nprint(unique.count)',
      output: '3',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Quick way to find unique elements',
    priority: 'essential',
  },
  {
    name: 'insert (Set)',
    category: 'sets',
    syntax: 'set.insert(element)',
    description: 'Add element to set, returns insertion result',
    example: {
      code: 'var set: Set = [1, 2]\nlet (inserted, _) = set.insert(3)\nprint(inserted, set.count)',
      output: 'true 3',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns tuple (inserted: Bool, memberAfterInsert: Element)'],
    interviewTip: 'Check inserted to detect duplicates',
    priority: 'essential',
  },
  {
    name: 'contains (Set)',
    category: 'sets',
    syntax: 'set.contains(element)',
    description: 'Check if element exists in set',
    example: {
      code: 'let set: Set = [1, 2, 3]\nprint(set.contains(2))',
      output: 'true',
    },
    timeComplexity: 'O(1) average',
    spaceComplexity: 'O(1)',
    interviewTip: 'Much faster than Array.contains() for repeated lookups',
    priority: 'essential',
  },
  {
    name: 'union / intersection',
    category: 'sets',
    syntax: 'set1.union(set2) / set1.intersection(set2)',
    description: 'Combine sets or find common elements',
    example: {
      code: 'let a: Set = [1, 2]\nlet b: Set = [2, 3]\nprint(a.union(b).sorted(), a.intersection(b))',
      output: '[1, 2, 3] [2]',
    },
    timeComplexity: 'O(m + n) for union, O(min(m,n)) for intersection',
    spaceComplexity: 'O(m + n)',
    interviewTip: 'Use formUnion/formIntersection to mutate in place',
    priority: 'common',
  },
  {
    name: 'subtracting',
    category: 'sets',
    syntax: 'set1.subtracting(set2)',
    description: 'Return set with elements in set1 but not set2',
    example: {
      code: 'let a: Set = [1, 2, 3]\nlet b: Set = [2, 3]\nprint(a.subtracting(b))',
      output: '[1]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'useful',
  },

  // ============ SORTING ============
  {
    name: 'sorted',
    category: 'sorting',
    syntax: 'array.sorted()',
    description: 'Return a sorted copy of the array',
    example: {
      code: 'let nums = [3, 1, 4, 1, 5]\nprint(nums.sorted())',
      output: '[1, 1, 3, 4, 5]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Use sort() to mutate in place',
    priority: 'essential',
  },
  {
    name: 'sorted with closure',
    category: 'sorting',
    syntax: 'array.sorted { $0 > $1 }',
    description: 'Sort with custom comparator',
    example: {
      code: 'let nums = [3, 1, 4]\nprint(nums.sorted { $0 > $1 })',
      output: '[4, 3, 1]',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Use sorted(by: >) for descending order',
    priority: 'essential',
  },
  {
    name: 'min / max',
    category: 'sorting',
    syntax: 'array.min() / array.max()',
    description: 'Get minimum or maximum element',
    example: {
      code: 'let nums = [3, 1, 4, 1, 5]\nprint(nums.min()!, nums.max()!)',
      output: '1 5',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns nil for empty array'],
    interviewTip: 'Faster than sorting just to get min/max',
    priority: 'essential',
  },

  // ============ FUNCTIONAL ============
  {
    name: 'map',
    category: 'functional',
    syntax: 'array.map { transform($0) }',
    description: 'Transform each element',
    example: {
      code: 'let nums = [1, 2, 3]\nprint(nums.map { $0 * 2 })',
      output: '[2, 4, 6]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Chain with filter and reduce for data pipelines',
    priority: 'essential',
  },
  {
    name: 'filter',
    category: 'functional',
    syntax: 'array.filter { predicate($0) }',
    description: 'Keep elements matching predicate',
    example: {
      code: 'let nums = [1, 2, 3, 4, 5]\nprint(nums.filter { $0 % 2 == 0 })',
      output: '[2, 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    priority: 'essential',
  },
  {
    name: 'reduce',
    category: 'functional',
    syntax: 'array.reduce(initial) { acc, elem in ... }',
    description: 'Combine elements into single value',
    example: {
      code: 'let nums = [1, 2, 3, 4]\nprint(nums.reduce(0, +))',
      output: '10',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use reduce(0, +) for sum, reduce(1, *) for product',
    priority: 'essential',
  },
  {
    name: 'flatMap',
    category: 'functional',
    syntax: 'array.flatMap { transform($0) }',
    description: 'Map and flatten nested arrays',
    example: {
      code: 'let nested = [[1, 2], [3, 4]]\nprint(nested.flatMap { $0 })',
      output: '[1, 2, 3, 4]',
    },
    timeComplexity: 'O(n * m)',
    spaceComplexity: 'O(n * m)',
    interviewTip: 'Use to flatten 2D arrays',
    priority: 'common',
  },
  {
    name: 'compactMap',
    category: 'functional',
    syntax: 'array.compactMap { transform($0) }',
    description: 'Map and remove nil values',
    example: {
      code: 'let strs = ["1", "2", "x", "4"]\nprint(strs.compactMap { Int($0) })',
      output: '[1, 2, 4]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Great for safe type conversion',
    priority: 'common',
  },
  {
    name: 'enumerated',
    category: 'functional',
    syntax: 'array.enumerated()',
    description: 'Get sequence of (index, element) pairs',
    example: {
      code: 'for (i, v) in ["a", "b"].enumerated() {\n  print(i, v)\n}',
      output: '0 a\n1 b',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Essential when you need both index and value',
    priority: 'essential',
  },
  {
    name: 'zip',
    category: 'functional',
    syntax: 'zip(sequence1, sequence2)',
    description: 'Combine two sequences into pairs',
    example: {
      code: 'let a = [1, 2, 3]\nlet b = ["a", "b", "c"]\nfor (n, s) in zip(a, b) { print(n, s) }',
      output: '1 a\n2 b\n3 c',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Stops at shorter sequence length'],
    interviewTip: 'Useful for parallel iteration',
    priority: 'common',
  },
  {
    name: 'first(where:)',
    category: 'functional',
    syntax: 'array.first { predicate($0) }',
    description: 'Find first element matching predicate',
    example: {
      code: 'let nums = [1, 2, 3, 4]\nprint(nums.first { $0 > 2 }!)',
      output: '3',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns nil if no match found'],
    interviewTip: 'More efficient than filter().first',
    priority: 'common',
  },

  // ============ OPTIONALS / TYPE CONVERSION ============
  {
    name: 'if let / guard let',
    category: 'type-conversion',
    syntax: 'if let value = optional { } / guard let value = optional else { return }',
    description: 'Safely unwrap optional values',
    example: {
      code: 'let x: Int? = 5\nif let value = x { print(value) }',
      output: '5',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use guard for early exit, if let for conditional logic',
    priority: 'essential',
  },
  {
    name: 'Nil coalescing (??)',
    category: 'type-conversion',
    syntax: 'optional ?? defaultValue',
    description: 'Provide default value for nil',
    example: {
      code: 'let x: Int? = nil\nprint(x ?? 0)',
      output: '0',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Great for providing defaults in one line',
    priority: 'essential',
  },
  {
    name: 'Optional chaining',
    category: 'type-conversion',
    syntax: 'optional?.property',
    description: 'Safely access properties of optional',
    example: {
      code: 'let arr: [Int]? = [1, 2, 3]\nprint(arr?.count ?? 0)',
      output: '3',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Chain multiple optionals: a?.b?.c',
    priority: 'essential',
  },

  // ============ MATH ============
  {
    name: 'abs',
    category: 'math',
    syntax: 'abs(number)',
    description: 'Get absolute value',
    example: {
      code: 'print(abs(-5), abs(3))',
      output: '5 3',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    priority: 'essential',
  },
  {
    name: 'Int.max / Int.min',
    category: 'math',
    syntax: 'Int.max / Int.min',
    description: 'Maximum and minimum Int values',
    example: {
      code: 'print(Int.max)\nprint(Int.min)',
      output: '9223372036854775807\n-9223372036854775808',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Useful for initializing min/max searches',
    priority: 'essential',
  },

  // ============ ITERATION ============
  {
    name: 'stride',
    category: 'iteration',
    syntax: 'stride(from: start, to: end, by: step)',
    description: 'Generate sequence with custom step',
    example: {
      code: 'for i in stride(from: 0, to: 10, by: 2) {\n  print(i, terminator: " ")\n}',
      output: '0 2 4 6 8',
    },
    timeComplexity: 'O(1) to create',
    spaceComplexity: 'O(1)',
    gotchas: ['to: is exclusive, through: is inclusive'],
    interviewTip: 'Use for stepping through arrays by 2, iterating backwards',
    priority: 'common',
  },
];
