/**
 * TypeScript Cheatsheet
 *
 * Essential TypeScript methods and type utilities for coding interviews.
 * Includes both standard JavaScript methods and TypeScript-specific patterns.
 */

import type { CheatsheetEntry } from './types';

export const typescriptCheatsheet: CheatsheetEntry[] = [
  // ==================== ARRAYS ====================
  {
    name: 'push',
    category: 'arrays',
    syntax: 'array.push(...items): number',
    description: 'Adds elements to end of array, returns new length',
    example: { code: 'const arr = [1, 2]; arr.push(3, 4);', output: '4 // arr = [1, 2, 3, 4]' },
    timeComplexity: 'O(1) amortized',
    spaceComplexity: 'O(1)',
    gotchas: ['Mutates original array', 'Returns length, not array'],
    interviewTip: 'Use for stack operations (LIFO)',
    priority: 'essential',
  },
  {
    name: 'pop',
    category: 'arrays',
    syntax: 'array.pop(): T | undefined',
    description: 'Removes and returns last element',
    example: { code: 'const arr = [1, 2, 3]; arr.pop();', output: '3 // arr = [1, 2]' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Mutates original array', 'Returns undefined if empty'],
    interviewTip: 'Use with push() for stack implementation',
    priority: 'essential',
  },
  {
    name: 'shift',
    category: 'arrays',
    syntax: 'array.shift(): T | undefined',
    description: 'Removes and returns first element',
    example: { code: 'const arr = [1, 2, 3]; arr.shift();', output: '1 // arr = [2, 3]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Mutates array', 'O(n) due to re-indexing'],
    interviewTip: 'Use with push() for queue, but prefer linked list for large queues',
    priority: 'essential',
  },
  {
    name: 'unshift',
    category: 'arrays',
    syntax: 'array.unshift(...items): number',
    description: 'Adds elements to start of array, returns new length',
    example: { code: 'const arr = [2, 3]; arr.unshift(0, 1);', output: '4 // arr = [0, 1, 2, 3]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Mutates array', 'O(n) due to re-indexing'],
    priority: 'common',
  },
  {
    name: 'slice',
    category: 'arrays',
    syntax: 'array.slice(start?, end?): T[]',
    description: 'Returns shallow copy of portion of array',
    example: { code: '[1, 2, 3, 4, 5].slice(1, 4);', output: '[2, 3, 4]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['End index is exclusive', 'Negative indices count from end'],
    interviewTip: 'Use slice() to clone array: arr.slice()',
    priority: 'essential',
  },
  {
    name: 'splice',
    category: 'arrays',
    syntax: 'array.splice(start, deleteCount?, ...items): T[]',
    description: 'Removes/replaces/adds elements in place',
    example: {
      code: 'const arr = [1, 2, 3]; arr.splice(1, 1, 5, 6);',
      output: '[2] // arr = [1, 5, 6, 3]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Mutates original array', 'Returns removed elements'],
    interviewTip: 'Useful for in-place deletion: arr.splice(i, 1)',
    priority: 'essential',
  },
  {
    name: 'concat',
    category: 'arrays',
    syntax: 'array.concat(...arrays): T[]',
    description: 'Merges arrays into new array',
    example: { code: '[1, 2].concat([3, 4], [5]);', output: '[1, 2, 3, 4, 5]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Does not modify originals', 'Shallow copy only'],
    interviewTip: 'Prefer spread: [...arr1, ...arr2] for readability',
    priority: 'common',
  },
  {
    name: 'indexOf',
    category: 'searching',
    syntax: 'array.indexOf(searchElement, fromIndex?): number',
    description: 'Returns first index of element, or -1 if not found',
    example: { code: '[1, 2, 3, 2].indexOf(2);', output: '1' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Uses strict equality (===)', 'Returns -1, not undefined'],
    interviewTip: 'For objects, use findIndex() instead',
    priority: 'essential',
  },
  {
    name: 'includes',
    category: 'searching',
    syntax: 'array.includes(searchElement, fromIndex?): boolean',
    description: 'Checks if array contains element',
    example: { code: '[1, 2, 3].includes(2);', output: 'true' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Uses SameValueZero (NaN === NaN)', 'Also works on strings'],
    interviewTip: 'For O(1) lookup, convert to Set first',
    priority: 'essential',
  },
  {
    name: 'find',
    category: 'searching',
    syntax: 'array.find(predicate): T | undefined',
    description: 'Returns first element satisfying predicate',
    example: { code: '[1, 2, 3, 4].find(x => x > 2);', output: '3' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns undefined if not found', 'Stops at first match'],
    interviewTip: 'Use findIndex() if you need the index',
    priority: 'essential',
  },
  {
    name: 'findIndex',
    category: 'searching',
    syntax: 'array.findIndex(predicate): number',
    description: 'Returns index of first element satisfying predicate',
    example: { code: '[1, 2, 3, 4].findIndex(x => x > 2);', output: '2' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns -1 if not found'],
    interviewTip: 'Useful for finding objects by property',
    priority: 'essential',
  },
  {
    name: 'reverse',
    category: 'arrays',
    syntax: 'array.reverse(): T[]',
    description: 'Reverses array in place',
    example: { code: '[1, 2, 3].reverse();', output: '[3, 2, 1]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Mutates original array'],
    interviewTip: 'To reverse without mutating: [...arr].reverse()',
    priority: 'essential',
  },
  {
    name: 'fill',
    category: 'arrays',
    syntax: 'array.fill(value, start?, end?): T[]',
    description: 'Fills array with static value',
    example: { code: 'new Array(5).fill(0);', output: '[0, 0, 0, 0, 0]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Same reference for objects', 'Mutates original'],
    interviewTip: 'For 2D arrays, use Array.from() to avoid shared references',
    priority: 'essential',
  },
  {
    name: 'flat',
    category: 'arrays',
    syntax: 'array.flat(depth?): T[]',
    description: 'Flattens nested arrays to specified depth',
    example: { code: '[1, [2, [3]]].flat(2);', output: '[1, 2, 3]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Default depth is 1', 'Use Infinity for complete flatten'],
    interviewTip: 'Useful for tree traversal results',
    priority: 'common',
  },
  {
    name: 'Array.from',
    category: 'arrays',
    syntax: 'Array.from(iterable, mapFn?): T[]',
    description: 'Creates array from iterable with optional mapping',
    example: { code: 'Array.from({length: 3}, (_, i) => i * 2);', output: '[0, 2, 4]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Second arg is map function, not thisArg'],
    interviewTip: 'Great for creating initialized arrays or converting Sets/Maps',
    priority: 'essential',
  },
  {
    name: 'Array.isArray',
    category: 'arrays',
    syntax: 'Array.isArray(value): boolean',
    description: 'Checks if value is an array',
    example: { code: 'Array.isArray([1, 2]);', output: 'true' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['typeof [] returns "object"'],
    interviewTip: 'Always use this over typeof for array check',
    priority: 'common',
  },

  // ==================== FUNCTIONAL ====================
  {
    name: 'map',
    category: 'functional',
    syntax: 'array.map(callback): U[]',
    description: 'Creates new array with results of calling function on every element',
    example: { code: '[1, 2, 3].map(x => x * 2);', output: '[2, 4, 6]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns new array', 'Callback receives (value, index, array)'],
    interviewTip: 'Chain with filter() for transform + filter operations',
    priority: 'essential',
  },
  {
    name: 'filter',
    category: 'functional',
    syntax: 'array.filter(predicate): T[]',
    description: 'Creates new array with elements passing the test',
    example: { code: '[1, 2, 3, 4].filter(x => x % 2 === 0);', output: '[2, 4]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns empty array if no matches'],
    interviewTip: 'Combine with map() but consider reduce() for single pass',
    priority: 'essential',
  },
  {
    name: 'reduce',
    category: 'functional',
    syntax: 'array.reduce(callback, initialValue?): U',
    description: 'Reduces array to single value by applying function',
    example: { code: '[1, 2, 3].reduce((acc, x) => acc + x, 0);', output: '6' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Always provide initialValue', 'Empty array without initial throws'],
    interviewTip: 'Extremely versatile - can implement map, filter, groupBy',
    priority: 'essential',
  },
  {
    name: 'forEach',
    category: 'iteration',
    syntax: 'array.forEach(callback): void',
    description: 'Executes function for each element',
    example: { code: '[1, 2, 3].forEach(x => console.log(x));', output: '1 2 3' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Cannot break early', 'Returns undefined'],
    interviewTip: 'Use for loop if you need to break early',
    priority: 'essential',
  },
  {
    name: 'some',
    category: 'functional',
    syntax: 'array.some(predicate): boolean',
    description: 'Tests if at least one element passes',
    example: { code: '[1, 2, 3].some(x => x > 2);', output: 'true' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Short-circuits on first true', 'Empty array returns false'],
    interviewTip: 'Like logical OR across array',
    priority: 'essential',
  },
  {
    name: 'every',
    category: 'functional',
    syntax: 'array.every(predicate): boolean',
    description: 'Tests if all elements pass',
    example: { code: '[2, 4, 6].every(x => x % 2 === 0);', output: 'true' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Short-circuits on first false', 'Empty array returns true'],
    interviewTip: 'Like logical AND across array',
    priority: 'essential',
  },
  {
    name: 'reduceRight',
    category: 'functional',
    syntax: 'array.reduceRight(callback, initialValue?): U',
    description: 'Reduce from right to left',
    example: {
      code: '[[1], [2], [3]].reduceRight((a, b) => a.concat(b), []);',
      output: '[3, 2, 1]',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Same behavior as reduce but reversed'],
    interviewTip: 'Useful for right-to-left composition',
    priority: 'useful',
  },

  // ==================== SORTING ====================
  {
    name: 'sort',
    category: 'sorting',
    syntax: 'array.sort(compareFn?): T[]',
    description: 'Sorts array in place',
    example: { code: '[3, 1, 2].sort((a, b) => a - b);', output: '[1, 2, 3]' },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(log n)',
    gotchas: ['Default sorts as strings!', 'Mutates original array', 'a - b for ascending numbers'],
    interviewTip: 'Always provide compareFn for numbers. Descending: (a, b) => b - a',
    priority: 'essential',
  },
  {
    name: 'toSorted',
    category: 'sorting',
    syntax: 'array.toSorted(compareFn?): T[]',
    description: 'Returns new sorted array without mutating original',
    example: {
      code: 'const arr = [3, 1, 2]; arr.toSorted();',
      output: '[1, 2, 3] // arr unchanged',
    },
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    gotchas: ['ES2023 feature', 'Same sorting rules as sort()'],
    interviewTip: 'Prefer over [...arr].sort() for immutable sorting',
    priority: 'common',
  },

  // ==================== STRINGS ====================
  {
    name: 'split',
    category: 'strings',
    syntax: 'string.split(separator, limit?): string[]',
    description: 'Splits string into array by separator',
    example: { code: '"a,b,c".split(",");', output: '["a", "b", "c"]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['"".split("") returns []', 'Regex separators supported'],
    interviewTip: 'str.split("") to get character array',
    priority: 'essential',
  },
  {
    name: 'join',
    category: 'arrays',
    syntax: 'array.join(separator?): string',
    description: 'Joins array elements into string',
    example: { code: '["a", "b", "c"].join("-");', output: '"a-b-c"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Default separator is comma', 'null/undefined become empty string'],
    interviewTip: 'Combine with split() for string manipulation',
    priority: 'essential',
  },
  {
    name: 'substring',
    category: 'strings',
    syntax: 'string.substring(start, end?): string',
    description: 'Returns part of string between indices',
    example: { code: '"hello".substring(1, 4);', output: '"ell"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['End is exclusive', 'Swaps args if start > end'],
    interviewTip: 'Prefer slice() which handles negatives better',
    priority: 'common',
  },
  {
    name: 'charAt',
    category: 'strings',
    syntax: 'string.charAt(index): string',
    description: 'Returns character at index',
    example: { code: '"hello".charAt(1);', output: '"e"' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: [
      'Returns empty string if out of bounds',
      'str[i] returns undefined for invalid index',
    ],
    interviewTip: 'Use bracket notation str[i] for most cases',
    priority: 'common',
  },
  {
    name: 'charCodeAt',
    category: 'strings',
    syntax: 'string.charCodeAt(index): number',
    description: 'Returns UTF-16 code unit at index',
    example: { code: '"ABC".charCodeAt(0);', output: '65' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns NaN if out of bounds'],
    interviewTip: 'Useful for character math: charCodeAt(0) - 97 for a-z index',
    priority: 'essential',
  },
  {
    name: 'String.fromCharCode',
    category: 'strings',
    syntax: 'String.fromCharCode(...codes): string',
    description: 'Creates string from UTF-16 code units',
    example: { code: 'String.fromCharCode(65, 66, 67);', output: '"ABC"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Limited to BMP (0-65535)'],
    interviewTip: 'Pair with charCodeAt for character manipulation',
    priority: 'essential',
  },
  {
    name: 'toLowerCase',
    category: 'strings',
    syntax: 'string.toLowerCase(): string',
    description: 'Converts string to lowercase',
    example: { code: '"Hello".toLowerCase();', output: '"hello"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns new string', 'Locale-independent'],
    interviewTip: 'Always normalize case for case-insensitive comparison',
    priority: 'essential',
  },
  {
    name: 'toUpperCase',
    category: 'strings',
    syntax: 'string.toUpperCase(): string',
    description: 'Converts string to uppercase',
    example: { code: '"hello".toUpperCase();', output: '"HELLO"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns new string'],
    priority: 'common',
  },
  {
    name: 'trim',
    category: 'strings',
    syntax: 'string.trim(): string',
    description: 'Removes whitespace from both ends',
    example: { code: '"  hello  ".trim();', output: '"hello"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Does not modify interior whitespace'],
    interviewTip: 'Use trimStart()/trimEnd() for one-sided trim',
    priority: 'common',
  },
  {
    name: 'repeat',
    category: 'strings',
    syntax: 'string.repeat(count): string',
    description: 'Repeats string count times',
    example: { code: '"ab".repeat(3);', output: '"ababab"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Throws if count is negative or Infinity'],
    interviewTip: 'Useful for padding or generating patterns',
    priority: 'common',
  },
  {
    name: 'padStart',
    category: 'strings',
    syntax: 'string.padStart(targetLength, padString?): string',
    description: 'Pads start of string to target length',
    example: { code: '"5".padStart(3, "0");', output: '"005"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Truncates padString if needed'],
    interviewTip: 'Great for formatting numbers',
    priority: 'common',
  },
  {
    name: 'startsWith',
    category: 'strings',
    syntax: 'string.startsWith(searchString, position?): boolean',
    description: 'Checks if string starts with given substring',
    example: { code: '"hello".startsWith("he");', output: 'true' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Case-sensitive'],
    priority: 'common',
  },
  {
    name: 'replace',
    category: 'strings',
    syntax: 'string.replace(searchValue, replaceValue): string',
    description: 'Replaces first match with replacement',
    example: { code: '"hello".replace("l", "L");', output: '"heLlo"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Only replaces first match with string', 'Use /g flag or replaceAll for all'],
    interviewTip: 'replaceAll() or /pattern/g for global replace',
    priority: 'common',
  },

  // ==================== MAPS ====================
  {
    name: 'Map.set',
    category: 'maps',
    syntax: 'map.set(key, value): Map',
    description: 'Adds or updates key-value pair',
    example: { code: 'const m = new Map(); m.set("a", 1);', output: 'Map { "a" => 1 }' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns the Map for chaining', 'Any value can be key'],
    interviewTip: 'Use Map over object when keys are not strings',
    priority: 'essential',
  },
  {
    name: 'Map.get',
    category: 'maps',
    syntax: 'map.get(key): V | undefined',
    description: 'Returns value for key',
    example: { code: 'new Map([["a", 1]]).get("a");', output: '1' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns undefined if not found'],
    interviewTip: 'Check existence with has() before get()',
    priority: 'essential',
  },
  {
    name: 'Map.has',
    category: 'maps',
    syntax: 'map.has(key): boolean',
    description: 'Checks if key exists in Map',
    example: { code: 'new Map([["a", 1]]).has("a");', output: 'true' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Essential for counting frequency problems',
    priority: 'essential',
  },
  {
    name: 'Map.delete',
    category: 'maps',
    syntax: 'map.delete(key): boolean',
    description: 'Removes key-value pair, returns if existed',
    example: { code: 'const m = new Map([["a", 1]]); m.delete("a");', output: 'true' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },

  // ==================== SETS ====================
  {
    name: 'Set.add',
    category: 'sets',
    syntax: 'set.add(value): Set',
    description: 'Adds value to Set',
    example: { code: 'const s = new Set(); s.add(1).add(2);', output: 'Set { 1, 2 }' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Chainable', 'Duplicate values ignored'],
    interviewTip: 'Perfect for tracking seen elements',
    priority: 'essential',
  },
  {
    name: 'Set.has',
    category: 'sets',
    syntax: 'set.has(value): boolean',
    description: 'Checks if value exists in Set',
    example: { code: 'new Set([1, 2, 3]).has(2);', output: 'true' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Use for O(1) lookups instead of array.includes()',
    priority: 'essential',
  },
  {
    name: 'Set.delete',
    category: 'sets',
    syntax: 'set.delete(value): boolean',
    description: 'Removes value, returns if existed',
    example: { code: 'const s = new Set([1]); s.delete(1);', output: 'true' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    priority: 'common',
  },

  // ==================== OBJECTS ====================
  {
    name: 'Object.keys',
    category: 'objects',
    syntax: 'Object.keys(obj): string[]',
    description: 'Returns array of own enumerable property names',
    example: { code: 'Object.keys({ a: 1, b: 2 });', output: '["a", "b"]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Returns strings only', 'Does not include inherited properties'],
    interviewTip: 'Use with forEach/map to iterate over objects',
    priority: 'essential',
  },
  {
    name: 'Object.values',
    category: 'objects',
    syntax: 'Object.values(obj): T[]',
    description: 'Returns array of own enumerable property values',
    example: { code: 'Object.values({ a: 1, b: 2 });', output: '[1, 2]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Useful for summing or aggregating values',
    priority: 'essential',
  },
  {
    name: 'Object.entries',
    category: 'objects',
    syntax: 'Object.entries(obj): [string, T][]',
    description: 'Returns array of [key, value] pairs',
    example: { code: 'Object.entries({ a: 1, b: 2 });', output: '[["a", 1], ["b", 2]]' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Keys are always strings'],
    interviewTip: 'Great for destructuring in loops: for (const [k, v] of entries)',
    priority: 'essential',
  },
  {
    name: 'Object.fromEntries',
    category: 'objects',
    syntax: 'Object.fromEntries(iterable): object',
    description: 'Creates object from key-value pairs',
    example: { code: 'Object.fromEntries([["a", 1], ["b", 2]]);', output: '{ a: 1, b: 2 }' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    interviewTip: 'Inverse of Object.entries - great for Map to object',
    priority: 'common',
  },
  {
    name: 'Object.assign',
    category: 'objects',
    syntax: 'Object.assign(target, ...sources): T',
    description: 'Copies properties from sources to target',
    example: { code: 'Object.assign({}, { a: 1 }, { b: 2 });', output: '{ a: 1, b: 2 }' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Shallow copy only', 'Mutates target'],
    interviewTip: 'Prefer spread {...obj1, ...obj2} for clarity',
    priority: 'common',
  },
  {
    name: 'Object.hasOwn',
    category: 'objects',
    syntax: 'Object.hasOwn(obj, prop): boolean',
    description: 'Checks if object has own property',
    example: { code: 'Object.hasOwn({ a: 1 }, "a");', output: 'true' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['ES2022 feature', 'Safer than hasOwnProperty'],
    interviewTip: 'Prefer over obj.hasOwnProperty(prop)',
    priority: 'common',
  },

  // ==================== MATH ====================
  {
    name: 'Math.max',
    category: 'math',
    syntax: 'Math.max(...values): number',
    description: 'Returns largest of given numbers',
    example: { code: 'Math.max(1, 5, 3);', output: '5' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns -Infinity if no args', 'Math.max(...arr) for arrays'],
    interviewTip: 'Use spread for arrays: Math.max(...arr)',
    priority: 'essential',
  },
  {
    name: 'Math.min',
    category: 'math',
    syntax: 'Math.min(...values): number',
    description: 'Returns smallest of given numbers',
    example: { code: 'Math.min(1, 5, 3);', output: '1' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns Infinity if no args'],
    priority: 'essential',
  },
  {
    name: 'Math.floor',
    category: 'math',
    syntax: 'Math.floor(x): number',
    description: 'Rounds down to nearest integer',
    example: { code: 'Math.floor(4.7);', output: '4' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Negative numbers round toward -Infinity'],
    interviewTip: 'Use for array index calculation: Math.floor(arr.length / 2)',
    priority: 'essential',
  },
  {
    name: 'Math.ceil',
    category: 'math',
    syntax: 'Math.ceil(x): number',
    description: 'Rounds up to nearest integer',
    example: { code: 'Math.ceil(4.2);', output: '5' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Useful for pagination: Math.ceil(total / pageSize)',
    priority: 'common',
  },
  {
    name: 'Math.abs',
    category: 'math',
    syntax: 'Math.abs(x): number',
    description: 'Returns absolute value',
    example: { code: 'Math.abs(-5);', output: '5' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    interviewTip: 'Essential for distance calculations',
    priority: 'essential',
  },
  {
    name: 'Math.round',
    category: 'math',
    syntax: 'Math.round(x): number',
    description: 'Rounds to nearest integer',
    example: { code: 'Math.round(4.5);', output: '5' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['0.5 rounds up', 'Negative -0.5 rounds up toward 0'],
    priority: 'common',
  },
  {
    name: 'Math.pow',
    category: 'math',
    syntax: 'Math.pow(base, exponent): number',
    description: 'Returns base raised to exponent power',
    example: { code: 'Math.pow(2, 10);', output: '1024' },
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Use ** operator as alternative'],
    interviewTip: 'Prefer 2 ** 10 syntax for readability',
    priority: 'common',
  },
  {
    name: 'Math.sqrt',
    category: 'math',
    syntax: 'Math.sqrt(x): number',
    description: 'Returns square root',
    example: { code: 'Math.sqrt(16);', output: '4' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Returns NaN for negative numbers'],
    priority: 'common',
  },

  // ==================== TYPE CONVERSION ====================
  {
    name: 'parseInt',
    category: 'type-conversion',
    syntax: 'parseInt(string, radix?): number',
    description: 'Parses string to integer',
    example: { code: 'parseInt("42", 10);', output: '42' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: [
      'Always specify radix!',
      'Stops at first non-numeric char',
      'Returns NaN if cannot parse',
    ],
    interviewTip: 'Always use radix 10: parseInt(str, 10)',
    priority: 'essential',
  },
  {
    name: 'parseFloat',
    category: 'type-conversion',
    syntax: 'parseFloat(string): number',
    description: 'Parses string to floating-point number',
    example: { code: 'parseFloat("3.14");', output: '3.14' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['No radix parameter', 'Stops at first invalid char'],
    priority: 'common',
  },
  {
    name: 'Number',
    category: 'type-conversion',
    syntax: 'Number(value): number',
    description: 'Converts value to number',
    example: { code: 'Number("42");', output: '42' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    gotchas: ['Empty string becomes 0', 'null becomes 0', 'undefined becomes NaN'],
    interviewTip: 'Use + operator for quick conversion: +str',
    priority: 'essential',
  },
  {
    name: 'String',
    category: 'type-conversion',
    syntax: 'String(value): string',
    description: 'Converts value to string',
    example: { code: 'String(42);', output: '"42"' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['null becomes "null"', 'undefined becomes "undefined"'],
    interviewTip: 'Can also use: value.toString() or template literal',
    priority: 'common',
  },
  {
    name: 'Boolean',
    category: 'type-conversion',
    syntax: 'Boolean(value): boolean',
    description: 'Converts value to boolean',
    example: { code: 'Boolean(0);', output: 'false' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Falsy: 0, "", null, undefined, NaN, false'],
    interviewTip: 'Use !! for quick conversion: !!value',
    priority: 'common',
  },
  {
    name: 'Number.isNaN',
    category: 'type-conversion',
    syntax: 'Number.isNaN(value): boolean',
    description: 'Checks if value is NaN',
    example: { code: 'Number.isNaN(NaN);', output: 'true' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Different from global isNaN()!', 'Only true for actual NaN'],
    interviewTip: 'Always use Number.isNaN, not global isNaN',
    priority: 'common',
  },
  {
    name: 'Number.isInteger',
    category: 'type-conversion',
    syntax: 'Number.isInteger(value): boolean',
    description: 'Checks if value is an integer',
    example: { code: 'Number.isInteger(5.0);', output: 'true' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['5.0 is integer, 5.5 is not'],
    priority: 'common',
  },

  // ==================== TYPESCRIPT-SPECIFIC ====================
  {
    name: 'typeof type guard',
    category: 'type-conversion',
    syntax: 'typeof value === "string"',
    description: 'Narrows type based on typeof check',
    example: {
      code: 'function f(x: string | number) { if (typeof x === "string") x.toUpperCase(); }',
      output: 'Type narrowed to string',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Works for: string, number, boolean, undefined, function, symbol, bigint'],
    interviewTip: 'Essential for union type handling',
    priority: 'essential',
  },
  {
    name: 'instanceof type guard',
    category: 'type-conversion',
    syntax: 'value instanceof Class',
    description: 'Narrows type based on class check',
    example: {
      code: 'function f(e: Error | string) { if (e instanceof Error) e.message; }',
      output: 'Type narrowed to Error',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Only works with classes', 'Does not work across realms'],
    interviewTip: 'Use for class-based type narrowing',
    priority: 'essential',
  },
  {
    name: 'in type guard',
    category: 'type-conversion',
    syntax: '"property" in object',
    description: 'Narrows type based on property existence',
    example: {
      code: 'function f(x: A | B) { if ("name" in x) x.name; }',
      output: 'Type narrowed by discriminant',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Checks prototype chain too'],
    interviewTip: 'Great for discriminated unions',
    priority: 'common',
  },
  {
    name: 'as assertion',
    category: 'type-conversion',
    syntax: 'value as Type',
    description: 'Type assertion (tells compiler to trust you)',
    example: {
      code: 'const el = document.getElementById("id") as HTMLInputElement;',
      output: 'el typed as HTMLInputElement',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['No runtime check!', 'Can cause runtime errors if wrong', 'Avoid when possible'],
    interviewTip: 'Prefer type guards over assertions',
    priority: 'common',
  },
  {
    name: 'as const',
    category: 'type-conversion',
    syntax: 'value as const',
    description: 'Creates literal/readonly type',
    example: { code: 'const arr = [1, 2, 3] as const;', output: 'Type: readonly [1, 2, 3]' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Makes arrays readonly tuples', 'Makes objects deeply readonly'],
    interviewTip: 'Use for constant configs and lookup objects',
    priority: 'common',
  },
  {
    name: 'Non-null assertion',
    category: 'type-conversion',
    syntax: 'value!',
    description: 'Asserts value is not null/undefined',
    example: {
      code: 'const el = document.getElementById("id")!;',
      output: 'Removes null from type',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['No runtime check!', 'Will cause runtime error if null'],
    interviewTip: 'Avoid in favor of proper null checks',
    priority: 'useful',
  },
  {
    name: 'Optional chaining',
    category: 'objects',
    syntax: 'obj?.prop or obj?.[expr] or func?.()',
    description: 'Safely access nested properties',
    example: { code: 'const x = obj?.nested?.value;', output: 'undefined if any null/undefined' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Short-circuits to undefined', 'Does not prevent accessing undefined'],
    interviewTip: 'Essential for safely navigating nullable objects',
    priority: 'essential',
  },
  {
    name: 'Nullish coalescing',
    category: 'objects',
    syntax: 'value ?? defaultValue',
    description: 'Returns right side if left is null/undefined',
    example: { code: 'const x = null ?? "default";', output: '"default"' },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Only null/undefined trigger default', '0 and "" do NOT trigger'],
    interviewTip: 'Prefer over || when 0 or "" are valid values',
    priority: 'essential',
  },
  {
    name: 'Spread operator',
    category: 'arrays',
    syntax: '[...arr] or {...obj}',
    description: 'Spreads iterable elements or object properties',
    example: {
      code: 'const copy = [...arr]; const merged = {...a, ...b};',
      output: 'Shallow copies/merges',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Shallow copy only', 'Object spread overwrites left with right'],
    interviewTip: 'Standard way to clone arrays/objects immutably',
    priority: 'essential',
  },
  {
    name: 'Destructuring',
    category: 'objects',
    syntax: 'const { a, b } = obj; const [x, y] = arr;',
    description: 'Extract values from objects/arrays into variables',
    example: {
      code: 'const { name, age = 0 } = person;',
      output: 'Extracts with optional default',
    },
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(1)',
    gotchas: ['Can rename: { a: newName }', 'Can set defaults: { a = 1 }'],
    interviewTip: 'Use in function params for cleaner API',
    priority: 'essential',
  },
  {
    name: 'Rest parameters',
    category: 'functional',
    syntax: 'function f(...args: T[])',
    description: 'Collects remaining arguments into array',
    example: {
      code: 'function sum(...nums: number[]) { return nums.reduce((a, b) => a + b, 0); }',
      output: 'sum(1, 2, 3) => 6',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Must be last parameter', 'Creates real array unlike arguments'],
    interviewTip: 'Prefer over arguments object',
    priority: 'common',
  },
  {
    name: 'Template literals',
    category: 'strings',
    syntax: '`string $expression`',
    description: 'String interpolation with embedded expressions using backticks',
    example: {
      code: 'const name = "World";\nconst msg = `Hello, ` + name + `!`;',
      output: '"Hello, World!"',
    },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Supports multi-line strings', 'Expressions are converted to strings'],
    interviewTip: 'Cleaner than string concatenation',
    priority: 'essential',
  },
  {
    name: 'JSON.stringify',
    category: 'type-conversion',
    syntax: 'JSON.stringify(value, replacer?, space?): string',
    description: 'Converts value to JSON string',
    example: { code: 'JSON.stringify({ a: 1 });', output: '\'{"a":1}\'' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['undefined, functions, symbols are omitted', 'Circular refs throw'],
    interviewTip: 'Use for deep equality check (but slow)',
    priority: 'essential',
  },
  {
    name: 'JSON.parse',
    category: 'type-conversion',
    syntax: 'JSON.parse(text, reviver?): any',
    description: 'Parses JSON string to value',
    example: { code: 'JSON.parse(\'{"a":1}\');', output: '{ a: 1 }' },
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n)',
    gotchas: ['Invalid JSON throws SyntaxError', 'Returns any - needs type assertion'],
    interviewTip: 'Wrap in try-catch for safety',
    priority: 'essential',
  },
];
