import type { Problem } from '../types';

/**
 * C++ coding drill problems
 * Covers: Vector Operations, Algorithm Header, String Operations, Map/Set
 */

export const cppProblems: Problem[] = [
  // ============================================================
  // Vector Operations (STL)
  // ============================================================
  {
    id: 'cpp-vector-push-back-1',
    category: 'Vector Methods',
    difficulty: 'easy',
    title: 'Add Element with push_back()',
    text: 'Add the value 42 to the end of the vector using push_back()',
    setup: 'std::vector<int> nums = {1, 2, 3};',
    setupCode: 'std::vector<int> nums = {1, 2, 3};',
    expected: '{1, 2, 3, 42}',
    sample: 'nums.push_back(42);',
    hints: ['push_back() adds an element to the end of the vector'],
    tags: ['vector', 'push_back', 'stl'],
  },
  {
    id: 'cpp-vector-pop-back-1',
    category: 'Vector Methods',
    difficulty: 'easy',
    title: 'Remove Last Element with pop_back()',
    text: 'Remove the last element from the vector using pop_back()',
    setup: 'std::vector<int> nums = {1, 2, 3, 4};',
    setupCode: 'std::vector<int> nums = {1, 2, 3, 4};',
    expected: '{1, 2, 3}',
    sample: 'nums.pop_back();',
    hints: ['pop_back() removes the last element from the vector'],
    tags: ['vector', 'pop_back', 'stl'],
  },
  {
    id: 'cpp-vector-size-1',
    category: 'Vector Methods',
    difficulty: 'easy',
    title: 'Get Vector Size',
    text: 'Get the number of elements in the vector using size()',
    setup: 'std::vector<int> nums = {10, 20, 30, 40, 50};',
    setupCode: 'std::vector<int> nums = {10, 20, 30, 40, 50};',
    expected: '5',
    sample: 'nums.size()',
    hints: ['size() returns the number of elements in the vector'],
    tags: ['vector', 'size', 'stl'],
  },
  {
    id: 'cpp-vector-empty-1',
    category: 'Vector Methods',
    difficulty: 'easy',
    title: 'Check if Vector is Empty',
    text: 'Check if the vector is empty using empty()',
    setup: 'std::vector<int> nums = {};',
    setupCode: 'std::vector<int> nums = {};',
    expected: 'true',
    sample: 'nums.empty()',
    hints: ['empty() returns true if the vector has no elements'],
    tags: ['vector', 'empty', 'stl'],
  },
  {
    id: 'cpp-vector-front-1',
    category: 'Vector Methods',
    difficulty: 'easy',
    title: 'Get First Element with front()',
    text: 'Get the first element of the vector using front()',
    setup: 'std::vector<int> nums = {100, 200, 300};',
    setupCode: 'std::vector<int> nums = {100, 200, 300};',
    expected: '100',
    sample: 'nums.front()',
    hints: ['front() returns a reference to the first element'],
    tags: ['vector', 'front', 'stl'],
  },
  {
    id: 'cpp-vector-back-1',
    category: 'Vector Methods',
    difficulty: 'easy',
    title: 'Get Last Element with back()',
    text: 'Get the last element of the vector using back()',
    setup: 'std::vector<int> nums = {100, 200, 300};',
    setupCode: 'std::vector<int> nums = {100, 200, 300};',
    expected: '300',
    sample: 'nums.back()',
    hints: ['back() returns a reference to the last element'],
    tags: ['vector', 'back', 'stl'],
  },
  {
    id: 'cpp-vector-at-1',
    category: 'Vector Methods',
    difficulty: 'easy',
    title: 'Access Element with at()',
    text: 'Get the element at index 2 using the at() method',
    setup: 'std::vector<int> nums = {10, 20, 30, 40};',
    setupCode: 'std::vector<int> nums = {10, 20, 30, 40};',
    expected: '30',
    sample: 'nums.at(2)',
    hints: ['at() provides bounds-checked access to elements'],
    tags: ['vector', 'at', 'stl'],
  },
  {
    id: 'cpp-vector-subscript-1',
    category: 'Vector Methods',
    difficulty: 'easy',
    title: 'Access Element with operator[]',
    text: 'Get the element at index 1 using the subscript operator',
    setup: 'std::vector<std::string> words = {"hello", "world", "cpp"};',
    setupCode: 'std::vector<std::string> words = {"hello", "world", "cpp"};',
    expected: '"world"',
    sample: 'words[1]',
    hints: ['operator[] provides fast, unchecked access to elements'],
    tags: ['vector', 'operator[]', 'stl'],
  },
  {
    id: 'cpp-vector-begin-end-1',
    category: 'Vector Methods',
    difficulty: 'medium',
    title: 'Use begin() and end() with Algorithm',
    text: 'Fill the vector with the value 7 using std::fill with begin() and end()',
    setup: 'std::vector<int> nums(5);',
    setupCode: 'std::vector<int> nums(5);',
    expected: '{7, 7, 7, 7, 7}',
    sample: 'std::fill(nums.begin(), nums.end(), 7);',
    hints: ['begin() returns an iterator to the first element', 'end() returns an iterator past the last element'],
    tags: ['vector', 'begin', 'end', 'iterators', 'stl'],
  },
  {
    id: 'cpp-vector-clear-1',
    category: 'Vector Methods',
    difficulty: 'easy',
    title: 'Clear All Elements',
    text: 'Remove all elements from the vector using clear()',
    setup: 'std::vector<int> nums = {1, 2, 3, 4, 5};',
    setupCode: 'std::vector<int> nums = {1, 2, 3, 4, 5};',
    expected: '{}',
    sample: 'nums.clear();',
    hints: ['clear() removes all elements, making size() return 0'],
    tags: ['vector', 'clear', 'stl'],
  },
  {
    id: 'cpp-vector-insert-1',
    category: 'Vector Methods',
    difficulty: 'medium',
    title: 'Insert Element at Position',
    text: 'Insert the value 99 at index 2 using insert()',
    setup: 'std::vector<int> nums = {1, 2, 3, 4};',
    setupCode: 'std::vector<int> nums = {1, 2, 3, 4};',
    expected: '{1, 2, 99, 3, 4}',
    sample: 'nums.insert(nums.begin() + 2, 99);',
    hints: ['insert() takes an iterator position and a value'],
    tags: ['vector', 'insert', 'stl'],
  },
  {
    id: 'cpp-vector-erase-1',
    category: 'Vector Methods',
    difficulty: 'medium',
    title: 'Erase Element at Position',
    text: 'Erase the element at index 1 using erase()',
    setup: 'std::vector<int> nums = {10, 20, 30, 40};',
    setupCode: 'std::vector<int> nums = {10, 20, 30, 40};',
    expected: '{10, 30, 40}',
    sample: 'nums.erase(nums.begin() + 1);',
    hints: ['erase() takes an iterator position and removes that element'],
    tags: ['vector', 'erase', 'stl'],
  },

  // ============================================================
  // Algorithm Header
  // ============================================================
  {
    id: 'cpp-algo-sort-1',
    category: 'Algorithm Library',
    difficulty: 'easy',
    title: 'Sort Vector in Ascending Order',
    text: 'Sort the vector in ascending order using std::sort()',
    setup: 'std::vector<int> nums = {5, 2, 8, 1, 9};',
    setupCode: 'std::vector<int> nums = {5, 2, 8, 1, 9};',
    expected: '{1, 2, 5, 8, 9}',
    sample: 'std::sort(nums.begin(), nums.end());',
    hints: ['std::sort() sorts elements in ascending order by default'],
    tags: ['algorithm', 'sort', 'stl'],
  },
  {
    id: 'cpp-algo-sort-desc-1',
    category: 'Algorithm Library',
    difficulty: 'medium',
    title: 'Sort Vector in Descending Order',
    text: 'Sort the vector in descending order using std::sort() with std::greater<int>()',
    setup: 'std::vector<int> nums = {5, 2, 8, 1, 9};',
    setupCode: 'std::vector<int> nums = {5, 2, 8, 1, 9};',
    expected: '{9, 8, 5, 2, 1}',
    sample: 'std::sort(nums.begin(), nums.end(), std::greater<int>());',
    hints: ['Use std::greater<int>() as the third argument for descending order'],
    tags: ['algorithm', 'sort', 'stl'],
  },
  {
    id: 'cpp-algo-reverse-1',
    category: 'Algorithm Library',
    difficulty: 'easy',
    title: 'Reverse Vector Elements',
    text: 'Reverse the order of elements in the vector using std::reverse()',
    setup: 'std::vector<int> nums = {1, 2, 3, 4, 5};',
    setupCode: 'std::vector<int> nums = {1, 2, 3, 4, 5};',
    expected: '{5, 4, 3, 2, 1}',
    sample: 'std::reverse(nums.begin(), nums.end());',
    hints: ['std::reverse() reverses the order of elements in-place'],
    tags: ['algorithm', 'reverse', 'stl'],
  },
  {
    id: 'cpp-algo-find-1',
    category: 'Algorithm Library',
    difficulty: 'medium',
    title: 'Find Element in Vector',
    text: 'Find the value 30 in the vector and return an iterator to it using std::find()',
    setup: 'std::vector<int> nums = {10, 20, 30, 40, 50};',
    setupCode: 'std::vector<int> nums = {10, 20, 30, 40, 50};',
    expected: 'iterator to 30',
    sample: 'auto it = std::find(nums.begin(), nums.end(), 30);',
    hints: ['std::find() returns an iterator to the first matching element or end() if not found'],
    tags: ['algorithm', 'find', 'stl'],
  },
  {
    id: 'cpp-algo-count-1',
    category: 'Algorithm Library',
    difficulty: 'easy',
    title: 'Count Occurrences of Value',
    text: 'Count how many times the value 3 appears in the vector using std::count()',
    setup: 'std::vector<int> nums = {1, 3, 3, 4, 3, 5, 3};',
    setupCode: 'std::vector<int> nums = {1, 3, 3, 4, 3, 5, 3};',
    expected: '4',
    sample: 'std::count(nums.begin(), nums.end(), 3)',
    hints: ['std::count() returns the number of elements equal to the given value'],
    tags: ['algorithm', 'count', 'stl'],
  },
  {
    id: 'cpp-algo-accumulate-1',
    category: 'Algorithm Library',
    difficulty: 'easy',
    title: 'Sum All Elements with accumulate()',
    text: 'Calculate the sum of all elements using std::accumulate() (from <numeric>)',
    setup: 'std::vector<int> nums = {1, 2, 3, 4, 5};',
    setupCode: 'std::vector<int> nums = {1, 2, 3, 4, 5};',
    expected: '15',
    sample: 'std::accumulate(nums.begin(), nums.end(), 0)',
    hints: ['std::accumulate() is in the <numeric> header', 'The third argument is the initial value'],
    tags: ['algorithm', 'accumulate', 'numeric', 'stl'],
  },
  {
    id: 'cpp-algo-transform-1',
    category: 'Algorithm Library',
    difficulty: 'medium',
    title: 'Transform Elements with Lambda',
    text: 'Double each element in the vector using std::transform()',
    setup: 'std::vector<int> nums = {1, 2, 3, 4, 5};',
    setupCode: 'std::vector<int> nums = {1, 2, 3, 4, 5};',
    expected: '{2, 4, 6, 8, 10}',
    sample: 'std::transform(nums.begin(), nums.end(), nums.begin(), [](int x) { return x * 2; });',
    hints: ['std::transform() applies a function to each element', 'Use a lambda for the transformation'],
    tags: ['algorithm', 'transform', 'lambda', 'stl'],
  },
  {
    id: 'cpp-algo-copy-if-1',
    category: 'Algorithm Library',
    difficulty: 'medium',
    title: 'Copy Elements Matching Condition',
    text: 'Copy only even numbers to a new vector using std::copy_if()',
    setup: 'std::vector<int> nums = {1, 2, 3, 4, 5, 6};\nstd::vector<int> evens;',
    setupCode: 'std::vector<int> nums = {1, 2, 3, 4, 5, 6};\nstd::vector<int> evens;',
    expected: 'evens = {2, 4, 6}',
    sample: 'std::copy_if(nums.begin(), nums.end(), std::back_inserter(evens), [](int x) { return x % 2 == 0; });',
    hints: ['std::copy_if() copies elements where the predicate returns true', 'Use std::back_inserter() to append to the destination'],
    tags: ['algorithm', 'copy_if', 'stl'],
  },
  {
    id: 'cpp-algo-remove-if-1',
    category: 'Algorithm Library',
    difficulty: 'medium',
    title: 'Remove Elements Matching Condition',
    text: 'Remove all odd numbers from the vector using std::remove_if() and erase()',
    setup: 'std::vector<int> nums = {1, 2, 3, 4, 5, 6};',
    setupCode: 'std::vector<int> nums = {1, 2, 3, 4, 5, 6};',
    expected: '{2, 4, 6}',
    sample: 'nums.erase(std::remove_if(nums.begin(), nums.end(), [](int x) { return x % 2 != 0; }), nums.end());',
    hints: ['std::remove_if() moves non-matching elements to the front', 'Combine with erase() to actually remove elements (erase-remove idiom)'],
    tags: ['algorithm', 'remove_if', 'erase', 'stl'],
  },
  {
    id: 'cpp-algo-any-of-1',
    category: 'Algorithm Library',
    difficulty: 'easy',
    title: 'Check if Any Element Matches',
    text: 'Check if any element is greater than 10 using std::any_of()',
    setup: 'std::vector<int> nums = {5, 8, 12, 3, 7};',
    setupCode: 'std::vector<int> nums = {5, 8, 12, 3, 7};',
    expected: 'true',
    sample: 'std::any_of(nums.begin(), nums.end(), [](int x) { return x > 10; })',
    hints: ['std::any_of() returns true if any element satisfies the predicate'],
    tags: ['algorithm', 'any_of', 'stl'],
  },
  {
    id: 'cpp-algo-all-of-1',
    category: 'Algorithm Library',
    difficulty: 'easy',
    title: 'Check if All Elements Match',
    text: 'Check if all elements are positive using std::all_of()',
    setup: 'std::vector<int> nums = {1, 5, 3, 8, 2};',
    setupCode: 'std::vector<int> nums = {1, 5, 3, 8, 2};',
    expected: 'true',
    sample: 'std::all_of(nums.begin(), nums.end(), [](int x) { return x > 0; })',
    hints: ['std::all_of() returns true if all elements satisfy the predicate'],
    tags: ['algorithm', 'all_of', 'stl'],
  },
  {
    id: 'cpp-algo-none-of-1',
    category: 'Algorithm Library',
    difficulty: 'easy',
    title: 'Check if No Elements Match',
    text: 'Check if no elements are negative using std::none_of()',
    setup: 'std::vector<int> nums = {1, 5, 3, 8, 2};',
    setupCode: 'std::vector<int> nums = {1, 5, 3, 8, 2};',
    expected: 'true',
    sample: 'std::none_of(nums.begin(), nums.end(), [](int x) { return x < 0; })',
    hints: ['std::none_of() returns true if no elements satisfy the predicate'],
    tags: ['algorithm', 'none_of', 'stl'],
  },
  {
    id: 'cpp-algo-max-element-1',
    category: 'Algorithm Library',
    difficulty: 'easy',
    title: 'Find Maximum Element',
    text: 'Find the maximum element in the vector using std::max_element()',
    setup: 'std::vector<int> nums = {3, 7, 2, 9, 4};',
    setupCode: 'std::vector<int> nums = {3, 7, 2, 9, 4};',
    expected: '9',
    sample: '*std::max_element(nums.begin(), nums.end())',
    hints: ['std::max_element() returns an iterator to the largest element', 'Dereference the iterator to get the value'],
    tags: ['algorithm', 'max_element', 'stl'],
  },
  {
    id: 'cpp-algo-min-element-1',
    category: 'Algorithm Library',
    difficulty: 'easy',
    title: 'Find Minimum Element',
    text: 'Find the minimum element in the vector using std::min_element()',
    setup: 'std::vector<int> nums = {3, 7, 2, 9, 4};',
    setupCode: 'std::vector<int> nums = {3, 7, 2, 9, 4};',
    expected: '2',
    sample: '*std::min_element(nums.begin(), nums.end())',
    hints: ['std::min_element() returns an iterator to the smallest element', 'Dereference the iterator to get the value'],
    tags: ['algorithm', 'min_element', 'stl'],
  },

  // ============================================================
  // String Operations
  // ============================================================
  {
    id: 'cpp-string-length-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Get String Length',
    text: 'Get the length of the string using length()',
    setup: 'std::string str = "Hello, World!";',
    setupCode: 'std::string str = "Hello, World!";',
    expected: '13',
    sample: 'str.length()',
    hints: ['length() and size() both return the number of characters'],
    tags: ['string', 'length', 'stl'],
  },
  {
    id: 'cpp-string-size-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Get String Size',
    text: 'Get the size of the string using size()',
    setup: 'std::string str = "C++ Programming";',
    setupCode: 'std::string str = "C++ Programming";',
    expected: '15',
    sample: 'str.size()',
    hints: ['size() is equivalent to length() for strings'],
    tags: ['string', 'size', 'stl'],
  },
  {
    id: 'cpp-string-substr-1',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Extract Substring',
    text: 'Extract the substring "World" from the string using substr()',
    setup: 'std::string str = "Hello, World!";',
    setupCode: 'std::string str = "Hello, World!";',
    expected: '"World"',
    sample: 'str.substr(7, 5)',
    hints: ['substr(pos, len) extracts len characters starting from pos'],
    tags: ['string', 'substr', 'stl'],
  },
  {
    id: 'cpp-string-find-1',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Find Substring Position',
    text: 'Find the position of "World" in the string using find()',
    setup: 'std::string str = "Hello, World!";',
    setupCode: 'std::string str = "Hello, World!";',
    expected: '7',
    sample: 'str.find("World")',
    hints: ['find() returns the position of the first occurrence or std::string::npos if not found'],
    tags: ['string', 'find', 'stl'],
  },
  {
    id: 'cpp-string-rfind-1',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Find Last Occurrence',
    text: 'Find the position of the last \'o\' in the string using rfind()',
    setup: 'std::string str = "Hello, World!";',
    setupCode: 'std::string str = "Hello, World!";',
    expected: '8',
    sample: 'str.rfind(\'o\')',
    hints: ['rfind() searches from the end of the string'],
    tags: ['string', 'rfind', 'stl'],
  },
  {
    id: 'cpp-string-append-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Append String',
    text: 'Append " World!" to the string using append()',
    setup: 'std::string str = "Hello";',
    setupCode: 'std::string str = "Hello";',
    expected: '"Hello World!"',
    sample: 'str.append(" World!");',
    hints: ['append() adds characters to the end of the string'],
    tags: ['string', 'append', 'stl'],
  },
  {
    id: 'cpp-string-concat-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Concatenate with += Operator',
    text: 'Append " C++" to the string using the += operator',
    setup: 'std::string str = "Hello";',
    setupCode: 'std::string str = "Hello";',
    expected: '"Hello C++"',
    sample: 'str += " C++";',
    hints: ['The += operator is a convenient way to append strings'],
    tags: ['string', 'operator+=', 'stl'],
  },
  {
    id: 'cpp-string-c-str-1',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Get C-Style String',
    text: 'Get a C-style character array pointer using c_str()',
    setup: 'std::string str = "Hello";',
    setupCode: 'std::string str = "Hello";',
    expected: 'const char* pointing to "Hello"',
    sample: 'const char* cstr = str.c_str();',
    hints: ['c_str() returns a null-terminated character array'],
    tags: ['string', 'c_str', 'stl'],
  },
  {
    id: 'cpp-string-compare-1',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Compare Strings',
    text: 'Compare str1 with str2 using compare(). Return value: 0 if equal, < 0 if str1 < str2, > 0 if str1 > str2',
    setup: 'std::string str1 = "apple";\nstd::string str2 = "banana";',
    setupCode: 'std::string str1 = "apple";\nstd::string str2 = "banana";',
    expected: 'negative value (str1 < str2)',
    sample: 'str1.compare(str2)',
    hints: ['compare() returns 0 for equal strings, negative if less, positive if greater'],
    tags: ['string', 'compare', 'stl'],
  },

  // ============================================================
  // Map Operations
  // ============================================================
  {
    id: 'cpp-map-insert-1',
    category: 'Map Methods',
    difficulty: 'medium',
    title: 'Insert into Map',
    text: 'Insert a key-value pair ("apple", 5) into the map using insert()',
    setup: 'std::map<std::string, int> fruits;',
    setupCode: 'std::map<std::string, int> fruits;',
    expected: 'fruits["apple"] = 5',
    sample: 'fruits.insert({"apple", 5});',
    hints: ['insert() takes a std::pair or initializer list', 'Alternative: fruits.insert(std::make_pair("apple", 5));'],
    tags: ['map', 'insert', 'stl'],
  },
  {
    id: 'cpp-map-subscript-1',
    category: 'Map Methods',
    difficulty: 'easy',
    title: 'Insert/Access with operator[]',
    text: 'Insert or update the key "banana" with value 3 using operator[]',
    setup: 'std::map<std::string, int> fruits = {{"apple", 5}};',
    setupCode: 'std::map<std::string, int> fruits = {{"apple", 5}};',
    expected: 'fruits["banana"] = 3',
    sample: 'fruits["banana"] = 3;',
    hints: ['operator[] inserts a new element if the key does not exist'],
    tags: ['map', 'operator[]', 'stl'],
  },
  {
    id: 'cpp-map-erase-1',
    category: 'Map Methods',
    difficulty: 'easy',
    title: 'Erase Map Element',
    text: 'Remove the element with key "apple" from the map using erase()',
    setup: 'std::map<std::string, int> fruits = {{"apple", 5}, {"banana", 3}};',
    setupCode: 'std::map<std::string, int> fruits = {{"apple", 5}, {"banana", 3}};',
    expected: 'fruits = {{"banana", 3}}',
    sample: 'fruits.erase("apple");',
    hints: ['erase() can take a key directly or an iterator'],
    tags: ['map', 'erase', 'stl'],
  },
  {
    id: 'cpp-map-find-1',
    category: 'Map Methods',
    difficulty: 'medium',
    title: 'Find Element in Map',
    text: 'Find the element with key "apple" and return an iterator using find()',
    setup: 'std::map<std::string, int> fruits = {{"apple", 5}, {"banana", 3}};',
    setupCode: 'std::map<std::string, int> fruits = {{"apple", 5}, {"banana", 3}};',
    expected: 'iterator to {"apple", 5}',
    sample: 'auto it = fruits.find("apple");',
    hints: ['find() returns end() if the key is not found', 'Access value with it->second'],
    tags: ['map', 'find', 'stl'],
  },
  {
    id: 'cpp-map-count-1',
    category: 'Map Methods',
    difficulty: 'easy',
    title: 'Check if Key Exists',
    text: 'Check if the key "apple" exists using count()',
    setup: 'std::map<std::string, int> fruits = {{"apple", 5}, {"banana", 3}};',
    setupCode: 'std::map<std::string, int> fruits = {{"apple", 5}, {"banana", 3}};',
    expected: '1 (key exists)',
    sample: 'fruits.count("apple")',
    hints: ['count() returns 1 if key exists, 0 if not (for std::map)', 'For multimap, it can return values > 1'],
    tags: ['map', 'count', 'stl'],
  },
  {
    id: 'cpp-map-size-1',
    category: 'Map Methods',
    difficulty: 'easy',
    title: 'Get Map Size',
    text: 'Get the number of key-value pairs in the map using size()',
    setup: 'std::map<std::string, int> fruits = {{"apple", 5}, {"banana", 3}, {"orange", 7}};',
    setupCode: 'std::map<std::string, int> fruits = {{"apple", 5}, {"banana", 3}, {"orange", 7}};',
    expected: '3',
    sample: 'fruits.size()',
    hints: ['size() returns the number of elements in the map'],
    tags: ['map', 'size', 'stl'],
  },

  // ============================================================
  // Set Operations
  // ============================================================
  {
    id: 'cpp-set-insert-1',
    category: 'Set Methods',
    difficulty: 'easy',
    title: 'Insert into Set',
    text: 'Insert the value 42 into the set using insert()',
    setup: 'std::set<int> numbers = {1, 2, 3};',
    setupCode: 'std::set<int> numbers = {1, 2, 3};',
    expected: '{1, 2, 3, 42}',
    sample: 'numbers.insert(42);',
    hints: ['insert() adds an element if it does not already exist'],
    tags: ['set', 'insert', 'stl'],
  },
  {
    id: 'cpp-set-erase-1',
    category: 'Set Methods',
    difficulty: 'easy',
    title: 'Erase from Set',
    text: 'Remove the value 2 from the set using erase()',
    setup: 'std::set<int> numbers = {1, 2, 3, 4};',
    setupCode: 'std::set<int> numbers = {1, 2, 3, 4};',
    expected: '{1, 3, 4}',
    sample: 'numbers.erase(2);',
    hints: ['erase() removes the element with the given value'],
    tags: ['set', 'erase', 'stl'],
  },
  {
    id: 'cpp-set-find-1',
    category: 'Set Methods',
    difficulty: 'medium',
    title: 'Find Element in Set',
    text: 'Find the value 3 in the set and return an iterator using find()',
    setup: 'std::set<int> numbers = {1, 2, 3, 4, 5};',
    setupCode: 'std::set<int> numbers = {1, 2, 3, 4, 5};',
    expected: 'iterator to 3',
    sample: 'auto it = numbers.find(3);',
    hints: ['find() returns end() if the element is not found'],
    tags: ['set', 'find', 'stl'],
  },
  {
    id: 'cpp-set-count-1',
    category: 'Set Methods',
    difficulty: 'easy',
    title: 'Check if Element Exists in Set',
    text: 'Check if the value 3 exists in the set using count()',
    setup: 'std::set<int> numbers = {1, 2, 3, 4, 5};',
    setupCode: 'std::set<int> numbers = {1, 2, 3, 4, 5};',
    expected: '1 (element exists)',
    sample: 'numbers.count(3)',
    hints: ['count() returns 1 if element exists, 0 if not (for std::set)'],
    tags: ['set', 'count', 'stl'],
  },
  {
    id: 'cpp-set-size-1',
    category: 'Set Methods',
    difficulty: 'easy',
    title: 'Get Set Size',
    text: 'Get the number of elements in the set using size()',
    setup: 'std::set<int> numbers = {1, 2, 3, 4, 5};',
    setupCode: 'std::set<int> numbers = {1, 2, 3, 4, 5};',
    expected: '5',
    sample: 'numbers.size()',
    hints: ['size() returns the number of unique elements in the set'],
    tags: ['set', 'size', 'stl'],
  },
];

export default cppProblems;
