import type { Problem } from '../types';

/**
 * C# coding drill problems
 * Covers: List<T> Methods, LINQ Methods, String Methods, Array Methods
 */

export const csharpProblems: Problem[] = [
  // ============================================================
  // Modern C# Features
  // ============================================================
  {
    id: 'csharp-range-slice-1',
    category: 'Modern C# Features',
    difficulty: 'easy',
    title: 'Slice Array with Range Operator',
    text: 'Get the last 3 elements of the array using the range operator (..)',
    setup: 'int[] numbers = { 1, 2, 3, 4, 5, 6 };',
    setupCode: 'int[] numbers = { 1, 2, 3, 4, 5, 6 };',
    expected: '{ 4, 5, 6 }',
    sample: 'numbers[^3..]',
    hints: ['^n means n elements from the end', 'Range operator (..) creates a slice without copying'],
    tags: ['modern', 'range', 'index', 'c#8'],
  },
  {
    id: 'csharp-range-middle-1',
    category: 'Modern C# Features',
    difficulty: 'medium',
    title: 'Extract Middle Elements with Range',
    text: 'Get elements from index 1 to 4 (exclusive) using the range operator',
    setup: 'int[] numbers = { 10, 20, 30, 40, 50 };',
    setupCode: 'int[] numbers = { 10, 20, 30, 40, 50 };',
    expected: '{ 20, 30, 40 }',
    sample: 'numbers[1..4]',
    hints: ['Range is inclusive at start, exclusive at end', 'Similar to Python slicing syntax'],
    tags: ['modern', 'range', 'slice', 'c#8'],
  },
  {
    id: 'csharp-null-coalescing-1',
    category: 'Modern C# Features',
    difficulty: 'easy',
    title: 'Null Coalescing Operator',
    text: 'Return the name or "Unknown" if null using the null-coalescing operator (??)',
    setup: 'string? name = null;',
    setupCode: 'string? name = null;',
    expected: '"Unknown"',
    sample: 'name ?? "Unknown"',
    hints: ['?? returns the left operand if not null, otherwise the right', 'Works with nullable value types and reference types'],
    tags: ['modern', 'null', 'coalescing', 'nullable'],
  },
  {
    id: 'csharp-null-coalescing-assign-1',
    category: 'Modern C# Features',
    difficulty: 'medium',
    title: 'Null Coalescing Assignment',
    text: 'Assign "Default" to name only if it is null using ??=',
    setup: 'string? name = null;',
    setupCode: 'string? name = null;',
    expected: 'name = "Default"',
    sample: 'name ??= "Default";',
    hints: ['??= assigns only if the variable is null', 'Introduced in C# 8.0'],
    tags: ['modern', 'null', 'assignment', 'c#8'],
  },
  {
    id: 'csharp-pattern-is-1',
    category: 'Modern C# Features',
    difficulty: 'medium',
    title: 'Pattern Matching with is',
    text: 'Check if the object is a non-null string with length > 5 using pattern matching',
    setup: 'object? value = "Hello World";',
    setupCode: 'object? value = "Hello World";',
    expected: 'true',
    sample: 'value is string s && s.Length > 5',
    hints: ['Pattern matching with is can declare a variable', 'The variable is only in scope when the pattern matches'],
    tags: ['modern', 'pattern', 'is', 'c#7'],
  },
  {
    id: 'csharp-switch-expression-1',
    category: 'Modern C# Features',
    difficulty: 'medium',
    title: 'Switch Expression',
    text: 'Convert day number (1-7) to day name using a switch expression',
    setup: 'int day = 3;',
    setupCode: 'int day = 3;',
    expected: '"Wednesday"',
    sample: 'day switch { 1 => "Monday", 2 => "Tuesday", 3 => "Wednesday", 4 => "Thursday", 5 => "Friday", 6 => "Saturday", 7 => "Sunday", _ => "Invalid" }',
    hints: ['Switch expressions use => instead of case/break', 'Use _ for the default/discard pattern'],
    tags: ['modern', 'switch', 'expression', 'c#8'],
  },
  {
    id: 'csharp-string-interpolation-1',
    category: 'Modern C# Features',
    difficulty: 'easy',
    title: 'String Interpolation',
    text: 'Create a greeting message using string interpolation',
    setup: 'string name = "Alice";\nint age = 30;',
    setupCode: 'string name = "Alice";\nint age = 30;',
    expected: '"Hello, Alice! You are 30 years old."',
    sample: '$"Hello, {name}! You are {age} years old."',
    hints: ['String interpolation uses $ prefix', 'Expressions inside {} are evaluated at runtime'],
    tags: ['modern', 'string', 'interpolation', 'c#6'],
  },
  {
    id: 'csharp-raw-string-1',
    category: 'Modern C# Features',
    difficulty: 'medium',
    title: 'Raw String Literals',
    text: 'Create a JSON string using raw string literals (triple quotes)',
    setup: 'string name = "test";',
    setupCode: 'string name = "test";',
    expected: '{"name": "test"}',
    sample: '$$"""{"name": "{{name}}"}"""',
    hints: ['Raw strings start and end with """', 'Use $$ with {{ }} for interpolation in raw strings', 'Introduced in C# 11'],
    tags: ['modern', 'string', 'raw', 'c#11'],
  },

  // ============================================================
  // List<T> Methods
  // ============================================================
  {
    id: 'csharp-list-add-1',
    category: 'List Methods',
    difficulty: 'easy',
    title: 'Add Element to List',
    text: 'Add the value 42 to the end of the list using Add()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3 };',
    expected: '{ 1, 2, 3, 42 }',
    sample: 'numbers.Add(42);',
    hints: ['Add() appends a single element to the end of the list', 'Add() modifies the list in-place and returns void'],
    tags: ['list', 'add', 'collections'],
  },
  {
    id: 'csharp-list-addrange-1',
    category: 'List Methods',
    difficulty: 'easy',
    title: 'Add Multiple Elements',
    text: 'Add the elements { 4, 5, 6 } to the list using AddRange()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3 };',
    expected: '{ 1, 2, 3, 4, 5, 6 }',
    sample: 'numbers.AddRange(new[] { 4, 5, 6 });',
    hints: ['AddRange() adds all elements from a collection to the end of the list'],
    tags: ['list', 'addrange', 'collections'],
  },
  {
    id: 'csharp-list-remove-1',
    category: 'List Methods',
    difficulty: 'easy',
    title: 'Remove Element by Value',
    text: 'Remove the first occurrence of the value 3 using Remove()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 3 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 3 };',
    expected: '{ 1, 2, 4, 3 }',
    sample: 'numbers.Remove(3);',
    hints: ['Remove() removes the first occurrence and returns true if found'],
    tags: ['list', 'remove', 'collections'],
  },
  {
    id: 'csharp-list-removeat-1',
    category: 'List Methods',
    difficulty: 'easy',
    title: 'Remove Element by Index',
    text: 'Remove the element at index 2 using RemoveAt()',
    setup: 'List<int> numbers = new List<int> { 10, 20, 30, 40 };',
    setupCode: 'List<int> numbers = new List<int> { 10, 20, 30, 40 };',
    expected: '{ 10, 20, 40 }',
    sample: 'numbers.RemoveAt(2);',
    hints: ['RemoveAt() removes the element at the specified index'],
    tags: ['list', 'removeat', 'collections'],
  },
  {
    id: 'csharp-list-removeall-1',
    category: 'List Methods',
    difficulty: 'medium',
    title: 'Remove All Matching Elements',
    text: 'Remove all even numbers from the list using RemoveAll()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5, 6 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5, 6 };',
    expected: '{ 1, 3, 5 }',
    sample: 'numbers.RemoveAll(x => x % 2 == 0);',
    hints: ['RemoveAll() takes a Predicate<T> and removes all matching elements'],
    tags: ['list', 'removeall', 'lambda', 'collections'],
  },
  {
    id: 'csharp-list-contains-1',
    category: 'List Methods',
    difficulty: 'easy',
    title: 'Check if List Contains Element',
    text: 'Check if the list contains the value 3 using Contains()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5 };',
    expected: 'true',
    sample: 'numbers.Contains(3)',
    hints: ['Contains() returns true if the element exists in the list'],
    tags: ['list', 'contains', 'collections'],
  },
  {
    id: 'csharp-list-indexof-1',
    category: 'List Methods',
    difficulty: 'easy',
    title: 'Find Index of Element',
    text: 'Find the index of the value 30 using IndexOf()',
    setup: 'List<int> numbers = new List<int> { 10, 20, 30, 40 };',
    setupCode: 'List<int> numbers = new List<int> { 10, 20, 30, 40 };',
    expected: '2',
    sample: 'numbers.IndexOf(30)',
    hints: ['IndexOf() returns -1 if the element is not found'],
    tags: ['list', 'indexof', 'collections'],
  },
  {
    id: 'csharp-list-count-1',
    category: 'List Methods',
    difficulty: 'easy',
    title: 'Get List Count',
    text: 'Get the number of elements in the list using the Count property',
    setup: 'List<string> names = new List<string> { "Alice", "Bob", "Charlie" };',
    setupCode: 'List<string> names = new List<string> { "Alice", "Bob", "Charlie" };',
    expected: '3',
    sample: 'names.Count',
    hints: ['Count is a property, not a method, so no parentheses needed'],
    tags: ['list', 'count', 'collections'],
  },
  {
    id: 'csharp-list-sort-1',
    category: 'List Methods',
    difficulty: 'easy',
    title: 'Sort List in Ascending Order',
    text: 'Sort the list in ascending order using Sort()',
    setup: 'List<int> numbers = new List<int> { 5, 2, 8, 1, 9 };',
    setupCode: 'List<int> numbers = new List<int> { 5, 2, 8, 1, 9 };',
    expected: '{ 1, 2, 5, 8, 9 }',
    sample: 'numbers.Sort();',
    hints: ['Sort() sorts the list in-place in ascending order by default'],
    tags: ['list', 'sort', 'collections'],
  },
  {
    id: 'csharp-list-reverse-1',
    category: 'List Methods',
    difficulty: 'easy',
    title: 'Reverse List Order',
    text: 'Reverse the order of elements in the list using Reverse()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5 };',
    expected: '{ 5, 4, 3, 2, 1 }',
    sample: 'numbers.Reverse();',
    hints: ['Reverse() reverses the list in-place'],
    tags: ['list', 'reverse', 'collections'],
  },
  {
    id: 'csharp-list-toarray-1',
    category: 'List Methods',
    difficulty: 'easy',
    title: 'Convert List to Array',
    text: 'Convert the list to an array using ToArray()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3 };',
    expected: 'int[] { 1, 2, 3 }',
    sample: 'int[] arr = numbers.ToArray();',
    hints: ['ToArray() creates a new array containing all list elements'],
    tags: ['list', 'toarray', 'collections'],
  },
  {
    id: 'csharp-list-insert-1',
    category: 'List Methods',
    difficulty: 'easy',
    title: 'Insert Element at Index',
    text: 'Insert the value 99 at index 1 using Insert()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3 };',
    expected: '{ 1, 99, 2, 3 }',
    sample: 'numbers.Insert(1, 99);',
    hints: ['Insert() adds an element at the specified index', 'Existing elements shift to make room'],
    tags: ['list', 'insert', 'collections'],
  },
  {
    id: 'csharp-list-clear-1',
    category: 'List Methods',
    difficulty: 'easy',
    title: 'Clear All Elements',
    text: 'Remove all elements from the list using Clear()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5 };',
    expected: '{ } (empty list with Count = 0)',
    sample: 'numbers.Clear();',
    hints: ['Clear() removes all elements but keeps the list object', 'Count becomes 0, but Capacity may remain'],
    tags: ['list', 'clear', 'collections'],
  },
  {
    id: 'csharp-list-find-1',
    category: 'List Methods',
    difficulty: 'medium',
    title: 'Find First Matching Element',
    text: 'Find the first number greater than 15 using Find()',
    setup: 'List<int> numbers = new List<int> { 5, 10, 20, 25, 30 };',
    setupCode: 'List<int> numbers = new List<int> { 5, 10, 20, 25, 30 };',
    expected: '20',
    sample: 'numbers.Find(x => x > 15)',
    hints: ['Find() returns default(T) if no match is found', 'For reference types, default is null'],
    tags: ['list', 'find', 'predicate', 'collections'],
  },
  {
    id: 'csharp-list-findall-1',
    category: 'List Methods',
    difficulty: 'medium',
    title: 'Find All Matching Elements in List',
    text: 'Find all numbers greater than 15 using FindAll()',
    setup: 'List<int> numbers = new List<int> { 5, 10, 20, 25, 30 };',
    setupCode: 'List<int> numbers = new List<int> { 5, 10, 20, 25, 30 };',
    expected: '{ 20, 25, 30 }',
    sample: 'numbers.FindAll(x => x > 15)',
    hints: ['FindAll() returns a new List<T> with matching elements', 'Returns empty list if no matches'],
    tags: ['list', 'findall', 'predicate', 'collections'],
  },
  {
    id: 'csharp-list-exists-1',
    category: 'List Methods',
    difficulty: 'easy',
    title: 'Check if Element Exists in List',
    text: 'Check if any number is negative using Exists()',
    setup: 'List<int> numbers = new List<int> { 5, -3, 10, 8 };',
    setupCode: 'List<int> numbers = new List<int> { 5, -3, 10, 8 };',
    expected: 'true',
    sample: 'numbers.Exists(x => x < 0)',
    hints: ['Exists() is similar to LINQ Any() but is a List<T> method', 'Returns true if any element matches the predicate'],
    tags: ['list', 'exists', 'predicate', 'collections'],
  },
  {
    id: 'csharp-list-trueforall-1',
    category: 'List Methods',
    difficulty: 'medium',
    title: 'Check if All Elements Match',
    text: 'Check if all numbers are positive using TrueForAll()',
    setup: 'List<int> numbers = new List<int> { 1, 5, 10, 8 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 5, 10, 8 };',
    expected: 'true',
    sample: 'numbers.TrueForAll(x => x > 0)',
    hints: ['TrueForAll() is similar to LINQ All() but is a List<T> method', 'Returns true if all elements match the predicate'],
    tags: ['list', 'trueforall', 'predicate', 'collections'],
  },

  // ============================================================
  // Dictionary Methods
  // ============================================================
  {
    id: 'csharp-dict-add-1',
    category: 'Dictionary Methods',
    difficulty: 'easy',
    title: 'Add Key-Value Pair',
    text: 'Add a new entry with key "grape" and value 4 using Add()',
    setup: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    setupCode: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    expected: '{ apple: 1, banana: 2, grape: 4 }',
    sample: 'fruits.Add("grape", 4);',
    hints: ['Add() throws ArgumentException if key already exists', 'Use indexer fruits["key"] = value to add or update'],
    tags: ['dictionary', 'add', 'collections'],
  },
  {
    id: 'csharp-dict-trygetvalue-1',
    category: 'Dictionary Methods',
    difficulty: 'medium',
    title: 'Safely Get Value with TryGetValue',
    text: 'Try to get the value for key "banana" using TryGetValue()',
    setup: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    setupCode: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    expected: 'true and out value = 2',
    sample: 'fruits.TryGetValue("banana", out int value)',
    hints: ['TryGetValue() returns bool and sets out parameter', 'Avoids KeyNotFoundException when key might not exist'],
    tags: ['dictionary', 'trygetvalue', 'collections'],
  },
  {
    id: 'csharp-dict-containskey-1',
    category: 'Dictionary Methods',
    difficulty: 'easy',
    title: 'Check if Key Exists',
    text: 'Check if the dictionary contains the key "banana" using ContainsKey()',
    setup: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    setupCode: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    expected: 'true',
    sample: 'fruits.ContainsKey("banana")',
    hints: ['ContainsKey() is O(1) average time complexity', 'Prefer TryGetValue() if you also need the value'],
    tags: ['dictionary', 'containskey', 'collections'],
  },
  {
    id: 'csharp-dict-containsvalue-1',
    category: 'Dictionary Methods',
    difficulty: 'easy',
    title: 'Check if Value Exists',
    text: 'Check if the dictionary contains the value 2 using ContainsValue()',
    setup: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    setupCode: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    expected: 'true',
    sample: 'fruits.ContainsValue(2)',
    hints: ['ContainsValue() is O(n) as it must scan all values', 'Consider using a reverse lookup dictionary if needed frequently'],
    tags: ['dictionary', 'containsvalue', 'collections'],
  },
  {
    id: 'csharp-dict-remove-1',
    category: 'Dictionary Methods',
    difficulty: 'easy',
    title: 'Remove Key-Value Pair',
    text: 'Remove the entry with key "apple" using Remove()',
    setup: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    setupCode: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    expected: '{ banana: 2 }',
    sample: 'fruits.Remove("apple");',
    hints: ['Remove() returns true if key was found and removed', 'Use Remove(key, out value) to also get the removed value'],
    tags: ['dictionary', 'remove', 'collections'],
  },
  {
    id: 'csharp-dict-keys-1',
    category: 'Dictionary Methods',
    difficulty: 'easy',
    title: 'Get All Keys',
    text: 'Get all keys from the dictionary using the Keys property',
    setup: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    setupCode: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    expected: '{ "apple", "banana" }',
    sample: 'fruits.Keys',
    hints: ['Keys returns KeyCollection which implements IEnumerable<TKey>', 'Use .ToList() or .ToArray() if you need a concrete collection'],
    tags: ['dictionary', 'keys', 'collections'],
  },
  {
    id: 'csharp-dict-values-1',
    category: 'Dictionary Methods',
    difficulty: 'easy',
    title: 'Get All Values',
    text: 'Get all values from the dictionary using the Values property',
    setup: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    setupCode: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    expected: '{ 1, 2 }',
    sample: 'fruits.Values',
    hints: ['Values returns ValueCollection which implements IEnumerable<TValue>', 'Use .ToList() or .ToArray() if you need a concrete collection'],
    tags: ['dictionary', 'values', 'collections'],
  },
  {
    id: 'csharp-dict-getvalueordefault-1',
    category: 'Dictionary Methods',
    difficulty: 'medium',
    title: 'Get Value or Default',
    text: 'Get the value for "cherry" or 0 if not found using GetValueOrDefault()',
    setup: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    setupCode: 'Dictionary<string, int> fruits = new Dictionary<string, int> { ["apple"] = 1, ["banana"] = 2 };',
    expected: '0',
    sample: 'fruits.GetValueOrDefault("cherry")',
    hints: ['GetValueOrDefault() returns default(TValue) if key not found', 'Can also specify a custom default: GetValueOrDefault("cherry", -1)'],
    tags: ['dictionary', 'getvalueordefault', 'collections'],
  },

  // ============================================================
  // LINQ Methods
  // ============================================================
  {
    id: 'csharp-linq-where-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Filter with Where()',
    text: 'Filter the list to only include numbers greater than 5 using Where()',
    setup: 'List<int> numbers = new List<int> { 3, 7, 2, 9, 4, 8 };',
    setupCode: 'List<int> numbers = new List<int> { 3, 7, 2, 9, 4, 8 };',
    expected: '{ 7, 9, 8 }',
    sample: 'numbers.Where(x => x > 5)',
    hints: ['Where() filters elements based on a predicate', 'Remember to add .ToList() if you need a List<T>'],
    tags: ['linq', 'where', 'filter'],
  },
  {
    id: 'csharp-linq-select-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Transform with Select()',
    text: 'Double each number in the list using Select()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3, 4 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3, 4 };',
    expected: '{ 2, 4, 6, 8 }',
    sample: 'numbers.Select(x => x * 2)',
    hints: ['Select() transforms each element using the provided function'],
    tags: ['linq', 'select', 'projection'],
  },
  {
    id: 'csharp-linq-orderby-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Sort with OrderBy()',
    text: 'Sort the list in ascending order using OrderBy()',
    setup: 'List<int> numbers = new List<int> { 5, 2, 8, 1, 9 };',
    setupCode: 'List<int> numbers = new List<int> { 5, 2, 8, 1, 9 };',
    expected: '{ 1, 2, 5, 8, 9 }',
    sample: 'numbers.OrderBy(x => x)',
    hints: ['OrderBy() returns a new sorted sequence', 'The lambda specifies the sort key'],
    tags: ['linq', 'orderby', 'sorting'],
  },
  {
    id: 'csharp-linq-orderbydesc-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Sort Descending with OrderByDescending()',
    text: 'Sort the list in descending order using OrderByDescending()',
    setup: 'List<int> numbers = new List<int> { 5, 2, 8, 1, 9 };',
    setupCode: 'List<int> numbers = new List<int> { 5, 2, 8, 1, 9 };',
    expected: '{ 9, 8, 5, 2, 1 }',
    sample: 'numbers.OrderByDescending(x => x)',
    hints: ['OrderByDescending() sorts in descending order'],
    tags: ['linq', 'orderbydescending', 'sorting'],
  },
  {
    id: 'csharp-linq-first-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Get First Element with First()',
    text: 'Get the first element of the list using First()',
    setup: 'List<int> numbers = new List<int> { 10, 20, 30 };',
    setupCode: 'List<int> numbers = new List<int> { 10, 20, 30 };',
    expected: '10',
    sample: 'numbers.First()',
    hints: ['First() throws an exception if the sequence is empty', 'Use FirstOrDefault() for safe access'],
    tags: ['linq', 'first', 'element'],
  },
  {
    id: 'csharp-linq-firstordefault-1',
    category: 'LINQ Methods',
    difficulty: 'medium',
    title: 'Get First Element Safely',
    text: 'Get the first even number, or 0 if none exist, using FirstOrDefault()',
    setup: 'List<int> numbers = new List<int> { 1, 3, 5, 7 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 3, 5, 7 };',
    expected: '0',
    sample: 'numbers.FirstOrDefault(x => x % 2 == 0)',
    hints: ['FirstOrDefault() returns default(T) if no match is found', 'default(int) is 0'],
    tags: ['linq', 'firstordefault', 'element'],
  },
  {
    id: 'csharp-linq-any-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Check if Any Element Matches',
    text: 'Check if any number is greater than 10 using Any()',
    setup: 'List<int> numbers = new List<int> { 5, 8, 12, 3 };',
    setupCode: 'List<int> numbers = new List<int> { 5, 8, 12, 3 };',
    expected: 'true',
    sample: 'numbers.Any(x => x > 10)',
    hints: ['Any() with a predicate checks if at least one element matches', 'Any() without arguments checks if the sequence is non-empty'],
    tags: ['linq', 'any', 'predicate'],
  },
  {
    id: 'csharp-linq-all-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Check if All Elements Match',
    text: 'Check if all numbers are positive using All()',
    setup: 'List<int> numbers = new List<int> { 1, 5, 3, 8 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 5, 3, 8 };',
    expected: 'true',
    sample: 'numbers.All(x => x > 0)',
    hints: ['All() returns true if every element satisfies the predicate'],
    tags: ['linq', 'all', 'predicate'],
  },
  {
    id: 'csharp-linq-count-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Count Elements with LINQ',
    text: 'Count how many numbers are even using Count()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5, 6 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5, 6 };',
    expected: '3',
    sample: 'numbers.Count(x => x % 2 == 0)',
    hints: ['Count() with a predicate counts matching elements', 'Count() without arguments returns total count'],
    tags: ['linq', 'count', 'aggregate'],
  },
  {
    id: 'csharp-linq-sum-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Calculate Sum with Sum()',
    text: 'Calculate the sum of all numbers using Sum()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5 };',
    expected: '15',
    sample: 'numbers.Sum()',
    hints: ['Sum() adds all elements in the sequence'],
    tags: ['linq', 'sum', 'aggregate'],
  },
  {
    id: 'csharp-linq-average-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Calculate Average',
    text: 'Calculate the average of all numbers using Average()',
    setup: 'List<int> numbers = new List<int> { 2, 4, 6, 8, 10 };',
    setupCode: 'List<int> numbers = new List<int> { 2, 4, 6, 8, 10 };',
    expected: '6.0',
    sample: 'numbers.Average()',
    hints: ['Average() returns a double'],
    tags: ['linq', 'average', 'aggregate'],
  },
  {
    id: 'csharp-linq-max-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Find Maximum Value',
    text: 'Find the maximum value using Max()',
    setup: 'List<int> numbers = new List<int> { 3, 7, 2, 9, 4 };',
    setupCode: 'List<int> numbers = new List<int> { 3, 7, 2, 9, 4 };',
    expected: '9',
    sample: 'numbers.Max()',
    hints: ['Max() throws an exception if the sequence is empty'],
    tags: ['linq', 'max', 'aggregate'],
  },
  {
    id: 'csharp-linq-min-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Find Minimum Value',
    text: 'Find the minimum value using Min()',
    setup: 'List<int> numbers = new List<int> { 3, 7, 2, 9, 4 };',
    setupCode: 'List<int> numbers = new List<int> { 3, 7, 2, 9, 4 };',
    expected: '2',
    sample: 'numbers.Min()',
    hints: ['Min() throws an exception if the sequence is empty'],
    tags: ['linq', 'min', 'aggregate'],
  },
  {
    id: 'csharp-linq-distinct-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Remove Duplicates with Distinct()',
    text: 'Remove duplicate values using Distinct()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 2, 3, 3, 3, 4 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 2, 3, 3, 3, 4 };',
    expected: '{ 1, 2, 3, 4 }',
    sample: 'numbers.Distinct()',
    hints: ['Distinct() returns a sequence with unique elements'],
    tags: ['linq', 'distinct', 'set'],
  },
  {
    id: 'csharp-linq-take-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Take First N Elements',
    text: 'Get the first 3 elements using Take()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5, 6 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5, 6 };',
    expected: '{ 1, 2, 3 }',
    sample: 'numbers.Take(3)',
    hints: ['Take() returns the first n elements'],
    tags: ['linq', 'take', 'partition'],
  },
  {
    id: 'csharp-linq-skip-1',
    category: 'LINQ Methods',
    difficulty: 'easy',
    title: 'Skip First N Elements',
    text: 'Skip the first 2 elements using Skip()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5 };',
    expected: '{ 3, 4, 5 }',
    sample: 'numbers.Skip(2)',
    hints: ['Skip() bypasses the first n elements'],
    tags: ['linq', 'skip', 'partition'],
  },
  {
    id: 'csharp-linq-groupby-1',
    category: 'LINQ Methods',
    difficulty: 'medium',
    title: 'Group Elements with GroupBy()',
    text: 'Group numbers by whether they are even or odd using GroupBy()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5, 6 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3, 4, 5, 6 };',
    expected: 'IEnumerable<IGrouping<bool, int>> with Key=false: {1,3,5} and Key=true: {2,4,6}',
    sample: 'numbers.GroupBy(x => x % 2 == 0)',
    hints: ['GroupBy() returns IEnumerable<IGrouping<TKey, TElement>>', 'Access the key with group.Key and iterate elements with foreach', 'Consider using ToDictionary() or ToLookup() for direct key access'],
    tags: ['linq', 'groupby', 'grouping'],
  },
  {
    id: 'csharp-linq-aggregate-1',
    category: 'LINQ Methods',
    difficulty: 'medium',
    title: 'Custom Aggregation with Aggregate()',
    text: 'Calculate the product of all numbers using Aggregate()',
    setup: 'List<int> numbers = new List<int> { 1, 2, 3, 4 };',
    setupCode: 'List<int> numbers = new List<int> { 1, 2, 3, 4 };',
    expected: '24',
    sample: 'numbers.Aggregate((acc, x) => acc * x)',
    hints: ['Aggregate() applies a function cumulatively', 'The accumulator starts with the first element'],
    tags: ['linq', 'aggregate', 'reduce'],
  },
  {
    id: 'csharp-linq-aggregate-seed-1',
    category: 'LINQ Methods',
    difficulty: 'medium',
    title: 'Aggregate with Seed Value',
    text: 'Concatenate all names with a prefix of "Names:" using Aggregate()',
    setup: 'List<string> names = new List<string> { "Alice", "Bob", "Charlie" };',
    setupCode: 'List<string> names = new List<string> { "Alice", "Bob", "Charlie" };',
    expected: '"Names: Alice Bob Charlie"',
    sample: 'names.Aggregate("Names:", (acc, name) => acc + " " + name)',
    hints: ['Aggregate with a seed starts accumulation from that value', 'The seed becomes the initial accumulator value'],
    tags: ['linq', 'aggregate', 'reduce'],
  },

  // ============================================================
  // String Methods
  // ============================================================
  {
    id: 'csharp-string-length-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Get String Length',
    text: 'Get the length of the string using the Length property',
    setup: 'string text = "Hello, World!";',
    setupCode: 'string text = "Hello, World!";',
    expected: '13',
    sample: 'text.Length',
    hints: ['Length is a property, not a method'],
    tags: ['string', 'length'],
  },
  {
    id: 'csharp-string-substring-1',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Extract Substring',
    text: 'Extract "World" from the string using Substring()',
    setup: 'string text = "Hello, World!";',
    setupCode: 'string text = "Hello, World!";',
    expected: '"World"',
    sample: 'text.Substring(7, 5)',
    hints: ['Substring(startIndex, length) extracts a portion of the string'],
    tags: ['string', 'substring'],
  },
  {
    id: 'csharp-string-indexof-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Find Substring Position',
    text: 'Find the position of "World" in the string using IndexOf()',
    setup: 'string text = "Hello, World!";',
    setupCode: 'string text = "Hello, World!";',
    expected: '7',
    sample: 'text.IndexOf("World")',
    hints: ['IndexOf() returns -1 if the substring is not found'],
    tags: ['string', 'indexof'],
  },
  {
    id: 'csharp-string-contains-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Check if String Contains Substring',
    text: 'Check if the string contains "World" using Contains()',
    setup: 'string text = "Hello, World!";',
    setupCode: 'string text = "Hello, World!";',
    expected: 'true',
    sample: 'text.Contains("World")',
    hints: ['Contains() is case-sensitive by default'],
    tags: ['string', 'contains'],
  },
  {
    id: 'csharp-string-split-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Split String into Array',
    text: 'Split the string by commas using Split()',
    setup: 'string text = "apple,banana,cherry";',
    setupCode: 'string text = "apple,banana,cherry";',
    expected: '["apple", "banana", "cherry"]',
    sample: 'text.Split(\',\')',
    hints: ['Split() returns a string array', 'Use char literals with single quotes'],
    tags: ['string', 'split'],
  },
  {
    id: 'csharp-string-join-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Join Array into String',
    text: 'Join the array elements with " - " separator using String.Join()',
    setup: 'string[] fruits = { "apple", "banana", "cherry" };',
    setupCode: 'string[] fruits = { "apple", "banana", "cherry" };',
    expected: '"apple - banana - cherry"',
    sample: 'string.Join(" - ", fruits)',
    hints: ['String.Join() is a static method'],
    tags: ['string', 'join'],
  },
  {
    id: 'csharp-string-toupper-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Convert to Uppercase',
    text: 'Convert the string to uppercase using ToUpper()',
    setup: 'string text = "Hello, World!";',
    setupCode: 'string text = "Hello, World!";',
    expected: '"HELLO, WORLD!"',
    sample: 'text.ToUpper()',
    hints: ['ToUpper() returns a new string; strings are immutable'],
    tags: ['string', 'toupper', 'case'],
  },
  {
    id: 'csharp-string-tolower-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Convert to Lowercase',
    text: 'Convert the string to lowercase using ToLower()',
    setup: 'string text = "Hello, World!";',
    setupCode: 'string text = "Hello, World!";',
    expected: '"hello, world!"',
    sample: 'text.ToLower()',
    hints: ['ToLower() returns a new string; strings are immutable'],
    tags: ['string', 'tolower', 'case'],
  },
  {
    id: 'csharp-string-trim-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Trim Whitespace',
    text: 'Remove leading and trailing whitespace using Trim()',
    setup: 'string text = "  Hello, World!  ";',
    setupCode: 'string text = "  Hello, World!  ";',
    expected: '"Hello, World!"',
    sample: 'text.Trim()',
    hints: ['Trim() removes whitespace from both ends', 'Use TrimStart() or TrimEnd() for one side only'],
    tags: ['string', 'trim'],
  },
  {
    id: 'csharp-string-replace-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Replace Substring',
    text: 'Replace "World" with "C#" using Replace()',
    setup: 'string text = "Hello, World!";',
    setupCode: 'string text = "Hello, World!";',
    expected: '"Hello, C#!"',
    sample: 'text.Replace("World", "C#")',
    hints: ['Replace() replaces all occurrences'],
    tags: ['string', 'replace'],
  },
  {
    id: 'csharp-string-startswith-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Check if String Starts With',
    text: 'Check if the string starts with "Hello" using StartsWith()',
    setup: 'string text = "Hello, World!";',
    setupCode: 'string text = "Hello, World!";',
    expected: 'true',
    sample: 'text.StartsWith("Hello")',
    hints: ['StartsWith() is case-sensitive by default'],
    tags: ['string', 'startswith'],
  },
  {
    id: 'csharp-string-endswith-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Check if String Ends With',
    text: 'Check if the string ends with "!" using EndsWith()',
    setup: 'string text = "Hello, World!";',
    setupCode: 'string text = "Hello, World!";',
    expected: 'true',
    sample: 'text.EndsWith("!")',
    hints: ['EndsWith() is case-sensitive by default'],
    tags: ['string', 'endswith'],
  },

  // ============================================================
  // Array Methods
  // ============================================================
  {
    id: 'csharp-array-sort-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Sort Array with Array.Sort()',
    text: 'Sort the array in ascending order using Array.Sort()',
    setup: 'int[] numbers = { 5, 2, 8, 1, 9 };',
    setupCode: 'int[] numbers = { 5, 2, 8, 1, 9 };',
    expected: '{ 1, 2, 5, 8, 9 }',
    sample: 'Array.Sort(numbers);',
    hints: ['Array.Sort() modifies the array in-place'],
    tags: ['array', 'sort'],
  },
  {
    id: 'csharp-array-reverse-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Reverse Array with Array.Reverse()',
    text: 'Reverse the order of elements using Array.Reverse()',
    setup: 'int[] numbers = { 1, 2, 3, 4, 5 };',
    setupCode: 'int[] numbers = { 1, 2, 3, 4, 5 };',
    expected: '{ 5, 4, 3, 2, 1 }',
    sample: 'Array.Reverse(numbers);',
    hints: ['Array.Reverse() modifies the array in-place'],
    tags: ['array', 'reverse'],
  },
  {
    id: 'csharp-array-indexof-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Find Index in Array',
    text: 'Find the index of the value 30 using Array.IndexOf()',
    setup: 'int[] numbers = { 10, 20, 30, 40, 50 };',
    setupCode: 'int[] numbers = { 10, 20, 30, 40, 50 };',
    expected: '2',
    sample: 'Array.IndexOf(numbers, 30)',
    hints: ['Array.IndexOf() returns -1 if the element is not found'],
    tags: ['array', 'indexof'],
  },
  {
    id: 'csharp-array-exists-1',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Check if Element Exists with Array.Exists()',
    text: 'Check if any element is greater than 40 using Array.Exists()',
    setup: 'int[] numbers = { 10, 20, 30, 45, 50 };',
    setupCode: 'int[] numbers = { 10, 20, 30, 45, 50 };',
    expected: 'true',
    sample: 'Array.Exists(numbers, x => x > 40)',
    hints: ['Array.Exists() takes a Predicate<T>'],
    tags: ['array', 'exists', 'predicate'],
  },
  {
    id: 'csharp-array-find-1',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Find Element with Array.Find()',
    text: 'Find the first element greater than 25 using Array.Find()',
    setup: 'int[] numbers = { 10, 20, 30, 40, 50 };',
    setupCode: 'int[] numbers = { 10, 20, 30, 40, 50 };',
    expected: '30',
    sample: 'Array.Find(numbers, x => x > 25)',
    hints: ['Array.Find() returns default(T) if no match is found'],
    tags: ['array', 'find', 'predicate'],
  },
  {
    id: 'csharp-array-findall-1',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Find All Matching Elements',
    text: 'Find all elements greater than 25 using Array.FindAll()',
    setup: 'int[] numbers = { 10, 20, 30, 40, 50 };',
    setupCode: 'int[] numbers = { 10, 20, 30, 40, 50 };',
    expected: '{ 30, 40, 50 }',
    sample: 'Array.FindAll(numbers, x => x > 25)',
    hints: ['Array.FindAll() returns an array of all matching elements'],
    tags: ['array', 'findall', 'predicate'],
  },
  {
    id: 'csharp-array-copy-1',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Copy Array Elements',
    text: 'Copy the first 3 elements to a new array using Array.Copy()',
    setup: 'int[] source = { 1, 2, 3, 4, 5 };\nint[] dest = new int[3];',
    setupCode: 'int[] source = { 1, 2, 3, 4, 5 };\nint[] dest = new int[3];',
    expected: 'dest = { 1, 2, 3 }',
    sample: 'Array.Copy(source, dest, 3);',
    hints: ['Array.Copy() copies elements from source to destination'],
    tags: ['array', 'copy'],
  },
  {
    id: 'csharp-array-resize-1',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Resize Array',
    text: 'Resize the array to hold 5 elements using Array.Resize()',
    setup: 'int[] numbers = { 1, 2, 3 };',
    setupCode: 'int[] numbers = { 1, 2, 3 };',
    expected: '{ 1, 2, 3, 0, 0 }',
    sample: 'Array.Resize(ref numbers, 5);',
    hints: ['Array.Resize() requires ref keyword', 'New elements are initialized to default(T)'],
    tags: ['array', 'resize'],
  },
];

export default csharpProblems;
