import type { Problem } from '../types';

export const javascriptProblems: Problem[] = [
  // ========================================
  // ARRAY METHODS - filter
  // ========================================
  {
    id: 'js-filter-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Filter Even Numbers',
    text: 'Use the filter method to get only even numbers from the array.',
    setup: 'const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];',
    setupCode: 'const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];',
    expected: [2, 4, 6, 8, 10],
    sample: 'numbers.filter(n => n % 2 === 0)',
    hints: ['Use the modulo operator %', 'Even numbers have remainder 0 when divided by 2'],
    validPatterns: [
      /\.filter\s*\(\s*\w*\s*=>\s*\w*\s*%\s*2\s*(===?|!==?)\s*0\s*\)/,
      /\.filter\s*\(\s*function\s*\(\s*\w+\s*\)\s*\{\s*return\s+\w+\s*%\s*2\s*(===?|!==?)\s*0/,
    ],
    tags: ['filter', 'modulo', 'basics'],
  },
  {
    id: 'js-filter-002',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Filter Strings by Length',
    text: 'Filter the array to get only strings with more than 4 characters.',
    setup: 'const words = ["cat", "elephant", "dog", "hippopotamus", "ant", "tiger"];',
    setupCode: 'const words = ["cat", "elephant", "dog", "hippopotamus", "ant", "tiger"];',
    expected: ['elephant', 'hippopotamus', 'tiger'],
    sample: 'words.filter(w => w.length > 4)',
    hints: ['Use the .length property', 'Compare length to 4'],
    validPatterns: [
      /\.filter\s*\(\s*\w+\s*=>\s*\w+\.length\s*>\s*4\s*\)/,
      /\.filter\s*\(\s*\(\s*\w+\s*\)\s*=>\s*\w+\.length\s*>\s*4\s*\)/,
    ],
    tags: ['filter', 'length', 'strings'],
  },
  {
    id: 'js-filter-003',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Filter Objects by Property',
    text: 'Filter the users array to get only users who are active.',
    setup: `const users = [
  { name: "Alice", active: true },
  { name: "Bob", active: false },
  { name: "Charlie", active: true },
  { name: "Diana", active: false }
];`,
    setupCode: `const users = [
  { name: "Alice", active: true },
  { name: "Bob", active: false },
  { name: "Charlie", active: true },
  { name: "Diana", active: false }
];`,
    expected: [
      { name: 'Alice', active: true },
      { name: 'Charlie', active: true },
    ],
    sample: 'users.filter(u => u.active)',
    hints: ['Access the active property', 'Boolean values work directly in conditions'],
    validPatterns: [
      /\.filter\s*\(\s*\w+\s*=>\s*\w+\.active\s*\)/,
      /\.filter\s*\(\s*\w+\s*=>\s*\w+\.active\s*(===?)\s*true\s*\)/,
      /\.filter\s*\(\s*\{\s*active\s*\}\s*=>\s*active\s*\)/,
    ],
    tags: ['filter', 'objects', 'property-access'],
  },
  {
    id: 'js-filter-004',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Filter Unique Values',
    text: 'Use filter with indexOf to get unique values from the array.',
    setup: 'const numbers = [1, 2, 2, 3, 4, 4, 5, 1, 3];',
    setupCode: 'const numbers = [1, 2, 2, 3, 4, 4, 5, 1, 3];',
    expected: [1, 2, 3, 4, 5],
    sample: 'numbers.filter((n, i) => numbers.indexOf(n) === i)',
    hints: ['indexOf returns the first occurrence index', 'Compare current index with first occurrence'],
    validPatterns: [
      /\.filter\s*\(\s*\(\s*\w+\s*,\s*\w+\s*\)\s*=>\s*\w+\.indexOf\s*\(\s*\w+\s*\)\s*===?\s*\w+\s*\)/,
    ],
    tags: ['filter', 'indexOf', 'unique'],
  },
  {
    id: 'js-filter-005',
    category: 'Array Methods',
    difficulty: 'hard',
    title: 'Filter with Multiple Conditions',
    text: 'Filter products that are in stock AND cost less than $50.',
    setup: `const products = [
  { name: "Laptop", price: 999, inStock: true },
  { name: "Mouse", price: 29, inStock: true },
  { name: "Keyboard", price: 49, inStock: false },
  { name: "Monitor", price: 299, inStock: true },
  { name: "USB Cable", price: 9, inStock: true }
];`,
    setupCode: `const products = [
  { name: "Laptop", price: 999, inStock: true },
  { name: "Mouse", price: 29, inStock: true },
  { name: "Keyboard", price: 49, inStock: false },
  { name: "Monitor", price: 299, inStock: true },
  { name: "USB Cable", price: 9, inStock: true }
];`,
    expected: [
      { name: 'Mouse', price: 29, inStock: true },
      { name: 'USB Cable', price: 9, inStock: true },
    ],
    sample: 'products.filter(p => p.inStock && p.price < 50)',
    hints: ['Use && for multiple conditions', 'Check both inStock and price'],
    validPatterns: [
      /\.filter\s*\(\s*\w+\s*=>\s*\w+\.inStock\s*&&\s*\w+\.price\s*<\s*50\s*\)/,
      /\.filter\s*\(\s*\w+\s*=>\s*\w+\.price\s*<\s*50\s*&&\s*\w+\.inStock\s*\)/,
    ],
    tags: ['filter', 'objects', 'conditions'],
  },

  // ========================================
  // ARRAY METHODS - map
  // ========================================
  {
    id: 'js-map-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Double All Numbers',
    text: 'Use map to double every number in the array.',
    setup: 'const numbers = [1, 2, 3, 4, 5];',
    setupCode: 'const numbers = [1, 2, 3, 4, 5];',
    expected: [2, 4, 6, 8, 10],
    sample: 'numbers.map(n => n * 2)',
    hints: ['Multiply each element by 2', 'map returns a new array'],
    validPatterns: [
      /\.map\s*\(\s*\w+\s*=>\s*\w+\s*\*\s*2\s*\)/,
      /\.map\s*\(\s*\(\s*\w+\s*\)\s*=>\s*\w+\s*\*\s*2\s*\)/,
    ],
    tags: ['map', 'arithmetic', 'basics'],
  },
  {
    id: 'js-map-002',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Extract Property Values',
    text: 'Use map to get an array of just the names from the users array.',
    setup: `const users = [
  { name: "Alice", age: 25 },
  { name: "Bob", age: 30 },
  { name: "Charlie", age: 35 }
];`,
    setupCode: `const users = [
  { name: "Alice", age: 25 },
  { name: "Bob", age: 30 },
  { name: "Charlie", age: 35 }
];`,
    expected: ['Alice', 'Bob', 'Charlie'],
    sample: 'users.map(u => u.name)',
    hints: ['Access the name property', 'map transforms each element'],
    validPatterns: [
      /\.map\s*\(\s*\w+\s*=>\s*\w+\.name\s*\)/,
      /\.map\s*\(\s*\{\s*name\s*\}\s*=>\s*name\s*\)/,
    ],
    tags: ['map', 'objects', 'property-access'],
  },
  {
    id: 'js-map-003',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Transform to New Object Shape',
    text: 'Transform each user into an object with fullName and isAdult properties.',
    setup: `const users = [
  { firstName: "John", lastName: "Doe", age: 17 },
  { firstName: "Jane", lastName: "Smith", age: 25 },
  { firstName: "Bob", lastName: "Brown", age: 16 }
];`,
    setupCode: `const users = [
  { firstName: "John", lastName: "Doe", age: 17 },
  { firstName: "Jane", lastName: "Smith", age: 25 },
  { firstName: "Bob", lastName: "Brown", age: 16 }
];`,
    expected: [
      { fullName: 'John Doe', isAdult: false },
      { fullName: 'Jane Smith', isAdult: true },
      { fullName: 'Bob Brown', isAdult: false },
    ],
    sample: 'users.map(u => ({ fullName: `${u.firstName} ${u.lastName}`, isAdult: u.age >= 18 }))',
    hints: ['Create a new object in map', 'Concatenate firstName and lastName', 'Check if age >= 18'],
    validPatterns: [
      /\.map\s*\(\s*\w+\s*=>\s*\(\s*\{/,
    ],
    tags: ['map', 'objects', 'transformation'],
  },
  {
    id: 'js-map-004',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Convert to Uppercase',
    text: 'Use map to convert all strings to uppercase.',
    setup: 'const words = ["hello", "world", "javascript"];',
    setupCode: 'const words = ["hello", "world", "javascript"];',
    expected: ['HELLO', 'WORLD', 'JAVASCRIPT'],
    sample: 'words.map(w => w.toUpperCase())',
    hints: ['Use the toUpperCase() method', 'map returns a new array'],
    validPatterns: [
      /\.map\s*\(\s*\w+\s*=>\s*\w+\.toUpperCase\s*\(\s*\)\s*\)/,
    ],
    tags: ['map', 'strings', 'toUpperCase'],
  },
  {
    id: 'js-map-005',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Map with Index',
    text: 'Create an array of objects with value and index properties.',
    setup: 'const letters = ["a", "b", "c", "d"];',
    setupCode: 'const letters = ["a", "b", "c", "d"];',
    expected: [
      { value: 'a', index: 0 },
      { value: 'b', index: 1 },
      { value: 'c', index: 2 },
      { value: 'd', index: 3 },
    ],
    sample: 'letters.map((value, index) => ({ value, index }))',
    hints: ['map callback receives index as second argument', 'Use shorthand property syntax'],
    validPatterns: [
      /\.map\s*\(\s*\(\s*\w+\s*,\s*\w+\s*\)\s*=>/,
    ],
    tags: ['map', 'index', 'objects'],
  },

  // ========================================
  // ARRAY METHODS - reduce
  // ========================================
  {
    id: 'js-reduce-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Sum All Numbers',
    text: 'Use reduce to calculate the sum of all numbers.',
    setup: 'const numbers = [1, 2, 3, 4, 5];',
    setupCode: 'const numbers = [1, 2, 3, 4, 5];',
    expected: 15,
    sample: 'numbers.reduce((sum, n) => sum + n, 0)',
    hints: ['Start with initial value 0', 'Add each number to the accumulator'],
    validPatterns: [
      /\.reduce\s*\(\s*\(\s*\w+\s*,\s*\w+\s*\)\s*=>\s*\w+\s*\+\s*\w+\s*,\s*0\s*\)/,
    ],
    tags: ['reduce', 'sum', 'basics'],
  },
  {
    id: 'js-reduce-002',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Find Maximum Value',
    text: 'Use reduce to find the maximum value in the array.',
    setup: 'const numbers = [5, 2, 9, 1, 7, 3];',
    setupCode: 'const numbers = [5, 2, 9, 1, 7, 3];',
    expected: 9,
    sample: 'numbers.reduce((max, n) => n > max ? n : max, numbers[0])',
    hints: ['Compare each number to the current max', 'Use ternary operator or Math.max'],
    validPatterns: [
      /\.reduce\s*\(\s*\(\s*\w+\s*,\s*\w+\s*\)\s*=>/,
      /Math\.max\s*\(\s*\.\.\.\w+\s*\)/,
    ],
    tags: ['reduce', 'max', 'comparison'],
  },
  {
    id: 'js-reduce-003',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Count Occurrences',
    text: 'Use reduce to count how many times each fruit appears.',
    setup: 'const fruits = ["apple", "banana", "apple", "orange", "banana", "apple"];',
    setupCode: 'const fruits = ["apple", "banana", "apple", "orange", "banana", "apple"];',
    expected: { apple: 3, banana: 2, orange: 1 },
    sample: 'fruits.reduce((acc, fruit) => ({ ...acc, [fruit]: (acc[fruit] || 0) + 1 }), {})',
    hints: ['Start with an empty object', 'Use computed property names [fruit]', 'Initialize count to 0 if undefined'],
    validPatterns: [
      /\.reduce\s*\(\s*\(\s*\w+\s*,\s*\w+\s*\)\s*=>/,
    ],
    tags: ['reduce', 'counting', 'objects'],
  },
  {
    id: 'js-reduce-004',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Flatten Nested Arrays',
    text: 'Use reduce to flatten the nested array one level deep.',
    setup: 'const nested = [[1, 2], [3, 4], [5, 6]];',
    setupCode: 'const nested = [[1, 2], [3, 4], [5, 6]];',
    expected: [1, 2, 3, 4, 5, 6],
    sample: 'nested.reduce((flat, arr) => [...flat, ...arr], [])',
    hints: ['Spread each inner array', 'Start with empty array'],
    validPatterns: [
      /\.reduce\s*\(\s*\(\s*\w+\s*,\s*\w+\s*\)\s*=>\s*\[\s*\.\.\.\w+\s*,\s*\.\.\.\w+\s*\]/,
      /\.reduce\s*\(\s*\(\s*\w+\s*,\s*\w+\s*\)\s*=>\s*\w+\.concat\s*\(\s*\w+\s*\)/,
      /\.flat\s*\(\s*\)/,
    ],
    tags: ['reduce', 'flatten', 'spread'],
  },
  {
    id: 'js-reduce-005',
    category: 'Array Methods',
    difficulty: 'hard',
    title: 'Group By Property',
    text: 'Use reduce to group users by their department.',
    setup: `const employees = [
  { name: "Alice", department: "Engineering" },
  { name: "Bob", department: "Marketing" },
  { name: "Charlie", department: "Engineering" },
  { name: "Diana", department: "Marketing" },
  { name: "Eve", department: "Sales" }
];`,
    setupCode: `const employees = [
  { name: "Alice", department: "Engineering" },
  { name: "Bob", department: "Marketing" },
  { name: "Charlie", department: "Engineering" },
  { name: "Diana", department: "Marketing" },
  { name: "Eve", department: "Sales" }
];`,
    expected: {
      Engineering: [
        { name: 'Alice', department: 'Engineering' },
        { name: 'Charlie', department: 'Engineering' },
      ],
      Marketing: [
        { name: 'Bob', department: 'Marketing' },
        { name: 'Diana', department: 'Marketing' },
      ],
      Sales: [{ name: 'Eve', department: 'Sales' }],
    },
    sample: `employees.reduce((groups, emp) => {
  const key = emp.department;
  groups[key] = groups[key] || [];
  groups[key].push(emp);
  return groups;
}, {})`,
    hints: ['Use department as the key', 'Initialize empty array for new departments', 'Push employee to appropriate group'],
    validPatterns: [
      /\.reduce\s*\(\s*\(\s*\w+\s*,\s*\w+\s*\)\s*=>/,
    ],
    tags: ['reduce', 'groupBy', 'objects'],
  },

  // ========================================
  // ARRAY METHODS - find and findIndex
  // ========================================
  {
    id: 'js-find-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Find First Even Number',
    text: 'Use find to get the first even number in the array.',
    setup: 'const numbers = [1, 3, 5, 8, 9, 10];',
    setupCode: 'const numbers = [1, 3, 5, 8, 9, 10];',
    expected: 8,
    sample: 'numbers.find(n => n % 2 === 0)',
    hints: ['find returns the first matching element', 'Use modulo to check for even'],
    validPatterns: [
      /\.find\s*\(\s*\w+\s*=>\s*\w+\s*%\s*2\s*===?\s*0\s*\)/,
    ],
    tags: ['find', 'modulo', 'basics'],
  },
  {
    id: 'js-find-002',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Find User by ID',
    text: 'Use find to get the user with id 3.',
    setup: `const users = [
  { id: 1, name: "Alice" },
  { id: 2, name: "Bob" },
  { id: 3, name: "Charlie" },
  { id: 4, name: "Diana" }
];`,
    setupCode: `const users = [
  { id: 1, name: "Alice" },
  { id: 2, name: "Bob" },
  { id: 3, name: "Charlie" },
  { id: 4, name: "Diana" }
];`,
    expected: { id: 3, name: 'Charlie' },
    sample: 'users.find(u => u.id === 3)',
    hints: ['Compare id property to 3', 'find returns the matching object'],
    validPatterns: [
      /\.find\s*\(\s*\w+\s*=>\s*\w+\.id\s*===?\s*3\s*\)/,
    ],
    tags: ['find', 'objects', 'property-access'],
  },
  {
    id: 'js-findIndex-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Find Index of First Negative',
    text: 'Use findIndex to get the index of the first negative number.',
    setup: 'const numbers = [5, 3, -2, 8, -6, 1];',
    setupCode: 'const numbers = [5, 3, -2, 8, -6, 1];',
    expected: 2,
    sample: 'numbers.findIndex(n => n < 0)',
    hints: ['findIndex returns the index, not the element', 'Negative numbers are less than 0'],
    validPatterns: [
      /\.findIndex\s*\(\s*\w+\s*=>\s*\w+\s*<\s*0\s*\)/,
    ],
    tags: ['findIndex', 'comparison', 'basics'],
  },

  // ========================================
  // ARRAY METHODS - some and every
  // ========================================
  {
    id: 'js-some-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Check for Any Negative',
    text: 'Use some to check if any number is negative.',
    setup: 'const numbers = [1, 5, -3, 8, 2];',
    setupCode: 'const numbers = [1, 5, -3, 8, 2];',
    expected: true,
    sample: 'numbers.some(n => n < 0)',
    hints: ['some returns true if at least one element matches', 'Negative numbers are less than 0'],
    validPatterns: [
      /\.some\s*\(\s*\w+\s*=>\s*\w+\s*<\s*0\s*\)/,
    ],
    tags: ['some', 'comparison', 'basics'],
  },
  {
    id: 'js-some-002',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Check for Admin User',
    text: 'Use some to check if any user is an admin.',
    setup: `const users = [
  { name: "Alice", role: "user" },
  { name: "Bob", role: "admin" },
  { name: "Charlie", role: "user" }
];`,
    setupCode: `const users = [
  { name: "Alice", role: "user" },
  { name: "Bob", role: "admin" },
  { name: "Charlie", role: "user" }
];`,
    expected: true,
    sample: 'users.some(u => u.role === "admin")',
    hints: ['Check the role property', 'Compare to "admin"'],
    validPatterns: [
      /\.some\s*\(\s*\w+\s*=>\s*\w+\.role\s*===?\s*['"]admin['"]\s*\)/,
    ],
    tags: ['some', 'objects', 'property-access'],
  },
  {
    id: 'js-every-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Check All Positive',
    text: 'Use every to check if all numbers are positive.',
    setup: 'const numbers = [1, 5, 3, 8, 2];',
    setupCode: 'const numbers = [1, 5, 3, 8, 2];',
    expected: true,
    sample: 'numbers.every(n => n > 0)',
    hints: ['every returns true if ALL elements match', 'Positive numbers are greater than 0'],
    validPatterns: [
      /\.every\s*\(\s*\w+\s*=>\s*\w+\s*>\s*0\s*\)/,
    ],
    tags: ['every', 'comparison', 'basics'],
  },
  {
    id: 'js-every-002',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Check All Valid Emails',
    text: 'Use every to check if all strings contain "@".',
    setup: 'const emails = ["alice@test.com", "bob@example.org", "charlie@demo.net"];',
    setupCode: 'const emails = ["alice@test.com", "bob@example.org", "charlie@demo.net"];',
    expected: true,
    sample: 'emails.every(e => e.includes("@"))',
    hints: ['Use the includes method', 'Check for @ symbol'],
    validPatterns: [
      /\.every\s*\(\s*\w+\s*=>\s*\w+\.includes\s*\(\s*['"]@['"]\s*\)\s*\)/,
    ],
    tags: ['every', 'includes', 'strings'],
  },

  // ========================================
  // ARRAY METHODS - sort
  // ========================================
  {
    id: 'js-sort-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Sort Numbers Ascending',
    text: 'Sort the numbers in ascending order.',
    setup: 'const numbers = [5, 2, 8, 1, 9, 3];',
    setupCode: 'const numbers = [5, 2, 8, 1, 9, 3];',
    expected: [1, 2, 3, 5, 8, 9],
    sample: 'numbers.sort((a, b) => a - b)',
    hints: ['Default sort converts to strings', 'Use comparison function for numbers'],
    validPatterns: [
      /\.sort\s*\(\s*\(\s*\w+\s*,\s*\w+\s*\)\s*=>\s*\w+\s*-\s*\w+\s*\)/,
    ],
    tags: ['sort', 'numbers', 'comparison'],
  },
  {
    id: 'js-sort-002',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Sort Numbers Descending',
    text: 'Sort the numbers in descending order.',
    setup: 'const numbers = [5, 2, 8, 1, 9, 3];',
    setupCode: 'const numbers = [5, 2, 8, 1, 9, 3];',
    expected: [9, 8, 5, 3, 2, 1],
    sample: 'numbers.sort((a, b) => b - a)',
    hints: ['Reverse the subtraction order', 'b - a gives descending'],
    validPatterns: [
      /\.sort\s*\(\s*\(\s*\w+\s*,\s*\w+\s*\)\s*=>\s*\w+\s*-\s*\w+\s*\)/,
    ],
    tags: ['sort', 'numbers', 'descending'],
  },
  {
    id: 'js-sort-003',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Sort by Object Property',
    text: 'Sort the users by age in ascending order.',
    setup: `const users = [
  { name: "Alice", age: 30 },
  { name: "Bob", age: 25 },
  { name: "Charlie", age: 35 }
];`,
    setupCode: `const users = [
  { name: "Alice", age: 30 },
  { name: "Bob", age: 25 },
  { name: "Charlie", age: 35 }
];`,
    expected: [
      { name: 'Bob', age: 25 },
      { name: 'Alice', age: 30 },
      { name: 'Charlie', age: 35 },
    ],
    sample: 'users.sort((a, b) => a.age - b.age)',
    hints: ['Access the age property', 'Subtract ages for comparison'],
    validPatterns: [
      /\.sort\s*\(\s*\(\s*\w+\s*,\s*\w+\s*\)\s*=>\s*\w+\.age\s*-\s*\w+\.age\s*\)/,
    ],
    tags: ['sort', 'objects', 'property-access'],
  },
  {
    id: 'js-sort-004',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Sort Strings Alphabetically',
    text: 'Sort the words alphabetically (case-insensitive).',
    setup: 'const words = ["Banana", "apple", "Cherry", "date"];',
    setupCode: 'const words = ["Banana", "apple", "Cherry", "date"];',
    expected: ['apple', 'Banana', 'Cherry', 'date'],
    sample: 'words.sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))',
    hints: ['Convert to lowercase for comparison', 'Use localeCompare for strings'],
    validPatterns: [
      /\.sort\s*\(\s*\(\s*\w+\s*,\s*\w+\s*\)\s*=>\s*\w+\.toLowerCase\s*\(\s*\)\.localeCompare/,
    ],
    tags: ['sort', 'strings', 'localeCompare'],
  },

  // ========================================
  // ARRAY METHODS - slice and splice
  // ========================================
  {
    id: 'js-slice-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Get First Three Elements',
    text: 'Use slice to get the first 3 elements.',
    setup: 'const numbers = [1, 2, 3, 4, 5, 6, 7];',
    setupCode: 'const numbers = [1, 2, 3, 4, 5, 6, 7];',
    expected: [1, 2, 3],
    sample: 'numbers.slice(0, 3)',
    hints: ['slice(start, end) - end is exclusive', 'Start at 0, end at 3'],
    validPatterns: [
      /\.slice\s*\(\s*0\s*,\s*3\s*\)/,
    ],
    tags: ['slice', 'basics'],
  },
  {
    id: 'js-slice-002',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Get Last Two Elements',
    text: 'Use slice to get the last 2 elements.',
    setup: 'const numbers = [1, 2, 3, 4, 5];',
    setupCode: 'const numbers = [1, 2, 3, 4, 5];',
    expected: [4, 5],
    sample: 'numbers.slice(-2)',
    hints: ['Negative index counts from end', '-2 means last 2 elements'],
    validPatterns: [
      /\.slice\s*\(\s*-2\s*\)/,
    ],
    tags: ['slice', 'negative-index'],
  },
  {
    id: 'js-slice-003',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Get Middle Elements',
    text: 'Use slice to get elements from index 2 to 4 (inclusive).',
    setup: 'const letters = ["a", "b", "c", "d", "e", "f"];',
    setupCode: 'const letters = ["a", "b", "c", "d", "e", "f"];',
    expected: ['c', 'd', 'e'],
    sample: 'letters.slice(2, 5)',
    hints: ['slice end is exclusive', 'To include index 4, use 5 as end'],
    validPatterns: [
      /\.slice\s*\(\s*2\s*,\s*5\s*\)/,
    ],
    tags: ['slice', 'range'],
  },

  // ========================================
  // ARRAY METHODS - includes, indexOf
  // ========================================
  {
    id: 'js-includes-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Check Array Contains Value',
    text: 'Check if the array includes the number 5.',
    setup: 'const numbers = [1, 2, 3, 4, 5, 6];',
    setupCode: 'const numbers = [1, 2, 3, 4, 5, 6];',
    expected: true,
    sample: 'numbers.includes(5)',
    hints: ['includes returns true/false', 'Direct method call'],
    validPatterns: [
      /\.includes\s*\(\s*5\s*\)/,
    ],
    tags: ['includes', 'search', 'basics'],
  },
  {
    id: 'js-indexOf-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Find Index of Element',
    text: 'Find the index of "orange" in the array.',
    setup: 'const fruits = ["apple", "banana", "orange", "grape"];',
    setupCode: 'const fruits = ["apple", "banana", "orange", "grape"];',
    expected: 2,
    sample: 'fruits.indexOf("orange")',
    hints: ['indexOf returns the index', 'Returns -1 if not found'],
    validPatterns: [
      /\.indexOf\s*\(\s*['"]orange['"]\s*\)/,
    ],
    tags: ['indexOf', 'search'],
  },

  // ========================================
  // ARRAY METHODS - concat, join, reverse
  // ========================================
  {
    id: 'js-concat-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Combine Two Arrays',
    text: 'Use concat to combine both arrays.',
    setup: `const arr1 = [1, 2, 3];
const arr2 = [4, 5, 6];`,
    setupCode: `const arr1 = [1, 2, 3];
const arr2 = [4, 5, 6];`,
    expected: [1, 2, 3, 4, 5, 6],
    sample: 'arr1.concat(arr2)',
    hints: ['concat returns a new array', 'Does not modify original'],
    validPatterns: [
      /arr1\.concat\s*\(\s*arr2\s*\)/,
      /\[\s*\.\.\.arr1\s*,\s*\.\.\.arr2\s*\]/,
    ],
    tags: ['concat', 'combine', 'basics'],
  },
  {
    id: 'js-join-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Join with Separator',
    text: 'Use join to create a string separated by " - ".',
    setup: 'const words = ["Hello", "World", "JavaScript"];',
    setupCode: 'const words = ["Hello", "World", "JavaScript"];',
    expected: 'Hello - World - JavaScript',
    sample: 'words.join(" - ")',
    hints: ['join takes a separator string', 'Returns a string'],
    validPatterns: [
      /\.join\s*\(\s*['"]\s*-\s*['"]\s*\)/,
    ],
    tags: ['join', 'strings'],
  },
  {
    id: 'js-reverse-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Reverse Array',
    text: 'Reverse the array without modifying the original (use slice first).',
    setup: 'const numbers = [1, 2, 3, 4, 5];',
    setupCode: 'const numbers = [1, 2, 3, 4, 5];',
    expected: [5, 4, 3, 2, 1],
    sample: 'numbers.slice().reverse()',
    hints: ['reverse modifies the original', 'Use slice() to copy first'],
    validPatterns: [
      /\.slice\s*\(\s*\)\.reverse\s*\(\s*\)/,
      /\[\s*\.\.\.numbers\s*\]\.reverse\s*\(\s*\)/,
    ],
    tags: ['reverse', 'slice', 'immutable'],
  },

  // ========================================
  // ARRAY METHODS - flat, flatMap
  // ========================================
  {
    id: 'js-flat-001',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Flatten Nested Array',
    text: 'Use flat to flatten the nested array.',
    setup: 'const nested = [1, [2, 3], [4, [5, 6]]];',
    setupCode: 'const nested = [1, [2, 3], [4, [5, 6]]];',
    expected: [1, 2, 3, 4, [5, 6]],
    sample: 'nested.flat()',
    hints: ['flat() flattens one level by default', 'Returns new array'],
    validPatterns: [
      /\.flat\s*\(\s*\)/,
      /\.flat\s*\(\s*1\s*\)/,
    ],
    tags: ['flat', 'nested'],
  },
  {
    id: 'js-flat-002',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Flatten All Levels',
    text: 'Use flat to completely flatten the deeply nested array.',
    setup: 'const deep = [1, [2, [3, [4, [5]]]]];',
    setupCode: 'const deep = [1, [2, [3, [4, [5]]]]];',
    expected: [1, 2, 3, 4, 5],
    sample: 'deep.flat(Infinity)',
    hints: ['Use Infinity for complete flattening', 'Or use a large number'],
    validPatterns: [
      /\.flat\s*\(\s*Infinity\s*\)/,
      /\.flat\s*\(\s*\d+\s*\)/,
    ],
    tags: ['flat', 'deep-nested'],
  },
  {
    id: 'js-flatMap-001',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'FlatMap Example',
    text: 'Use flatMap to double each number into a pair [n, n*2].',
    setup: 'const numbers = [1, 2, 3];',
    setupCode: 'const numbers = [1, 2, 3];',
    expected: [1, 2, 2, 4, 3, 6],
    sample: 'numbers.flatMap(n => [n, n * 2])',
    hints: ['flatMap combines map and flat', 'Return an array from callback'],
    validPatterns: [
      /\.flatMap\s*\(\s*\w+\s*=>\s*\[\s*\w+\s*,\s*\w+\s*\*\s*2\s*\]\s*\)/,
    ],
    tags: ['flatMap', 'transform'],
  },

  // ========================================
  // STRING METHODS
  // ========================================
  {
    id: 'js-string-001',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Split String into Array',
    text: 'Split the string into an array of words.',
    setup: 'const sentence = "Hello World JavaScript";',
    setupCode: 'const sentence = "Hello World JavaScript";',
    expected: ['Hello', 'World', 'JavaScript'],
    sample: 'sentence.split(" ")',
    hints: ['split takes a separator', 'Space character separates words'],
    validPatterns: [
      /\.split\s*\(\s*['"] ['"]\s*\)/,
      /\.split\s*\(\s*\/\s+\/\s*\)/,
    ],
    tags: ['split', 'strings', 'basics'],
  },
  {
    id: 'js-string-002',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Trim Whitespace',
    text: 'Remove leading and trailing whitespace from the string.',
    setup: 'const text = "   Hello World   ";',
    setupCode: 'const text = "   Hello World   ";',
    expected: 'Hello World',
    sample: 'text.trim()',
    hints: ['trim removes whitespace from both ends', 'Does not affect middle spaces'],
    validPatterns: [
      /\.trim\s*\(\s*\)/,
    ],
    tags: ['trim', 'whitespace'],
  },
  {
    id: 'js-string-003',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Replace Substring',
    text: 'Replace "World" with "JavaScript" in the string.',
    setup: 'const greeting = "Hello World";',
    setupCode: 'const greeting = "Hello World";',
    expected: 'Hello JavaScript',
    sample: 'greeting.replace("World", "JavaScript")',
    hints: ['replace takes search and replacement', 'Returns new string'],
    validPatterns: [
      /\.replace\s*\(\s*['"]World['"]\s*,\s*['"]JavaScript['"]\s*\)/,
    ],
    tags: ['replace', 'strings'],
  },
  {
    id: 'js-string-004',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Replace All Occurrences',
    text: 'Replace all occurrences of "a" with "o".',
    setup: 'const text = "banana";',
    setupCode: 'const text = "banana";',
    expected: 'bonono',
    sample: 'text.replaceAll("a", "o")',
    hints: ['replaceAll replaces all matches', 'Or use replace with global regex'],
    validPatterns: [
      /\.replaceAll\s*\(\s*['"]a['"]\s*,\s*['"]o['"]\s*\)/,
      /\.replace\s*\(\s*\/a\/g\s*,\s*['"]o['"]\s*\)/,
    ],
    tags: ['replaceAll', 'strings'],
  },
  {
    id: 'js-string-005',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Check String Includes',
    text: 'Check if the string includes "script".',
    setup: 'const lang = "JavaScript";',
    setupCode: 'const lang = "JavaScript";',
    expected: true,
    sample: 'lang.toLowerCase().includes("script")',
    hints: ['includes is case-sensitive', 'Convert to lowercase for case-insensitive'],
    validPatterns: [
      /\.toLowerCase\s*\(\s*\)\.includes\s*\(\s*['"]script['"]\s*\)/,
      /\.includes\s*\(\s*['"]Script['"]\s*\)/,
    ],
    tags: ['includes', 'strings'],
  },
  {
    id: 'js-string-006',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'String Starts With',
    text: 'Check if the string starts with "Hello".',
    setup: 'const greeting = "Hello World";',
    setupCode: 'const greeting = "Hello World";',
    expected: true,
    sample: 'greeting.startsWith("Hello")',
    hints: ['startsWith checks the beginning', 'Case-sensitive'],
    validPatterns: [
      /\.startsWith\s*\(\s*['"]Hello['"]\s*\)/,
    ],
    tags: ['startsWith', 'strings'],
  },
  {
    id: 'js-string-007',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'String Ends With',
    text: 'Check if the filename ends with ".js".',
    setup: 'const filename = "app.js";',
    setupCode: 'const filename = "app.js";',
    expected: true,
    sample: 'filename.endsWith(".js")',
    hints: ['endsWith checks the ending', 'Include the dot'],
    validPatterns: [
      /\.endsWith\s*\(\s*['"]\.js['"]\s*\)/,
    ],
    tags: ['endsWith', 'strings'],
  },
  {
    id: 'js-string-008',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Pad String Start',
    text: 'Pad the number string to 5 characters with leading zeros.',
    setup: 'const num = "42";',
    setupCode: 'const num = "42";',
    expected: '00042',
    sample: 'num.padStart(5, "0")',
    hints: ['padStart adds to the beginning', 'Second argument is the fill string'],
    validPatterns: [
      /\.padStart\s*\(\s*5\s*,\s*['"]0['"]\s*\)/,
    ],
    tags: ['padStart', 'formatting'],
  },
  {
    id: 'js-string-009',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Repeat String',
    text: 'Repeat the string 3 times.',
    setup: 'const star = "* ";',
    setupCode: 'const star = "* ";',
    expected: '* * * ',
    sample: 'star.repeat(3)',
    hints: ['repeat takes a count', 'Returns new string'],
    validPatterns: [
      /\.repeat\s*\(\s*3\s*\)/,
    ],
    tags: ['repeat', 'strings'],
  },
  {
    id: 'js-string-010',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Get Character at Index',
    text: 'Get the character at index 4.',
    setup: 'const word = "JavaScript";',
    setupCode: 'const word = "JavaScript";',
    expected: 'S',
    sample: 'word.charAt(4)',
    hints: ['charAt returns single character', 'Index starts at 0'],
    validPatterns: [
      /\.charAt\s*\(\s*4\s*\)/,
      /word\s*\[\s*4\s*\]/,
    ],
    tags: ['charAt', 'indexing'],
  },
  {
    id: 'js-string-011',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Extract Substring',
    text: 'Extract "World" from the string using substring.',
    setup: 'const greeting = "Hello World";',
    setupCode: 'const greeting = "Hello World";',
    expected: 'World',
    sample: 'greeting.substring(6)',
    hints: ['substring(start, end)', 'Or just start to get rest'],
    validPatterns: [
      /\.substring\s*\(\s*6\s*\)/,
      /\.substring\s*\(\s*6\s*,\s*11\s*\)/,
      /\.slice\s*\(\s*6\s*\)/,
    ],
    tags: ['substring', 'extraction'],
  },

  // ========================================
  // OBJECT METHODS
  // ========================================
  {
    id: 'js-object-001',
    category: 'Object Methods',
    difficulty: 'easy',
    title: 'Get Object Keys',
    text: 'Get an array of the object keys.',
    setup: 'const person = { name: "Alice", age: 30, city: "NYC" };',
    setupCode: 'const person = { name: "Alice", age: 30, city: "NYC" };',
    expected: ['name', 'age', 'city'],
    sample: 'Object.keys(person)',
    hints: ['Object.keys returns array of keys', 'Static method on Object'],
    validPatterns: [
      /Object\.keys\s*\(\s*person\s*\)/,
    ],
    tags: ['Object.keys', 'objects'],
  },
  {
    id: 'js-object-002',
    category: 'Object Methods',
    difficulty: 'easy',
    title: 'Get Object Values',
    text: 'Get an array of the object values.',
    setup: 'const person = { name: "Alice", age: 30, city: "NYC" };',
    setupCode: 'const person = { name: "Alice", age: 30, city: "NYC" };',
    expected: ['Alice', 30, 'NYC'],
    sample: 'Object.values(person)',
    hints: ['Object.values returns array of values', 'Static method on Object'],
    validPatterns: [
      /Object\.values\s*\(\s*person\s*\)/,
    ],
    tags: ['Object.values', 'objects'],
  },
  {
    id: 'js-object-003',
    category: 'Object Methods',
    difficulty: 'easy',
    title: 'Get Object Entries',
    text: 'Get an array of [key, value] pairs.',
    setup: 'const person = { name: "Alice", age: 30 };',
    setupCode: 'const person = { name: "Alice", age: 30 };',
    expected: [
      ['name', 'Alice'],
      ['age', 30],
    ],
    sample: 'Object.entries(person)',
    hints: ['Object.entries returns array of pairs', 'Each pair is [key, value]'],
    validPatterns: [
      /Object\.entries\s*\(\s*person\s*\)/,
    ],
    tags: ['Object.entries', 'objects'],
  },
  {
    id: 'js-object-004',
    category: 'Object Methods',
    difficulty: 'medium',
    title: 'Create Object from Entries',
    text: 'Convert the array of pairs back to an object.',
    setup: 'const entries = [["a", 1], ["b", 2], ["c", 3]];',
    setupCode: 'const entries = [["a", 1], ["b", 2], ["c", 3]];',
    expected: { a: 1, b: 2, c: 3 },
    sample: 'Object.fromEntries(entries)',
    hints: ['Object.fromEntries is inverse of entries', 'Takes array of pairs'],
    validPatterns: [
      /Object\.fromEntries\s*\(\s*entries\s*\)/,
    ],
    tags: ['Object.fromEntries', 'objects'],
  },
  {
    id: 'js-object-005',
    category: 'Object Methods',
    difficulty: 'medium',
    title: 'Merge Objects',
    text: 'Merge the two objects into one (second overwrites first).',
    setup: `const defaults = { theme: "light", fontSize: 14 };
const userPrefs = { theme: "dark" };`,
    setupCode: `const defaults = { theme: "light", fontSize: 14 };
const userPrefs = { theme: "dark" };`,
    expected: { theme: 'dark', fontSize: 14 },
    sample: '{ ...defaults, ...userPrefs }',
    hints: ['Use spread operator', 'Later values overwrite earlier'],
    validPatterns: [
      /\{\s*\.\.\.defaults\s*,\s*\.\.\.userPrefs\s*\}/,
      /Object\.assign\s*\(\s*\{\s*\}\s*,\s*defaults\s*,\s*userPrefs\s*\)/,
    ],
    tags: ['spread', 'merge', 'objects'],
  },
  {
    id: 'js-object-006',
    category: 'Object Methods',
    difficulty: 'medium',
    title: 'Check Property Exists',
    text: 'Check if the object has its own "name" property.',
    setup: 'const person = { name: "Alice", age: 30 };',
    setupCode: 'const person = { name: "Alice", age: 30 };',
    expected: true,
    sample: 'Object.hasOwn(person, "name")',
    hints: ['Object.hasOwn is the modern way', 'Or use hasOwnProperty'],
    validPatterns: [
      /Object\.hasOwn\s*\(\s*person\s*,\s*['"]name['"]\s*\)/,
      /person\.hasOwnProperty\s*\(\s*['"]name['"]\s*\)/,
      /['"]name['"]\s*in\s*person/,
    ],
    tags: ['hasOwn', 'property-check'],
  },

  // ========================================
  // SET METHODS
  // ========================================
  {
    id: 'js-set-001',
    category: 'Set Methods',
    difficulty: 'easy',
    title: 'Create Set from Array',
    text: 'Create a Set from the array to remove duplicates, then convert back to array.',
    setup: 'const numbers = [1, 2, 2, 3, 3, 3, 4];',
    setupCode: 'const numbers = [1, 2, 2, 3, 3, 3, 4];',
    expected: [1, 2, 3, 4],
    sample: '[...new Set(numbers)]',
    hints: ['Set automatically removes duplicates', 'Spread to convert back to array'],
    validPatterns: [
      /\[\s*\.\.\.new\s+Set\s*\(\s*numbers\s*\)\s*\]/,
      /Array\.from\s*\(\s*new\s+Set\s*\(\s*numbers\s*\)\s*\)/,
    ],
    tags: ['Set', 'unique', 'duplicates'],
  },
  {
    id: 'js-set-002',
    category: 'Set Methods',
    difficulty: 'medium',
    title: 'Set Intersection',
    text: 'Find common elements between two arrays using Set.',
    setup: `const arr1 = [1, 2, 3, 4, 5];
const arr2 = [4, 5, 6, 7, 8];`,
    setupCode: `const arr1 = [1, 2, 3, 4, 5];
const arr2 = [4, 5, 6, 7, 8];`,
    expected: [4, 5],
    sample: 'arr1.filter(x => new Set(arr2).has(x))',
    hints: ['Convert one array to Set', 'Filter the other by membership'],
    validPatterns: [
      /\.filter\s*\(\s*\w+\s*=>\s*new\s+Set\s*\(\s*\w+\s*\)\.has\s*\(\s*\w+\s*\)\s*\)/,
    ],
    tags: ['Set', 'intersection', 'filter'],
  },
  {
    id: 'js-set-003',
    category: 'Set Methods',
    difficulty: 'medium',
    title: 'Set Difference',
    text: 'Find elements in arr1 that are not in arr2.',
    setup: `const arr1 = [1, 2, 3, 4, 5];
const arr2 = [4, 5, 6, 7, 8];`,
    setupCode: `const arr1 = [1, 2, 3, 4, 5];
const arr2 = [4, 5, 6, 7, 8];`,
    expected: [1, 2, 3],
    sample: 'arr1.filter(x => !new Set(arr2).has(x))',
    hints: ['Use Set.has for O(1) lookup', 'Negate the condition for difference'],
    validPatterns: [
      /\.filter\s*\(\s*\w+\s*=>\s*!new\s+Set\s*\(\s*\w+\s*\)\.has\s*\(\s*\w+\s*\)\s*\)/,
    ],
    tags: ['Set', 'difference', 'filter'],
  },

  // ========================================
  // MATH OPERATIONS
  // ========================================
  {
    id: 'js-math-001',
    category: 'Math Operations',
    difficulty: 'easy',
    title: 'Find Maximum',
    text: 'Find the maximum value in the array.',
    setup: 'const numbers = [5, 2, 9, 1, 7, 3];',
    setupCode: 'const numbers = [5, 2, 9, 1, 7, 3];',
    expected: 9,
    sample: 'Math.max(...numbers)',
    hints: ['Math.max takes individual arguments', 'Use spread to expand array'],
    validPatterns: [
      /Math\.max\s*\(\s*\.\.\.numbers\s*\)/,
    ],
    tags: ['Math.max', 'spread'],
  },
  {
    id: 'js-math-002',
    category: 'Math Operations',
    difficulty: 'easy',
    title: 'Find Minimum',
    text: 'Find the minimum value in the array.',
    setup: 'const numbers = [5, 2, 9, 1, 7, 3];',
    setupCode: 'const numbers = [5, 2, 9, 1, 7, 3];',
    expected: 1,
    sample: 'Math.min(...numbers)',
    hints: ['Math.min finds smallest', 'Spread the array'],
    validPatterns: [
      /Math\.min\s*\(\s*\.\.\.numbers\s*\)/,
    ],
    tags: ['Math.min', 'spread'],
  },
  {
    id: 'js-math-003',
    category: 'Math Operations',
    difficulty: 'easy',
    title: 'Round Number',
    text: 'Round the number to the nearest integer.',
    setup: 'const num = 4.7;',
    setupCode: 'const num = 4.7;',
    expected: 5,
    sample: 'Math.round(num)',
    hints: ['Math.round rounds to nearest', '4.5 and up rounds up'],
    validPatterns: [
      /Math\.round\s*\(\s*num\s*\)/,
    ],
    tags: ['Math.round', 'rounding'],
  },
  {
    id: 'js-math-004',
    category: 'Math Operations',
    difficulty: 'easy',
    title: 'Floor Number',
    text: 'Round down to the nearest integer.',
    setup: 'const num = 4.9;',
    setupCode: 'const num = 4.9;',
    expected: 4,
    sample: 'Math.floor(num)',
    hints: ['Math.floor always rounds down', 'Towards negative infinity'],
    validPatterns: [
      /Math\.floor\s*\(\s*num\s*\)/,
    ],
    tags: ['Math.floor', 'rounding'],
  },
  {
    id: 'js-math-005',
    category: 'Math Operations',
    difficulty: 'easy',
    title: 'Ceil Number',
    text: 'Round up to the nearest integer.',
    setup: 'const num = 4.1;',
    setupCode: 'const num = 4.1;',
    expected: 5,
    sample: 'Math.ceil(num)',
    hints: ['Math.ceil always rounds up', 'Towards positive infinity'],
    validPatterns: [
      /Math\.ceil\s*\(\s*num\s*\)/,
    ],
    tags: ['Math.ceil', 'rounding'],
  },
  {
    id: 'js-math-006',
    category: 'Math Operations',
    difficulty: 'medium',
    title: 'Absolute Value',
    text: 'Get the absolute value of the number.',
    setup: 'const num = -42;',
    setupCode: 'const num = -42;',
    expected: 42,
    sample: 'Math.abs(num)',
    hints: ['Math.abs removes sign', 'Always returns positive'],
    validPatterns: [
      /Math\.abs\s*\(\s*num\s*\)/,
    ],
    tags: ['Math.abs', 'absolute'],
  },
  {
    id: 'js-math-007',
    category: 'Math Operations',
    difficulty: 'medium',
    title: 'Power Calculation',
    text: 'Calculate 2 to the power of 10.',
    setup: 'const base = 2, exponent = 10;',
    setupCode: 'const base = 2, exponent = 10;',
    expected: 1024,
    sample: 'Math.pow(base, exponent)',
    hints: ['Math.pow(base, exponent)', 'Or use ** operator'],
    validPatterns: [
      /Math\.pow\s*\(\s*base\s*,\s*exponent\s*\)/,
      /base\s*\*\*\s*exponent/,
      /2\s*\*\*\s*10/,
    ],
    tags: ['Math.pow', 'exponent'],
  },
  {
    id: 'js-math-008',
    category: 'Math Operations',
    difficulty: 'medium',
    title: 'Square Root',
    text: 'Calculate the square root of 144.',
    setup: 'const num = 144;',
    setupCode: 'const num = 144;',
    expected: 12,
    sample: 'Math.sqrt(num)',
    hints: ['Math.sqrt for square root', 'Returns the positive root'],
    validPatterns: [
      /Math\.sqrt\s*\(\s*num\s*\)/,
      /Math\.sqrt\s*\(\s*144\s*\)/,
    ],
    tags: ['Math.sqrt', 'root'],
  },

  // ========================================
  // CHAINED METHODS
  // ========================================
  {
    id: 'js-chain-001',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Filter and Map Chain',
    text: 'Get the names of users who are 30 or older.',
    setup: `const users = [
  { name: "Alice", age: 25 },
  { name: "Bob", age: 30 },
  { name: "Charlie", age: 35 },
  { name: "Diana", age: 28 }
];`,
    setupCode: `const users = [
  { name: "Alice", age: 25 },
  { name: "Bob", age: 30 },
  { name: "Charlie", age: 35 },
  { name: "Diana", age: 28 }
];`,
    expected: ['Bob', 'Charlie'],
    sample: 'users.filter(u => u.age >= 30).map(u => u.name)',
    hints: ['Filter first, then map', 'Chain the methods'],
    validPatterns: [
      /\.filter\s*\([^)]+\)\.map\s*\([^)]+\)/,
    ],
    tags: ['filter', 'map', 'chaining'],
  },
  {
    id: 'js-chain-002',
    category: 'Array Methods',
    difficulty: 'hard',
    title: 'Complex Chain',
    text: 'Get the total price of all in-stock items, with 10% discount applied.',
    setup: `const items = [
  { name: "Laptop", price: 1000, inStock: true },
  { name: "Phone", price: 500, inStock: false },
  { name: "Tablet", price: 300, inStock: true },
  { name: "Watch", price: 200, inStock: true }
];`,
    setupCode: `const items = [
  { name: "Laptop", price: 1000, inStock: true },
  { name: "Phone", price: 500, inStock: false },
  { name: "Tablet", price: 300, inStock: true },
  { name: "Watch", price: 200, inStock: true }
];`,
    expected: 1350,
    sample: 'items.filter(i => i.inStock).map(i => i.price * 0.9).reduce((sum, p) => sum + p, 0)',
    hints: ['Filter in-stock items', 'Map to apply discount', 'Reduce to sum'],
    validPatterns: [
      /\.filter\s*\([^)]+\)\.map\s*\([^)]+\)\.reduce\s*\([^)]+\)/,
      /\.filter\s*\([^)]+\)\.reduce\s*\([^)]+\)/,
    ],
    tags: ['filter', 'map', 'reduce', 'chaining'],
  },
  {
    id: 'js-chain-003',
    category: 'Array Methods',
    difficulty: 'hard',
    title: 'Sort and Slice',
    text: 'Get the top 3 highest scores.',
    setup: 'const scores = [85, 92, 78, 96, 88, 91, 73];',
    setupCode: 'const scores = [85, 92, 78, 96, 88, 91, 73];',
    expected: [96, 92, 91],
    sample: 'scores.slice().sort((a, b) => b - a).slice(0, 3)',
    hints: ['Sort descending first', 'Slice to get top 3', 'Use slice() to avoid mutation'],
    validPatterns: [
      /\.sort\s*\([^)]+\)\.slice\s*\(\s*0\s*,\s*3\s*\)/,
    ],
    tags: ['sort', 'slice', 'chaining'],
  },

  // ========================================
  // ADVANCED PROBLEMS
  // ========================================
  {
    id: 'js-advanced-001',
    category: 'Array Methods',
    difficulty: 'hard',
    title: 'Partition Array',
    text: 'Partition the array into [evens, odds].',
    setup: 'const numbers = [1, 2, 3, 4, 5, 6, 7, 8];',
    setupCode: 'const numbers = [1, 2, 3, 4, 5, 6, 7, 8];',
    expected: [
      [2, 4, 6, 8],
      [1, 3, 5, 7],
    ],
    sample: '[numbers.filter(n => n % 2 === 0), numbers.filter(n => n % 2 !== 0)]',
    hints: ['Create two filtered arrays', 'Use modulo to check even/odd'],
    validPatterns: [
      /\[\s*numbers\.filter\s*\([^)]+\)\s*,\s*numbers\.filter\s*\([^)]+\)\s*\]/,
      /\.reduce\s*\([^)]+\[\s*\w+\s*%\s*2/,
    ],
    tags: ['partition', 'filter', 'advanced'],
  },
  {
    id: 'js-advanced-002',
    category: 'Array Methods',
    difficulty: 'hard',
    title: 'Zip Two Arrays',
    text: 'Combine two arrays into pairs.',
    setup: `const keys = ["a", "b", "c"];
const values = [1, 2, 3];`,
    setupCode: `const keys = ["a", "b", "c"];
const values = [1, 2, 3];`,
    expected: [
      ['a', 1],
      ['b', 2],
      ['c', 3],
    ],
    sample: 'keys.map((k, i) => [k, values[i]])',
    hints: ['Use map with index', 'Access values by same index'],
    validPatterns: [
      /\.map\s*\(\s*\(\s*\w+\s*,\s*\w+\s*\)\s*=>\s*\[\s*\w+\s*,\s*values\s*\[\s*\w+\s*\]\s*\]\s*\)/,
    ],
    tags: ['zip', 'map', 'index'],
  },
  {
    id: 'js-advanced-003',
    category: 'Array Methods',
    difficulty: 'hard',
    title: 'Running Total',
    text: 'Create an array of running totals.',
    setup: 'const numbers = [1, 2, 3, 4, 5];',
    setupCode: 'const numbers = [1, 2, 3, 4, 5];',
    expected: [1, 3, 6, 10, 15],
    sample: 'numbers.map((n, i) => numbers.slice(0, i + 1).reduce((a, b) => a + b, 0))',
    hints: ['For each position, sum all previous', 'Or use reduce to track running total'],
    validPatterns: [
      /\.map\s*\(/,
      /\.reduce\s*\(/,
    ],
    tags: ['running-total', 'reduce', 'advanced'],
  },
  {
    id: 'js-advanced-004',
    category: 'Object Methods',
    difficulty: 'hard',
    title: 'Invert Object',
    text: 'Swap keys and values in the object.',
    setup: 'const obj = { a: 1, b: 2, c: 3 };',
    setupCode: 'const obj = { a: 1, b: 2, c: 3 };',
    expected: { 1: 'a', 2: 'b', 3: 'c' },
    sample: 'Object.fromEntries(Object.entries(obj).map(([k, v]) => [v, k]))',
    hints: ['Use Object.entries to get pairs', 'Swap positions in each pair', 'Use Object.fromEntries to rebuild'],
    validPatterns: [
      /Object\.fromEntries\s*\(\s*Object\.entries\s*\([^)]+\)\.map/,
    ],
    tags: ['Object.entries', 'Object.fromEntries', 'transform'],
  },
  {
    id: 'js-advanced-005',
    category: 'Array Methods',
    difficulty: 'hard',
    title: 'Frequency Map',
    text: 'Count the frequency of each character.',
    setup: 'const str = "hello";',
    setupCode: 'const str = "hello";',
    expected: { h: 1, e: 1, l: 2, o: 1 },
    sample: 'str.split("").reduce((acc, char) => ({ ...acc, [char]: (acc[char] || 0) + 1 }), {})',
    hints: ['Split string into array', 'Use reduce to count'],
    validPatterns: [
      /\.split\s*\(\s*['"]{2}\s*\)\.reduce/,
      /\[\s*\.\.\.str\s*\]\.reduce/,
    ],
    tags: ['frequency', 'reduce', 'strings'],
  },
  {
    id: 'js-advanced-006',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Array to Object',
    text: 'Convert the array of users to an object keyed by id.',
    setup: `const users = [
  { id: 1, name: "Alice" },
  { id: 2, name: "Bob" },
  { id: 3, name: "Charlie" }
];`,
    setupCode: `const users = [
  { id: 1, name: "Alice" },
  { id: 2, name: "Bob" },
  { id: 3, name: "Charlie" }
];`,
    expected: {
      1: { id: 1, name: 'Alice' },
      2: { id: 2, name: 'Bob' },
      3: { id: 3, name: 'Charlie' },
    },
    sample: 'Object.fromEntries(users.map(u => [u.id, u]))',
    hints: ['Map to [id, user] pairs', 'Use Object.fromEntries'],
    validPatterns: [
      /Object\.fromEntries\s*\(\s*users\.map/,
      /users\.reduce\s*\(/,
    ],
    tags: ['Object.fromEntries', 'map', 'transform'],
  },
];

export default javascriptProblems;
