import type { Problem } from '../types';

/**
 * Java Coding Drills Problems
 *
 * Comprehensive collection of Java problems covering:
 * - ArrayList/List Methods (20 problems)
 * - Stream API (25 problems)
 * - String Methods (17 problems)
 * - Array Operations (8 problems)
 *
 * Note: Examples are compatible with Java 8+, with hints for modern Java features
 * (Java 11+ strip(), Java 16+ toList(), etc.) where applicable.
 */

export const javaProblems: Problem[] = [
  // ============================================================
  // ArrayList/List Methods (12+ problems)
  // ============================================================

  {
    id: 'java-list-001',
    category: 'ArrayList Methods',
    difficulty: 'easy',
    title: 'Add Element to List',
    text: 'Add the number 10 to the end of the list',
    setup: 'List<Integer> nums = new ArrayList<>(Arrays.asList(1, 2, 3));',
    setupCode: 'List<Integer> nums = new ArrayList<>(Arrays.asList(1, 2, 3));',
    expected: [1, 2, 3, 10],
    sample: 'nums.add(10); // nums is now [1, 2, 3, 10]',
    hints: ['Use the add() method to append an element', 'add() appends to the end of the list'],
    validPatterns: [/\.add\(\s*10\s*\)/],
    tags: ['ArrayList', 'add', 'basics'],
  },

  {
    id: 'java-list-002',
    category: 'ArrayList Methods',
    difficulty: 'easy',
    title: 'Add Element at Index',
    text: 'Insert the number 99 at index 1 (second position)',
    setup: 'List<Integer> nums = new ArrayList<>(Arrays.asList(1, 2, 3));',
    setupCode: 'List<Integer> nums = new ArrayList<>(Arrays.asList(1, 2, 3));',
    expected: [1, 99, 2, 3],
    sample: 'nums.add(1, 99); // nums is now [1, 99, 2, 3]',
    hints: ['Use add(index, element) to insert at a specific position', 'Index 1 means the second position'],
    validPatterns: [/\.add\(\s*1\s*,\s*99\s*\)/],
    tags: ['ArrayList', 'add', 'index'],
  },

  {
    id: 'java-list-003',
    category: 'ArrayList Methods',
    difficulty: 'easy',
    title: 'Add All Elements',
    text: 'Add all elements from newNums to nums',
    setup: 'List<Integer> nums = new ArrayList<>(Arrays.asList(1, 2));\nList<Integer> newNums = Arrays.asList(3, 4, 5);',
    setupCode: 'List<Integer> nums = new ArrayList<>(Arrays.asList(1, 2));\nList<Integer> newNums = Arrays.asList(3, 4, 5);',
    expected: [1, 2, 3, 4, 5],
    sample: 'nums.addAll(newNums); // nums is now [1, 2, 3, 4, 5]',
    hints: ['Use addAll() to add all elements from another collection', 'addAll() appends to the end by default'],
    validPatterns: [/\.addAll\(\s*newNums\s*\)/],
    tags: ['ArrayList', 'addAll', 'collections'],
  },

  {
    id: 'java-list-004',
    category: 'ArrayList Methods',
    difficulty: 'easy',
    title: 'Get Element by Index',
    text: 'Get the element at index 2 from the list',
    setup: 'List<String> fruits = Arrays.asList("apple", "banana", "cherry", "date");',
    setupCode: 'List<String> fruits = Arrays.asList("apple", "banana", "cherry", "date");',
    expected: 'cherry',
    sample: 'fruits.get(2) // returns "cherry"',
    hints: ['Use get(index) to retrieve an element', 'Indices start at 0'],
    validPatterns: [/\.get\(\s*2\s*\)/],
    tags: ['ArrayList', 'get', 'access'],
  },

  {
    id: 'java-list-005',
    category: 'ArrayList Methods',
    difficulty: 'easy',
    title: 'Set Element at Index',
    text: 'Replace the element at index 1 with "orange"',
    setup: 'List<String> fruits = new ArrayList<>(Arrays.asList("apple", "banana", "cherry"));',
    setupCode: 'List<String> fruits = new ArrayList<>(Arrays.asList("apple", "banana", "cherry"));',
    expected: ['apple', 'orange', 'cherry'],
    sample: 'fruits.set(1, "orange"); // fruits is now ["apple", "orange", "cherry"]',
    hints: ['Use set(index, element) to replace an element', 'set() returns the old element that was replaced'],
    validPatterns: [/\.set\(\s*1\s*,\s*"orange"\s*\)/],
    tags: ['ArrayList', 'set', 'update'],
  },

  {
    id: 'java-list-006',
    category: 'ArrayList Methods',
    difficulty: 'easy',
    title: 'Remove by Index',
    text: 'Remove the element at index 0 from the list',
    setup: 'List<Integer> nums = new ArrayList<>(Arrays.asList(10, 20, 30, 40));',
    setupCode: 'List<Integer> nums = new ArrayList<>(Arrays.asList(10, 20, 30, 40));',
    expected: [20, 30, 40],
    sample: 'nums.remove(0); // nums is now [20, 30, 40]',
    hints: ['Use remove(index) to remove by position', 'For List<Integer>, remove(int) removes by index', 'To remove by value, use remove(Integer.valueOf(10)) to force Object removal'],
    validPatterns: [/\.remove\(\s*0\s*\)/],
    tags: ['ArrayList', 'remove', 'index'],
  },

  {
    id: 'java-list-007',
    category: 'ArrayList Methods',
    difficulty: 'medium',
    title: 'Remove by Object',
    text: 'Remove the string "banana" from the list',
    setup: 'List<String> fruits = new ArrayList<>(Arrays.asList("apple", "banana", "cherry"));',
    setupCode: 'List<String> fruits = new ArrayList<>(Arrays.asList("apple", "banana", "cherry"));',
    expected: ['apple', 'cherry'],
    sample: 'fruits.remove("banana"); // fruits is now ["apple", "cherry"]',
    hints: ['Use remove(Object) to remove by value', 'Returns true if element was found and removed'],
    validPatterns: [/\.remove\(\s*"banana"\s*\)/],
    tags: ['ArrayList', 'remove', 'object'],
  },

  {
    id: 'java-list-008',
    category: 'ArrayList Methods',
    difficulty: 'easy',
    title: 'Clear All Elements',
    text: 'Remove all elements from the list',
    setup: 'List<Integer> nums = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5));',
    setupCode: 'List<Integer> nums = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5));',
    expected: [],
    sample: 'nums.clear(); // nums is now []',
    hints: ['Use clear() to remove all elements', 'The list becomes empty after clear()'],
    validPatterns: [/\.clear\(\)/],
    tags: ['ArrayList', 'clear', 'basics'],
  },

  {
    id: 'java-list-009',
    category: 'ArrayList Methods',
    difficulty: 'easy',
    title: 'Get List Size',
    text: 'Get the number of elements in the list',
    setup: 'List<String> colors = Arrays.asList("red", "green", "blue", "yellow");',
    setupCode: 'List<String> colors = Arrays.asList("red", "green", "blue", "yellow");',
    expected: 4,
    sample: 'colors.size() // returns 4',
    hints: ['Use size() to get the number of elements', 'size() returns an int'],
    validPatterns: [/\.size\(\)/],
    tags: ['ArrayList', 'size', 'basics'],
  },

  {
    id: 'java-list-010',
    category: 'ArrayList Methods',
    difficulty: 'easy',
    title: 'Check if List is Empty',
    text: 'Check if the list is empty',
    setup: 'List<Integer> nums = new ArrayList<>();',
    setupCode: 'List<Integer> nums = new ArrayList<>();',
    expected: true,
    sample: 'nums.isEmpty() // returns true',
    hints: ['Use isEmpty() to check if a list has no elements', 'isEmpty() returns a boolean'],
    validPatterns: [/\.isEmpty\(\)/],
    tags: ['ArrayList', 'isEmpty', 'validation'],
  },

  {
    id: 'java-list-011',
    category: 'ArrayList Methods',
    difficulty: 'easy',
    title: 'Check if Contains Element',
    text: 'Check if the list contains the number 3',
    setup: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);',
    setupCode: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);',
    expected: true,
    sample: 'nums.contains(3) // returns true',
    hints: ['Use contains() to check for element presence', 'Uses equals() for comparison'],
    validPatterns: [/\.contains\(\s*3\s*\)/],
    tags: ['ArrayList', 'contains', 'search'],
  },

  {
    id: 'java-list-012',
    category: 'ArrayList Methods',
    difficulty: 'easy',
    title: 'Find Index of Element',
    text: 'Find the index of "cherry" in the list',
    setup: 'List<String> fruits = Arrays.asList("apple", "banana", "cherry", "date");',
    setupCode: 'List<String> fruits = Arrays.asList("apple", "banana", "cherry", "date");',
    expected: 2,
    sample: 'fruits.indexOf("cherry") // returns 2',
    hints: ['Use indexOf() to find the first occurrence', 'Returns -1 if not found'],
    validPatterns: [/\.indexOf\(\s*"cherry"\s*\)/],
    tags: ['ArrayList', 'indexOf', 'search'],
  },

  {
    id: 'java-list-013',
    category: 'Collections Utility',
    difficulty: 'medium',
    title: 'Sort List Ascending',
    text: 'Sort the list in ascending order',
    setup: 'List<Integer> nums = new ArrayList<>(Arrays.asList(5, 2, 8, 1, 9));',
    setupCode: 'List<Integer> nums = new ArrayList<>(Arrays.asList(5, 2, 8, 1, 9));',
    expected: [1, 2, 5, 8, 9],
    sample: 'Collections.sort(nums); // nums is now [1, 2, 5, 8, 9]',
    hints: ['Use Collections.sort() to sort in natural order', 'Modifies the list in place'],
    validPatterns: [/Collections\.sort\(\s*nums\s*\)/],
    tags: ['Collections', 'sort', 'ordering'],
  },

  {
    id: 'java-list-014',
    category: 'Collections Utility',
    difficulty: 'medium',
    title: 'Reverse List',
    text: 'Reverse the order of elements in the list',
    setup: 'List<Integer> nums = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5));',
    setupCode: 'List<Integer> nums = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5));',
    expected: [5, 4, 3, 2, 1],
    sample: 'Collections.reverse(nums); // nums is now [5, 4, 3, 2, 1]',
    hints: ['Use Collections.reverse() to reverse order', 'Modifies the list in place'],
    validPatterns: [/Collections\.reverse\(\s*nums\s*\)/],
    tags: ['Collections', 'reverse', 'ordering'],
  },

  {
    id: 'java-list-015',
    category: 'ArrayList Methods',
    difficulty: 'medium',
    title: 'Get Sublist',
    text: 'Get a sublist from index 1 to 4 (exclusive)',
    setup: 'List<Integer> nums = Arrays.asList(10, 20, 30, 40, 50, 60);',
    setupCode: 'List<Integer> nums = Arrays.asList(10, 20, 30, 40, 50, 60);',
    expected: [20, 30, 40],
    sample: 'nums.subList(1, 4) // returns [20, 30, 40]',
    hints: ['Use subList(fromIndex, toIndex)', 'toIndex is exclusive'],
    validPatterns: [/\.subList\(\s*1\s*,\s*4\s*\)/],
    tags: ['ArrayList', 'subList', 'slicing'],
  },

  // ============================================================
  // Stream API (15+ problems)
  // ============================================================

  {
    id: 'java-stream-001',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Filter Even Numbers',
    text: 'Filter to keep only even numbers using streams',
    setup: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6);',
    setupCode: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6);',
    expected: [2, 4, 6],
    sample: 'nums.stream().filter(n -> n % 2 == 0).collect(Collectors.toList())',
    hints: ['Use stream(), filter(), and collect()', 'Lambda: n -> n % 2 == 0 checks for even numbers', 'Java 16+: Use .toList() instead of .collect(Collectors.toList())'],
    validPatterns: [/\.stream\(\)/, /\.filter\(/, /\.collect\(|\.toList\(\)/],
    tags: ['Stream', 'filter', 'lambda'],
  },

  {
    id: 'java-stream-002',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Filter Strings by Length',
    text: 'Filter to keep only strings with length greater than 4',
    setup: 'List<String> words = Arrays.asList("cat", "elephant", "dog", "giraffe", "bee");',
    setupCode: 'List<String> words = Arrays.asList("cat", "elephant", "dog", "giraffe", "bee");',
    expected: ['elephant', 'giraffe'],
    sample: 'words.stream().filter(w -> w.length() > 4).collect(Collectors.toList())',
    hints: ['Use filter() with a length check', 'String.length() returns the character count'],
    validPatterns: [/\.stream\(\)/, /\.filter\(/, /\.length\(\)/],
    tags: ['Stream', 'filter', 'String'],
  },

  {
    id: 'java-stream-003',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Map to Uppercase',
    text: 'Transform all strings to uppercase using streams',
    setup: 'List<String> words = Arrays.asList("hello", "world", "java");',
    setupCode: 'List<String> words = Arrays.asList("hello", "world", "java");',
    expected: ['HELLO', 'WORLD', 'JAVA'],
    sample: 'words.stream().map(String::toUpperCase).collect(Collectors.toList())',
    hints: ['Use map() to transform elements', 'String::toUpperCase is a method reference'],
    validPatterns: [/\.stream\(\)/, /\.map\(/, /toUpperCase/],
    tags: ['Stream', 'map', 'transformation'],
  },

  {
    id: 'java-stream-004',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Map to String Lengths',
    text: 'Get the length of each string using streams',
    setup: 'List<String> words = Arrays.asList("apple", "banana", "cherry");',
    setupCode: 'List<String> words = Arrays.asList("apple", "banana", "cherry");',
    expected: [5, 6, 6],
    sample: 'words.stream().map(String::length).collect(Collectors.toList())',
    hints: ['Use map() with String::length', 'Returns a List<Integer>'],
    validPatterns: [/\.stream\(\)/, /\.map\(/, /length/],
    tags: ['Stream', 'map', 'transformation'],
  },

  {
    id: 'java-stream-005',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Square Numbers',
    text: 'Square each number using streams',
    setup: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);',
    setupCode: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);',
    expected: [1, 4, 9, 16, 25],
    sample: 'nums.stream().map(n -> n * n).collect(Collectors.toList())',
    hints: ['Use map() with a lambda that squares', 'n -> n * n squares the value'],
    validPatterns: [/\.stream\(\)/, /\.map\(/, /\*\s*n|\*\s*\w/],
    tags: ['Stream', 'map', 'math'],
  },

  {
    id: 'java-stream-006',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Sum with Reduce',
    text: 'Calculate the sum of all numbers using reduce',
    setup: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);',
    setupCode: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);',
    expected: 15,
    sample: 'nums.stream().reduce(0, Integer::sum)',
    hints: ['Use reduce(identity, accumulator)', '0 is the identity, Integer::sum is the accumulator'],
    validPatterns: [/\.stream\(\)/, /\.reduce\(/],
    tags: ['Stream', 'reduce', 'aggregation'],
  },

  {
    id: 'java-stream-007',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Find Maximum with Reduce',
    text: 'Find the maximum value using reduce',
    setup: 'List<Integer> nums = Arrays.asList(3, 7, 2, 9, 5);',
    setupCode: 'List<Integer> nums = Arrays.asList(3, 7, 2, 9, 5);',
    expected: 9,
    sample: 'nums.stream().reduce(Integer::max).orElse(null) // or: nums.stream().reduce(Integer.MIN_VALUE, Integer::max)',
    hints: ['Use reduce() with Integer::max', 'Prefer reduce(BinaryOperator) returning Optional over reduce with identity for max/min', 'Alternative: use max(Comparator) which is more readable'],
    validPatterns: [/\.stream\(\)/, /\.reduce\(|\.max\(/],
    tags: ['Stream', 'reduce', 'max', 'Optional'],
  },

  {
    id: 'java-stream-008',
    category: 'Stream API',
    difficulty: 'easy',
    title: 'Sort Stream',
    text: 'Sort the numbers in ascending order using streams',
    setup: 'List<Integer> nums = Arrays.asList(5, 2, 8, 1, 9);',
    setupCode: 'List<Integer> nums = Arrays.asList(5, 2, 8, 1, 9);',
    expected: [1, 2, 5, 8, 9],
    sample: 'nums.stream().sorted().collect(Collectors.toList())',
    hints: ['Use sorted() for natural ordering', 'No comparator needed for natural order'],
    validPatterns: [/\.stream\(\)/, /\.sorted\(\)/, /\.collect\(/],
    tags: ['Stream', 'sorted', 'ordering'],
  },

  {
    id: 'java-stream-009',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Sort Descending',
    text: 'Sort the numbers in descending order using streams',
    setup: 'List<Integer> nums = Arrays.asList(5, 2, 8, 1, 9);',
    setupCode: 'List<Integer> nums = Arrays.asList(5, 2, 8, 1, 9);',
    expected: [9, 8, 5, 2, 1],
    sample: 'nums.stream().sorted(Comparator.reverseOrder()).collect(Collectors.toList())',
    hints: ['Use sorted() with Comparator.reverseOrder()', 'Or use Collections.reverseOrder()'],
    validPatterns: [/\.stream\(\)/, /\.sorted\(/, /reverseOrder|reversed/],
    tags: ['Stream', 'sorted', 'Comparator'],
  },

  {
    id: 'java-stream-010',
    category: 'Stream API',
    difficulty: 'easy',
    title: 'Get Distinct Elements',
    text: 'Remove duplicate elements using streams',
    setup: 'List<Integer> nums = Arrays.asList(1, 2, 2, 3, 3, 3, 4);',
    setupCode: 'List<Integer> nums = Arrays.asList(1, 2, 2, 3, 3, 3, 4);',
    expected: [1, 2, 3, 4],
    sample: 'nums.stream().distinct().collect(Collectors.toList())',
    hints: ['Use distinct() to remove duplicates', 'Uses equals() for comparison'],
    validPatterns: [/\.stream\(\)/, /\.distinct\(\)/, /\.collect\(/],
    tags: ['Stream', 'distinct', 'deduplication'],
  },

  {
    id: 'java-stream-011',
    category: 'Stream API',
    difficulty: 'easy',
    title: 'Count Elements',
    text: 'Count the number of elements using streams',
    setup: 'List<String> words = Arrays.asList("a", "b", "c", "d", "e");',
    setupCode: 'List<String> words = Arrays.asList("a", "b", "c", "d", "e");',
    expected: 5,
    sample: 'words.stream().count()',
    hints: ['Use count() to get the number of elements', 'Returns a long'],
    validPatterns: [/\.stream\(\)/, /\.count\(\)/],
    tags: ['Stream', 'count', 'aggregation'],
  },

  {
    id: 'java-stream-012',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Count Filtered Elements',
    text: 'Count how many numbers are greater than 3',
    setup: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6);',
    setupCode: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6);',
    expected: 3,
    sample: 'nums.stream().filter(n -> n > 3).count()',
    hints: ['Combine filter() and count()', 'Filter first, then count'],
    validPatterns: [/\.stream\(\)/, /\.filter\(/, /\.count\(\)/],
    tags: ['Stream', 'filter', 'count'],
  },

  {
    id: 'java-stream-013',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Any Match',
    text: 'Check if any number is greater than 10',
    setup: 'List<Integer> nums = Arrays.asList(5, 8, 12, 3, 7);',
    setupCode: 'List<Integer> nums = Arrays.asList(5, 8, 12, 3, 7);',
    expected: true,
    sample: 'nums.stream().anyMatch(n -> n > 10)',
    hints: ['Use anyMatch() with a predicate', 'Returns true if at least one matches'],
    validPatterns: [/\.stream\(\)/, /\.anyMatch\(/],
    tags: ['Stream', 'anyMatch', 'predicate'],
  },

  {
    id: 'java-stream-014',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'All Match',
    text: 'Check if all numbers are positive',
    setup: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);',
    setupCode: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);',
    expected: true,
    sample: 'nums.stream().allMatch(n -> n > 0)',
    hints: ['Use allMatch() with a predicate', 'Returns true only if ALL elements match'],
    validPatterns: [/\.stream\(\)/, /\.allMatch\(/],
    tags: ['Stream', 'allMatch', 'predicate'],
  },

  {
    id: 'java-stream-015',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'None Match',
    text: 'Check if no number is negative',
    setup: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);',
    setupCode: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);',
    expected: true,
    sample: 'nums.stream().noneMatch(n -> n < 0)',
    hints: ['Use noneMatch() with a predicate', 'Returns true if NO element matches'],
    validPatterns: [/\.stream\(\)/, /\.noneMatch\(/],
    tags: ['Stream', 'noneMatch', 'predicate'],
  },

  {
    id: 'java-stream-016',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Find First',
    text: 'Find the first even number in the list',
    setup: 'List<Integer> nums = Arrays.asList(1, 3, 4, 5, 6);',
    setupCode: 'List<Integer> nums = Arrays.asList(1, 3, 4, 5, 6);',
    expected: 4,
    sample: 'nums.stream().filter(n -> n % 2 == 0).findFirst().orElse(null)',
    hints: ['Use filter() then findFirst()', 'findFirst() returns an Optional<T>', 'Use orElse(default) or orElseThrow() to unwrap the Optional', 'findAny() is similar but may return any matching element (useful for parallel streams)'],
    validPatterns: [/\.stream\(\)/, /\.filter\(/, /\.findFirst\(\)/],
    tags: ['Stream', 'findFirst', 'Optional'],
  },

  {
    id: 'java-stream-017',
    category: 'Stream API',
    difficulty: 'easy',
    title: 'For Each',
    text: 'Print each element using forEach (returns void, side effect)',
    setup: 'List<String> words = Arrays.asList("hello", "world");',
    setupCode: 'List<String> words = Arrays.asList("hello", "world");',
    expected: null,
    sample: 'words.stream().forEach(System.out::println) // or: words.forEach(System.out::println)',
    hints: ['Use forEach() for side effects like printing', 'System.out::println is a method reference', 'forEach returns void - it is a terminal operation', 'Note: List has forEach() directly, stream() is optional here'],
    validPatterns: [/\.forEach\(/],
    tags: ['Stream', 'forEach', 'terminal', 'side-effect'],
  },

  {
    id: 'java-stream-018',
    category: 'Stream API',
    difficulty: 'hard',
    title: 'FlatMap Nested Lists',
    text: 'Flatten a list of lists into a single list',
    setup: 'List<List<Integer>> nested = Arrays.asList(\n  Arrays.asList(1, 2),\n  Arrays.asList(3, 4),\n  Arrays.asList(5, 6)\n);',
    setupCode: 'List<List<Integer>> nested = Arrays.asList(\n  Arrays.asList(1, 2),\n  Arrays.asList(3, 4),\n  Arrays.asList(5, 6)\n);',
    expected: [1, 2, 3, 4, 5, 6],
    sample: 'nested.stream().flatMap(List::stream).collect(Collectors.toList())',
    hints: ['Use flatMap() to flatten nested structures', 'flatMap transforms each element to a stream, then flattens all streams into one', 'List::stream is a method reference equivalent to list -> list.stream()', 'Common use: flatten nested collections, or map to multiple values per input'],
    validPatterns: [/\.stream\(\)/, /\.flatMap\(/, /\.collect\(|\.toList\(\)/],
    tags: ['Stream', 'flatMap', 'nested', 'advanced'],
  },

  {
    id: 'java-stream-019',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'MapToInt and Sum',
    text: 'Calculate the sum of string lengths using mapToInt',
    setup: 'List<String> words = Arrays.asList("hello", "world", "java");',
    setupCode: 'List<String> words = Arrays.asList("hello", "world", "java");',
    expected: 14,
    sample: 'words.stream().mapToInt(String::length).sum()',
    hints: ['Use mapToInt() for primitive int stream', 'IntStream has sum() method'],
    validPatterns: [/\.stream\(\)/, /\.mapToInt\(/, /\.sum\(\)/],
    tags: ['Stream', 'mapToInt', 'IntStream'],
  },

  {
    id: 'java-stream-020',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Filter and Map Chain',
    text: 'Get the squares of even numbers only',
    setup: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6);',
    setupCode: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6);',
    expected: [4, 16, 36],
    sample: 'nums.stream().filter(n -> n % 2 == 0).map(n -> n * n).collect(Collectors.toList())',
    hints: ['Chain filter() then map()', 'Filter first to select even, then square'],
    validPatterns: [/\.stream\(\)/, /\.filter\(/, /\.map\(/, /\.collect\(/],
    tags: ['Stream', 'filter', 'map', 'chaining'],
  },

  // ============================================================
  // String Methods (10+ problems)
  // ============================================================

  {
    id: 'java-string-001',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'String Length',
    text: 'Get the length of the string',
    setup: 'String str = "Hello World";',
    setupCode: 'String str = "Hello World";',
    expected: 11,
    sample: 'str.length() // returns 11',
    hints: ['Use length() method', 'Includes spaces in the count'],
    validPatterns: [/\.length\(\)/],
    tags: ['String', 'length', 'basics'],
  },

  {
    id: 'java-string-002',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Character at Index',
    text: 'Get the character at index 4',
    setup: 'String str = "Hello World";',
    setupCode: 'String str = "Hello World";',
    expected: 'o',
    sample: 'str.charAt(4) // returns \'o\'',
    hints: ['Use charAt(index)', 'Indices start at 0'],
    validPatterns: [/\.charAt\(\s*4\s*\)/],
    tags: ['String', 'charAt', 'access'],
  },

  {
    id: 'java-string-003',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Substring Extraction',
    text: 'Extract substring from index 0 to 5 (exclusive)',
    setup: 'String str = "Hello World";',
    setupCode: 'String str = "Hello World";',
    expected: 'Hello',
    sample: 'str.substring(0, 5) // returns "Hello"',
    hints: ['Use substring(beginIndex, endIndex)', 'endIndex is exclusive'],
    validPatterns: [/\.substring\(\s*0\s*,\s*5\s*\)/],
    tags: ['String', 'substring', 'extraction'],
  },

  {
    id: 'java-string-004',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Find Index of Substring',
    text: 'Find the index of "World" in the string',
    setup: 'String str = "Hello World";',
    setupCode: 'String str = "Hello World";',
    expected: 6,
    sample: 'str.indexOf("World") // returns 6',
    hints: ['Use indexOf(substring)', 'Returns -1 if not found'],
    validPatterns: [/\.indexOf\(\s*"World"\s*\)/],
    tags: ['String', 'indexOf', 'search'],
  },

  {
    id: 'java-string-005',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Last Index Of',
    text: 'Find the last index of the character "o"',
    setup: 'String str = "Hello World";',
    setupCode: 'String str = "Hello World";',
    expected: 7,
    sample: 'str.lastIndexOf("o") // returns 7',
    hints: ['Use lastIndexOf()', 'Returns the index of the last occurrence'],
    validPatterns: [/\.lastIndexOf\(\s*"o"\s*\)/],
    tags: ['String', 'lastIndexOf', 'search'],
  },

  {
    id: 'java-string-006',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Split String',
    text: 'Split the string by comma into an array',
    setup: 'String str = "apple,banana,cherry";',
    setupCode: 'String str = "apple,banana,cherry";',
    expected: ['apple', 'banana', 'cherry'],
    sample: 'str.split(",") // returns ["apple", "banana", "cherry"]',
    hints: ['Use split(regex)', 'Returns a String array'],
    validPatterns: [/\.split\(\s*","\s*\)/],
    tags: ['String', 'split', 'parsing'],
  },

  {
    id: 'java-string-007',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Join Strings',
    text: 'Join the array elements with " - " separator',
    setup: 'String[] words = {"apple", "banana", "cherry"};',
    setupCode: 'String[] words = {"apple", "banana", "cherry"};',
    expected: 'apple - banana - cherry',
    sample: 'String.join(" - ", words) // returns "apple - banana - cherry"',
    hints: ['Use String.join(delimiter, elements)', 'First argument is the delimiter'],
    validPatterns: [/String\.join\(/],
    tags: ['String', 'join', 'concatenation'],
  },

  {
    id: 'java-string-008',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Convert to Lowercase',
    text: 'Convert the string to lowercase',
    setup: 'String str = "HELLO WORLD";',
    setupCode: 'String str = "HELLO WORLD";',
    expected: 'hello world',
    sample: 'str.toLowerCase() // returns "hello world"',
    hints: ['Use toLowerCase()', 'Returns a new string'],
    validPatterns: [/\.toLowerCase\(\)/],
    tags: ['String', 'toLowerCase', 'case'],
  },

  {
    id: 'java-string-009',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Convert to Uppercase',
    text: 'Convert the string to uppercase',
    setup: 'String str = "hello world";',
    setupCode: 'String str = "hello world";',
    expected: 'HELLO WORLD',
    sample: 'str.toUpperCase() // returns "HELLO WORLD"',
    hints: ['Use toUpperCase()', 'Returns a new string'],
    validPatterns: [/\.toUpperCase\(\)/],
    tags: ['String', 'toUpperCase', 'case'],
  },

  {
    id: 'java-string-010',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Trim Whitespace',
    text: 'Remove leading and trailing whitespace',
    setup: 'String str = "   Hello World   ";',
    setupCode: 'String str = "   Hello World   ";',
    expected: 'Hello World',
    sample: 'str.trim() // returns "Hello World"',
    hints: ['Use trim() to remove leading and trailing whitespace', 'Java 11+: Use strip() which handles Unicode whitespace better', 'stripLeading() and stripTrailing() remove whitespace from one side only'],
    validPatterns: [/\.trim\(\)|\.strip\(\)/],
    tags: ['String', 'trim', 'whitespace'],
  },

  {
    id: 'java-string-011',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Replace Characters',
    text: 'Replace all spaces with underscores',
    setup: 'String str = "Hello World Java";',
    setupCode: 'String str = "Hello World Java";',
    expected: 'Hello_World_Java',
    sample: 'str.replace(" ", "_") // returns "Hello_World_Java"',
    hints: ['Use replace(oldChar, newChar)', 'Replaces all occurrences'],
    validPatterns: [/\.replace\(\s*" "\s*,\s*"_"\s*\)/],
    tags: ['String', 'replace', 'substitution'],
  },

  {
    id: 'java-string-012',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Replace All with Regex',
    text: 'Remove all digits from the string using regex',
    setup: 'String str = "abc123def456";',
    setupCode: 'String str = "abc123def456";',
    expected: 'abcdef',
    sample: 'str.replaceAll("\\\\d", "") // returns "abcdef"',
    hints: ['Use replaceAll(regex, replacement)', 'In Java, write "\\\\d" to match any digit (the double backslash escapes to \\d in the regex)'],
    validPatterns: [/\.replaceAll\(/],
    tags: ['String', 'replaceAll', 'regex'],
  },

  {
    id: 'java-string-013',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Check Starts With',
    text: 'Check if the string starts with "Hello"',
    setup: 'String str = "Hello World";',
    setupCode: 'String str = "Hello World";',
    expected: true,
    sample: 'str.startsWith("Hello") // returns true',
    hints: ['Use startsWith(prefix)', 'Case sensitive'],
    validPatterns: [/\.startsWith\(\s*"Hello"\s*\)/],
    tags: ['String', 'startsWith', 'validation'],
  },

  {
    id: 'java-string-014',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Check Ends With',
    text: 'Check if the string ends with "World"',
    setup: 'String str = "Hello World";',
    setupCode: 'String str = "Hello World";',
    expected: true,
    sample: 'str.endsWith("World") // returns true',
    hints: ['Use endsWith(suffix)', 'Case sensitive'],
    validPatterns: [/\.endsWith\(\s*"World"\s*\)/],
    tags: ['String', 'endsWith', 'validation'],
  },

  {
    id: 'java-string-015',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Check Contains Substring',
    text: 'Check if the string contains "World"',
    setup: 'String str = "Hello World";',
    setupCode: 'String str = "Hello World";',
    expected: true,
    sample: 'str.contains("World") // returns true',
    hints: ['Use contains(sequence)', 'Case sensitive'],
    validPatterns: [/\.contains\(\s*"World"\s*\)/],
    tags: ['String', 'contains', 'search'],
  },

  {
    id: 'java-string-016',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'String Equality',
    text: 'Check if two strings are equal',
    setup: 'String str1 = "hello";\nString str2 = "hello";',
    setupCode: 'String str1 = "hello";\nString str2 = "hello";',
    expected: true,
    sample: 'str1.equals(str2) // returns true',
    hints: ['Use equals() for content comparison', 'NEVER use == for string content comparison (== checks reference equality)', 'Objects.equals(str1, str2) is null-safe alternative'],
    validPatterns: [/\.equals\(|Objects\.equals\(/],
    tags: ['String', 'equals', 'comparison', 'best-practice'],
  },

  {
    id: 'java-string-017',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'String Equality Ignore Case',
    text: 'Check if two strings are equal ignoring case',
    setup: 'String str1 = "Hello";\nString str2 = "hello";',
    setupCode: 'String str1 = "Hello";\nString str2 = "hello";',
    expected: true,
    sample: 'str1.equalsIgnoreCase(str2) // returns true',
    hints: ['Use equalsIgnoreCase()', 'Ignores uppercase/lowercase differences'],
    validPatterns: [/\.equalsIgnoreCase\(/],
    tags: ['String', 'equalsIgnoreCase', 'comparison'],
  },

  // ============================================================
  // Array Operations (5+ problems)
  // ============================================================

  {
    id: 'java-array-001',
    category: 'Arrays Utility',
    difficulty: 'easy',
    title: 'Array Length',
    text: 'Get the length of the array',
    setup: 'int[] nums = {1, 2, 3, 4, 5};',
    setupCode: 'int[] nums = {1, 2, 3, 4, 5};',
    expected: 5,
    sample: 'nums.length // returns 5',
    hints: ['Use .length property (no parentheses)', 'Arrays use length, not length()'],
    validPatterns: [/\.length(?!\()/],
    tags: ['Array', 'length', 'basics'],
  },

  {
    id: 'java-array-002',
    category: 'Arrays Utility',
    difficulty: 'medium',
    title: 'Sort Array',
    text: 'Sort the array in ascending order',
    setup: 'int[] nums = {5, 2, 8, 1, 9};',
    setupCode: 'int[] nums = {5, 2, 8, 1, 9};',
    expected: [1, 2, 5, 8, 9],
    sample: 'Arrays.sort(nums); // nums is now {1, 2, 5, 8, 9}',
    hints: ['Use Arrays.sort()', 'Sorts in place'],
    validPatterns: [/Arrays\.sort\(\s*nums\s*\)/],
    tags: ['Arrays', 'sort', 'ordering'],
  },

  {
    id: 'java-array-003',
    category: 'Arrays Utility',
    difficulty: 'medium',
    title: 'Array to List',
    text: 'Convert the array to a List',
    setup: 'String[] arr = {"apple", "banana", "cherry"};',
    setupCode: 'String[] arr = {"apple", "banana", "cherry"};',
    expected: ['apple', 'banana', 'cherry'],
    sample: 'Arrays.asList(arr) // returns List containing "apple", "banana", "cherry"',
    hints: ['Use Arrays.asList()', 'Returns a fixed-size list'],
    validPatterns: [/Arrays\.asList\(\s*arr\s*\)/],
    tags: ['Arrays', 'asList', 'conversion'],
  },

  {
    id: 'java-array-004',
    category: 'Arrays Utility',
    difficulty: 'medium',
    title: 'Array to Stream and Sum',
    text: 'Convert the array to a Stream and calculate the sum',
    setup: 'int[] nums = {1, 2, 3, 4, 5};',
    setupCode: 'int[] nums = {1, 2, 3, 4, 5};',
    expected: 15,
    sample: 'Arrays.stream(nums).sum() // returns 15',
    hints: ['Use Arrays.stream() to create an IntStream', 'IntStream has sum(), average(), min(), max() methods', 'For primitive arrays, Arrays.stream() returns primitive streams (IntStream, LongStream, DoubleStream)'],
    validPatterns: [/Arrays\.stream\(\s*nums\s*\)/],
    tags: ['Arrays', 'stream', 'IntStream', 'conversion'],
  },

  {
    id: 'java-array-005',
    category: 'Arrays Utility',
    difficulty: 'medium',
    title: 'Binary Search',
    text: 'Find the index of 5 in the sorted array using binary search',
    setup: 'int[] nums = {1, 2, 3, 4, 5, 6, 7};',
    setupCode: 'int[] nums = {1, 2, 3, 4, 5, 6, 7};',
    expected: 4,
    sample: 'Arrays.binarySearch(nums, 5) // returns 4',
    hints: ['Use Arrays.binarySearch()', 'Array must be sorted first'],
    validPatterns: [/Arrays\.binarySearch\(\s*nums\s*,\s*5\s*\)/],
    tags: ['Arrays', 'binarySearch', 'search'],
  },

  {
    id: 'java-array-006',
    category: 'Arrays Utility',
    difficulty: 'easy',
    title: 'Fill Array',
    text: 'Fill the entire array with the value 0',
    setup: 'int[] nums = {1, 2, 3, 4, 5};',
    setupCode: 'int[] nums = {1, 2, 3, 4, 5};',
    expected: [0, 0, 0, 0, 0],
    sample: 'Arrays.fill(nums, 0); // nums is now {0, 0, 0, 0, 0}',
    hints: ['Use Arrays.fill()', 'Fills all elements with the value'],
    validPatterns: [/Arrays\.fill\(\s*nums\s*,\s*0\s*\)/],
    tags: ['Arrays', 'fill', 'initialization'],
  },

  {
    id: 'java-array-007',
    category: 'Arrays Utility',
    difficulty: 'easy',
    title: 'Copy Array',
    text: 'Create a copy of the first 3 elements',
    setup: 'int[] nums = {1, 2, 3, 4, 5};',
    setupCode: 'int[] nums = {1, 2, 3, 4, 5};',
    expected: [1, 2, 3],
    sample: 'Arrays.copyOf(nums, 3) // returns {1, 2, 3}',
    hints: ['Use Arrays.copyOf()', 'Second argument is the new length'],
    validPatterns: [/Arrays\.copyOf\(\s*nums\s*,\s*3\s*\)/],
    tags: ['Arrays', 'copyOf', 'copy'],
  },

  {
    id: 'java-array-008',
    category: 'Arrays Utility',
    difficulty: 'medium',
    title: 'Array Equality',
    text: 'Check if two arrays have the same elements',
    setup: 'int[] arr1 = {1, 2, 3};\nint[] arr2 = {1, 2, 3};',
    setupCode: 'int[] arr1 = {1, 2, 3};\nint[] arr2 = {1, 2, 3};',
    expected: true,
    sample: 'Arrays.equals(arr1, arr2) // returns true',
    hints: ['Use Arrays.equals()', 'Compares element by element'],
    validPatterns: [/Arrays\.equals\(/],
    tags: ['Arrays', 'equals', 'comparison'],
  },

  // ============================================================
  // Additional Stream API Problems
  // ============================================================

  {
    id: 'java-stream-021',
    category: 'Stream API',
    difficulty: 'hard',
    title: 'Group By with Collectors',
    text: 'Group strings by their length',
    setup: 'List<String> words = Arrays.asList("cat", "dog", "elephant", "rat", "giraffe");',
    setupCode: 'List<String> words = Arrays.asList("cat", "dog", "elephant", "rat", "giraffe");',
    expected: { 3: ['cat', 'dog', 'rat'], 7: ['giraffe'], 8: ['elephant'] },
    sample: 'words.stream().collect(Collectors.groupingBy(String::length))',
    hints: ['Use Collectors.groupingBy(classifier)', 'Returns Map<K, List<T>> where K is the classifier result', 'String::length is a method reference returning the string length'],
    validPatterns: [/\.stream\(\)/, /\.collect\(/, /groupingBy/],
    tags: ['Stream', 'Collectors', 'groupingBy', 'Map'],
  },

  {
    id: 'java-stream-022',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Join Strings with Collectors',
    text: 'Join all strings with comma separator',
    setup: 'List<String> words = Arrays.asList("apple", "banana", "cherry");',
    setupCode: 'List<String> words = Arrays.asList("apple", "banana", "cherry");',
    expected: 'apple,banana,cherry',
    sample: 'words.stream().collect(Collectors.joining(","))',
    hints: ['Use Collectors.joining()', 'Pass the delimiter as argument'],
    validPatterns: [/\.stream\(\)/, /\.collect\(/, /joining/],
    tags: ['Stream', 'Collectors', 'joining'],
  },

  {
    id: 'java-stream-023',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Average with IntStream',
    text: 'Calculate the average of numbers',
    setup: 'List<Integer> nums = Arrays.asList(10, 20, 30, 40, 50);',
    setupCode: 'List<Integer> nums = Arrays.asList(10, 20, 30, 40, 50);',
    expected: 30.0,
    sample: 'nums.stream().mapToInt(Integer::intValue).average().orElse(0)',
    hints: ['Use mapToInt() then average()', 'average() returns OptionalDouble'],
    validPatterns: [/\.stream\(\)/, /\.mapToInt\(/, /\.average\(\)/],
    tags: ['Stream', 'IntStream', 'average'],
  },

  {
    id: 'java-stream-024',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Limit Stream Results',
    text: 'Get only the first 3 elements from the stream',
    setup: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6, 7);',
    setupCode: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6, 7);',
    expected: [1, 2, 3],
    sample: 'nums.stream().limit(3).collect(Collectors.toList())',
    hints: ['Use limit(n) to restrict the stream size', 'limit() is a short-circuiting intermediate operation'],
    validPatterns: [/\.stream\(\)/, /\.limit\(\s*3\s*\)/, /\.collect\(/],
    tags: ['Stream', 'limit', 'truncation'],
  },

  {
    id: 'java-stream-025',
    category: 'Stream API',
    difficulty: 'medium',
    title: 'Skip Elements',
    text: 'Skip the first 2 elements and get the rest',
    setup: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);',
    setupCode: 'List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5);',
    expected: [3, 4, 5],
    sample: 'nums.stream().skip(2).collect(Collectors.toList())',
    hints: ['Use skip(n) to skip elements', 'skip() is a stateful intermediate operation'],
    validPatterns: [/\.stream\(\)/, /\.skip\(\s*2\s*\)/, /\.collect\(/],
    tags: ['Stream', 'skip', 'pagination'],
  },

  // ============================================================
  // Additional ArrayList Problems
  // ============================================================

  {
    id: 'java-list-016',
    category: 'ArrayList Methods',
    difficulty: 'medium',
    title: 'Last Index Of Element',
    text: 'Find the last index of the number 2 in the list',
    setup: 'List<Integer> nums = Arrays.asList(1, 2, 3, 2, 4, 2, 5);',
    setupCode: 'List<Integer> nums = Arrays.asList(1, 2, 3, 2, 4, 2, 5);',
    expected: 5,
    sample: 'nums.lastIndexOf(2) // returns 5',
    hints: ['Use lastIndexOf()', 'Returns the index of the last occurrence'],
    validPatterns: [/\.lastIndexOf\(\s*2\s*\)/],
    tags: ['ArrayList', 'lastIndexOf', 'search'],
  },

  {
    id: 'java-list-017',
    category: 'Collections Utility',
    difficulty: 'medium',
    title: 'Find Maximum',
    text: 'Find the maximum element in the list',
    setup: 'List<Integer> nums = Arrays.asList(3, 7, 2, 9, 5);',
    setupCode: 'List<Integer> nums = Arrays.asList(3, 7, 2, 9, 5);',
    expected: 9,
    sample: 'Collections.max(nums) // returns 9',
    hints: ['Use Collections.max()', 'Works with Comparable elements'],
    validPatterns: [/Collections\.max\(\s*nums\s*\)/],
    tags: ['Collections', 'max', 'aggregation'],
  },

  {
    id: 'java-list-018',
    category: 'Collections Utility',
    difficulty: 'medium',
    title: 'Find Minimum',
    text: 'Find the minimum element in the list',
    setup: 'List<Integer> nums = Arrays.asList(3, 7, 2, 9, 5);',
    setupCode: 'List<Integer> nums = Arrays.asList(3, 7, 2, 9, 5);',
    expected: 2,
    sample: 'Collections.min(nums) // returns 2',
    hints: ['Use Collections.min()', 'Works with Comparable elements'],
    validPatterns: [/Collections\.min\(\s*nums\s*\)/],
    tags: ['Collections', 'min', 'aggregation'],
  },

  {
    id: 'java-list-019',
    category: 'Collections Utility',
    difficulty: 'medium',
    title: 'Shuffle List',
    text: 'Randomly shuffle the elements in the list (use Collections.shuffle)',
    setup: 'List<Integer> nums = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5));',
    setupCode: 'List<Integer> nums = new ArrayList<>(Arrays.asList(1, 2, 3, 4, 5));',
    expected: null,
    sample: 'Collections.shuffle(nums); // nums is now in random order',
    hints: ['Use Collections.shuffle(list)', 'Modifies the list in place using a default Random source', 'For reproducible shuffles, use Collections.shuffle(list, random) with a seeded Random'],
    validPatterns: [/Collections\.shuffle\(\s*nums/],
    tags: ['Collections', 'shuffle', 'random', 'in-place'],
  },

  {
    id: 'java-list-020',
    category: 'Collections Utility',
    difficulty: 'medium',
    title: 'Frequency Count',
    text: 'Count how many times the number 3 appears in the list',
    setup: 'List<Integer> nums = Arrays.asList(1, 3, 2, 3, 4, 3, 5);',
    setupCode: 'List<Integer> nums = Arrays.asList(1, 3, 2, 3, 4, 3, 5);',
    expected: 3,
    sample: 'Collections.frequency(nums, 3) // returns 3',
    hints: ['Use Collections.frequency()', 'Counts occurrences of specified element'],
    validPatterns: [/Collections\.frequency\(\s*nums\s*,\s*3\s*\)/],
    tags: ['Collections', 'frequency', 'counting'],
  },
];

export default javaProblems;
