/**
 * Lua coding drill problems
 * Covers Table Operations, String Functions, Math Functions, Iterator Functions, and Pattern Matching
 */

import type { Problem } from '../types';

export const luaProblems: Problem[] = [
  // ============================================================
  // Table Operations (11 problems: 4 easy, 4 medium, 3 hard)
  // ============================================================

  // table.insert
  {
    id: 'lua-table-001',
    category: 'Table Operations',
    difficulty: 'easy',
    title: 'Insert Element at End',
    text: 'Use `table.insert` to add the number 4 to the end of the table.',
    setup: 'local numbers = {1, 2, 3}',
    setupCode: 'local numbers = {1, 2, 3}',
    expected: [1, 2, 3, 4],
    sample: 'table.insert(numbers, 4); return numbers',
    hints: ['table.insert(t, value) adds to end', 'The table is modified in place'],
    validPatterns: [/table\.insert\s*\(\s*numbers\s*,\s*4\s*\)/],
    tags: ['table.insert', 'append'],
  },
  {
    id: 'lua-table-002',
    category: 'Table Operations',
    difficulty: 'medium',
    title: 'Insert Element at Position',
    text: 'Use `table.insert` to add the number 10 at index 2.',
    setup: 'local numbers = {1, 2, 3}',
    setupCode: 'local numbers = {1, 2, 3}',
    expected: [1, 10, 2, 3],
    sample: 'table.insert(numbers, 2, 10); return numbers',
    hints: ['table.insert(t, pos, value) inserts at position', 'Elements shift to make room'],
    validPatterns: [/table\.insert\s*\(\s*numbers\s*,\s*2\s*,\s*10\s*\)/],
    tags: ['table.insert', 'position'],
  },

  // table.remove
  {
    id: 'lua-table-003',
    category: 'Table Operations',
    difficulty: 'easy',
    title: 'Remove Last Element',
    text: 'Use `table.remove` to remove and return the last element from the table.',
    setup: 'local numbers = {1, 2, 3, 4}',
    setupCode: 'local numbers = {1, 2, 3, 4}',
    expected: 4,
    sample: 'return table.remove(numbers)',
    hints: ['table.remove(t) removes the last element', 'Returns the removed element'],
    validPatterns: [/table\.remove\s*\(\s*numbers\s*\)/],
    tags: ['table.remove', 'pop'],
  },
  {
    id: 'lua-table-004',
    category: 'Table Operations',
    difficulty: 'medium',
    title: 'Remove Element at Position',
    text: 'Use `table.remove` to remove and return the element at index 2.',
    setup: 'local numbers = {10, 20, 30, 40}',
    setupCode: 'local numbers = {10, 20, 30, 40}',
    expected: 20,
    sample: 'return table.remove(numbers, 2)',
    hints: ['table.remove(t, pos) removes at position', 'Elements shift after removal'],
    validPatterns: [/table\.remove\s*\(\s*numbers\s*,\s*2\s*\)/],
    tags: ['table.remove', 'position'],
  },

  // table.sort
  {
    id: 'lua-table-005',
    category: 'Table Operations',
    difficulty: 'easy',
    title: 'Sort Table Ascending',
    text: 'Use `table.sort` to sort the numbers in ascending order.',
    setup: 'local numbers = {5, 2, 8, 1, 9}',
    setupCode: 'local numbers = {5, 2, 8, 1, 9}',
    expected: [1, 2, 5, 8, 9],
    sample: 'table.sort(numbers); return numbers',
    hints: ['table.sort(t) sorts in ascending order', 'The table is sorted in place'],
    validPatterns: [/table\.sort\s*\(\s*numbers\s*\)/],
    tags: ['table.sort', 'ascending'],
  },
  {
    id: 'lua-table-006',
    category: 'Table Operations',
    difficulty: 'medium',
    title: 'Sort Table Descending',
    text: 'Use `table.sort` with a comparison function to sort numbers in descending order.',
    setup: 'local numbers = {5, 2, 8, 1, 9}',
    setupCode: 'local numbers = {5, 2, 8, 1, 9}',
    expected: [9, 8, 5, 2, 1],
    sample: 'table.sort(numbers, function(a, b) return a > b end); return numbers',
    hints: ['table.sort(t, comp) uses custom comparison', 'Return true if a should come before b'],
    validPatterns: [/table\.sort\s*\(\s*numbers\s*,\s*function\s*\(\s*\w+\s*,\s*\w+\s*\)\s*return\s+\w+\s*>\s*\w+/],
    tags: ['table.sort', 'descending', 'comparator'],
  },
  {
    id: 'lua-table-007',
    category: 'Table Operations',
    difficulty: 'hard',
    title: 'Sort Strings by Length',
    text: 'Use `table.sort` to sort words by their length (shortest first).',
    setup: 'local words = {"apple", "hi", "banana", "cat"}',
    setupCode: 'local words = {"apple", "hi", "banana", "cat"}',
    expected: ['hi', 'cat', 'apple', 'banana'],
    sample: 'table.sort(words, function(a, b) return #a < #b end); return words',
    hints: ['Use # operator to get string length', 'Compare lengths in the function'],
    validPatterns: [/table\.sort\s*\(\s*words\s*,\s*function\s*\(\s*\w+\s*,\s*\w+\s*\)\s*return\s+#\w+\s*<\s*#\w+/],
    tags: ['table.sort', 'length', 'strings'],
  },

  // table.concat
  {
    id: 'lua-table-008',
    category: 'Table Operations',
    difficulty: 'easy',
    title: 'Concatenate Table Elements',
    text: 'Use `table.concat` to join the words with a space separator.',
    setup: 'local words = {"hello", "world", "lua"}',
    setupCode: 'local words = {"hello", "world", "lua"}',
    expected: 'hello world lua',
    sample: 'return table.concat(words, " ")',
    hints: ['table.concat(t, sep) joins elements', 'Second argument is the separator'],
    validPatterns: [/table\.concat\s*\(\s*words\s*,\s*["'] ["']\s*\)/],
    tags: ['table.concat', 'join'],
  },
  {
    id: 'lua-table-009',
    category: 'Table Operations',
    difficulty: 'medium',
    title: 'Concatenate Range',
    text: 'Use `table.concat` to join only elements from index 2 to 4.',
    setup: 'local letters = {"a", "b", "c", "d", "e"}',
    setupCode: 'local letters = {"a", "b", "c", "d", "e"}',
    expected: 'b-c-d',
    sample: 'return table.concat(letters, "-", 2, 4)',
    hints: ['table.concat(t, sep, i, j) joins range', 'i and j are start and end indices'],
    validPatterns: [/table\.concat\s*\(\s*letters\s*,\s*["']-["']\s*,\s*2\s*,\s*4\s*\)/],
    tags: ['table.concat', 'range'],
  },

  // # length operator
  {
    id: 'lua-table-010',
    category: 'Table Operations',
    difficulty: 'hard',
    title: 'Build Table from Scratch',
    text: 'Create a table containing numbers 1 to 5 using a loop and table.insert.',
    setup: 'local result = {}',
    setupCode: 'local result = {}',
    expected: [1, 2, 3, 4, 5],
    sample: 'for i = 1, 5 do table.insert(result, i) end; return result',
    hints: ['Use a for loop from 1 to 5', 'Insert each number into the table'],
    validPatterns: [/for\s+\w+\s*=\s*1\s*,\s*5/, /table\.insert/],
    tags: ['table.insert', 'loop', 'build'],
  },
  {
    id: 'lua-table-011',
    category: 'Table Operations',
    difficulty: 'hard',
    title: 'Reverse Table In Place',
    text: 'Reverse the table in place using table operations.',
    setup: 'local numbers = {1, 2, 3, 4, 5}',
    setupCode: 'local numbers = {1, 2, 3, 4, 5}',
    expected: [5, 4, 3, 2, 1],
    sample: 'for i = 1, math.floor(#numbers / 2) do numbers[i], numbers[#numbers - i + 1] = numbers[#numbers - i + 1], numbers[i] end; return numbers',
    hints: ['Swap elements from ends toward middle', 'Use multiple assignment for swapping'],
    validPatterns: [/numbers\[.*\]\s*,\s*numbers\[.*\]\s*=\s*numbers\[.*\]\s*,\s*numbers\[.*\]/],
    tags: ['table', 'reverse', 'swap'],
  },

  // ============================================================
  // String Functions (15 problems: 6 easy, 6 medium, 3 hard)
  // ============================================================

  // string.len
  {
    id: 'lua-string-001',
    category: 'String Functions',
    difficulty: 'easy',
    title: 'Get String Length',
    text: 'Use `string.len` to get the length of the string.',
    setup: 'local text = "hello world"',
    setupCode: 'local text = "hello world"',
    expected: 11,
    sample: 'return string.len(text)',
    hints: ['string.len returns byte length', 'Can also use #text'],
    validPatterns: [/string\.len\s*\(\s*text\s*\)/, /#text/],
    tags: ['string.len', 'length'],
  },

  // string.sub
  {
    id: 'lua-string-002',
    category: 'String Functions',
    difficulty: 'easy',
    title: 'Extract Substring',
    text: 'Use `string.sub` to extract characters from index 1 to 5.',
    setup: 'local text = "hello world"',
    setupCode: 'local text = "hello world"',
    expected: 'hello',
    sample: 'return string.sub(text, 1, 5)',
    hints: ['string.sub(s, i, j) extracts substring', 'Lua strings are 1-indexed'],
    validPatterns: [/string\.sub\s*\(\s*text\s*,\s*1\s*,\s*5\s*\)/, /text:sub\s*\(\s*1\s*,\s*5\s*\)/],
    tags: ['string.sub', 'substring'],
  },
  {
    id: 'lua-string-003',
    category: 'String Functions',
    difficulty: 'medium',
    title: 'Get Last Characters',
    text: 'Use `string.sub` with negative index to get the last 3 characters.',
    setup: 'local text = "programming"',
    setupCode: 'local text = "programming"',
    expected: 'ing',
    sample: 'return string.sub(text, -3)',
    hints: ['Negative indices count from end', '-3 means 3rd from last'],
    validPatterns: [/string\.sub\s*\(\s*text\s*,\s*-3\s*\)/, /text:sub\s*\(\s*-3\s*\)/],
    tags: ['string.sub', 'negative index'],
  },

  // string.upper / string.lower
  {
    id: 'lua-string-004',
    category: 'String Functions',
    difficulty: 'easy',
    title: 'Convert to Uppercase',
    text: 'Use `string.upper` to convert the string to uppercase.',
    setup: 'local text = "hello"',
    setupCode: 'local text = "hello"',
    expected: 'HELLO',
    sample: 'return string.upper(text)',
    hints: ['string.upper converts all to uppercase', 'Can use text:upper() method syntax'],
    validPatterns: [/string\.upper\s*\(\s*text\s*\)/, /text:upper\s*\(\s*\)/],
    tags: ['string.upper', 'uppercase'],
  },
  {
    id: 'lua-string-005',
    category: 'String Functions',
    difficulty: 'easy',
    title: 'Convert to Lowercase',
    text: 'Use `string.lower` to convert the string to lowercase.',
    setup: 'local text = "HELLO WORLD"',
    setupCode: 'local text = "HELLO WORLD"',
    expected: 'hello world',
    sample: 'return string.lower(text)',
    hints: ['string.lower converts all to lowercase', 'Can use text:lower() method syntax'],
    validPatterns: [/string\.lower\s*\(\s*text\s*\)/, /text:lower\s*\(\s*\)/],
    tags: ['string.lower', 'lowercase'],
  },

  // string.find
  {
    id: 'lua-string-006',
    category: 'String Functions',
    difficulty: 'easy',
    title: 'Find Substring Position',
    text: 'Use `string.find` to find the starting position of "world".',
    setup: 'local text = "hello world"',
    setupCode: 'local text = "hello world"',
    expected: 7,
    sample: 'local start = string.find(text, "world"); return start',
    hints: ['string.find returns start and end positions', 'Returns nil if not found'],
    validPatterns: [/string\.find\s*\(\s*text\s*,\s*["']world["']\s*\)/, /text:find\s*\(\s*["']world["']\s*\)/],
    tags: ['string.find', 'search'],
  },
  {
    id: 'lua-string-007',
    category: 'String Functions',
    difficulty: 'medium',
    title: 'Find with Plain Text',
    text: 'Use `string.find` with plain text mode to find the literal ".".',
    setup: 'local text = "version 1.0.3"',
    setupCode: 'local text = "version 1.0.3"',
    expected: 10,
    sample: 'local start = string.find(text, ".", 1, true); return start',
    hints: ['Fourth argument enables plain text mode', 'Dot is a pattern character normally'],
    validPatterns: [/string\.find\s*\(\s*text\s*,\s*["']\.["']\s*,\s*\d+\s*,\s*true\s*\)/],
    tags: ['string.find', 'plain'],
  },

  // string.gsub
  {
    id: 'lua-string-008',
    category: 'String Functions',
    difficulty: 'medium',
    title: 'Replace All Occurrences',
    text: 'Use `string.gsub` to replace all spaces with underscores.',
    setup: 'local text = "hello world lua"',
    setupCode: 'local text = "hello world lua"',
    expected: 'hello_world_lua',
    sample: 'return (string.gsub(text, " ", "_"))',
    hints: ['string.gsub replaces all occurrences', 'Returns new string and count'],
    validPatterns: [/string\.gsub\s*\(\s*text\s*,\s*["'] ["']\s*,\s*["']_["']\s*\)/, /text:gsub\s*\(\s*["'] ["']\s*,\s*["']_["']\s*\)/],
    tags: ['string.gsub', 'replace'],
  },
  {
    id: 'lua-string-009',
    category: 'String Functions',
    difficulty: 'medium',
    title: 'Replace with Limit',
    text: 'Use `string.gsub` to replace only the first 2 occurrences of "a" with "X".',
    setup: 'local text = "banana"',
    setupCode: 'local text = "banana"',
    expected: 'bXnXna',
    sample: 'return (string.gsub(text, "a", "X", 2))',
    hints: ['Fourth argument limits replacements', 'gsub returns (result, count)'],
    validPatterns: [/string\.gsub\s*\(\s*text\s*,\s*["']a["']\s*,\s*["']X["']\s*,\s*2\s*\)/],
    tags: ['string.gsub', 'limit'],
  },

  // string.match
  {
    id: 'lua-string-010',
    category: 'String Functions',
    difficulty: 'medium',
    title: 'Extract First Match',
    text: 'Use `string.match` to extract the first number from the string.',
    setup: 'local text = "price: 42 dollars"',
    setupCode: 'local text = "price: 42 dollars"',
    expected: '42',
    sample: 'return string.match(text, "%d+")',
    hints: ['string.match returns captured text', '%d+ matches one or more digits'],
    validPatterns: [/string\.match\s*\(\s*text\s*,\s*["']%d\+["']\s*\)/, /text:match\s*\(\s*["']%d\+["']\s*\)/],
    tags: ['string.match', 'pattern'],
  },

  // string.format
  {
    id: 'lua-string-011',
    category: 'String Functions',
    difficulty: 'easy',
    title: 'Format String with Values',
    text: 'Use `string.format` to create "Name: Alice, Age: 25".',
    setup: 'local name = "Alice"\nlocal age = 25',
    setupCode: 'local name = "Alice"\nlocal age = 25',
    expected: 'Name: Alice, Age: 25',
    sample: 'return string.format("Name: %s, Age: %d", name, age)',
    hints: ['%s for strings, %d for integers', 'Similar to C printf format'],
    validPatterns: [/string\.format\s*\(\s*["']Name:\s*%s,\s*Age:\s*%d["']\s*,\s*name\s*,\s*age\s*\)/],
    tags: ['string.format', 'sprintf'],
  },
  {
    id: 'lua-string-012',
    category: 'String Functions',
    difficulty: 'medium',
    title: 'Format Floating Point',
    text: 'Use `string.format` to format the number with 2 decimal places.',
    setup: 'local pi = 3.14159265',
    setupCode: 'local pi = 3.14159265',
    expected: '3.14',
    sample: 'return string.format("%.2f", pi)',
    hints: ['%.2f formats with 2 decimal places', 'f is for floating point numbers'],
    validPatterns: [/string\.format\s*\(\s*["']%.2f["']\s*,\s*pi\s*\)/],
    tags: ['string.format', 'float'],
  },

  // string.rep
  {
    id: 'lua-string-013',
    category: 'String Functions',
    difficulty: 'hard',
    title: 'Build Separator Line',
    text: 'Use `string.rep` and `string.format` to create "---[TITLE]---".',
    setup: 'local title = "TITLE"',
    setupCode: 'local title = "TITLE"',
    expected: '---[TITLE]---',
    sample: 'return string.format("%s[%s]%s", string.rep("-", 3), title, string.rep("-", 3))',
    hints: ['Combine rep and format', 'rep creates repeated characters'],
    validPatterns: [/string\.rep\s*\(\s*["']-["']\s*,\s*3\s*\)/, /string\.format/],
    tags: ['string.rep', 'string.format'],
  },

  // string.reverse
  {
    id: 'lua-string-014',
    category: 'String Functions',
    difficulty: 'hard',
    title: 'Check Palindrome',
    text: 'Use `string.reverse` and `string.lower` to check if the word is a palindrome.',
    setup: 'local word = "Level"',
    setupCode: 'local word = "Level"',
    expected: true,
    sample: 'local lower = string.lower(word); return lower == string.reverse(lower)',
    hints: ['Convert to lowercase first', 'Compare with reversed version'],
    validPatterns: [/string\.reverse/, /string\.lower/],
    tags: ['string.reverse', 'string.lower', 'palindrome'],
  },
  {
    id: 'lua-string-015',
    category: 'String Functions',
    difficulty: 'hard',
    title: 'Extract File Extension',
    text: 'Use string functions to extract the file extension from the filename.',
    setup: 'local filename = "document.txt"',
    setupCode: 'local filename = "document.txt"',
    expected: 'txt',
    sample: 'local dot = string.find(filename, ".", 1, true); return string.sub(filename, dot + 1)',
    hints: ['Find the dot position first', 'Extract from dot+1 to end'],
    validPatterns: [/string\.find/, /string\.sub/],
    tags: ['string.find', 'string.sub', 'extension'],
  },

  // ============================================================
  // Math Functions (10 problems: 5 easy, 4 medium, 1 hard)
  // ============================================================

  // math.abs
  {
    id: 'lua-math-001',
    category: 'Math Functions',
    difficulty: 'easy',
    title: 'Absolute Value',
    text: 'Use `math.abs` to get the absolute value of the number.',
    setup: 'local num = -42',
    setupCode: 'local num = -42',
    expected: 42,
    sample: 'return math.abs(num)',
    hints: ['math.abs returns absolute value', 'Removes the negative sign'],
    validPatterns: [/math\.abs\s*\(\s*num\s*\)/],
    tags: ['math.abs', 'absolute'],
  },

  // math.ceil / math.floor
  {
    id: 'lua-math-002',
    category: 'Math Functions',
    difficulty: 'easy',
    title: 'Round Up',
    text: 'Use `math.ceil` to round the number up to the nearest integer.',
    setup: 'local num = 4.3',
    setupCode: 'local num = 4.3',
    expected: 5,
    sample: 'return math.ceil(num)',
    hints: ['math.ceil rounds up to ceiling', 'Always rounds toward positive infinity'],
    validPatterns: [/math\.ceil\s*\(\s*num\s*\)/],
    tags: ['math.ceil', 'round'],
  },
  {
    id: 'lua-math-003',
    category: 'Math Functions',
    difficulty: 'easy',
    title: 'Round Down',
    text: 'Use `math.floor` to round the number down to the nearest integer.',
    setup: 'local num = 4.7',
    setupCode: 'local num = 4.7',
    expected: 4,
    sample: 'return math.floor(num)',
    hints: ['math.floor rounds down to floor', 'Always rounds toward negative infinity'],
    validPatterns: [/math\.floor\s*\(\s*num\s*\)/],
    tags: ['math.floor', 'round'],
  },

  // math.max / math.min
  {
    id: 'lua-math-004',
    category: 'Math Functions',
    difficulty: 'easy',
    title: 'Find Maximum',
    text: 'Use `math.max` to find the largest of the three numbers.',
    setup: 'local a, b, c = 10, 25, 15',
    setupCode: 'local a, b, c = 10, 25, 15',
    expected: 25,
    sample: 'return math.max(a, b, c)',
    hints: ['math.max takes multiple arguments', 'Returns the largest value'],
    validPatterns: [/math\.max\s*\(\s*a\s*,\s*b\s*,\s*c\s*\)/],
    tags: ['math.max', 'maximum'],
  },
  {
    id: 'lua-math-005',
    category: 'Math Functions',
    difficulty: 'easy',
    title: 'Find Minimum',
    text: 'Use `math.min` to find the smallest of the three numbers.',
    setup: 'local a, b, c = 10, 25, 15',
    setupCode: 'local a, b, c = 10, 25, 15',
    expected: 10,
    sample: 'return math.min(a, b, c)',
    hints: ['math.min takes multiple arguments', 'Returns the smallest value'],
    validPatterns: [/math\.min\s*\(\s*a\s*,\s*b\s*,\s*c\s*\)/],
    tags: ['math.min', 'minimum'],
  },

  // math.sqrt
  {
    id: 'lua-math-006',
    category: 'Math Functions',
    difficulty: 'medium',
    title: 'Square Root',
    text: 'Use `math.sqrt` to calculate the square root of the number.',
    setup: 'local num = 64',
    setupCode: 'local num = 64',
    expected: 8,
    sample: 'return math.sqrt(num)',
    hints: ['math.sqrt returns square root', 'Equivalent to num^0.5'],
    validPatterns: [/math\.sqrt\s*\(\s*num\s*\)/, /num\s*\^\s*0\.5/],
    tags: ['math.sqrt', 'root'],
  },

  // math.random
  {
    id: 'lua-math-007',
    category: 'Math Functions',
    difficulty: 'medium',
    title: 'Random Integer in Range',
    text: 'Use `math.random` to generate a random integer between 1 and 10 (inclusive).',
    setup: 'math.randomseed(os.time())',
    setupCode: 'math.randomseed(os.time())',
    expected: 'random 1-10',
    sample: 'return math.random(1, 10)',
    hints: ['math.random(m, n) returns integer in [m, n]', 'Both bounds are inclusive'],
    validPatterns: [/math\.random\s*\(\s*1\s*,\s*10\s*\)/],
    tags: ['math.random', 'random'],
  },

  // math.modf
  {
    id: 'lua-math-008',
    category: 'Math Functions',
    difficulty: 'medium',
    title: 'Get Integer Part',
    text: 'Use `math.modf` to get only the integer part of the number.',
    setup: 'local num = 7.89',
    setupCode: 'local num = 7.89',
    expected: 7,
    sample: 'local int_part = math.modf(num); return int_part',
    hints: ['math.modf returns integer and fractional parts', 'First return value is integer part'],
    validPatterns: [/math\.modf\s*\(\s*num\s*\)/],
    tags: ['math.modf', 'integer'],
  },

  // math.fmod
  {
    id: 'lua-math-009',
    category: 'Math Functions',
    difficulty: 'medium',
    title: 'Float Modulo',
    text: 'Use `math.fmod` to get the remainder of 10.5 divided by 3.',
    setup: 'local a = 10.5\nlocal b = 3',
    setupCode: 'local a = 10.5\nlocal b = 3',
    expected: 1.5,
    sample: 'return math.fmod(a, b)',
    hints: ['math.fmod works with floats', 'Returns remainder with same sign as dividend'],
    validPatterns: [/math\.fmod\s*\(\s*a\s*,\s*b\s*\)/],
    tags: ['math.fmod', 'modulo'],
  },

  // Combined math
  {
    id: 'lua-math-010',
    category: 'Math Functions',
    difficulty: 'hard',
    title: 'Clamp Value',
    text: 'Use `math.max` and `math.min` to clamp the value between 0 and 100.',
    setup: 'local value = 150\nlocal min_val = 0\nlocal max_val = 100',
    setupCode: 'local value = 150\nlocal min_val = 0\nlocal max_val = 100',
    expected: 100,
    sample: 'return math.min(math.max(value, min_val), max_val)',
    hints: ['Use max to enforce lower bound', 'Use min to enforce upper bound'],
    validPatterns: [/math\.min\s*\(.*math\.max/, /math\.max\s*\(.*math\.min/],
    tags: ['math.min', 'math.max', 'clamp'],
  },

  // ============================================================
  // Iterator Functions (8 problems: 3 easy, 4 medium, 1 hard)
  // ============================================================

  // ipairs
  {
    id: 'lua-iter-001',
    category: 'Iterator Functions',
    difficulty: 'easy',
    title: 'Sum with ipairs',
    text: 'Use `ipairs` to iterate and sum all numbers in the table.',
    setup: 'local numbers = {1, 2, 3, 4, 5}',
    setupCode: 'local numbers = {1, 2, 3, 4, 5}',
    expected: 15,
    sample: 'local sum = 0; for _, v in ipairs(numbers) do sum = sum + v end; return sum',
    hints: ['ipairs iterates over array part', 'Gives index and value pairs'],
    validPatterns: [/ipairs\s*\(\s*numbers\s*\)/],
    tags: ['ipairs', 'loop', 'sum'],
  },
  {
    id: 'lua-iter-002',
    category: 'Iterator Functions',
    difficulty: 'easy',
    title: 'Find with ipairs',
    text: 'Use `ipairs` to find the index of the first even number.',
    setup: 'local numbers = {1, 3, 4, 7, 8}',
    setupCode: 'local numbers = {1, 3, 4, 7, 8}',
    expected: 3,
    sample: 'for i, v in ipairs(numbers) do if v % 2 == 0 then return i end end',
    hints: ['ipairs gives index as first value', 'Check each value with modulo'],
    validPatterns: [/ipairs\s*\(\s*numbers\s*\)/],
    tags: ['ipairs', 'find', 'index'],
  },
  {
    id: 'lua-iter-003',
    category: 'Iterator Functions',
    difficulty: 'medium',
    title: 'Double Values with ipairs',
    text: 'Use `ipairs` to create a new table with all values doubled.',
    setup: 'local numbers = {1, 2, 3, 4}',
    setupCode: 'local numbers = {1, 2, 3, 4}',
    expected: [2, 4, 6, 8],
    sample: 'local result = {}; for i, v in ipairs(numbers) do result[i] = v * 2 end; return result',
    hints: ['Create a new table for results', 'Use the index to set values'],
    validPatterns: [/ipairs\s*\(\s*numbers\s*\)/],
    tags: ['ipairs', 'transform'],
  },

  // pairs
  {
    id: 'lua-iter-004',
    category: 'Iterator Functions',
    difficulty: 'easy',
    title: 'Count Keys with pairs',
    text: 'Use `pairs` to count the number of key-value pairs in the table.',
    setup: 'local person = {name = "Alice", age = 30, city = "NYC"}',
    setupCode: 'local person = {name = "Alice", age = 30, city = "NYC"}',
    expected: 3,
    sample: 'local count = 0; for _ in pairs(person) do count = count + 1 end; return count',
    hints: ['pairs iterates all key-value pairs', 'Increment counter for each pair'],
    validPatterns: [/pairs\s*\(\s*person\s*\)/],
    tags: ['pairs', 'count'],
  },
  {
    id: 'lua-iter-005',
    category: 'Iterator Functions',
    difficulty: 'medium',
    title: 'Collect Keys with pairs',
    text: 'Use `pairs` to collect all keys into a table.',
    setup: 'local person = {name = "Alice", age = 30}',
    setupCode: 'local person = {name = "Alice", age = 30}',
    expected: ['name', 'age'],
    sample: 'local keys = {}; for k in pairs(person) do table.insert(keys, k) end; return keys',
    hints: ['pairs gives key as first value', 'Use table.insert to add keys'],
    validPatterns: [/pairs\s*\(\s*person\s*\)/],
    tags: ['pairs', 'keys'],
  },
  {
    id: 'lua-iter-006',
    category: 'Iterator Functions',
    difficulty: 'medium',
    title: 'Sum Values with pairs',
    text: 'Use `pairs` to sum all numeric values in the table.',
    setup: 'local scores = {alice = 90, bob = 85, carol = 95}',
    setupCode: 'local scores = {alice = 90, bob = 85, carol = 95}',
    expected: 270,
    sample: 'local sum = 0; for _, v in pairs(scores) do sum = sum + v end; return sum',
    hints: ['pairs works with string keys', 'Use _ to ignore the key'],
    validPatterns: [/pairs\s*\(\s*scores\s*\)/],
    tags: ['pairs', 'sum'],
  },

  // next
  {
    id: 'lua-iter-007',
    category: 'Iterator Functions',
    difficulty: 'medium',
    title: 'Check Empty Table with next',
    text: 'Use `next` to check if the table is empty (return true if empty).',
    setup: 'local empty = {}',
    setupCode: 'local empty = {}',
    expected: true,
    sample: 'return next(empty) == nil',
    hints: ['next(t) returns nil for empty tables', 'Compare result with nil'],
    validPatterns: [/next\s*\(\s*empty\s*\)\s*==\s*nil/],
    tags: ['next', 'empty'],
  },
  {
    id: 'lua-iter-008',
    category: 'Iterator Functions',
    difficulty: 'hard',
    title: 'Filter with ipairs',
    text: 'Use `ipairs` to create a new table containing only even numbers.',
    setup: 'local numbers = {1, 2, 3, 4, 5, 6}',
    setupCode: 'local numbers = {1, 2, 3, 4, 5, 6}',
    expected: [2, 4, 6],
    sample: 'local result = {}; for _, v in ipairs(numbers) do if v % 2 == 0 then table.insert(result, v) end end; return result',
    hints: ['Check if each value is even', 'Use table.insert for matching values'],
    validPatterns: [/ipairs\s*\(\s*numbers\s*\)/, /v\s*%\s*2\s*==\s*0/],
    tags: ['ipairs', 'filter', 'even'],
  },

  // ============================================================
  // Pattern Matching (6 problems: 2 easy, 2 medium, 2 hard)
  // ============================================================

  // Basic patterns
  {
    id: 'lua-pattern-001',
    category: 'Pattern Matching',
    difficulty: 'easy',
    title: 'Match Digits',
    text: 'Use `string.match` to extract all consecutive digits from the string.',
    setup: 'local text = "Order #12345 confirmed"',
    setupCode: 'local text = "Order #12345 confirmed"',
    expected: '12345',
    sample: 'return string.match(text, "%d+")',
    hints: ['%d matches any digit', '+ means one or more'],
    validPatterns: [/string\.match\s*\(\s*text\s*,\s*["']%d\+["']\s*\)/, /text:match\s*\(\s*["']%d\+["']\s*\)/],
    tags: ['pattern', 'digits'],
  },
  {
    id: 'lua-pattern-002',
    category: 'Pattern Matching',
    difficulty: 'easy',
    title: 'Match Word Characters',
    text: 'Use `string.match` to extract the first word (letters only).',
    setup: 'local text = "Hello, World!"',
    setupCode: 'local text = "Hello, World!"',
    expected: 'Hello',
    sample: 'return string.match(text, "%a+")',
    hints: ['%a matches any letter', '+ means one or more'],
    validPatterns: [/string\.match\s*\(\s*text\s*,\s*["']%a\+["']\s*\)/, /text:match\s*\(\s*["']%a\+["']\s*\)/],
    tags: ['pattern', 'letters'],
  },

  // Captures
  {
    id: 'lua-pattern-003',
    category: 'Pattern Matching',
    difficulty: 'medium',
    title: 'Capture Groups',
    text: 'Use `string.match` with captures to extract the area code from the phone number.',
    setup: 'local phone = "(555) 123-4567"',
    setupCode: 'local phone = "(555) 123-4567"',
    expected: '555',
    sample: 'return string.match(phone, "%((%d+)%)")',
    hints: ['Use () to capture', '%( and %) match literal parentheses'],
    validPatterns: [/string\.match\s*\(\s*phone\s*,\s*["'].*%\(.*%d.*%\).*["']\s*\)/],
    tags: ['pattern', 'capture'],
  },
  {
    id: 'lua-pattern-004',
    category: 'Pattern Matching',
    difficulty: 'medium',
    title: 'Replace with Pattern',
    text: 'Use `string.gsub` with a pattern to remove all digits from the string.',
    setup: 'local text = "abc123def456"',
    setupCode: 'local text = "abc123def456"',
    expected: 'abcdef',
    sample: 'return (string.gsub(text, "%d+", ""))',
    hints: ['%d+ matches digit sequences', 'Replace with empty string to remove'],
    validPatterns: [/string\.gsub\s*\(\s*text\s*,\s*["']%d\+["']\s*,\s*["']["']\s*\)/],
    tags: ['pattern', 'gsub', 'remove'],
  },

  // gmatch iterator
  {
    id: 'lua-pattern-005',
    category: 'Pattern Matching',
    difficulty: 'hard',
    title: 'Iterate All Matches',
    text: 'Use `string.gmatch` to collect all words into a table.',
    setup: 'local text = "hello world lua programming"',
    setupCode: 'local text = "hello world lua programming"',
    expected: ['hello', 'world', 'lua', 'programming'],
    sample: 'local words = {}; for word in string.gmatch(text, "%w+") do table.insert(words, word) end; return words',
    hints: ['gmatch returns an iterator', 'Use for loop to collect matches'],
    validPatterns: [/string\.gmatch\s*\(\s*text\s*,\s*["']%w\+["']\s*\)/, /text:gmatch\s*\(\s*["']%w\+["']\s*\)/],
    tags: ['pattern', 'gmatch', 'iterator'],
  },
  {
    id: 'lua-pattern-006',
    category: 'Pattern Matching',
    difficulty: 'hard',
    title: 'Replace with Function',
    text: 'Use `string.gsub` with a function to double each number found.',
    setup: 'local text = "I have 5 apples and 3 oranges"',
    setupCode: 'local text = "I have 5 apples and 3 oranges"',
    expected: 'I have 10 apples and 6 oranges',
    sample: 'return (string.gsub(text, "%d+", function(n) return tostring(tonumber(n) * 2) end))',
    hints: ['gsub can take a function', 'Function receives the match as argument'],
    validPatterns: [/string\.gsub\s*\(\s*text\s*,\s*["']%d\+["']\s*,\s*function/],
    tags: ['pattern', 'gsub', 'function'],
  },
];

export default luaProblems;
