import type { Problem } from '../types';

/**
 * PHP Problems for Coding Drills
 * Covers modern PHP 8.2+ features, Laravel patterns, and best practices
 */

export const phpProblems: Problem[] = [
  // ============================================================
  // ARRAY FUNCTIONS - Transformation (15 problems)
  // ============================================================
  {
    id: 'php-array-001',
    category: 'array',
    difficulty: 'easy',
    title: 'Double Each Number',
    text: 'Double each number in the array using array_map with an arrow function',
    setup: '$nums = [1, 2, 3, 4, 5];',
    setupCode: '$nums = [1, 2, 3, 4, 5];',
    expected: [2, 4, 6, 8, 10],
    sample: 'array_map(fn($n) => $n * 2, $nums)',
    hints: ['Use array_map with an arrow function (fn)'],
    validPatterns: [
      /array_map\s*\(\s*fn\s*\(\s*\$\w+\s*\)\s*=>\s*\$\w+\s*\*\s*2\s*,\s*\$nums\s*\)/,
      /array_map\s*\(\s*fn\s*\(\s*\$\w+\s*\)\s*=>\s*2\s*\*\s*\$\w+\s*,\s*\$nums\s*\)/,
    ],
    tags: ['array_map', 'arrow-function', 'basic'],
  },
  {
    id: 'php-array-002',
    category: 'array',
    difficulty: 'easy',
    title: 'Square Each Number',
    text: 'Square each number in the array',
    setup: '$nums = [1, 2, 3, 4, 5];',
    setupCode: '$nums = [1, 2, 3, 4, 5];',
    expected: [1, 4, 9, 16, 25],
    sample: 'array_map(fn($n) => $n ** 2, $nums)',
    hints: ['Use ** for exponentiation in PHP'],
    validPatterns: [
      /array_map\s*\(\s*fn\s*\(\s*\$\w+\s*\)\s*=>\s*\$\w+\s*\*\*\s*2\s*,\s*\$nums\s*\)/,
      /array_map\s*\(\s*fn\s*\(\s*\$\w+\s*\)\s*=>\s*pow\s*\(\s*\$\w+\s*,\s*2\s*\)\s*,\s*\$nums\s*\)/,
    ],
    tags: ['array_map', 'math'],
  },
  {
    id: 'php-array-003',
    category: 'array',
    difficulty: 'easy',
    title: 'Filter Even Numbers',
    text: 'Filter the array to only include even numbers',
    setup: '$nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];',
    setupCode: '$nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];',
    expected: [2, 4, 6, 8, 10],
    sample: 'array_values(array_filter($nums, fn($n) => $n % 2 === 0))',
    hints: ['Use array_filter with a callback', 'Use array_values to reindex the result'],
    validPatterns: [
      /array_values\s*\(\s*array_filter\s*\(\s*\$nums\s*,\s*fn\s*\(\s*\$\w+\s*\)\s*=>\s*\$\w+\s*%\s*2\s*===?\s*0\s*\)\s*\)/,
    ],
    tags: ['array_filter', 'array_values'],
  },
  {
    id: 'php-array-004',
    category: 'array',
    difficulty: 'easy',
    title: 'Filter Numbers Greater Than 5',
    text: 'Filter the array to only include numbers greater than 5',
    setup: '$nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];',
    setupCode: '$nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];',
    expected: [6, 7, 8, 9, 10],
    sample: 'array_values(array_filter($nums, fn($n) => $n > 5))',
    hints: ['Use array_filter with a comparison'],
    validPatterns: [
      /array_values\s*\(\s*array_filter\s*\(\s*\$nums\s*,\s*fn\s*\(\s*\$\w+\s*\)\s*=>\s*\$\w+\s*>\s*5\s*\)\s*\)/,
    ],
    tags: ['array_filter'],
  },
  {
    id: 'php-array-005',
    category: 'array',
    difficulty: 'easy',
    title: 'Convert to Uppercase',
    text: 'Convert each string in the array to uppercase using first-class callable syntax',
    setup: '$words = ["hello", "world", "php"];',
    setupCode: '$words = ["hello", "world", "php"];',
    expected: ['HELLO', 'WORLD', 'PHP'],
    sample: 'array_map(strtoupper(...), $words)',
    hints: ['Use strtoupper(...) first-class callable syntax (PHP 8.1+)'],
    validPatterns: [
      /array_map\s*\(\s*strtoupper\s*\(\s*\.\.\.\s*\)\s*,\s*\$words\s*\)/,
      /array_map\s*\(\s*'strtoupper'\s*,\s*\$words\s*\)/,
      /array_map\s*\(\s*fn\s*\(\s*\$\w+\s*\)\s*=>\s*strtoupper\s*\(\s*\$\w+\s*\)\s*,\s*\$words\s*\)/,
    ],
    tags: ['array_map', 'first-class-callable'],
  },
  {
    id: 'php-array-006',
    category: 'array',
    difficulty: 'medium',
    title: 'Sum with Reduce',
    text: 'Calculate the sum of all numbers using array_reduce',
    setup: '$nums = [1, 2, 3, 4, 5];',
    setupCode: '$nums = [1, 2, 3, 4, 5];',
    expected: 15,
    sample: 'array_reduce($nums, fn($sum, $n) => $sum + $n, 0)',
    hints: ['Use array_reduce with an initial value of 0', 'Or simply use array_sum'],
    validPatterns: [
      /array_reduce\s*\(\s*\$nums\s*,\s*fn\s*\(\s*\$\w+\s*,\s*\$\w+\s*\)\s*=>\s*\$\w+\s*\+\s*\$\w+\s*,\s*0\s*\)/,
      /array_sum\s*\(\s*\$nums\s*\)/,
    ],
    tags: ['array_reduce', 'array_sum'],
  },
  {
    id: 'php-array-007',
    category: 'array',
    difficulty: 'medium',
    title: 'Flatten Nested Arrays',
    text: 'Flatten a nested array using array_reduce and the spread operator',
    setup: '$nested = [[1, 2], [3, 4], [5, 6]];',
    setupCode: '$nested = [[1, 2], [3, 4], [5, 6]];',
    expected: [1, 2, 3, 4, 5, 6],
    sample: 'array_reduce($nested, fn($a, $b) => [...$a, ...$b], [])',
    hints: ['Use array_reduce with spread operator', 'Or use array_merge with the splat operator'],
    validPatterns: [
      /array_reduce\s*\(\s*\$nested\s*,\s*fn\s*\(\s*\$\w+\s*,\s*\$\w+\s*\)\s*=>\s*\[\s*\.\.\.\$\w+\s*,\s*\.\.\.\$\w+\s*\]\s*,\s*\[\s*\]\s*\)/,
      /array_merge\s*\(\s*\.\.\.\$nested\s*\)/,
    ],
    tags: ['array_reduce', 'spread-operator'],
  },
  {
    id: 'php-array-008',
    category: 'array',
    difficulty: 'easy',
    title: 'Merge Arrays with Spread',
    text: 'Merge two arrays using the spread operator',
    setup: '$arr1 = [1, 2, 3]; $arr2 = [4, 5, 6];',
    setupCode: '$arr1 = [1, 2, 3]; $arr2 = [4, 5, 6];',
    expected: [1, 2, 3, 4, 5, 6],
    sample: '[...$arr1, ...$arr2]',
    hints: ['Use the spread operator inside array literals'],
    validPatterns: [
      /\[\s*\.\.\.\$arr1\s*,\s*\.\.\.\$arr2\s*\]/,
      /array_merge\s*\(\s*\$arr1\s*,\s*\$arr2\s*\)/,
    ],
    tags: ['spread-operator', 'array_merge'],
  },
  {
    id: 'php-array-009',
    category: 'array',
    difficulty: 'easy',
    title: 'Get Unique Values',
    text: 'Get unique values from the array and reset keys',
    setup: '$nums = [1, 2, 2, 3, 3, 3, 4];',
    setupCode: '$nums = [1, 2, 2, 3, 3, 3, 4];',
    expected: [1, 2, 3, 4],
    sample: 'array_values(array_unique($nums))',
    hints: ['Use array_unique then array_values to reset keys'],
    validPatterns: [
      /array_values\s*\(\s*array_unique\s*\(\s*\$nums\s*\)\s*\)/,
    ],
    tags: ['array_unique', 'array_values'],
  },
  {
    id: 'php-array-010',
    category: 'array',
    difficulty: 'medium',
    title: 'Extract Column from Array of Arrays',
    text: 'Extract the "name" values from an array of associative arrays',
    setup: '$users = [["id" => 1, "name" => "Alice"], ["id" => 2, "name" => "Bob"], ["id" => 3, "name" => "Charlie"]];',
    setupCode: '$users = [["id" => 1, "name" => "Alice"], ["id" => 2, "name" => "Bob"], ["id" => 3, "name" => "Charlie"]];',
    expected: ['Alice', 'Bob', 'Charlie'],
    sample: 'array_column($users, "name")',
    hints: ['Use array_column to extract values by key'],
    validPatterns: [
      /array_column\s*\(\s*\$users\s*,\s*['"]name['"]\s*\)/,
    ],
    tags: ['array_column'],
  },
  {
    id: 'php-array-011',
    category: 'array',
    difficulty: 'medium',
    title: 'Index Array by Key',
    text: 'Index the users array by their id',
    setup: '$users = [["id" => 1, "name" => "Alice"], ["id" => 2, "name" => "Bob"]];',
    setupCode: '$users = [["id" => 1, "name" => "Alice"], ["id" => 2, "name" => "Bob"]];',
    expected: { 1: { id: 1, name: 'Alice' }, 2: { id: 2, name: 'Bob' } },
    sample: 'array_column($users, null, "id")',
    hints: ['Use array_column with null as second parameter to keep full rows'],
    validPatterns: [
      /array_column\s*\(\s*\$users\s*,\s*null\s*,\s*['"]id['"]\s*\)/,
    ],
    tags: ['array_column'],
  },
  {
    id: 'php-array-012',
    category: 'array',
    difficulty: 'medium',
    title: 'Sort with Custom Comparison',
    text: 'Sort the array in descending order using usort with spaceship operator',
    setup: '$nums = [3, 1, 4, 1, 5, 9, 2, 6];',
    setupCode: '$nums = [3, 1, 4, 1, 5, 9, 2, 6];',
    expected: [9, 6, 5, 4, 3, 2, 1, 1],
    sample: 'usort($nums, fn($a, $b) => $b <=> $a); $nums',
    hints: ['Use usort with spaceship operator', 'Swap $a and $b for descending order'],
    validPatterns: [
      /usort\s*\(\s*\$nums\s*,\s*fn\s*\(\s*\$\w+\s*,\s*\$\w+\s*\)\s*=>\s*\$\w+\s*<=>\s*\$\w+\s*\)/,
    ],
    tags: ['usort', 'spaceship-operator'],
  },
  {
    id: 'php-array-013',
    category: 'array',
    difficulty: 'easy',
    title: 'Slice Array',
    text: 'Extract elements from index 2 to 5 (3 elements)',
    setup: '$nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];',
    setupCode: '$nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];',
    expected: [2, 3, 4],
    sample: 'array_slice($nums, 2, 3)',
    hints: ['Use array_slice with offset and length'],
    validPatterns: [
      /array_slice\s*\(\s*\$nums\s*,\s*2\s*,\s*3\s*\)/,
    ],
    tags: ['array_slice'],
  },
  {
    id: 'php-array-014',
    category: 'array',
    difficulty: 'easy',
    title: 'Check Value Exists (Strict)',
    text: 'Check if the integer 2 exists in the array using strict comparison',
    setup: '$arr = [1, "2", 3, "4"];',
    setupCode: '$arr = [1, "2", 3, "4"];',
    expected: false,
    sample: 'in_array(2, $arr, strict: true)',
    hints: ['Use in_array with named argument strict: true (PHP 8+)'],
    validPatterns: [
      /in_array\s*\(\s*2\s*,\s*\$arr\s*,\s*strict:\s*true\s*\)/,
      /in_array\s*\(\s*2\s*,\s*\$arr\s*,\s*true\s*\)/,
    ],
    tags: ['in_array', 'strict-comparison'],
  },
  {
    id: 'php-array-015',
    category: 'array',
    difficulty: 'medium',
    title: 'Chunk Array',
    text: 'Split the array into chunks of 3 elements each',
    setup: '$nums = [1, 2, 3, 4, 5, 6, 7, 8];',
    setupCode: '$nums = [1, 2, 3, 4, 5, 6, 7, 8];',
    expected: [[1, 2, 3], [4, 5, 6], [7, 8]],
    sample: 'array_chunk($nums, 3)',
    hints: ['Use array_chunk with size parameter'],
    validPatterns: [
      /array_chunk\s*\(\s*\$nums\s*,\s*3\s*\)/,
    ],
    tags: ['array_chunk'],
  },

  // ============================================================
  // STRING FUNCTIONS (15 problems)
  // ============================================================
  {
    id: 'php-string-001',
    category: 'string',
    difficulty: 'easy',
    title: 'Check String Contains',
    text: 'Check if the string contains "World" (PHP 8+)',
    setup: '$str = "Hello World";',
    setupCode: '$str = "Hello World";',
    expected: true,
    sample: 'str_contains($str, "World")',
    hints: ['Use str_contains (PHP 8.0+)'],
    validPatterns: [
      /str_contains\s*\(\s*\$str\s*,\s*['"]World['"]\s*\)/,
    ],
    tags: ['str_contains', 'php8'],
  },
  {
    id: 'php-string-002',
    category: 'string',
    difficulty: 'easy',
    title: 'Check String Starts With',
    text: 'Check if the string starts with "Hello" (PHP 8+)',
    setup: '$str = "Hello World";',
    setupCode: '$str = "Hello World";',
    expected: true,
    sample: 'str_starts_with($str, "Hello")',
    hints: ['Use str_starts_with (PHP 8.0+)'],
    validPatterns: [
      /str_starts_with\s*\(\s*\$str\s*,\s*['"]Hello['"]\s*\)/,
    ],
    tags: ['str_starts_with', 'php8'],
  },
  {
    id: 'php-string-003',
    category: 'string',
    difficulty: 'easy',
    title: 'Check String Ends With',
    text: 'Check if the filename ends with ".jpg"',
    setup: '$filename = "photo.jpg";',
    setupCode: '$filename = "photo.jpg";',
    expected: true,
    sample: 'str_ends_with($filename, ".jpg")',
    hints: ['Use str_ends_with (PHP 8.0+)'],
    validPatterns: [
      /str_ends_with\s*\(\s*\$filename\s*,\s*['"]\.jpg['"]\s*\)/,
    ],
    tags: ['str_ends_with', 'php8'],
  },
  {
    id: 'php-string-004',
    category: 'string',
    difficulty: 'easy',
    title: 'Split String',
    text: 'Split the string by comma into an array',
    setup: '$str = "apple,banana,cherry";',
    setupCode: '$str = "apple,banana,cherry";',
    expected: ['apple', 'banana', 'cherry'],
    sample: 'explode(",", $str)',
    hints: ['Use explode with comma as delimiter'],
    validPatterns: [
      /explode\s*\(\s*['"],['"],\s*\$str\s*\)/,
    ],
    tags: ['explode'],
  },
  {
    id: 'php-string-005',
    category: 'string',
    difficulty: 'easy',
    title: 'Join Array to String',
    text: 'Join the array elements with " - " separator',
    setup: '$arr = ["one", "two", "three"];',
    setupCode: '$arr = ["one", "two", "three"];',
    expected: 'one - two - three',
    sample: 'implode(" - ", $arr)',
    hints: ['Use implode (or join alias)'],
    validPatterns: [
      /implode\s*\(\s*['"]\s*-\s*['"]\s*,\s*\$arr\s*\)/,
      /join\s*\(\s*['"]\s*-\s*['"]\s*,\s*\$arr\s*\)/,
    ],
    tags: ['implode', 'join'],
  },
  {
    id: 'php-string-006',
    category: 'string',
    difficulty: 'easy',
    title: 'Trim Whitespace',
    text: 'Remove leading and trailing whitespace from the string',
    setup: '$str = "  Hello World  ";',
    setupCode: '$str = "  Hello World  ";',
    expected: 'Hello World',
    sample: 'trim($str)',
    hints: ['Use trim to remove whitespace'],
    validPatterns: [
      /trim\s*\(\s*\$str\s*\)/,
    ],
    tags: ['trim'],
  },
  {
    id: 'php-string-007',
    category: 'string',
    difficulty: 'medium',
    title: 'Format String with sprintf',
    text: 'Format the output as "Item: Product, Price: $19.99"',
    setup: '$name = "Product"; $price = 19.99;',
    setupCode: '$name = "Product"; $price = 19.99;',
    expected: 'Item: Product, Price: $19.99',
    sample: 'sprintf("Item: %s, Price: $%.2f", $name, $price)',
    hints: ['Use sprintf with %s for string and %.2f for float with 2 decimals'],
    validPatterns: [
      /sprintf\s*\(\s*['"]Item:\s*%s,\s*Price:\s*\$%.2f['"]\s*,\s*\$name\s*,\s*\$price\s*\)/,
    ],
    tags: ['sprintf', 'formatting'],
  },
  {
    id: 'php-string-008',
    category: 'string',
    difficulty: 'easy',
    title: 'Replace Substring',
    text: 'Replace "world" with "PHP" in the string',
    setup: '$str = "Hello world";',
    setupCode: '$str = "Hello world";',
    expected: 'Hello PHP',
    sample: 'str_replace("world", "PHP", $str)',
    hints: ['Use str_replace'],
    validPatterns: [
      /str_replace\s*\(\s*['"]world['"]\s*,\s*['"]PHP['"]\s*,\s*\$str\s*\)/,
    ],
    tags: ['str_replace'],
  },
  {
    id: 'php-string-009',
    category: 'string',
    difficulty: 'easy',
    title: 'Extract Substring',
    text: 'Extract "World" from the string (characters 6-10)',
    setup: '$str = "Hello World";',
    setupCode: '$str = "Hello World";',
    expected: 'World',
    sample: 'substr($str, 6)',
    hints: ['Use substr with starting position'],
    validPatterns: [
      /substr\s*\(\s*\$str\s*,\s*6\s*\)/,
      /substr\s*\(\s*\$str\s*,\s*6\s*,\s*5\s*\)/,
    ],
    tags: ['substr'],
  },
  {
    id: 'php-string-010',
    category: 'string',
    difficulty: 'medium',
    title: 'Regex Extract Number',
    text: 'Extract the numeric price from the string',
    setup: '$str = "Price: $42.99";',
    setupCode: '$str = "Price: $42.99";',
    expected: '42.99',
    sample: 'preg_match("/\\d+\\.\\d+/", $str, $m) ? $m[0] : null',
    hints: ['Use preg_match with a regex pattern for decimals'],
    validPatterns: [
      /preg_match\s*\(\s*['"]/,
    ],
    tags: ['preg_match', 'regex'],
  },
  {
    id: 'php-string-011',
    category: 'string',
    difficulty: 'easy',
    title: 'Pad Number with Zeros',
    text: 'Pad the number to 5 digits with leading zeros',
    setup: '$num = 42;',
    setupCode: '$num = 42;',
    expected: '00042',
    sample: 'sprintf("%05d", $num)',
    hints: ['Use sprintf with %05d format'],
    validPatterns: [
      /sprintf\s*\(\s*['"]%05d['"]\s*,\s*\$num\s*\)/,
      /str_pad\s*\(\s*\$num\s*,\s*5\s*,\s*['"]0['"]\s*,\s*STR_PAD_LEFT\s*\)/,
    ],
    tags: ['sprintf', 'str_pad'],
  },
  {
    id: 'php-string-012',
    category: 'string',
    difficulty: 'medium',
    title: 'Destructuring with Explode',
    text: 'Extract the first word and the rest separately',
    setup: '$str = "Hello World Today";',
    setupCode: '$str = "Hello World Today";',
    expected: ['Hello', 'World Today'],
    sample: 'explode(" ", $str, 2)',
    hints: ['Use explode with limit parameter'],
    validPatterns: [
      /explode\s*\(\s*['"]\s*['"]\s*,\s*\$str\s*,\s*2\s*\)/,
    ],
    tags: ['explode', 'destructuring'],
  },
  {
    id: 'php-string-013',
    category: 'string',
    difficulty: 'medium',
    title: 'Multiple Replacements',
    text: 'Replace both "a" and "e" with "@"',
    setup: '$str = "hacker";',
    setupCode: '$str = "hacker";',
    expected: 'h@ck@r',
    sample: 'str_replace(["a", "e"], "@", $str)',
    hints: ['str_replace accepts arrays for search parameter'],
    validPatterns: [
      /str_replace\s*\(\s*\[\s*['"]a['"]\s*,\s*['"]e['"]\s*\]\s*,\s*['"]@['"]\s*,\s*\$str\s*\)/,
    ],
    tags: ['str_replace', 'array'],
  },
  {
    id: 'php-string-014',
    category: 'string',
    difficulty: 'easy',
    title: 'Convert Case',
    text: 'Convert string to lowercase then capitalize first letter',
    setup: '$str = "hELLO WORLD";',
    setupCode: '$str = "hELLO WORLD";',
    expected: 'Hello world',
    sample: 'ucfirst(strtolower($str))',
    hints: ['Chain strtolower and ucfirst'],
    validPatterns: [
      /ucfirst\s*\(\s*strtolower\s*\(\s*\$str\s*\)\s*\)/,
    ],
    tags: ['strtolower', 'ucfirst'],
  },
  {
    id: 'php-string-015',
    category: 'string',
    difficulty: 'medium',
    title: 'Regex Named Groups',
    text: 'Extract year, month, and day from a date string using named capture groups',
    setup: '$date = "2024-01-15";',
    setupCode: '$date = "2024-01-15";',
    expected: { year: '2024', month: '01', day: '15' },
    sample: 'preg_match("/(?<year>\\d{4})-(?<month>\\d{2})-(?<day>\\d{2})/", $date, $m) ? ["year" => $m["year"], "month" => $m["month"], "day" => $m["day"]] : null',
    hints: ['Use named capture groups (?<name>pattern)'],
    validPatterns: [
      /preg_match\s*\(\s*['"]\/\(\?<year>/,
    ],
    tags: ['preg_match', 'named-groups'],
  },

  // ============================================================
  // COLLECTION METHODS - Laravel Patterns (15 problems)
  // ============================================================
  {
    id: 'php-collection-001',
    category: 'collection',
    difficulty: 'easy',
    title: 'Collection Map',
    text: 'Double each number using Laravel Collection map',
    setup: 'use Illuminate\\Support\\Collection; $nums = collect([1, 2, 3, 4, 5]);',
    setupCode: 'use Illuminate\\Support\\Collection; $nums = collect([1, 2, 3, 4, 5]);',
    expected: [2, 4, 6, 8, 10],
    sample: '$nums->map(fn($n) => $n * 2)->all()',
    hints: ['Use the map method with an arrow function'],
    validPatterns: [
      /\$nums->map\s*\(\s*fn\s*\(\s*\$\w+\s*\)\s*=>\s*\$\w+\s*\*\s*2\s*\)->all\s*\(\s*\)/,
    ],
    tags: ['collection', 'map', 'laravel'],
  },
  {
    id: 'php-collection-002',
    category: 'collection',
    difficulty: 'easy',
    title: 'Collection Filter',
    text: 'Filter to keep only even numbers using Collection',
    setup: 'use Illuminate\\Support\\Collection; $nums = collect([1, 2, 3, 4, 5, 6]);',
    setupCode: 'use Illuminate\\Support\\Collection; $nums = collect([1, 2, 3, 4, 5, 6]);',
    expected: [2, 4, 6],
    sample: '$nums->filter(fn($n) => $n % 2 === 0)->values()->all()',
    hints: ['Use filter then values to reset keys'],
    validPatterns: [
      /\$nums->filter\s*\(\s*fn\s*\(\s*\$\w+\s*\)\s*=>\s*\$\w+\s*%\s*2\s*===?\s*0\s*\)->values\s*\(\s*\)->all\s*\(\s*\)/,
    ],
    tags: ['collection', 'filter', 'laravel'],
  },
  {
    id: 'php-collection-003',
    category: 'collection',
    difficulty: 'easy',
    title: 'Collection Reduce Sum',
    text: 'Sum all numbers using Collection reduce',
    setup: 'use Illuminate\\Support\\Collection; $nums = collect([1, 2, 3, 4, 5]);',
    setupCode: 'use Illuminate\\Support\\Collection; $nums = collect([1, 2, 3, 4, 5]);',
    expected: 15,
    sample: '$nums->reduce(fn($sum, $n) => $sum + $n, 0)',
    hints: ['Use reduce or the simpler sum method'],
    validPatterns: [
      /\$nums->reduce\s*\(\s*fn\s*\(\s*\$\w+\s*,\s*\$\w+\s*\)\s*=>\s*\$\w+\s*\+\s*\$\w+\s*,\s*0\s*\)/,
      /\$nums->sum\s*\(\s*\)/,
    ],
    tags: ['collection', 'reduce', 'laravel'],
  },
  {
    id: 'php-collection-004',
    category: 'collection',
    difficulty: 'medium',
    title: 'Collection Pluck',
    text: 'Extract all "name" values from users collection',
    setup: 'use Illuminate\\Support\\Collection; $users = collect([["id" => 1, "name" => "Alice"], ["id" => 2, "name" => "Bob"]]);',
    setupCode: 'use Illuminate\\Support\\Collection; $users = collect([["id" => 1, "name" => "Alice"], ["id" => 2, "name" => "Bob"]]);',
    expected: ['Alice', 'Bob'],
    sample: '$users->pluck("name")->all()',
    hints: ['Use the pluck method with the key name'],
    validPatterns: [
      /\$users->pluck\s*\(\s*['"]name['"]\s*\)->all\s*\(\s*\)/,
    ],
    tags: ['collection', 'pluck', 'laravel'],
  },
  {
    id: 'php-collection-005',
    category: 'collection',
    difficulty: 'medium',
    title: 'Collection Where',
    text: 'Filter users where role is "admin"',
    setup: 'use Illuminate\\Support\\Collection; $users = collect([["name" => "Alice", "role" => "admin"], ["name" => "Bob", "role" => "user"], ["name" => "Charlie", "role" => "admin"]]);',
    setupCode: 'use Illuminate\\Support\\Collection; $users = collect([["name" => "Alice", "role" => "admin"], ["name" => "Bob", "role" => "user"], ["name" => "Charlie", "role" => "admin"]]);',
    expected: [{ name: 'Alice', role: 'admin' }, { name: 'Charlie', role: 'admin' }],
    sample: '$users->where("role", "admin")->values()->all()',
    hints: ['Use where for key-value filtering'],
    validPatterns: [
      /\$users->where\s*\(\s*['"]role['"]\s*,\s*['"]admin['"]\s*\)/,
    ],
    tags: ['collection', 'where', 'laravel'],
  },
  {
    id: 'php-collection-006',
    category: 'collection',
    difficulty: 'medium',
    title: 'Collection GroupBy',
    text: 'Group users by their role',
    setup: 'use Illuminate\\Support\\Collection; $users = collect([["name" => "Alice", "role" => "admin"], ["name" => "Bob", "role" => "user"], ["name" => "Charlie", "role" => "admin"]]);',
    setupCode: 'use Illuminate\\Support\\Collection; $users = collect([["name" => "Alice", "role" => "admin"], ["name" => "Bob", "role" => "user"], ["name" => "Charlie", "role" => "admin"]]);',
    expected: { admin: [{ name: 'Alice', role: 'admin' }, { name: 'Charlie', role: 'admin' }], user: [{ name: 'Bob', role: 'user' }] },
    sample: '$users->groupBy("role")->toArray()',
    hints: ['Use groupBy with the key to group by'],
    validPatterns: [
      /\$users->groupBy\s*\(\s*['"]role['"]\s*\)/,
    ],
    tags: ['collection', 'groupBy', 'laravel'],
  },
  {
    id: 'php-collection-007',
    category: 'collection',
    difficulty: 'easy',
    title: 'Collection SortBy',
    text: 'Sort users by name alphabetically',
    setup: 'use Illuminate\\Support\\Collection; $users = collect([["name" => "Charlie"], ["name" => "Alice"], ["name" => "Bob"]]);',
    setupCode: 'use Illuminate\\Support\\Collection; $users = collect([["name" => "Charlie"], ["name" => "Alice"], ["name" => "Bob"]]);',
    expected: [{ name: 'Alice' }, { name: 'Bob' }, { name: 'Charlie' }],
    sample: '$users->sortBy("name")->values()->all()',
    hints: ['Use sortBy then values to reset keys'],
    validPatterns: [
      /\$users->sortBy\s*\(\s*['"]name['"]\s*\)->values\s*\(\s*\)->all\s*\(\s*\)/,
    ],
    tags: ['collection', 'sortBy', 'laravel'],
  },
  {
    id: 'php-collection-008',
    category: 'collection',
    difficulty: 'easy',
    title: 'Collection First',
    text: 'Get the first user with role "admin"',
    setup: 'use Illuminate\\Support\\Collection; $users = collect([["name" => "Alice", "role" => "user"], ["name" => "Bob", "role" => "admin"], ["name" => "Charlie", "role" => "admin"]]);',
    setupCode: 'use Illuminate\\Support\\Collection; $users = collect([["name" => "Alice", "role" => "user"], ["name" => "Bob", "role" => "admin"], ["name" => "Charlie", "role" => "admin"]]);',
    expected: { name: 'Bob', role: 'admin' },
    sample: '$users->first(fn($u) => $u["role"] === "admin")',
    hints: ['Use first with a callback'],
    validPatterns: [
      /\$users->first\s*\(\s*fn\s*\(\s*\$\w+\s*\)\s*=>\s*\$\w+\s*\[\s*['"]role['"]\s*\]\s*===?\s*['"]admin['"]\s*\)/,
      /\$users->firstWhere\s*\(\s*['"]role['"]\s*,\s*['"]admin['"]\s*\)/,
    ],
    tags: ['collection', 'first', 'laravel'],
  },
  {
    id: 'php-collection-009',
    category: 'collection',
    difficulty: 'medium',
    title: 'Collection Chunk',
    text: 'Split the collection into chunks of 3',
    setup: 'use Illuminate\\Support\\Collection; $nums = collect([1, 2, 3, 4, 5, 6, 7, 8]);',
    setupCode: 'use Illuminate\\Support\\Collection; $nums = collect([1, 2, 3, 4, 5, 6, 7, 8]);',
    expected: [[1, 2, 3], [4, 5, 6], [7, 8]],
    sample: '$nums->chunk(3)->map(fn($c) => $c->values()->all())->all()',
    hints: ['Use chunk method'],
    validPatterns: [
      /\$nums->chunk\s*\(\s*3\s*\)/,
    ],
    tags: ['collection', 'chunk', 'laravel'],
  },
  {
    id: 'php-collection-010',
    category: 'collection',
    difficulty: 'medium',
    title: 'Collection FlatMap',
    text: 'FlatMap to get all tags from posts',
    setup: 'use Illuminate\\Support\\Collection; $posts = collect([["tags" => ["php", "laravel"]], ["tags" => ["javascript", "vue"]]]);',
    setupCode: 'use Illuminate\\Support\\Collection; $posts = collect([["tags" => ["php", "laravel"]], ["tags" => ["javascript", "vue"]]]);',
    expected: ['php', 'laravel', 'javascript', 'vue'],
    sample: '$posts->flatMap(fn($p) => $p["tags"])->all()',
    hints: ['Use flatMap to map and flatten in one step'],
    validPatterns: [
      /\$posts->flatMap\s*\(\s*fn\s*\(\s*\$\w+\s*\)\s*=>\s*\$\w+\s*\[\s*['"]tags['"]\s*\]\s*\)->all\s*\(\s*\)/,
    ],
    tags: ['collection', 'flatMap', 'laravel'],
  },
  {
    id: 'php-collection-011',
    category: 'collection',
    difficulty: 'easy',
    title: 'Collection Unique',
    text: 'Get unique values from the collection',
    setup: 'use Illuminate\\Support\\Collection; $nums = collect([1, 2, 2, 3, 3, 3]);',
    setupCode: 'use Illuminate\\Support\\Collection; $nums = collect([1, 2, 2, 3, 3, 3]);',
    expected: [1, 2, 3],
    sample: '$nums->unique()->values()->all()',
    hints: ['Use unique then values to reset keys'],
    validPatterns: [
      /\$nums->unique\s*\(\s*\)->values\s*\(\s*\)->all\s*\(\s*\)/,
    ],
    tags: ['collection', 'unique', 'laravel'],
  },
  {
    id: 'php-collection-012',
    category: 'collection',
    difficulty: 'medium',
    title: 'Collection Method Chaining',
    text: 'Get names of active users sorted alphabetically',
    setup: 'use Illuminate\\Support\\Collection; $users = collect([["name" => "Charlie", "active" => true], ["name" => "Alice", "active" => false], ["name" => "Bob", "active" => true]]);',
    setupCode: 'use Illuminate\\Support\\Collection; $users = collect([["name" => "Charlie", "active" => true], ["name" => "Alice", "active" => false], ["name" => "Bob", "active" => true]]);',
    expected: ['Bob', 'Charlie'],
    sample: '$users->where("active", true)->sortBy("name")->pluck("name")->values()->all()',
    hints: ['Chain where, sortBy, pluck, values'],
    validPatterns: [
      /\$users->where\s*\(\s*['"]active['"]\s*,\s*true\s*\)->sortBy\s*\(\s*['"]name['"]\s*\)->pluck\s*\(\s*['"]name['"]\s*\)/,
    ],
    tags: ['collection', 'chaining', 'laravel'],
  },
  {
    id: 'php-collection-013',
    category: 'collection',
    difficulty: 'medium',
    title: 'Collection Pipe',
    text: 'Use pipe to transform collection to a report object',
    setup: 'use Illuminate\\Support\\Collection; $nums = collect([1, 2, 3, 4, 5]);',
    setupCode: 'use Illuminate\\Support\\Collection; $nums = collect([1, 2, 3, 4, 5]);',
    expected: { count: 5, sum: 15, avg: 3 },
    sample: '$nums->pipe(fn($c) => ["count" => $c->count(), "sum" => $c->sum(), "avg" => $c->avg()])',
    hints: ['Use pipe to break out of method chaining'],
    validPatterns: [
      /\$nums->pipe\s*\(\s*fn\s*\(\s*\$\w+\s*\)\s*=>/,
    ],
    tags: ['collection', 'pipe', 'laravel'],
  },
  {
    id: 'php-collection-014',
    category: 'collection',
    difficulty: 'easy',
    title: 'Collection Contains',
    text: 'Check if collection contains the value 3',
    setup: 'use Illuminate\\Support\\Collection; $nums = collect([1, 2, 3, 4, 5]);',
    setupCode: 'use Illuminate\\Support\\Collection; $nums = collect([1, 2, 3, 4, 5]);',
    expected: true,
    sample: '$nums->contains(3)',
    hints: ['Use contains method'],
    validPatterns: [
      /\$nums->contains\s*\(\s*3\s*\)/,
    ],
    tags: ['collection', 'contains', 'laravel'],
  },
  {
    id: 'php-collection-015',
    category: 'collection',
    difficulty: 'medium',
    title: 'Collection KeyBy',
    text: 'Index the users collection by their id',
    setup: 'use Illuminate\\Support\\Collection; $users = collect([["id" => 1, "name" => "Alice"], ["id" => 2, "name" => "Bob"]]);',
    setupCode: 'use Illuminate\\Support\\Collection; $users = collect([["id" => 1, "name" => "Alice"], ["id" => 2, "name" => "Bob"]]);',
    expected: { 1: { id: 1, name: 'Alice' }, 2: { id: 2, name: 'Bob' } },
    sample: '$users->keyBy("id")->toArray()',
    hints: ['Use keyBy to index by a key'],
    validPatterns: [
      /\$users->keyBy\s*\(\s*['"]id['"]\s*\)/,
    ],
    tags: ['collection', 'keyBy', 'laravel'],
  },

  // ============================================================
  // ELOQUENT ORM (10 problems)
  // ============================================================
  {
    id: 'php-eloquent-001',
    category: 'eloquent',
    difficulty: 'easy',
    title: 'Find by ID',
    text: 'Find a user by ID using Eloquent',
    setup: '// User model extends Eloquent Model',
    setupCode: '// User model extends Eloquent Model',
    expected: 'User model or null',
    sample: 'User::find(1)',
    hints: ['Use the static find method'],
    validPatterns: [
      /User::find\s*\(\s*1\s*\)/,
    ],
    tags: ['eloquent', 'find', 'laravel'],
  },
  {
    id: 'php-eloquent-002',
    category: 'eloquent',
    difficulty: 'easy',
    title: 'Where Clause',
    text: 'Get all active users',
    setup: '// User model with "active" column',
    setupCode: '// User model with "active" column',
    expected: 'Collection of active users',
    sample: 'User::where("active", true)->get()',
    hints: ['Use where with get to retrieve results'],
    validPatterns: [
      /User::where\s*\(\s*['"]active['"]\s*,\s*true\s*\)->get\s*\(\s*\)/,
    ],
    tags: ['eloquent', 'where', 'laravel'],
  },
  {
    id: 'php-eloquent-003',
    category: 'eloquent',
    difficulty: 'medium',
    title: 'Eager Loading',
    text: 'Get all posts with their authors eager loaded',
    setup: '// Post model with belongsTo("author") relationship',
    setupCode: '// Post model with belongsTo("author") relationship',
    expected: 'Collection of posts with authors',
    sample: 'Post::with("author")->get()',
    hints: ['Use with() to eager load relationships'],
    validPatterns: [
      /Post::with\s*\(\s*['"]author['"]\s*\)->get\s*\(\s*\)/,
    ],
    tags: ['eloquent', 'eager-loading', 'laravel'],
  },
  {
    id: 'php-eloquent-004',
    category: 'eloquent',
    difficulty: 'medium',
    title: 'Create Model',
    text: 'Create a new user with name and email',
    setup: '// User model with fillable name and email',
    setupCode: '// User model with fillable name and email',
    expected: 'New User model instance',
    sample: 'User::create(["name" => "John", "email" => "john@example.com"])',
    hints: ['Use the static create method with an array'],
    validPatterns: [
      /User::create\s*\(\s*\[\s*['"]name['"]\s*=>\s*['"]John['"]\s*,\s*['"]email['"]\s*=>\s*['"]john@example\.com['"]\s*\]\s*\)/,
    ],
    tags: ['eloquent', 'create', 'laravel'],
  },
  {
    id: 'php-eloquent-005',
    category: 'eloquent',
    difficulty: 'medium',
    title: 'Update or Create',
    text: 'Update or create a user by email',
    setup: '// User model',
    setupCode: '// User model',
    expected: 'User model (created or updated)',
    sample: 'User::updateOrCreate(["email" => "john@example.com"], ["name" => "John Doe"])',
    hints: ['First array is for lookup, second is for data'],
    validPatterns: [
      /User::updateOrCreate\s*\(\s*\[\s*['"]email['"]\s*=>/,
    ],
    tags: ['eloquent', 'updateOrCreate', 'laravel'],
  },
  {
    id: 'php-eloquent-006',
    category: 'eloquent',
    difficulty: 'medium',
    title: 'Constrained Eager Loading',
    text: 'Get posts with only published comments',
    setup: '// Post model with hasMany("comments") relationship',
    setupCode: '// Post model with hasMany("comments") relationship',
    expected: 'Posts with filtered comments',
    sample: 'Post::with(["comments" => fn($q) => $q->where("published", true)])->get()',
    hints: ['Use array syntax with closure for constrained loading'],
    validPatterns: [
      /Post::with\s*\(\s*\[\s*['"]comments['"]\s*=>\s*fn\s*\(\s*\$\w+\s*\)\s*=>\s*\$\w+->where\s*\(\s*['"]published['"]\s*,\s*true\s*\)\s*\]\s*\)->get\s*\(\s*\)/,
    ],
    tags: ['eloquent', 'constrained-eager-loading', 'laravel'],
  },
  {
    id: 'php-eloquent-007',
    category: 'eloquent',
    difficulty: 'easy',
    title: 'Order Results',
    text: 'Get users ordered by name in descending order',
    setup: '// User model',
    setupCode: '// User model',
    expected: 'Users sorted Z-A',
    sample: 'User::orderByDesc("name")->get()',
    hints: ['Use orderByDesc or orderBy with "desc"'],
    validPatterns: [
      /User::orderByDesc\s*\(\s*['"]name['"]\s*\)->get\s*\(\s*\)/,
      /User::orderBy\s*\(\s*['"]name['"]\s*,\s*['"]desc['"]\s*\)->get\s*\(\s*\)/,
    ],
    tags: ['eloquent', 'ordering', 'laravel'],
  },
  {
    id: 'php-eloquent-008',
    category: 'eloquent',
    difficulty: 'medium',
    title: 'Scope Usage',
    text: 'Use the "active" scope to get active users (scope is already defined)',
    setup: '// User model with scopeActive($query) method',
    setupCode: '// User model with scopeActive($query) method',
    expected: 'Active users',
    sample: 'User::active()->get()',
    hints: ['Scopes are called without the "scope" prefix'],
    validPatterns: [
      /User::active\s*\(\s*\)->get\s*\(\s*\)/,
    ],
    tags: ['eloquent', 'scope', 'laravel'],
  },
  {
    id: 'php-eloquent-009',
    category: 'eloquent',
    difficulty: 'medium',
    title: 'Multiple Eager Loading',
    text: 'Get posts with author and comments eager loaded',
    setup: '// Post model with relationships',
    setupCode: '// Post model with relationships',
    expected: 'Posts with author and comments',
    sample: 'Post::with(["author", "comments"])->get()',
    hints: ['Pass an array to with() for multiple relationships'],
    validPatterns: [
      /Post::with\s*\(\s*\[\s*['"]author['"]\s*,\s*['"]comments['"]\s*\]\s*\)->get\s*\(\s*\)/,
    ],
    tags: ['eloquent', 'eager-loading', 'laravel'],
  },
  {
    id: 'php-eloquent-010',
    category: 'eloquent',
    difficulty: 'hard',
    title: 'Query Builder Closure',
    text: 'Get users where (role is admin OR verified is true)',
    setup: '// User model',
    setupCode: '// User model',
    expected: 'Users matching condition',
    sample: 'User::where(fn($q) => $q->where("role", "admin")->orWhere("verified", true))->get()',
    hints: ['Use closure for grouping conditions'],
    validPatterns: [
      /User::where\s*\(\s*fn\s*\(\s*\$\w+\s*\)\s*=>\s*\$\w+->where\s*\(\s*['"]role['"]\s*,\s*['"]admin['"]\s*\)->orWhere\s*\(\s*['"]verified['"]\s*,\s*true\s*\)\s*\)->get\s*\(\s*\)/,
    ],
    tags: ['eloquent', 'closure', 'laravel'],
  },

  // ============================================================
  // LARAVEL HELPERS (10 problems)
  // ============================================================
  {
    id: 'php-helper-001',
    category: 'helper',
    difficulty: 'easy',
    title: 'Fluent String',
    text: 'Convert "hello world" to title case using Str::of',
    setup: 'use Illuminate\\Support\\Str;',
    setupCode: 'use Illuminate\\Support\\Str;',
    expected: 'Hello World',
    sample: 'Str::of("hello world")->title()->toString()',
    hints: ['Use Str::of for fluent string manipulation'],
    validPatterns: [
      /Str::of\s*\(\s*['"]hello world['"]\s*\)->title\s*\(\s*\)/,
    ],
    tags: ['str', 'fluent', 'laravel'],
  },
  {
    id: 'php-helper-002',
    category: 'helper',
    difficulty: 'easy',
    title: 'Generate Slug',
    text: 'Generate a URL slug from "Hello World!"',
    setup: 'use Illuminate\\Support\\Str;',
    setupCode: 'use Illuminate\\Support\\Str;',
    expected: 'hello-world',
    sample: 'Str::slug("Hello World!")',
    hints: ['Use Str::slug for URL-friendly strings'],
    validPatterns: [
      /Str::slug\s*\(\s*['"]Hello World!['"]\s*\)/,
    ],
    tags: ['str', 'slug', 'laravel'],
  },
  {
    id: 'php-helper-003',
    category: 'helper',
    difficulty: 'medium',
    title: 'Nested Array Access',
    text: 'Get the value at "user.profile.name" from a nested array',
    setup: 'use Illuminate\\Support\\Arr; $data = ["user" => ["profile" => ["name" => "John"]]];',
    setupCode: 'use Illuminate\\Support\\Arr; $data = ["user" => ["profile" => ["name" => "John"]]];',
    expected: 'John',
    sample: 'Arr::get($data, "user.profile.name")',
    hints: ['Use Arr::get with dot notation'],
    validPatterns: [
      /Arr::get\s*\(\s*\$data\s*,\s*['"]user\.profile\.name['"]\s*\)/,
    ],
    tags: ['arr', 'dot-notation', 'laravel'],
  },
  {
    id: 'php-helper-004',
    category: 'helper',
    difficulty: 'easy',
    title: 'Array Only',
    text: 'Get only "name" and "email" from the user array',
    setup: 'use Illuminate\\Support\\Arr; $user = ["id" => 1, "name" => "John", "email" => "john@example.com", "password" => "secret"];',
    setupCode: 'use Illuminate\\Support\\Arr; $user = ["id" => 1, "name" => "John", "email" => "john@example.com", "password" => "secret"];',
    expected: { name: 'John', email: 'john@example.com' },
    sample: 'Arr::only($user, ["name", "email"])',
    hints: ['Use Arr::only to whitelist keys'],
    validPatterns: [
      /Arr::only\s*\(\s*\$user\s*,\s*\[\s*['"]name['"]\s*,\s*['"]email['"]\s*\]\s*\)/,
    ],
    tags: ['arr', 'only', 'laravel'],
  },
  {
    id: 'php-helper-005',
    category: 'helper',
    difficulty: 'easy',
    title: 'Array Except',
    text: 'Remove "password" from the user array',
    setup: 'use Illuminate\\Support\\Arr; $user = ["id" => 1, "name" => "John", "password" => "secret"];',
    setupCode: 'use Illuminate\\Support\\Arr; $user = ["id" => 1, "name" => "John", "password" => "secret"];',
    expected: { id: 1, name: 'John' },
    sample: 'Arr::except($user, ["password"])',
    hints: ['Use Arr::except to blacklist keys'],
    validPatterns: [
      /Arr::except\s*\(\s*\$user\s*,\s*\[\s*['"]password['"]\s*\]\s*\)/,
    ],
    tags: ['arr', 'except', 'laravel'],
  },
  {
    id: 'php-helper-006',
    category: 'helper',
    difficulty: 'medium',
    title: 'Optional Helper',
    text: 'Safely access name property on a possibly null user',
    setup: '$user = null;',
    setupCode: '$user = null;',
    expected: null,
    sample: 'optional($user)->name',
    hints: ['Use optional() to avoid null errors'],
    validPatterns: [
      /optional\s*\(\s*\$user\s*\)->name/,
      /\$user\?->name/,
    ],
    tags: ['optional', 'null-safety', 'laravel'],
  },
  {
    id: 'php-helper-007',
    category: 'helper',
    difficulty: 'medium',
    title: 'Tap Helper',
    text: 'Update user last_login and return the user using tap',
    setup: '$user = new User();',
    setupCode: '$user = new User();',
    expected: 'User with updated last_login',
    sample: 'tap($user)->update(["last_login" => now()])',
    hints: ['Use tap to perform action and return original'],
    validPatterns: [
      /tap\s*\(\s*\$user\s*\)->update/,
    ],
    tags: ['tap', 'fluent', 'laravel'],
  },
  {
    id: 'php-helper-008',
    category: 'helper',
    difficulty: 'easy',
    title: 'Now Helper',
    text: 'Get the current timestamp using the now() helper',
    setup: '// Laravel application',
    setupCode: '// Laravel application',
    expected: 'Carbon instance',
    sample: 'now()',
    hints: ['now() returns a Carbon instance'],
    validPatterns: [
      /now\s*\(\s*\)/,
    ],
    tags: ['now', 'carbon', 'laravel'],
  },
  {
    id: 'php-helper-009',
    category: 'helper',
    difficulty: 'medium',
    title: 'String Chaining',
    text: 'Convert "  HELLO WORLD  " to "hello-world" using Str::of chain',
    setup: 'use Illuminate\\Support\\Str;',
    setupCode: 'use Illuminate\\Support\\Str;',
    expected: 'hello-world',
    sample: 'Str::of("  HELLO WORLD  ")->trim()->lower()->slug()->toString()',
    hints: ['Chain trim, lower, and slug methods'],
    validPatterns: [
      /Str::of\s*\(\s*['"]\s*HELLO WORLD\s*['"]\s*\)->trim\s*\(\s*\)->lower\s*\(\s*\)->slug\s*\(\s*\)/,
    ],
    tags: ['str', 'chaining', 'laravel'],
  },
  {
    id: 'php-helper-010',
    category: 'helper',
    difficulty: 'medium',
    title: 'Arr Has',
    text: 'Check if nested key "user.profile.name" exists in array',
    setup: 'use Illuminate\\Support\\Arr; $data = ["user" => ["profile" => ["name" => "John"]]];',
    setupCode: 'use Illuminate\\Support\\Arr; $data = ["user" => ["profile" => ["name" => "John"]]];',
    expected: true,
    sample: 'Arr::has($data, "user.profile.name")',
    hints: ['Use Arr::has with dot notation'],
    validPatterns: [
      /Arr::has\s*\(\s*\$data\s*,\s*['"]user\.profile\.name['"]\s*\)/,
    ],
    tags: ['arr', 'has', 'laravel'],
  },

  // ============================================================
  // MODERN PHP FEATURES (10 problems)
  // ============================================================
  {
    id: 'php-modern-001',
    category: 'modern',
    difficulty: 'easy',
    title: 'Arrow Function',
    text: 'Create an arrow function that doubles a number',
    setup: '',
    setupCode: '',
    expected: 'fn($n) => $n * 2',
    sample: 'fn($n) => $n * 2',
    hints: ['Use fn() => syntax for arrow functions'],
    validPatterns: [
      /fn\s*\(\s*\$\w+\s*\)\s*=>\s*\$\w+\s*\*\s*2/,
    ],
    tags: ['arrow-function', 'php74'],
  },
  {
    id: 'php-modern-002',
    category: 'modern',
    difficulty: 'easy',
    title: 'Nullsafe Operator',
    text: 'Access user profile name with nullsafe operator',
    setup: '$user = null;',
    setupCode: '$user = null;',
    expected: null,
    sample: '$user?->profile?->name',
    hints: ['Use ?-> for nullsafe property access'],
    validPatterns: [
      /\$user\?->profile\?->name/,
    ],
    tags: ['nullsafe', 'php8'],
  },
  {
    id: 'php-modern-003',
    category: 'modern',
    difficulty: 'easy',
    title: 'Named Arguments',
    text: 'Call array_slice with named arguments for clarity',
    setup: '$arr = [1, 2, 3, 4, 5];',
    setupCode: '$arr = [1, 2, 3, 4, 5];',
    expected: [3, 4, 5],
    sample: 'array_slice(array: $arr, offset: 2)',
    hints: ['Use argument: value syntax for named arguments'],
    validPatterns: [
      /array_slice\s*\(\s*array:\s*\$arr\s*,\s*offset:\s*2\s*\)/,
    ],
    tags: ['named-arguments', 'php8'],
  },
  {
    id: 'php-modern-004',
    category: 'modern',
    difficulty: 'medium',
    title: 'Match Expression',
    text: 'Use match expression to return day name for 1-7',
    setup: '$day = 1;',
    setupCode: '$day = 1;',
    expected: 'Monday',
    sample: 'match($day) { 1 => "Monday", 2 => "Tuesday", 3 => "Wednesday", 4 => "Thursday", 5 => "Friday", 6 => "Saturday", 7 => "Sunday" }',
    hints: ['Use match expression (PHP 8+) instead of switch'],
    validPatterns: [
      /match\s*\(\s*\$day\s*\)\s*\{/,
    ],
    tags: ['match', 'php8'],
  },
  {
    id: 'php-modern-005',
    category: 'modern',
    difficulty: 'easy',
    title: 'Null Coalescing',
    text: 'Use null coalescing operator with default value',
    setup: '$config = [];',
    setupCode: '$config = [];',
    expected: 'default',
    sample: '$config["timeout"] ?? "default"',
    hints: ['Use ?? for null coalescing'],
    validPatterns: [
      /\$config\s*\[\s*['"]timeout['"]\s*\]\s*\?\?\s*['"]default['"]/,
    ],
    tags: ['null-coalescing', 'php7'],
  },
  {
    id: 'php-modern-006',
    category: 'modern',
    difficulty: 'easy',
    title: 'Spaceship Operator',
    text: 'Compare two numbers using spaceship operator',
    setup: '$a = 5; $b = 3;',
    setupCode: '$a = 5; $b = 3;',
    expected: 1,
    sample: '$a <=> $b',
    hints: ['<=> returns -1, 0, or 1'],
    validPatterns: [
      /\$a\s*<=>\s*\$b/,
    ],
    tags: ['spaceship', 'php7'],
  },
  {
    id: 'php-modern-007',
    category: 'modern',
    difficulty: 'medium',
    title: 'Spread Operator in Arrays',
    text: 'Add elements to both ends of an array using spread',
    setup: '$middle = [2, 3, 4];',
    setupCode: '$middle = [2, 3, 4];',
    expected: [1, 2, 3, 4, 5],
    sample: '[1, ...$middle, 5]',
    hints: ['Use ... to spread array elements'],
    validPatterns: [
      /\[\s*1\s*,\s*\.\.\.\$middle\s*,\s*5\s*\]/,
    ],
    tags: ['spread', 'php74'],
  },
  {
    id: 'php-modern-008',
    category: 'modern',
    difficulty: 'medium',
    title: 'First Class Callable',
    text: 'Pass strlen as a first-class callable to array_map',
    setup: '$words = ["hi", "hello", "world"];',
    setupCode: '$words = ["hi", "hello", "world"];',
    expected: [2, 5, 5],
    sample: 'array_map(strlen(...), $words)',
    hints: ['Use function_name(...) for first-class callable'],
    validPatterns: [
      /array_map\s*\(\s*strlen\s*\(\s*\.\.\.\s*\)\s*,\s*\$words\s*\)/,
    ],
    tags: ['first-class-callable', 'php81'],
  },
  {
    id: 'php-modern-009',
    category: 'modern',
    difficulty: 'easy',
    title: 'Array Destructuring',
    text: 'Destructure first and second elements from array',
    setup: '$arr = [1, 2, 3, 4, 5];',
    setupCode: '$arr = [1, 2, 3, 4, 5];',
    expected: { first: 1, second: 2 },
    sample: '[$first, $second] = $arr; ["first" => $first, "second" => $second]',
    hints: ['Use [$a, $b] = $arr for destructuring'],
    validPatterns: [
      /\[\s*\$\w+\s*,\s*\$\w+\s*\]\s*=\s*\$arr/,
    ],
    tags: ['destructuring', 'php71'],
  },
  {
    id: 'php-modern-010',
    category: 'modern',
    difficulty: 'medium',
    title: 'Readonly Properties',
    text: 'Define a readonly name property in a class constructor',
    setup: '',
    setupCode: '',
    expected: 'class User { public function __construct(public readonly string $name) {} }',
    sample: 'class User { public function __construct(public readonly string $name) {} }',
    hints: ['Use readonly modifier with constructor promotion'],
    validPatterns: [
      /public\s+readonly\s+string\s+\$name/,
    ],
    tags: ['readonly', 'php81'],
  },

  // ============================================================
  // JSON AND TYPE FUNCTIONS (5 problems)
  // ============================================================
  {
    id: 'php-json-001',
    category: 'json',
    difficulty: 'easy',
    title: 'Encode to JSON',
    text: 'Encode an array to JSON with pretty print',
    setup: '$data = ["name" => "John", "age" => 30];',
    setupCode: '$data = ["name" => "John", "age" => 30];',
    expected: '{\n    "name": "John",\n    "age": 30\n}',
    sample: 'json_encode($data, JSON_PRETTY_PRINT)',
    hints: ['Use JSON_PRETTY_PRINT flag'],
    validPatterns: [
      /json_encode\s*\(\s*\$data\s*,\s*JSON_PRETTY_PRINT\s*\)/,
    ],
    tags: ['json_encode'],
  },
  {
    id: 'php-json-002',
    category: 'json',
    difficulty: 'easy',
    title: 'Decode JSON to Array',
    text: 'Decode JSON string to an associative array',
    setup: '$json = \'{"name":"John","age":30}\';',
    setupCode: '$json = \'{"name":"John","age":30}\';',
    expected: { name: 'John', age: 30 },
    sample: 'json_decode($json, true)',
    hints: ['Pass true as second argument for associative array'],
    validPatterns: [
      /json_decode\s*\(\s*\$json\s*,\s*true\s*\)/,
    ],
    tags: ['json_decode'],
  },
  {
    id: 'php-json-003',
    category: 'json',
    difficulty: 'medium',
    title: 'JSON with Error Handling',
    text: 'Decode JSON with exception throwing on error',
    setup: '$json = \'{"name":"John"}\';',
    setupCode: '$json = \'{"name":"John"}\';',
    expected: { name: 'John' },
    sample: 'json_decode($json, true, 512, JSON_THROW_ON_ERROR)',
    hints: ['Use JSON_THROW_ON_ERROR flag (PHP 7.3+)'],
    validPatterns: [
      /json_decode\s*\(\s*\$json\s*,\s*true\s*,\s*512\s*,\s*JSON_THROW_ON_ERROR\s*\)/,
    ],
    tags: ['json_decode', 'error-handling'],
  },
  {
    id: 'php-type-001',
    category: 'type',
    difficulty: 'easy',
    title: 'Get Debug Type',
    text: 'Get the type name of a value using get_debug_type (PHP 8+)',
    setup: '$value = 42;',
    setupCode: '$value = 42;',
    expected: 'int',
    sample: 'get_debug_type($value)',
    hints: ['get_debug_type returns actual type names'],
    validPatterns: [
      /get_debug_type\s*\(\s*\$value\s*\)/,
    ],
    tags: ['get_debug_type', 'php8'],
  },
  {
    id: 'php-type-002',
    category: 'type',
    difficulty: 'easy',
    title: 'Instance Check',
    text: 'Check if $user is an instance of User class',
    setup: 'class User {} $user = new User();',
    setupCode: 'class User {} $user = new User();',
    expected: true,
    sample: '$user instanceof User',
    hints: ['Use instanceof operator'],
    validPatterns: [
      /\$user\s+instanceof\s+User/,
    ],
    tags: ['instanceof'],
  },
];
