import type { Problem } from '../types';

/**
 * Python problems for coding drills
 * Covers list methods, string methods, dictionary methods, set methods, and built-in functions
 */

export const pythonProblems: Problem[] = [
  // ============================================================
  // LIST METHODS - List Comprehensions (15+ problems)
  // ============================================================
  {
    id: 'py-list-001',
    category: 'list',
    difficulty: 'easy',
    title: 'Double Each Number',
    text: 'Double each number in the list using a list comprehension',
    setup: 'nums = [1, 2, 3, 4, 5]',
    setupCode: 'nums = [1, 2, 3, 4, 5]',
    expected: [2, 4, 6, 8, 10],
    sample: '[x * 2 for x in nums]',
    hints: ['Use a list comprehension with the pattern [expression for item in iterable]'],
    validPatterns: [
      /\[\s*\w+\s*\*\s*2\s+for\s+\w+\s+in\s+nums\s*\]/,
      /\[\s*2\s*\*\s*\w+\s+for\s+\w+\s+in\s+nums\s*\]/,
      /list\s*\(\s*map\s*\(\s*lambda\s+\w+\s*:\s*\w+\s*\*\s*2/,
    ],
    tags: ['list-comprehension', 'basic'],
  },
  {
    id: 'py-list-002',
    category: 'list',
    difficulty: 'easy',
    title: 'Square Each Number',
    text: 'Square each number in the list',
    setup: 'nums = [1, 2, 3, 4, 5]',
    setupCode: 'nums = [1, 2, 3, 4, 5]',
    expected: [1, 4, 9, 16, 25],
    sample: '[x ** 2 for x in nums]',
    hints: ['Use ** for exponentiation in Python'],
    validPatterns: [
      /\[\s*\w+\s*\*\*\s*2\s+for\s+\w+\s+in\s+nums\s*\]/,
      /\[\s*pow\s*\(\s*\w+\s*,\s*2\s*\)\s+for\s+\w+\s+in\s+nums\s*\]/,
      /list\s*\(\s*map\s*\(\s*lambda\s+\w+\s*:\s*\w+\s*\*\*\s*2/,
    ],
    tags: ['list-comprehension', 'math'],
  },
  {
    id: 'py-list-003',
    category: 'list',
    difficulty: 'easy',
    title: 'Filter Even Numbers',
    text: 'Filter the list to only include even numbers',
    setup: 'nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]',
    setupCode: 'nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]',
    expected: [2, 4, 6, 8, 10],
    sample: '[x for x in nums if x % 2 == 0]',
    hints: ['Use a conditional in the list comprehension: [x for x in iterable if condition]'],
    validPatterns: [
      /\[\s*\w+\s+for\s+\w+\s+in\s+nums\s+if\s+\w+\s*%\s*2\s*==\s*0\s*\]/,
      /\[\s*\w+\s+for\s+\w+\s+in\s+nums\s+if\s+not\s+\w+\s*%\s*2\s*\]/,
      /list\s*\(\s*filter\s*\(\s*lambda\s+\w+\s*:\s*\w+\s*%\s*2\s*==\s*0/,
    ],
    tags: ['list-comprehension', 'filter'],
  },
  {
    id: 'py-list-004',
    category: 'list',
    difficulty: 'easy',
    title: 'Filter Odd Numbers',
    text: 'Filter the list to only include odd numbers',
    setup: 'nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]',
    setupCode: 'nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]',
    expected: [1, 3, 5, 7, 9],
    sample: '[x for x in nums if x % 2 != 0]',
    hints: ['Odd numbers have a remainder of 1 when divided by 2'],
    validPatterns: [
      /\[\s*\w+\s+for\s+\w+\s+in\s+nums\s+if\s+\w+\s*%\s*2\s*!=\s*0\s*\]/,
      /\[\s*\w+\s+for\s+\w+\s+in\s+nums\s+if\s+\w+\s*%\s*2\s*==\s*1\s*\]/,
      /\[\s*\w+\s+for\s+\w+\s+in\s+nums\s+if\s+\w+\s*%\s*2\s*\]/,
      /list\s*\(\s*filter\s*\(\s*lambda\s+\w+\s*:\s*\w+\s*%\s*2/,
    ],
    tags: ['list-comprehension', 'filter'],
  },
  {
    id: 'py-list-005',
    category: 'list',
    difficulty: 'easy',
    title: 'Filter Numbers Greater Than 5',
    text: 'Filter the list to only include numbers greater than 5',
    setup: 'nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]',
    setupCode: 'nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]',
    expected: [6, 7, 8, 9, 10],
    sample: '[x for x in nums if x > 5]',
    hints: ['Use a comparison operator in the condition'],
    validPatterns: [
      /\[\s*\w+\s+for\s+\w+\s+in\s+nums\s+if\s+\w+\s*>\s*5\s*\]/,
      /list\s*\(\s*filter\s*\(\s*lambda\s+\w+\s*:\s*\w+\s*>\s*5/,
    ],
    tags: ['list-comprehension', 'filter'],
  },
  {
    id: 'py-list-006',
    category: 'list',
    difficulty: 'medium',
    title: 'Double Even Numbers Only',
    text: 'Double only the even numbers in the list, keeping the result as a list of doubled values',
    setup: 'nums = [1, 2, 3, 4, 5, 6]',
    setupCode: 'nums = [1, 2, 3, 4, 5, 6]',
    expected: [4, 8, 12],
    sample: '[x * 2 for x in nums if x % 2 == 0]',
    hints: ['Combine transformation and filtering in one comprehension'],
    validPatterns: [
      /\[\s*\w+\s*\*\s*2\s+for\s+\w+\s+in\s+nums\s+if\s+\w+\s*%\s*2\s*==\s*0\s*\]/,
      /\[\s*2\s*\*\s*\w+\s+for\s+\w+\s+in\s+nums\s+if\s+\w+\s*%\s*2\s*==\s*0\s*\]/,
    ],
    tags: ['list-comprehension', 'filter', 'transform'],
  },
  {
    id: 'py-list-007',
    category: 'list',
    difficulty: 'easy',
    title: 'Convert to Uppercase',
    text: 'Convert each string in the list to uppercase',
    setup: 'words = ["hello", "world", "python"]',
    setupCode: 'words = ["hello", "world", "python"]',
    expected: ['HELLO', 'WORLD', 'PYTHON'],
    sample: '[w.upper() for w in words]',
    hints: ['Use the upper() string method'],
    validPatterns: [
      /\[\s*\w+\.upper\s*\(\s*\)\s+for\s+\w+\s+in\s+words\s*\]/,
      /list\s*\(\s*map\s*\(\s*lambda\s+\w+\s*:\s*\w+\.upper\s*\(\s*\)/,
      /list\s*\(\s*map\s*\(\s*str\.upper/,
    ],
    tags: ['list-comprehension', 'string'],
  },
  {
    id: 'py-list-008',
    category: 'list',
    difficulty: 'medium',
    title: 'Map with Lambda',
    text: 'Use map() and lambda to triple each number in the list',
    setup: 'nums = [1, 2, 3, 4, 5]',
    setupCode: 'nums = [1, 2, 3, 4, 5]',
    expected: [3, 6, 9, 12, 15],
    sample: 'list(map(lambda x: x * 3, nums))',
    hints: ['Use map() with a lambda function and convert to list'],
    validPatterns: [
      /list\s*\(\s*map\s*\(\s*lambda\s+\w+\s*:\s*\w+\s*\*\s*3\s*,\s*nums\s*\)\s*\)/,
      /list\s*\(\s*map\s*\(\s*lambda\s+\w+\s*:\s*3\s*\*\s*\w+\s*,\s*nums\s*\)\s*\)/,
      /\[\s*\w+\s*\*\s*3\s+for\s+\w+\s+in\s+nums\s*\]/,
    ],
    tags: ['map', 'lambda'],
  },
  {
    id: 'py-list-009',
    category: 'list',
    difficulty: 'easy',
    title: 'Sort List Ascending',
    text: 'Sort the list in ascending order (return a new sorted list)',
    setup: 'nums = [5, 2, 8, 1, 9, 3]',
    setupCode: 'nums = [5, 2, 8, 1, 9, 3]',
    expected: [1, 2, 3, 5, 8, 9],
    sample: 'sorted(nums)',
    hints: ['Use the sorted() built-in function'],
    validPatterns: [
      /sorted\s*\(\s*nums\s*\)/,
      /sorted\s*\(\s*nums\s*,\s*reverse\s*=\s*False\s*\)/,
    ],
    tags: ['sorting', 'built-in'],
  },
  {
    id: 'py-list-010',
    category: 'list',
    difficulty: 'easy',
    title: 'Sort List Descending',
    text: 'Sort the list in descending order (return a new sorted list)',
    setup: 'nums = [5, 2, 8, 1, 9, 3]',
    setupCode: 'nums = [5, 2, 8, 1, 9, 3]',
    expected: [9, 8, 5, 3, 2, 1],
    sample: 'sorted(nums, reverse=True)',
    hints: ['Use the reverse parameter of sorted()'],
    validPatterns: [
      /sorted\s*\(\s*nums\s*,\s*reverse\s*=\s*True\s*\)/,
      /sorted\s*\(\s*nums\s*\)\s*\[\s*::\s*-1\s*\]/,
      /list\s*\(\s*reversed\s*\(\s*sorted\s*\(\s*nums\s*\)\s*\)\s*\)/,
    ],
    tags: ['sorting', 'built-in'],
  },
  {
    id: 'py-list-011',
    category: 'list',
    difficulty: 'easy',
    title: 'Reverse a List',
    text: 'Reverse the order of elements in the list (return a new list)',
    setup: 'nums = [1, 2, 3, 4, 5]',
    setupCode: 'nums = [1, 2, 3, 4, 5]',
    expected: [5, 4, 3, 2, 1],
    sample: 'list(reversed(nums))',
    hints: ['Use reversed() or slice notation [::-1]'],
    validPatterns: [
      /list\s*\(\s*reversed\s*\(\s*nums\s*\)\s*\)/,
      /nums\s*\[\s*::\s*-1\s*\]/,
    ],
    tags: ['reverse', 'built-in'],
  },
  {
    id: 'py-list-012',
    category: 'list',
    difficulty: 'easy',
    title: 'Sum of List',
    text: 'Calculate the sum of all numbers in the list',
    setup: 'nums = [1, 2, 3, 4, 5]',
    setupCode: 'nums = [1, 2, 3, 4, 5]',
    expected: 15,
    sample: 'sum(nums)',
    hints: ['Use the sum() built-in function'],
    validPatterns: [
      /sum\s*\(\s*nums\s*\)/,
    ],
    tags: ['aggregation', 'built-in'],
  },
  {
    id: 'py-list-013',
    category: 'list',
    difficulty: 'easy',
    title: 'Find Maximum',
    text: 'Find the maximum value in the list',
    setup: 'nums = [3, 7, 2, 9, 4, 1]',
    setupCode: 'nums = [3, 7, 2, 9, 4, 1]',
    expected: 9,
    sample: 'max(nums)',
    hints: ['Use the max() built-in function'],
    validPatterns: [
      /max\s*\(\s*nums\s*\)/,
      /sorted\s*\(\s*nums\s*\)\s*\[\s*-1\s*\]/,
    ],
    tags: ['aggregation', 'built-in'],
  },
  {
    id: 'py-list-014',
    category: 'list',
    difficulty: 'easy',
    title: 'Find Minimum',
    text: 'Find the minimum value in the list',
    setup: 'nums = [3, 7, 2, 9, 4, 1]',
    setupCode: 'nums = [3, 7, 2, 9, 4, 1]',
    expected: 1,
    sample: 'min(nums)',
    hints: ['Use the min() built-in function'],
    validPatterns: [
      /min\s*\(\s*nums\s*\)/,
      /sorted\s*\(\s*nums\s*\)\s*\[\s*0\s*\]/,
    ],
    tags: ['aggregation', 'built-in'],
  },
  {
    id: 'py-list-015',
    category: 'list',
    difficulty: 'easy',
    title: 'List Length',
    text: 'Find the length of the list',
    setup: 'nums = [1, 2, 3, 4, 5, 6, 7]',
    setupCode: 'nums = [1, 2, 3, 4, 5, 6, 7]',
    expected: 7,
    sample: 'len(nums)',
    hints: ['Use the len() built-in function'],
    validPatterns: [
      /len\s*\(\s*nums\s*\)/,
    ],
    tags: ['built-in'],
  },
  {
    id: 'py-list-016',
    category: 'list',
    difficulty: 'medium',
    title: 'Check Any Positive',
    text: 'Check if any number in the list is positive',
    setup: 'nums = [-1, -2, 3, -4, -5]',
    setupCode: 'nums = [-1, -2, 3, -4, -5]',
    expected: true,
    sample: 'any(x > 0 for x in nums)',
    hints: ['Use any() with a generator expression'],
    validPatterns: [
      /any\s*\(\s*\w+\s*>\s*0\s+for\s+\w+\s+in\s+nums\s*\)/,
      /any\s*\(\s*\[\s*\w+\s*>\s*0\s+for\s+\w+\s+in\s+nums\s*\]\s*\)/,
    ],
    tags: ['any', 'generator'],
  },
  {
    id: 'py-list-017',
    category: 'list',
    difficulty: 'medium',
    title: 'Check All Positive',
    text: 'Check if all numbers in the list are positive',
    setup: 'nums = [1, 2, 3, 4, 5]',
    setupCode: 'nums = [1, 2, 3, 4, 5]',
    expected: true,
    sample: 'all(x > 0 for x in nums)',
    hints: ['Use all() with a generator expression'],
    validPatterns: [
      /all\s*\(\s*\w+\s*>\s*0\s+for\s+\w+\s+in\s+nums\s*\)/,
      /all\s*\(\s*\[\s*\w+\s*>\s*0\s+for\s+\w+\s+in\s+nums\s*\]\s*\)/,
    ],
    tags: ['all', 'generator'],
  },
  {
    id: 'py-list-018',
    category: 'list',
    difficulty: 'medium',
    title: 'Zip Two Lists',
    text: 'Combine two lists into a list of tuples using zip. The result should be a list containing tuples like [("Alice", 25), ("Bob", 30), ("Charlie", 35)].',
    setup: 'names = ["Alice", "Bob", "Charlie"]\nages = [25, 30, 35]',
    setupCode: 'names = ["Alice", "Bob", "Charlie"]\nages = [25, 30, 35]',
    expected: [['Alice', 25], ['Bob', 30], ['Charlie', 35]],
    sample: 'list(zip(names, ages))',
    hints: ['Use zip() to combine iterables element by element', 'zip() returns tuples, which are displayed similar to lists in output'],
    validPatterns: [
      /list\s*\(\s*zip\s*\(\s*names\s*,\s*ages\s*\)\s*\)/,
      /\[\s*\(\s*\w+\s*,\s*\w+\s*\)\s+for\s+\w+\s*,\s*\w+\s+in\s+zip\s*\(\s*names\s*,\s*ages\s*\)\s*\]/,
      /\[\s*tuple\s*\(\s*\[\s*\w+\s*,\s*\w+\s*\]\s*\)\s+for\s+\w+\s*,\s*\w+\s+in\s+zip/,
    ],
    tags: ['zip', 'tuple'],
  },
  {
    id: 'py-list-019',
    category: 'list',
    difficulty: 'medium',
    title: 'Enumerate with Index',
    text: 'Create a list of tuples with (index, value) pairs using enumerate. The result should be [(0, "apple"), (1, "banana"), (2, "cherry")].',
    setup: 'fruits = ["apple", "banana", "cherry"]',
    setupCode: 'fruits = ["apple", "banana", "cherry"]',
    expected: [[0, 'apple'], [1, 'banana'], [2, 'cherry']],
    sample: 'list(enumerate(fruits))',
    hints: ['Use enumerate() to get index and value pairs', 'enumerate() yields tuples of (index, element)'],
    validPatterns: [
      /list\s*\(\s*enumerate\s*\(\s*fruits\s*\)\s*\)/,
      /\[\s*\(\s*i\s*,\s*\w+\s*\)\s+for\s+i\s*,\s*\w+\s+in\s+enumerate\s*\(\s*fruits\s*\)\s*\]/,
      /\[\s*\(\s*\w+\s*,\s*\w+\s*\)\s+for\s+\w+\s*,\s*\w+\s+in\s+enumerate\s*\(\s*fruits\s*\)\s*\]/,
    ],
    tags: ['enumerate'],
  },
  {
    id: 'py-list-020',
    category: 'list',
    difficulty: 'easy',
    title: 'Count Occurrences',
    text: 'Count how many times 3 appears in the list',
    setup: 'nums = [1, 3, 2, 3, 4, 3, 5]',
    setupCode: 'nums = [1, 3, 2, 3, 4, 3, 5]',
    expected: 3,
    sample: 'nums.count(3)',
    hints: ['Use the count() method on lists'],
    validPatterns: [
      /nums\.count\s*\(\s*3\s*\)/,
      /sum\s*\(\s*1\s+for\s+\w+\s+in\s+nums\s+if\s+\w+\s*==\s*3\s*\)/,
      /len\s*\(\s*\[\s*\w+\s+for\s+\w+\s+in\s+nums\s+if\s+\w+\s*==\s*3\s*\]\s*\)/,
    ],
    tags: ['count', 'list-method'],
  },
  {
    id: 'py-list-021',
    category: 'list',
    difficulty: 'easy',
    title: 'Find Index',
    text: 'Find the index of the first occurrence of "banana"',
    setup: 'fruits = ["apple", "banana", "cherry", "banana"]',
    setupCode: 'fruits = ["apple", "banana", "cherry", "banana"]',
    expected: 1,
    sample: 'fruits.index("banana")',
    hints: ['Use the index() method on lists'],
    validPatterns: [
      /fruits\.index\s*\(\s*["']banana["']\s*\)/,
    ],
    tags: ['index', 'list-method'],
  },
  {
    id: 'py-list-022',
    category: 'list',
    difficulty: 'medium',
    title: 'Flatten Nested List',
    text: 'Flatten a 2D list into a 1D list',
    setup: 'matrix = [[1, 2], [3, 4], [5, 6]]',
    setupCode: 'matrix = [[1, 2], [3, 4], [5, 6]]',
    expected: [1, 2, 3, 4, 5, 6],
    sample: '[x for row in matrix for x in row]',
    hints: ['Use a nested list comprehension'],
    validPatterns: [
      /\[\s*\w+\s+for\s+\w+\s+in\s+matrix\s+for\s+\w+\s+in\s+\w+\s*\]/,
      /sum\s*\(\s*matrix\s*,\s*\[\s*\]\s*\)/,
    ],
    tags: ['list-comprehension', 'nested'],
  },
  {
    id: 'py-list-023',
    category: 'list',
    difficulty: 'medium',
    title: 'Sum with Map',
    text: 'Use map and sum to calculate the sum of squared values',
    setup: 'nums = [1, 2, 3, 4, 5]',
    setupCode: 'nums = [1, 2, 3, 4, 5]',
    expected: 55,
    sample: 'sum(map(lambda x: x ** 2, nums))',
    hints: ['Combine map() with sum()'],
    validPatterns: [
      /sum\s*\(\s*map\s*\(\s*lambda\s+\w+\s*:\s*\w+\s*\*\*\s*2\s*,\s*nums\s*\)\s*\)/,
      /sum\s*\(\s*\w+\s*\*\*\s*2\s+for\s+\w+\s+in\s+nums\s*\)/,
      /sum\s*\(\s*\[\s*\w+\s*\*\*\s*2\s+for\s+\w+\s+in\s+nums\s*\]\s*\)/,
    ],
    tags: ['map', 'sum', 'lambda'],
  },

  // ============================================================
  // STRING METHODS (15+ problems)
  // ============================================================
  {
    id: 'py-str-001',
    category: 'string',
    difficulty: 'easy',
    title: 'Split String',
    text: 'Split the sentence into a list of words',
    setup: 'sentence = "hello world python"',
    setupCode: 'sentence = "hello world python"',
    expected: ['hello', 'world', 'python'],
    sample: 'sentence.split()',
    hints: ['Use the split() method on strings'],
    validPatterns: [
      /sentence\.split\s*\(\s*\)/,
      /sentence\.split\s*\(\s*["']\s*["']\s*\)/,
      /sentence\.split\s*\(\s*" "\s*\)/,
    ],
    tags: ['split', 'string-method'],
  },
  {
    id: 'py-str-002',
    category: 'string',
    difficulty: 'easy',
    title: 'Split by Comma',
    text: 'Split the CSV string into a list of values',
    setup: 'csv = "apple,banana,cherry"',
    setupCode: 'csv = "apple,banana,cherry"',
    expected: ['apple', 'banana', 'cherry'],
    sample: 'csv.split(",")',
    hints: ['Pass the delimiter to split()'],
    validPatterns: [
      /csv\.split\s*\(\s*["'],["']\s*\)/,
    ],
    tags: ['split', 'string-method'],
  },
  {
    id: 'py-str-003',
    category: 'string',
    difficulty: 'easy',
    title: 'Join List into String',
    text: 'Join the list of words with spaces',
    setup: 'words = ["hello", "world", "python"]',
    setupCode: 'words = ["hello", "world", "python"]',
    expected: 'hello world python',
    sample: '" ".join(words)',
    hints: ['Use the join() method with a space separator'],
    validPatterns: [
      /["']\s["']\.join\s*\(\s*words\s*\)/,
      /" "\.join\s*\(\s*words\s*\)/,
    ],
    tags: ['join', 'string-method'],
  },
  {
    id: 'py-str-004',
    category: 'string',
    difficulty: 'easy',
    title: 'Join with Comma',
    text: 'Join the list of items with commas',
    setup: 'items = ["apple", "banana", "cherry"]',
    setupCode: 'items = ["apple", "banana", "cherry"]',
    expected: 'apple,banana,cherry',
    sample: '",".join(items)',
    hints: ['Use comma as the separator in join()'],
    validPatterns: [
      /["'],["']\.join\s*\(\s*items\s*\)/,
    ],
    tags: ['join', 'string-method'],
  },
  {
    id: 'py-str-005',
    category: 'string',
    difficulty: 'easy',
    title: 'Strip Whitespace',
    text: 'Remove leading and trailing whitespace from the string',
    setup: 'text = "  hello world  "',
    setupCode: 'text = "  hello world  "',
    expected: 'hello world',
    sample: 'text.strip()',
    hints: ['Use the strip() method'],
    validPatterns: [
      /text\.strip\s*\(\s*\)/,
    ],
    tags: ['strip', 'string-method'],
  },
  {
    id: 'py-str-006',
    category: 'string',
    difficulty: 'easy',
    title: 'Upper Case',
    text: 'Convert the string to uppercase',
    setup: 'text = "hello world"',
    setupCode: 'text = "hello world"',
    expected: 'HELLO WORLD',
    sample: 'text.upper()',
    hints: ['Use the upper() method'],
    validPatterns: [
      /text\.upper\s*\(\s*\)/,
    ],
    tags: ['upper', 'string-method'],
  },
  {
    id: 'py-str-007',
    category: 'string',
    difficulty: 'easy',
    title: 'Lower Case',
    text: 'Convert the string to lowercase',
    setup: 'text = "HELLO WORLD"',
    setupCode: 'text = "HELLO WORLD"',
    expected: 'hello world',
    sample: 'text.lower()',
    hints: ['Use the lower() method'],
    validPatterns: [
      /text\.lower\s*\(\s*\)/,
    ],
    tags: ['lower', 'string-method'],
  },
  {
    id: 'py-str-008',
    category: 'string',
    difficulty: 'easy',
    title: 'Title Case',
    text: 'Convert the string to title case',
    setup: 'text = "hello world python"',
    setupCode: 'text = "hello world python"',
    expected: 'Hello World Python',
    sample: 'text.title()',
    hints: ['Use the title() method'],
    validPatterns: [
      /text\.title\s*\(\s*\)/,
    ],
    tags: ['title', 'string-method'],
  },
  {
    id: 'py-str-009',
    category: 'string',
    difficulty: 'easy',
    title: 'Capitalize',
    text: 'Capitalize the first character of the string',
    setup: 'text = "hello world"',
    setupCode: 'text = "hello world"',
    expected: 'Hello world',
    sample: 'text.capitalize()',
    hints: ['Use the capitalize() method'],
    validPatterns: [
      /text\.capitalize\s*\(\s*\)/,
    ],
    tags: ['capitalize', 'string-method'],
  },
  {
    id: 'py-str-010',
    category: 'string',
    difficulty: 'easy',
    title: 'Replace Substring',
    text: 'Replace "world" with "Python" in the string',
    setup: 'text = "hello world"',
    setupCode: 'text = "hello world"',
    expected: 'hello Python',
    sample: 'text.replace("world", "Python")',
    hints: ['Use the replace() method'],
    validPatterns: [
      /text\.replace\s*\(\s*["']world["']\s*,\s*["']Python["']\s*\)/,
    ],
    tags: ['replace', 'string-method'],
  },
  {
    id: 'py-str-011',
    category: 'string',
    difficulty: 'easy',
    title: 'Find Substring',
    text: 'Find the index of "world" in the string',
    setup: 'text = "hello world"',
    setupCode: 'text = "hello world"',
    expected: 6,
    sample: 'text.find("world")',
    hints: ['Use the find() method'],
    validPatterns: [
      /text\.find\s*\(\s*["']world["']\s*\)/,
      /text\.index\s*\(\s*["']world["']\s*\)/,
    ],
    tags: ['find', 'string-method'],
  },
  {
    id: 'py-str-012',
    category: 'string',
    difficulty: 'easy',
    title: 'Count Substring',
    text: 'Count how many times "l" appears in the string',
    setup: 'text = "hello world"',
    setupCode: 'text = "hello world"',
    expected: 3,
    sample: 'text.count("l")',
    hints: ['Use the count() method'],
    validPatterns: [
      /text\.count\s*\(\s*["']l["']\s*\)/,
    ],
    tags: ['count', 'string-method'],
  },
  {
    id: 'py-str-013',
    category: 'string',
    difficulty: 'easy',
    title: 'Starts With',
    text: 'Check if the string starts with "hello"',
    setup: 'text = "hello world"',
    setupCode: 'text = "hello world"',
    expected: true,
    sample: 'text.startswith("hello")',
    hints: ['Use the startswith() method'],
    validPatterns: [
      /text\.startswith\s*\(\s*["']hello["']\s*\)/,
    ],
    tags: ['startswith', 'string-method'],
  },
  {
    id: 'py-str-014',
    category: 'string',
    difficulty: 'easy',
    title: 'Ends With',
    text: 'Check if the string ends with "world"',
    setup: 'text = "hello world"',
    setupCode: 'text = "hello world"',
    expected: true,
    sample: 'text.endswith("world")',
    hints: ['Use the endswith() method'],
    validPatterns: [
      /text\.endswith\s*\(\s*["']world["']\s*\)/,
    ],
    tags: ['endswith', 'string-method'],
  },
  {
    id: 'py-str-015',
    category: 'string',
    difficulty: 'easy',
    title: 'Is Digit',
    text: 'Check if the string contains only digits',
    setup: 'text = "12345"',
    setupCode: 'text = "12345"',
    expected: true,
    sample: 'text.isdigit()',
    hints: ['Use the isdigit() method'],
    validPatterns: [
      /text\.isdigit\s*\(\s*\)/,
      /text\.isnumeric\s*\(\s*\)/,
    ],
    tags: ['isdigit', 'string-method'],
  },
  {
    id: 'py-str-016',
    category: 'string',
    difficulty: 'easy',
    title: 'Is Alpha',
    text: 'Check if the string contains only alphabetic characters',
    setup: 'text = "hello"',
    setupCode: 'text = "hello"',
    expected: true,
    sample: 'text.isalpha()',
    hints: ['Use the isalpha() method'],
    validPatterns: [
      /text\.isalpha\s*\(\s*\)/,
    ],
    tags: ['isalpha', 'string-method'],
  },
  {
    id: 'py-str-017',
    category: 'string',
    difficulty: 'easy',
    title: 'Is Alphanumeric',
    text: 'Check if the string contains only alphanumeric characters',
    setup: 'text = "hello123"',
    setupCode: 'text = "hello123"',
    expected: true,
    sample: 'text.isalnum()',
    hints: ['Use the isalnum() method'],
    validPatterns: [
      /text\.isalnum\s*\(\s*\)/,
    ],
    tags: ['isalnum', 'string-method'],
  },
  {
    id: 'py-str-018',
    category: 'string',
    difficulty: 'medium',
    title: 'F-String Formatting',
    text: 'Create a formatted string with the name and age using f-string',
    setup: 'name = "Alice"\nage = 30',
    setupCode: 'name = "Alice"\nage = 30',
    expected: 'Alice is 30 years old',
    sample: 'f"{name} is {age} years old"',
    hints: ['Use f-string syntax: f"text {variable}"'],
    validPatterns: [
      /f["']\{name\}\s+is\s+\{age\}\s+years\s+old["']/,
      /f["']{name}\s+is\s+{age}\s+years\s+old["']/,
      /["']\s*\{\}\s*is\s*\{\}\s*years\s*old["']\.format\s*\(\s*name\s*,\s*age\s*\)/,
    ],
    tags: ['f-string', 'formatting'],
  },
  {
    id: 'py-str-019',
    category: 'string',
    difficulty: 'easy',
    title: 'String Slicing - First Three',
    text: 'Get the first 3 characters of the string',
    setup: 'text = "hello world"',
    setupCode: 'text = "hello world"',
    expected: 'hel',
    sample: 'text[:3]',
    hints: ['Use slice notation text[:n] to get first n characters'],
    validPatterns: [
      /text\s*\[\s*:\s*3\s*\]/,
      /text\s*\[\s*0\s*:\s*3\s*\]/,
    ],
    tags: ['slicing', 'string'],
  },
  {
    id: 'py-str-020',
    category: 'string',
    difficulty: 'easy',
    title: 'String Slicing - Last Three',
    text: 'Get the last 3 characters of the string',
    setup: 'text = "hello world"',
    setupCode: 'text = "hello world"',
    expected: 'rld',
    sample: 'text[-3:]',
    hints: ['Use negative indexing with slices'],
    validPatterns: [
      /text\s*\[\s*-3\s*:\s*\]/,
    ],
    tags: ['slicing', 'string'],
  },
  {
    id: 'py-str-021',
    category: 'string',
    difficulty: 'medium',
    title: 'Reverse String',
    text: 'Reverse the string using slicing',
    setup: 'text = "hello"',
    setupCode: 'text = "hello"',
    expected: 'olleh',
    sample: 'text[::-1]',
    hints: ['Use slice with step -1: text[::-1]'],
    validPatterns: [
      /text\s*\[\s*::\s*-1\s*\]/,
      /["']["']\.join\s*\(\s*reversed\s*\(\s*text\s*\)\s*\)/,
    ],
    tags: ['slicing', 'reverse'],
  },

  // ============================================================
  // DICTIONARY METHODS (10+ problems)
  // ============================================================
  {
    id: 'py-dict-001',
    category: 'dict',
    difficulty: 'easy',
    title: 'Get Dictionary Keys',
    text: 'Get all keys from the dictionary as a list',
    setup: 'person = {"name": "Alice", "age": 30, "city": "NYC"}',
    setupCode: 'person = {"name": "Alice", "age": 30, "city": "NYC"}',
    expected: ['name', 'age', 'city'],
    sample: 'list(person.keys())',
    hints: ['Use the keys() method and convert to list'],
    validPatterns: [
      /list\s*\(\s*person\.keys\s*\(\s*\)\s*\)/,
      /\[\s*k\s+for\s+k\s+in\s+person\s*\]/,
      /\[\s*\w+\s+for\s+\w+\s+in\s+person\.keys\s*\(\s*\)\s*\]/,
    ],
    tags: ['keys', 'dict-method'],
  },
  {
    id: 'py-dict-002',
    category: 'dict',
    difficulty: 'easy',
    title: 'Get Dictionary Values',
    text: 'Get all values from the dictionary as a list',
    setup: 'person = {"name": "Alice", "age": 30, "city": "NYC"}',
    setupCode: 'person = {"name": "Alice", "age": 30, "city": "NYC"}',
    expected: ['Alice', 30, 'NYC'],
    sample: 'list(person.values())',
    hints: ['Use the values() method and convert to list'],
    validPatterns: [
      /list\s*\(\s*person\.values\s*\(\s*\)\s*\)/,
      /\[\s*\w+\s+for\s+\w+\s+in\s+person\.values\s*\(\s*\)\s*\]/,
    ],
    tags: ['values', 'dict-method'],
  },
  {
    id: 'py-dict-003',
    category: 'dict',
    difficulty: 'easy',
    title: 'Get Dictionary Items',
    text: 'Get all key-value pairs as a list of tuples. The result should be [("name", "Alice"), ("age", 30)].',
    setup: 'person = {"name": "Alice", "age": 30}',
    setupCode: 'person = {"name": "Alice", "age": 30}',
    expected: [['name', 'Alice'], ['age', 30]],
    sample: 'list(person.items())',
    hints: ['Use the items() method and convert to list', 'items() returns tuples of (key, value)'],
    validPatterns: [
      /list\s*\(\s*person\.items\s*\(\s*\)\s*\)/,
      /\[\s*\(\s*k\s*,\s*v\s*\)\s+for\s+k\s*,\s*v\s+in\s+person\.items\s*\(\s*\)\s*\]/,
      /\[\s*\(\s*\w+\s*,\s*\w+\s*\)\s+for\s+\w+\s*,\s*\w+\s+in\s+person\.items\s*\(\s*\)\s*\]/,
    ],
    tags: ['items', 'dict-method'],
  },
  {
    id: 'py-dict-004',
    category: 'dict',
    difficulty: 'easy',
    title: 'Get with Default',
    text: 'Get the value for key "country" with a default of "Unknown"',
    setup: 'person = {"name": "Alice", "age": 30}',
    setupCode: 'person = {"name": "Alice", "age": 30}',
    expected: 'Unknown',
    sample: 'person.get("country", "Unknown")',
    hints: ['Use the get() method with a default value'],
    validPatterns: [
      /person\.get\s*\(\s*["']country["']\s*,\s*["']Unknown["']\s*\)/,
    ],
    tags: ['get', 'dict-method'],
  },
  {
    id: 'py-dict-005',
    category: 'dict',
    difficulty: 'medium',
    title: 'Set Default Value',
    text: 'Get "score" from dict, setting it to 0 if not present (use setdefault)',
    setup: 'data = {"name": "Alice"}',
    setupCode: 'data = {"name": "Alice"}',
    expected: 0,
    sample: 'data.setdefault("score", 0)',
    hints: ['Use setdefault() to get or set a default value'],
    validPatterns: [
      /data\.setdefault\s*\(\s*["']score["']\s*,\s*0\s*\)/,
    ],
    tags: ['setdefault', 'dict-method'],
  },
  {
    id: 'py-dict-006',
    category: 'dict',
    difficulty: 'easy',
    title: 'Update Dictionary',
    text: 'Merge additional data into the original dictionary and return it',
    setup: 'original = {"a": 1, "b": 2}\nadditional = {"c": 3, "d": 4}',
    setupCode: 'original = {"a": 1, "b": 2}\nadditional = {"c": 3, "d": 4}',
    expected: { a: 1, b: 2, c: 3, d: 4 },
    sample: 'original.update(additional) or original',
    hints: ['Use the update() method to merge dictionaries'],
    validPatterns: [
      /original\.update\s*\(\s*additional\s*\)/,
      /\{\s*\*\*original\s*,\s*\*\*additional\s*\}/,
      /original\s*\|\s*additional/,
    ],
    tags: ['update', 'dict-method'],
  },
  {
    id: 'py-dict-007',
    category: 'dict',
    difficulty: 'medium',
    title: 'Dict Comprehension',
    text: 'Create a dictionary mapping each number to its square',
    setup: 'nums = [1, 2, 3, 4, 5]',
    setupCode: 'nums = [1, 2, 3, 4, 5]',
    expected: { 1: 1, 2: 4, 3: 9, 4: 16, 5: 25 },
    sample: '{x: x**2 for x in nums}',
    hints: ['Use dict comprehension: {key: value for item in iterable}'],
    validPatterns: [
      /\{\s*\w+\s*:\s*\w+\s*\*\*\s*2\s+for\s+\w+\s+in\s+nums\s*\}/,
      /\{\s*\w+\s*:\s*pow\s*\(\s*\w+\s*,\s*2\s*\)\s+for\s+\w+\s+in\s+nums\s*\}/,
      /dict\s*\(\s*\[\s*\(\s*\w+\s*,\s*\w+\s*\*\*\s*2\s*\)\s+for\s+\w+\s+in\s+nums\s*\]\s*\)/,
    ],
    tags: ['dict-comprehension'],
  },
  {
    id: 'py-dict-008',
    category: 'dict',
    difficulty: 'medium',
    title: 'Filter Dict Comprehension',
    text: 'Create a new dictionary with only entries where value > 2',
    setup: 'scores = {"a": 1, "b": 3, "c": 2, "d": 4}',
    setupCode: 'scores = {"a": 1, "b": 3, "c": 2, "d": 4}',
    expected: { b: 3, d: 4 },
    sample: '{k: v for k, v in scores.items() if v > 2}',
    hints: ['Use dict comprehension with a condition'],
    validPatterns: [
      /\{\s*\w+\s*:\s*\w+\s+for\s+\w+\s*,\s*\w+\s+in\s+scores\.items\s*\(\s*\)\s+if\s+\w+\s*>\s*2\s*\}/,
    ],
    tags: ['dict-comprehension', 'filter'],
  },
  {
    id: 'py-dict-009',
    category: 'dict',
    difficulty: 'medium',
    title: 'Pop from Dictionary',
    text: 'Remove and return the value for key "age"',
    setup: 'person = {"name": "Alice", "age": 30, "city": "NYC"}',
    setupCode: 'person = {"name": "Alice", "age": 30, "city": "NYC"}',
    expected: 30,
    sample: 'person.pop("age")',
    hints: ['Use the pop() method to remove and return a value'],
    validPatterns: [
      /person\.pop\s*\(\s*["']age["']\s*\)/,
    ],
    tags: ['pop', 'dict-method'],
  },
  {
    id: 'py-dict-010',
    category: 'dict',
    difficulty: 'medium',
    title: 'Create Dict from Keys',
    text: 'Create a dictionary with the given keys, all with value 0',
    setup: 'keys = ["a", "b", "c", "d"]',
    setupCode: 'keys = ["a", "b", "c", "d"]',
    expected: { a: 0, b: 0, c: 0, d: 0 },
    sample: 'dict.fromkeys(keys, 0)',
    hints: ['Use dict.fromkeys() to create a dictionary with default values'],
    validPatterns: [
      /dict\.fromkeys\s*\(\s*keys\s*,\s*0\s*\)/,
      /\{\s*\w+\s*:\s*0\s+for\s+\w+\s+in\s+keys\s*\}/,
    ],
    tags: ['fromkeys', 'dict-method'],
  },
  {
    id: 'py-dict-011',
    category: 'dict',
    difficulty: 'medium',
    title: 'Invert Dictionary',
    text: 'Swap keys and values in the dictionary',
    setup: 'original = {"a": 1, "b": 2, "c": 3}',
    setupCode: 'original = {"a": 1, "b": 2, "c": 3}',
    expected: { 1: 'a', 2: 'b', 3: 'c' },
    sample: '{v: k for k, v in original.items()}',
    hints: ['Use dict comprehension to swap keys and values'],
    validPatterns: [
      /\{\s*\w+\s*:\s*\w+\s+for\s+\w+\s*,\s*\w+\s+in\s+original\.items\s*\(\s*\)\s*\}/,
      /dict\s*\(\s*\[\s*\(\s*\w+\s*,\s*\w+\s*\)\s+for\s+\w+\s*,\s*\w+\s+in\s+original\.items\s*\(\s*\)\s*\]\s*\)/,
    ],
    tags: ['dict-comprehension', 'invert'],
  },

  // ============================================================
  // SET METHODS (5+ problems)
  // ============================================================
  {
    id: 'py-set-001',
    category: 'set',
    difficulty: 'easy',
    title: 'Create Set from List',
    text: 'Remove duplicates from the list by converting to a set and back to list',
    setup: 'nums = [1, 2, 2, 3, 3, 3, 4, 4, 5]',
    setupCode: 'nums = [1, 2, 2, 3, 3, 3, 4, 4, 5]',
    expected: [1, 2, 3, 4, 5],
    sample: 'list(set(nums))',
    hints: ['Convert to set to remove duplicates, then back to list'],
    validPatterns: [
      /list\s*\(\s*set\s*\(\s*nums\s*\)\s*\)/,
      /sorted\s*\(\s*set\s*\(\s*nums\s*\)\s*\)/,
    ],
    tags: ['set', 'conversion'],
  },
  {
    id: 'py-set-002',
    category: 'set',
    difficulty: 'easy',
    title: 'Set Union',
    text: 'Combine two sets to get all unique elements',
    setup: 'set1 = {1, 2, 3}\nset2 = {3, 4, 5}',
    setupCode: 'set1 = {1, 2, 3}\nset2 = {3, 4, 5}',
    expected: [1, 2, 3, 4, 5],
    sample: 'set1.union(set2)',
    hints: ['Use the union() method or | operator'],
    validPatterns: [
      /set1\.union\s*\(\s*set2\s*\)/,
      /set1\s*\|\s*set2/,
      /set2\.union\s*\(\s*set1\s*\)/,
      /set2\s*\|\s*set1/,
    ],
    tags: ['union', 'set-method'],
  },
  {
    id: 'py-set-003',
    category: 'set',
    difficulty: 'easy',
    title: 'Set Intersection',
    text: 'Find elements that exist in both sets',
    setup: 'set1 = {1, 2, 3, 4}\nset2 = {3, 4, 5, 6}',
    setupCode: 'set1 = {1, 2, 3, 4}\nset2 = {3, 4, 5, 6}',
    expected: [3, 4],
    sample: 'set1.intersection(set2)',
    hints: ['Use the intersection() method or & operator'],
    validPatterns: [
      /set1\.intersection\s*\(\s*set2\s*\)/,
      /set1\s*&\s*set2/,
      /set2\.intersection\s*\(\s*set1\s*\)/,
      /set2\s*&\s*set1/,
    ],
    tags: ['intersection', 'set-method'],
  },
  {
    id: 'py-set-004',
    category: 'set',
    difficulty: 'easy',
    title: 'Set Difference',
    text: 'Find elements in set1 that are not in set2',
    setup: 'set1 = {1, 2, 3, 4, 5}\nset2 = {4, 5, 6, 7}',
    setupCode: 'set1 = {1, 2, 3, 4, 5}\nset2 = {4, 5, 6, 7}',
    expected: [1, 2, 3],
    sample: 'set1.difference(set2)',
    hints: ['Use the difference() method or - operator'],
    validPatterns: [
      /set1\.difference\s*\(\s*set2\s*\)/,
      /set1\s*-\s*set2/,
    ],
    tags: ['difference', 'set-method'],
  },
  {
    id: 'py-set-005',
    category: 'set',
    difficulty: 'medium',
    title: 'Set Comprehension',
    text: 'Create a set of squares from the numbers using set comprehension',
    setup: 'nums = [1, 2, 2, 3, 3, 4]',
    setupCode: 'nums = [1, 2, 2, 3, 3, 4]',
    expected: [1, 4, 9, 16],
    sample: '{x**2 for x in nums}',
    hints: ['Use set comprehension: {expression for item in iterable}'],
    validPatterns: [
      /\{\s*\w+\s*\*\*\s*2\s+for\s+\w+\s+in\s+nums\s*\}/,
      /set\s*\(\s*\[\s*\w+\s*\*\*\s*2\s+for\s+\w+\s+in\s+nums\s*\]\s*\)/,
    ],
    tags: ['set-comprehension'],
  },
  {
    id: 'py-set-006',
    category: 'set',
    difficulty: 'medium',
    title: 'Check Subset',
    text: 'Check if set1 is a subset of set2',
    setup: 'set1 = {1, 2}\nset2 = {1, 2, 3, 4, 5}',
    setupCode: 'set1 = {1, 2}\nset2 = {1, 2, 3, 4, 5}',
    expected: true,
    sample: 'set1.issubset(set2)',
    hints: ['Use the issubset() method or <= operator'],
    validPatterns: [
      /set1\.issubset\s*\(\s*set2\s*\)/,
      /set1\s*<=\s*set2/,
    ],
    tags: ['issubset', 'set-method'],
  },
  {
    id: 'py-set-007',
    category: 'set',
    difficulty: 'medium',
    title: 'Check Superset',
    text: 'Check if set1 is a superset of set2',
    setup: 'set1 = {1, 2, 3, 4, 5}\nset2 = {2, 3}',
    setupCode: 'set1 = {1, 2, 3, 4, 5}\nset2 = {2, 3}',
    expected: true,
    sample: 'set1.issuperset(set2)',
    hints: ['Use the issuperset() method or >= operator'],
    validPatterns: [
      /set1\.issuperset\s*\(\s*set2\s*\)/,
      /set1\s*>=\s*set2/,
    ],
    tags: ['issuperset', 'set-method'],
  },

  // ============================================================
  // OTHER BUILT-INS (5+ problems)
  // ============================================================
  {
    id: 'py-builtin-001',
    category: 'builtin',
    difficulty: 'easy',
    title: 'Range to List',
    text: 'Create a list of numbers from 0 to 9 using range',
    setup: '# Use range to generate numbers',
    setupCode: '# Use range to generate numbers',
    expected: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    sample: 'list(range(10))',
    hints: ['Use range() and convert to list'],
    validPatterns: [
      /list\s*\(\s*range\s*\(\s*10\s*\)\s*\)/,
      /\[\s*\w+\s+for\s+\w+\s+in\s+range\s*\(\s*10\s*\)\s*\]/,
    ],
    tags: ['range', 'built-in'],
  },
  {
    id: 'py-builtin-002',
    category: 'builtin',
    difficulty: 'easy',
    title: 'Range with Start and Stop',
    text: 'Create a list of numbers from 5 to 14 using range',
    setup: '# Use range with start and stop',
    setupCode: '# Use range with start and stop',
    expected: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
    sample: 'list(range(5, 15))',
    hints: ['Use range(start, stop) where stop is exclusive'],
    validPatterns: [
      /list\s*\(\s*range\s*\(\s*5\s*,\s*15\s*\)\s*\)/,
      /\[\s*\w+\s+for\s+\w+\s+in\s+range\s*\(\s*5\s*,\s*15\s*\)\s*\]/,
    ],
    tags: ['range', 'built-in'],
  },
  {
    id: 'py-builtin-003',
    category: 'builtin',
    difficulty: 'easy',
    title: 'Range with Step',
    text: 'Create a list of even numbers from 0 to 18 using range',
    setup: '# Use range with step',
    setupCode: '# Use range with step',
    expected: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18],
    sample: 'list(range(0, 20, 2))',
    hints: ['Use range(start, stop, step)'],
    validPatterns: [
      /list\s*\(\s*range\s*\(\s*0\s*,\s*20\s*,\s*2\s*\)\s*\)/,
      /list\s*\(\s*range\s*\(\s*0\s*,\s*19\s*,\s*2\s*\)\s*\)/,
      /\[\s*\w+\s+for\s+\w+\s+in\s+range\s*\(\s*0\s*,\s*20\s*,\s*2\s*\)\s*\]/,
    ],
    tags: ['range', 'built-in'],
  },
  {
    id: 'py-builtin-004',
    category: 'builtin',
    difficulty: 'easy',
    title: 'Convert String to Int',
    text: 'Convert the string to an integer',
    setup: 'num_str = "42"',
    setupCode: 'num_str = "42"',
    expected: 42,
    sample: 'int(num_str)',
    hints: ['Use the int() built-in function'],
    validPatterns: [
      /int\s*\(\s*num_str\s*\)/,
    ],
    tags: ['type-conversion', 'built-in'],
  },
  {
    id: 'py-builtin-005',
    category: 'builtin',
    difficulty: 'easy',
    title: 'Convert Int to String',
    text: 'Convert the integer to a string',
    setup: 'num = 42',
    setupCode: 'num = 42',
    expected: '42',
    sample: 'str(num)',
    hints: ['Use the str() built-in function'],
    validPatterns: [
      /str\s*\(\s*num\s*\)/,
      /f["']\{num\}["']/,
    ],
    tags: ['type-conversion', 'built-in'],
  },
  {
    id: 'py-builtin-006',
    category: 'builtin',
    difficulty: 'easy',
    title: 'Convert String to List',
    text: 'Convert the string to a list of characters',
    setup: 'text = "hello"',
    setupCode: 'text = "hello"',
    expected: ['h', 'e', 'l', 'l', 'o'],
    sample: 'list(text)',
    hints: ['Use the list() built-in function'],
    validPatterns: [
      /list\s*\(\s*text\s*\)/,
      /\[\s*\w+\s+for\s+\w+\s+in\s+text\s*\]/,
    ],
    tags: ['type-conversion', 'built-in'],
  },
  {
    id: 'py-builtin-007',
    category: 'builtin',
    difficulty: 'medium',
    title: 'Lambda Function',
    text: 'Create a lambda function that doubles a number and apply it to 5',
    setup: '# Create and use a lambda function',
    setupCode: '# Create and use a lambda function',
    expected: 10,
    sample: '(lambda x: x * 2)(5)',
    hints: ['Use lambda syntax: lambda args: expression'],
    validPatterns: [
      /\(\s*lambda\s+\w+\s*:\s*\w+\s*\*\s*2\s*\)\s*\(\s*5\s*\)/,
      /\(\s*lambda\s+\w+\s*:\s*2\s*\*\s*\w+\s*\)\s*\(\s*5\s*\)/,
    ],
    tags: ['lambda', 'built-in'],
  },
  {
    id: 'py-builtin-008',
    category: 'builtin',
    difficulty: 'medium',
    title: 'Reduce Sum',
    text: 'Use reduce from functools to sum all numbers in the list',
    setup: 'from functools import reduce\nnums = [1, 2, 3, 4, 5]',
    setupCode: 'from functools import reduce\nnums = [1, 2, 3, 4, 5]',
    expected: 15,
    sample: 'reduce(lambda a, b: a + b, nums)',
    hints: ['Import reduce from functools and use with a lambda'],
    validPatterns: [
      /reduce\s*\(\s*lambda\s+\w+\s*,\s*\w+\s*:\s*\w+\s*\+\s*\w+\s*,\s*nums\s*\)/,
    ],
    tags: ['reduce', 'functools'],
  },
  {
    id: 'py-builtin-009',
    category: 'builtin',
    difficulty: 'medium',
    title: 'Reduce Product',
    text: 'Use reduce to calculate the product of all numbers in the list',
    setup: 'from functools import reduce\nnums = [1, 2, 3, 4, 5]',
    setupCode: 'from functools import reduce\nnums = [1, 2, 3, 4, 5]',
    expected: 120,
    sample: 'reduce(lambda a, b: a * b, nums)',
    hints: ['Use reduce with multiplication'],
    validPatterns: [
      /reduce\s*\(\s*lambda\s+\w+\s*,\s*\w+\s*:\s*\w+\s*\*\s*\w+\s*,\s*nums\s*\)/,
    ],
    tags: ['reduce', 'functools'],
  },
  {
    id: 'py-builtin-010',
    category: 'builtin',
    difficulty: 'easy',
    title: 'Absolute Value',
    text: 'Get the absolute value of the number',
    setup: 'num = -42',
    setupCode: 'num = -42',
    expected: 42,
    sample: 'abs(num)',
    hints: ['Use the abs() built-in function'],
    validPatterns: [
      /abs\s*\(\s*num\s*\)/,
    ],
    tags: ['abs', 'built-in'],
  },
  {
    id: 'py-builtin-011',
    category: 'builtin',
    difficulty: 'easy',
    title: 'Round Number',
    text: 'Round the float to 2 decimal places',
    setup: 'num = 3.14159',
    setupCode: 'num = 3.14159',
    expected: 3.14,
    sample: 'round(num, 2)',
    hints: ['Use the round() built-in function with precision'],
    validPatterns: [
      /round\s*\(\s*num\s*,\s*2\s*\)/,
    ],
    tags: ['round', 'built-in'],
  },
  {
    id: 'py-builtin-012',
    category: 'builtin',
    difficulty: 'medium',
    title: 'Filter with Lambda',
    text: 'Use filter() with lambda to get only positive numbers',
    setup: 'nums = [-2, -1, 0, 1, 2, 3]',
    setupCode: 'nums = [-2, -1, 0, 1, 2, 3]',
    expected: [1, 2, 3],
    sample: 'list(filter(lambda x: x > 0, nums))',
    hints: ['Use filter() with a lambda function'],
    validPatterns: [
      /list\s*\(\s*filter\s*\(\s*lambda\s+\w+\s*:\s*\w+\s*>\s*0\s*,\s*nums\s*\)\s*\)/,
      /\[\s*\w+\s+for\s+\w+\s+in\s+nums\s+if\s+\w+\s*>\s*0\s*\]/,
    ],
    tags: ['filter', 'lambda'],
  },
  {
    id: 'py-builtin-013',
    category: 'builtin',
    difficulty: 'medium',
    title: 'Sort by Key',
    text: 'Sort the list of tuples by the second element (age)',
    setup: 'people = [("Alice", 30), ("Bob", 25), ("Charlie", 35)]',
    setupCode: 'people = [("Alice", 30), ("Bob", 25), ("Charlie", 35)]',
    expected: [['Bob', 25], ['Alice', 30], ['Charlie', 35]],
    sample: 'sorted(people, key=lambda x: x[1])',
    hints: ['Use sorted() with a key function'],
    validPatterns: [
      /sorted\s*\(\s*people\s*,\s*key\s*=\s*lambda\s+\w+\s*:\s*\w+\s*\[\s*1\s*\]\s*\)/,
    ],
    tags: ['sorted', 'key', 'lambda'],
  },
  {
    id: 'py-builtin-014',
    category: 'builtin',
    difficulty: 'medium',
    title: 'Sort by String Length',
    text: 'Sort the list of words by their length',
    setup: 'words = ["python", "is", "awesome", "coding"]',
    setupCode: 'words = ["python", "is", "awesome", "coding"]',
    expected: ['is', 'python', 'coding', 'awesome'],
    sample: 'sorted(words, key=len)',
    hints: ['Use len as the key function'],
    validPatterns: [
      /sorted\s*\(\s*words\s*,\s*key\s*=\s*len\s*\)/,
      /sorted\s*\(\s*words\s*,\s*key\s*=\s*lambda\s+\w+\s*:\s*len\s*\(\s*\w+\s*\)\s*\)/,
    ],
    tags: ['sorted', 'key'],
  },
  {
    id: 'py-builtin-015',
    category: 'builtin',
    difficulty: 'medium',
    title: 'Boolean Conversion',
    text: 'Convert the list to a boolean value',
    setup: 'items = [1, 2, 3]',
    setupCode: 'items = [1, 2, 3]',
    expected: true,
    sample: 'bool(items)',
    hints: ['Use bool() - non-empty lists are truthy'],
    validPatterns: [
      /bool\s*\(\s*items\s*\)/,
    ],
    tags: ['bool', 'type-conversion'],
  },

  // ============================================================
  // ADDITIONAL LIST PROBLEMS
  // ============================================================
  {
    id: 'py-list-024',
    category: 'list',
    difficulty: 'medium',
    title: 'Append to List',
    text: 'Append 6 to the list and return the list',
    setup: 'nums = [1, 2, 3, 4, 5]',
    setupCode: 'nums = [1, 2, 3, 4, 5]',
    expected: [1, 2, 3, 4, 5, 6],
    sample: 'nums.append(6) or nums',
    hints: ['Use append() to add an element to the end'],
    validPatterns: [
      /nums\.append\s*\(\s*6\s*\)/,
      /nums\s*\+\s*\[\s*6\s*\]/,
      /\[\s*\*nums\s*,\s*6\s*\]/,
    ],
    tags: ['append', 'list-method'],
  },
  {
    id: 'py-list-025',
    category: 'list',
    difficulty: 'medium',
    title: 'Extend List',
    text: 'Extend nums with more_nums and return the combined list',
    setup: 'nums = [1, 2, 3]\nmore_nums = [4, 5, 6]',
    setupCode: 'nums = [1, 2, 3]\nmore_nums = [4, 5, 6]',
    expected: [1, 2, 3, 4, 5, 6],
    sample: 'nums.extend(more_nums) or nums',
    hints: ['Use extend() to add all elements from another list'],
    validPatterns: [
      /nums\.extend\s*\(\s*more_nums\s*\)/,
      /nums\s*\+\s*more_nums/,
      /\[\s*\*nums\s*,\s*\*more_nums\s*\]/,
    ],
    tags: ['extend', 'list-method'],
  },
  {
    id: 'py-list-026',
    category: 'list',
    difficulty: 'medium',
    title: 'Insert at Index',
    text: 'Insert 10 at index 2 and return the list',
    setup: 'nums = [1, 2, 3, 4, 5]',
    setupCode: 'nums = [1, 2, 3, 4, 5]',
    expected: [1, 2, 10, 3, 4, 5],
    sample: 'nums.insert(2, 10) or nums',
    hints: ['Use insert(index, element) to insert at a specific position'],
    validPatterns: [
      /nums\.insert\s*\(\s*2\s*,\s*10\s*\)/,
    ],
    tags: ['insert', 'list-method'],
  },
  {
    id: 'py-list-027',
    category: 'list',
    difficulty: 'medium',
    title: 'Pop Last Element',
    text: 'Remove and return the last element from the list',
    setup: 'nums = [1, 2, 3, 4, 5]',
    setupCode: 'nums = [1, 2, 3, 4, 5]',
    expected: 5,
    sample: 'nums.pop()',
    hints: ['Use pop() without arguments to remove the last element'],
    validPatterns: [
      /nums\.pop\s*\(\s*\)/,
      /nums\s*\[\s*-1\s*\]/,
    ],
    tags: ['pop', 'list-method'],
  },
  {
    id: 'py-list-028',
    category: 'list',
    difficulty: 'medium',
    title: 'Pop at Index',
    text: 'Remove and return the element at index 2',
    setup: 'nums = [1, 2, 3, 4, 5]',
    setupCode: 'nums = [1, 2, 3, 4, 5]',
    expected: 3,
    sample: 'nums.pop(2)',
    hints: ['Use pop(index) to remove and return element at specific index'],
    validPatterns: [
      /nums\.pop\s*\(\s*2\s*\)/,
    ],
    tags: ['pop', 'list-method'],
  },
  {
    id: 'py-list-029',
    category: 'list',
    difficulty: 'medium',
    title: 'Remove by Value',
    text: 'Remove the first occurrence of 3 from the list and return the list',
    setup: 'nums = [1, 2, 3, 4, 3, 5]',
    setupCode: 'nums = [1, 2, 3, 4, 3, 5]',
    expected: [1, 2, 4, 3, 5],
    sample: 'nums.remove(3) or nums',
    hints: ['Use remove() to remove the first occurrence of a value'],
    validPatterns: [
      /nums\.remove\s*\(\s*3\s*\)/,
    ],
    tags: ['remove', 'list-method'],
  },
  {
    id: 'py-list-030',
    category: 'list',
    difficulty: 'hard',
    title: 'List Slicing Middle',
    text: 'Get elements from index 2 to 5 (exclusive)',
    setup: 'nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]',
    setupCode: 'nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]',
    expected: [2, 3, 4],
    sample: 'nums[2:5]',
    hints: ['Use slice notation: list[start:stop]'],
    validPatterns: [
      /nums\s*\[\s*2\s*:\s*5\s*\]/,
    ],
    tags: ['slicing', 'list'],
  },
  {
    id: 'py-list-031',
    category: 'list',
    difficulty: 'hard',
    title: 'Every Other Element',
    text: 'Get every other element from the list starting from index 0',
    setup: 'nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]',
    setupCode: 'nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]',
    expected: [0, 2, 4, 6, 8],
    sample: 'nums[::2]',
    hints: ['Use slice with step: list[::step]'],
    validPatterns: [
      /nums\s*\[\s*::\s*2\s*\]/,
      /nums\s*\[\s*0\s*:\s*:\s*2\s*\]/,
      /\[\s*\w+\s+for\s+\w+\s+in\s+nums\s+if\s+nums\.index\s*\(\s*\w+\s*\)\s*%\s*2\s*==\s*0\s*\]/,
    ],
    tags: ['slicing', 'list'],
  },
  {
    id: 'py-list-032',
    category: 'list',
    difficulty: 'hard',
    title: 'Nested List Comprehension',
    text: 'Create a multiplication table (3x3) using nested list comprehension',
    setup: '# Create 3x3 multiplication table',
    setupCode: '# Create 3x3 multiplication table',
    expected: [[1, 2, 3], [2, 4, 6], [3, 6, 9]],
    sample: '[[i * j for j in range(1, 4)] for i in range(1, 4)]',
    hints: ['Use nested list comprehensions: [[expr for inner] for outer]'],
    validPatterns: [
      /\[\s*\[\s*\w+\s*\*\s*\w+\s+for\s+\w+\s+in\s+range\s*\(\s*1\s*,\s*4\s*\)\s*\]\s+for\s+\w+\s+in\s+range\s*\(\s*1\s*,\s*4\s*\)\s*\]/,
    ],
    tags: ['list-comprehension', 'nested', 'advanced'],
  },

  // ============================================================
  // ADDITIONAL STRING PROBLEMS
  // ============================================================
  {
    id: 'py-str-022',
    category: 'string',
    difficulty: 'medium',
    title: 'F-String Expression',
    text: 'Create a formatted string showing "The sum of 5 and 3 is 8" using f-string with calculation',
    setup: 'a = 5\nb = 3',
    setupCode: 'a = 5\nb = 3',
    expected: 'The sum of 5 and 3 is 8',
    sample: 'f"The sum of {a} and {b} is {a + b}"',
    hints: ['F-strings can contain expressions inside curly braces'],
    validPatterns: [
      /f["']The sum of \{a\} and \{b\} is \{a\s*\+\s*b\}["']/,
      /f["']The sum of \{a\} and \{b\} is \{\s*a\s*\+\s*b\s*\}["']/,
    ],
    tags: ['f-string', 'formatting', 'expressions'],
  },
  {
    id: 'py-str-023',
    category: 'string',
    difficulty: 'medium',
    title: 'String Center',
    text: 'Center the text in a string of width 20, padded with asterisks',
    setup: 'text = "Python"',
    setupCode: 'text = "Python"',
    expected: '*******Python*******',
    sample: 'text.center(20, "*")',
    hints: ['Use the center() method with width and fill character'],
    validPatterns: [
      /text\.center\s*\(\s*20\s*,\s*["']\*["']\s*\)/,
    ],
    tags: ['center', 'string-method', 'padding'],
  },
  {
    id: 'py-str-024',
    category: 'string',
    difficulty: 'easy',
    title: 'Check Whitespace Only',
    text: 'Check if the string contains only whitespace characters',
    setup: 'text = "   \\t\\n"',
    setupCode: 'text = "   \\t\\n"',
    expected: true,
    sample: 'text.isspace()',
    hints: ['Use the isspace() method'],
    validPatterns: [
      /text\.isspace\s*\(\s*\)/,
    ],
    tags: ['isspace', 'string-method'],
  },
  {
    id: 'py-str-025',
    category: 'string',
    difficulty: 'medium',
    title: 'Partition String',
    text: 'Split the email at "@" using partition, return the username part (before @)',
    setup: 'email = "user@example.com"',
    setupCode: 'email = "user@example.com"',
    expected: 'user',
    sample: 'email.partition("@")[0]',
    hints: ['Use partition() which returns (before, separator, after)', 'Index [0] gets the part before the separator'],
    validPatterns: [
      /email\.partition\s*\(\s*["']@["']\s*\)\s*\[\s*0\s*\]/,
      /email\.split\s*\(\s*["']@["']\s*\)\s*\[\s*0\s*\]/,
    ],
    tags: ['partition', 'string-method'],
  },
  {
    id: 'py-str-026',
    category: 'string',
    difficulty: 'medium',
    title: 'Swapcase',
    text: 'Swap the case of all characters in the string',
    setup: 'text = "Hello World"',
    setupCode: 'text = "Hello World"',
    expected: 'hELLO wORLD',
    sample: 'text.swapcase()',
    hints: ['Use the swapcase() method'],
    validPatterns: [
      /text\.swapcase\s*\(\s*\)/,
    ],
    tags: ['swapcase', 'string-method'],
  },

  // ============================================================
  // ADVANCED DICTIONARY PROBLEMS
  // ============================================================
  {
    id: 'py-dict-012',
    category: 'dict',
    difficulty: 'medium',
    title: 'Merge Dictionaries (Python 3.9+)',
    text: 'Merge dict1 and dict2 using the | operator (creates new dict)',
    setup: 'dict1 = {"a": 1, "b": 2}\ndict2 = {"b": 3, "c": 4}',
    setupCode: 'dict1 = {"a": 1, "b": 2}\ndict2 = {"b": 3, "c": 4}',
    expected: { a: 1, b: 3, c: 4 },
    sample: 'dict1 | dict2',
    hints: ['Use the | operator to merge dictionaries (Python 3.9+)', 'Later values override earlier ones'],
    validPatterns: [
      /dict1\s*\|\s*dict2/,
      /\{\s*\*\*dict1\s*,\s*\*\*dict2\s*\}/,
    ],
    tags: ['merge', 'dict-operator'],
  },
  {
    id: 'py-dict-013',
    category: 'dict',
    difficulty: 'hard',
    title: 'Count Word Frequencies',
    text: 'Count the frequency of each word in the list',
    setup: 'words = ["apple", "banana", "apple", "cherry", "banana", "apple"]',
    setupCode: 'words = ["apple", "banana", "apple", "cherry", "banana", "apple"]',
    expected: { apple: 3, banana: 2, cherry: 1 },
    sample: '{word: words.count(word) for word in set(words)}',
    hints: ['Use dict comprehension with set to get unique words', 'Or use collections.Counter'],
    validPatterns: [
      /\{\s*\w+\s*:\s*words\.count\s*\(\s*\w+\s*\)\s+for\s+\w+\s+in\s+set\s*\(\s*words\s*\)\s*\}/,
      /Counter\s*\(\s*words\s*\)/,
    ],
    tags: ['dict-comprehension', 'counting'],
  },
  {
    id: 'py-dict-014',
    category: 'dict',
    difficulty: 'hard',
    title: 'Group by Length',
    text: 'Group words by their length into a dictionary',
    setup: 'words = ["hi", "hello", "hey", "world", "a"]',
    setupCode: 'words = ["hi", "hello", "hey", "world", "a"]',
    expected: { 1: ['a'], 2: ['hi'], 3: ['hey'], 5: ['hello', 'world'] },
    sample: '{length: [w for w in words if len(w) == length] for length in set(len(w) for w in words)}',
    hints: ['Group by extracting unique lengths first', 'Then filter words matching each length'],
    validPatterns: [
      /\{\s*\w+\s*:\s*\[\s*\w+\s+for\s+\w+\s+in\s+words\s+if\s+len\s*\(\s*\w+\s*\)\s*==\s*\w+\s*\]\s+for\s+\w+\s+in/,
    ],
    tags: ['dict-comprehension', 'grouping', 'advanced'],
  },

  // ============================================================
  // ADVANCED BUILT-IN PROBLEMS
  // ============================================================
  {
    id: 'py-builtin-016',
    category: 'builtin',
    difficulty: 'medium',
    title: 'Check Type',
    text: 'Check if the variable is an instance of list',
    setup: 'data = [1, 2, 3]',
    setupCode: 'data = [1, 2, 3]',
    expected: true,
    sample: 'isinstance(data, list)',
    hints: ['Use isinstance() to check if an object is of a certain type'],
    validPatterns: [
      /isinstance\s*\(\s*data\s*,\s*list\s*\)/,
      /type\s*\(\s*data\s*\)\s*==\s*list/,
    ],
    tags: ['isinstance', 'type-checking'],
  },
  {
    id: 'py-builtin-017',
    category: 'builtin',
    difficulty: 'medium',
    title: 'Chained Comparison',
    text: 'Check if x is between 1 and 10 (inclusive) using chained comparison',
    setup: 'x = 5',
    setupCode: 'x = 5',
    expected: true,
    sample: '1 <= x <= 10',
    hints: ['Python supports chained comparisons'],
    validPatterns: [
      /1\s*<=\s*x\s*<=\s*10/,
      /x\s*>=\s*1\s*and\s*x\s*<=\s*10/,
    ],
    tags: ['comparison', 'pythonic'],
  },
  {
    id: 'py-builtin-018',
    category: 'builtin',
    difficulty: 'hard',
    title: 'Ternary Expression',
    text: 'Use a conditional expression to return "even" if num is even, "odd" otherwise',
    setup: 'num = 7',
    setupCode: 'num = 7',
    expected: 'odd',
    sample: '"even" if num % 2 == 0 else "odd"',
    hints: ['Use Python ternary syntax: value_if_true if condition else value_if_false'],
    validPatterns: [
      /["']even["']\s+if\s+num\s*%\s*2\s*==\s*0\s+else\s+["']odd["']/,
      /["']odd["']\s+if\s+num\s*%\s*2\s*!=?\s*0?\s+else\s+["']even["']/,
      /["']odd["']\s+if\s+num\s*%\s*2\s+else\s+["']even["']/,
    ],
    tags: ['ternary', 'conditional'],
  },
  {
    id: 'py-builtin-019',
    category: 'builtin',
    difficulty: 'medium',
    title: 'Unpack with Star',
    text: 'Unpack the list to get first, middle elements, and last using star expression',
    setup: 'nums = [1, 2, 3, 4, 5]',
    setupCode: 'nums = [1, 2, 3, 4, 5]',
    expected: [2, 3, 4],
    sample: 'first, *middle, last = nums; middle',
    hints: ['Use * to capture multiple elements during unpacking'],
    validPatterns: [
      /\w+\s*,\s*\*\s*\w+\s*,\s*\w+\s*=\s*nums/,
    ],
    tags: ['unpacking', 'star-expression'],
  },
  {
    id: 'py-builtin-020',
    category: 'builtin',
    difficulty: 'medium',
    title: 'Walrus Operator',
    text: 'Use the walrus operator to assign and check length in one expression (return True if length > 3)',
    setup: 'text = "hello"',
    setupCode: 'text = "hello"',
    expected: true,
    sample: '(n := len(text)) > 3',
    hints: ['Use := (walrus operator) to assign within an expression', 'Available in Python 3.8+'],
    validPatterns: [
      /\(\s*\w+\s*:=\s*len\s*\(\s*text\s*\)\s*\)\s*>\s*3/,
      /len\s*\(\s*text\s*\)\s*>\s*3/,
    ],
    tags: ['walrus', 'assignment-expression'],
  },

  // ============================================================
  // SET ADVANCED PROBLEMS
  // ============================================================
  {
    id: 'py-set-008',
    category: 'set',
    difficulty: 'medium',
    title: 'Symmetric Difference',
    text: 'Find elements that are in either set but not in both',
    setup: 'set1 = {1, 2, 3, 4}\nset2 = {3, 4, 5, 6}',
    setupCode: 'set1 = {1, 2, 3, 4}\nset2 = {3, 4, 5, 6}',
    expected: [1, 2, 5, 6],
    sample: 'set1.symmetric_difference(set2)',
    hints: ['Use symmetric_difference() or ^ operator'],
    validPatterns: [
      /set1\.symmetric_difference\s*\(\s*set2\s*\)/,
      /set1\s*\^\s*set2/,
      /\(\s*set1\s*-\s*set2\s*\)\s*\|\s*\(\s*set2\s*-\s*set1\s*\)/,
    ],
    tags: ['symmetric_difference', 'set-method'],
  },
  {
    id: 'py-set-009',
    category: 'set',
    difficulty: 'medium',
    title: 'Check Disjoint',
    text: 'Check if the two sets have no common elements',
    setup: 'set1 = {1, 2, 3}\nset2 = {4, 5, 6}',
    setupCode: 'set1 = {1, 2, 3}\nset2 = {4, 5, 6}',
    expected: true,
    sample: 'set1.isdisjoint(set2)',
    hints: ['Use the isdisjoint() method'],
    validPatterns: [
      /set1\.isdisjoint\s*\(\s*set2\s*\)/,
      /len\s*\(\s*set1\s*&\s*set2\s*\)\s*==\s*0/,
      /not\s+set1\s*&\s*set2/,
    ],
    tags: ['isdisjoint', 'set-method'],
  },

  // ============================================================
  // TUPLE PROBLEMS
  // ============================================================
  {
    id: 'py-tuple-001',
    category: 'tuple',
    difficulty: 'easy',
    title: 'Create Tuple',
    text: 'Create a tuple containing the numbers 1, 2, 3',
    setup: '# Create a tuple',
    setupCode: '# Create a tuple',
    expected: [1, 2, 3],
    sample: '(1, 2, 3)',
    hints: ['Use parentheses to create a tuple: (item1, item2, ...)'],
    validPatterns: [
      /\(\s*1\s*,\s*2\s*,\s*3\s*\)/,
      /tuple\s*\(\s*\[\s*1\s*,\s*2\s*,\s*3\s*\]\s*\)/,
    ],
    tags: ['tuple', 'creation'],
  },
  {
    id: 'py-tuple-002',
    category: 'tuple',
    difficulty: 'easy',
    title: 'Tuple Index',
    text: 'Find the index of "banana" in the tuple',
    setup: 'fruits = ("apple", "banana", "cherry")',
    setupCode: 'fruits = ("apple", "banana", "cherry")',
    expected: 1,
    sample: 'fruits.index("banana")',
    hints: ['Tuples have an index() method like lists'],
    validPatterns: [
      /fruits\.index\s*\(\s*["']banana["']\s*\)/,
    ],
    tags: ['tuple', 'index'],
  },
  {
    id: 'py-tuple-003',
    category: 'tuple',
    difficulty: 'easy',
    title: 'Tuple Count',
    text: 'Count how many times 1 appears in the tuple',
    setup: 'nums = (1, 2, 1, 3, 1, 4)',
    setupCode: 'nums = (1, 2, 1, 3, 1, 4)',
    expected: 3,
    sample: 'nums.count(1)',
    hints: ['Tuples have a count() method like lists'],
    validPatterns: [
      /nums\.count\s*\(\s*1\s*\)/,
    ],
    tags: ['tuple', 'count'],
  },
  {
    id: 'py-tuple-004',
    category: 'tuple',
    difficulty: 'medium',
    title: 'Tuple Unpacking',
    text: 'Unpack the tuple into variables x, y, z and return their sum',
    setup: 'point = (10, 20, 30)',
    setupCode: 'point = (10, 20, 30)',
    expected: 60,
    sample: 'x, y, z = point; x + y + z',
    hints: ['Use tuple unpacking: a, b, c = tuple'],
    validPatterns: [
      /\w+\s*,\s*\w+\s*,\s*\w+\s*=\s*point/,
      /sum\s*\(\s*point\s*\)/,
    ],
    tags: ['tuple', 'unpacking'],
  },

  // ============================================================
  // GENERATOR PROBLEMS
  // ============================================================
  {
    id: 'py-gen-001',
    category: 'generator',
    difficulty: 'medium',
    title: 'Generator Expression Sum',
    text: 'Use a generator expression to sum squares of numbers from 1 to 5',
    setup: '# Sum of squares using generator',
    setupCode: '# Sum of squares using generator',
    expected: 55,
    sample: 'sum(x**2 for x in range(1, 6))',
    hints: ['Generator expressions use parentheses: (expr for x in iterable)', 'More memory efficient than list comprehensions'],
    validPatterns: [
      /sum\s*\(\s*\w+\s*\*\*\s*2\s+for\s+\w+\s+in\s+range\s*\(\s*1\s*,\s*6\s*\)\s*\)/,
      /sum\s*\(\s*\[\s*\w+\s*\*\*\s*2\s+for\s+\w+\s+in\s+range\s*\(\s*1\s*,\s*6\s*\)\s*\]\s*\)/,
    ],
    tags: ['generator', 'sum'],
  },
  {
    id: 'py-gen-002',
    category: 'generator',
    difficulty: 'medium',
    title: 'Generator with Condition',
    text: 'Use a generator expression to find the maximum of even numbers',
    setup: 'nums = [1, 4, 2, 8, 5, 7, 6]',
    setupCode: 'nums = [1, 4, 2, 8, 5, 7, 6]',
    expected: 8,
    sample: 'max(x for x in nums if x % 2 == 0)',
    hints: ['Generator expressions can include conditions'],
    validPatterns: [
      /max\s*\(\s*\w+\s+for\s+\w+\s+in\s+nums\s+if\s+\w+\s*%\s*2\s*==\s*0\s*\)/,
    ],
    tags: ['generator', 'max', 'filter'],
  },
];

export default pythonProblems;
