import type { Problem } from '../types';

export const rProblems: Problem[] = [
  // ============================================================
  // VECTOR OPERATIONS - Easy (8 problems)
  // ============================================================
  {
    id: 'r-vector-001',
    category: 'Vector Operations',
    difficulty: 'easy',
    title: 'Create a Numeric Vector',
    text: 'Create a vector containing the numbers 1, 2, 3, 4, 5 using the c() function.',
    setup: '# Create a numeric vector',
    setupCode: '# Create a numeric vector',
    expected: [1, 2, 3, 4, 5],
    sample: 'c(1, 2, 3, 4, 5)',
    hints: ['Use the c() function to combine values', 'c stands for combine or concatenate'],
    validPatterns: [/c\s*\(/],
    tags: ['vectors', 'c', 'basics'],
  },
  {
    id: 'r-vector-002',
    category: 'Vector Operations',
    difficulty: 'easy',
    title: 'Find Vector Length',
    text: 'Find the length of the given vector using the length() function.',
    setup: 'numbers <- c(10, 20, 30, 40, 50, 60)',
    setupCode: 'numbers <- c(10, 20, 30, 40, 50, 60)',
    expected: 6,
    sample: 'length(numbers)',
    hints: ['Use the length() function', 'It returns the number of elements in a vector'],
    validPatterns: [/length\s*\(/],
    tags: ['vectors', 'length', 'basics'],
  },
  {
    id: 'r-vector-003',
    category: 'Vector Operations',
    difficulty: 'easy',
    title: 'Calculate Vector Sum',
    text: 'Calculate the sum of all elements in the given vector.',
    setup: 'values <- c(5, 10, 15, 20)',
    setupCode: 'values <- c(5, 10, 15, 20)',
    expected: 50,
    sample: 'sum(values)',
    hints: ['Use the sum() function', 'It adds all elements together'],
    validPatterns: [/sum\s*\(/],
    tags: ['vectors', 'sum', 'aggregation'],
  },
  {
    id: 'r-vector-004',
    category: 'Vector Operations',
    difficulty: 'easy',
    title: 'Calculate Vector Mean',
    text: 'Calculate the arithmetic mean (average) of the given vector.',
    setup: 'scores <- c(80, 90, 85, 95, 70)',
    setupCode: 'scores <- c(80, 90, 85, 95, 70)',
    expected: 84,
    sample: 'mean(scores)',
    hints: ['Use the mean() function', 'Mean is the sum divided by count'],
    validPatterns: [/mean\s*\(/],
    tags: ['vectors', 'mean', 'statistics'],
  },
  {
    id: 'r-vector-005',
    category: 'Vector Operations',
    difficulty: 'easy',
    title: 'Find Maximum Value',
    text: 'Find the maximum value in the given vector.',
    setup: 'temps <- c(72, 85, 68, 91, 77)',
    setupCode: 'temps <- c(72, 85, 68, 91, 77)',
    expected: 91,
    sample: 'max(temps)',
    hints: ['Use the max() function', 'It returns the largest element'],
    validPatterns: [/max\s*\(/],
    tags: ['vectors', 'max', 'aggregation'],
  },
  {
    id: 'r-vector-006',
    category: 'Vector Operations',
    difficulty: 'easy',
    title: 'Find Minimum Value',
    text: 'Find the minimum value in the given vector.',
    setup: 'prices <- c(25.99, 19.99, 34.50, 12.00, 28.75)',
    setupCode: 'prices <- c(25.99, 19.99, 34.50, 12.00, 28.75)',
    expected: 12.00,
    sample: 'min(prices)',
    hints: ['Use the min() function', 'It returns the smallest element'],
    validPatterns: [/min\s*\(/],
    tags: ['vectors', 'min', 'aggregation'],
  },
  {
    id: 'r-vector-007',
    category: 'Vector Operations',
    difficulty: 'easy',
    title: 'Sort Vector Ascending',
    text: 'Sort the given vector in ascending order.',
    setup: 'nums <- c(5, 2, 8, 1, 9, 3)',
    setupCode: 'nums <- c(5, 2, 8, 1, 9, 3)',
    expected: [1, 2, 3, 5, 8, 9],
    sample: 'sort(nums)',
    hints: ['Use the sort() function', 'Default sorting is ascending'],
    validPatterns: [/sort\s*\(/],
    tags: ['vectors', 'sort', 'ordering'],
  },
  {
    id: 'r-vector-008',
    category: 'Vector Operations',
    difficulty: 'easy',
    title: 'Reverse a Vector',
    text: 'Reverse the order of elements in the given vector.',
    setup: 'letters_vec <- c("a", "b", "c", "d", "e")',
    setupCode: 'letters_vec <- c("a", "b", "c", "d", "e")',
    expected: ['e', 'd', 'c', 'b', 'a'],
    sample: 'rev(letters_vec)',
    hints: ['Use the rev() function', 'It reverses the element order'],
    validPatterns: [/rev\s*\(/],
    tags: ['vectors', 'rev', 'ordering'],
  },

  // ============================================================
  // STRING FUNCTIONS - Easy (6 problems)
  // ============================================================
  {
    id: 'r-string-001',
    category: 'String Functions',
    difficulty: 'easy',
    title: 'Concatenate Strings with Paste',
    text: 'Join the two strings together with a space between them using paste().',
    setup: 'first <- "Hello"\nsecond <- "World"',
    setupCode: 'first <- "Hello"\nsecond <- "World"',
    expected: 'Hello World',
    sample: 'paste(first, second)',
    hints: ['Use the paste() function', 'Default separator is a space'],
    validPatterns: [/paste\s*\(/],
    tags: ['strings', 'paste', 'concatenation'],
  },
  {
    id: 'r-string-002',
    category: 'String Functions',
    difficulty: 'easy',
    title: 'Get String Length',
    text: 'Find the number of characters in the given string.',
    setup: 'message <- "R Programming"',
    setupCode: 'message <- "R Programming"',
    expected: 13,
    sample: 'nchar(message)',
    hints: ['Use the nchar() function', 'It counts all characters including spaces'],
    validPatterns: [/nchar\s*\(/],
    tags: ['strings', 'nchar', 'length'],
  },
  {
    id: 'r-string-003',
    category: 'String Functions',
    difficulty: 'easy',
    title: 'Convert to Uppercase',
    text: 'Convert the given string to all uppercase letters.',
    setup: 'text <- "data science"',
    setupCode: 'text <- "data science"',
    expected: 'DATA SCIENCE',
    sample: 'toupper(text)',
    hints: ['Use the toupper() function', 'It converts all letters to uppercase'],
    validPatterns: [/toupper\s*\(/],
    tags: ['strings', 'toupper', 'case'],
  },
  {
    id: 'r-string-004',
    category: 'String Functions',
    difficulty: 'easy',
    title: 'Convert to Lowercase',
    text: 'Convert the given string to all lowercase letters.',
    setup: 'title <- "MACHINE LEARNING"',
    setupCode: 'title <- "MACHINE LEARNING"',
    expected: 'machine learning',
    sample: 'tolower(title)',
    hints: ['Use the tolower() function', 'It converts all letters to lowercase'],
    validPatterns: [/tolower\s*\(/],
    tags: ['strings', 'tolower', 'case'],
  },
  {
    id: 'r-string-005',
    category: 'String Functions',
    difficulty: 'easy',
    title: 'Extract Substring',
    text: 'Extract characters 1 through 5 from the given string.',
    setup: 'word <- "Statistics"',
    setupCode: 'word <- "Statistics"',
    expected: 'Stati',
    sample: 'substr(word, 1, 5)',
    hints: ['Use the substr() function', 'Provide start and stop positions'],
    validPatterns: [/substr\s*\(/],
    tags: ['strings', 'substr', 'extraction'],
  },
  {
    id: 'r-string-006',
    category: 'String Functions',
    difficulty: 'easy',
    title: 'Paste with Custom Separator',
    text: 'Join the three words with a hyphen separator.',
    setup: 'w1 <- "one"\nw2 <- "two"\nw3 <- "three"',
    setupCode: 'w1 <- "one"\nw2 <- "two"\nw3 <- "three"',
    expected: 'one-two-three',
    sample: 'paste(w1, w2, w3, sep = "-")',
    hints: ['Use paste() with sep argument', 'sep defines the separator between elements'],
    validPatterns: [/paste\s*\(/, /sep\s*=/],
    tags: ['strings', 'paste', 'separator'],
  },

  // ============================================================
  // LIST OPERATIONS - Easy (3 problems)
  // ============================================================
  {
    id: 'r-list-001',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Create a Named List',
    text: 'Create a list with name="Alice" and age=30.',
    setup: '# Create a named list',
    setupCode: '# Create a named list',
    expected: { name: 'Alice', age: 30 },
    sample: 'list(name = "Alice", age = 30)',
    hints: ['Use the list() function', 'Assign names with = inside list()'],
    validPatterns: [/list\s*\(/],
    tags: ['lists', 'list', 'creation'],
  },
  {
    id: 'r-list-002',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Get List Element Names',
    text: 'Get the names of all elements in the given list.',
    setup: 'person <- list(name = "Bob", age = 25, city = "NYC")',
    setupCode: 'person <- list(name = "Bob", age = 25, city = "NYC")',
    expected: ['name', 'age', 'city'],
    sample: 'names(person)',
    hints: ['Use the names() function', 'It returns a character vector of names'],
    validPatterns: [/names\s*\(/],
    tags: ['lists', 'names', 'attributes'],
  },
  {
    id: 'r-list-003',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Access List Element by Name',
    text: 'Extract the "city" element from the list using $ notation.',
    setup: 'info <- list(name = "Carol", age = 28, city = "Boston")',
    setupCode: 'info <- list(name = "Carol", age = 28, city = "Boston")',
    expected: 'Boston',
    sample: 'info$city',
    hints: ['Use the $ operator to access by name', 'Syntax is list$elementname'],
    validPatterns: [/\$city/],
    tags: ['lists', 'access', 'dollar'],
  },

  // ============================================================
  // DATA FRAME BASICS - Easy (2 problems)
  // ============================================================
  {
    id: 'r-dataframe-001',
    category: 'Data Frame Basics',
    difficulty: 'easy',
    title: 'Get Number of Rows',
    text: 'Find the number of rows in the given data frame.',
    setup: 'df <- data.frame(x = 1:5, y = c("a", "b", "c", "d", "e"))',
    setupCode: 'df <- data.frame(x = 1:5, y = c("a", "b", "c", "d", "e"))',
    expected: 5,
    sample: 'nrow(df)',
    hints: ['Use the nrow() function', 'It returns the number of rows'],
    validPatterns: [/nrow\s*\(/],
    tags: ['dataframes', 'nrow', 'dimensions'],
  },
  {
    id: 'r-dataframe-002',
    category: 'Data Frame Basics',
    difficulty: 'easy',
    title: 'Get Number of Columns',
    text: 'Find the number of columns in the given data frame.',
    setup: 'df <- data.frame(a = 1:3, b = 4:6, c = 7:9, d = 10:12)',
    setupCode: 'df <- data.frame(a = 1:3, b = 4:6, c = 7:9, d = 10:12)',
    expected: 4,
    sample: 'ncol(df)',
    hints: ['Use the ncol() function', 'It returns the number of columns'],
    validPatterns: [/ncol\s*\(/],
    tags: ['dataframes', 'ncol', 'dimensions'],
  },

  // ============================================================
  // MATH FUNCTIONS - Easy (1 problem)
  // ============================================================
  {
    id: 'r-math-001',
    category: 'Math Functions',
    difficulty: 'easy',
    title: 'Calculate Square Root',
    text: 'Calculate the square root of 144.',
    setup: 'num <- 144',
    setupCode: 'num <- 144',
    expected: 12,
    sample: 'sqrt(num)',
    hints: ['Use the sqrt() function', 'Square root of 144 is 12'],
    validPatterns: [/sqrt\s*\(/],
    tags: ['math', 'sqrt', 'arithmetic'],
  },

  // ============================================================
  // VECTOR OPERATIONS - Medium (4 problems)
  // ============================================================
  {
    id: 'r-vector-009',
    category: 'Vector Operations',
    difficulty: 'medium',
    title: 'Get Unique Values',
    text: 'Extract all unique values from the vector that contains duplicates.',
    setup: 'data <- c(1, 2, 2, 3, 3, 3, 4, 4, 4, 4)',
    setupCode: 'data <- c(1, 2, 2, 3, 3, 3, 4, 4, 4, 4)',
    expected: [1, 2, 3, 4],
    sample: 'unique(data)',
    hints: ['Use the unique() function', 'It removes duplicate values'],
    validPatterns: [/unique\s*\(/],
    tags: ['vectors', 'unique', 'duplicates'],
  },
  {
    id: 'r-vector-010',
    category: 'Vector Operations',
    difficulty: 'medium',
    title: 'Sort Vector Descending',
    text: 'Sort the given vector in descending order (largest to smallest).',
    setup: 'values <- c(15, 8, 23, 4, 16)',
    setupCode: 'values <- c(15, 8, 23, 4, 16)',
    expected: [23, 16, 15, 8, 4],
    sample: 'sort(values, decreasing = TRUE)',
    hints: ['Use sort() with decreasing argument', 'Set decreasing = TRUE'],
    validPatterns: [/sort\s*\(/, /decreasing\s*=\s*TRUE/],
    tags: ['vectors', 'sort', 'ordering'],
  },
  {
    id: 'r-vector-011',
    category: 'Vector Operations',
    difficulty: 'medium',
    title: 'Filter Even Numbers',
    text: 'Extract only the even numbers from the vector using logical indexing.',
    setup: 'numbers <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)',
    setupCode: 'numbers <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)',
    expected: [2, 4, 6, 8, 10],
    sample: 'numbers[numbers %% 2 == 0]',
    hints: ['Use modulo operator %% to check for even', 'Use logical indexing with []'],
    validPatterns: [/%%/, /==\s*0/],
    tags: ['vectors', 'filtering', 'modulo'],
  },
  {
    id: 'r-vector-012',
    category: 'Vector Operations',
    difficulty: 'medium',
    title: 'Calculate Range',
    text: 'Find the range (difference between max and min) of the vector.',
    setup: 'temps <- c(55, 72, 68, 81, 59, 65)',
    setupCode: 'temps <- c(55, 72, 68, 81, 59, 65)',
    expected: 26,
    sample: 'max(temps) - min(temps)',
    hints: ['Range is max minus min', 'Use both max() and min() functions'],
    validPatterns: [/max\s*\(/, /min\s*\(/],
    tags: ['vectors', 'range', 'statistics'],
  },

  // ============================================================
  // STRING FUNCTIONS - Medium (5 problems)
  // ============================================================
  {
    id: 'r-string-007',
    category: 'String Functions',
    difficulty: 'medium',
    title: 'Split String by Delimiter',
    text: 'Split the CSV string by commas into a vector of individual items.',
    setup: 'csv <- "apple,banana,cherry,date"',
    setupCode: 'csv <- "apple,banana,cherry,date"',
    expected: [['apple', 'banana', 'cherry', 'date']],
    sample: 'strsplit(csv, ",")',
    hints: ['Use the strsplit() function', 'First argument is string, second is delimiter'],
    validPatterns: [/strsplit\s*\(/],
    tags: ['strings', 'strsplit', 'splitting'],
  },
  {
    id: 'r-string-008',
    category: 'String Functions',
    difficulty: 'medium',
    title: 'Replace Pattern with gsub',
    text: 'Replace all spaces in the string with underscores.',
    setup: 'sentence <- "this is a test"',
    setupCode: 'sentence <- "this is a test"',
    expected: 'this_is_a_test',
    sample: 'gsub(" ", "_", sentence)',
    hints: ['Use gsub() for global substitution', 'Arguments: pattern, replacement, string'],
    validPatterns: [/gsub\s*\(/],
    tags: ['strings', 'gsub', 'replacement'],
  },
  {
    id: 'r-string-009',
    category: 'String Functions',
    difficulty: 'medium',
    title: 'Paste with Collapse',
    text: 'Combine the vector of words into a single string separated by spaces.',
    setup: 'words <- c("R", "is", "awesome")',
    setupCode: 'words <- c("R", "is", "awesome")',
    expected: 'R is awesome',
    sample: 'paste(words, collapse = " ")',
    hints: ['Use paste() with collapse argument', 'collapse joins vector elements into one string'],
    validPatterns: [/paste\s*\(/, /collapse\s*=/],
    tags: ['strings', 'paste', 'collapse'],
  },
  {
    id: 'r-string-010',
    category: 'String Functions',
    difficulty: 'medium',
    title: 'Extract Last N Characters',
    text: 'Extract the last 4 characters from the string.',
    setup: 'filename <- "report2023.csv"',
    setupCode: 'filename <- "report2023.csv"',
    expected: '.csv',
    sample: 'substr(filename, nchar(filename) - 3, nchar(filename))',
    hints: ['Combine substr() with nchar()', 'Calculate the start position dynamically'],
    validPatterns: [/substr\s*\(/, /nchar\s*\(/],
    tags: ['strings', 'substr', 'nchar'],
  },
  {
    id: 'r-string-011',
    category: 'String Functions',
    difficulty: 'medium',
    title: 'Remove Digits from String',
    text: 'Remove all digits from the given string using gsub.',
    setup: 'mixed <- "abc123def456"',
    setupCode: 'mixed <- "abc123def456"',
    expected: 'abcdef',
    sample: 'gsub("[0-9]", "", mixed)',
    hints: ['Use gsub() with regex pattern', '[0-9] matches any digit'],
    validPatterns: [/gsub\s*\(/, /\[0-9\]/],
    tags: ['strings', 'gsub', 'regex'],
  },

  // ============================================================
  // LIST OPERATIONS - Medium (4 problems)
  // ============================================================
  {
    id: 'r-list-004',
    category: 'List Operations',
    difficulty: 'medium',
    title: 'Apply Function to List with lapply',
    text: 'Use lapply to find the length of each element in the list.',
    setup: 'items <- list(a = 1:5, b = 1:10, c = 1:3)',
    setupCode: 'items <- list(a = 1:5, b = 1:10, c = 1:3)',
    expected: { a: 5, b: 10, c: 3 },
    sample: 'lapply(items, length)',
    hints: ['Use lapply() to apply a function to each element', 'First arg is list, second is function'],
    validPatterns: [/lapply\s*\(/],
    tags: ['lists', 'lapply', 'apply'],
  },
  {
    id: 'r-list-005',
    category: 'List Operations',
    difficulty: 'medium',
    title: 'Simplify with sapply',
    text: 'Use sapply to calculate the mean of each numeric vector in the list and return a simple vector.',
    setup: 'data <- list(x = c(1, 2, 3), y = c(10, 20, 30), z = c(5, 5, 5))',
    setupCode: 'data <- list(x = c(1, 2, 3), y = c(10, 20, 30), z = c(5, 5, 5))',
    expected: { x: 2, y: 20, z: 5 },
    sample: 'sapply(data, mean)',
    hints: ['sapply simplifies output when possible', 'It returns a vector instead of list'],
    validPatterns: [/sapply\s*\(/],
    tags: ['lists', 'sapply', 'apply'],
  },
  {
    id: 'r-list-006',
    category: 'List Operations',
    difficulty: 'medium',
    title: 'Modify List Names',
    text: 'Change the names of the list elements to "first", "second", "third".',
    setup: 'my_list <- list(a = 1, b = 2, c = 3)',
    setupCode: 'my_list <- list(a = 1, b = 2, c = 3)',
    expected: ['first', 'second', 'third'],
    sample: 'names(my_list) <- c("first", "second", "third"); names(my_list)',
    hints: ['Assign new values to names()', 'names() can be used on left side of assignment'],
    validPatterns: [/names\s*\(/, /<-/],
    tags: ['lists', 'names', 'modification'],
  },
  {
    id: 'r-list-007',
    category: 'List Operations',
    difficulty: 'medium',
    title: 'Apply Custom Function with lapply',
    text: 'Use lapply to square each numeric value in the list.',
    setup: 'nums <- list(a = 2, b = 3, c = 4, d = 5)',
    setupCode: 'nums <- list(a = 2, b = 3, c = 4, d = 5)',
    expected: { a: 4, b: 9, c: 16, d: 25 },
    sample: 'lapply(nums, function(x) x^2)',
    hints: ['Use anonymous function inside lapply', 'function(x) x^2 squares the input'],
    validPatterns: [/lapply\s*\(/, /function\s*\(/],
    tags: ['lists', 'lapply', 'anonymous-function'],
  },

  // ============================================================
  // DATA FRAME BASICS - Medium (4 problems)
  // ============================================================
  {
    id: 'r-dataframe-003',
    category: 'Data Frame Basics',
    difficulty: 'medium',
    title: 'Create a Data Frame',
    text: 'Create a data frame with columns: name (character) and score (numeric).',
    setup: '# Create a data frame with 3 students',
    setupCode: '# Create a data frame with 3 students',
    expected: { name: ['Alice', 'Bob', 'Carol'], score: [85, 92, 78] },
    sample: 'data.frame(name = c("Alice", "Bob", "Carol"), score = c(85, 92, 78))',
    hints: ['Use data.frame() to create', 'Each column is a named vector'],
    validPatterns: [/data\.frame\s*\(/],
    tags: ['dataframes', 'creation', 'data.frame'],
  },
  {
    id: 'r-dataframe-004',
    category: 'Data Frame Basics',
    difficulty: 'medium',
    title: 'Subset Rows by Condition',
    text: 'Get all rows where age is greater than 25.',
    setup: 'df <- data.frame(name = c("Amy", "Ben", "Cal"), age = c(22, 28, 35))',
    setupCode: 'df <- data.frame(name = c("Amy", "Ben", "Cal"), age = c(22, 28, 35))',
    expected: { name: ['Ben', 'Cal'], age: [28, 35] },
    sample: 'subset(df, age > 25)',
    hints: ['Use the subset() function', 'Second argument is the condition'],
    validPatterns: [/subset\s*\(/],
    tags: ['dataframes', 'subset', 'filtering'],
  },
  {
    id: 'r-dataframe-005',
    category: 'Data Frame Basics',
    difficulty: 'medium',
    title: 'Select Specific Columns',
    text: 'Select only the name and city columns from the data frame.',
    setup: 'df <- data.frame(name = c("X", "Y"), age = c(20, 30), city = c("LA", "NY"))',
    setupCode: 'df <- data.frame(name = c("X", "Y"), age = c(20, 30), city = c("LA", "NY"))',
    expected: { name: ['X', 'Y'], city: ['LA', 'NY'] },
    sample: 'subset(df, select = c(name, city))',
    hints: ['Use subset() with select argument', 'select specifies which columns to keep'],
    validPatterns: [/subset\s*\(/, /select\s*=/],
    tags: ['dataframes', 'subset', 'columns'],
  },
  {
    id: 'r-dataframe-006',
    category: 'Data Frame Basics',
    difficulty: 'medium',
    title: 'Access Column as Vector',
    text: 'Extract the "price" column as a vector using $ notation.',
    setup: 'products <- data.frame(item = c("A", "B", "C"), price = c(10, 20, 30))',
    setupCode: 'products <- data.frame(item = c("A", "B", "C"), price = c(10, 20, 30))',
    expected: [10, 20, 30],
    sample: 'products$price',
    hints: ['Use $ operator to access columns', 'Returns a vector'],
    validPatterns: [/\$price/],
    tags: ['dataframes', 'access', 'dollar'],
  },

  // ============================================================
  // MATH FUNCTIONS - Medium (3 problems)
  // ============================================================
  {
    id: 'r-math-002',
    category: 'Math Functions',
    difficulty: 'medium',
    title: 'Calculate Absolute Values',
    text: 'Find the absolute values of all elements in the vector.',
    setup: 'values <- c(-5, 3, -8, 12, -1)',
    setupCode: 'values <- c(-5, 3, -8, 12, -1)',
    expected: [5, 3, 8, 12, 1],
    sample: 'abs(values)',
    hints: ['Use the abs() function', 'It works on entire vectors'],
    validPatterns: [/abs\s*\(/],
    tags: ['math', 'abs', 'vectors'],
  },
  {
    id: 'r-math-003',
    category: 'Math Functions',
    difficulty: 'medium',
    title: 'Round to Decimal Places',
    text: 'Round the numbers to 2 decimal places.',
    setup: 'prices <- c(10.567, 23.891, 5.123, 99.999)',
    setupCode: 'prices <- c(10.567, 23.891, 5.123, 99.999)',
    expected: [10.57, 23.89, 5.12, 100],
    sample: 'round(prices, 2)',
    hints: ['Use round() with digits argument', 'Second argument specifies decimal places'],
    validPatterns: [/round\s*\(/],
    tags: ['math', 'round', 'precision'],
  },
  {
    id: 'r-math-004',
    category: 'Math Functions',
    difficulty: 'medium',
    title: 'Apply Ceiling Function',
    text: 'Round all numbers up to the nearest integer using ceiling.',
    setup: 'nums <- c(1.2, 2.7, 3.0, 4.5, 5.9)',
    setupCode: 'nums <- c(1.2, 2.7, 3.0, 4.5, 5.9)',
    expected: [2, 3, 3, 5, 6],
    sample: 'ceiling(nums)',
    hints: ['Use the ceiling() function', 'It always rounds up'],
    validPatterns: [/ceiling\s*\(/],
    tags: ['math', 'ceiling', 'rounding'],
  },

  // ============================================================
  // VECTOR OPERATIONS - Hard (2 problems)
  // ============================================================
  {
    id: 'r-vector-013',
    category: 'Vector Operations',
    difficulty: 'hard',
    title: 'Find Values Above Mean',
    text: 'Extract all values that are above the mean of the vector.',
    setup: 'scores <- c(45, 72, 89, 56, 91, 68, 77, 83)',
    setupCode: 'scores <- c(45, 72, 89, 56, 91, 68, 77, 83)',
    expected: [72, 89, 91, 77, 83],
    sample: 'scores[scores > mean(scores)]',
    hints: ['Calculate mean inside the condition', 'Use logical indexing with comparison'],
    validPatterns: [/mean\s*\(/, />/],
    tags: ['vectors', 'filtering', 'statistics'],
  },
  {
    id: 'r-vector-014',
    category: 'Vector Operations',
    difficulty: 'hard',
    title: 'Combine and Sort Unique Values',
    text: 'Combine two vectors, remove duplicates, and sort in descending order.',
    setup: 'v1 <- c(5, 3, 8, 3, 1)\nv2 <- c(8, 2, 5, 9, 1)',
    setupCode: 'v1 <- c(5, 3, 8, 3, 1)\nv2 <- c(8, 2, 5, 9, 1)',
    expected: [9, 8, 5, 3, 2, 1],
    sample: 'sort(unique(c(v1, v2)), decreasing = TRUE)',
    hints: ['First combine with c()', 'Then unique(), then sort()'],
    validPatterns: [/sort\s*\(/, /unique\s*\(/, /c\s*\(/],
    tags: ['vectors', 'combining', 'unique', 'sort'],
  },

  // ============================================================
  // STRING FUNCTIONS - Hard (2 problems)
  // ============================================================
  {
    id: 'r-string-012',
    category: 'String Functions',
    difficulty: 'hard',
    title: 'Extract Domain from Email',
    text: 'Extract the domain (part after @) from the email address.',
    setup: 'email <- "user@example.com"',
    setupCode: 'email <- "user@example.com"',
    expected: 'example.com',
    sample: 'strsplit(email, "@")[[1]][2]',
    hints: ['Split by @ symbol', 'Access second element of result'],
    validPatterns: [/strsplit\s*\(/, /@/],
    tags: ['strings', 'strsplit', 'extraction'],
  },
  {
    id: 'r-string-013',
    category: 'String Functions',
    difficulty: 'hard',
    title: 'Clean and Standardize String',
    text: 'Convert to lowercase, replace spaces with underscores, and remove non-alphanumeric characters except underscores.',
    setup: 'messy <- "Hello World! 123"',
    setupCode: 'messy <- "Hello World! 123"',
    expected: 'hello_world_123',
    sample: 'gsub("[^a-z0-9_]", "", gsub(" ", "_", tolower(messy)))',
    hints: ['Chain multiple transformations', 'Use tolower, gsub for spaces, gsub for cleaning'],
    validPatterns: [/tolower\s*\(/, /gsub\s*\(/],
    tags: ['strings', 'cleaning', 'standardization'],
  },

  // ============================================================
  // LIST OPERATIONS - Hard (2 problems)
  // ============================================================
  {
    id: 'r-list-008',
    category: 'List Operations',
    difficulty: 'hard',
    title: 'Filter List Elements by Condition',
    text: 'Use lapply and sapply to keep only list elements with sum greater than 10.',
    setup: 'data <- list(a = c(1, 2, 3), b = c(5, 5, 5), c = c(1, 1, 1))',
    setupCode: 'data <- list(a = c(1, 2, 3), b = c(5, 5, 5), c = c(1, 1, 1))',
    expected: { b: [5, 5, 5] },
    sample: 'data[sapply(data, sum) > 10]',
    hints: ['Use sapply to get sums as vector', 'Use logical indexing on the list'],
    validPatterns: [/sapply\s*\(/, /sum/],
    tags: ['lists', 'filtering', 'sapply'],
  },
  {
    id: 'r-list-009',
    category: 'List Operations',
    difficulty: 'hard',
    title: 'Nested List Access and Modification',
    text: 'Extract the nested value "deep_value" from the complex nested list structure.',
    setup: 'nested <- list(level1 = list(level2 = list(target = "deep_value")))',
    setupCode: 'nested <- list(level1 = list(level2 = list(target = "deep_value")))',
    expected: 'deep_value',
    sample: 'nested$level1$level2$target',
    hints: ['Chain $ operators for nested access', 'Go through each level sequentially'],
    validPatterns: [/\$level1/, /\$level2/, /\$target/],
    tags: ['lists', 'nested', 'access'],
  },

  // ============================================================
  // DATA FRAME BASICS - Hard (2 problems)
  // ============================================================
  {
    id: 'r-dataframe-007',
    category: 'Data Frame Basics',
    difficulty: 'hard',
    title: 'Merge Two Data Frames',
    text: 'Merge the two data frames by the common "id" column.',
    setup: 'df1 <- data.frame(id = 1:3, name = c("A", "B", "C"))\ndf2 <- data.frame(id = 1:3, score = c(80, 90, 85))',
    setupCode: 'df1 <- data.frame(id = 1:3, name = c("A", "B", "C"))\ndf2 <- data.frame(id = 1:3, score = c(80, 90, 85))',
    expected: { id: [1, 2, 3], name: ['A', 'B', 'C'], score: [80, 90, 85] },
    sample: 'merge(df1, df2, by = "id")',
    hints: ['Use the merge() function', 'Specify the common column with by argument'],
    validPatterns: [/merge\s*\(/, /by\s*=/],
    tags: ['dataframes', 'merge', 'joining'],
  },
  {
    id: 'r-dataframe-008',
    category: 'Data Frame Basics',
    difficulty: 'hard',
    title: 'Subset with Multiple Conditions',
    text: 'Get rows where age > 20 AND salary > 50000.',
    setup: 'employees <- data.frame(\n  name = c("Ann", "Bob", "Cat", "Dan"),\n  age = c(25, 19, 32, 28),\n  salary = c(55000, 45000, 72000, 48000)\n)',
    setupCode: 'employees <- data.frame(\n  name = c("Ann", "Bob", "Cat", "Dan"),\n  age = c(25, 19, 32, 28),\n  salary = c(55000, 45000, 72000, 48000)\n)',
    expected: { name: ['Ann', 'Cat'], age: [25, 32], salary: [55000, 72000] },
    sample: 'subset(employees, age > 20 & salary > 50000)',
    hints: ['Use & for AND conditions in subset', 'Both conditions must be TRUE'],
    validPatterns: [/subset\s*\(/, /&/],
    tags: ['dataframes', 'subset', 'conditions'],
  },

  // ============================================================
  // MATH FUNCTIONS - Hard (2 problems)
  // ============================================================
  {
    id: 'r-math-005',
    category: 'Math Functions',
    difficulty: 'hard',
    title: 'Normalize Vector to 0-1 Range',
    text: 'Normalize the vector so all values fall between 0 and 1 using min-max scaling.',
    setup: 'values <- c(10, 20, 30, 40, 50)',
    setupCode: 'values <- c(10, 20, 30, 40, 50)',
    expected: [0, 0.25, 0.5, 0.75, 1],
    sample: '(values - min(values)) / (max(values) - min(values))',
    hints: ['Formula: (x - min) / (max - min)', 'Use vectorized operations'],
    validPatterns: [/min\s*\(/, /max\s*\(/],
    tags: ['math', 'normalization', 'scaling'],
  },
  {
    id: 'r-math-006',
    category: 'Math Functions',
    difficulty: 'hard',
    title: 'Calculate Compound Interest',
    text: 'Calculate the final amount after 5 years with $1000 principal at 5% annual interest compounded annually. Use: A = P * (1 + r)^t',
    setup: 'principal <- 1000\nrate <- 0.05\nyears <- 5',
    setupCode: 'principal <- 1000\nrate <- 0.05\nyears <- 5',
    expected: 1276.28,
    sample: 'round(principal * (1 + rate)^years, 2)',
    hints: ['Use ^ for exponentiation', 'Round to 2 decimal places'],
    validPatterns: [/\^/, /round\s*\(/],
    tags: ['math', 'finance', 'exponentiation'],
  },

  // ============================================================
  // ADDITIONAL MEDIUM PROBLEMS (to reach 20)
  // ============================================================
  {
    id: 'r-vector-015',
    category: 'Vector Operations',
    difficulty: 'medium',
    title: 'Calculate Cumulative Sum',
    text: 'Calculate the cumulative sum of the vector (running total).',
    setup: 'payments <- c(100, 200, 150, 300)',
    setupCode: 'payments <- c(100, 200, 150, 300)',
    expected: [100, 300, 450, 750],
    sample: 'cumsum(payments)',
    hints: ['Use the cumsum() function', 'Each element is sum of all previous elements plus current'],
    validPatterns: [/cumsum\s*\(/],
    tags: ['vectors', 'cumsum', 'cumulative'],
  },
  {
    id: 'r-math-007',
    category: 'Math Functions',
    difficulty: 'medium',
    title: 'Apply Floor Function',
    text: 'Round all numbers down to the nearest integer using floor.',
    setup: 'decimals <- c(1.9, 2.1, 3.7, 4.0, 5.5)',
    setupCode: 'decimals <- c(1.9, 2.1, 3.7, 4.0, 5.5)',
    expected: [1, 2, 3, 4, 5],
    sample: 'floor(decimals)',
    hints: ['Use the floor() function', 'It always rounds down'],
    validPatterns: [/floor\s*\(/],
    tags: ['math', 'floor', 'rounding'],
  },
  {
    id: 'r-math-008',
    category: 'Math Functions',
    difficulty: 'medium',
    title: 'Calculate Natural Logarithm',
    text: 'Calculate the natural logarithm (base e) of each element.',
    setup: 'values <- c(1, 2.718, 7.389)',
    setupCode: 'values <- c(1, 2.718, 7.389)',
    expected: [0, 1, 2],
    sample: 'round(log(values))',
    hints: ['Use the log() function for natural log', 'log(e) = 1'],
    validPatterns: [/log\s*\(/],
    tags: ['math', 'log', 'logarithm'],
  },
  {
    id: 'r-math-009',
    category: 'Math Functions',
    difficulty: 'medium',
    title: 'Calculate Exponential',
    text: 'Calculate e raised to the power of each element.',
    setup: 'powers <- c(0, 1, 2)',
    setupCode: 'powers <- c(0, 1, 2)',
    expected: [1, 2.72, 7.39],
    sample: 'round(exp(powers), 2)',
    hints: ['Use the exp() function', 'exp(1) = e ≈ 2.718'],
    validPatterns: [/exp\s*\(/],
    tags: ['math', 'exp', 'exponential'],
  },

  // ============================================================
  // ADDITIONAL HARD PROBLEMS (to reach 10)
  // ============================================================
  {
    id: 'r-vector-016',
    category: 'Vector Operations',
    difficulty: 'hard',
    title: 'Z-Score Standardization',
    text: 'Standardize the vector using z-score: (x - mean) / sd',
    setup: 'data <- c(2, 4, 4, 4, 5, 5, 7, 9)',
    setupCode: 'data <- c(2, 4, 4, 4, 5, 5, 7, 9)',
    expected: [-1.5, -0.5, -0.5, -0.5, 0, 0, 1, 2],
    sample: '(data - mean(data)) / sd(data)',
    hints: ['Use mean() and sd() functions', 'sd() calculates standard deviation'],
    validPatterns: [/mean\s*\(/, /sd\s*\(/],
    tags: ['vectors', 'statistics', 'standardization'],
  },
  {
    id: 'r-dataframe-009',
    category: 'Data Frame Basics',
    difficulty: 'hard',
    title: 'Add Calculated Column',
    text: 'Add a new column "total" that is the sum of columns a, b, and c.',
    setup: 'df <- data.frame(a = c(1, 2, 3), b = c(4, 5, 6), c = c(7, 8, 9))',
    setupCode: 'df <- data.frame(a = c(1, 2, 3), b = c(4, 5, 6), c = c(7, 8, 9))',
    expected: { a: [1, 2, 3], b: [4, 5, 6], c: [7, 8, 9], total: [12, 15, 18] },
    sample: 'df$total <- df$a + df$b + df$c; df',
    hints: ['Create new column with $', 'Use vectorized addition'],
    validPatterns: [/\$total/, /<-/],
    tags: ['dataframes', 'columns', 'calculation'],
  },
];
