import type { Problem } from '../types';

/**
 * Redis problems for coding drills
 *
 * Categories (13 total):
 * - String Operations (17 problems)
 * - List Operations (15 problems)
 * - Hash Operations (14 problems)
 * - Set Operations (15 problems)
 * - Sorted Set Operations (18 problems)
 * - Key Management (13 problems)
 * - Transactions (7 problems)
 * - Pub/Sub (5 problems)
 * - HyperLogLog Operations (10 problems)
 * - Streams (12 problems)
 * - Geospatial (10 problems)
 * - Bitmaps (10 problems)
 * - Scripting (8 problems)
 *
 * Total: 154 problems
 */

export const redisProblems: Problem[] = [
  // ============================================================
  // STRING OPERATIONS (17 problems)
  // ============================================================
  {
    id: 'redis-str-001',
    category: 'String Operations',
    difficulty: 'easy',
    title: 'Set a Key-Value Pair',
    text: 'Set the key "name" to the value "Alice".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'OK',
    sample: 'SET name Alice',
    hints: ['Use the SET command', 'Syntax: SET key value', 'Redis returns OK on success'],
    validPatterns: [/SET\s+name\s+["']?Alice["']?/i],
    tags: ['string', 'set', 'basic'],
  },
  {
    id: 'redis-str-002',
    category: 'String Operations',
    difficulty: 'easy',
    title: 'Get a Value by Key',
    text: 'Retrieve the value stored at key "username".',
    setup: 'Key "username" contains "john_doe"',
    setupCode: 'SET username john_doe',
    expected: 'john_doe',
    sample: 'GET username',
    hints: [
      'Use the GET command',
      'Syntax: GET key',
      'Returns the value or nil if key does not exist',
    ],
    validPatterns: [/GET\s+username/i],
    tags: ['string', 'get', 'basic'],
  },
  {
    id: 'redis-str-003',
    category: 'String Operations',
    difficulty: 'easy',
    title: 'Increment a Counter',
    text: 'Increment the numeric value stored at key "views" by 1.',
    setup: 'Key "views" contains "100"',
    setupCode: 'SET views 100',
    expected: '101',
    sample: 'INCR views',
    hints: [
      'Use the INCR command for atomic increment',
      'INCR increments by 1',
      'The value must be a valid integer string',
    ],
    validPatterns: [/INCR\s+views/i],
    tags: ['string', 'incr', 'counter'],
  },
  {
    id: 'redis-str-004',
    category: 'String Operations',
    difficulty: 'easy',
    title: 'Increment by Specific Amount',
    text: 'Increase the counter "score" by 50 points.',
    setup: 'Key "score" contains "200"',
    setupCode: 'SET score 200',
    expected: '250',
    sample: 'INCRBY score 50',
    hints: ['Use INCRBY for specific increment amounts', 'Syntax: INCRBY key increment'],
    validPatterns: [/INCRBY\s+score\s+50/i],
    tags: ['string', 'incrby', 'counter'],
  },
  {
    id: 'redis-str-005',
    category: 'String Operations',
    difficulty: 'easy',
    title: 'Decrement a Counter',
    text: 'Decrement the numeric value stored at key "stock" by 1.',
    setup: 'Key "stock" contains "50"',
    setupCode: 'SET stock 50',
    expected: '49',
    sample: 'DECR stock',
    hints: [
      'Use the DECR command',
      'DECR decrements by 1',
      'Returns the new value after decrementing',
    ],
    validPatterns: [/DECR\s+stock/i],
    tags: ['string', 'decr', 'counter'],
  },
  {
    id: 'redis-str-006',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Set with Expiration',
    text: 'Set the key "session" to "abc123" with a 60 second expiration.',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'OK',
    sample: 'SET session abc123 EX 60',
    hints: [
      'Use SET with the EX option for seconds',
      'EX sets expiration in seconds',
      'Alternative: SETEX session 60 abc123',
    ],
    validPatterns: [
      /SET\s+session\s+["']?abc123["']?\s+EX\s+60/i,
      /SETEX\s+session\s+60\s+["']?abc123["']?/i,
    ],
    tags: ['string', 'set', 'expiration', 'ttl'],
  },
  {
    id: 'redis-str-007',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Set Only If Not Exists',
    text: 'Set the key "lock" to "1" only if it does not already exist.',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'OK or 1',
    sample: 'SET lock 1 NX',
    hints: [
      'Use SET with NX option',
      'NX means "only set if Not eXists"',
      'Alternative: SETNX lock 1',
    ],
    validPatterns: [/SET\s+lock\s+["']?1["']?\s+NX/i, /SETNX\s+lock\s+["']?1["']?/i],
    tags: ['string', 'set', 'nx', 'lock'],
  },
  {
    id: 'redis-str-008',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Append to String',
    text: 'Append " World" to the existing value at key "greeting".',
    setup: 'Key "greeting" contains "Hello"',
    setupCode: 'SET greeting Hello',
    expected: '11',
    sample: 'APPEND greeting " World"',
    hints: [
      'Use the APPEND command',
      'APPEND returns the length of the string after appending',
      'Syntax: APPEND key value',
    ],
    validPatterns: [/APPEND\s+greeting\s+["'] ?World["']/i],
    tags: ['string', 'append'],
  },
  {
    id: 'redis-str-009',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Get String Length',
    text: 'Get the length of the string stored at key "message".',
    setup: 'Key "message" contains "Hello Redis"',
    setupCode: 'SET message "Hello Redis"',
    expected: '11',
    sample: 'STRLEN message',
    hints: [
      'Use the STRLEN command',
      'Returns the length of the string value',
      'Returns 0 if key does not exist',
    ],
    validPatterns: [/STRLEN\s+message/i],
    tags: ['string', 'strlen', 'length'],
  },
  {
    id: 'redis-str-010',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Get Substring',
    text: 'Get characters 0 through 4 (inclusive) from the string at key "text".',
    setup: 'Key "text" contains "Hello World"',
    setupCode: 'SET text "Hello World"',
    expected: 'Hello',
    sample: 'GETRANGE text 0 4',
    hints: [
      'Use the GETRANGE command',
      'Syntax: GETRANGE key start end',
      'Both start and end are inclusive',
    ],
    validPatterns: [/GETRANGE\s+text\s+0\s+4/i],
    tags: ['string', 'getrange', 'substring'],
  },
  {
    id: 'redis-str-011',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Set Multiple Keys',
    text: 'Set keys "a" to "1", "b" to "2", and "c" to "3" in one command.',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'OK',
    sample: 'MSET a 1 b 2 c 3',
    hints: [
      'Use MSET for multiple key-value pairs',
      'Syntax: MSET key1 value1 key2 value2 ...',
      'Atomic operation - all keys set at once',
    ],
    validPatterns: [/MSET\s+a\s+["']?1["']?\s+b\s+["']?2["']?\s+c\s+["']?3["']?/i],
    tags: ['string', 'mset', 'bulk'],
  },
  {
    id: 'redis-str-012',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Get Multiple Keys',
    text: 'Get the values of keys "first", "second", and "third" in one command.',
    setup: 'Keys set with different values',
    setupCode: 'MSET first "a" second "b" third "c"',
    expected: ['a', 'b', 'c'],
    sample: 'MGET first second third',
    hints: [
      'Use MGET for retrieving multiple keys',
      'Syntax: MGET key1 key2 key3 ...',
      'Returns nil for keys that do not exist',
    ],
    validPatterns: [/MGET\s+first\s+second\s+third/i],
    tags: ['string', 'mget', 'bulk'],
  },
  {
    id: 'redis-str-013',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Get and Delete',
    text: 'Get the value of key "one_time_code" and delete it atomically.',
    setup: 'Key "one_time_code" contains a value',
    setupCode: 'SET one_time_code ABC123',
    expected: 'ABC123',
    sample: 'GETDEL one_time_code',
    hints: [
      'Use GETDEL to get and delete atomically',
      'Returns the value before deletion',
      'Useful for one-time-use tokens',
    ],
    validPatterns: [/GETDEL\s+one_time_code/i],
    tags: ['string', 'getdel', 'atomic'],
  },
  {
    id: 'redis-str-014',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Get with Expiration Update',
    text: 'Get the value of key "token" and set its expiration to 120 seconds.',
    setup: 'Key "token" exists',
    setupCode: 'SET token secret_value',
    expected: 'secret_value',
    sample: 'GETEX token EX 120',
    hints: [
      'Use GETEX to get and set expiration',
      'EX sets seconds, PX sets milliseconds',
      'PERSIST option removes expiration',
    ],
    validPatterns: [/GETEX\s+token\s+EX\s+120/i],
    tags: ['string', 'getex', 'expiration'],
  },
  {
    id: 'redis-str-015',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Set Range in String',
    text: 'Replace characters starting at offset 6 in key "message" with "Redis".',
    setup: 'Key "message" contains "Hello World"',
    setupCode: 'SET message "Hello World"',
    expected: '11',
    sample: 'SETRANGE message 6 Redis',
    hints: [
      'Use SETRANGE to overwrite at offset',
      'Syntax: SETRANGE key offset value',
      'Returns the length of the modified string',
    ],
    validPatterns: [/SETRANGE\s+message\s+6\s+["']?Redis["']?/i],
    tags: ['string', 'setrange', 'modify'],
  },
  {
    id: 'redis-str-016',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Copy Key',
    text: 'Copy the value from key "original" to key "backup".',
    setup: 'Key "original" exists',
    setupCode: 'SET original important_data',
    expected: '1',
    sample: 'COPY original backup',
    hints: [
      'Use COPY to duplicate a key',
      'Syntax: COPY source destination',
      'Use REPLACE option to overwrite existing',
    ],
    validPatterns: [/COPY\s+original\s+backup/i],
    tags: ['string', 'copy', 'key'],
  },
  {
    id: 'redis-str-017',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Get and Set (Deprecated)',
    text: 'Set key "counter" to "0" and return its old value atomically.',
    setup: 'Key "counter" contains "42"',
    setupCode: 'SET counter 42',
    expected: '42',
    sample: 'GETSET counter 0',
    hints: [
      'GETSET sets new value and returns old',
      'Deprecated: use SET with GET option instead',
      'Alternative: SET counter 0 GET',
    ],
    validPatterns: [/GETSET\s+counter\s+["']?0["']?/i, /SET\s+counter\s+["']?0["']?\s+GET/i],
    tags: ['string', 'getset', 'atomic'],
  },

  // ============================================================
  // LIST OPERATIONS (15 problems)
  // ============================================================
  {
    id: 'redis-list-001',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Push to List Head',
    text: 'Add the value "first" to the head (left) of list "queue".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: '1',
    sample: 'LPUSH queue first',
    hints: [
      'Use LPUSH to add to the left (head) of a list',
      'Syntax: LPUSH key value',
      'Returns the length of the list after push',
    ],
    validPatterns: [/LPUSH\s+queue\s+["']?first["']?/i],
    tags: ['list', 'lpush', 'basic'],
  },
  {
    id: 'redis-list-002',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Push to List Tail',
    text: 'Add the value "last" to the tail (right) of list "queue".',
    setup: 'List "queue" exists with some elements',
    setupCode: 'RPUSH queue one two',
    expected: '3',
    sample: 'RPUSH queue last',
    hints: [
      'Use RPUSH to add to the right (tail) of a list',
      'Syntax: RPUSH key value',
      'Returns the length of the list after push',
    ],
    validPatterns: [/RPUSH\s+queue\s+["']?last["']?/i],
    tags: ['list', 'rpush', 'basic'],
  },
  {
    id: 'redis-list-003',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Pop from List Head',
    text: 'Remove and return the first element from list "tasks".',
    setup: 'List "tasks" contains ["urgent", "normal", "low"]',
    setupCode: 'RPUSH tasks urgent normal low',
    expected: 'urgent',
    sample: 'LPOP tasks',
    hints: [
      'Use LPOP to remove from the left (head)',
      'Returns the removed element',
      'Returns nil if list is empty',
    ],
    validPatterns: [/LPOP\s+tasks/i],
    tags: ['list', 'lpop', 'basic'],
  },
  {
    id: 'redis-list-004',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Pop from List Tail',
    text: 'Remove and return the last element from list "stack".',
    setup: 'List "stack" contains ["a", "b", "c"]',
    setupCode: 'RPUSH stack a b c',
    expected: 'c',
    sample: 'RPOP stack',
    hints: [
      'Use RPOP to remove from the right (tail)',
      'Perfect for stack operations (LIFO)',
      'Returns nil if list is empty',
    ],
    validPatterns: [/RPOP\s+stack/i],
    tags: ['list', 'rpop', 'stack'],
  },
  {
    id: 'redis-list-005',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Get List Range',
    text: 'Get all elements from list "items" (from index 0 to -1).',
    setup: 'List "items" contains ["apple", "banana", "cherry"]',
    setupCode: 'RPUSH items apple banana cherry',
    expected: ['apple', 'banana', 'cherry'],
    sample: 'LRANGE items 0 -1',
    hints: [
      'Use LRANGE to get elements by index range',
      '-1 means the last element',
      '0 -1 returns all elements',
    ],
    validPatterns: [/LRANGE\s+items\s+0\s+-1/i],
    tags: ['list', 'lrange', 'range'],
  },
  {
    id: 'redis-list-006',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Get List Length',
    text: 'Get the number of elements in list "mylist".',
    setup: 'List "mylist" contains 5 elements',
    setupCode: 'RPUSH mylist a b c d e',
    expected: '5',
    sample: 'LLEN mylist',
    hints: ['Use LLEN to get the length of a list', 'Returns 0 for non-existent keys'],
    validPatterns: [/LLEN\s+mylist/i],
    tags: ['list', 'llen', 'length'],
  },
  {
    id: 'redis-list-007',
    category: 'List Operations',
    difficulty: 'medium',
    title: 'Get Element by Index',
    text: 'Get the element at index 2 from list "colors".',
    setup: 'List "colors" contains ["red", "green", "blue", "yellow"]',
    setupCode: 'RPUSH colors red green blue yellow',
    expected: 'blue',
    sample: 'LINDEX colors 2',
    hints: [
      'Use LINDEX to get element at specific index',
      'Index is 0-based',
      'Negative indices count from the end',
    ],
    validPatterns: [/LINDEX\s+colors\s+2/i],
    tags: ['list', 'lindex', 'index'],
  },
  {
    id: 'redis-list-008',
    category: 'List Operations',
    difficulty: 'medium',
    title: 'Set Element by Index',
    text: 'Change the element at index 1 in list "names" to "Bob".',
    setup: 'List "names" contains ["Alice", "Charlie", "Dave"]',
    setupCode: 'RPUSH names Alice Charlie Dave',
    expected: 'OK',
    sample: 'LSET names 1 Bob',
    hints: [
      'Use LSET to update an element at a specific index',
      'Syntax: LSET key index value',
      'Returns an error if index is out of range',
    ],
    validPatterns: [/LSET\s+names\s+1\s+["']?Bob["']?/i],
    tags: ['list', 'lset', 'update'],
  },
  {
    id: 'redis-list-009',
    category: 'List Operations',
    difficulty: 'medium',
    title: 'Remove Elements by Value',
    text: 'Remove all occurrences of "spam" from list "messages".',
    setup: 'List "messages" contains ["hello", "spam", "world", "spam"]',
    setupCode: 'RPUSH messages hello spam world spam',
    expected: '2',
    sample: 'LREM messages 0 spam',
    hints: [
      'Use LREM to remove elements by value',
      'Count 0 removes ALL matching elements',
      'Positive count removes from head, negative from tail',
    ],
    validPatterns: [/LREM\s+messages\s+0\s+["']?spam["']?/i],
    tags: ['list', 'lrem', 'remove'],
  },
  {
    id: 'redis-list-010',
    category: 'List Operations',
    difficulty: 'hard',
    title: 'Blocking Pop',
    text: 'Pop from the left of list "jobs" with a 5 second timeout if empty.',
    setup: 'List "jobs" may or may not have elements',
    setupCode: 'DEL jobs',
    expected: 'Element or nil after timeout',
    sample: 'BLPOP jobs 5',
    hints: [
      'Use BLPOP for blocking pop operations',
      'Syntax: BLPOP key timeout',
      'Useful for message queues',
    ],
    validPatterns: [/BLPOP\s+jobs\s+5/i],
    tags: ['list', 'blpop', 'blocking', 'queue'],
  },
  {
    id: 'redis-list-011',
    category: 'List Operations',
    difficulty: 'medium',
    title: 'Find Element Position',
    text: 'Find the position of element "target" in list "search_list".',
    setup: 'List "search_list" contains the element',
    setupCode: 'RPUSH search_list a b target c d',
    expected: '2',
    sample: 'LPOS search_list target',
    hints: [
      'Use LPOS to find element position',
      'Returns first occurrence by default',
      'Use RANK option for nth occurrence',
    ],
    validPatterns: [/LPOS\s+search_list\s+["']?target["']?/i],
    tags: ['list', 'lpos', 'search'],
  },
  {
    id: 'redis-list-012',
    category: 'List Operations',
    difficulty: 'medium',
    title: 'Move Element Between Lists',
    text: 'Move an element from the right of "source" to the left of "dest".',
    setup: 'List "source" has elements',
    setupCode: 'RPUSH source a b c',
    expected: 'c',
    sample: 'LMOVE source dest RIGHT LEFT',
    hints: [
      'Use LMOVE to move between lists',
      'Specify source side and dest side',
      'Atomic operation',
    ],
    validPatterns: [/LMOVE\s+source\s+dest\s+RIGHT\s+LEFT/i],
    tags: ['list', 'lmove', 'move'],
  },
  {
    id: 'redis-list-013',
    category: 'List Operations',
    difficulty: 'medium',
    title: 'Insert Before Element',
    text: 'Insert "new_item" before "pivot" in list "mylist".',
    setup: 'List "mylist" contains pivot element',
    setupCode: 'RPUSH mylist a pivot b',
    expected: '4',
    sample: 'LINSERT mylist BEFORE pivot new_item',
    hints: [
      'Use LINSERT with BEFORE or AFTER',
      'Syntax: LINSERT key BEFORE|AFTER pivot value',
      'Returns -1 if pivot not found',
    ],
    validPatterns: [/LINSERT\s+mylist\s+BEFORE\s+["']?pivot["']?\s+["']?new_item["']?/i],
    tags: ['list', 'linsert', 'insert'],
  },
  {
    id: 'redis-list-014',
    category: 'List Operations',
    difficulty: 'medium',
    title: 'Trim List',
    text: 'Trim list "log" to keep only elements from index 0 to 99.',
    setup: 'List "log" has many elements',
    setupCode:
      'RPUSH log entry1 entry2 entry3 entry4 entry5 entry6 entry7 entry8 entry9 entry10 entry11',
    expected: 'OK',
    sample: 'LTRIM log 0 99',
    hints: [
      'Use LTRIM to keep only a range',
      'Elements outside range are removed',
      'Useful for capped lists/logs',
    ],
    validPatterns: [/LTRIM\s+log\s+0\s+99/i],
    tags: ['list', 'ltrim', 'trim'],
  },
  {
    id: 'redis-list-015',
    category: 'List Operations',
    difficulty: 'hard',
    title: 'Blocking Move (Legacy)',
    text: 'Pop from the right of "source" and push to left of "dest" with 5 second timeout.',
    setup: 'List "source" may be empty',
    setupCode: 'RPUSH source item1 item2',
    expected: 'Moved element or nil',
    sample: 'BRPOPLPUSH source dest 5',
    hints: [
      'BRPOPLPUSH is blocking version of RPOPLPUSH',
      'Useful for reliable queues',
      'Note: BLMOVE is the newer alternative',
    ],
    validPatterns: [/BRPOPLPUSH\s+source\s+dest\s+5/i],
    tags: ['list', 'brpoplpush', 'blocking', 'queue'],
  },

  // ============================================================
  // HASH OPERATIONS (14 problems)
  // ============================================================
  {
    id: 'redis-hash-001',
    category: 'Hash Operations',
    difficulty: 'easy',
    title: 'Set Hash Field',
    text: 'Set the field "name" to "John" in hash "user:1".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: '1',
    sample: 'HSET user:1 name John',
    hints: [
      'Use HSET to set a field in a hash',
      'Syntax: HSET key field value',
      'Returns 1 if field is new, 0 if updated',
    ],
    validPatterns: [/HSET\s+user:1\s+name\s+["']?John["']?/i],
    tags: ['hash', 'hset', 'basic'],
  },
  {
    id: 'redis-hash-002',
    category: 'Hash Operations',
    difficulty: 'easy',
    title: 'Get Hash Field',
    text: 'Get the value of field "email" from hash "user:1".',
    setup: 'Hash "user:1" has field "email" set',
    setupCode: 'HSET user:1 email john@example.com',
    expected: 'john@example.com',
    sample: 'HGET user:1 email',
    hints: [
      'Use HGET to get a single field value',
      'Syntax: HGET key field',
      'Returns nil if field does not exist',
    ],
    validPatterns: [/HGET\s+user:1\s+email/i],
    tags: ['hash', 'hget', 'basic'],
  },
  {
    id: 'redis-hash-003',
    category: 'Hash Operations',
    difficulty: 'easy',
    title: 'Get All Hash Fields and Values',
    text: 'Get all fields and values from hash "product:100".',
    setup: 'Hash "product:100" has multiple fields',
    setupCode: 'HSET product:100 name Widget price 29.99 stock 50',
    expected: { name: 'Widget', price: '29.99', stock: '50' },
    sample: 'HGETALL product:100',
    hints: [
      'Use HGETALL to get all field-value pairs',
      'Returns alternating field names and values',
      'Use with caution on large hashes',
    ],
    validPatterns: [/HGETALL\s+product:100/i],
    tags: ['hash', 'hgetall', 'basic'],
  },
  {
    id: 'redis-hash-004',
    category: 'Hash Operations',
    difficulty: 'medium',
    title: 'Set Multiple Hash Fields',
    text: 'Set fields "city" to "NYC" and "country" to "USA" in hash "location".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'OK',
    sample: 'HSET location city NYC country USA',
    hints: [
      'HSET can set multiple field-value pairs',
      'Syntax: HSET key field1 value1 field2 value2 ...',
      'Alternative: HMSET (deprecated but still works)',
    ],
    validPatterns: [
      /HSET\s+location\s+city\s+["']?NYC["']?\s+country\s+["']?USA["']?/i,
      /HMSET\s+location\s+city\s+["']?NYC["']?\s+country\s+["']?USA["']?/i,
    ],
    tags: ['hash', 'hset', 'multiple'],
  },
  {
    id: 'redis-hash-005',
    category: 'Hash Operations',
    difficulty: 'medium',
    title: 'Get Multiple Hash Fields',
    text: 'Get fields "name" and "age" from hash "person:1".',
    setup: 'Hash "person:1" has multiple fields',
    setupCode: 'HSET person:1 name Alice age 30 city Boston',
    expected: ['Alice', '30'],
    sample: 'HMGET person:1 name age',
    hints: [
      'Use HMGET to get multiple field values',
      'Syntax: HMGET key field1 field2 ...',
      'Returns nil for non-existent fields',
    ],
    validPatterns: [/HMGET\s+person:1\s+name\s+age/i],
    tags: ['hash', 'hmget', 'multiple'],
  },
  {
    id: 'redis-hash-006',
    category: 'Hash Operations',
    difficulty: 'medium',
    title: 'Increment Hash Field',
    text: 'Increment the "views" field in hash "article:1" by 1.',
    setup: 'Hash "article:1" has views field set',
    setupCode: 'HSET article:1 views 100',
    expected: '101',
    sample: 'HINCRBY article:1 views 1',
    hints: [
      'Use HINCRBY for integer increment',
      'Syntax: HINCRBY key field increment',
      'Creates field with 0 if it does not exist',
    ],
    validPatterns: [/HINCRBY\s+article:1\s+views\s+1/i],
    tags: ['hash', 'hincrby', 'counter'],
  },
  {
    id: 'redis-hash-007',
    category: 'Hash Operations',
    difficulty: 'medium',
    title: 'Check Field Existence',
    text: 'Check if field "admin" exists in hash "user:1".',
    setup: 'Hash "user:1" may or may not have admin field',
    setupCode: 'HSET user:1 name John role member',
    expected: '0 or 1',
    sample: 'HEXISTS user:1 admin',
    hints: [
      'Use HEXISTS to check field existence',
      'Returns 1 if field exists, 0 otherwise',
      'Useful for conditional logic',
    ],
    validPatterns: [/HEXISTS\s+user:1\s+admin/i],
    tags: ['hash', 'hexists', 'check'],
  },
  {
    id: 'redis-hash-008',
    category: 'Hash Operations',
    difficulty: 'medium',
    title: 'Delete Hash Field',
    text: 'Delete the field "temp" from hash "config".',
    setup: 'Hash "config" has a temp field',
    setupCode: 'HSET config temp value permanent keep',
    expected: '1',
    sample: 'HDEL config temp',
    hints: [
      'Use HDEL to delete fields from a hash',
      'Syntax: HDEL key field1 field2 ...',
      'Returns number of fields removed',
    ],
    validPatterns: [/HDEL\s+config\s+temp/i],
    tags: ['hash', 'hdel', 'delete'],
  },
  {
    id: 'redis-hash-009',
    category: 'Hash Operations',
    difficulty: 'easy',
    title: 'Get All Hash Keys',
    text: 'Get all field names from hash "settings".',
    setup: 'Hash "settings" has multiple fields',
    setupCode: 'HSET settings theme dark lang en timeout 30',
    expected: ['theme', 'lang', 'timeout'],
    sample: 'HKEYS settings',
    hints: [
      'Use HKEYS to get all field names',
      'Returns an array of field names',
      'Complement: HVALS returns all values',
    ],
    validPatterns: [/HKEYS\s+settings/i],
    tags: ['hash', 'hkeys', 'fields'],
  },
  {
    id: 'redis-hash-010',
    category: 'Hash Operations',
    difficulty: 'easy',
    title: 'Get Hash Field Count',
    text: 'Get the number of fields in hash "metadata".',
    setup: 'Hash "metadata" has several fields',
    setupCode: 'HSET metadata created 2024 author admin version 1.0',
    expected: '3',
    sample: 'HLEN metadata',
    hints: ['Use HLEN to get the number of fields', 'Returns 0 for non-existent keys'],
    validPatterns: [/HLEN\s+metadata/i],
    tags: ['hash', 'hlen', 'length'],
  },
  {
    id: 'redis-hash-011',
    category: 'Hash Operations',
    difficulty: 'medium',
    title: 'Set Field Only If Not Exists',
    text: 'Set field "lock" to "1" in hash "resource" only if it does not exist.',
    setup: 'Hash "resource" exists',
    setupCode: 'HSET resource name test',
    expected: '1',
    sample: 'HSETNX resource lock 1',
    hints: [
      'Use HSETNX for conditional set',
      'Returns 1 if field was set',
      'Returns 0 if field already exists',
    ],
    validPatterns: [/HSETNX\s+resource\s+lock\s+["']?1["']?/i],
    tags: ['hash', 'hsetnx', 'conditional'],
  },
  {
    id: 'redis-hash-012',
    category: 'Hash Operations',
    difficulty: 'easy',
    title: 'Get All Hash Values',
    text: 'Get all values from hash "config" (without field names).',
    setup: 'Hash "config" has multiple fields',
    setupCode: 'HSET config host localhost port 6379 db 0',
    expected: ['localhost', '6379', '0'],
    sample: 'HVALS config',
    hints: [
      'Use HVALS to get only values',
      'Complement of HKEYS (only names)',
      'Order corresponds to HKEYS order',
    ],
    validPatterns: [/HVALS\s+config/i],
    tags: ['hash', 'hvals', 'values'],
  },
  {
    id: 'redis-hash-013',
    category: 'Hash Operations',
    difficulty: 'medium',
    title: 'Get Random Hash Fields',
    text: 'Get 2 random fields from hash "products".',
    setup: 'Hash "products" has many fields',
    setupCode: 'HSET products item1 10 item2 20 item3 30 item4 40 item5 50',
    expected: 'Array of 2 random field names',
    sample: 'HRANDFIELD products 2',
    hints: [
      'Use HRANDFIELD for random fields',
      'Positive count = unique fields',
      'Add WITHVALUES to include values',
    ],
    validPatterns: [/HRANDFIELD\s+products\s+2/i],
    tags: ['hash', 'hrandfield', 'random'],
  },
  {
    id: 'redis-hash-014',
    category: 'Hash Operations',
    difficulty: 'hard',
    title: 'Scan Hash Fields',
    text: 'Incrementally iterate through fields in hash "big_hash" starting from cursor 0.',
    setup: 'Hash "big_hash" has many fields',
    setupCode: 'HSET big_hash f1 v1 f2 v2 f3 v3 f4 v4 f5 v5',
    expected: 'Cursor and array of fields/values',
    sample: 'HSCAN big_hash 0',
    hints: [
      'Use HSCAN for incremental iteration',
      'Returns new cursor and results',
      'Continue until cursor returns 0',
    ],
    validPatterns: [/HSCAN\s+big_hash\s+0/i],
    tags: ['hash', 'hscan', 'scan', 'iteration'],
  },

  // ============================================================
  // SET OPERATIONS (15 problems)
  // ============================================================
  {
    id: 'redis-set-001',
    category: 'Set Operations',
    difficulty: 'easy',
    title: 'Add to Set',
    text: 'Add "apple" to the set "fruits".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: '1',
    sample: 'SADD fruits apple',
    hints: [
      'Use SADD to add members to a set',
      'Returns number of new members added',
      'Duplicates are automatically ignored',
    ],
    validPatterns: [/SADD\s+fruits\s+["']?apple["']?/i],
    tags: ['set', 'sadd', 'basic'],
  },
  {
    id: 'redis-set-002',
    category: 'Set Operations',
    difficulty: 'easy',
    title: 'Get All Set Members',
    text: 'Get all members of the set "tags".',
    setup: 'Set "tags" contains several members',
    setupCode: 'SADD tags redis database nosql',
    expected: ['redis', 'database', 'nosql'],
    sample: 'SMEMBERS tags',
    hints: [
      'Use SMEMBERS to get all members',
      'Order is not guaranteed',
      'Use with caution on large sets',
    ],
    validPatterns: [/SMEMBERS\s+tags/i],
    tags: ['set', 'smembers', 'basic'],
  },
  {
    id: 'redis-set-003',
    category: 'Set Operations',
    difficulty: 'easy',
    title: 'Check Set Membership',
    text: 'Check if "bob" is a member of set "users".',
    setup: 'Set "users" contains some members',
    setupCode: 'SADD users alice bob charlie',
    expected: '1',
    sample: 'SISMEMBER users bob',
    hints: [
      'Use SISMEMBER to check membership',
      'Returns 1 if member exists, 0 otherwise',
      'O(1) operation',
    ],
    validPatterns: [/SISMEMBER\s+users\s+["']?bob["']?/i],
    tags: ['set', 'sismember', 'check'],
  },
  {
    id: 'redis-set-004',
    category: 'Set Operations',
    difficulty: 'easy',
    title: 'Get Set Cardinality',
    text: 'Get the number of members in set "visitors".',
    setup: 'Set "visitors" has several members',
    setupCode: 'SADD visitors user1 user2 user3 user4',
    expected: '4',
    sample: 'SCARD visitors',
    hints: [
      'Use SCARD to get the set size',
      'SCARD = Set CARDinality',
      'Returns 0 for non-existent keys',
    ],
    validPatterns: [/SCARD\s+visitors/i],
    tags: ['set', 'scard', 'cardinality'],
  },
  {
    id: 'redis-set-005',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Remove from Set',
    text: 'Remove "expired" from the set "tokens".',
    setup: 'Set "tokens" contains the member',
    setupCode: 'SADD tokens valid expired pending',
    expected: '1',
    sample: 'SREM tokens expired',
    hints: [
      'Use SREM to remove members',
      'Syntax: SREM key member1 member2 ...',
      'Returns number of members removed',
    ],
    validPatterns: [/SREM\s+tokens\s+["']?expired["']?/i],
    tags: ['set', 'srem', 'remove'],
  },
  {
    id: 'redis-set-006',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Set Union',
    text: 'Get the union of sets "set1" and "set2".',
    setup: 'Two sets with some overlapping members',
    setupCode: 'SADD set1 a b c\nSADD set2 b c d',
    expected: ['a', 'b', 'c', 'd'],
    sample: 'SUNION set1 set2',
    hints: [
      'Use SUNION to combine sets',
      'Returns all unique members from all sets',
      'Does not modify the original sets',
    ],
    validPatterns: [/SUNION\s+set1\s+set2/i],
    tags: ['set', 'sunion', 'union'],
  },
  {
    id: 'redis-set-007',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Set Intersection',
    text: 'Get the intersection of sets "groupA" and "groupB".',
    setup: 'Two sets with some common members',
    setupCode: 'SADD groupA alice bob charlie\nSADD groupB bob charlie dave',
    expected: ['bob', 'charlie'],
    sample: 'SINTER groupA groupB',
    hints: [
      'Use SINTER for intersection',
      'Returns members present in ALL sets',
      'Empty result if any set is empty',
    ],
    validPatterns: [/SINTER\s+groupA\s+groupB/i],
    tags: ['set', 'sinter', 'intersection'],
  },
  {
    id: 'redis-set-008',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Set Difference',
    text: 'Get members in "all_users" that are not in "banned_users".',
    setup: 'Two sets where one is a subset of activities',
    setupCode: 'SADD all_users alice bob charlie dave\nSADD banned_users bob',
    expected: ['alice', 'charlie', 'dave'],
    sample: 'SDIFF all_users banned_users',
    hints: [
      'Use SDIFF for difference',
      'Returns members in first set not in others',
      'Order matters: first set minus others',
    ],
    validPatterns: [/SDIFF\s+all_users\s+banned_users/i],
    tags: ['set', 'sdiff', 'difference'],
  },
  {
    id: 'redis-set-009',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Pop Random Member',
    text: 'Remove and return a random member from set "pool".',
    setup: 'Set "pool" has several members',
    setupCode: 'SADD pool item1 item2 item3 item4',
    expected: 'Random member',
    sample: 'SPOP pool',
    hints: [
      'Use SPOP to remove random member',
      'Useful for random selection',
      'Can specify count: SPOP pool 2',
    ],
    validPatterns: [/SPOP\s+pool/i],
    tags: ['set', 'spop', 'random'],
  },
  {
    id: 'redis-set-010',
    category: 'Set Operations',
    difficulty: 'easy',
    title: 'Get Random Member',
    text: 'Get a random member from set "prizes" without removing it.',
    setup: 'Set "prizes" has several members',
    setupCode: 'SADD prizes gold silver bronze',
    expected: 'Random member',
    sample: 'SRANDMEMBER prizes',
    hints: [
      'Use SRANDMEMBER for random without removal',
      'Can specify count for multiple random members',
      'Negative count allows duplicates',
    ],
    validPatterns: [/SRANDMEMBER\s+prizes/i],
    tags: ['set', 'srandmember', 'random'],
  },
  {
    id: 'redis-set-011',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Move Member Between Sets',
    text: 'Move member "item" from set "source" to set "dest".',
    setup: 'Both sets exist, source contains the member',
    setupCode: 'SADD source item other\nSADD dest existing',
    expected: '1',
    sample: 'SMOVE source dest item',
    hints: [
      'Use SMOVE to transfer members',
      'Atomic operation',
      'Returns 0 if member not in source',
    ],
    validPatterns: [/SMOVE\s+source\s+dest\s+["']?item["']?/i],
    tags: ['set', 'smove', 'move'],
  },
  {
    id: 'redis-set-012',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Store Intersection',
    text: 'Store the intersection of "set1" and "set2" into "result".',
    setup: 'Two sets with overlapping members',
    setupCode: 'SADD set1 a b c\nSADD set2 b c d',
    expected: '2',
    sample: 'SINTERSTORE result set1 set2',
    hints: [
      'Use SINTERSTORE to save intersection',
      'Returns the cardinality of result',
      'Overwrites destination if exists',
    ],
    validPatterns: [/SINTERSTORE\s+result\s+set1\s+set2/i],
    tags: ['set', 'sinterstore', 'intersection'],
  },
  {
    id: 'redis-set-013',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Store Union',
    text: 'Store the union of "set1" and "set2" into "combined".',
    setup: 'Two sets exist',
    setupCode: 'SADD set1 a b\nSADD set2 c d',
    expected: '4',
    sample: 'SUNIONSTORE combined set1 set2',
    hints: [
      'Use SUNIONSTORE to save union',
      'Returns size of resulting set',
      'Destination is overwritten',
    ],
    validPatterns: [/SUNIONSTORE\s+combined\s+set1\s+set2/i],
    tags: ['set', 'sunionstore', 'union'],
  },
  {
    id: 'redis-set-014',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Store Difference',
    text: 'Store members in "all" but not in "excluded" into "active".',
    setup: 'Two sets exist',
    setupCode: 'SADD all user1 user2 user3\nSADD excluded user2',
    expected: '2',
    sample: 'SDIFFSTORE active all excluded',
    hints: [
      'Use SDIFFSTORE to save difference',
      'First set minus subsequent sets',
      'Returns cardinality of result',
    ],
    validPatterns: [/SDIFFSTORE\s+active\s+all\s+excluded/i],
    tags: ['set', 'sdiffstore', 'difference'],
  },
  {
    id: 'redis-set-015',
    category: 'Set Operations',
    difficulty: 'hard',
    title: 'Scan Set Members',
    text: 'Incrementally iterate through members of set "large_set" starting from cursor 0.',
    setup: 'Set "large_set" has many members',
    setupCode: 'SADD large_set m1 m2 m3 m4 m5 m6 m7 m8 m9 m10',
    expected: 'Cursor and array of members',
    sample: 'SSCAN large_set 0',
    hints: [
      'Use SSCAN for incremental iteration',
      'Returns cursor and batch of members',
      'Continue until cursor is 0',
    ],
    validPatterns: [/SSCAN\s+large_set\s+0/i],
    tags: ['set', 'sscan', 'scan', 'iteration'],
  },

  // ============================================================
  // SORTED SET OPERATIONS (18 problems)
  // ============================================================
  {
    id: 'redis-zset-001',
    category: 'Sorted Set Operations',
    difficulty: 'easy',
    title: 'Add to Sorted Set',
    text: 'Add member "player1" with score 100 to sorted set "leaderboard".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: '1',
    sample: 'ZADD leaderboard 100 player1',
    hints: [
      'Use ZADD to add scored members',
      'Syntax: ZADD key score member',
      'Score is the sorting value',
    ],
    validPatterns: [/ZADD\s+leaderboard\s+100\s+["']?player1["']?/i],
    tags: ['zset', 'zadd', 'basic'],
  },
  {
    id: 'redis-zset-002',
    category: 'Sorted Set Operations',
    difficulty: 'easy',
    title: 'Get Sorted Set Range',
    text: 'Get the top 3 members from sorted set "scores" (highest scores first).',
    setup: 'Sorted set with multiple members',
    setupCode: 'ZADD scores 100 alice 200 bob 150 charlie 300 dave',
    expected: ['dave', 'bob', 'charlie'],
    sample: 'ZRANGE scores 0 2 REV',
    hints: [
      'Use ZRANGE with REV for descending order',
      'Index 0 to 2 gives top 3',
      'Alternative: ZREVRANGE scores 0 2',
    ],
    validPatterns: [/ZRANGE\s+scores\s+0\s+2\s+REV/i, /ZREVRANGE\s+scores\s+0\s+2/i],
    tags: ['zset', 'zrange', 'range'],
  },
  {
    id: 'redis-zset-003',
    category: 'Sorted Set Operations',
    difficulty: 'easy',
    title: 'Get Member Score',
    text: 'Get the score of member "alice" in sorted set "points".',
    setup: 'Sorted set with alice as member',
    setupCode: 'ZADD points 75 alice 80 bob',
    expected: '75',
    sample: 'ZSCORE points alice',
    hints: [
      'Use ZSCORE to get a member score',
      'Syntax: ZSCORE key member',
      'Returns nil if member does not exist',
    ],
    validPatterns: [/ZSCORE\s+points\s+["']?alice["']?/i],
    tags: ['zset', 'zscore', 'score'],
  },
  {
    id: 'redis-zset-004',
    category: 'Sorted Set Operations',
    difficulty: 'medium',
    title: 'Get Member Rank',
    text: 'Get the rank of member "bob" in sorted set "rankings" (0-based, lowest score first).',
    setup: 'Sorted set with bob as member',
    setupCode: 'ZADD rankings 50 alice 75 bob 100 charlie',
    expected: '1',
    sample: 'ZRANK rankings bob',
    hints: [
      'Use ZRANK for ascending rank (lowest = 0)',
      'Use ZREVRANK for descending rank',
      'Returns nil if member not found',
    ],
    validPatterns: [/ZRANK\s+rankings\s+["']?bob["']?/i],
    tags: ['zset', 'zrank', 'rank'],
  },
  {
    id: 'redis-zset-005',
    category: 'Sorted Set Operations',
    difficulty: 'medium',
    title: 'Increment Score',
    text: 'Increment the score of "player1" by 25 in sorted set "game_scores".',
    setup: 'Sorted set with player1',
    setupCode: 'ZADD game_scores 100 player1',
    expected: '125',
    sample: 'ZINCRBY game_scores 25 player1',
    hints: [
      'Use ZINCRBY to increment a score',
      'Syntax: ZINCRBY key increment member',
      'Returns the new score',
    ],
    validPatterns: [/ZINCRBY\s+game_scores\s+25\s+["']?player1["']?/i],
    tags: ['zset', 'zincrby', 'increment'],
  },
  {
    id: 'redis-zset-006',
    category: 'Sorted Set Operations',
    difficulty: 'medium',
    title: 'Count Members in Score Range',
    text: 'Count members with scores between 50 and 100 (inclusive) in sorted set "exam_results".',
    setup: 'Sorted set with various scores',
    setupCode: 'ZADD exam_results 45 fail1 55 pass1 75 pass2 95 pass3 105 extra',
    expected: '3',
    sample: 'ZCOUNT exam_results 50 100',
    hints: [
      'Use ZCOUNT to count by score range',
      'Syntax: ZCOUNT key min max',
      'Inclusive by default',
    ],
    validPatterns: [/ZCOUNT\s+exam_results\s+50\s+100/i],
    tags: ['zset', 'zcount', 'range'],
  },
  {
    id: 'redis-zset-007',
    category: 'Sorted Set Operations',
    difficulty: 'medium',
    title: 'Get Members by Score Range',
    text: 'Get all members with scores from 0 to 100 in sorted set "prices".',
    setup: 'Sorted set with price data',
    setupCode: 'ZADD prices 25 cheap 75 medium 150 expensive',
    expected: ['cheap', 'medium'],
    sample: 'ZRANGEBYSCORE prices 0 100',
    hints: [
      'Use ZRANGEBYSCORE for score-based range',
      'Syntax: ZRANGEBYSCORE key min max',
      'Use -inf and +inf for unbounded',
    ],
    validPatterns: [/ZRANGEBYSCORE\s+prices\s+0\s+100/i, /ZRANGE\s+prices\s+0\s+100\s+BYSCORE/i],
    tags: ['zset', 'zrangebyscore', 'range'],
  },
  {
    id: 'redis-zset-008',
    category: 'Sorted Set Operations',
    difficulty: 'medium',
    title: 'Remove Member from Sorted Set',
    text: 'Remove "inactive" from sorted set "active_users".',
    setup: 'Sorted set with the member',
    setupCode: 'ZADD active_users 1 alice 2 bob 3 inactive',
    expected: '1',
    sample: 'ZREM active_users inactive',
    hints: [
      'Use ZREM to remove members',
      'Syntax: ZREM key member1 member2 ...',
      'Returns number of members removed',
    ],
    validPatterns: [/ZREM\s+active_users\s+["']?inactive["']?/i],
    tags: ['zset', 'zrem', 'remove'],
  },
  {
    id: 'redis-zset-009',
    category: 'Sorted Set Operations',
    difficulty: 'easy',
    title: 'Get Sorted Set Cardinality',
    text: 'Get the number of members in sorted set "inventory".',
    setup: 'Sorted set with several members',
    setupCode: 'ZADD inventory 10 item1 20 item2 30 item3',
    expected: '3',
    sample: 'ZCARD inventory',
    hints: [
      'Use ZCARD to get sorted set size',
      'Like SCARD for sets',
      'Returns 0 for non-existent keys',
    ],
    validPatterns: [/ZCARD\s+inventory/i],
    tags: ['zset', 'zcard', 'cardinality'],
  },
  {
    id: 'redis-zset-010',
    category: 'Sorted Set Operations',
    difficulty: 'hard',
    title: 'Get Range with Scores',
    text: 'Get the top 3 members WITH their scores from sorted set "highscores" (highest first).',
    setup: 'Sorted set with scores',
    setupCode: 'ZADD highscores 1000 pro 500 amateur 750 intermediate 250 beginner',
    expected: [
      ['pro', '1000'],
      ['intermediate', '750'],
      ['amateur', '500'],
    ],
    sample: 'ZRANGE highscores 0 2 REV WITHSCORES',
    hints: [
      'Add WITHSCORES to include scores',
      'Returns alternating member, score pairs',
      'Useful for leaderboards',
    ],
    validPatterns: [
      /ZRANGE\s+highscores\s+0\s+2\s+REV\s+WITHSCORES/i,
      /ZREVRANGE\s+highscores\s+0\s+2\s+WITHSCORES/i,
    ],
    tags: ['zset', 'zrange', 'withscores'],
  },
  {
    id: 'redis-zset-011',
    category: 'Sorted Set Operations',
    difficulty: 'medium',
    title: 'Pop Minimum Score',
    text: 'Remove and return the member with the lowest score from sorted set "queue".',
    setup: 'Sorted set with multiple members',
    setupCode: 'ZADD queue 10 high 5 medium 1 low',
    expected: ['low', '1'],
    sample: 'ZPOPMIN queue',
    hints: [
      'Use ZPOPMIN to remove lowest scored member',
      'Returns member and score',
      'Can specify count: ZPOPMIN queue 2',
    ],
    validPatterns: [/ZPOPMIN\s+queue/i],
    tags: ['zset', 'zpopmin', 'pop'],
  },
  {
    id: 'redis-zset-012',
    category: 'Sorted Set Operations',
    difficulty: 'medium',
    title: 'Pop Maximum Score',
    text: 'Remove and return the member with the highest score from sorted set "scores".',
    setup: 'Sorted set with multiple members',
    setupCode: 'ZADD scores 100 first 200 second 300 third',
    expected: ['third', '300'],
    sample: 'ZPOPMAX scores',
    hints: [
      'Use ZPOPMAX to remove highest scored member',
      'Opposite of ZPOPMIN',
      'Useful for priority queues',
    ],
    validPatterns: [/ZPOPMAX\s+scores/i],
    tags: ['zset', 'zpopmax', 'pop'],
  },
  {
    id: 'redis-zset-013',
    category: 'Sorted Set Operations',
    difficulty: 'hard',
    title: 'Blocking Pop Minimum',
    text: 'Pop the lowest scored member from sorted set "tasks" with 5 second timeout.',
    setup: 'Sorted set may be empty',
    setupCode: 'ZADD tasks 1 urgent 5 normal',
    expected: 'Member and score or nil',
    sample: 'BZPOPMIN tasks 5',
    hints: [
      'Use BZPOPMIN for blocking pop',
      'Blocks until element available or timeout',
      'Useful for priority job queues',
    ],
    validPatterns: [/BZPOPMIN\s+tasks\s+5/i],
    tags: ['zset', 'bzpopmin', 'blocking'],
  },
  {
    id: 'redis-zset-014',
    category: 'Sorted Set Operations',
    difficulty: 'hard',
    title: 'Range by Lexicographical Order',
    text: 'Get members between "[a" and "[d" (inclusive) from sorted set "names" (all same score).',
    setup: 'Sorted set with same scores for lex ordering',
    setupCode: 'ZADD names 0 alice 0 bob 0 charlie 0 dave 0 eve',
    expected: ['alice', 'bob', 'charlie', 'dave'],
    sample: 'ZRANGEBYLEX names [a [d',
    hints: [
      'Use ZRANGEBYLEX for lexicographical range',
      'Only works when all scores are equal',
      'Use [ for inclusive, ( for exclusive',
    ],
    validPatterns: [/ZRANGEBYLEX\s+names\s+\[a\s+\[d/i, /ZRANGE\s+names\s+\[a\s+\[d\s+BYLEX/i],
    tags: ['zset', 'zrangebylex', 'lexicographical'],
  },
  {
    id: 'redis-zset-015',
    category: 'Sorted Set Operations',
    difficulty: 'hard',
    title: 'Count by Lexicographical Range',
    text: 'Count members starting with letters a-m in sorted set "words" (all same score).',
    setup: 'Sorted set with alphabetically ordered words',
    setupCode: 'ZADD words 0 apple 0 banana 0 mango 0 orange 0 zebra',
    expected: '3',
    sample: 'ZLEXCOUNT words [a (n',
    hints: [
      'Use ZLEXCOUNT for lex range counting',
      'Works with same-score sorted sets',
      '( is exclusive, [ is inclusive',
    ],
    validPatterns: [/ZLEXCOUNT\s+words\s+\[a\s+\(n/i],
    tags: ['zset', 'zlexcount', 'lexicographical', 'count'],
  },
  {
    id: 'redis-zset-016',
    category: 'Sorted Set Operations',
    difficulty: 'hard',
    title: 'Store Union of Sorted Sets',
    text: 'Store the union of "zset1" and "zset2" into "merged" (sum scores by default).',
    setup: 'Two sorted sets with some common members',
    setupCode: 'ZADD zset1 10 a 20 b\nZADD zset2 15 b 25 c',
    expected: '3',
    sample: 'ZUNIONSTORE merged 2 zset1 zset2',
    hints: [
      'Use ZUNIONSTORE to combine sorted sets',
      'Specify numkeys before key names',
      'Default aggregation is SUM',
    ],
    validPatterns: [/ZUNIONSTORE\s+merged\s+2\s+zset1\s+zset2/i],
    tags: ['zset', 'zunionstore', 'union', 'aggregate'],
  },
  {
    id: 'redis-zset-017',
    category: 'Sorted Set Operations',
    difficulty: 'hard',
    title: 'Store Intersection of Sorted Sets',
    text: 'Store the intersection of "scores1" and "scores2" into "common" with MIN aggregation.',
    setup: 'Two sorted sets with overlapping members',
    setupCode:
      'ZADD scores1 100 alice 200 bob 300 charlie\nZADD scores2 150 bob 250 charlie 350 dave',
    expected: '2',
    sample: 'ZINTERSTORE common 2 scores1 scores2 AGGREGATE MIN',
    hints: [
      'Use ZINTERSTORE for intersection',
      'AGGREGATE can be SUM, MIN, or MAX',
      'Only members in all sets are kept',
    ],
    validPatterns: [/ZINTERSTORE\s+common\s+2\s+scores1\s+scores2\s+AGGREGATE\s+MIN/i],
    tags: ['zset', 'zinterstore', 'intersection', 'aggregate'],
  },
  {
    id: 'redis-zset-018',
    category: 'Sorted Set Operations',
    difficulty: 'medium',
    title: 'Get Multiple Scores',
    text: 'Get the scores of members "alice" and "bob" from sorted set "rankings".',
    setup: 'Sorted set with both members',
    setupCode: 'ZADD rankings 100 alice 200 bob 150 charlie',
    expected: ['100', '200'],
    sample: 'ZMSCORE rankings alice bob',
    hints: [
      'Use ZMSCORE for multiple scores',
      'Returns scores in order of input',
      'Returns nil for non-existent members',
    ],
    validPatterns: [/ZMSCORE\s+rankings\s+["']?alice["']?\s+["']?bob["']?/i],
    tags: ['zset', 'zmscore', 'score', 'multiple'],
  },

  // ============================================================
  // KEY MANAGEMENT (13 problems)
  // ============================================================
  {
    id: 'redis-key-001',
    category: 'Key Management',
    difficulty: 'easy',
    title: 'Delete a Key',
    text: 'Delete the key "temp".',
    setup: 'Key "temp" exists',
    setupCode: 'SET temp value',
    expected: '1',
    sample: 'DEL temp',
    hints: [
      'Use DEL to delete keys',
      'Can delete multiple keys at once',
      'Returns number of keys deleted',
    ],
    validPatterns: [/DEL\s+temp/i],
    tags: ['key', 'del', 'delete'],
  },
  {
    id: 'redis-key-002',
    category: 'Key Management',
    difficulty: 'easy',
    title: 'Check Key Existence',
    text: 'Check if key "config" exists.',
    setup: 'Key may or may not exist',
    setupCode: 'SET config value',
    expected: '1',
    sample: 'EXISTS config',
    hints: [
      'Use EXISTS to check existence',
      'Returns 1 if exists, 0 otherwise',
      'Can check multiple keys at once',
    ],
    validPatterns: [/EXISTS\s+config/i],
    tags: ['key', 'exists', 'check'],
  },
  {
    id: 'redis-key-003',
    category: 'Key Management',
    difficulty: 'easy',
    title: 'Set Key Expiration',
    text: 'Set key "session" to expire in 3600 seconds.',
    setup: 'Key "session" exists',
    setupCode: 'SET session data',
    expected: '1',
    sample: 'EXPIRE session 3600',
    hints: [
      'Use EXPIRE to set TTL in seconds',
      'Returns 1 if timeout was set',
      'Returns 0 if key does not exist',
    ],
    validPatterns: [/EXPIRE\s+session\s+3600/i],
    tags: ['key', 'expire', 'ttl'],
  },
  {
    id: 'redis-key-004',
    category: 'Key Management',
    difficulty: 'easy',
    title: 'Get Time-to-Live',
    text: 'Get the remaining TTL of key "cache" in seconds.',
    setup: 'Key "cache" has an expiration set',
    setupCode: 'SET cache data EX 300',
    expected: 'Seconds remaining',
    sample: 'TTL cache',
    hints: [
      'Use TTL to get remaining time',
      'Returns -1 if no expiration',
      'Returns -2 if key does not exist',
    ],
    validPatterns: [/TTL\s+cache/i],
    tags: ['key', 'ttl', 'expiration'],
  },
  {
    id: 'redis-key-005',
    category: 'Key Management',
    difficulty: 'medium',
    title: 'Rename a Key',
    text: 'Rename key "old_name" to "new_name".',
    setup: 'Key "old_name" exists',
    setupCode: 'SET old_name value',
    expected: 'OK',
    sample: 'RENAME old_name new_name',
    hints: [
      'Use RENAME to change key name',
      'Overwrites "new_name" if it exists',
      'Use RENAMENX to avoid overwriting',
    ],
    validPatterns: [/RENAME\s+old_name\s+new_name/i],
    tags: ['key', 'rename'],
  },
  {
    id: 'redis-key-006',
    category: 'Key Management',
    difficulty: 'medium',
    title: 'Get Key Type',
    text: 'Get the data type of key "mykey".',
    setup: 'Key "mykey" contains a list',
    setupCode: 'RPUSH mykey a b c',
    expected: 'list',
    sample: 'TYPE mykey',
    hints: [
      'Use TYPE to get data type',
      'Returns: string, list, set, zset, hash, stream',
      'Returns "none" if key does not exist',
    ],
    validPatterns: [/TYPE\s+mykey/i],
    tags: ['key', 'type'],
  },
  {
    id: 'redis-key-007',
    category: 'Key Management',
    difficulty: 'medium',
    title: 'Find Keys by Pattern',
    text: 'Find all keys matching pattern "user:*".',
    setup: 'Several user keys exist',
    setupCode: 'SET user:1 a\nSET user:2 b\nSET product:1 c',
    expected: ['user:1', 'user:2'],
    sample: 'KEYS user:*',
    hints: [
      'Use KEYS for pattern matching',
      '* matches any characters',
      'Warning: KEYS can block in production',
    ],
    validPatterns: [/KEYS\s+user:\*/i],
    tags: ['key', 'keys', 'pattern'],
  },
  {
    id: 'redis-key-008',
    category: 'Key Management',
    difficulty: 'medium',
    title: 'Remove Expiration',
    text: 'Remove the expiration from key "persistent".',
    setup: 'Key has an expiration set',
    setupCode: 'SET persistent value EX 60',
    expected: '1',
    sample: 'PERSIST persistent',
    hints: [
      'Use PERSIST to remove TTL',
      'Makes key permanent again',
      'Returns 1 if expiration was removed',
    ],
    validPatterns: [/PERSIST\s+persistent/i],
    tags: ['key', 'persist', 'ttl'],
  },
  {
    id: 'redis-key-009',
    category: 'Key Management',
    difficulty: 'medium',
    title: 'Delete Key Asynchronously',
    text: 'Delete key "large_data" asynchronously without blocking.',
    setup: 'Key "large_data" exists',
    setupCode: 'SET large_data value',
    expected: '1',
    sample: 'UNLINK large_data',
    hints: [
      'Use UNLINK for non-blocking delete',
      'Reclaims memory in background',
      'Better than DEL for large values',
    ],
    validPatterns: [/UNLINK\s+large_data/i],
    tags: ['key', 'unlink', 'delete', 'async'],
  },
  {
    id: 'redis-key-010',
    category: 'Key Management',
    difficulty: 'hard',
    title: 'Dump Key Value',
    text: 'Serialize and dump the value of key "object" for backup.',
    setup: 'Key "object" exists',
    setupCode: 'SET object "important data"',
    expected: 'Serialized value',
    sample: 'DUMP object',
    hints: [
      'Use DUMP to serialize a value',
      'Returns RDB-like serialization',
      'Use with RESTORE to recreate',
    ],
    validPatterns: [/DUMP\s+object/i],
    tags: ['key', 'dump', 'serialize', 'backup'],
  },
  {
    id: 'redis-key-011',
    category: 'Key Management',
    difficulty: 'hard',
    title: 'Restore Serialized Value',
    text: 'Restore a serialized value to key "restored" with 0 TTL (no expiration).',
    setup: 'Serialized data available from DUMP',
    setupCode: 'SET temp_source data',
    expected: 'OK',
    sample: 'RESTORE restored 0 "\\x00\\x04data\\n\\x00..."',
    hints: [
      'Use RESTORE with DUMP output',
      'Syntax: RESTORE key ttl serialized-value',
      'TTL 0 means no expiration',
    ],
    validPatterns: [/RESTORE\s+restored\s+0/i],
    tags: ['key', 'restore', 'deserialize'],
  },
  {
    id: 'redis-key-012',
    category: 'Key Management',
    difficulty: 'medium',
    title: 'Get Key Encoding',
    text: 'Get the internal encoding of key "mylist".',
    setup: 'Key "mylist" is a list',
    setupCode: 'RPUSH mylist a b c',
    expected: 'listpack or quicklist',
    sample: 'OBJECT ENCODING mylist',
    hints: [
      'Use OBJECT ENCODING for internal type',
      'Shows memory optimization used',
      'Varies by data and size',
    ],
    validPatterns: [/OBJECT\s+ENCODING\s+mylist/i],
    tags: ['key', 'object', 'encoding'],
  },
  {
    id: 'redis-key-013',
    category: 'Key Management',
    difficulty: 'medium',
    title: 'Touch Key (Update Access Time)',
    text: 'Update the last access time of keys "key1" and "key2".',
    setup: 'Keys exist',
    setupCode: 'SET key1 a\nSET key2 b',
    expected: '2',
    sample: 'TOUCH key1 key2',
    hints: [
      'Use TOUCH to update access time',
      'Affects LRU eviction behavior',
      'Returns count of existing keys',
    ],
    validPatterns: [/TOUCH\s+key1\s+key2/i],
    tags: ['key', 'touch', 'access'],
  },

  // ============================================================
  // TRANSACTIONS (7 problems)
  // ============================================================
  {
    id: 'redis-tx-001',
    category: 'Transactions',
    difficulty: 'medium',
    title: 'Start Transaction',
    text: 'Start a transaction block.',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'OK',
    sample: 'MULTI',
    hints: [
      'Use MULTI to start a transaction',
      'Commands are queued until EXEC',
      'Use DISCARD to abort',
    ],
    validPatterns: [/MULTI/i],
    tags: ['transaction', 'multi', 'basic'],
  },
  {
    id: 'redis-tx-002',
    category: 'Transactions',
    difficulty: 'medium',
    title: 'Execute Transaction',
    text: 'Execute all queued commands in a transaction.',
    setup: 'Transaction started with MULTI',
    setupCode: 'MULTI\nSET key1 value1\nSET key2 value2',
    expected: 'Array of results',
    sample: 'EXEC',
    hints: [
      'Use EXEC to execute queued commands',
      'Returns array of results',
      'Returns nil if WATCH failed',
    ],
    validPatterns: [/EXEC/i],
    tags: ['transaction', 'exec'],
  },
  {
    id: 'redis-tx-003',
    category: 'Transactions',
    difficulty: 'medium',
    title: 'Discard Transaction',
    text: 'Abort the current transaction and discard queued commands.',
    setup: 'Transaction started with MULTI',
    setupCode: 'MULTI\nSET key1 value1',
    expected: 'OK',
    sample: 'DISCARD',
    hints: [
      'Use DISCARD to abort transaction',
      'All queued commands are discarded',
      'Returns to normal command mode',
    ],
    validPatterns: [/DISCARD/i],
    tags: ['transaction', 'discard'],
  },
  {
    id: 'redis-tx-004',
    category: 'Transactions',
    difficulty: 'hard',
    title: 'Watch Key for CAS',
    text: 'Watch key "balance" for changes before starting a transaction.',
    setup: 'Key "balance" exists',
    setupCode: 'SET balance 100',
    expected: 'OK',
    sample: 'WATCH balance',
    hints: [
      'Use WATCH for optimistic locking',
      'Transaction aborts if watched key changes',
      'Implement Compare-And-Set (CAS)',
    ],
    validPatterns: [/WATCH\s+balance/i],
    tags: ['transaction', 'watch', 'cas'],
  },
  {
    id: 'redis-tx-005',
    category: 'Transactions',
    difficulty: 'hard',
    title: 'Unwatch Keys',
    text: 'Stop watching all keys.',
    setup: 'Keys being watched',
    setupCode: 'WATCH key1 key2',
    expected: 'OK',
    sample: 'UNWATCH',
    hints: [
      'Use UNWATCH to stop watching all keys',
      'Called automatically after EXEC',
      'Useful when aborting before MULTI',
    ],
    validPatterns: [/UNWATCH/i],
    tags: ['transaction', 'unwatch'],
  },
  {
    id: 'redis-tx-006',
    category: 'Transactions',
    difficulty: 'hard',
    title: 'WATCH with Failed Transaction',
    text: 'Demonstrate WATCH by checking balance, then MULTI/EXEC to deduct (fails if balance changed).',
    setup: 'Key "balance" exists, another client may modify it',
    setupCode: 'SET balance 100',
    expected: 'nil (if watched key changed) or results',
    sample: 'WATCH balance\nGET balance\nMULTI\nDECRBY balance 50\nEXEC',
    hints: [
      'WATCH enables optimistic locking',
      'EXEC returns nil if watched key changed',
      'Implement retry logic in application',
    ],
    validPatterns: [/WATCH\s+balance[\s\S]*MULTI[\s\S]*DECRBY\s+balance[\s\S]*EXEC/i],
    tags: ['transaction', 'watch', 'cas', 'optimistic-locking'],
  },
  {
    id: 'redis-tx-007',
    category: 'Transactions',
    difficulty: 'hard',
    title: 'Complete Transfer Transaction',
    text: 'Transfer 50 from account:1 to account:2 in a transaction (WATCH both, check balance, transfer).',
    setup: 'Two account keys exist',
    setupCode: 'SET account:1 100\nSET account:2 50',
    expected: 'Array with OK results or nil',
    sample: 'WATCH account:1 account:2\nMULTI\nDECRBY account:1 50\nINCRBY account:2 50\nEXEC',
    hints: [
      'Watch both accounts for safety',
      'Transaction ensures atomicity',
      'Handle nil result (retry needed)',
    ],
    validPatterns: [
      /WATCH\s+account:1\s+account:2[\s\S]*MULTI[\s\S]*DECRBY\s+account:1\s+50[\s\S]*INCRBY\s+account:2\s+50[\s\S]*EXEC/i,
    ],
    tags: ['transaction', 'watch', 'transfer', 'atomic'],
  },

  // ============================================================
  // PUB/SUB (5 problems)
  // ============================================================
  {
    id: 'redis-pubsub-001',
    category: 'Pub/Sub',
    difficulty: 'medium',
    title: 'Subscribe to Channel',
    text: 'Subscribe to the channel "notifications".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'Subscription confirmation',
    sample: 'SUBSCRIBE notifications',
    hints: [
      'Use SUBSCRIBE to listen to channels',
      'Client enters subscription mode',
      'Use UNSUBSCRIBE to exit',
    ],
    validPatterns: [/SUBSCRIBE\s+notifications/i],
    tags: ['pubsub', 'subscribe'],
  },
  {
    id: 'redis-pubsub-002',
    category: 'Pub/Sub',
    difficulty: 'medium',
    title: 'Publish Message',
    text: 'Publish message "Hello World" to channel "chat".',
    setup: 'Channel may have subscribers',
    setupCode: '',
    expected: 'Number of subscribers that received the message',
    sample: 'PUBLISH chat "Hello World"',
    hints: [
      'Use PUBLISH to send messages',
      'Syntax: PUBLISH channel message',
      'Returns number of receivers',
    ],
    validPatterns: [/PUBLISH\s+chat\s+["']?Hello\s*World["']?/i],
    tags: ['pubsub', 'publish'],
  },
  {
    id: 'redis-pubsub-003',
    category: 'Pub/Sub',
    difficulty: 'medium',
    title: 'Pattern Subscribe',
    text: 'Subscribe to all channels matching pattern "news:*".',
    setup: 'Multiple news channels exist',
    setupCode: '',
    expected: 'Pattern subscription confirmation',
    sample: 'PSUBSCRIBE news:*',
    hints: [
      'Use PSUBSCRIBE for pattern matching',
      '* matches any characters',
      'Receives from all matching channels',
    ],
    validPatterns: [/PSUBSCRIBE\s+news:\*/i],
    tags: ['pubsub', 'psubscribe', 'pattern'],
  },
  {
    id: 'redis-pubsub-004',
    category: 'Pub/Sub',
    difficulty: 'easy',
    title: 'Unsubscribe from Channel',
    text: 'Unsubscribe from channel "updates".',
    setup: 'Subscribed to updates channel',
    setupCode: 'SUBSCRIBE updates',
    expected: 'Unsubscription confirmation',
    sample: 'UNSUBSCRIBE updates',
    hints: [
      'Use UNSUBSCRIBE to stop listening',
      'No argument unsubscribes from all',
      'Can specify multiple channels',
    ],
    validPatterns: [/UNSUBSCRIBE\s+updates/i],
    tags: ['pubsub', 'unsubscribe'],
  },
  {
    id: 'redis-pubsub-005',
    category: 'Pub/Sub',
    difficulty: 'medium',
    title: 'List Active Channels',
    text: 'List all active channels with at least one subscriber.',
    setup: 'Some channels have subscribers',
    setupCode: '',
    expected: 'Array of active channels',
    sample: 'PUBSUB CHANNELS',
    hints: [
      'Use PUBSUB CHANNELS to list active channels',
      'Can add pattern: PUBSUB CHANNELS news:*',
      'Only shows channels with subscribers',
    ],
    validPatterns: [/PUBSUB\s+CHANNELS/i],
    tags: ['pubsub', 'channels'],
  },

  // ============================================================
  // HYPERLOGLOG OPERATIONS (10 problems)
  // ============================================================
  {
    id: 'redis-hll-001',
    category: 'HyperLogLog Operations',
    difficulty: 'easy',
    title: 'Add Elements to HyperLogLog',
    text: 'Add elements "user1", "user2", "user3" to HyperLogLog "visitors".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: '1',
    sample: 'PFADD visitors user1 user2 user3',
    hints: [
      'Use PFADD to add elements',
      'Returns 1 if cardinality changed',
      'Probabilistic data structure for counting',
    ],
    validPatterns: [/PFADD\s+visitors\s+["']?user1["']?\s+["']?user2["']?\s+["']?user3["']?/i],
    tags: ['hyperloglog', 'pfadd', 'cardinality'],
  },
  {
    id: 'redis-hll-002',
    category: 'HyperLogLog Operations',
    difficulty: 'easy',
    title: 'Count Unique Elements',
    text: 'Get the approximate count of unique elements in HyperLogLog "unique_visitors".',
    setup: 'HyperLogLog with elements',
    setupCode: 'PFADD unique_visitors a b c d e f g h i j',
    expected: '10',
    sample: 'PFCOUNT unique_visitors',
    hints: [
      'Use PFCOUNT to get cardinality estimate',
      'Standard error of 0.81%',
      'Can count multiple HLLs at once',
    ],
    validPatterns: [/PFCOUNT\s+unique_visitors/i],
    tags: ['hyperloglog', 'pfcount', 'cardinality'],
  },
  {
    id: 'redis-hll-003',
    category: 'HyperLogLog Operations',
    difficulty: 'medium',
    title: 'Merge HyperLogLogs',
    text: 'Merge HyperLogLogs "hll1" and "hll2" into "hll_merged".',
    setup: 'Two HyperLogLogs with different elements',
    setupCode: 'PFADD hll1 a b c\nPFADD hll2 c d e',
    expected: 'OK',
    sample: 'PFMERGE hll_merged hll1 hll2',
    hints: [
      'Use PFMERGE to combine HLLs',
      'Result contains union of all elements',
      'Useful for aggregating counts',
    ],
    validPatterns: [/PFMERGE\s+hll_merged\s+hll1\s+hll2/i],
    tags: ['hyperloglog', 'pfmerge', 'merge'],
  },
  {
    id: 'redis-hll-004',
    category: 'HyperLogLog Operations',
    difficulty: 'medium',
    title: 'Count Multiple HyperLogLogs',
    text: 'Get the combined unique count from "daily_visitors" and "weekly_visitors".',
    setup: 'Two HyperLogLogs exist',
    setupCode: 'PFADD daily_visitors user1 user2 user3\nPFADD weekly_visitors user3 user4 user5',
    expected: '5',
    sample: 'PFCOUNT daily_visitors weekly_visitors',
    hints: [
      'PFCOUNT can take multiple keys',
      'Computes union cardinality',
      'Does not modify the HLLs',
    ],
    validPatterns: [/PFCOUNT\s+daily_visitors\s+weekly_visitors/i],
    tags: ['hyperloglog', 'pfcount', 'union'],
  },
  {
    id: 'redis-hll-005',
    category: 'HyperLogLog Operations',
    difficulty: 'easy',
    title: 'Add Single Element',
    text: 'Add a single unique identifier "session_abc123" to HyperLogLog "sessions".',
    setup: 'HyperLogLog may or may not exist',
    setupCode: 'DEL sessions',
    expected: '1',
    sample: 'PFADD sessions session_abc123',
    hints: [
      'PFADD creates HLL if not exists',
      'Each element is hashed internally',
      'Duplicates do not increase count',
    ],
    validPatterns: [/PFADD\s+sessions\s+["']?session_abc123["']?/i],
    tags: ['hyperloglog', 'pfadd', 'single'],
  },
  {
    id: 'redis-hll-006',
    category: 'HyperLogLog Operations',
    difficulty: 'medium',
    title: 'Track Daily Unique Users',
    text: 'Add user IDs 1001, 1002, 1003 to today\'s HyperLogLog "users:2024-01-15".',
    setup: 'Fresh day tracking',
    setupCode: 'DEL users:2024-01-15',
    expected: '1',
    sample: 'PFADD users:2024-01-15 1001 1002 1003',
    hints: [
      'Use date in key for daily tracking',
      'Each day gets separate HLL',
      'Merge for weekly/monthly counts',
    ],
    validPatterns: [/PFADD\s+users:2024-01-15\s+["']?1001["']?\s+["']?1002["']?\s+["']?1003["']?/i],
    tags: ['hyperloglog', 'pfadd', 'tracking'],
  },
  {
    id: 'redis-hll-007',
    category: 'HyperLogLog Operations',
    difficulty: 'hard',
    title: 'Compute Weekly Unique Users',
    text: 'Merge 7 daily HLLs (day1 through day7) into "week_total".',
    setup: 'Seven daily HyperLogLogs',
    setupCode:
      'PFADD day1 a b\nPFADD day2 b c\nPFADD day3 c d\nPFADD day4 d e\nPFADD day5 e f\nPFADD day6 f g\nPFADD day7 g h',
    expected: 'OK',
    sample: 'PFMERGE week_total day1 day2 day3 day4 day5 day6 day7',
    hints: [
      'PFMERGE accepts multiple source keys',
      'Creates union of all inputs',
      'Result HLL can be further merged',
    ],
    validPatterns: [/PFMERGE\s+week_total\s+day1\s+day2\s+day3\s+day4\s+day5\s+day6\s+day7/i],
    tags: ['hyperloglog', 'pfmerge', 'aggregation'],
  },
  {
    id: 'redis-hll-008',
    category: 'HyperLogLog Operations',
    difficulty: 'medium',
    title: 'Check if HLL Would Change',
    text: 'Add elements that are already in "existing_hll" to see if cardinality changes.',
    setup: 'HLL with known elements',
    setupCode: 'PFADD existing_hll a b c',
    expected: '0',
    sample: 'PFADD existing_hll a b',
    hints: [
      'PFADD returns 0 if no cardinality change',
      'Useful to check for new unique elements',
      'Duplicates are efficiently detected',
    ],
    validPatterns: [/PFADD\s+existing_hll\s+["']?a["']?\s+["']?b["']?/i],
    tags: ['hyperloglog', 'pfadd', 'duplicate'],
  },
  {
    id: 'redis-hll-009',
    category: 'HyperLogLog Operations',
    difficulty: 'hard',
    title: 'Estimate Large Cardinality',
    text: 'Get the count from "big_hll" that tracks millions of elements.',
    setup: 'Large HyperLogLog (simulated)',
    setupCode: 'PFADD big_hll elem1 elem2 elem3 elem4 elem5',
    expected: 'Approximate count',
    sample: 'PFCOUNT big_hll',
    hints: [
      'HLL uses only ~12KB regardless of count',
      'Accuracy is ~0.81% standard error',
      'Handles billions of unique elements',
    ],
    validPatterns: [/PFCOUNT\s+big_hll/i],
    tags: ['hyperloglog', 'pfcount', 'scale'],
  },
  {
    id: 'redis-hll-010',
    category: 'HyperLogLog Operations',
    difficulty: 'medium',
    title: 'Merge Into Existing HLL',
    text: 'Merge "new_data" into existing "total" HyperLogLog (total is both source and destination).',
    setup: 'Existing total and new data',
    setupCode: 'PFADD total x y z\nPFADD new_data a b c',
    expected: 'OK',
    sample: 'PFMERGE total total new_data',
    hints: [
      'Destination can be one of the sources',
      'Adds new unique elements to total',
      'Efficient incremental updates',
    ],
    validPatterns: [/PFMERGE\s+total\s+total\s+new_data/i],
    tags: ['hyperloglog', 'pfmerge', 'update'],
  },

  // ============================================================
  // STREAMS (12 problems)
  // ============================================================
  {
    id: 'redis-stream-001',
    category: 'Streams',
    difficulty: 'easy',
    title: 'Add Entry to Stream',
    text: 'Add an entry with fields "user" = "alice" and "action" = "login" to stream "events".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'Entry ID (e.g., 1234567890123-0)',
    sample: 'XADD events * user alice action login',
    hints: [
      'Use XADD to add stream entries',
      '* auto-generates entry ID',
      'Fields are key-value pairs',
    ],
    validPatterns: [/XADD\s+events\s+\*\s+user\s+["']?alice["']?\s+action\s+["']?login["']?/i],
    tags: ['stream', 'xadd', 'basic'],
  },
  {
    id: 'redis-stream-002',
    category: 'Streams',
    difficulty: 'easy',
    title: 'Read Stream Entries',
    text: 'Read all entries from stream "mystream" starting from the beginning (ID 0).',
    setup: 'Stream with entries',
    setupCode: 'XADD mystream * msg hello\nXADD mystream * msg world',
    expected: 'Array of entries',
    sample: 'XREAD STREAMS mystream 0',
    hints: [
      'Use XREAD to consume stream entries',
      'ID 0 reads from beginning',
      'Use $ to read only new entries',
    ],
    validPatterns: [/XREAD\s+STREAMS\s+mystream\s+0/i],
    tags: ['stream', 'xread', 'consume'],
  },
  {
    id: 'redis-stream-003',
    category: 'Streams',
    difficulty: 'medium',
    title: 'Read Range of Entries',
    text: 'Get entries from stream "log" between IDs - (minimum) and + (maximum).',
    setup: 'Stream with multiple entries',
    setupCode: 'XADD log * level info msg test1\nXADD log * level error msg test2',
    expected: 'Array of entries in range',
    sample: 'XRANGE log - +',
    hints: [
      'Use XRANGE for range queries',
      '- is minimum ID, + is maximum ID',
      'Can specify exact IDs or timestamps',
    ],
    validPatterns: [/XRANGE\s+log\s+-\s+\+/i],
    tags: ['stream', 'xrange', 'range'],
  },
  {
    id: 'redis-stream-004',
    category: 'Streams',
    difficulty: 'easy',
    title: 'Get Stream Length',
    text: 'Get the number of entries in stream "messages".',
    setup: 'Stream with entries',
    setupCode: 'XADD messages * text hello\nXADD messages * text world\nXADD messages * text test',
    expected: '3',
    sample: 'XLEN messages',
    hints: ['Use XLEN to get entry count', 'Returns 0 for non-existent streams', 'O(1) operation'],
    validPatterns: [/XLEN\s+messages/i],
    tags: ['stream', 'xlen', 'length'],
  },
  {
    id: 'redis-stream-005',
    category: 'Streams',
    difficulty: 'hard',
    title: 'Create Consumer Group',
    text: 'Create a consumer group "workers" on stream "tasks" starting from ID 0.',
    setup: 'Stream exists',
    setupCode: 'XADD tasks * job process',
    expected: 'OK',
    sample: 'XGROUP CREATE tasks workers 0',
    hints: [
      'Use XGROUP CREATE for consumer groups',
      'ID 0 reads from beginning',
      'Use $ to read only new entries',
    ],
    validPatterns: [/XGROUP\s+CREATE\s+tasks\s+workers\s+0/i],
    tags: ['stream', 'xgroup', 'consumer-group'],
  },
  {
    id: 'redis-stream-006',
    category: 'Streams',
    difficulty: 'hard',
    title: 'Read with Consumer Group',
    text: 'Read entries from stream "jobs" as consumer "worker1" in group "processors", reading pending messages (>).',
    setup: 'Stream and consumer group exist',
    setupCode: 'XADD jobs * task build\nXGROUP CREATE jobs processors 0 MKSTREAM',
    expected: 'Array of entries or empty',
    sample: 'XREADGROUP GROUP processors worker1 STREAMS jobs >',
    hints: [
      'Use XREADGROUP for group consumption',
      '> reads new messages not yet delivered',
      'Each consumer gets unique messages',
    ],
    validPatterns: [/XREADGROUP\s+GROUP\s+processors\s+worker1\s+STREAMS\s+jobs\s+>/i],
    tags: ['stream', 'xreadgroup', 'consumer-group'],
  },
  {
    id: 'redis-stream-007',
    category: 'Streams',
    difficulty: 'hard',
    title: 'Acknowledge Processed Entry',
    text: 'Acknowledge that entry "1234567890123-0" in stream "work" was processed by group "team".',
    setup: 'Entry was delivered to a consumer',
    setupCode: 'XADD work 1234567890123-0 status pending',
    expected: '1',
    sample: 'XACK work team 1234567890123-0',
    hints: [
      'Use XACK to acknowledge processing',
      'Removes from pending entries list',
      'Can acknowledge multiple IDs at once',
    ],
    validPatterns: [/XACK\s+work\s+team\s+1234567890123-0/i],
    tags: ['stream', 'xack', 'acknowledge'],
  },
  {
    id: 'redis-stream-008',
    category: 'Streams',
    difficulty: 'medium',
    title: 'Trim Stream to Length',
    text: 'Trim stream "logs" to keep only the most recent 1000 entries.',
    setup: 'Stream with many entries',
    setupCode: 'XADD logs * entry 1',
    expected: 'Number of removed entries',
    sample: 'XTRIM logs MAXLEN 1000',
    hints: [
      'Use XTRIM to limit stream size',
      'MAXLEN keeps most recent entries',
      'Use ~ for approximate trimming (faster)',
    ],
    validPatterns: [/XTRIM\s+logs\s+MAXLEN\s+~?\s*1000/i],
    tags: ['stream', 'xtrim', 'trim'],
  },
  {
    id: 'redis-stream-009',
    category: 'Streams',
    difficulty: 'medium',
    title: 'Get Consumer Group Info',
    text: 'Get information about consumer groups for stream "queue".',
    setup: 'Stream with consumer groups',
    setupCode: 'XADD queue * data test\nXGROUP CREATE queue group1 0 MKSTREAM',
    expected: 'Array of group information',
    sample: 'XINFO GROUPS queue',
    hints: [
      'Use XINFO GROUPS for group details',
      'Shows consumers, pending count, last ID',
      'Useful for monitoring',
    ],
    validPatterns: [/XINFO\s+GROUPS\s+queue/i],
    tags: ['stream', 'xinfo', 'groups', 'monitoring'],
  },
  {
    id: 'redis-stream-010',
    category: 'Streams',
    difficulty: 'hard',
    title: 'View Pending Entries',
    text: 'View pending entries for group "workers" on stream "tasks".',
    setup: 'Consumer group with pending entries',
    setupCode:
      'XADD tasks * job 1\nXGROUP CREATE tasks workers 0 MKSTREAM\nXREADGROUP GROUP workers w1 STREAMS tasks >',
    expected: 'Pending entry list summary',
    sample: 'XPENDING tasks workers',
    hints: [
      'Use XPENDING to see unacknowledged entries',
      'Shows count, min/max ID, consumers',
      'Add range for detailed view',
    ],
    validPatterns: [/XPENDING\s+tasks\s+workers/i],
    tags: ['stream', 'xpending', 'pending'],
  },
  {
    id: 'redis-stream-011',
    category: 'Streams',
    difficulty: 'medium',
    title: 'Blocking Stream Read',
    text: 'Read from stream "notifications" with 5 second blocking timeout, starting from latest ($).',
    setup: 'Stream may be empty',
    setupCode: 'DEL notifications',
    expected: 'Entry or nil after timeout',
    sample: 'XREAD BLOCK 5000 STREAMS notifications $',
    hints: ['Use BLOCK for blocking reads', 'Timeout in milliseconds', '$ reads only new entries'],
    validPatterns: [/XREAD\s+BLOCK\s+5000\s+STREAMS\s+notifications\s+\$/i],
    tags: ['stream', 'xread', 'blocking'],
  },
  {
    id: 'redis-stream-012',
    category: 'Streams',
    difficulty: 'medium',
    title: 'Add Entry with Specific ID',
    text: 'Add an entry to stream "ordered" with explicit ID "1000-0" and field "seq" = "first".',
    setup: 'Empty stream',
    setupCode: 'DEL ordered',
    expected: '1000-0',
    sample: 'XADD ordered 1000-0 seq first',
    hints: [
      'Specify ID instead of * for control',
      'ID must be greater than last entry',
      'Format: millisecondsTime-sequenceNumber',
    ],
    validPatterns: [/XADD\s+ordered\s+1000-0\s+seq\s+["']?first["']?/i],
    tags: ['stream', 'xadd', 'explicit-id'],
  },

  // ============================================================
  // GEOSPATIAL (10 problems)
  // ============================================================
  {
    id: 'redis-geo-001',
    category: 'Geospatial',
    difficulty: 'easy',
    title: 'Add Geospatial Point',
    text: 'Add location "office" at longitude -122.4194, latitude 37.7749 to geospatial index "locations".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: '1',
    sample: 'GEOADD locations -122.4194 37.7749 office',
    hints: [
      'Use GEOADD to add coordinates',
      'Syntax: GEOADD key longitude latitude member',
      'Longitude first, then latitude',
    ],
    validPatterns: [/GEOADD\s+locations\s+-?122\.4194\s+37\.7749\s+["']?office["']?/i],
    tags: ['geo', 'geoadd', 'basic'],
  },
  {
    id: 'redis-geo-002',
    category: 'Geospatial',
    difficulty: 'easy',
    title: 'Get Position of Member',
    text: 'Get the coordinates of "store1" from geospatial index "stores".',
    setup: 'Geospatial index with store1',
    setupCode: 'GEOADD stores -73.9857 40.7484 store1',
    expected: 'Array with [longitude, latitude]',
    sample: 'GEOPOS stores store1',
    hints: [
      'Use GEOPOS to get coordinates',
      'Returns array of [lon, lat]',
      'Returns nil for missing members',
    ],
    validPatterns: [/GEOPOS\s+stores\s+["']?store1["']?/i],
    tags: ['geo', 'geopos', 'coordinates'],
  },
  {
    id: 'redis-geo-003',
    category: 'Geospatial',
    difficulty: 'medium',
    title: 'Calculate Distance Between Points',
    text: 'Get the distance between "home" and "work" in kilometers from "places".',
    setup: 'Geospatial index with both locations',
    setupCode: 'GEOADD places -122.4 37.8 home -122.5 37.7 work',
    expected: 'Distance in km',
    sample: 'GEODIST places home work km',
    hints: ['Use GEODIST to calculate distance', 'Units: m, km, mi, ft', 'Default unit is meters'],
    validPatterns: [/GEODIST\s+places\s+["']?home["']?\s+["']?work["']?\s+km/i],
    tags: ['geo', 'geodist', 'distance'],
  },
  {
    id: 'redis-geo-004',
    category: 'Geospatial',
    difficulty: 'medium',
    title: 'Search Within Radius',
    text: 'Find all locations within 10 km of coordinates -122.4194, 37.7749 in "places".',
    setup: 'Geospatial index with multiple locations',
    setupCode: 'GEOADD places -122.4194 37.7749 downtown -122.48 37.78 marina -122.2 37.5 faraway',
    expected: 'Array of matching members',
    sample: 'GEOSEARCH places FROMMEMBER downtown BYRADIUS 10 km',
    hints: [
      'Use GEOSEARCH with BYRADIUS',
      'Can search from member or coordinates',
      'Add WITHDIST for distances',
    ],
    validPatterns: [
      /GEOSEARCH\s+places\s+FROMMEMBER\s+["']?downtown["']?\s+BYRADIUS\s+10\s+km/i,
      /GEOSEARCH\s+places\s+FROMLONLAT\s+-?122\.4194\s+37\.7749\s+BYRADIUS\s+10\s+km/i,
    ],
    tags: ['geo', 'geosearch', 'radius'],
  },
  {
    id: 'redis-geo-005',
    category: 'Geospatial',
    difficulty: 'hard',
    title: 'Search by Radius from Member',
    text: 'Find locations within 50 miles of "headquarters" in "offices", including distances.',
    setup: 'Geospatial index with offices',
    setupCode:
      'GEOADD offices -122.4 37.8 headquarters -121.9 37.3 branch1 -122.1 37.4 branch2 -118.2 34.0 remote',
    expected: 'Array with distances',
    sample: 'GEORADIUSBYMEMBER offices headquarters 50 mi WITHDIST',
    hints: [
      'GEORADIUSBYMEMBER searches from existing member',
      'WITHDIST includes distance in results',
      'Note: GEOSEARCH is the newer alternative',
    ],
    validPatterns: [
      /GEORADIUSBYMEMBER\s+offices\s+["']?headquarters["']?\s+50\s+mi\s+WITHDIST/i,
      /GEOSEARCH\s+offices\s+FROMMEMBER\s+["']?headquarters["']?\s+BYRADIUS\s+50\s+mi\s+WITHDIST/i,
    ],
    tags: ['geo', 'georadiusbymember', 'radius'],
  },
  {
    id: 'redis-geo-006',
    category: 'Geospatial',
    difficulty: 'medium',
    title: 'Get Geohash of Location',
    text: 'Get the geohash string representation of "landmark" from "points".',
    setup: 'Geospatial index with landmark',
    setupCode: 'GEOADD points -122.4194 37.7749 landmark',
    expected: 'Geohash string',
    sample: 'GEOHASH points landmark',
    hints: [
      'Use GEOHASH for hash representation',
      'Returns 11-character geohash',
      'Useful for external geohash APIs',
    ],
    validPatterns: [/GEOHASH\s+points\s+["']?landmark["']?/i],
    tags: ['geo', 'geohash', 'hash'],
  },
  {
    id: 'redis-geo-007',
    category: 'Geospatial',
    difficulty: 'medium',
    title: 'Add Multiple Locations',
    text: 'Add three cities to "cities": NYC (-74.006, 40.7128), LA (-118.2437, 34.0522), Chicago (-87.6298, 41.8781).',
    setup: 'Empty geospatial index',
    setupCode: 'DEL cities',
    expected: '3',
    sample: 'GEOADD cities -74.006 40.7128 NYC -118.2437 34.0522 LA -87.6298 41.8781 Chicago',
    hints: [
      'GEOADD accepts multiple locations',
      'Each location: longitude latitude member',
      'Returns count of new members added',
    ],
    validPatterns: [/GEOADD\s+cities.*NYC.*LA.*Chicago/i],
    tags: ['geo', 'geoadd', 'multiple'],
  },
  {
    id: 'redis-geo-008',
    category: 'Geospatial',
    difficulty: 'hard',
    title: 'Search Box Region',
    text: 'Find locations within a 100km x 100km box centered at coordinates -122.4, 37.8 in "region".',
    setup: 'Geospatial index with locations',
    setupCode: 'GEOADD region -122.4 37.8 center -122.3 37.85 nearby -121.0 36.0 outside',
    expected: 'Array of matching locations',
    sample: 'GEOSEARCH region FROMLONLAT -122.4 37.8 BYBOX 100 100 km',
    hints: [
      'Use GEOSEARCH with BYBOX',
      'Specify width and height',
      'Finds locations in rectangular area',
    ],
    validPatterns: [/GEOSEARCH\s+region\s+FROMLONLAT\s+-?122\.4\s+37\.8\s+BYBOX\s+100\s+100\s+km/i],
    tags: ['geo', 'geosearch', 'box'],
  },
  {
    id: 'redis-geo-009',
    category: 'Geospatial',
    difficulty: 'hard',
    title: 'Search with Coordinates and Options',
    text: 'Find 5 nearest locations to (-122.4, 37.8) within 50km from "venues", sorted by distance ascending.',
    setup: 'Geospatial index with venues',
    setupCode:
      'GEOADD venues -122.4 37.8 venue1 -122.45 37.78 venue2 -122.35 37.82 venue3 -122.5 37.75 venue4 -122.38 37.81 venue5 -122.6 37.7 venue6',
    expected: 'Sorted array of 5 nearest venues',
    sample: 'GEOSEARCH venues FROMLONLAT -122.4 37.8 BYRADIUS 50 km ASC COUNT 5',
    hints: [
      'ASC sorts by nearest first',
      'COUNT limits results',
      'Can combine with WITHDIST, WITHCOORD',
    ],
    validPatterns: [
      /GEOSEARCH\s+venues\s+FROMLONLAT\s+-?122\.4\s+37\.8\s+BYRADIUS\s+50\s+km\s+ASC\s+COUNT\s+5/i,
    ],
    tags: ['geo', 'geosearch', 'sorted', 'limit'],
  },
  {
    id: 'redis-geo-010',
    category: 'Geospatial',
    difficulty: 'easy',
    title: 'Get Distance in Miles',
    text: 'Get the distance between "Boston" and "NYC" in miles from "cities".',
    setup: 'Geospatial index with cities',
    setupCode: 'GEOADD cities -71.0589 42.3601 Boston -74.006 40.7128 NYC',
    expected: 'Distance in miles',
    sample: 'GEODIST cities Boston NYC mi',
    hints: ['Use mi for miles unit', 'Other units: m, km, ft', 'Returns nil if member missing'],
    validPatterns: [/GEODIST\s+cities\s+["']?Boston["']?\s+["']?NYC["']?\s+mi/i],
    tags: ['geo', 'geodist', 'miles'],
  },

  // ============================================================
  // BITMAPS (10 problems)
  // ============================================================
  {
    id: 'redis-bitmap-001',
    category: 'Bitmaps',
    difficulty: 'easy',
    title: 'Set Bit Value',
    text: 'Set bit at offset 7 to 1 in bitmap "flags".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: '0 (previous bit value)',
    sample: 'SETBIT flags 7 1',
    hints: [
      'Use SETBIT to set individual bits',
      'Syntax: SETBIT key offset value',
      'Returns the original bit value',
    ],
    validPatterns: [/SETBIT\s+flags\s+7\s+1/i],
    tags: ['bitmap', 'setbit', 'basic'],
  },
  {
    id: 'redis-bitmap-002',
    category: 'Bitmaps',
    difficulty: 'easy',
    title: 'Get Bit Value',
    text: 'Get the bit value at offset 3 in bitmap "status".',
    setup: 'Bitmap with some bits set',
    setupCode: 'SETBIT status 3 1',
    expected: '1',
    sample: 'GETBIT status 3',
    hints: [
      'Use GETBIT to read individual bits',
      'Returns 0 or 1',
      'Returns 0 for out-of-range offsets',
    ],
    validPatterns: [/GETBIT\s+status\s+3/i],
    tags: ['bitmap', 'getbit', 'basic'],
  },
  {
    id: 'redis-bitmap-003',
    category: 'Bitmaps',
    difficulty: 'medium',
    title: 'Count Set Bits',
    text: 'Count the number of bits set to 1 in bitmap "active_users".',
    setup: 'Bitmap with several bits set',
    setupCode:
      'SETBIT active_users 1 1\nSETBIT active_users 5 1\nSETBIT active_users 10 1\nSETBIT active_users 100 1',
    expected: '4',
    sample: 'BITCOUNT active_users',
    hints: [
      'Use BITCOUNT for population count',
      'Can specify byte range',
      'Efficient for large bitmaps',
    ],
    validPatterns: [/BITCOUNT\s+active_users/i],
    tags: ['bitmap', 'bitcount', 'count'],
  },
  {
    id: 'redis-bitmap-004',
    category: 'Bitmaps',
    difficulty: 'medium',
    title: 'Bitwise AND Operation',
    text: 'Perform AND operation on "bitmap1" and "bitmap2", store result in "result".',
    setup: 'Two bitmaps with overlapping bits',
    setupCode: 'SETBIT bitmap1 0 1\nSETBIT bitmap1 1 1\nSETBIT bitmap2 1 1\nSETBIT bitmap2 2 1',
    expected: 'Length of result string',
    sample: 'BITOP AND result bitmap1 bitmap2',
    hints: [
      'Use BITOP for bitwise operations',
      'Operations: AND, OR, XOR, NOT',
      'Returns length of resulting string',
    ],
    validPatterns: [/BITOP\s+AND\s+result\s+bitmap1\s+bitmap2/i],
    tags: ['bitmap', 'bitop', 'and'],
  },
  {
    id: 'redis-bitmap-005',
    category: 'Bitmaps',
    difficulty: 'medium',
    title: 'Find First Set Bit',
    text: 'Find the position of the first bit set to 1 in bitmap "events".',
    setup: 'Bitmap with bits set',
    setupCode: 'SETBIT events 100 1\nSETBIT events 200 1',
    expected: '100',
    sample: 'BITPOS events 1',
    hints: ['Use BITPOS to find first bit', 'Search for 0 or 1', 'Can specify byte range'],
    validPatterns: [/BITPOS\s+events\s+1/i],
    tags: ['bitmap', 'bitpos', 'find'],
  },
  {
    id: 'redis-bitmap-006',
    category: 'Bitmaps',
    difficulty: 'hard',
    title: 'Bitfield Get Operation',
    text: 'Get an unsigned 8-bit integer starting at bit offset 0 from "counters".',
    setup: 'Bitmap with data',
    setupCode: 'SET counters "\\xff"',
    expected: '255',
    sample: 'BITFIELD counters GET u8 0',
    hints: [
      'Use BITFIELD for complex bit operations',
      'u8 = unsigned 8-bit, i8 = signed',
      'Offset in bits',
    ],
    validPatterns: [/BITFIELD\s+counters\s+GET\s+u8\s+0/i],
    tags: ['bitmap', 'bitfield', 'get'],
  },
  {
    id: 'redis-bitmap-007',
    category: 'Bitmaps',
    difficulty: 'hard',
    title: 'Bitfield Set Operation',
    text: 'Set an unsigned 4-bit value of 15 at bit offset 0 in "nibbles".',
    setup: 'Empty bitmap',
    setupCode: 'DEL nibbles',
    expected: '0 (previous value)',
    sample: 'BITFIELD nibbles SET u4 0 15',
    hints: [
      'BITFIELD SET writes bit sequences',
      'u4 = unsigned 4-bit integer',
      'Returns previous value at that position',
    ],
    validPatterns: [/BITFIELD\s+nibbles\s+SET\s+u4\s+0\s+15/i],
    tags: ['bitmap', 'bitfield', 'set'],
  },
  {
    id: 'redis-bitmap-008',
    category: 'Bitmaps',
    difficulty: 'medium',
    title: 'Bitwise OR Operation',
    text: 'Combine "monday" and "tuesday" attendance bitmaps with OR into "either_day".',
    setup: 'Two attendance bitmaps',
    setupCode: 'SETBIT monday 1 1\nSETBIT monday 3 1\nSETBIT tuesday 2 1\nSETBIT tuesday 3 1',
    expected: 'Length of result',
    sample: 'BITOP OR either_day monday tuesday',
    hints: [
      'OR combines all set bits',
      'Result has bit set if any source has it',
      'Useful for union operations',
    ],
    validPatterns: [/BITOP\s+OR\s+either_day\s+monday\s+tuesday/i],
    tags: ['bitmap', 'bitop', 'or'],
  },
  {
    id: 'redis-bitmap-009',
    category: 'Bitmaps',
    difficulty: 'medium',
    title: 'Count Bits in Range',
    text: 'Count bits set to 1 in first 10 bytes of bitmap "large_bitmap".',
    setup: 'Large bitmap',
    setupCode: 'SETBIT large_bitmap 0 1\nSETBIT large_bitmap 50 1\nSETBIT large_bitmap 100 1',
    expected: 'Count in range',
    sample: 'BITCOUNT large_bitmap 0 9',
    hints: [
      'BITCOUNT with range is in bytes',
      'Byte 0-9 = first 80 bits',
      'Useful for time-sliced counting',
    ],
    validPatterns: [/BITCOUNT\s+large_bitmap\s+0\s+9/i],
    tags: ['bitmap', 'bitcount', 'range'],
  },
  {
    id: 'redis-bitmap-010',
    category: 'Bitmaps',
    difficulty: 'hard',
    title: 'Bitfield Increment',
    text: 'Increment an unsigned 8-bit counter at offset 0 in "byte_counters" by 1, with saturation overflow.',
    setup: 'Counter bitmap',
    setupCode: 'BITFIELD byte_counters SET u8 0 254',
    expected: '255',
    sample: 'BITFIELD byte_counters OVERFLOW SAT INCRBY u8 0 1',
    hints: [
      'INCRBY increments bitfield integers',
      'OVERFLOW controls behavior: WRAP, SAT, FAIL',
      'SAT saturates at min/max value',
    ],
    validPatterns: [/BITFIELD\s+byte_counters\s+OVERFLOW\s+SAT\s+INCRBY\s+u8\s+0\s+1/i],
    tags: ['bitmap', 'bitfield', 'incrby', 'overflow'],
  },

  // ============================================================
  // SCRIPTING (8 problems)
  // ============================================================
  {
    id: 'redis-script-001',
    category: 'Scripting',
    difficulty: 'medium',
    title: 'Execute Lua Script',
    text: 'Execute a Lua script that returns the value of key "mykey" using EVAL.',
    setup: 'Key exists',
    setupCode: 'SET mykey hello',
    expected: 'hello',
    sample: 'EVAL "return redis.call(\'GET\', KEYS[1])" 1 mykey',
    hints: [
      'Use EVAL to run Lua scripts',
      'Syntax: EVAL script numkeys key1 ... arg1 ...',
      'KEYS[1] refers to first key',
    ],
    validPatterns: [/EVAL\s+["'].*redis\.call.*GET.*KEYS\[1\].*["']\s+1\s+mykey/i],
    tags: ['scripting', 'eval', 'lua', 'basic'],
  },
  {
    id: 'redis-script-002',
    category: 'Scripting',
    difficulty: 'hard',
    title: 'Execute Cached Script',
    text: 'Execute a script with SHA1 hash "abc123..." using EVALSHA with key "counter".',
    setup: 'Script is loaded',
    setupCode: 'SCRIPT LOAD "return redis.call(\'INCR\', KEYS[1])"',
    expected: 'Incremented value',
    sample: 'EVALSHA abc123def456 1 counter',
    hints: [
      'EVALSHA uses cached script by SHA1',
      'Faster than EVAL for repeated calls',
      'Falls back to EVAL if not cached',
    ],
    validPatterns: [/EVALSHA\s+\w+\s+1\s+counter/i],
    tags: ['scripting', 'evalsha', 'cache'],
  },
  {
    id: 'redis-script-003',
    category: 'Scripting',
    difficulty: 'medium',
    title: 'Load Script to Cache',
    text: 'Load the script "return 1" into the script cache and get its SHA1 hash.',
    setup: 'Empty script cache',
    setupCode: 'SCRIPT FLUSH',
    expected: 'SHA1 hash string',
    sample: 'SCRIPT LOAD "return 1"',
    hints: [
      'Use SCRIPT LOAD to cache scripts',
      'Returns SHA1 hash of script',
      'Use hash with EVALSHA',
    ],
    validPatterns: [/SCRIPT\s+LOAD\s+["']return\s+1["']/i],
    tags: ['scripting', 'script-load', 'cache'],
  },
  {
    id: 'redis-script-004',
    category: 'Scripting',
    difficulty: 'medium',
    title: 'Check Script Existence',
    text: 'Check if scripts with SHA1 hashes "sha1" and "sha2" exist in the cache.',
    setup: 'Some scripts may be cached',
    setupCode: 'SCRIPT LOAD "return 1"',
    expected: 'Array of 0s and 1s',
    sample: 'SCRIPT EXISTS sha1 sha2',
    hints: [
      'SCRIPT EXISTS checks multiple hashes',
      'Returns 1 if cached, 0 if not',
      'Useful before EVALSHA',
    ],
    validPatterns: [/SCRIPT\s+EXISTS\s+\w+\s+\w+/i],
    tags: ['scripting', 'script-exists', 'check'],
  },
  {
    id: 'redis-script-005',
    category: 'Scripting',
    difficulty: 'easy',
    title: 'Flush Script Cache',
    text: 'Clear all scripts from the script cache.',
    setup: 'Scripts are cached',
    setupCode: 'SCRIPT LOAD "return 1"',
    expected: 'OK',
    sample: 'SCRIPT FLUSH',
    hints: [
      'SCRIPT FLUSH clears all cached scripts',
      'Use after script updates',
      'Can add ASYNC for non-blocking',
    ],
    validPatterns: [/SCRIPT\s+FLUSH/i],
    tags: ['scripting', 'script-flush', 'cache'],
  },
  {
    id: 'redis-script-006',
    category: 'Scripting',
    difficulty: 'hard',
    title: 'Atomic Compare and Set',
    text: 'Write a Lua script that sets key to new value only if current value equals expected (CAS).',
    setup: 'Key with known value',
    setupCode: 'SET cas_key old_value',
    expected: '1 (success) or 0 (failure)',
    sample:
      "EVAL \"if redis.call('GET', KEYS[1]) == ARGV[1] then redis.call('SET', KEYS[1], ARGV[2]) return 1 else return 0 end\" 1 cas_key old_value new_value",
    hints: [
      'Lua scripts are atomic in Redis',
      'ARGV contains additional arguments',
      'Perfect for compare-and-set operations',
    ],
    validPatterns: [/EVAL\s+["'].*GET.*KEYS\[1\].*==.*ARGV\[1\].*SET.*KEYS\[1\].*ARGV\[2\].*["']/i],
    tags: ['scripting', 'eval', 'cas', 'atomic'],
  },
  {
    id: 'redis-script-007',
    category: 'Scripting',
    difficulty: 'hard',
    title: 'Rate Limiter Script',
    text: 'Write a script that increments a counter and sets expiry, returning count (for rate limiting).',
    setup: 'Empty key or existing counter',
    setupCode: 'DEL rate_limit_key',
    expected: 'Current count',
    sample:
      "EVAL \"local count = redis.call('INCR', KEYS[1]) if count == 1 then redis.call('EXPIRE', KEYS[1], ARGV[1]) end return count\" 1 rate_limit_key 60",
    hints: [
      'INCR creates key if not exists',
      'Set EXPIRE only on first increment',
      'Common pattern for rate limiting',
    ],
    validPatterns: [/EVAL\s+["'].*INCR.*KEYS\[1\].*EXPIRE.*KEYS\[1\].*ARGV\[1\].*["']/i],
    tags: ['scripting', 'eval', 'rate-limit'],
  },
  {
    id: 'redis-script-008',
    category: 'Scripting',
    difficulty: 'medium',
    title: 'Script with Multiple Keys',
    text: 'Execute a script that swaps values between two keys "key1" and "key2".',
    setup: 'Two keys with values',
    setupCode: 'SET key1 value1\nSET key2 value2',
    expected: 'OK',
    sample:
      "EVAL \"local temp = redis.call('GET', KEYS[1]) redis.call('SET', KEYS[1], redis.call('GET', KEYS[2])) redis.call('SET', KEYS[2], temp) return 'OK'\" 2 key1 key2",
    hints: [
      'Use numkeys=2 for two keys',
      'KEYS[1] and KEYS[2] access them',
      'All operations are atomic',
    ],
    validPatterns: [
      /EVAL\s+["'].*GET.*KEYS\[1\].*GET.*KEYS\[2\].*SET.*KEYS\[2\].*["']\s+2\s+key1\s+key2/i,
    ],
    tags: ['scripting', 'eval', 'multiple-keys', 'swap'],
  },
];

// ── Helper functions for Redis problems ────────────────────────

export function getRedisProblemsById(id: string) {
  return redisProblems.find((p) => p.id === id);
}

export function getRedisProblemsByCategory(category: string) {
  return redisProblems.filter((p) => p.category === category);
}

export function getRedisProblemsByDifficulty(difficulty: 'easy' | 'medium' | 'hard') {
  return redisProblems.filter((p) => p.difficulty === difficulty);
}

export function getRedisProblemsByTag(tag: string) {
  return redisProblems.filter((p) => p.tags?.includes(tag));
}

export function getRedisCategories(): string[] {
  return [...new Set(redisProblems.map((p) => p.category))];
}
