import type { Problem } from '../types';

/**
 * Redis problems for coding drills
 * Covers String Operations, List Operations, Hash Operations,
 * Set Operations, Sorted Set Operations, Key Management, Pub/Sub, Transactions, and Scripting
 */

export const redisProblems: Problem[] = [
  // ============================================================
  // STRING OPERATIONS (12 problems)
  // ============================================================
  {
    id: 'redis-str-001',
    category: 'String Operations',
    difficulty: 'easy',
    title: 'Set a Key-Value Pair',
    text: 'Set the key "name" to the value "Alice".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'OK',
    sample: 'SET name Alice',
    hints: ['Use the SET command', 'Syntax: SET key value', 'Redis returns OK on success'],
    validPatterns: [/SET\s+name\s+["']?Alice["']?/i],
    tags: ['string', 'set', 'basic'],
  },
  {
    id: 'redis-str-002',
    category: 'String Operations',
    difficulty: 'easy',
    title: 'Get a Value by Key',
    text: 'Retrieve the value stored at key "username".',
    setup: 'Key "username" contains "john_doe"',
    setupCode: 'SET username john_doe',
    expected: 'john_doe',
    sample: 'GET username',
    hints: [
      'Use the GET command',
      'Syntax: GET key',
      'Returns the value or nil if key does not exist',
    ],
    validPatterns: [/GET\s+username/i],
    tags: ['string', 'get', 'basic'],
  },
  {
    id: 'redis-str-003',
    category: 'String Operations',
    difficulty: 'easy',
    title: 'Increment a Counter',
    text: 'Increment the numeric value stored at key "views" by 1.',
    setup: 'Key "views" contains "100"',
    setupCode: 'SET views 100',
    expected: '101',
    sample: 'INCR views',
    hints: [
      'Use the INCR command for atomic increment',
      'INCR increments by 1',
      'The value must be a valid integer string',
    ],
    validPatterns: [/INCR\s+views/i],
    tags: ['string', 'incr', 'counter'],
  },
  {
    id: 'redis-str-004',
    category: 'String Operations',
    difficulty: 'easy',
    title: 'Increment by Specific Amount',
    text: 'Increase the counter "score" by 50 points.',
    setup: 'Key "score" contains "200"',
    setupCode: 'SET score 200',
    expected: '250',
    sample: 'INCRBY score 50',
    hints: ['Use INCRBY for specific increment amounts', 'Syntax: INCRBY key increment'],
    validPatterns: [/INCRBY\s+score\s+50/i],
    tags: ['string', 'incrby', 'counter'],
  },
  {
    id: 'redis-str-005',
    category: 'String Operations',
    difficulty: 'easy',
    title: 'Decrement a Counter',
    text: 'Decrement the numeric value stored at key "stock" by 1.',
    setup: 'Key "stock" contains "50"',
    setupCode: 'SET stock 50',
    expected: '49',
    sample: 'DECR stock',
    hints: [
      'Use the DECR command',
      'DECR decrements by 1',
      'Returns the new value after decrementing',
    ],
    validPatterns: [/DECR\s+stock/i],
    tags: ['string', 'decr', 'counter'],
  },
  {
    id: 'redis-str-006',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Set with Expiration',
    text: 'Set the key "session" to "abc123" with a 60 second expiration.',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'OK',
    sample: 'SET session abc123 EX 60',
    hints: [
      'Use SET with the EX option for seconds',
      'EX sets expiration in seconds',
      'Alternative: SETEX session 60 abc123',
    ],
    validPatterns: [
      /SET\s+session\s+["']?abc123["']?\s+EX\s+60/i,
      /SETEX\s+session\s+60\s+["']?abc123["']?/i,
    ],
    tags: ['string', 'set', 'expiration', 'ttl'],
  },
  {
    id: 'redis-str-007',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Set Only If Not Exists',
    text: 'Set the key "lock" to "1" only if it does not already exist.',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'OK or 1',
    sample: 'SET lock 1 NX',
    hints: [
      'Use SET with NX option',
      'NX means "only set if Not eXists"',
      'Alternative: SETNX lock 1',
    ],
    validPatterns: [/SET\s+lock\s+["']?1["']?\s+NX/i, /SETNX\s+lock\s+["']?1["']?/i],
    tags: ['string', 'set', 'nx', 'lock'],
  },
  {
    id: 'redis-str-008',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Append to String',
    text: 'Append " World" to the existing value at key "greeting".',
    setup: 'Key "greeting" contains "Hello"',
    setupCode: 'SET greeting Hello',
    expected: '11',
    sample: 'APPEND greeting " World"',
    hints: [
      'Use the APPEND command',
      'APPEND returns the length of the string after appending',
      'Syntax: APPEND key value',
    ],
    validPatterns: [/APPEND\s+greeting\s+["'] ?World["']/i],
    tags: ['string', 'append'],
  },
  {
    id: 'redis-str-009',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Get String Length',
    text: 'Get the length of the string stored at key "message".',
    setup: 'Key "message" contains "Hello Redis"',
    setupCode: 'SET message "Hello Redis"',
    expected: '11',
    sample: 'STRLEN message',
    hints: [
      'Use the STRLEN command',
      'Returns the length of the string value',
      'Returns 0 if key does not exist',
    ],
    validPatterns: [/STRLEN\s+message/i],
    tags: ['string', 'strlen', 'length'],
  },
  {
    id: 'redis-str-010',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Get Substring',
    text: 'Get characters 0 through 4 (inclusive) from the string at key "text".',
    setup: 'Key "text" contains "Hello World"',
    setupCode: 'SET text "Hello World"',
    expected: 'Hello',
    sample: 'GETRANGE text 0 4',
    hints: [
      'Use the GETRANGE command',
      'Syntax: GETRANGE key start end',
      'Both start and end are inclusive',
    ],
    validPatterns: [/GETRANGE\s+text\s+0\s+4/i],
    tags: ['string', 'getrange', 'substring'],
  },
  {
    id: 'redis-str-011',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Set Multiple Keys',
    text: 'Set keys "a" to "1", "b" to "2", and "c" to "3" in one command.',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'OK',
    sample: 'MSET a 1 b 2 c 3',
    hints: [
      'Use MSET for multiple key-value pairs',
      'Syntax: MSET key1 value1 key2 value2 ...',
      'Atomic operation - all keys set at once',
    ],
    validPatterns: [/MSET\s+a\s+["']?1["']?\s+b\s+["']?2["']?\s+c\s+["']?3["']?/i],
    tags: ['string', 'mset', 'bulk'],
  },
  {
    id: 'redis-str-012',
    category: 'String Operations',
    difficulty: 'medium',
    title: 'Get Multiple Keys',
    text: 'Get the values of keys "first", "second", and "third" in one command.',
    setup: 'Keys set with different values',
    setupCode: 'MSET first "a" second "b" third "c"',
    expected: ['a', 'b', 'c'],
    sample: 'MGET first second third',
    hints: [
      'Use MGET for retrieving multiple keys',
      'Syntax: MGET key1 key2 key3 ...',
      'Returns nil for keys that do not exist',
    ],
    validPatterns: [/MGET\s+first\s+second\s+third/i],
    tags: ['string', 'mget', 'bulk'],
  },

  // ============================================================
  // LIST OPERATIONS (10 problems)
  // ============================================================
  {
    id: 'redis-list-001',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Push to List Head',
    text: 'Add the value "first" to the head (left) of list "queue".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: '1',
    sample: 'LPUSH queue first',
    hints: [
      'Use LPUSH to add to the left (head) of a list',
      'Syntax: LPUSH key value',
      'Returns the length of the list after push',
    ],
    validPatterns: [/LPUSH\s+queue\s+["']?first["']?/i],
    tags: ['list', 'lpush', 'basic'],
  },
  {
    id: 'redis-list-002',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Push to List Tail',
    text: 'Add the value "last" to the tail (right) of list "queue".',
    setup: 'List "queue" exists with some elements',
    setupCode: 'RPUSH queue one two',
    expected: '3',
    sample: 'RPUSH queue last',
    hints: [
      'Use RPUSH to add to the right (tail) of a list',
      'Syntax: RPUSH key value',
      'Returns the length of the list after push',
    ],
    validPatterns: [/RPUSH\s+queue\s+["']?last["']?/i],
    tags: ['list', 'rpush', 'basic'],
  },
  {
    id: 'redis-list-003',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Pop from List Head',
    text: 'Remove and return the first element from list "tasks".',
    setup: 'List "tasks" contains ["urgent", "normal", "low"]',
    setupCode: 'RPUSH tasks urgent normal low',
    expected: 'urgent',
    sample: 'LPOP tasks',
    hints: [
      'Use LPOP to remove from the left (head)',
      'Returns the removed element',
      'Returns nil if list is empty',
    ],
    validPatterns: [/LPOP\s+tasks/i],
    tags: ['list', 'lpop', 'basic'],
  },
  {
    id: 'redis-list-004',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Pop from List Tail',
    text: 'Remove and return the last element from list "stack".',
    setup: 'List "stack" contains ["a", "b", "c"]',
    setupCode: 'RPUSH stack a b c',
    expected: 'c',
    sample: 'RPOP stack',
    hints: [
      'Use RPOP to remove from the right (tail)',
      'Perfect for stack operations (LIFO)',
      'Returns nil if list is empty',
    ],
    validPatterns: [/RPOP\s+stack/i],
    tags: ['list', 'rpop', 'stack'],
  },
  {
    id: 'redis-list-005',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Get List Range',
    text: 'Get all elements from list "items" (from index 0 to -1).',
    setup: 'List "items" contains ["apple", "banana", "cherry"]',
    setupCode: 'RPUSH items apple banana cherry',
    expected: ['apple', 'banana', 'cherry'],
    sample: 'LRANGE items 0 -1',
    hints: [
      'Use LRANGE to get elements by index range',
      '-1 means the last element',
      '0 -1 returns all elements',
    ],
    validPatterns: [/LRANGE\s+items\s+0\s+-1/i],
    tags: ['list', 'lrange', 'range'],
  },
  {
    id: 'redis-list-006',
    category: 'List Operations',
    difficulty: 'easy',
    title: 'Get List Length',
    text: 'Get the number of elements in list "mylist".',
    setup: 'List "mylist" contains 5 elements',
    setupCode: 'RPUSH mylist a b c d e',
    expected: '5',
    sample: 'LLEN mylist',
    hints: ['Use LLEN to get the length of a list', 'Returns 0 for non-existent keys'],
    validPatterns: [/LLEN\s+mylist/i],
    tags: ['list', 'llen', 'length'],
  },
  {
    id: 'redis-list-007',
    category: 'List Operations',
    difficulty: 'medium',
    title: 'Get Element by Index',
    text: 'Get the element at index 2 from list "colors".',
    setup: 'List "colors" contains ["red", "green", "blue", "yellow"]',
    setupCode: 'RPUSH colors red green blue yellow',
    expected: 'blue',
    sample: 'LINDEX colors 2',
    hints: [
      'Use LINDEX to get element at specific index',
      'Index is 0-based',
      'Negative indices count from the end',
    ],
    validPatterns: [/LINDEX\s+colors\s+2/i],
    tags: ['list', 'lindex', 'index'],
  },
  {
    id: 'redis-list-008',
    category: 'List Operations',
    difficulty: 'medium',
    title: 'Set Element by Index',
    text: 'Change the element at index 1 in list "names" to "Bob".',
    setup: 'List "names" contains ["Alice", "Charlie", "Dave"]',
    setupCode: 'RPUSH names Alice Charlie Dave',
    expected: 'OK',
    sample: 'LSET names 1 Bob',
    hints: [
      'Use LSET to update an element at a specific index',
      'Syntax: LSET key index value',
      'Returns an error if index is out of range',
    ],
    validPatterns: [/LSET\s+names\s+1\s+["']?Bob["']?/i],
    tags: ['list', 'lset', 'update'],
  },
  {
    id: 'redis-list-009',
    category: 'List Operations',
    difficulty: 'medium',
    title: 'Remove Elements by Value',
    text: 'Remove all occurrences of "spam" from list "messages".',
    setup: 'List "messages" contains ["hello", "spam", "world", "spam"]',
    setupCode: 'RPUSH messages hello spam world spam',
    expected: '2',
    sample: 'LREM messages 0 spam',
    hints: [
      'Use LREM to remove elements by value',
      'Count 0 removes ALL matching elements',
      'Positive count removes from head, negative from tail',
    ],
    validPatterns: [/LREM\s+messages\s+0\s+["']?spam["']?/i],
    tags: ['list', 'lrem', 'remove'],
  },
  {
    id: 'redis-list-010',
    category: 'List Operations',
    difficulty: 'hard',
    title: 'Blocking Pop',
    text: 'Pop from the left of list "jobs" with a 5 second timeout if empty.',
    setup: 'List "jobs" may or may not have elements',
    setupCode: 'DEL jobs',
    expected: 'Element or nil after timeout',
    sample: 'BLPOP jobs 5',
    hints: [
      'Use BLPOP for blocking pop operations',
      'Syntax: BLPOP key timeout',
      'Useful for message queues',
    ],
    validPatterns: [/BLPOP\s+jobs\s+5/i],
    tags: ['list', 'blpop', 'blocking', 'queue'],
  },

  // ============================================================
  // HASH OPERATIONS (10 problems)
  // ============================================================
  {
    id: 'redis-hash-001',
    category: 'Hash Operations',
    difficulty: 'easy',
    title: 'Set Hash Field',
    text: 'Set the field "name" to "John" in hash "user:1".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: '1',
    sample: 'HSET user:1 name John',
    hints: [
      'Use HSET to set a field in a hash',
      'Syntax: HSET key field value',
      'Returns 1 if field is new, 0 if updated',
    ],
    validPatterns: [/HSET\s+user:1\s+name\s+["']?John["']?/i],
    tags: ['hash', 'hset', 'basic'],
  },
  {
    id: 'redis-hash-002',
    category: 'Hash Operations',
    difficulty: 'easy',
    title: 'Get Hash Field',
    text: 'Get the value of field "email" from hash "user:1".',
    setup: 'Hash "user:1" has field "email" set',
    setupCode: 'HSET user:1 email john@example.com',
    expected: 'john@example.com',
    sample: 'HGET user:1 email',
    hints: [
      'Use HGET to get a single field value',
      'Syntax: HGET key field',
      'Returns nil if field does not exist',
    ],
    validPatterns: [/HGET\s+user:1\s+email/i],
    tags: ['hash', 'hget', 'basic'],
  },
  {
    id: 'redis-hash-003',
    category: 'Hash Operations',
    difficulty: 'easy',
    title: 'Get All Hash Fields and Values',
    text: 'Get all fields and values from hash "product:100".',
    setup: 'Hash "product:100" has multiple fields',
    setupCode: 'HSET product:100 name Widget price 29.99 stock 50',
    expected: { name: 'Widget', price: '29.99', stock: '50' },
    sample: 'HGETALL product:100',
    hints: [
      'Use HGETALL to get all field-value pairs',
      'Returns alternating field names and values',
      'Use with caution on large hashes',
    ],
    validPatterns: [/HGETALL\s+product:100/i],
    tags: ['hash', 'hgetall', 'basic'],
  },
  {
    id: 'redis-hash-004',
    category: 'Hash Operations',
    difficulty: 'medium',
    title: 'Set Multiple Hash Fields',
    text: 'Set fields "city" to "NYC" and "country" to "USA" in hash "location".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'OK',
    sample: 'HSET location city NYC country USA',
    hints: [
      'HSET can set multiple field-value pairs',
      'Syntax: HSET key field1 value1 field2 value2 ...',
      'Alternative: HMSET (deprecated but still works)',
    ],
    validPatterns: [
      /HSET\s+location\s+city\s+["']?NYC["']?\s+country\s+["']?USA["']?/i,
      /HMSET\s+location\s+city\s+["']?NYC["']?\s+country\s+["']?USA["']?/i,
    ],
    tags: ['hash', 'hset', 'multiple'],
  },
  {
    id: 'redis-hash-005',
    category: 'Hash Operations',
    difficulty: 'medium',
    title: 'Get Multiple Hash Fields',
    text: 'Get fields "name" and "age" from hash "person:1".',
    setup: 'Hash "person:1" has multiple fields',
    setupCode: 'HSET person:1 name Alice age 30 city Boston',
    expected: ['Alice', '30'],
    sample: 'HMGET person:1 name age',
    hints: [
      'Use HMGET to get multiple field values',
      'Syntax: HMGET key field1 field2 ...',
      'Returns nil for non-existent fields',
    ],
    validPatterns: [/HMGET\s+person:1\s+name\s+age/i],
    tags: ['hash', 'hmget', 'multiple'],
  },
  {
    id: 'redis-hash-006',
    category: 'Hash Operations',
    difficulty: 'medium',
    title: 'Increment Hash Field',
    text: 'Increment the "views" field in hash "article:1" by 1.',
    setup: 'Hash "article:1" has views field set',
    setupCode: 'HSET article:1 views 100',
    expected: '101',
    sample: 'HINCRBY article:1 views 1',
    hints: [
      'Use HINCRBY for integer increment',
      'Syntax: HINCRBY key field increment',
      'Creates field with 0 if it does not exist',
    ],
    validPatterns: [/HINCRBY\s+article:1\s+views\s+1/i],
    tags: ['hash', 'hincrby', 'counter'],
  },
  {
    id: 'redis-hash-007',
    category: 'Hash Operations',
    difficulty: 'medium',
    title: 'Check Field Existence',
    text: 'Check if field "admin" exists in hash "user:1".',
    setup: 'Hash "user:1" may or may not have admin field',
    setupCode: 'HSET user:1 name John role member',
    expected: '0 or 1',
    sample: 'HEXISTS user:1 admin',
    hints: [
      'Use HEXISTS to check field existence',
      'Returns 1 if field exists, 0 otherwise',
      'Useful for conditional logic',
    ],
    validPatterns: [/HEXISTS\s+user:1\s+admin/i],
    tags: ['hash', 'hexists', 'check'],
  },
  {
    id: 'redis-hash-008',
    category: 'Hash Operations',
    difficulty: 'medium',
    title: 'Delete Hash Field',
    text: 'Delete the field "temp" from hash "config".',
    setup: 'Hash "config" has a temp field',
    setupCode: 'HSET config temp value permanent keep',
    expected: '1',
    sample: 'HDEL config temp',
    hints: [
      'Use HDEL to delete fields from a hash',
      'Syntax: HDEL key field1 field2 ...',
      'Returns number of fields removed',
    ],
    validPatterns: [/HDEL\s+config\s+temp/i],
    tags: ['hash', 'hdel', 'delete'],
  },
  {
    id: 'redis-hash-009',
    category: 'Hash Operations',
    difficulty: 'easy',
    title: 'Get All Hash Keys',
    text: 'Get all field names from hash "settings".',
    setup: 'Hash "settings" has multiple fields',
    setupCode: 'HSET settings theme dark lang en timeout 30',
    expected: ['theme', 'lang', 'timeout'],
    sample: 'HKEYS settings',
    hints: [
      'Use HKEYS to get all field names',
      'Returns an array of field names',
      'Complement: HVALS returns all values',
    ],
    validPatterns: [/HKEYS\s+settings/i],
    tags: ['hash', 'hkeys', 'fields'],
  },
  {
    id: 'redis-hash-010',
    category: 'Hash Operations',
    difficulty: 'easy',
    title: 'Get Hash Field Count',
    text: 'Get the number of fields in hash "metadata".',
    setup: 'Hash "metadata" has several fields',
    setupCode: 'HSET metadata created 2024 author admin version 1.0',
    expected: '3',
    sample: 'HLEN metadata',
    hints: ['Use HLEN to get the number of fields', 'Returns 0 for non-existent keys'],
    validPatterns: [/HLEN\s+metadata/i],
    tags: ['hash', 'hlen', 'length'],
  },

  // ============================================================
  // SET OPERATIONS (10 problems)
  // ============================================================
  {
    id: 'redis-set-001',
    category: 'Set Operations',
    difficulty: 'easy',
    title: 'Add to Set',
    text: 'Add "apple" to the set "fruits".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: '1',
    sample: 'SADD fruits apple',
    hints: [
      'Use SADD to add members to a set',
      'Returns number of new members added',
      'Duplicates are automatically ignored',
    ],
    validPatterns: [/SADD\s+fruits\s+["']?apple["']?/i],
    tags: ['set', 'sadd', 'basic'],
  },
  {
    id: 'redis-set-002',
    category: 'Set Operations',
    difficulty: 'easy',
    title: 'Get All Set Members',
    text: 'Get all members of the set "tags".',
    setup: 'Set "tags" contains several members',
    setupCode: 'SADD tags redis database nosql',
    expected: ['redis', 'database', 'nosql'],
    sample: 'SMEMBERS tags',
    hints: [
      'Use SMEMBERS to get all members',
      'Order is not guaranteed',
      'Use with caution on large sets',
    ],
    validPatterns: [/SMEMBERS\s+tags/i],
    tags: ['set', 'smembers', 'basic'],
  },
  {
    id: 'redis-set-003',
    category: 'Set Operations',
    difficulty: 'easy',
    title: 'Check Set Membership',
    text: 'Check if "bob" is a member of set "users".',
    setup: 'Set "users" contains some members',
    setupCode: 'SADD users alice bob charlie',
    expected: '1',
    sample: 'SISMEMBER users bob',
    hints: [
      'Use SISMEMBER to check membership',
      'Returns 1 if member exists, 0 otherwise',
      'O(1) operation',
    ],
    validPatterns: [/SISMEMBER\s+users\s+["']?bob["']?/i],
    tags: ['set', 'sismember', 'check'],
  },
  {
    id: 'redis-set-004',
    category: 'Set Operations',
    difficulty: 'easy',
    title: 'Get Set Cardinality',
    text: 'Get the number of members in set "visitors".',
    setup: 'Set "visitors" has several members',
    setupCode: 'SADD visitors user1 user2 user3 user4',
    expected: '4',
    sample: 'SCARD visitors',
    hints: [
      'Use SCARD to get the set size',
      'SCARD = Set CARDinality',
      'Returns 0 for non-existent keys',
    ],
    validPatterns: [/SCARD\s+visitors/i],
    tags: ['set', 'scard', 'cardinality'],
  },
  {
    id: 'redis-set-005',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Remove from Set',
    text: 'Remove "expired" from the set "tokens".',
    setup: 'Set "tokens" contains the member',
    setupCode: 'SADD tokens valid expired pending',
    expected: '1',
    sample: 'SREM tokens expired',
    hints: [
      'Use SREM to remove members',
      'Syntax: SREM key member1 member2 ...',
      'Returns number of members removed',
    ],
    validPatterns: [/SREM\s+tokens\s+["']?expired["']?/i],
    tags: ['set', 'srem', 'remove'],
  },
  {
    id: 'redis-set-006',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Set Union',
    text: 'Get the union of sets "set1" and "set2".',
    setup: 'Two sets with some overlapping members',
    setupCode: 'SADD set1 a b c\nSADD set2 b c d',
    expected: ['a', 'b', 'c', 'd'],
    sample: 'SUNION set1 set2',
    hints: [
      'Use SUNION to combine sets',
      'Returns all unique members from all sets',
      'Does not modify the original sets',
    ],
    validPatterns: [/SUNION\s+set1\s+set2/i],
    tags: ['set', 'sunion', 'union'],
  },
  {
    id: 'redis-set-007',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Set Intersection',
    text: 'Get the intersection of sets "groupA" and "groupB".',
    setup: 'Two sets with some common members',
    setupCode: 'SADD groupA alice bob charlie\nSADD groupB bob charlie dave',
    expected: ['bob', 'charlie'],
    sample: 'SINTER groupA groupB',
    hints: [
      'Use SINTER for intersection',
      'Returns members present in ALL sets',
      'Empty result if any set is empty',
    ],
    validPatterns: [/SINTER\s+groupA\s+groupB/i],
    tags: ['set', 'sinter', 'intersection'],
  },
  {
    id: 'redis-set-008',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Set Difference',
    text: 'Get members in "all_users" that are not in "banned_users".',
    setup: 'Two sets where one is a subset of activities',
    setupCode: 'SADD all_users alice bob charlie dave\nSADD banned_users bob',
    expected: ['alice', 'charlie', 'dave'],
    sample: 'SDIFF all_users banned_users',
    hints: [
      'Use SDIFF for difference',
      'Returns members in first set not in others',
      'Order matters: first set minus others',
    ],
    validPatterns: [/SDIFF\s+all_users\s+banned_users/i],
    tags: ['set', 'sdiff', 'difference'],
  },
  {
    id: 'redis-set-009',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Pop Random Member',
    text: 'Remove and return a random member from set "pool".',
    setup: 'Set "pool" has several members',
    setupCode: 'SADD pool item1 item2 item3 item4',
    expected: 'Random member',
    sample: 'SPOP pool',
    hints: [
      'Use SPOP to remove random member',
      'Useful for random selection',
      'Can specify count: SPOP pool 2',
    ],
    validPatterns: [/SPOP\s+pool/i],
    tags: ['set', 'spop', 'random'],
  },
  {
    id: 'redis-set-010',
    category: 'Set Operations',
    difficulty: 'easy',
    title: 'Get Random Member',
    text: 'Get a random member from set "prizes" without removing it.',
    setup: 'Set "prizes" has several members',
    setupCode: 'SADD prizes gold silver bronze',
    expected: 'Random member',
    sample: 'SRANDMEMBER prizes',
    hints: [
      'Use SRANDMEMBER for random without removal',
      'Can specify count for multiple random members',
      'Negative count allows duplicates',
    ],
    validPatterns: [/SRANDMEMBER\s+prizes/i],
    tags: ['set', 'srandmember', 'random'],
  },

  // ============================================================
  // SORTED SET OPERATIONS (10 problems)
  // ============================================================
  {
    id: 'redis-zset-001',
    category: 'Sorted Set Operations',
    difficulty: 'easy',
    title: 'Add to Sorted Set',
    text: 'Add member "player1" with score 100 to sorted set "leaderboard".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: '1',
    sample: 'ZADD leaderboard 100 player1',
    hints: [
      'Use ZADD to add scored members',
      'Syntax: ZADD key score member',
      'Score is the sorting value',
    ],
    validPatterns: [/ZADD\s+leaderboard\s+100\s+["']?player1["']?/i],
    tags: ['zset', 'zadd', 'basic'],
  },
  {
    id: 'redis-zset-002',
    category: 'Sorted Set Operations',
    difficulty: 'easy',
    title: 'Get Sorted Set Range',
    text: 'Get the top 3 members from sorted set "scores" (highest scores first).',
    setup: 'Sorted set with multiple members',
    setupCode: 'ZADD scores 100 alice 200 bob 150 charlie 300 dave',
    expected: ['dave', 'bob', 'charlie'],
    sample: 'ZRANGE scores 0 2 REV',
    hints: [
      'Use ZRANGE with REV for descending order',
      'Index 0 to 2 gives top 3',
      'Alternative: ZREVRANGE scores 0 2',
    ],
    validPatterns: [/ZRANGE\s+scores\s+0\s+2\s+REV/i, /ZREVRANGE\s+scores\s+0\s+2/i],
    tags: ['zset', 'zrange', 'range'],
  },
  {
    id: 'redis-zset-003',
    category: 'Sorted Set Operations',
    difficulty: 'easy',
    title: 'Get Member Score',
    text: 'Get the score of member "alice" in sorted set "points".',
    setup: 'Sorted set with alice as member',
    setupCode: 'ZADD points 75 alice 80 bob',
    expected: '75',
    sample: 'ZSCORE points alice',
    hints: [
      'Use ZSCORE to get a member score',
      'Syntax: ZSCORE key member',
      'Returns nil if member does not exist',
    ],
    validPatterns: [/ZSCORE\s+points\s+["']?alice["']?/i],
    tags: ['zset', 'zscore', 'score'],
  },
  {
    id: 'redis-zset-004',
    category: 'Sorted Set Operations',
    difficulty: 'medium',
    title: 'Get Member Rank',
    text: 'Get the rank of member "bob" in sorted set "rankings" (0-based, lowest score first).',
    setup: 'Sorted set with bob as member',
    setupCode: 'ZADD rankings 50 alice 75 bob 100 charlie',
    expected: '1',
    sample: 'ZRANK rankings bob',
    hints: [
      'Use ZRANK for ascending rank (lowest = 0)',
      'Use ZREVRANK for descending rank',
      'Returns nil if member not found',
    ],
    validPatterns: [/ZRANK\s+rankings\s+["']?bob["']?/i],
    tags: ['zset', 'zrank', 'rank'],
  },
  {
    id: 'redis-zset-005',
    category: 'Sorted Set Operations',
    difficulty: 'medium',
    title: 'Increment Score',
    text: 'Increment the score of "player1" by 25 in sorted set "game_scores".',
    setup: 'Sorted set with player1',
    setupCode: 'ZADD game_scores 100 player1',
    expected: '125',
    sample: 'ZINCRBY game_scores 25 player1',
    hints: [
      'Use ZINCRBY to increment a score',
      'Syntax: ZINCRBY key increment member',
      'Returns the new score',
    ],
    validPatterns: [/ZINCRBY\s+game_scores\s+25\s+["']?player1["']?/i],
    tags: ['zset', 'zincrby', 'increment'],
  },
  {
    id: 'redis-zset-006',
    category: 'Sorted Set Operations',
    difficulty: 'medium',
    title: 'Count Members in Score Range',
    text: 'Count members with scores between 50 and 100 (inclusive) in sorted set "exam_results".',
    setup: 'Sorted set with various scores',
    setupCode: 'ZADD exam_results 45 fail1 55 pass1 75 pass2 95 pass3 105 extra',
    expected: '3',
    sample: 'ZCOUNT exam_results 50 100',
    hints: [
      'Use ZCOUNT to count by score range',
      'Syntax: ZCOUNT key min max',
      'Inclusive by default',
    ],
    validPatterns: [/ZCOUNT\s+exam_results\s+50\s+100/i],
    tags: ['zset', 'zcount', 'range'],
  },
  {
    id: 'redis-zset-007',
    category: 'Sorted Set Operations',
    difficulty: 'medium',
    title: 'Get Members by Score Range',
    text: 'Get all members with scores from 0 to 100 in sorted set "prices".',
    setup: 'Sorted set with price data',
    setupCode: 'ZADD prices 25 cheap 75 medium 150 expensive',
    expected: ['cheap', 'medium'],
    sample: 'ZRANGEBYSCORE prices 0 100',
    hints: [
      'Use ZRANGEBYSCORE for score-based range',
      'Syntax: ZRANGEBYSCORE key min max',
      'Use -inf and +inf for unbounded',
    ],
    validPatterns: [/ZRANGEBYSCORE\s+prices\s+0\s+100/i, /ZRANGE\s+prices\s+0\s+100\s+BYSCORE/i],
    tags: ['zset', 'zrangebyscore', 'range'],
  },
  {
    id: 'redis-zset-008',
    category: 'Sorted Set Operations',
    difficulty: 'medium',
    title: 'Remove Member from Sorted Set',
    text: 'Remove "inactive" from sorted set "active_users".',
    setup: 'Sorted set with the member',
    setupCode: 'ZADD active_users 1 alice 2 bob 3 inactive',
    expected: '1',
    sample: 'ZREM active_users inactive',
    hints: [
      'Use ZREM to remove members',
      'Syntax: ZREM key member1 member2 ...',
      'Returns number of members removed',
    ],
    validPatterns: [/ZREM\s+active_users\s+["']?inactive["']?/i],
    tags: ['zset', 'zrem', 'remove'],
  },
  {
    id: 'redis-zset-009',
    category: 'Sorted Set Operations',
    difficulty: 'easy',
    title: 'Get Sorted Set Cardinality',
    text: 'Get the number of members in sorted set "inventory".',
    setup: 'Sorted set with several members',
    setupCode: 'ZADD inventory 10 item1 20 item2 30 item3',
    expected: '3',
    sample: 'ZCARD inventory',
    hints: [
      'Use ZCARD to get sorted set size',
      'Like SCARD for sets',
      'Returns 0 for non-existent keys',
    ],
    validPatterns: [/ZCARD\s+inventory/i],
    tags: ['zset', 'zcard', 'cardinality'],
  },
  {
    id: 'redis-zset-010',
    category: 'Sorted Set Operations',
    difficulty: 'hard',
    title: 'Get Range with Scores',
    text: 'Get the top 3 members WITH their scores from sorted set "highscores" (highest first).',
    setup: 'Sorted set with scores',
    setupCode: 'ZADD highscores 1000 pro 500 amateur 750 intermediate 250 beginner',
    expected: [
      ['pro', '1000'],
      ['intermediate', '750'],
      ['amateur', '500'],
    ],
    sample: 'ZRANGE highscores 0 2 REV WITHSCORES',
    hints: [
      'Add WITHSCORES to include scores',
      'Returns alternating member, score pairs',
      'Useful for leaderboards',
    ],
    validPatterns: [
      /ZRANGE\s+highscores\s+0\s+2\s+REV\s+WITHSCORES/i,
      /ZREVRANGE\s+highscores\s+0\s+2\s+WITHSCORES/i,
    ],
    tags: ['zset', 'zrange', 'withscores'],
  },

  // ============================================================
  // KEY MANAGEMENT (8 problems)
  // ============================================================
  {
    id: 'redis-key-001',
    category: 'Key Management',
    difficulty: 'easy',
    title: 'Delete a Key',
    text: 'Delete the key "temp".',
    setup: 'Key "temp" exists',
    setupCode: 'SET temp value',
    expected: '1',
    sample: 'DEL temp',
    hints: [
      'Use DEL to delete keys',
      'Can delete multiple keys at once',
      'Returns number of keys deleted',
    ],
    validPatterns: [/DEL\s+temp/i],
    tags: ['key', 'del', 'delete'],
  },
  {
    id: 'redis-key-002',
    category: 'Key Management',
    difficulty: 'easy',
    title: 'Check Key Existence',
    text: 'Check if key "config" exists.',
    setup: 'Key may or may not exist',
    setupCode: 'SET config value',
    expected: '1',
    sample: 'EXISTS config',
    hints: [
      'Use EXISTS to check existence',
      'Returns 1 if exists, 0 otherwise',
      'Can check multiple keys at once',
    ],
    validPatterns: [/EXISTS\s+config/i],
    tags: ['key', 'exists', 'check'],
  },
  {
    id: 'redis-key-003',
    category: 'Key Management',
    difficulty: 'easy',
    title: 'Set Key Expiration',
    text: 'Set key "session" to expire in 3600 seconds.',
    setup: 'Key "session" exists',
    setupCode: 'SET session data',
    expected: '1',
    sample: 'EXPIRE session 3600',
    hints: [
      'Use EXPIRE to set TTL in seconds',
      'Returns 1 if timeout was set',
      'Returns 0 if key does not exist',
    ],
    validPatterns: [/EXPIRE\s+session\s+3600/i],
    tags: ['key', 'expire', 'ttl'],
  },
  {
    id: 'redis-key-004',
    category: 'Key Management',
    difficulty: 'easy',
    title: 'Get Time-to-Live',
    text: 'Get the remaining TTL of key "cache" in seconds.',
    setup: 'Key "cache" has an expiration set',
    setupCode: 'SET cache data EX 300',
    expected: 'Seconds remaining',
    sample: 'TTL cache',
    hints: [
      'Use TTL to get remaining time',
      'Returns -1 if no expiration',
      'Returns -2 if key does not exist',
    ],
    validPatterns: [/TTL\s+cache/i],
    tags: ['key', 'ttl', 'expiration'],
  },
  {
    id: 'redis-key-005',
    category: 'Key Management',
    difficulty: 'medium',
    title: 'Rename a Key',
    text: 'Rename key "old_name" to "new_name".',
    setup: 'Key "old_name" exists',
    setupCode: 'SET old_name value',
    expected: 'OK',
    sample: 'RENAME old_name new_name',
    hints: [
      'Use RENAME to change key name',
      'Overwrites "new_name" if it exists',
      'Use RENAMENX to avoid overwriting',
    ],
    validPatterns: [/RENAME\s+old_name\s+new_name/i],
    tags: ['key', 'rename'],
  },
  {
    id: 'redis-key-006',
    category: 'Key Management',
    difficulty: 'medium',
    title: 'Get Key Type',
    text: 'Get the data type of key "mykey".',
    setup: 'Key "mykey" contains a list',
    setupCode: 'RPUSH mykey a b c',
    expected: 'list',
    sample: 'TYPE mykey',
    hints: [
      'Use TYPE to get data type',
      'Returns: string, list, set, zset, hash, stream',
      'Returns "none" if key does not exist',
    ],
    validPatterns: [/TYPE\s+mykey/i],
    tags: ['key', 'type'],
  },
  {
    id: 'redis-key-007',
    category: 'Key Management',
    difficulty: 'medium',
    title: 'Find Keys by Pattern',
    text: 'Find all keys matching pattern "user:*".',
    setup: 'Several user keys exist',
    setupCode: 'SET user:1 a\nSET user:2 b\nSET product:1 c',
    expected: ['user:1', 'user:2'],
    sample: 'KEYS user:*',
    hints: [
      'Use KEYS for pattern matching',
      '* matches any characters',
      'Warning: KEYS can block in production',
    ],
    validPatterns: [/KEYS\s+user:\*/i],
    tags: ['key', 'keys', 'pattern'],
  },
  {
    id: 'redis-key-008',
    category: 'Key Management',
    difficulty: 'medium',
    title: 'Remove Expiration',
    text: 'Remove the expiration from key "persistent".',
    setup: 'Key has an expiration set',
    setupCode: 'SET persistent value EX 60',
    expected: '1',
    sample: 'PERSIST persistent',
    hints: [
      'Use PERSIST to remove TTL',
      'Makes key permanent again',
      'Returns 1 if expiration was removed',
    ],
    validPatterns: [/PERSIST\s+persistent/i],
    tags: ['key', 'persist', 'ttl'],
  },

  // ============================================================
  // TRANSACTIONS (5 problems)
  // ============================================================
  {
    id: 'redis-tx-001',
    category: 'Transactions',
    difficulty: 'medium',
    title: 'Start Transaction',
    text: 'Start a transaction block.',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'OK',
    sample: 'MULTI',
    hints: [
      'Use MULTI to start a transaction',
      'Commands are queued until EXEC',
      'Use DISCARD to abort',
    ],
    validPatterns: [/MULTI/i],
    tags: ['transaction', 'multi', 'basic'],
  },
  {
    id: 'redis-tx-002',
    category: 'Transactions',
    difficulty: 'medium',
    title: 'Execute Transaction',
    text: 'Execute all queued commands in a transaction.',
    setup: 'Transaction started with MULTI',
    setupCode: 'MULTI\nSET key1 value1\nSET key2 value2',
    expected: 'Array of results',
    sample: 'EXEC',
    hints: [
      'Use EXEC to execute queued commands',
      'Returns array of results',
      'Returns nil if WATCH failed',
    ],
    validPatterns: [/EXEC/i],
    tags: ['transaction', 'exec'],
  },
  {
    id: 'redis-tx-003',
    category: 'Transactions',
    difficulty: 'medium',
    title: 'Discard Transaction',
    text: 'Abort the current transaction and discard queued commands.',
    setup: 'Transaction started with MULTI',
    setupCode: 'MULTI\nSET key1 value1',
    expected: 'OK',
    sample: 'DISCARD',
    hints: [
      'Use DISCARD to abort transaction',
      'All queued commands are discarded',
      'Returns to normal command mode',
    ],
    validPatterns: [/DISCARD/i],
    tags: ['transaction', 'discard'],
  },
  {
    id: 'redis-tx-004',
    category: 'Transactions',
    difficulty: 'hard',
    title: 'Watch Key for CAS',
    text: 'Watch key "balance" for changes before starting a transaction.',
    setup: 'Key "balance" exists',
    setupCode: 'SET balance 100',
    expected: 'OK',
    sample: 'WATCH balance',
    hints: [
      'Use WATCH for optimistic locking',
      'Transaction aborts if watched key changes',
      'Implement Compare-And-Set (CAS)',
    ],
    validPatterns: [/WATCH\s+balance/i],
    tags: ['transaction', 'watch', 'cas'],
  },
  {
    id: 'redis-tx-005',
    category: 'Transactions',
    difficulty: 'hard',
    title: 'Unwatch Keys',
    text: 'Stop watching all keys.',
    setup: 'Keys being watched',
    setupCode: 'WATCH key1 key2',
    expected: 'OK',
    sample: 'UNWATCH',
    hints: [
      'Use UNWATCH to stop watching all keys',
      'Called automatically after EXEC',
      'Useful when aborting before MULTI',
    ],
    validPatterns: [/UNWATCH/i],
    tags: ['transaction', 'unwatch'],
  },

  // ============================================================
  // PUB/SUB (5 problems)
  // ============================================================
  {
    id: 'redis-pubsub-001',
    category: 'Pub/Sub',
    difficulty: 'medium',
    title: 'Subscribe to Channel',
    text: 'Subscribe to the channel "notifications".',
    setup: 'Empty Redis instance',
    setupCode: 'FLUSHALL',
    expected: 'Subscription confirmation',
    sample: 'SUBSCRIBE notifications',
    hints: [
      'Use SUBSCRIBE to listen to channels',
      'Client enters subscription mode',
      'Use UNSUBSCRIBE to exit',
    ],
    validPatterns: [/SUBSCRIBE\s+notifications/i],
    tags: ['pubsub', 'subscribe'],
  },
  {
    id: 'redis-pubsub-002',
    category: 'Pub/Sub',
    difficulty: 'medium',
    title: 'Publish Message',
    text: 'Publish message "Hello World" to channel "chat".',
    setup: 'Channel may have subscribers',
    setupCode: '',
    expected: 'Number of subscribers that received the message',
    sample: 'PUBLISH chat "Hello World"',
    hints: [
      'Use PUBLISH to send messages',
      'Syntax: PUBLISH channel message',
      'Returns number of receivers',
    ],
    validPatterns: [/PUBLISH\s+chat\s+["']?Hello\s*World["']?/i],
    tags: ['pubsub', 'publish'],
  },
  {
    id: 'redis-pubsub-003',
    category: 'Pub/Sub',
    difficulty: 'medium',
    title: 'Pattern Subscribe',
    text: 'Subscribe to all channels matching pattern "news:*".',
    setup: 'Multiple news channels exist',
    setupCode: '',
    expected: 'Pattern subscription confirmation',
    sample: 'PSUBSCRIBE news:*',
    hints: [
      'Use PSUBSCRIBE for pattern matching',
      '* matches any characters',
      'Receives from all matching channels',
    ],
    validPatterns: [/PSUBSCRIBE\s+news:\*/i],
    tags: ['pubsub', 'psubscribe', 'pattern'],
  },
  {
    id: 'redis-pubsub-004',
    category: 'Pub/Sub',
    difficulty: 'easy',
    title: 'Unsubscribe from Channel',
    text: 'Unsubscribe from channel "updates".',
    setup: 'Subscribed to updates channel',
    setupCode: 'SUBSCRIBE updates',
    expected: 'Unsubscription confirmation',
    sample: 'UNSUBSCRIBE updates',
    hints: [
      'Use UNSUBSCRIBE to stop listening',
      'No argument unsubscribes from all',
      'Can specify multiple channels',
    ],
    validPatterns: [/UNSUBSCRIBE\s+updates/i],
    tags: ['pubsub', 'unsubscribe'],
  },
  {
    id: 'redis-pubsub-005',
    category: 'Pub/Sub',
    difficulty: 'medium',
    title: 'List Active Channels',
    text: 'List all active channels with at least one subscriber.',
    setup: 'Some channels have subscribers',
    setupCode: '',
    expected: 'Array of active channels',
    sample: 'PUBSUB CHANNELS',
    hints: [
      'Use PUBSUB CHANNELS to list active channels',
      'Can add pattern: PUBSUB CHANNELS news:*',
      'Only shows channels with subscribers',
    ],
    validPatterns: [/PUBSUB\s+CHANNELS/i],
    tags: ['pubsub', 'channels'],
  },
];

// ── Helper functions for Redis problems ────────────────────────

export function getRedisProblemsById(id: string) {
  return redisProblems.find((p) => p.id === id);
}

export function getRedisProblemsByCategory(category: string) {
  return redisProblems.filter((p) => p.category === category);
}

export function getRedisProblemsByDifficulty(difficulty: 'easy' | 'medium' | 'hard') {
  return redisProblems.filter((p) => p.difficulty === difficulty);
}

export function getRedisProblemsByTag(tag: string) {
  return redisProblems.filter((p) => p.tags?.includes(tag));
}

export function getRedisCategories(): string[] {
  return [...new Set(redisProblems.map((p) => p.category))];
}
