/**
 * Ruby coding drill problems
 * Covers Array, String, Hash, and Enumerable methods
 */

import type { Problem } from '../types';

export const rubyProblems: Problem[] = [
  // ============================================================
  // Array Methods
  // ============================================================

  // map / collect
  {
    id: 'ruby-array-map-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Double Array Elements with map',
    text: 'Use the `map` method to double each number in the array.',
    setup: 'numbers = [1, 2, 3, 4, 5]',
    setupCode: 'numbers = [1, 2, 3, 4, 5]',
    expected: [2, 4, 6, 8, 10],
    sample: 'numbers.map { |n| n * 2 }',
    hints: ['map transforms each element', 'Use a block with |n|'],
    validPatterns: [
      /numbers\.map\s*\{\s*\|(\w+)\|\s*\1\s*\*\s*2\s*\}/,
      /numbers\.map\s*\(\s*&:.*\)/,
      /numbers\.collect\s*\{\s*\|(\w+)\|\s*\1\s*\*\s*2\s*\}/,
    ],
    tags: ['map', 'collect', 'transform'],
  },
  {
    id: 'ruby-array-collect-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Convert to Strings with collect',
    text: 'Use the `collect` method to convert each number to a string.',
    setup: 'numbers = [1, 2, 3]',
    setupCode: 'numbers = [1, 2, 3]',
    expected: ['1', '2', '3'],
    sample: 'numbers.collect(&:to_s)',
    hints: ['collect is an alias for map', 'Use &:to_s for method shorthand'],
    validPatterns: [
      /numbers\.collect\s*\(\s*&:to_s\s*\)/,
      /numbers\.collect\s*\{\s*\|(\w+)\|\s*\1\.to_s\s*\}/,
      /numbers\.map\s*\(\s*&:to_s\s*\)/,
      /numbers\.map\s*\{\s*\|(\w+)\|\s*\1\.to_s\s*\}/,
    ],
    tags: ['collect', 'map', 'to_s'],
  },

  // select / reject / filter
  {
    id: 'ruby-array-select-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Select Even Numbers',
    text: 'Use the `select` method to filter only even numbers from the array.',
    setup: 'numbers = [1, 2, 3, 4, 5, 6]',
    setupCode: 'numbers = [1, 2, 3, 4, 5, 6]',
    expected: [2, 4, 6],
    sample: 'numbers.select { |n| n.even? }',
    hints: ['select returns elements where block is true', 'Use .even? method'],
    validPatterns: [
      /numbers\.select\s*\{\s*\|(\w+)\|\s*\1\.even\?\s*\}/,
      /numbers\.select\s*\{\s*\|(\w+)\|\s*\1\s*%\s*2\s*==\s*0\s*\}/,
      /numbers\.select\s*\(\s*&:even\?\s*\)/,
      /numbers\.filter\s*\{\s*\|(\w+)\|\s*\1\.even\?\s*\}/,
    ],
    tags: ['select', 'filter', 'even'],
  },
  {
    id: 'ruby-array-reject-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Reject Negative Numbers',
    text: 'Use the `reject` method to remove all negative numbers from the array.',
    setup: 'numbers = [-3, -1, 0, 2, 5]',
    setupCode: 'numbers = [-3, -1, 0, 2, 5]',
    expected: [0, 2, 5],
    sample: 'numbers.reject { |n| n < 0 }',
    hints: ['reject removes elements where block is true', 'Check if n < 0'],
    validPatterns: [
      /numbers\.reject\s*\{\s*\|(\w+)\|\s*\1\s*<\s*0\s*\}/,
      /numbers\.reject\s*\{\s*\|(\w+)\|\s*\1\.negative\?\s*\}/,
      /numbers\.reject\s*\(\s*&:negative\?\s*\)/,
    ],
    tags: ['reject', 'filter', 'negative'],
  },
  {
    id: 'ruby-array-filter-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Filter Long Words',
    text: 'Use the `filter` method to keep only words longer than 4 characters.',
    setup: 'words = ["hi", "hello", "world", "ok", "ruby"]',
    setupCode: 'words = ["hi", "hello", "world", "ok", "ruby"]',
    expected: ['hello', 'world'],
    sample: 'words.filter { |w| w.length > 4 }',
    hints: ['filter is an alias for select', 'Check w.length > 4'],
    validPatterns: [
      /words\.filter\s*\{\s*\|(\w+)\|\s*\1\.length\s*>\s*4\s*\}/,
      /words\.filter\s*\{\s*\|(\w+)\|\s*\1\.size\s*>\s*4\s*\}/,
      /words\.select\s*\{\s*\|(\w+)\|\s*\1\.length\s*>\s*4\s*\}/,
    ],
    tags: ['filter', 'select', 'length'],
  },

  // reduce / inject
  {
    id: 'ruby-array-reduce-1',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Sum Array with reduce',
    text: 'Use the `reduce` method to calculate the sum of all numbers.',
    setup: 'numbers = [1, 2, 3, 4, 5]',
    setupCode: 'numbers = [1, 2, 3, 4, 5]',
    expected: 15,
    sample: 'numbers.reduce(0) { |sum, n| sum + n }',
    hints: [
      'reduce accumulates a value',
      'Start with 0 as initial value',
      'Can also use numbers.reduce(:+) shorthand',
    ],
    validPatterns: [
      /numbers\.reduce\s*\(\s*0\s*\)\s*\{\s*\|(\w+),\s*(\w+)\|\s*\1\s*\+\s*\2\s*\}/,
      /numbers\.reduce\s*\(\s*:\+\s*\)/,
      /numbers\.reduce\s*\{\s*\|(\w+),\s*(\w+)\|\s*\1\s*\+\s*\2\s*\}/,
      /numbers\.inject\s*\(\s*0\s*\)\s*\{\s*\|(\w+),\s*(\w+)\|\s*\1\s*\+\s*\2\s*\}/,
      /numbers\.inject\s*\(\s*:\+\s*\)/,
      /numbers\.sum\b/,
    ],
    tags: ['reduce', 'inject', 'sum'],
  },
  {
    id: 'ruby-array-inject-1',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Product with inject',
    text: 'Use the `inject` method to calculate the product of all numbers.',
    setup: 'numbers = [1, 2, 3, 4]',
    setupCode: 'numbers = [1, 2, 3, 4]',
    expected: 24,
    sample: 'numbers.inject(1) { |product, n| product * n }',
    hints: [
      'inject is an alias for reduce',
      'Start with 1 for multiplication',
      'Can also use numbers.inject(:*) shorthand',
    ],
    validPatterns: [
      /numbers\.inject\s*\(\s*1\s*\)\s*\{\s*\|(\w+),\s*(\w+)\|\s*\1\s*\*\s*\2\s*\}/,
      /numbers\.inject\s*\(\s*:\*\s*\)/,
      /numbers\.inject\s*\{\s*\|(\w+),\s*(\w+)\|\s*\1\s*\*\s*\2\s*\}/,
      /numbers\.reduce\s*\(\s*1\s*\)\s*\{\s*\|(\w+),\s*(\w+)\|\s*\1\s*\*\s*\2\s*\}/,
      /numbers\.reduce\s*\(\s*:\*\s*\)/,
    ],
    tags: ['inject', 'reduce', 'product'],
  },

  // find / detect
  {
    id: 'ruby-array-find-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Find First Even Number',
    text: 'Use the `find` method to get the first even number in the array.',
    setup: 'numbers = [1, 3, 4, 6, 7]',
    setupCode: 'numbers = [1, 3, 4, 6, 7]',
    expected: 4,
    sample: 'numbers.find { |n| n.even? }',
    hints: ['find returns the first matching element', 'Use .even? method'],
    validPatterns: [
      /numbers\.find\s*\{\s*\|(\w+)\|\s*\1\.even\?\s*\}/,
      /numbers\.find\s*\{\s*\|(\w+)\|\s*\1\s*%\s*2\s*==\s*0\s*\}/,
      /numbers\.find\s*\(\s*&:even\?\s*\)/,
      /numbers\.detect\s*\{\s*\|(\w+)\|\s*\1\.even\?\s*\}/,
    ],
    tags: ['find', 'detect', 'first'],
  },
  {
    id: 'ruby-array-detect-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Detect String Starting with A',
    text: 'Use the `detect` method to find the first word starting with "a".',
    setup: 'words = ["hello", "apple", "world", "ant"]',
    setupCode: 'words = ["hello", "apple", "world", "ant"]',
    expected: 'apple',
    sample: 'words.detect { |w| w.start_with?("a") }',
    hints: ['detect is an alias for find', 'Use start_with? method'],
    validPatterns: [
      /words\.detect\s*\{\s*\|(\w+)\|\s*\1\.start_with\?\s*\(\s*["']a["']\s*\)\s*\}/,
      /words\.detect\s*\{\s*\|(\w+)\|\s*\1\[0\]\s*==\s*["']a["']\s*\}/,
      /words\.find\s*\{\s*\|(\w+)\|\s*\1\.start_with\?\s*\(\s*["']a["']\s*\)\s*\}/,
    ],
    tags: ['detect', 'find', 'start_with'],
  },

  // sort / sort_by
  {
    id: 'ruby-array-sort-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Sort Numbers Ascending',
    text: 'Use the `sort` method to sort the numbers in ascending order.',
    setup: 'numbers = [5, 2, 8, 1, 9]',
    setupCode: 'numbers = [5, 2, 8, 1, 9]',
    expected: [1, 2, 5, 8, 9],
    sample: 'numbers.sort',
    hints: ['sort returns a sorted array', 'Default is ascending order'],
    validPatterns: [/numbers\.sort\b/],
    tags: ['sort', 'ascending'],
  },
  {
    id: 'ruby-array-sort-2',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Sort Numbers Descending',
    text: 'Use the `sort` method with a block to sort numbers in descending order.',
    setup: 'numbers = [5, 2, 8, 1, 9]',
    setupCode: 'numbers = [5, 2, 8, 1, 9]',
    expected: [9, 8, 5, 2, 1],
    sample: 'numbers.sort { |a, b| b <=> a }',
    hints: ['Use spaceship operator <=>', 'Reverse the comparison for descending'],
    validPatterns: [
      /numbers\.sort\s*\{\s*\|(\w+),\s*(\w+)\|\s*\2\s*<=>\s*\1\s*\}/,
      /numbers\.sort\.reverse/,
      /numbers\.sort\s*\{\s*\|(\w+),\s*(\w+)\|\s*-?\s*\(\s*\1\s*<=>\s*\2\s*\)\s*\}/,
    ],
    tags: ['sort', 'descending', 'spaceship'],
  },
  {
    id: 'ruby-array-sort-by-1',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Sort by String Length',
    text: 'Use the `sort_by` method to sort words by their length.',
    setup: 'words = ["ruby", "is", "awesome"]',
    setupCode: 'words = ["ruby", "is", "awesome"]',
    expected: ['is', 'ruby', 'awesome'],
    sample: 'words.sort_by { |w| w.length }',
    hints: ['sort_by uses block value for comparison', 'Use length or size'],
    validPatterns: [
      /words\.sort_by\s*\{\s*\|(\w+)\|\s*\1\.length\s*\}/,
      /words\.sort_by\s*\{\s*\|(\w+)\|\s*\1\.size\s*\}/,
      /words\.sort_by\s*\(\s*&:length\s*\)/,
      /words\.sort_by\s*\(\s*&:size\s*\)/,
    ],
    tags: ['sort_by', 'length'],
  },

  // each / each_with_index
  {
    id: 'ruby-array-each-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Iterate with each',
    text: 'Use `each` to iterate and return the original array (side effects only).',
    setup: 'numbers = [1, 2, 3]',
    setupCode: 'numbers = [1, 2, 3]',
    expected: [1, 2, 3],
    sample: 'numbers.each { |n| puts n }',
    hints: ['each returns the original array', 'Block is for side effects'],
    validPatterns: [/numbers\.each\s*\{\s*\|(\w+)\|/, /numbers\.each\s+do\s*\|(\w+)\|/],
    tags: ['each', 'iteration'],
  },
  {
    id: 'ruby-array-each-with-index-1',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Iterate with Index',
    text: 'Use `each_with_index` to create an array of [element, index] pairs.',
    setup: 'letters = ["a", "b", "c"]',
    setupCode: 'letters = ["a", "b", "c"]',
    expected: [
      ['a', 0],
      ['b', 1],
      ['c', 2],
    ],
    sample: 'letters.each_with_index.map { |letter, index| [letter, index] }',
    hints: ['each_with_index gives element and index', 'Combine with map'],
    validPatterns: [
      /letters\.each_with_index\.map\s*\{\s*\|(\w+),\s*(\w+)\|\s*\[\s*\1,\s*\2\s*\]\s*\}/,
      /letters\.map\.with_index\s*\{\s*\|(\w+),\s*(\w+)\|\s*\[\s*\1,\s*\2\s*\]\s*\}/,
    ],
    tags: ['each_with_index', 'map', 'index'],
  },

  // first / last / take / drop
  {
    id: 'ruby-array-first-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Get First Element',
    text: 'Use the `first` method to get the first element of the array.',
    setup: 'numbers = [10, 20, 30, 40]',
    setupCode: 'numbers = [10, 20, 30, 40]',
    expected: 10,
    sample: 'numbers.first',
    hints: ['first returns the first element'],
    validPatterns: [/numbers\.first\b/, /numbers\[0\]/],
    tags: ['first', 'access'],
  },
  {
    id: 'ruby-array-last-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Get Last Element',
    text: 'Use the `last` method to get the last element of the array.',
    setup: 'numbers = [10, 20, 30, 40]',
    setupCode: 'numbers = [10, 20, 30, 40]',
    expected: 40,
    sample: 'numbers.last',
    hints: ['last returns the last element'],
    validPatterns: [/numbers\.last\b/, /numbers\[-1\]/],
    tags: ['last', 'access'],
  },
  {
    id: 'ruby-array-take-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Take First N Elements',
    text: 'Use the `take` method to get the first 3 elements.',
    setup: 'numbers = [1, 2, 3, 4, 5]',
    setupCode: 'numbers = [1, 2, 3, 4, 5]',
    expected: [1, 2, 3],
    sample: 'numbers.take(3)',
    hints: ['take(n) returns first n elements'],
    validPatterns: [
      /numbers\.take\s*\(\s*3\s*\)/,
      /numbers\.first\s*\(\s*3\s*\)/,
      /numbers\[0,\s*3\]/,
      /numbers\[0\.\.2\]/,
    ],
    tags: ['take', 'slice'],
  },
  {
    id: 'ruby-array-drop-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Drop First N Elements',
    text: 'Use the `drop` method to skip the first 2 elements.',
    setup: 'numbers = [1, 2, 3, 4, 5]',
    setupCode: 'numbers = [1, 2, 3, 4, 5]',
    expected: [3, 4, 5],
    sample: 'numbers.drop(2)',
    hints: ['drop(n) skips first n elements'],
    validPatterns: [/numbers\.drop\s*\(\s*2\s*\)/, /numbers\[2\.\.-1\]/, /numbers\[2\.\.4\]/],
    tags: ['drop', 'slice'],
  },

  // flatten / compact
  {
    id: 'ruby-array-flatten-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Flatten Nested Array',
    text: 'Use the `flatten` method to convert a nested array to a flat array.',
    setup: 'nested = [[1, 2], [3, [4, 5]]]',
    setupCode: 'nested = [[1, 2], [3, [4, 5]]]',
    expected: [1, 2, 3, 4, 5],
    sample: 'nested.flatten',
    hints: ['flatten removes all nesting levels'],
    validPatterns: [/nested\.flatten\b/],
    tags: ['flatten', 'nested'],
  },
  {
    id: 'ruby-array-compact-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Remove Nil Values',
    text: 'Use the `compact` method to remove all nil values from the array.',
    setup: 'values = [1, nil, 2, nil, 3]',
    setupCode: 'values = [1, nil, 2, nil, 3]',
    expected: [1, 2, 3],
    sample: 'values.compact',
    hints: ['compact removes nil values'],
    validPatterns: [/values\.compact\b/],
    tags: ['compact', 'nil'],
  },

  // uniq
  {
    id: 'ruby-array-uniq-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Remove Duplicates',
    text: 'Use the `uniq` method to remove duplicate values.',
    setup: 'numbers = [1, 2, 2, 3, 3, 3, 4]',
    setupCode: 'numbers = [1, 2, 2, 3, 3, 3, 4]',
    expected: [1, 2, 3, 4],
    sample: 'numbers.uniq',
    hints: ['uniq removes duplicates preserving order'],
    validPatterns: [/numbers\.uniq\b/],
    tags: ['uniq', 'duplicates'],
  },

  // join
  {
    id: 'ruby-array-join-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Join Array Elements',
    text: 'Use the `join` method to combine array elements with a comma separator.',
    setup: 'words = ["hello", "world", "ruby"]',
    setupCode: 'words = ["hello", "world", "ruby"]',
    expected: 'hello, world, ruby',
    sample: 'words.join(", ")',
    hints: ['join combines elements with separator'],
    validPatterns: [/words\.join\s*\(\s*["'],\s*["']\s*\)/],
    tags: ['join', 'string'],
  },

  // push / pop / shift / unshift
  {
    id: 'ruby-array-push-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Add to End with push',
    text: 'Use the `push` method to add 4 to the end of the array.',
    setup: 'numbers = [1, 2, 3]',
    setupCode: 'numbers = [1, 2, 3]',
    expected: [1, 2, 3, 4],
    sample: 'numbers.push(4)',
    hints: ['push adds element to the end', 'Can also use <<'],
    validPatterns: [/numbers\.push\s*\(\s*4\s*\)/, /numbers\s*<<\s*4/],
    tags: ['push', 'append'],
  },
  {
    id: 'ruby-array-pop-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Remove from End with pop',
    text: 'Use the `pop` method to remove and return the last element.',
    setup: 'numbers = [1, 2, 3, 4]',
    setupCode: 'numbers = [1, 2, 3, 4]',
    expected: 4,
    sample: 'numbers.pop',
    hints: ['pop removes and returns the last element'],
    validPatterns: [/numbers\.pop\b/],
    tags: ['pop', 'remove'],
  },
  {
    id: 'ruby-array-shift-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Remove from Start with shift',
    text: 'Use the `shift` method to remove and return the first element.',
    setup: 'numbers = [1, 2, 3, 4]',
    setupCode: 'numbers = [1, 2, 3, 4]',
    expected: 1,
    sample: 'numbers.shift',
    hints: ['shift removes and returns the first element'],
    validPatterns: [/numbers\.shift\b/],
    tags: ['shift', 'remove'],
  },
  {
    id: 'ruby-array-unshift-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Add to Start with unshift',
    text: 'Use the `unshift` method to add 0 to the beginning of the array.',
    setup: 'numbers = [1, 2, 3]',
    setupCode: 'numbers = [1, 2, 3]',
    expected: [0, 1, 2, 3],
    sample: 'numbers.unshift(0)',
    hints: ['unshift adds element to the beginning', 'Can also use prepend'],
    validPatterns: [/numbers\.unshift\s*\(\s*0\s*\)/, /numbers\.prepend\s*\(\s*0\s*\)/],
    tags: ['unshift', 'prepend'],
  },

  // include?
  {
    id: 'ruby-array-include-1',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Check Element Inclusion',
    text: 'Use the `include?` method to check if 3 is in the array.',
    setup: 'numbers = [1, 2, 3, 4, 5]',
    setupCode: 'numbers = [1, 2, 3, 4, 5]',
    expected: true,
    sample: 'numbers.include?(3)',
    hints: ['include? returns true or false'],
    validPatterns: [/numbers\.include\?\s*\(\s*3\s*\)/],
    tags: ['include?', 'membership'],
  },

  // ============================================================
  // String Methods
  // ============================================================

  // split / join
  {
    id: 'ruby-string-split-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Split String by Space',
    text: 'Use the `split` method to break the string into words.',
    setup: 'sentence = "hello world ruby"',
    setupCode: 'sentence = "hello world ruby"',
    expected: ['hello', 'world', 'ruby'],
    sample: 'sentence.split(" ")',
    hints: ['split breaks string at delimiter', 'split with no argument splits on whitespace'],
    validPatterns: [
      /sentence\.split\s*\(\s*["'] ["']\s*\)/,
      /sentence\.split\s*\(\s*\/\s+\/\s*\)/,
      /sentence\.split\b/,
    ],
    tags: ['split', 'words'],
  },
  {
    id: 'ruby-string-join-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Join Words with Dash',
    text: 'Join the array of words with a dash separator.',
    setup: 'words = ["hello", "world"]',
    setupCode: 'words = ["hello", "world"]',
    expected: 'hello-world',
    sample: 'words.join("-")',
    hints: ['join combines with separator'],
    validPatterns: [/words\.join\s*\(\s*["']-["']\s*\)/],
    tags: ['join', 'concatenate'],
  },

  // upcase / downcase / capitalize
  {
    id: 'ruby-string-upcase-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Convert to Uppercase',
    text: 'Use the `upcase` method to convert the string to uppercase.',
    setup: 'text = "hello"',
    setupCode: 'text = "hello"',
    expected: 'HELLO',
    sample: 'text.upcase',
    hints: ['upcase converts all characters to uppercase'],
    validPatterns: [/text\.upcase\b/],
    tags: ['upcase', 'uppercase'],
  },
  {
    id: 'ruby-string-downcase-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Convert to Lowercase',
    text: 'Use the `downcase` method to convert the string to lowercase.',
    setup: 'text = "HELLO"',
    setupCode: 'text = "HELLO"',
    expected: 'hello',
    sample: 'text.downcase',
    hints: ['downcase converts all characters to lowercase'],
    validPatterns: [/text\.downcase\b/],
    tags: ['downcase', 'lowercase'],
  },
  {
    id: 'ruby-string-capitalize-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Capitalize String',
    text: 'Use the `capitalize` method to capitalize the first letter.',
    setup: 'text = "hello world"',
    setupCode: 'text = "hello world"',
    expected: 'Hello world',
    sample: 'text.capitalize',
    hints: ['capitalize makes first letter uppercase, rest lowercase'],
    validPatterns: [/text\.capitalize\b/],
    tags: ['capitalize', 'title'],
  },

  // strip / chomp
  {
    id: 'ruby-string-strip-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Remove Whitespace',
    text: 'Use the `strip` method to remove leading and trailing whitespace.',
    setup: 'text = "  hello world  "',
    setupCode: 'text = "  hello world  "',
    expected: 'hello world',
    sample: 'text.strip',
    hints: ['strip removes whitespace from both ends'],
    validPatterns: [/text\.strip\b/],
    tags: ['strip', 'trim'],
  },
  {
    id: 'ruby-string-chomp-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Remove Trailing Newline',
    text: 'Use the `chomp` method to remove the trailing newline.',
    setup: 'text = "hello\\n"',
    setupCode: 'text = "hello\\n"',
    expected: 'hello',
    sample: 'text.chomp',
    hints: ['chomp removes trailing newline characters'],
    validPatterns: [/text\.chomp\b/],
    tags: ['chomp', 'newline'],
  },

  // gsub / sub
  {
    id: 'ruby-string-gsub-1',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Replace All Occurrences',
    text: 'Use `gsub` to replace all spaces with underscores.',
    setup: 'text = "hello world ruby"',
    setupCode: 'text = "hello world ruby"',
    expected: 'hello_world_ruby',
    sample: 'text.gsub(" ", "_")',
    hints: ['gsub replaces all occurrences', 'Takes pattern and replacement'],
    validPatterns: [
      /text\.gsub\s*\(\s*["'] ["'],\s*["']_["']\s*\)/,
      /text\.gsub\s*\(\s*\/\s+\/,\s*["']_["']\s*\)/,
      /text\.tr\s*\(\s*["'] ["'],\s*["']_["']\s*\)/,
    ],
    tags: ['gsub', 'replace'],
  },
  {
    id: 'ruby-string-sub-1',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Replace First Occurrence',
    text: 'Use `sub` to replace only the first space with a dash.',
    setup: 'text = "hello world ruby"',
    setupCode: 'text = "hello world ruby"',
    expected: 'hello-world ruby',
    sample: 'text.sub(" ", "-")',
    hints: ['sub replaces only the first occurrence'],
    validPatterns: [
      /text\.sub\s*\(\s*["'] ["'],\s*["']-["']\s*\)/,
      /text\.sub\s*\(\s*\/\s+\/,\s*["']-["']\s*\)/,
    ],
    tags: ['sub', 'replace'],
  },

  // include? / start_with? / end_with?
  {
    id: 'ruby-string-include-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Check Substring Inclusion',
    text: 'Use `include?` to check if the string contains "world".',
    setup: 'text = "hello world"',
    setupCode: 'text = "hello world"',
    expected: true,
    sample: 'text.include?("world")',
    hints: ['include? checks for substring presence'],
    validPatterns: [/text\.include\?\s*\(\s*["']world["']\s*\)/],
    tags: ['include?', 'contains'],
  },
  {
    id: 'ruby-string-start-with-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Check String Prefix',
    text: 'Use `start_with?` to check if the string starts with "hello".',
    setup: 'text = "hello world"',
    setupCode: 'text = "hello world"',
    expected: true,
    sample: 'text.start_with?("hello")',
    hints: ['start_with? checks the beginning'],
    validPatterns: [/text\.start_with\?\s*\(\s*["']hello["']\s*\)/],
    tags: ['start_with?', 'prefix'],
  },
  {
    id: 'ruby-string-end-with-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Check String Suffix',
    text: 'Use `end_with?` to check if the string ends with "world".',
    setup: 'text = "hello world"',
    setupCode: 'text = "hello world"',
    expected: true,
    sample: 'text.end_with?("world")',
    hints: ['end_with? checks the ending'],
    validPatterns: [/text\.end_with\?\s*\(\s*["']world["']\s*\)/],
    tags: ['end_with?', 'suffix'],
  },

  // reverse
  {
    id: 'ruby-string-reverse-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Reverse String',
    text: 'Use the `reverse` method to reverse the string.',
    setup: 'text = "hello"',
    setupCode: 'text = "hello"',
    expected: 'olleh',
    sample: 'text.reverse',
    hints: ['reverse returns the string backwards'],
    validPatterns: [/text\.reverse\b/],
    tags: ['reverse', 'backwards'],
  },

  // chars / bytes
  {
    id: 'ruby-string-chars-1',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Convert to Character Array',
    text: 'Use the `chars` method to convert the string to an array of characters.',
    setup: 'text = "ruby"',
    setupCode: 'text = "ruby"',
    expected: ['r', 'u', 'b', 'y'],
    sample: 'text.chars',
    hints: ['chars returns array of individual characters', 'split("") also works'],
    validPatterns: [/text\.chars\b/, /text\.split\s*\(\s*["']["']\s*\)/, /text\.each_char\.to_a\b/],
    tags: ['chars', 'characters'],
  },
  {
    id: 'ruby-string-bytes-1',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Get Byte Values',
    text: 'Use the `bytes` method to get the byte values of the string.',
    setup: 'text = "abc"',
    setupCode: 'text = "abc"',
    expected: [97, 98, 99],
    sample: 'text.bytes',
    hints: ['bytes returns ASCII values'],
    validPatterns: [/text\.bytes\b/],
    tags: ['bytes', 'ascii'],
  },

  // ============================================================
  // Hash Methods
  // ============================================================

  // keys / values
  {
    id: 'ruby-hash-keys-1',
    category: 'Hash Methods',
    difficulty: 'easy',
    title: 'Get Hash Keys',
    text: 'Use the `keys` method to get all keys from the hash.',
    setup: 'person = { name: "Alice", age: 30, city: "NYC" }',
    setupCode: 'person = { name: "Alice", age: 30, city: "NYC" }',
    expected: [':name', ':age', ':city'],
    sample: 'person.keys',
    hints: ['keys returns an array of all keys (as symbols)'],
    validPatterns: [/person\.keys\b/],
    tags: ['keys', 'hash', 'symbols'],
  },
  {
    id: 'ruby-hash-values-1',
    category: 'Hash Methods',
    difficulty: 'easy',
    title: 'Get Hash Values',
    text: 'Use the `values` method to get all values from the hash.',
    setup: 'person = { name: "Alice", age: 30 }',
    setupCode: 'person = { name: "Alice", age: 30 }',
    expected: ['Alice', 30],
    sample: 'person.values',
    hints: ['values returns an array of all values'],
    validPatterns: [/person\.values\b/],
    tags: ['values', 'hash'],
  },

  // each / each_pair
  {
    id: 'ruby-hash-each-1',
    category: 'Hash Methods',
    difficulty: 'medium',
    title: 'Iterate Hash with each',
    text: 'Use `each` to iterate and return the original hash.',
    setup: 'scores = { alice: 90, bob: 85 }',
    setupCode: 'scores = { alice: 90, bob: 85 }',
    expected: { alice: 90, bob: 85 },
    sample: 'scores.each { |k, v| puts "#{k}: #{v}" }',
    hints: ['each yields key-value pairs', 'Returns the original hash'],
    validPatterns: [
      /scores\.each\s*\{\s*\|(\w+),\s*(\w+)\|/,
      /scores\.each_pair\s*\{\s*\|(\w+),\s*(\w+)\|/,
    ],
    tags: ['each', 'iteration'],
  },

  // select / reject
  {
    id: 'ruby-hash-select-1',
    category: 'Hash Methods',
    difficulty: 'medium',
    title: 'Select Hash Entries',
    text: 'Use `select` to get hash entries where value is greater than 80.',
    setup: 'scores = { alice: 90, bob: 75, carol: 85 }',
    setupCode: 'scores = { alice: 90, bob: 75, carol: 85 }',
    expected: { alice: 90, carol: 85 },
    sample: 'scores.select { |k, v| v > 80 }',
    hints: ['select filters hash entries', 'Block receives key and value'],
    validPatterns: [
      /scores\.select\s*\{\s*\|(\w+),\s*(\w+)\|\s*\2\s*>\s*80\s*\}/,
      /scores\.select\s*\{\s*\|_,\s*(\w+)\|\s*\1\s*>\s*80\s*\}/,
    ],
    tags: ['select', 'filter'],
  },
  {
    id: 'ruby-hash-reject-1',
    category: 'Hash Methods',
    difficulty: 'medium',
    title: 'Reject Hash Entries',
    text: 'Use `reject` to remove hash entries where value is less than 80.',
    setup: 'scores = { alice: 90, bob: 75, carol: 85 }',
    setupCode: 'scores = { alice: 90, bob: 75, carol: 85 }',
    expected: { alice: 90, carol: 85 },
    sample: 'scores.reject { |k, v| v < 80 }',
    hints: ['reject removes entries where block is true'],
    validPatterns: [
      /scores\.reject\s*\{\s*\|(\w+),\s*(\w+)\|\s*\2\s*<\s*80\s*\}/,
      /scores\.reject\s*\{\s*\|_,\s*(\w+)\|\s*\1\s*<\s*80\s*\}/,
    ],
    tags: ['reject', 'filter'],
  },

  // merge
  {
    id: 'ruby-hash-merge-1',
    category: 'Hash Methods',
    difficulty: 'easy',
    title: 'Merge Hashes',
    text: 'Use `merge` to combine two hashes.',
    setup: 'defaults = { a: 1, b: 2 }\noverrides = { b: 3, c: 4 }',
    setupCode: 'defaults = { a: 1, b: 2 }\noverrides = { b: 3, c: 4 }',
    expected: { a: 1, b: 3, c: 4 },
    sample: 'defaults.merge(overrides)',
    hints: ['merge combines hashes', 'Second hash values override first'],
    validPatterns: [/defaults\.merge\s*\(\s*overrides\s*\)/],
    tags: ['merge', 'combine'],
  },

  // fetch / dig
  {
    id: 'ruby-hash-fetch-1',
    category: 'Hash Methods',
    difficulty: 'medium',
    title: 'Fetch with Default',
    text: 'Use `fetch` to get a value with a default if key is missing.',
    setup: 'person = { name: "Alice" }',
    setupCode: 'person = { name: "Alice" }',
    expected: 'Unknown',
    sample: 'person.fetch(:age, "Unknown")',
    hints: ['fetch takes key and default value', 'Default used if key missing'],
    validPatterns: [/person\.fetch\s*\(\s*:age,\s*["']Unknown["']\s*\)/],
    tags: ['fetch', 'default'],
  },
  {
    id: 'ruby-hash-dig-1',
    category: 'Hash Methods',
    difficulty: 'medium',
    title: 'Dig into Nested Hash',
    text: 'Use `dig` to safely access a nested value.',
    setup: 'data = { user: { profile: { name: "Alice" } } }',
    setupCode: 'data = { user: { profile: { name: "Alice" } } }',
    expected: 'Alice',
    sample: 'data.dig(:user, :profile, :name)',
    hints: ['dig navigates nested structures safely', 'Returns nil if path missing'],
    validPatterns: [/data\.dig\s*\(\s*:user,\s*:profile,\s*:name\s*\)/],
    tags: ['dig', 'nested'],
  },

  // ============================================================
  // Enumerable Methods
  // ============================================================

  // any? / all? / none?
  {
    id: 'ruby-enum-any-1',
    category: 'Enumerable Methods',
    difficulty: 'easy',
    title: 'Check if Any Match',
    text: 'Use `any?` to check if any number is greater than 10.',
    setup: 'numbers = [5, 8, 12, 3]',
    setupCode: 'numbers = [5, 8, 12, 3]',
    expected: true,
    sample: 'numbers.any? { |n| n > 10 }',
    hints: ['any? returns true if any element matches'],
    validPatterns: [/numbers\.any\?\s*\{\s*\|(\w+)\|\s*\1\s*>\s*10\s*\}/],
    tags: ['any?', 'predicate'],
  },
  {
    id: 'ruby-enum-all-1',
    category: 'Enumerable Methods',
    difficulty: 'easy',
    title: 'Check if All Match',
    text: 'Use `all?` to check if all numbers are positive.',
    setup: 'numbers = [1, 2, 3, 4, 5]',
    setupCode: 'numbers = [1, 2, 3, 4, 5]',
    expected: true,
    sample: 'numbers.all? { |n| n > 0 }',
    hints: ['all? returns true if all elements match'],
    validPatterns: [
      /numbers\.all\?\s*\{\s*\|(\w+)\|\s*\1\s*>\s*0\s*\}/,
      /numbers\.all\?\s*\(\s*&:positive\?\s*\)/,
    ],
    tags: ['all?', 'predicate'],
  },
  {
    id: 'ruby-enum-none-1',
    category: 'Enumerable Methods',
    difficulty: 'easy',
    title: 'Check if None Match',
    text: 'Use `none?` to check if no numbers are negative.',
    setup: 'numbers = [1, 2, 3, 4, 5]',
    setupCode: 'numbers = [1, 2, 3, 4, 5]',
    expected: true,
    sample: 'numbers.none? { |n| n < 0 }',
    hints: ['none? returns true if no elements match'],
    validPatterns: [
      /numbers\.none\?\s*\{\s*\|(\w+)\|\s*\1\s*<\s*0\s*\}/,
      /numbers\.none\?\s*\(\s*&:negative\?\s*\)/,
    ],
    tags: ['none?', 'predicate'],
  },

  // count
  {
    id: 'ruby-enum-count-1',
    category: 'Enumerable Methods',
    difficulty: 'easy',
    title: 'Count Elements',
    text: 'Use `count` to count how many numbers are even.',
    setup: 'numbers = [1, 2, 3, 4, 5, 6]',
    setupCode: 'numbers = [1, 2, 3, 4, 5, 6]',
    expected: 3,
    sample: 'numbers.count { |n| n.even? }',
    hints: ['count with block counts matching elements'],
    validPatterns: [
      /numbers\.count\s*\{\s*\|(\w+)\|\s*\1\.even\?\s*\}/,
      /numbers\.count\s*\(\s*&:even\?\s*\)/,
    ],
    tags: ['count', 'quantity'],
  },

  // max / min / minmax
  {
    id: 'ruby-enum-max-1',
    category: 'Enumerable Methods',
    difficulty: 'easy',
    title: 'Find Maximum',
    text: 'Use the `max` method to find the largest number.',
    setup: 'numbers = [3, 7, 1, 9, 4]',
    setupCode: 'numbers = [3, 7, 1, 9, 4]',
    expected: 9,
    sample: 'numbers.max',
    hints: ['max returns the largest element'],
    validPatterns: [/numbers\.max\b/],
    tags: ['max', 'largest'],
  },
  {
    id: 'ruby-enum-min-1',
    category: 'Enumerable Methods',
    difficulty: 'easy',
    title: 'Find Minimum',
    text: 'Use the `min` method to find the smallest number.',
    setup: 'numbers = [3, 7, 1, 9, 4]',
    setupCode: 'numbers = [3, 7, 1, 9, 4]',
    expected: 1,
    sample: 'numbers.min',
    hints: ['min returns the smallest element'],
    validPatterns: [/numbers\.min\b/],
    tags: ['min', 'smallest'],
  },
  {
    id: 'ruby-enum-minmax-1',
    category: 'Enumerable Methods',
    difficulty: 'easy',
    title: 'Find Min and Max',
    text: 'Use `minmax` to get both minimum and maximum in one call.',
    setup: 'numbers = [3, 7, 1, 9, 4]',
    setupCode: 'numbers = [3, 7, 1, 9, 4]',
    expected: [1, 9],
    sample: 'numbers.minmax',
    hints: ['minmax returns [min, max] array'],
    validPatterns: [/numbers\.minmax\b/],
    tags: ['minmax', 'range'],
  },

  // sum
  {
    id: 'ruby-enum-sum-1',
    category: 'Enumerable Methods',
    difficulty: 'easy',
    title: 'Sum Array Elements',
    text: 'Use the `sum` method to calculate the total of all numbers.',
    setup: 'numbers = [1, 2, 3, 4, 5]',
    setupCode: 'numbers = [1, 2, 3, 4, 5]',
    expected: 15,
    sample: 'numbers.sum',
    hints: ['sum adds all elements together'],
    validPatterns: [
      /numbers\.sum\b/,
      /numbers\.reduce\s*\(\s*:?\+\s*\)/,
      /numbers\.inject\s*\(\s*:?\+\s*\)/,
    ],
    tags: ['sum', 'total'],
  },
];

export default rubyProblems;
