/**
 * Swift Coding Drills Problems
 *
 * Comprehensive collection of Swift problems covering:
 * - Array Methods (10 problems)
 * - String Methods (10 problems)
 * - Dictionary Methods (10 problems)
 * - Set Operations (10 problems)
 * - Optional Handling (10 problems)
 *
 * Distribution: 20 easy, 20 medium, 10 hard
 */

import type { Problem } from '../types';

export const swiftProblems: Problem[] = [
  // ============================================================
  // Array Methods (10 problems: 4 easy, 4 medium, 2 hard)
  // ============================================================

  {
    id: 'swift-array-001',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Filter Even Numbers',
    text: 'Filter the array to keep only even numbers.',
    setup: 'let numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]',
    setupCode: 'let numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]',
    expected: [2, 4, 6, 8, 10],
    sample: 'numbers.filter { $0 % 2 == 0 }',
    hints: ['Use filter with a closure', '$0 refers to each element in the closure'],
    validPatterns: [/\.filter\s*\{.*%\s*2\s*==\s*0.*\}/],
    tags: ['filter', 'arrays', 'closure'],
  },

  {
    id: 'swift-array-002',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Map to Squares',
    text: 'Transform each number in the array to its square.',
    setup: 'let numbers = [1, 2, 3, 4, 5]',
    setupCode: 'let numbers = [1, 2, 3, 4, 5]',
    expected: [1, 4, 9, 16, 25],
    sample: 'numbers.map { $0 * $0 }',
    hints: ['Use map to transform each element', 'Return the square of each number'],
    validPatterns: [/\.map\s*\{.*\*.*\}/],
    tags: ['map', 'arrays', 'transform'],
  },

  {
    id: 'swift-array-003',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Reduce to Sum',
    text: 'Calculate the sum of all numbers using reduce.',
    setup: 'let numbers = [1, 2, 3, 4, 5]',
    setupCode: 'let numbers = [1, 2, 3, 4, 5]',
    expected: 15,
    sample: 'numbers.reduce(0, +)',
    hints: [
      'reduce takes an initial value and a combining closure',
      'You can use the + operator directly',
    ],
    validPatterns: [/\.reduce\s*\(\s*0\s*,\s*\+\s*\)/, /\.reduce\s*\(\s*0\s*\)\s*\{.*\+.*\}/],
    tags: ['reduce', 'arrays', 'aggregation'],
  },

  {
    id: 'swift-array-004',
    category: 'Array Methods',
    difficulty: 'easy',
    title: 'Check Contains Element',
    text: 'Check if the array contains the number 5.',
    setup: 'let numbers = [1, 2, 3, 4, 5, 6, 7]',
    setupCode: 'let numbers = [1, 2, 3, 4, 5, 6, 7]',
    expected: true,
    sample: 'numbers.contains(5)',
    hints: ['contains returns a Bool', 'Works with Equatable types'],
    validPatterns: [/\.contains\s*\(\s*5\s*\)/],
    tags: ['contains', 'arrays', 'search'],
  },

  {
    id: 'swift-array-005',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Sort Array Ascending',
    text: 'Sort the array in ascending order.',
    setup: 'let numbers = [5, 2, 8, 1, 9, 3]',
    setupCode: 'let numbers = [5, 2, 8, 1, 9, 3]',
    expected: [1, 2, 3, 5, 8, 9],
    sample: 'numbers.sorted()',
    hints: ['sorted() returns a new sorted array', 'Default sorting is ascending'],
    validPatterns: [/\.sorted\s*\(\s*\)/],
    tags: ['sorted', 'arrays', 'order'],
  },

  {
    id: 'swift-array-006',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Reverse Array',
    text: 'Reverse the order of elements in the array.',
    setup: 'let numbers = [1, 2, 3, 4, 5]',
    setupCode: 'let numbers = [1, 2, 3, 4, 5]',
    expected: [5, 4, 3, 2, 1],
    sample: 'Array(numbers.reversed())',
    hints: ['reversed() returns a ReversedCollection', 'Wrap in Array() to get an Array'],
    validPatterns: [/\.reversed\s*\(\s*\)/, /Array\s*\(\s*numbers\.reversed\s*\(\s*\)\s*\)/],
    tags: ['reversed', 'arrays', 'order'],
  },

  {
    id: 'swift-array-007',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Get First Element',
    text: 'Get the first element of the array safely.',
    setup: 'let fruits = ["apple", "banana", "cherry"]',
    setupCode: 'let fruits = ["apple", "banana", "cherry"]',
    expected: 'apple',
    sample: 'fruits.first',
    hints: ['first is a property that returns an optional', 'Returns nil for empty arrays'],
    validPatterns: [/\.first(?!\()/],
    tags: ['first', 'arrays', 'access'],
  },

  {
    id: 'swift-array-008',
    category: 'Array Methods',
    difficulty: 'medium',
    title: 'Get Last Element',
    text: 'Get the last element of the array safely.',
    setup: 'let fruits = ["apple", "banana", "cherry"]',
    setupCode: 'let fruits = ["apple", "banana", "cherry"]',
    expected: 'cherry',
    sample: 'fruits.last',
    hints: ['last is a property that returns an optional', 'Returns nil for empty arrays'],
    validPatterns: [/\.last(?!\()/],
    tags: ['last', 'arrays', 'access'],
  },

  {
    id: 'swift-array-009',
    category: 'Array Methods',
    difficulty: 'hard',
    title: 'Reduce to Dictionary',
    text: 'Create a dictionary counting occurrences of each element.',
    setup: 'let letters = ["a", "b", "a", "c", "b", "a"]',
    setupCode: 'let letters = ["a", "b", "a", "c", "b", "a"]',
    expected: { a: 3, b: 2, c: 1 },
    sample: 'letters.reduce(into: [:]) { counts, letter in counts[letter, default: 0] += 1 }',
    hints: [
      'reduce(into:) allows mutation of the accumulator',
      'More efficient for building collections',
    ],
    validPatterns: [/\.reduce\s*\(\s*into:\s*\[:\]\s*\)\s*\{/],
    tags: ['reduce', 'arrays', 'dictionary'],
  },

  {
    id: 'swift-array-010',
    category: 'Array Methods',
    difficulty: 'hard',
    title: 'Sort By Custom Criteria',
    text: 'Sort strings by their length in ascending order.',
    setup: 'let words = ["cat", "elephant", "dog", "bird"]',
    setupCode: 'let words = ["cat", "elephant", "dog", "bird"]',
    expected: ['cat', 'dog', 'bird', 'elephant'],
    sample: 'words.sorted { $0.count < $1.count }',
    hints: [
      'sorted(by:) takes a comparison closure',
      'Return true if first element should come before second',
    ],
    validPatterns: [
      /\.sorted\s*\{.*\.count\s*<.*\.count.*\}/,
      /\.sorted\s*\(\s*by:\s*\{.*\.count.*\}\s*\)/,
    ],
    tags: ['sorted', 'arrays', 'custom sort'],
  },

  // ============================================================
  // String Methods (10 problems: 4 easy, 4 medium, 2 hard)
  // ============================================================

  {
    id: 'swift-string-001',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'String Length',
    text: 'Get the number of characters in the string.',
    setup: 'let message = "Hello, Swift!"',
    setupCode: 'let message = "Hello, Swift!"',
    expected: 13,
    sample: 'message.count',
    hints: ['Use the count property for String length', 'count returns the number of characters'],
    validPatterns: [/\.count(?!\()/],
    tags: ['count', 'string', 'length'],
  },

  {
    id: 'swift-string-002',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Convert to Lowercase',
    text: 'Convert the string to all lowercase letters.',
    setup: 'let message = "Hello, SWIFT!"',
    setupCode: 'let message = "Hello, SWIFT!"',
    expected: 'hello, swift!',
    sample: 'message.lowercased()',
    hints: ['lowercased() returns a new lowercase string', 'Does not modify the original string'],
    validPatterns: [/\.lowercased\s*\(\s*\)/],
    tags: ['lowercased', 'string', 'case'],
  },

  {
    id: 'swift-string-003',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Convert to Uppercase',
    text: 'Convert the string to all uppercase letters.',
    setup: 'let message = "Hello, Swift!"',
    setupCode: 'let message = "Hello, Swift!"',
    expected: 'HELLO, SWIFT!',
    sample: 'message.uppercased()',
    hints: ['uppercased() returns a new uppercase string', 'Does not modify the original string'],
    validPatterns: [/\.uppercased\s*\(\s*\)/],
    tags: ['uppercased', 'string', 'case'],
  },

  {
    id: 'swift-string-004',
    category: 'String Methods',
    difficulty: 'easy',
    title: 'Check String Contains',
    text: 'Check if the string contains the word "Swift".',
    setup: 'let message = "Hello, Swift!"',
    setupCode: 'let message = "Hello, Swift!"',
    expected: true,
    sample: 'message.contains("Swift")',
    hints: ['contains returns a Bool', 'Case-sensitive by default'],
    validPatterns: [/\.contains\s*\(\s*"Swift"\s*\)/],
    tags: ['contains', 'string', 'search'],
  },

  {
    id: 'swift-string-005',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Split String by Delimiter',
    text: 'Split the string into an array using comma as delimiter.',
    setup: 'let csv = "apple,banana,cherry,date"',
    setupCode: 'let csv = "apple,banana,cherry,date"',
    expected: ['apple', 'banana', 'cherry', 'date'],
    sample: 'csv.split(separator: ",").map(String.init)',
    hints: ['split returns an array of Substring', 'Map to String if you need String array'],
    validPatterns: [
      /\.split\s*\(\s*separator:\s*","\s*\)/,
      /\.components\s*\(\s*separatedBy:\s*","\s*\)/,
    ],
    tags: ['split', 'string', 'tokenize'],
  },

  {
    id: 'swift-string-006',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Check String Prefix',
    text: 'Check if the string starts with "Hello".',
    setup: 'let message = "Hello, World!"',
    setupCode: 'let message = "Hello, World!"',
    expected: true,
    sample: 'message.hasPrefix("Hello")',
    hints: [
      'hasPrefix checks the beginning of the string',
      'Returns true if string starts with the prefix',
    ],
    validPatterns: [/\.hasPrefix\s*\(\s*"Hello"\s*\)/],
    tags: ['hasPrefix', 'string', 'prefix'],
  },

  {
    id: 'swift-string-007',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Check String Suffix',
    text: 'Check if the string ends with "World!".',
    setup: 'let message = "Hello, World!"',
    setupCode: 'let message = "Hello, World!"',
    expected: true,
    sample: 'message.hasSuffix("World!")',
    hints: [
      'hasSuffix checks the end of the string',
      'Returns true if string ends with the suffix',
    ],
    validPatterns: [/\.hasSuffix\s*\(\s*"World!"\s*\)/],
    tags: ['hasSuffix', 'string', 'suffix'],
  },

  {
    id: 'swift-string-008',
    category: 'String Methods',
    difficulty: 'medium',
    title: 'Join Array to String',
    text: 'Join the array elements into a single string separated by ", ".',
    setup: 'let fruits = ["apple", "banana", "cherry"]',
    setupCode: 'let fruits = ["apple", "banana", "cherry"]',
    expected: 'apple, banana, cherry',
    sample: 'fruits.joined(separator: ", ")',
    hints: ['joined(separator:) concatenates array elements', 'Works on arrays of strings'],
    validPatterns: [/\.joined\s*\(\s*separator:\s*", "\s*\)/],
    tags: ['joined', 'string', 'concatenate'],
  },

  {
    id: 'swift-string-009',
    category: 'String Methods',
    difficulty: 'hard',
    title: 'String Indices',
    text: 'Get the character at index 4 of the string.',
    setup: 'let message = "Hello, Swift!"',
    setupCode: 'let message = "Hello, Swift!"',
    expected: 'o',
    sample: 'message[message.index(message.startIndex, offsetBy: 4)]',
    hints: [
      'Swift strings use String.Index, not integers',
      'Use index(_:offsetBy:) to calculate positions',
    ],
    validPatterns: [/message\.index\s*\(\s*message\.startIndex\s*,\s*offsetBy:\s*4\s*\)/],
    tags: ['index', 'string', 'access'],
  },

  {
    id: 'swift-string-010',
    category: 'String Methods',
    difficulty: 'hard',
    title: 'Substring Range',
    text: 'Extract the first 5 characters of the string.',
    setup: 'let message = "Hello, World!"',
    setupCode: 'let message = "Hello, World!"',
    expected: 'Hello',
    sample: 'String(message.prefix(5))',
    hints: ['prefix() returns the first n characters', 'Convert Substring to String if needed'],
    validPatterns: [/\.prefix\s*\(\s*5\s*\)/],
    tags: ['prefix', 'string', 'substring'],
  },

  // ============================================================
  // Dictionary Methods (10 problems: 4 easy, 4 medium, 2 hard)
  // ============================================================

  {
    id: 'swift-dictionary-001',
    category: 'Dictionary Methods',
    difficulty: 'easy',
    title: 'Get All Keys',
    text: 'Get an array of all keys from the dictionary.',
    setup: 'let scores = ["Alice": 95, "Bob": 87, "Charlie": 92]',
    setupCode: 'let scores = ["Alice": 95, "Bob": 87, "Charlie": 92]',
    expected: ['Alice', 'Bob', 'Charlie'],
    sample: 'Array(scores.keys)',
    hints: ['keys property returns a Keys collection', 'Wrap in Array() to get an Array'],
    validPatterns: [/Array\s*\(\s*scores\.keys\s*\)/, /scores\.keys/],
    tags: ['keys', 'dictionary', 'access'],
  },

  {
    id: 'swift-dictionary-002',
    category: 'Dictionary Methods',
    difficulty: 'easy',
    title: 'Get All Values',
    text: 'Get an array of all values from the dictionary.',
    setup: 'let scores = ["Alice": 95, "Bob": 87, "Charlie": 92]',
    setupCode: 'let scores = ["Alice": 95, "Bob": 87, "Charlie": 92]',
    expected: [95, 87, 92],
    sample: 'Array(scores.values)',
    hints: ['values property returns a Values collection', 'Wrap in Array() to get an Array'],
    validPatterns: [/Array\s*\(\s*scores\.values\s*\)/, /scores\.values/],
    tags: ['values', 'dictionary', 'access'],
  },

  {
    id: 'swift-dictionary-003',
    category: 'Dictionary Methods',
    difficulty: 'easy',
    title: 'Get Value by Key',
    text: 'Get the value for key "Alice" from the dictionary.',
    setup: 'let scores = ["Alice": 95, "Bob": 87, "Charlie": 92]',
    setupCode: 'let scores = ["Alice": 95, "Bob": 87, "Charlie": 92]',
    expected: 95,
    sample: 'scores["Alice"]',
    hints: ['Use subscript notation with the key', 'Returns an optional value'],
    validPatterns: [/scores\s*\[\s*"Alice"\s*\]/],
    tags: ['subscript', 'dictionary', 'access'],
  },

  {
    id: 'swift-dictionary-004',
    category: 'Dictionary Methods',
    difficulty: 'easy',
    title: 'Get Value with Default',
    text: 'Get the value for key "David" with a default value of 0.',
    setup: 'let scores = ["Alice": 95, "Bob": 87]',
    setupCode: 'let scores = ["Alice": 95, "Bob": 87]',
    expected: 0,
    sample: 'scores["David", default: 0]',
    hints: ['Use subscript with default parameter', 'Returns the default if key is not found'],
    validPatterns: [/scores\s*\[\s*"David"\s*,\s*default:\s*0\s*\]/],
    tags: ['subscript', 'dictionary', 'default'],
  },

  {
    id: 'swift-dictionary-005',
    category: 'Dictionary Methods',
    difficulty: 'medium',
    title: 'Update Dictionary Value',
    text: 'Update the value for key "Alice" to 100 and return the old value.',
    setup: 'var scores = ["Alice": 95, "Bob": 87]',
    setupCode: 'var scores = ["Alice": 95, "Bob": 87]',
    expected: 95,
    sample: 'scores.updateValue(100, forKey: "Alice")',
    hints: ['updateValue returns the old value as optional', 'Returns nil if key did not exist'],
    validPatterns: [/\.updateValue\s*\(\s*100\s*,\s*forKey:\s*"Alice"\s*\)/],
    tags: ['updateValue', 'dictionary', 'modify'],
  },

  {
    id: 'swift-dictionary-006',
    category: 'Dictionary Methods',
    difficulty: 'medium',
    title: 'Remove Value by Key',
    text: 'Remove the entry for key "Bob" and return the removed value.',
    setup: 'var scores = ["Alice": 95, "Bob": 87, "Charlie": 92]',
    setupCode: 'var scores = ["Alice": 95, "Bob": 87, "Charlie": 92]',
    expected: 87,
    sample: 'scores.removeValue(forKey: "Bob")',
    hints: [
      'removeValue returns the removed value as optional',
      'Returns nil if key did not exist',
    ],
    validPatterns: [/\.removeValue\s*\(\s*forKey:\s*"Bob"\s*\)/],
    tags: ['removeValue', 'dictionary', 'remove'],
  },

  {
    id: 'swift-dictionary-007',
    category: 'Dictionary Methods',
    difficulty: 'medium',
    title: 'Check Key Exists',
    text: 'Check if the dictionary contains the key "Alice".',
    setup: 'let scores = ["Alice": 95, "Bob": 87]',
    setupCode: 'let scores = ["Alice": 95, "Bob": 87]',
    expected: true,
    sample: 'scores.keys.contains("Alice")',
    hints: ['Check if key exists in keys collection', 'Or check if value is not nil'],
    validPatterns: [
      /\.keys\.contains\s*\(\s*"Alice"\s*\)/,
      /scores\s*\[\s*"Alice"\s*\]\s*!=\s*nil/,
    ],
    tags: ['contains', 'dictionary', 'check'],
  },

  {
    id: 'swift-dictionary-008',
    category: 'Dictionary Methods',
    difficulty: 'medium',
    title: 'Merge Dictionaries',
    text: 'Merge two dictionaries, keeping the values from the second one for duplicate keys.',
    setup: 'var dict1 = ["a": 1, "b": 2]\nlet dict2 = ["b": 3, "c": 4]',
    setupCode: 'var dict1 = ["a": 1, "b": 2]\nlet dict2 = ["b": 3, "c": 4]',
    expected: { a: 1, b: 3, c: 4 },
    sample: 'dict1.merge(dict2) { _, new in new }',
    hints: [
      'merge takes a dictionary and a closure for conflicts',
      'The closure receives (current, new) values',
    ],
    validPatterns: [/\.merge\s*\(\s*dict2\s*\)\s*\{/, /\.merging\s*\(\s*dict2\s*\)\s*\{/],
    tags: ['merge', 'dictionary', 'combine'],
  },

  {
    id: 'swift-dictionary-009',
    category: 'Dictionary Methods',
    difficulty: 'hard',
    title: 'Filter Dictionary',
    text: 'Filter the dictionary to keep only entries where the value is greater than 90.',
    setup: 'let scores = ["Alice": 95, "Bob": 87, "Charlie": 92]',
    setupCode: 'let scores = ["Alice": 95, "Bob": 87, "Charlie": 92]',
    expected: { Alice: 95, Charlie: 92 },
    sample: 'scores.filter { $0.value > 90 }',
    hints: ['filter works on dictionaries too', 'Closure receives key-value pairs'],
    validPatterns: [
      /\.filter\s*\{.*\.value\s*>\s*90.*\}/,
      /\.filter\s*\{.*\$0\.value\s*>\s*90.*\}/,
    ],
    tags: ['filter', 'dictionary', 'predicate'],
  },

  {
    id: 'swift-dictionary-010',
    category: 'Dictionary Methods',
    difficulty: 'hard',
    title: 'Map Dictionary Values',
    text: 'Transform all values in the dictionary by adding 10 to each.',
    setup: 'let scores = ["Alice": 90, "Bob": 80, "Charlie": 85]',
    setupCode: 'let scores = ["Alice": 90, "Bob": 80, "Charlie": 85]',
    expected: { Alice: 100, Bob: 90, Charlie: 95 },
    sample: 'scores.mapValues { $0 + 10 }',
    hints: ['mapValues transforms values while keeping keys', 'Returns a new dictionary'],
    validPatterns: [/\.mapValues\s*\{.*\+\s*10.*\}/],
    tags: ['mapValues', 'dictionary', 'transform'],
  },

  // ============================================================
  // Set Operations (10 problems: 4 easy, 4 medium, 2 hard)
  // ============================================================

  {
    id: 'swift-set-001',
    category: 'Set Operations',
    difficulty: 'easy',
    title: 'Insert Element',
    text: 'Insert the number 4 into the set.',
    setup: 'var numbers: Set = [1, 2, 3]',
    setupCode: 'var numbers: Set = [1, 2, 3]',
    expected: [1, 2, 3, 4],
    sample: 'numbers.insert(4)',
    hints: [
      'insert adds an element to the set',
      'Returns a tuple with (inserted, memberAfterInsert)',
    ],
    validPatterns: [/\.insert\s*\(\s*4\s*\)/],
    tags: ['insert', 'set', 'add'],
  },

  {
    id: 'swift-set-002',
    category: 'Set Operations',
    difficulty: 'easy',
    title: 'Remove Element',
    text: 'Remove the number 2 from the set.',
    setup: 'var numbers: Set = [1, 2, 3]',
    setupCode: 'var numbers: Set = [1, 2, 3]',
    expected: 2,
    sample: 'numbers.remove(2)',
    hints: ['remove returns the removed element or nil', 'Does nothing if element not found'],
    validPatterns: [/\.remove\s*\(\s*2\s*\)/],
    tags: ['remove', 'set', 'delete'],
  },

  {
    id: 'swift-set-003',
    category: 'Set Operations',
    difficulty: 'easy',
    title: 'Check Set Contains',
    text: 'Check if the set contains the number 3.',
    setup: 'let numbers: Set = [1, 2, 3, 4, 5]',
    setupCode: 'let numbers: Set = [1, 2, 3, 4, 5]',
    expected: true,
    sample: 'numbers.contains(3)',
    hints: ['contains returns a Bool', 'O(1) lookup for sets'],
    validPatterns: [/\.contains\s*\(\s*3\s*\)/],
    tags: ['contains', 'set', 'search'],
  },

  {
    id: 'swift-set-004',
    category: 'Set Operations',
    difficulty: 'easy',
    title: 'Union of Sets',
    text: 'Create the union of two sets.',
    setup: 'let setA: Set = [1, 2, 3]\nlet setB: Set = [3, 4, 5]',
    setupCode: 'let setA: Set = [1, 2, 3]\nlet setB: Set = [3, 4, 5]',
    expected: [1, 2, 3, 4, 5],
    sample: 'setA.union(setB)',
    hints: ['union combines elements from both sets', 'Duplicates are automatically removed'],
    validPatterns: [/\.union\s*\(\s*setB\s*\)/, /setA\.union\s*\(/],
    tags: ['union', 'set', 'combine'],
  },

  {
    id: 'swift-set-005',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Intersection of Sets',
    text: 'Find the common elements between two sets.',
    setup: 'let setA: Set = [1, 2, 3, 4]\nlet setB: Set = [3, 4, 5, 6]',
    setupCode: 'let setA: Set = [1, 2, 3, 4]\nlet setB: Set = [3, 4, 5, 6]',
    expected: [3, 4],
    sample: 'setA.intersection(setB)',
    hints: ['intersection returns elements present in both sets', 'Returns a new set'],
    validPatterns: [/\.intersection\s*\(\s*setB\s*\)/, /setA\.intersection\s*\(/],
    tags: ['intersection', 'set', 'common'],
  },

  {
    id: 'swift-set-006',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Difference of Sets',
    text: 'Find elements in setA that are not in setB.',
    setup: 'let setA: Set = [1, 2, 3, 4]\nlet setB: Set = [3, 4, 5, 6]',
    setupCode: 'let setA: Set = [1, 2, 3, 4]\nlet setB: Set = [3, 4, 5, 6]',
    expected: [1, 2],
    sample: 'setA.subtracting(setB)',
    hints: [
      'subtracting removes elements present in the other set',
      'Order matters: A - B is different from B - A',
    ],
    validPatterns: [/\.subtracting\s*\(\s*setB\s*\)/, /setA\.subtracting\s*\(/],
    tags: ['subtracting', 'set', 'difference'],
  },

  {
    id: 'swift-set-007',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Symmetric Difference',
    text: 'Find elements that are in either set but not in both.',
    setup: 'let setA: Set = [1, 2, 3]\nlet setB: Set = [3, 4, 5]',
    setupCode: 'let setA: Set = [1, 2, 3]\nlet setB: Set = [3, 4, 5]',
    expected: [1, 2, 4, 5],
    sample: 'setA.symmetricDifference(setB)',
    hints: [
      'symmetricDifference returns elements unique to each set',
      'Excludes elements present in both',
    ],
    validPatterns: [/\.symmetricDifference\s*\(\s*setB\s*\)/],
    tags: ['symmetricDifference', 'set', 'xor'],
  },

  {
    id: 'swift-set-008',
    category: 'Set Operations',
    difficulty: 'medium',
    title: 'Check Subset',
    text: 'Check if setA is a subset of setB.',
    setup: 'let setA: Set = [1, 2]\nlet setB: Set = [1, 2, 3, 4, 5]',
    setupCode: 'let setA: Set = [1, 2]\nlet setB: Set = [1, 2, 3, 4, 5]',
    expected: true,
    sample: 'setA.isSubset(of: setB)',
    hints: [
      'isSubset returns true if all elements are in the other set',
      'A set is a subset of itself',
    ],
    validPatterns: [/\.isSubset\s*\(\s*of:\s*setB\s*\)/],
    tags: ['isSubset', 'set', 'subset'],
  },

  {
    id: 'swift-set-009',
    category: 'Set Operations',
    difficulty: 'hard',
    title: 'Check Superset',
    text: 'Check if setA is a superset of setB.',
    setup: 'let setA: Set = [1, 2, 3, 4, 5]\nlet setB: Set = [2, 3]',
    setupCode: 'let setA: Set = [1, 2, 3, 4, 5]\nlet setB: Set = [2, 3]',
    expected: true,
    sample: 'setA.isSuperset(of: setB)',
    hints: [
      'isSuperset returns true if it contains all elements of the other set',
      'Opposite of isSubset',
    ],
    validPatterns: [/\.isSuperset\s*\(\s*of:\s*setB\s*\)/],
    tags: ['isSuperset', 'set', 'superset'],
  },

  {
    id: 'swift-set-010',
    category: 'Set Operations',
    difficulty: 'hard',
    title: 'Check Disjoint Sets',
    text: 'Check if two sets have no common elements.',
    setup: 'let setA: Set = [1, 2, 3]\nlet setB: Set = [4, 5, 6]',
    setupCode: 'let setA: Set = [1, 2, 3]\nlet setB: Set = [4, 5, 6]',
    expected: true,
    sample: 'setA.isDisjoint(with: setB)',
    hints: [
      'isDisjoint returns true if sets have no common elements',
      'Empty intersection means disjoint',
    ],
    validPatterns: [/\.isDisjoint\s*\(\s*with:\s*setB\s*\)/],
    tags: ['isDisjoint', 'set', 'disjoint'],
  },

  // ============================================================
  // Optional Handling (10 problems: 4 easy, 4 medium, 2 hard)
  // ============================================================

  {
    id: 'swift-optional-001',
    category: 'Optional Handling',
    difficulty: 'easy',
    title: 'Optional Binding with if let',
    text: 'Safely unwrap the optional name using if let.',
    setup: 'let name: String? = "Alice"',
    setupCode: 'let name: String? = "Alice"',
    expected: 'Alice',
    sample: 'if let unwrapped = name { print(unwrapped) }',
    hints: [
      'if let creates a new constant with the unwrapped value',
      'Code inside the block only runs if optional has a value',
    ],
    validPatterns: [/if\s+let\s+\w+\s*=\s*name/],
    tags: ['if let', 'optional', 'unwrap'],
  },

  {
    id: 'swift-optional-002',
    category: 'Optional Handling',
    difficulty: 'easy',
    title: 'Guard Let for Early Exit',
    text: 'Use guard let to unwrap the optional and exit early if nil.',
    setup: 'let age: Int? = 25',
    setupCode: 'let age: Int? = 25',
    expected: 25,
    sample: 'guard let validAge = age else { return }',
    hints: [
      'guard let requires an else clause with exit',
      'The unwrapped value is available after the guard',
    ],
    validPatterns: [/guard\s+let\s+\w+\s*=\s*age\s+else/],
    tags: ['guard let', 'optional', 'early exit'],
  },

  {
    id: 'swift-optional-003',
    category: 'Optional Handling',
    difficulty: 'easy',
    title: 'Nil Coalescing Operator',
    text: 'Provide a default value of "Unknown" if the name is nil.',
    setup: 'let name: String? = nil',
    setupCode: 'let name: String? = nil',
    expected: 'Unknown',
    sample: 'name ?? "Unknown"',
    hints: [
      '?? is the nil coalescing operator',
      'Returns the left value if non-nil, otherwise the right',
    ],
    validPatterns: [/name\s*\?\?\s*"Unknown"/],
    tags: ['nil coalescing', 'optional', 'default'],
  },

  {
    id: 'swift-optional-004',
    category: 'Optional Handling',
    difficulty: 'easy',
    title: 'Optional Chaining',
    text: 'Safely access the count property of an optional string.',
    setup: 'let message: String? = "Hello"',
    setupCode: 'let message: String? = "Hello"',
    expected: 5,
    sample: 'message?.count',
    hints: ['?. is optional chaining', 'Returns nil if the optional is nil'],
    validPatterns: [/message\?\s*\.count/],
    tags: ['optional chaining', 'optional', 'safe access'],
  },

  {
    id: 'swift-optional-005',
    category: 'Optional Handling',
    difficulty: 'medium',
    title: 'Force Unwrap',
    text: 'Force unwrap the optional to get its value (when you are certain it has a value).',
    setup: 'let number: Int? = 42',
    setupCode: 'let number: Int? = 42',
    expected: 42,
    sample: 'number!',
    hints: ['! force unwraps an optional', 'Crashes if the optional is nil - use with caution'],
    validPatterns: [/number!/],
    tags: ['force unwrap', 'optional', 'unwrap'],
  },

  {
    id: 'swift-optional-006',
    category: 'Optional Handling',
    difficulty: 'medium',
    title: 'Optional Map',
    text: 'Transform the optional value by doubling it if present.',
    setup: 'let number: Int? = 5',
    setupCode: 'let number: Int? = 5',
    expected: 10,
    sample: 'number.map { $0 * 2 }',
    hints: ['map transforms the value if present', 'Returns nil if the optional is nil'],
    validPatterns: [/\.map\s*\{.*\*\s*2.*\}/],
    tags: ['map', 'optional', 'transform'],
  },

  {
    id: 'swift-optional-007',
    category: 'Optional Handling',
    difficulty: 'medium',
    title: 'Optional FlatMap',
    text: 'Parse an optional string to an optional integer.',
    setup: 'let numString: String? = "42"',
    setupCode: 'let numString: String? = "42"',
    expected: 42,
    sample: 'numString.flatMap { Int($0) }',
    hints: [
      'flatMap unwraps nested optionals',
      'Useful when the transform also returns an optional',
    ],
    validPatterns: [/\.flatMap\s*\{.*Int\s*\(\s*\$0\s*\).*\}/],
    tags: ['flatMap', 'optional', 'flatten'],
  },

  {
    id: 'swift-optional-008',
    category: 'Optional Handling',
    difficulty: 'medium',
    title: 'Chained Optional Binding',
    text: 'Unwrap multiple optionals in a single if let statement.',
    setup: 'let firstName: String? = "John"\nlet lastName: String? = "Doe"',
    setupCode: 'let firstName: String? = "John"\nlet lastName: String? = "Doe"',
    expected: 'John Doe',
    sample: 'if let first = firstName, let last = lastName { "\\(first) \\(last)" }',
    hints: [
      'Chain multiple if let conditions with commas',
      'All must be non-nil for the block to execute',
    ],
    validPatterns: [/if\s+let\s+\w+\s*=\s*firstName\s*,\s*let\s+\w+\s*=\s*lastName/],
    tags: ['if let', 'optional', 'chaining'],
  },

  {
    id: 'swift-optional-009',
    category: 'Optional Handling',
    difficulty: 'hard',
    title: 'Nested Optional Chaining',
    text: 'Safely access a deeply nested optional property.',
    setup:
      'struct Address { var city: String? }\nstruct Person { var address: Address? }\nlet person: Person? = Person(address: Address(city: "NYC"))',
    setupCode:
      'struct Address { var city: String? }\nstruct Person { var address: Address? }\nlet person: Person? = Person(address: Address(city: "NYC"))',
    expected: 'NYC',
    sample: 'person?.address?.city',
    hints: [
      'Chain multiple ?. for nested optionals',
      'Returns nil if any part of the chain is nil',
    ],
    validPatterns: [/person\?\s*\.address\?\s*\.city/],
    tags: ['optional chaining', 'optional', 'nested'],
  },

  {
    id: 'swift-optional-010',
    category: 'Optional Handling',
    difficulty: 'hard',
    title: 'Optional with Condition',
    text: 'Unwrap the optional and only proceed if the value is greater than 10.',
    setup: 'let number: Int? = 15',
    setupCode: 'let number: Int? = 15',
    expected: 15,
    sample: 'if let num = number, num > 10 { num }',
    hints: [
      'Add conditions after optional binding with commas',
      'Conditions are checked after successful unwrap',
    ],
    validPatterns: [/if\s+let\s+\w+\s*=\s*number\s*,\s*\w+\s*>\s*10/],
    tags: ['if let', 'optional', 'condition'],
  },
];

export default swiftProblems;
