import type { Meta, StoryObj } from '@storybook/nextjs-vite';
import { Breadcrumb } from '../components/Breadcrumb';

const meta = {
  title: 'Navigation/Breadcrumb',
  component: Breadcrumb,
  parameters: {
    layout: 'padded',
    backgrounds: {
      default: 'dark',
      values: [
        { name: 'dark', value: '#0a0a0f' },
        { name: 'light', value: '#ffffff' },
      ],
    },
    nextjs: {
      appDirectory: true,
      navigation: {
        pathname: '/quiz/javascript/arrays',
      },
    },
  },
  tags: ['autodocs'],
} satisfies Meta<typeof Breadcrumb>;

export default meta;
type Story = StoryObj<typeof meta>;

const homeIcon = (
  <svg
    className="w-4 h-4"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
    strokeWidth={2}
    aria-hidden="true"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
    />
  </svg>
);

const codeIcon = (
  <svg
    className="w-4 h-4"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
    strokeWidth={2}
    aria-hidden="true"
  >
    <path strokeLinecap="round" strokeLinejoin="round" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
  </svg>
);

const bookIcon = (
  <svg
    className="w-4 h-4"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
    strokeWidth={2}
    aria-hidden="true"
  >
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"
    />
  </svg>
);

// Default auto-generated breadcrumb from pathname
export const Default: Story = {
  args: {
    autoGenerate: true,
  },
};

// Two levels deep
export const TwoLevels: Story = {
  args: {
    items: [{ label: 'Home', href: '/' }, { label: 'Quiz Mode' }],
  },
};

// Three levels deep
export const ThreeLevels: Story = {
  args: {
    items: [
      { label: 'Home', href: '/' },
      { label: 'Quiz Mode', href: '/quiz' },
      { label: 'JavaScript' },
    ],
  },
};

// Deep nesting that triggers truncation
export const DeepNesting: Story = {
  args: {
    items: [
      { label: 'Home', href: '/' },
      { label: 'Frontend Drills', href: '/frontend-drills' },
      { label: 'UI Patterns', href: '/frontend-drills/ui-patterns' },
      { label: 'React', href: '/frontend-drills/ui-patterns/react' },
      { label: 'Modal Dialog', href: '/frontend-drills/ui-patterns/react/modal-dialog' },
      { label: 'Implementation' },
    ],
    maxItems: 4,
  },
};

// With icons on breadcrumb items
export const WithIcons: Story = {
  args: {
    items: [
      { label: 'Home', href: '/', icon: homeIcon },
      { label: 'JavaScript', href: '/javascript', icon: codeIcon },
      { label: 'Reference', icon: bookIcon },
    ],
  },
};

// Maximum items before truncation kicks in
export const MaxItems: Story = {
  args: {
    items: [
      { label: 'Home', href: '/' },
      { label: 'Drill Mode', href: '/drill' },
      { label: 'TypeScript', href: '/drill/typescript' },
      { label: 'Arrays' },
    ],
    maxItems: 4,
  },
};

// Single item (just Home)
export const SingleItem: Story = {
  args: {
    items: [{ label: 'Home' }],
  },
};

// With long labels that get truncated
export const LongLabels: Story = {
  args: {
    items: [
      { label: 'Home', href: '/' },
      { label: 'Frontend Development Drills', href: '/frontend-drills' },
      { label: 'Advanced UI Design Patterns', href: '/frontend-drills/ui-patterns' },
      { label: 'Interactive Modal Dialog Component' },
    ],
  },
};

// Auto-generated from a frontend-drills path
export const AutoGeneratedFrontend: Story = {
  parameters: {
    nextjs: {
      appDirectory: true,
      navigation: {
        pathname: '/frontend-drills/ui-patterns/react',
      },
    },
  },
  args: {
    autoGenerate: true,
  },
};

// Auto-generated from a drill path
export const AutoGeneratedDrill: Story = {
  parameters: {
    nextjs: {
      appDirectory: true,
      navigation: {
        pathname: '/drill/typescript/arrays',
      },
    },
  },
  args: {
    autoGenerate: true,
  },
};

// All variants displayed together
export const AllVariants: Story = {
  render: () => (
    <div className="space-y-6 max-w-xl">
      <div>
        <p className="text-xs text-zinc-500 mb-2">Single item</p>
        <Breadcrumb items={[{ label: 'Home' }]} />
      </div>
      <div>
        <p className="text-xs text-zinc-500 mb-2">Two levels</p>
        <Breadcrumb items={[{ label: 'Home', href: '/' }, { label: 'Quiz Mode' }]} />
      </div>
      <div>
        <p className="text-xs text-zinc-500 mb-2">Three levels</p>
        <Breadcrumb
          items={[
            { label: 'Home', href: '/' },
            { label: 'Quiz Mode', href: '/quiz' },
            { label: 'JavaScript' },
          ]}
        />
      </div>
      <div>
        <p className="text-xs text-zinc-500 mb-2">With icons</p>
        <Breadcrumb
          items={[
            { label: 'Home', href: '/', icon: homeIcon },
            { label: 'JavaScript', href: '/javascript', icon: codeIcon },
            { label: 'Reference', icon: bookIcon },
          ]}
        />
      </div>
      <div>
        <p className="text-xs text-zinc-500 mb-2">Deep nesting (truncated, maxItems=4)</p>
        <Breadcrumb
          items={[
            { label: 'Home', href: '/' },
            { label: 'Frontend Drills', href: '/frontend-drills' },
            { label: 'UI Patterns', href: '/frontend-drills/ui-patterns' },
            { label: 'React', href: '/frontend-drills/ui-patterns/react' },
            {
              label: 'Modal Dialog',
              href: '/frontend-drills/ui-patterns/react/modal-dialog',
            },
            { label: 'Implementation' },
          ]}
          maxItems={4}
        />
      </div>
      <div>
        <p className="text-xs text-zinc-500 mb-2">Long labels</p>
        <Breadcrumb
          items={[
            { label: 'Home', href: '/' },
            { label: 'Frontend Development Drills', href: '/frontend-drills' },
            { label: 'Advanced UI Design Patterns' },
          ]}
        />
      </div>
    </div>
  ),
};
